@echo off
alchemy All.bmp      ..\All.bmp       -w0 -o -f..\palety.pal
alchemy Close.bmp    ..\Close.bmp     -w0 -o -f..\palety.pal
alchemy Color.bmp    ..\Color.bmp     -w0 -o -f..\palety.pal
alchemy Color_en.bmp ..\Color_en.bmp  -w0 -o -f..\palety.pal
alchemy Copy.bmp     ..\Copy.bmp      -w0 -o -f..\palety.pal
alchemy Cut.bmp      ..\Cut.bmp       -w0 -o -f..\palety.pal
alchemy DefIcon.bmp  ..\DefIcon.bmp   -w0 -o -f..\palety.pal
alchemy DefTxt.bmp   ..\DefTxt.bmp    -w0 -o -f..\palety.pal
alchemy Dekl.bmp     ..\Dekl.bmp      -w0 -o -f..\palety.pal
alchemy DeklNext.bmp ..\DeklNext.bmp  -w0 -o -f..\palety.pal
alchemy DeklPrev.bmp ..\DeklPrev.bmp  -w0 -o -f..\palety.pal
alchemy Del.bmp      ..\Del.bmp       -w0 -o -f..\palety.pal
alchemy Dith1.bmp    ..\Dith1.bmp     -w0 -o -f..\palety.pal
alchemy Dith2.bmp    ..\Dith2.bmp     -w0 -o -f..\palety.pal
alchemy EditBlok.bmp ..\EditBlok.bmp  -w0 -o -f..\palety.pal
alchemy EditBox.bmp  ..\EditBox.bmp   -w0 -o -f..\palety.pal
alchemy EditBox2.bmp ..\EditBox2.bmp  -w0 -o -f..\palety.pal
alchemy EditCirc.bmp ..\EditCirc.bmp  -w0 -o -f..\palety.pal
alchemy EditElip.bmp ..\EditElip.bmp  -w0 -o -f..\palety.pal
alchemy EditFill.bmp ..\EditFill.bmp  -w0 -o -f..\palety.pal
alchemy EditIcon.bmp ..\EditIcon.bmp  -w0 -o -f..\palety.pal
alchemy EditI_en.bmp ..\EditI_en.bmp  -w0 -o -f..\palety.pal
alchemy EditKoul.bmp ..\EditKoul.bmp  -w0 -o -f..\palety.pal
alchemy EditKruh.bmp ..\EditKruh.bmp  -w0 -o -f..\palety.pal
alchemy EditLine.bmp ..\EditLine.bmp  -w0 -o -f..\palety.pal
alchemy EditLn01.bmp ..\EditLn01.bmp  -w0 -o -f..\palety.pal
alchemy EditLn02.bmp ..\EditLn02.bmp  -w0 -o -f..\palety.pal
alchemy EditLn05.bmp ..\EditLn05.bmp  -w0 -o -f..\palety.pal
alchemy EditLn09.bmp ..\EditLn09.bmp  -w0 -o -f..\palety.pal
alchemy EditLn21.bmp ..\EditLn21.bmp  -w0 -o -f..\palety.pal
alchemy EditLog0.psd ..\EditLog0.bmp  -w0 -o -f..\palety.pal
alchemy EditLog1.psd ..\EditLog1.bmp  -w0 -o -f..\palety.pal
alchemy EditL0en.psd ..\EditL0en.bmp  -w0 -o -f..\palety.pal
alchemy EditL1en.psd ..\EditL1en.bmp  -w0 -o -f..\palety.pal
alchemy EditNum.psd  ..\EditNum.bmp   -w0 -o -f..\palety.pal
alchemy EditN_en.psd ..\EditN_en.bmp  -w0 -o -f..\palety.pal
alchemy Editor.bmp   ..\Editor.bmp    -w0 -o -f..\palety.pal
alchemy Edit_en.bmp  ..\Edit_en.bmp   -w0 -o -f..\palety.pal
alchemy EditOval.bmp ..\EditOval.bmp  -w0 -o -f..\palety.pal
alchemy EditPen.bmp  ..\EditPen.bmp   -w0 -o -f..\palety.pal
alchemy EditPipe.bmp ..\EditPipe.bmp  -w0 -o -f..\palety.pal
alchemy EditSnd.psd  ..\EditSnd.bmp   -w0 -o -f..\palety.pal
alchemy EditS_en.psd ..\EditS_en.bmp  -w0 -o -f..\palety.pal
alchemy EditSpr.psd  ..\EditSpr.bmp   -w0 -o -f..\palety.pal
alchemy EditP_en.psd ..\EditP_en.bmp  -w0 -o -f..\palety.pal
alchemy EditSpry.bmp ..\EditSpry.bmp  -w0 -o -f..\palety.pal
alchemy EditText.bmp ..\EditText.bmp  -w0 -o -f..\palety.pal
alchemy EditT_en.bmp ..\EditT_en.bmp  -w0 -o -f..\palety.pal
alchemy EditTxt.bmp  ..\EditTxt.bmp   -w0 -o -f..\palety.pal
alchemy Find.bmp     ..\Find.bmp      -w0 -o -f..\palety.pal
alchemy FindNext.bmp ..\FindNext.bmp  -w0 -o -f..\palety.pal
alchemy FindPrev.bmp ..\FindPrev.bmp  -w0 -o -f..\palety.pal
alchemy HistNext.bmp ..\HistNext.bmp  -w0 -o -f..\palety.pal
alchemy HistPrev.bmp ..\HistPrev.bmp  -w0 -o -f..\palety.pal
alchemy Icon.bmp     ..\Icon.bmp      -w0 -o -f..\palety.pal
alchemy Klavesy.bmp  ..\Klavesy.bmp   -w0 -o -f..\palety.pal
alchemy Klav_en.bmp  ..\Klav_en.bmp   -w0 -o -f..\palety.pal
alchemy Lock.bmp     ..\Lock.bmp      -w0 -o -f..\palety.pal
alchemy Loop.bmp     ..\Loop.bmp      -w0 -o -f..\palety.pal
alchemy Main.bmp     ..\Main.bmp      -w0 -o -f..\palety.pal
alchemy Map1.bmp     ..\Map1.bmp      -w0 -o -f..\palety.pal
alchemy Map2.bmp     ..\Map2.bmp      -w0 -o -f..\palety.pal
alchemy Map3.bmp     ..\Map3.bmp      -w0 -o -f..\palety.pal
alchemy Map4.bmp     ..\Map4.bmp      -w0 -o -f..\palety.pal
alchemy Map5.bmp     ..\Map5.bmp      -w0 -o -f..\palety.pal
alchemy MapEdit.bmp  ..\MapEdit.bmp   -w0 -o -f..\palety.pal
alchemy MapFill.bmp  ..\MapFill.bmp   -w0 -o -f..\palety.pal
alchemy MapN1.bmp    ..\MapN1.bmp     -w0 -o -f..\palety.pal
alchemy MapN2.bmp    ..\MapN2.bmp     -w0 -o -f..\palety.pal
alchemy MapN3.bmp    ..\MapN3.bmp     -w0 -o -f..\palety.pal
alchemy MapPic.bmp   ..\MapPic.bmp    -w0 -o -f..\palety.pal
alchemy New.bmp      ..\New.bmp       -w0 -o -f..\palety.pal
alchemy NewDir.bmp   ..\NewDir.bmp    -w0 -o -f..\palety.pal
alchemy Next.bmp     ..\Next.bmp      -w0 -o -f..\palety.pal
alchemy Off.bmp      ..\Off.bmp       -w0 -o -f..\palety.pal
alchemy Open.bmp     ..\Open.bmp      -w0 -o -f..\palety.pal
alchemy Otisk.bmp    ..\Otisk.bmp     -w0 -o -f..\palety.pal
alchemy Paste.bmp    ..\Paste.bmp     -w0 -o -f..\palety.pal
alchemy Petr.bmp     ..\Petr.bmp      -w0 -o -f..\palety.pal
alchemy PicDim.bmp   ..\PicDim.bmp    -w0 -o -f..\palety.pal
alchemy PicDim2.bmp  ..\PicDim2.bmp   -w0 -o -f..\palety.pal
alchemy PicD2_en.bmp ..\PicD2_en.bmp  -w0 -o -f..\palety.pal
alchemy PicKonv.bmp  ..\PicKonv.bmp   -w0 -o -f..\palety.pal
alchemy PicKonv2.bmp ..\PicKonv2.bmp  -w0 -o -f..\palety.pal
alchemy PicK2_en.bmp ..\PicK2_en.bmp  -w0 -o -f..\palety.pal
alchemy PicKonv3.bmp ..\PicKonv3.bmp  -w0 -o -f..\palety.pal
alchemy PicK3_en.bmp ..\PicK3_en.bmp  -w0 -o -f..\palety.pal
alchemy Play.bmp     ..\Play.bmp      -w0 -o -f..\palety.pal
alchemy Pokus4.bmp   ..\Pokus4.bmp    -w0 -o -f..\palety.pal
alchemy Pokus6.bmp   ..\Pokus6.bmp    -w0 -o -f..\palety.pal
alchemy Pok4_en.bmp  ..\Pok4_en.bmp   -w0 -o -f..\palety.pal
alchemy Pok6_en.bmp  ..\Pok6_en.bmp   -w0 -o -f..\palety.pal
alchemy Prev.bmp     ..\Prev.bmp      -w0 -o -f..\palety.pal
alchemy Pause.bmp    ..\Pause.bmp     -w0 -o -f..\palety.pal
alchemy Rastr.bmp    ..\Rastr.bmp     -w0 -o -f..\palety.pal
alchemy Record.bmp   ..\Record.bmp    -w0 -o -f..\palety.pal
alchemy Redo.bmp     ..\Redo.bmp      -w0 -o -f..\palety.pal
alchemy Rename.bmp   ..\Rename.bmp    -w0 -o -f..\palety.pal
alchemy Save.bmp     ..\Save.bmp      -w0 -o -f..\palety.pal
alchemy Sourad.bmp   ..\Sourad.bmp    -w0 -o -f..\palety.pal
alchemy SprSet.bmp   ..\SprSet.bmp    -w0 -o -f..\palety.pal
alchemy SprSet2.bmp  ..\SprSet2.bmp   -w0 -o -f..\palety.pal
alchemy SprS2en.bmp  ..\SprS2en.bmp   -w0 -o -f..\palety.pal
alchemy SprTest.bmp  ..\SprTest.bmp   -w0 -o -f..\palety.pal
alchemy Start.bmp    ..\Start.bmp     -w0 -o -f..\palety.pal
alchemy Stop.bmp     ..\Stop.bmp      -w0 -o -f..\palety.pal
alchemy Strukt.bmp   ..\Strukt.bmp    -w0 -o -f..\palety.pal
alchemy Struk_en.bmp ..\Struk_en.bmp  -w0 -o -f..\palety.pal
alchemy TreeClos.bmp ..\TreeClos.bmp  -w0 -o -f..\palety.pal
alchemy TreeDef.bmp  ..\TreeDef.bmp   -w0 -o -f..\palety.pal
alchemy TreeEqu.bmp  ..\TreeEqu.bmp   -w0 -o -f..\palety.pal
alchemy TreeNSet.bmp ..\TreeNSet.bmp  -w0 -o -f..\palety.pal
alchemy TreeOpen.bmp ..\TreeOpen.bmp  -w0 -o -f..\palety.pal
alchemy TreeSet.bmp  ..\TreeSet.bmp   -w0 -o -f..\palety.pal
alchemy Undo.bmp     ..\Undo.bmp      -w0 -o -f..\palety.pal
alchemy Vrstvy.bmp   ..\Vrstvy.bmp    -w0 -o -f..\palety.pal
alchemy Vrstv_en.bmp ..\Vrstv_en.bmp  -w0 -o -f..\palety.pal
alchemy Vybarv11.bmp ..\Vybarv11.bmp  -w0 -o -f..\palety.pal
alchemy Vybarv20.bmp ..\Vybarv20.bmp  -w0 -o -f..\palety.pal
alchemy Vyb20_en.bmp ..\Vyb20_en.bmp  -w0 -o -f..\palety.pal
alchemy Vyb11_en.bmp ..\Vyb11_en.bmp  -w0 -o -f..\palety.pal
alchemy Vyber.bmp    ..\Vyber.bmp     -w0 -o -f..\palety.pal
alchemy Vyber_en.bmp ..\Vyber_en.bmp  -w0 -o -f..\palety.pal
alchemy ZoomIn.bmp   ..\ZoomIn.bmp    -w0 -o -f..\palety.pal
alchemy ZoomOut.bmp  ..\ZoomOut.bmp   -w0 -o -f..\palety.pal
