// Maïarsky (Hungarian)
// 1250
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Globális változók és függvények",																	// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Lokális változók és függvények",																	// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Alap elemek, szemétkosár",																			// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Változók és függvények könyvtára",																	// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"Alap változók és függvények",																		// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Új program",																						// implicitní název nového programu
IDN_NEWDIR_NAME,			"Új alkönyvtár",																					// implicitní název nové sloky
IDN_TEXTVZOR,				"[példák]",																							// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Használva",																						// zobrazuje poèet pouití prvku
IDT_RADEK,					"sor",																								// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"oszlop",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"bekapcsolva",																						// text editoru hodnoty pøepínaèe
IDN_DATUM,					"dátum",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"idõ",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"méret",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"szabad",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"ismétlés",																							// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"Ismételve",																						// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMO",																								// oznaèení DEMO verze
IDN_PROFI,					"Professional",																						// oznaèení verze Professional
IDN_LITE,					"Lite",																								// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Fájl",																							// volba k vyvolání menu "Soubor"
IDN_START0,					"&Futtatás\tF5",																					// volba pro spuštìní programu
IDN_START,					"Futtatja a programot.\nFuttatás",																	// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Megnyit\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Megnyitja a programot szerkesztésre.\nMegnyit",													// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"Ú&j...\tCtrl+N",																					// volba pro zaloení nového programu
IDN_NEW,					"Kialakít egy új programot.\nÚj",																	// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"Átn&evez...\tAlt+Enter",																			// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Átnevezi a program/alkönyvtár nevét (nem lehetséges átnevezni a példa programokat és alkönyvtárakat).\nÁtnevez",	// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"Má&sol...\tCtrl+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Másolja a kijelölt programot és más nével menti el.\nMásol",										// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"Új &alkönyvtár...\tCtrl+P",																		// volba k vytvoøení nové sloky
IDN_PATH,					"Kialakít egy új alkönyvtárat a programok számára.\nÚj alkönyvtár",									// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Töröl...\tDelete",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Törli a programot vagy az alkönyvtárat (nem lehetséges törölni a példa programokat és alkönyvtárakat).\nTöröl",	// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"&Rövid nevek",																						// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"A programok/alkönyvtárak nevei 8 karakter hosszúságban lesznek kialakítva.\nRövid nevek",			// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Kilépés\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Kilép a Peter nevû programból.\nKilépés",															// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"&Betû",																							// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"&Betû a program kijelöléshez...",																	// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Beállítja a betû formátumot a program kijelölési ablakban.\nBetû a program kijelöléshez",			// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"&A szerkesztõ betû formátuma...",																	// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Beállítja a szerkesztõ ablak betû formátumát.\nA szerkesztõ betû formátuma",						// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"&Szövegszerkesztõ betû típusa...",																	// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Beállítja a szövegszerkesztõ betû formátumát.\nSzövegszerkesztõ betû típusa",						// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"&Menü betû formátuma...",																			// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Beállítja a menü betûformátumát.\nMenü betû formátuma",											// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Á&llapotsor betû formátuma...",																	// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Beállítja az állapotsor betû formátumát.\nÁllapotsor betû formátuma",								// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&Nyelv",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automatikus nyelv",																				// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Automatikusan kiválasztja a nyelvet a operációs rendszer beállításai alapján.\nAutomatikus nyelv",	// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Elõzõ nyelv\tCtrl+F9",																			// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Átkapcsol a két legutoljára használt nyelv között.\nElõzõ nyelv",									// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Bolgárul (Bulgarija)",																				// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Átkapcsolja a Peter programot bolgár nyelvre.\nBolgárul",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"&Csehül (Cesky)",																					// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Átkapcsolja a Peter programot cseh nyelvre.\nCsehül",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"&Dánul (Danmark)",																					// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Átkapcsolja a Peter programot dán nyelvre.\nDánul",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"&Németül (Deutsch)",																				// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Átkapcsolja a Peter programot német nyelvre.\nNémetül",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Görögül (Hellás)",																					// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Átkapcsolja a Peter programot görög nyelvre.\nGörögül",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"An&golul (English)",																				// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Átkapcsolja a Peter programot angol nyelvre.\nAngol",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"&Spanyolul (España)",																				// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Átkapcsolja a Peter programot spanyol nyelvre.\nSpanyolul",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finnül (Finland)",																					// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Átkapcsolja a Peter programot finn nyelvre.\nFinnül",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"&Franciául (France)",																				// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Átkapcsolja a Peter programot francia nyelvre.\nFranciául",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"Magyarul",																							// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Átkapcsolja a Peter programot átkapcsolja a programot magyar nyelvre.\nMagyarul",					// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Izlandiul (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Átkapcsolja a Peter programot izlandi nyelvre.\nIzlandiul",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Olaszul (Italy)",																					// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Átkapcsolja a Peter programot olasz nyelvre.\nOlaszul",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Hollandul (Nederland)",																			// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Átkapcsolja a Peter programot holland nyelvre.\nHollandul",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Norvégul (Norge)",																					// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Átkapcsolja a Peter programot norvég nyelvre.\nNorvégul",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Lengyelül (Po polsku)",																			// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Átkapcsolja a Peter programot lengyel nyelvre.\nLengyelül",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portugálul (Portugal)",																			// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Átkapcsolja a Peter programot portugál nyelvre.\nPortugálul",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Románul (România)",																				// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Átkapcsolja a Peter programot román nyevre.\nRománul",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&Oroszul (Po-rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Átkapcsolja a Peter programot orosz nyelvre.\nOroszul",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Szerb-horvátul (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Átkapcsolja a Peter programot szerb-horvát nyelvre.\nSzerb-horvátul",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"S&zlovákul (Po slovensky)",																		// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Átkapcsolja a Peter programot szlovák nyelvre.\nSzlovákul",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albánul (Shqipërisë)",																				// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Átkapcsolja a Peter programot albán nyelvre.\nAlbánul",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Svédül (Swerige)",																					// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Átkapcsolja a Peter programot svéd nyelvre.\nSvédül",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Törökül (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Átkapcsolja a Peter programot török nyelvre.\nTörökül",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"&Vietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Segítség",																						// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Segítség\tF1",																					// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Megjeleníti a segítséget a kiválasztott elemhez.\nSegítség",										// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"&A segítség témákörei",																			// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Megjeleníti a segítség témaköreit.\nA segítség témákörei",											// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Keress a segítségben",																			// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Keres a segítségben.\nKeress a segítségben",														// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"A &Peter programról",																				// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Megjeleníti az információkat a Peter programról, verzió számot és a szerzõi jogokat.\nA Peter programról",	// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"Be&zár\tCtrl+O",																					// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Bezárja a szerkesztett programot és kinyit egy másikat.\nBezár",									// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Elment\tCtrl+S",																					// volba k uloení programu pøi editaci
IDN_SAVE,					"Elmenti a változásokat a programban.\nElment",														// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"E&lment nem futtatható állapotban\tCtrl+Alt+S",													// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Elmenti a programot nem futtatható állapotban (kisebb méret).\nElment nem futtatható állapotban",	// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"El&ment új néven...\tCtrl+Shift+S",																// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Elmenti a programot egy új néven vagy egy másik lemezre.\nElment új néven",						// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Disztribúció...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Elment egy disztribúciós, nem szerkeszthetõ verziót a programról (csak a Professional licenció esetében).\nDisztribúció",	// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"&Export...",																						// volba k exportování programu
IDN_EXPORT,					"Exportálja a programot szöveges formába.\nExport",													// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Importálja a programot szöveges formából.\nImport",												// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"S&zerkesztés",																						// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Visszavonás\tCtrl+Z",																				// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Visszavonja az elõbbi változtatást.\nVisszavonás",													// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Ismétlés\tCtrl+Y",																				// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Ismételten végrehajtja az elõtte visszavont változtatást.\nIsmétlés",								// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"&Kivág\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Kivágja a kiválasztott részt és a vágótáblára menti.\nKivág",										// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Másol\tCtrl+C",																					// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Másolja a kijelölt részt a vágótáblára.\nMásol",													// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"&Beilleszt\tCtrl+V",																				// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Behelyezi a vágótábla tartalmát az aktuális pozícióra.\nBeilleszt",								// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Töröl\tDelete",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Törli a kiválasztott részt.\nTöröl",																// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Kivál&aszt mindent\tCtrl+A",																		// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Kiválaszt mindent.\nKiválaszt mindent",															// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Képek behozatalánál és méret csökkentésüknél ditheringet használ.\nDithering",						// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Nézet",																							// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"&Közelít\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Felnagyítja a megjelenítés mértékét.\nKözelít",													// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"&Távolítt\tCtrl+[-]",																				// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Lecsökkenti a megjelenítés mértékét.\nTávolít",													// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"&Elõzõ szerkesztés\tCtrl+fel",																		// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Visszatér az elõzõ szerkesztett elemhez.\nElõzõ szerkesztés",										// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"Kö&vetkezõ szerkesztés\tCtrl+le",																	// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Visszatér a következõ szerkesztett elemhez.\nKövetkezõ szerkesztés",								// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Szöveg keresése...\tCtrl+F",																		// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Megkeresi a megadott szöveget.\nSzöveg keresése",													// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"E&lõzõ szöveg\tShift+F3",																			// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Megkeresi a szöveg elõzõ helyzetét.\nElõzõ szöveg",												// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"Követke&zõ szöveg\tF3",																			// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Megkeresi a szöveg következõ helyzetét.\nKövetkezõ szöveg",										// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Program",																							// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Lezár",																							// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Lezárja az elemet a változtatás elõl.\nLezár",														// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Kikapcsol",																						// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Kikapcsolja az elem üzemelését.\nKikapcsol",														// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"L&eírás\tAlt+Enter",																				// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Szerkeszti az elem leírását.\nLeírás",																// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"&Implicit leírás",																					// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Felhasználja az elem implicit leírását.\nImplicit leírás",											// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"Ik&on",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Szerkeszti az elem ikonját.\nIkon",																// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Implicit iko&n",																					// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Felhasználja az elem implicit ikonját.\nImplicit ikon",											// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"&Deklaráció",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Megkeresi az elem deklarációját.\nDeklaráció",														// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"Elõ&zõ használat",																					// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Megkeresi az elem elõzõ felhasználásának helyzetét.\nElõzõ használat",								// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"Kö&vetkezõ használat",																				// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Megkeresi az elem következõ felhasználásának helyzetét.\nKövetkezõ használat",						// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Kép",																								// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"&Méretek...",																						// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Beállítja a kép teljes méreteit.\nMéretek",														// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Rács",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Az orientációs rács ki/bekapcsolása.\nRács",														// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"&Szerkesztés...",																					// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Szerkeszti a képet (méret változás, forgatás, színek).\nSzerkesztés",								// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Blokk lenyomat",																					// volba k otisku bloku do obrázku
IDN_OTISK,					"A blokkot képbe nyomja.\nBlokk lenyomat",															// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Vízszintessen",																					// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Vízszintessen megfordítja a képet vagy egy részét.\nVízszintessen",								// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Függõlegesen",																					// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Függõlegesen megfordítja a képet vagy egy részét.\nFüggõlegesen",									// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"B&alra",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Megfordítja a képet balra (90 fokkal az óramutató járásával ellentétes irányban).\nBalra",			// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"&Jobbra",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Megfordítja a képet jobbra (90 fokkal az óramutató járásának irányában).\nJobbra",					// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"&Kétszeres",																						// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Megnöveli a kép vagy annak egy részének méretét a kétszeresre .\nKétszeres",						// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"Fé&l",																								// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Csökkenti a kép vagy annak egy részének méretét a felére.\nFél",									// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"Mér&et...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Beállítja a kép vagy annak egy részének méretét választhatóan.\nMéret",							// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"&Csere",																							// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Felcseréli a képben vagy annak egy részében az egér bal és jobb nyomógombjának színeit.\nCsere",	// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Helyetesít",																						// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Helyetesíti a képben vagy annak egy részében az egér jobb nyomógombjának színét a ball színével.\nHelyetesít",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Eszközök",																						// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Toll",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Tollal rajzol.\nToll",																				// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"&Vonal",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Vonalat rajzol.\nVonal",																			// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"Ü&res téglalap",																					// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Üres téglalapot rajzol.\nÜres téglalap",															// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"&Kitöltött téglalap",																				// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Kitöltött téglalapot rajzol.\nKitöltött téglalap",													// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"Ür&es kör",																						// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Üres kört rajzol.\nÜres kör",																		// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"K&itöltött kör",																					// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Kitöltött kört rajzol.\nKitöltött kör",															// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"E&llipszis",																						// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Ellipszist rajzol.\nEllipszis",																	// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"Kitöltött elli&pszis",																				// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Kitöltött ellipszist rajzol.\nKitöltött ellipszis",												// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"&Gömb",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Gömböt rajzol.\nGömb",																				// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"Ki&jelöl",																							// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Megjelöli a kiválasztott részt.\nKijelöl",															// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"&Festékszóró",																						// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Festékszóróval rajzol.\nFestékszóró",																// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"Pipett&a",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Beállítja a kurzor alatt helyezkedõ színt mint kiválasztottat.\nPipetta",							// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"Kitölté&s",																						// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Kitölti a kiválasztott színnel a felületet .\nKitöltés",											// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"S&zövegíró",																						// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Szöveget ír.\nSzövegíró",																			// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Vastagság",																						// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Vonal vastagság &1 pixel",																			// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"1 pixel vastagságú vonalat rajzol.\nVonal vastagság 1 pixel",										// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Vonal vastagság &2 pixel",																			// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"2 pixel vastagságú vonalat rajzol.\nVonal vastagság 2 pixel",										// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Vonal vastagság &5 pixel",																			// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"5 pixel vastagságú vonalat rajzol.\nVonal vastagság 5 pixel",										// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Vonal vastagság &9 pixel",																			// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"9 pixel vastagságú vonalat rajzol.\nVonal vastagság 9 pixel",										// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Vonal vastagság 21 &pixel",																		// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"21 pixel vastagságú vonalat rajzol.\nVonal vastagság 21 pixel",									// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"F&elület",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Szerkesztés",																						// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Ki/bekapcsolja a felület szerkesztési módját.\nSzerkesztés",										// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Kitöltés",																						// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Ki/bekapcsolja a felület elemmel való kitöltési módját.\nKitöltés",								// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"M&ezõk",																							// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Szerkeszti a mezõket a felületen.\nMezõk",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Kapcsoló &1",																						// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Szerkeszti a kapcsoló 1-et.\nKapcsoló 1",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Kapcsoló &2",																						// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Szerkeszti a kapcsoló 2-õt.\nKapcsoló 2",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Kapcsoló &3",																						// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Szerkeszti a kapcsoló 3-at.\nKapcsoló 3",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Kapcsoló &4",																						// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Szerkeszti a kapcsoló 4-et.\nKapcsoló 4",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Kapcsoló &5",																						// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Szerkeszti a kapcsoló 5-öt.\nKapcsoló 5",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"Szám &változó 1",																					// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Szerkeszti a szám változó 1 értékét (érték 0-tól 1023-ig).\nSzám változó 1",						// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"Szám vál&tozó 2",																					// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Szerkeszti a szám változó 2 értékét (érték 0-tól 1023-ig).\nSzám változó 2",						// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Szám válto&zó 3",																					// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Szerkeszti a szám változó 3 értékét (érték 0-tól 127-ig).\nSzám változó 3",						// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"Sz&prájt",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Tulajdonságok",																					// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Beállítja a szprájt tulajdonságait (fázisok, irányok,... száma).\nTulajdonságok",					// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Ellenõrzés",																						// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Futtatja a szprájt ellenõrzési üzemmódban.\nEllenõrzés",											// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"&Hang",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Lejátszás",																						// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Elindítja a hang (zene) lejátszását.\nLejátszás",													// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"&Szüneteltet",																						// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Szünetelteti a lejátszást.\nSzüneteltet",															// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"&Megállít",																						// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Megállítja a lejátszást.\nMegállít",																// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Ismételten",																						// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Ki/be kapcsolja a lejátszás ismétlõdését.\nIsmételten",											// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Feljátszik",																						// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Elindítja a feljátszást.\nFeljátszik",																// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"Z&ene",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Vissza",																							// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Vissza állítja a lejátszást 10 másodpercel.\nVissza",												// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Elõre",																							// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Elõbre állítja a lejátszást 10 másodpercel.\nElõre",												// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"A Peter programról",																				// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Peter verzió",																						// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Ing. Miroslav Nìmeèek",														// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Ronov pod Radhoštìm",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Cseh köztársaság",																					// Èeská Republika
IDC_DEMOTEXT1,				"A demoverzió nem teszi lehetõvé a programok elmentését, sem az új",								// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"vagy változtatott programok futtatását. A szerkesztési lehetõségek,",								// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"a segítség és az elmentés a könyvtárba mûködõ képesek.",											// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Aktuális információk a termékrõl a következõ internetes oldalon találhatók:",						// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"A megrendeléseket a következõ címre küldjék:",														// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENCIÓ",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"korlátlan",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"1 számítógép részére",																				// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"számítógép részére",																				// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"számítógép részére",																				// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"A Lite verziója a Peter programnak korlátolt programy felszerelést kínál",							// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(a nem mûködõ elemek szürke ikonokkal vannak megjelölve). A Lite verzió",							// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"FREEWARE és lehetséges szabadon terjeszteni és használni saját",									// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"célokra. Irodai használat vagy iskolák részére igényelt a licenciós",								// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"illeték megfizetése. Közelebbi információk a www.gemtree.com internetes címen találhatók.",		// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Szöveg keresése",																					// titulek okna hledání textu
IDN_FINDTEXT,				"Keresendõ szöveg:",																				// vızva k zadání textu k hledání
IDN_CANCEL0,				"Mégse",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Felület méretei",																					// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Szélesség:",																						// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Magasság:",																						// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Hiba a megnyitásnál",																				// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"A programot nem lehet megnyitni.",																	// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Nyilván más programmal van már megnyitva",															// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"vagy a hozzáférés a fájlhoz le van tiltva.",														// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Hiba az olvasásnál",																				// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Hiba történt a program olvasásánál.",																// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"A program sérült vagy magasabb verziójú szerkesztõvel",											// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"lett létrehozva, ezért nembiztos a helyes mûködése.",												// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Nem támogatott parancsok",																			// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Figyelmeztetés: A program olyan parancsokat használ, amelyek a Peter program",						// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"Lite verziója nem alkalmazhat. A program elmentésével",											// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"elõfordulhat, hogy nem fog mûködni.",																// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"A képek vagy egy kijelölt részük szerkesztése",													// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Elfordítás",																						// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Vízszintes",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Függõleges",																						// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Forgatás",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 fok)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 fok)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 fok)",																				// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 fok)",																				// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 fok)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 fok)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 fok)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 fok)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 fok)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 fok)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 fok)",																				// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 fok)",																				// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Méret változtatás",																				// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Kétszeres",																						// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Fél",																								// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Választható",																						// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Színek",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Bal <-> jobb gomb",																				// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Bal -> jobb gomb",																					// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Kép méretei",																						// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Méretek megadása",																					// nadpis rámeèku volby jednotky
IDC_KROK,					"&Lépésekben",																						// [1] volba jednotky v krocích
IDC_BOD,					"&Pixelekben",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"A kép vagy annak egy részének méret változtatása",													// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Aktuális méretek:",																				// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"lépés",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"pixel",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Új méretek",																						// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Szélesség:",																						// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Magasság:",																						// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"Lépésekben",																						// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"Pixelekben",																						// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"Százalékokban",																					// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Megõrizni a kép eredeti méret arányát (arány szélesség/magasság)",									// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Élek finomítása (pontos, de lassú átvitel)",														// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (bekapcsolni a fényképeknek, kikapcsolni a rajzoknak)",									// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Szín kiválasztás",																					// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"A programot nem lehet létrehozni",																	// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"A programot nem sikerült létrehozni.",																// 1. øádek hlášení
IDN_JINE_JMENO,				"Próbálja meg más nével.",																			// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Program törlése",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Biztosan törölni akarja a kiválasztott programot?",												// 1. øádek hlášení
IDN_SELECT_DEL2,			"Figyelmeztetés: a programot utánna nem lehet felujítani!",											// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Alkönyvtár törlése",																				// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Biztosan törölni akarja a kiválasztott alkönyvtárat?",												// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Az alkönyvtárat nem sikerült törölni",																// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Az alkönyvtárat nem lehet törölni, amíg nem üres.",												// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"A programot nem sikerült törölni",																	// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"A programot nem lehet törölni, amíg írás védelemmel van védve.",									// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Új alkönyvtár",																					// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Mi lesz az új alkönyvtár neve?",																	// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Az alkönyvtárat nem lehet létrehozni",																// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Az alkönyvtárat nem sikerült létrehozni.",															// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Az alkönyvtár létezik",																			// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Vigyázat - az alkönyvtár már létezik.",															// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"A program létezik",																				// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Vigyázat - a program már létezik.",																// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Új program",																						// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Mi lesz az új program neve?",																		// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"A program másolása",																				// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Mi lesz a program másolatának a neve?",															// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"A szprájt tulajdonságai",																			// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animáció",																							// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Idõ eltolódás a fázisok között:",																	// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"milliszekundum",																					// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Fázis egy lépésre (0 = azonnal):",																	// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Megjelenítési felszín (0 = mezõk):",																// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Képek száma",																						// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Nyugalmi fázisok:",																				// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Mozgási fázisok:",																					// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Irányok:",																							// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"A kép mérete",																						// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Szélesség:",																						// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Magasság:",																						// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"A szprájt tesztelése",																				// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Hiba az elmentésben",																				// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"A programot nem lehet elmenteni.",																	// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Ellenõrizze, hogy nincs-e futtatva",																// 2. øádek hlášení
IDN_WRITEERR3,				"vagy nem írásvédett-e.",																			// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"Szükség esetén mentse el a programot",																// 4. øádek hlášení
IDN_WRITEERR5,				"más néven vagy egy másik lemezre.",																// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"A program változtatva volt",																		// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"A program változtatva volt.\nElmentsem a változásokat?",											// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Az elem használva van",																			// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Figyelmeztetés - a törölni kívánt elem a programban felvan használva.\nTörlésével kitörli az esetleges alárendelt elemeket.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"felujíthatatlan törlés",																			// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Figyelmeztetés - törli az elemet a könyvtárból.\nA törlés helyreállíthatatlan, az elemet nem fog lehetni felújítani.",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Kevés memória",																					// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Nincs elég memória a mûvelet végrehajtására!\n\nSzabadítson fel helyet a Windows rendszer lemezén\nvagy ellenõrizze a Windows virtuális memóriájának beállításait.\nA program most instabil helyzetben lehet,\nezért, ha lehetséges, azonnal zárja be.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"Sajnálom, de a program befejezi futását memória hiány következtében!",								// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Sérült licenciós adatok",																			// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"A licenciós adatok megsérültek. Indítsa újra a Peter telepítõ programját a licenciós adatok javítására.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Vége az korlátolt idõszerû mûködésnek",															// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Lejárt a korlátolt idõszerû mûködés ideje a Peter programnak.",									// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Közeledik a vége a korlátolt idõszerû mûködésnek",													// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"A Peter aplikáció mûködése idõszerûen korlátorva van.\nMaradék napok száma a mûködésig:",			// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"Rendszer hiba",																					// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Hiányos rendszer eszközök a  PETER.EXE program indítására.",										// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"A program sérült",																					// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"A PETER.EXE program sérült, nem lehet futtatni.",													// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Elmenteni másik állományba",																		// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programok",																						// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Minden állomány",																					// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Elmenteni a program disztribúciós verzióját",														// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"A program már létezik",																			// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Figyelmeztetés - az elmentett állomány ezen a néven már létezik.\n\nA program disztribúciós verzióját menti el,\nha az a forráskódot tartalmazó programot írja felül,\na forráskód felujíthatatlanul elveszik.\n\nFolytassam a felülírást?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Nem futtatható program",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Ez a program a Peter programozói eszközzel lett létrehozva\nés most nem futtatható formában van elmentve.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Betû beállítása",																					// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Példa:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Ez egy példa arra, hogy nézhet ki egy szöveg pontokkal és ékezetekkel a betûkön.",					// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Standard betû",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Kövér",																							// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Dõlt",																								// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Aláhúzott",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Áthúzott",																							// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Sarkak nélkül",																					// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"Sarkakkal",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Szilárd betû szélesség",																			// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Kiválasztani a listából",																			// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Betû típus lista:",																				// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Magasság:",																						// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Szélesség[%]:",																					// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Stílus",																							// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Kinézet",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Alkönyvtár és név a program exportálásához",														// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Az importált program neve",																		// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Peter programok",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"üres mezõ",																						// prázdnı implicitní pøedmìt
IDF_GROUP,					"csoport",																							// skupina prvkù
IDF_IF,						"utasítások feltételes végrehajtása",																// záhlaví podmínky
IDF_IF_COND,				"ha érvényes",																						// test podmínky (IF)
IDF_IF_YES,					"akkor végezd el",																					// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"különben végezd el",																				// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"utasítások feltételes ismétlése",																	// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"amíg érvényes",																					// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"ismételd az utasításokat",																			// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"szakítsd meg az ismétlést",																		// pøerušení smyèky (BREAK)
IDF_MINUS,					"negatív elõjel",																					// záporné znaménko "-" v èísle
IDF_CASE,					"utasítások töbszörös elágazása",																	// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"a kifejezés értéke",																				// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"hajsd végre az utasításokat, ha",																	// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"a kifejezés egyenlõ az értékkel",																	// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"különben hajtsd végre az utasításokat",															// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"konstans szám",																					// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"exponens",																							// exponent v èísle
IDF_EQU,					"egyenlõ",																							// podmínka =
IDF_NEQU,					"nem egyenlõ",																						// podmínka <>
IDF_EQGR,					"nagyobb vagy egyenlõ",																				// podmínka >=
IDF_EQLT,					"kisebb vagy egyenlõ",																				// podmínka <=
IDF_GR,						"nagyobb mint",																						// podmínka >
IDF_LT,						"kisebb mint",																						// podmínka <
IDF_AND,					"és",																								// logickı souèin
IDF_OR,						"vagy",																								// logickı souèet
IDF_XOR,					"log. egyenlõtlenség (EXOR)",																		// logickı vıhradní souèet
IDF_NOT,					"ha nem érvényes, hogy",																			// logická negace
IDF_ADD,					"összeadás",																						// souèet èísel
IDF_SUB,					"kivonás",																							// rozdíl èísel
IDF_MUL,					"szorzás",																							// násobek èísel
IDF_DIV,					"osztás",																							// podíl èísel
IDF_REAL,					"szám",																								// èíselná promìnná
IDF_ICON,					"mezõ",																								// pøedmìtová promìnná
IDF_SND,					"hang",																								// zvuková promìnná
IDF_MUS,					"zene",																								// hudební promìnná
IDF_FNC,					"függvény",																							// funkce
IDF_MAP,					"felület",																							// promìnná plochy
IDF_SPRITE,					"szprájt",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"a program irányítása - kibõvítés",																	// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"szöveg",																							// textová promìnná
IDF_WINDOWS,				"ablakok",																							// skupina prvkù pro øízení oken
IDF_PAR,					"bemeneti változók",																				// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"kimeneti változó",																					// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"felület - kibõvítés",																				// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"lista",																							// záhlaví seznamu (LIST)
IDF_OPER,					"program irányítása",																				// skupina prvkù pro øízení programu
IDF_KROK,					"lépés",																							// Petøík popojít o krok vpøed
IDF_VLEVO,					"balra",																							// Petøík otoèit doleva
IDF_VPRAVO,					"jobbra",																							// Petøík otoèit doprava
IDF_VZAD,					"hátra",																							// Petøík otoèit vzad
IDF_PETRIK,					"Péter",																							// skupina prvkù Petøíka
IDF_BOOL,					"logikai változó",																					// logická promìnná
IDF_TEXT_CONST,				"Konstans szöveg",																					// textová konstanta
IDF_TRUE,					"igen",																								// logickı pøíznak TRUE
IDF_FALSE,					"nem",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucka",																							// skupina prvkù Lucky
IDF_PETRA_KROK,				"lépés",																							// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"balra",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"jobbra",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"hátra",																							// Lucka otoèit vzad
IDF_RYCHLE,					"látható",																							// viditelnost Petøíka
IDF_EXIT,					"függvény vége",																					// pøerušení funkce
IDF_PETRA_RYCHLE,			"látható",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"hang és zene",																						// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"mezõ Péter elõtt",																					// pøedmìt pøed Petøíkem
IDF_SMER,					"irány",																							// smìr otoèení Petøíka
IDF_POZICEX,				"vízszintes helyzet",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"függõleges helyzet",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"mezõ Lucka elõtt",																					// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"irány",																							// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"vízszintes helyzet",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"függõleges helyzet",																				// vertikální souøadnice Lucky
IDF_CONST,					"számítások",																						// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"aritmetikai mûveletek",																			// skupina èíselnıch operátorù
IDF_FUNC,					"függvények",																						// skupina èíselnıch funkcí
IDF_POROVNANI,				"összehasonlítás",																					// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logikai mûveletek",																				// skupina logickıch prvkù
IDF_MOD,					"modulo osztás",																					// èíselnı operátor modulo
IDF_SIN,					"színusz",																							// funkce sinus
IDF_COS,					"koszínusz",																						// funkce kosinus
IDF_TG,						"tangens",																							// funkce tangens
IDF_COTG,					"kotangens",																						// funkce kotangens
IDF_ARCSIN,					"arkusszínusz",																						// funkce arcus sinus
IDF_ARCCOS,					"arkuszkoszínusz",																					// funkce arcus kosinus
IDF_ARCTG,					"arkusztangens",																					// funkce arcus tangens
IDF_ARCCOTG,				"arkuszkotangens",																					// funkce arcus kotangens
IDF_PI,						"PI",																								// Ludolfovo èíslo (pí)
IDF_INTEGER,				"egész rész",																						// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"tizedes rész",																						// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"abszolút érték",																					// funkce absolutní hodnoty
IDF_SQRT,					"másodfokú gyök",																					// funkce druhá mocnina
IDF_FACT,					"faktoriális",																						// funkce faktoriál
IDF_RAND,					"véletlen szám (0 <= x < 1)",																		// náhodné èíslo
IDF_EUL,					"Euler állandó",																					// Eulerova konstanta (e)
IDF_DEGRAD,					"fok átalakítása radiánná",																			// funkce konverze stupòù na radiány
IDF_RADDEG,					"radián átalakítása fokra",																			// funkce konverze radiánù na stupnì
IDF_LOG,					"tizes alapú logaritmus",																			// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"természetes logaritmus",																			// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"természetes exponenciálú függvény",																// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"hatvány",																							// operátor mocniny
IDF_UHEL,					"szög, irány",																						// skupina úhlù (smìrù)
IDF_UHEL0,					"jobbra (0 pi, tehát 0 fok)",																		// smìr vpravo
IDF_UHEL45,					"jobbra fel (1/4 pi, tehát 45 fok)",																// smìr vpravo nahoru
IDF_UHEL90,					"fel (1/2 pi, tehát 90 fok)",																		// smìr nahoru
IDF_UHEL135,				"balra fel (3/4 pi, tehát 135 fok)",																// smìr vlevo nahoru
IDF_UHEL180,				"balra (1 pi, tehát 180 fok)",																		// smìr vlevo
IDF_UHEL225,				"balra le (1 1/4 pi, tehát 225 fok)",																// smìr vlevo dolù
IDF_UHEL270,				"le (1 1/2 pi, tehát 270 fok)",																		// smìr dolù
IDF_UHEL315,				"jobbra le (1 3/4 pi, tehát 315 fok)",																// smìr vpravo dolù
IDF_COMMAND,				"vezérlés",																							// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"vár (implicit = 0.05 s)",																			// pøíkaz pro èekání
IDF_KLAV,					"billentyûzet",																						// skupina ovládání klávesnice
IDF_KLAV_TEST,				"le van nyomva a billentyû?",																		// test stisknuté klávesy
IDF_KLAV_VKEY,				"billentyû bemenete (nem vár egy billentyû lenyomására)",											// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"karakter bemenete (nem vár egy billentyû lenyomására)",											// vstup znaku bez èekání
IDF_KLAV_VK,				"billentyûk",																						// skupina kódù kláves
IDF_KLAV_FX,				"funkcióbillentyûzet",																				// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"betûk",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numerikus billentyûzet",																			// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"jel billentyûk",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"vezérlõ (kurzor) billentyûk",																		// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"átlátszóság",																						// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 End",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 le",																								// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 PgDn",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 balra",																							// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 jobbra",																							// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Home",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 fel",																							// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Del",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 ! (1 \')",																						// kód klávesy 1 !
IDF_VK_2,					"2 @ (2 \")",																						// kód klávesy 2 @
IDF_VK_3,					"3 # (3 +)",																						// kód klávesy 3 #
IDF_VK_4,					"4 $ (4 !)",																						// kód klávesy 4 $
IDF_VK_5,					"5 % (5 %)",																						// kód klávesy 5 %
IDF_VK_6,					"6 ^ (6 /)",																						// kód klávesy 6 ^
IDF_VK_7,					"7 & (7 =)",																						// kód klávesy 7 &
IDF_VK_8,					"8 * (8 ( )",																						// kód klávesy 8 *
IDF_VK_9,					"9 ( (9 ))",																						// kód klávesy 9 (
IDF_VK_0,					"0 ) (ö Ö)",																						// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~ (0 §)",																						// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _ (ü Ü)",																						// kód klávesy - _
IDF_VK_ROVNITKO,			"= + (ó Ó)",																						// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ | (û Û)",																						// kód klávesy \ |
IDF_VK_LLOMENA,				"[ { (õ Õ)",																						// kód klávesy [ {
IDF_VK_RLOMENA,				"] } (ú Ú)",																						// kód klávesy ] }
IDF_VK_STREDNIK,			"; : (é É)",																						// kód klávesy ; :
IDF_VK_RCARKA,				"\' \" (á Á)",																						// kód klávesy ' "
IDF_VK_CARKA,				", < (, ?)",																						// kód klávesy , <
IDF_VK_TECKA,				". > (. :)",																						// kód klávesy . >
IDF_VK_LOMITKO,				"/ ? (- _)",																						// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"bal menü Windows",																					// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Back Space",																						// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"lokális menü",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"balra",																							// kód klávesy Vlevo
IDF_VK_RIGHT,				"jobbra",																							// kód klávesy Vpravo
IDF_VK_UP,					"fel",																								// kód klávesy Nahoru
IDF_VK_DOWN,				"le",																								// kód klávesy Dolù
IDF_VK_INSERT,				"Insert",																							// kód klávesy Insert
IDF_VK_DELETE,				"Delete",																							// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"End",																								// kód klávesy End
IDF_VK_PAGEUP,				"Page Up",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Page Down",																						// kód klávesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"bal Shift",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"bal Ctrl",																							// kód klávesy Levı Ctrl
IDF_VK_ALT,					"bal Alt",																							// kód klávesy Levı Alt
IDF_VK_SPACE,				"helyköz",																							// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"egér",																								// skupina prvkù myši
IDF_MOUSE_L,				"egér bal nyomógombja le van nyomva",																// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"egér jobb nyomógombja le van nyomva",																// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"egér helyzete vízszintes irányban",																// horizontální souøadnice myši
IDF_MOUSE_Y,				"egér helyzete függõleges irányban",																// vertikální souøadnice myši
IDF_EQU_TEXT,				"szövegek egyenlõsége",																				// operátor porovnání textù
IDF_EQU_ICO,				"mezõk egyenlõsége",																				// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"szprájtok - kibõvítés",																			// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"az ablaknak van ablakkerete",																		// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"az ablaknak van címmezeje",																		// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"program paraméterei",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"kimeneti kód",																						// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"kép",																								// promìnná obrázku
IDF_REPEAT,					"utasítások ismétlése szám mennyiség szerint",														// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"ismétlések száma",																					// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"felület széle",																					// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"vízszintessen",																					// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"függõlegesen",																						// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"irány",																							// smìr sprajtu
IDF_SPRITE_MOVE,			"mozgásban",																						// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"látható",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"elemek száma",																						// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"index",																							// index seznamu
IDF_LIST_AUTO,				"index inkrementálása",																				// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Péter - kibõvítés",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucka - kibõvítés",																				// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"szám változó 1 (érték 0-tól 1023-ig)",																// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"szám változó 1 (érték 0-tól 1023-ig)",																// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"szám változó 2 (érték 0-tól 1023-ig)",																// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"szám változó 2 (érték 0-tól 1023-ig)",																// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"szám változó 3 (érték 0-tól 127-ig)",																// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"szám változó 3 (érték 0-tól 127-ig)",																// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"kapcsoló 1",																						// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"kapcsoló 1",																						// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"kapcsoló 2",																						// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"kapcsoló 2",																						// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"kapcsoló 3",																						// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"kapcsoló 3",																						// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"kapcsoló 4",																						// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"kapcsoló 4",																						// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"kapcsoló 5",																						// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"kapcsoló 5",																						// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"Szövegek",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"bal oldali része a szövegnek",																		// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"bal oldali rész hossza a szövegben",																// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"jobb oldali része a szövegnek",																	// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"jobb oldali rész eleje a szövegben",																// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"középsõ része a szövegnek",																		// funkce støední èásti textu
IDF_TEXT_MID_POS,			"középsõ rész eleje a szövegben",																	// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"középsõ rész hossza a szövegben",																	// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"szöveg hossza",																					// funkce zjištìní délky textu
IDF_TEXT_ADD,				"szövegek összevonása",																				// operátor pro slouèení textù
IDF_TEXT_SCAN,				"szöveg átalakítása számmá",																		// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"szám átalakítása szövegre",																		// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"szövegek ábécés összehasonlítása",																	// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"átalakítás kis betûkre",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"átalakítás nagy betûkre",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"keresd a szöveg helyzetét (-1 = nincs)",															// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"bemeneti szöveg",																					// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"keresett szöveg",																					// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"állapotsor szövege",																				// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"címmezõ szövege",																					// titulek hlavního okna (textová promìnná)
IDF_ORD,					"karakter átalakítása numerikus kódra",																// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"numerikus kód átalakítása karakterra",																// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"hang",																								// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"hang lejátszás",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"hang megállítása (megadás nélkül = mind)",															// vypnutí zvuku
IDF_COLOR,					"szín",																								// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"grafika",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"toll színe",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"toll vastagság",																					// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"pont",																								// nakreslení grafického bodu
IDF_POINT_X,				"vízszintes koordinátája X a pontnak",																// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"függõleges koordinátája Y a pontnak",																// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"vonal",																							// nakreslení èáry
IDF_LINE_X1,				"vízszintes koordinátája X1 a vonalnak",															// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"függõleges koordinátája Y1 a vonalnak",															// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"vízszintes koordinátája X2 a vonalnak",															// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"függõleges koordinátája Y2 a vonalnak",															// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"téglalap",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"vízszintes koordinátája X1 a téglalapnak",															// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"függõleges koordinátája Y1 a téglalapnak",															// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"vízszintes koordinátája X2 a téglalapnak",															// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"függõleges koordinátája Y2 a téglalapnak",															// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"kitöltött téglalap",																				// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"vízszintes koordinátája X1 a kitöltött téglalapnak",												// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"függõleges koordinátája Y1 a kitöltött téglalapnak",												// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"vízszintes koordinátája X2 a kitöltött téglalapnak",												// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"függõleges koordinátája Y2 a kitöltött téglalapnak",												// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"kitöltés",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"kitöltés vízszintes koordinátája X",																// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"kitöltés függõleges koordinátája Y",																// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"üres kör",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"a középpont vízszintes koordinátája X",															// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"a középpont függõleges koordinátája Y",															// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"rádiusz",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"kitöltött kör",																					// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"a középpont vízszintes koordinátája X",															// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"a középpont függõleges koordinátája Y",															// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"rádiusz",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"háromszög",																						// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"vízszintes koordinátája X1 a háromszögnek",														// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"függõleges koordinátája Y1 a háromszögnek",														// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"vízszintes koordinátája X2 a háromszögnek",														// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"függõleges koordinátája Y2 a háromszögnek",														// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"vízszintes koordinátája X3 a háromszögnek",														// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"függõleges koordinátája Y3 a háromszögnek",														// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"gömb",																								// nakreslení koule
IDF_SPHERE_X,				"a középpont vízszintes koordinátája X",															// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"a középpont függõleges koordinátája Y",															// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"rádiusz",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"szín fény változtatása",																			// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"szín fénye (0-tól 1-ig)",																			// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"billentyû bemenete (vár egy billentyû lenyomására)",												// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"karakter bemenete (vár egy billentyû lenyomására)",												// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"nem volt billentyû lenyomva",																		// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"jobb Windows menü",																				// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"jobb Shift",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"jobb Ctrl",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"jobb Alt",																							// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"Num Lock állapota",																				// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"Caps Lock állapota",																				// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"Scroll Lock állapota",																				// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"Insert állapota",																					// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"kattintás egér bal nyomógombjával",																// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"kattintás egér jobb nyomógombjával",																// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"dupla kattintás egér bal nyomógombjával",															// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"dupla kattintás egér jobb nyomógombjával",															// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"egér tesztelése a területen",																		// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"terület elejének vízszintes koordinátája X",														// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"terület elejének függõleges koordinátája Y",														// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"a terület szélessége",																				// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"a terület magassága",																				// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"szöveg kiírása",																					// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"szöveg vízszintes koordinátája X",																	// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"szöveg függõleges koordinátája Y",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"szöveg elhelyezkedésének szöge",																	// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"karakterek magassága",																				// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"karakterek relatív szélessége (1 = átlagos)",														// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"kövér betû",																						// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"döntött betû",																						// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"aláhúzott betû",																					// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"áthúzott betû",																					// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"sarkak",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"írógép",																							// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"szöveg a kiírásra",																				// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"sorok száma a szövegben",																			// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"szöveg sora",																						// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"sor száma a szövegben",																			// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"hang ellenõrzése (megadás nélkül = összes hang)",													// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"ismétlések száma (0 = állandóan)",																	// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"mezõ Péter helyzetén",																				// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"mezõ Lucka helyzetén",																				// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"kép kirajzolása",																					// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"a kirajzolandó kép",																				// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"a kép vízszintes koordinátája X",																	// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"a kép függõleges koordinátája Y",																	// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"kivágás vízszintes koordinátája X",																// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"kivágás függõleges koordinátája Y",																// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"kivágás szélessége",																				// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"kivágás magassága",																				// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"kivágás elmentése a felületrõl, mint kép",															// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"kivágás elmentése a felületrõl, mint mezõ",														// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"nyelv (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"hang lejátszásra",																					// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"hang erõssége (0-tól 1-ig)",																		// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"sztereofónikus egyensúly (-1 = bal egész +1 = jobb)",												// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"megállítani a hang lejászását",																	// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"kommentár",																						// komentáø
IDF_SOUND_FUNCTIONS,		"hang függvények",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"egér kinézetének beállítása",																		// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"az egér kurzorának képe (megadás nélkül = eredeti)",												// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"terület elejének vízszintes koordinátája X",														// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"terület elejének függõleges koordinátája Y",														// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"terület szélessége",																				// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"terület magassága",																				// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"zene lejátszás",																					// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"a zene ismételt lejátszása",																		// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"zene lejátszás megállítása",																		// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"zene lejátszás szüneteltetése/folytatása",															// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"zene lejátszás ellenõrzése",																		// test pøehrávání hudby
IDF_MUSIC_POS,				"pozíció a zene lejátszásban",																		// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"a lejátszott zene hossza",																			// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"alap színek összevonása egy új színben",															// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"piros összetevõ (0-tól 1-ig)",																		// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"zöld összetevõ (0-tól 1-ig)",																		// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"kék összetevõ (0-tól 1-ig)",																		// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"pixel színének megállapítása",																		// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"vízszintes koordináta X a pixel színének megállapítására",											// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"függõleges koordinátá Y a pixel színének megállapítására",											// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"négyzet",																							// funkce druhá mocnina
IDF_MUSIC_GROUP,			"zene",																								// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"audio CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"CD lejátszás megadott sávtól (megadás nélkül = 1)",												// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"CD lejátszás megállítása",																			// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"CD lejátszást szüneteltet/folytat",																// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"CD lejátszás tesztelése",																			// test pøehrávání CD
IDF_CD_LENGTH,				"CD teljes hossza",																					// celková délka CD
IDF_CD_TRACKS,				"mezõk száma",																						// poèet stop CD
IDF_CD_POS,					"pozíció az elejétõl",																				// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"lejátszott mezõ",																					// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"a lejátszott mezõ hossza",																			// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"pozíció a mezõ elejétõl",																			// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"állományok",																						// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"alap mûveletek",																					// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"új állomány",																						// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"új alkönyvtár",																					// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"állomány vagy alkönyvtár törlése",																	// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"létezés ellenõrzése",																				// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"aktív lemez és alkönyvtár",																		// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"lemez kapacitás",																					// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"szabad hely a lemezen",																			// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"lemez megnevezése",																				// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"lemez gyártási száma",																				// zjištìní sériového èísla disku
IDF_FILE_READ,				"aktív állomány/alkönyvtár olvasásra",																// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"aktív állomány/alkönyvtár írásra",																	// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"állomány másolása",																				// provedení kopie souboru
IDF_FILE_MOVE,				"állomány (alkönyvtár) áthelyezése/átnevezése",														// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"lemez",																							// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"atribútumok",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"R/O (csak olvasható) atribútum",																	// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"HID (rejtett) atribútum",																			// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"SYS (rendszer) atribútum",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"DIR (alkönyvtár) atribútum",																		// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"ARC (archív) atribútum",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"TEMP (átmeneti) atribútum",																		// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"COMP (csomagolt) atribútum",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"OFF (nem hozzáférhetõ) atribútum",																	// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"létrehozás dátuma és ideje",																		// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"utolsó hozzáférés dátuma és ideje",																// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"utolsó változtatás dátuma és ideje",																// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"adatok",																							// skupina dat souborù
IDF_FILE_BYTES,				"elõjeles egész szám, 1 byte",																		// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"elõjel nélküli egész szám, 1 byte",																// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"elõjeles egész szám, 2 byte",																		// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"elõjel nélküli egész szám, 2 byte",																// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"elõjeles egész szám, 4 byte",																		// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"elõjel nélküli egész szám, 4 byte",																// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"tizedes szám, 4 byte",																				// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"tizedes szám, 8 byte",																				// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"bináris nullával lezárt szöveg (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"új sor jellel lezár szöveg",																		// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"szöveg megadott hosszal",																			// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"mezõ (ICO)",																						// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"kép (BMP, JPG)",																					// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"hang (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"zene (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"olvasás mutatója",																					// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"írás mutatója",																					// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"dátum és idõ",																						// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"aktuális dátum és idõ (másodpercek száma 1601.1.1.-tõl)",											// aktuální datum a èas
IDF_DATETIME_UTC,			"helyi idõ átalakítása nemzetközire",																// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"nemzetközi idõ átalakítása helyire",																// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"a dátum és idõ elemeinek összevonása",																// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"év",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"hónap",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"nap",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"óra",																								// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"perc",																								// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"másodperc",																						// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"miliszekundum",																					// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"év a dátum és idõbõl",																				// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"hónap a dátum és idõbõl",																			// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"nap a dátum és idõbõl",																			// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"nap a hétben a dátum és idõbõl alapján (0 = vasárnap, 1 = hétfõ, ...)",							// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"óra a dátum és idõbõl",																			// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"perc a dátum és idõbõl",																			// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"másodperc a dátum és idõbõl",																		// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"miliszekundum a dátum és idõbõl",																	// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"dátum átalakítása \"nap.hónap.év\" szöveggé",														// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"dátum átalakítása \"hónap/nap/év\" szöveggé",														// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"dátum átalakítása \"év-hónap-nap\" szöveggé",														// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"idõ átalakítása \"óra:perc:másodperc\" szöveggé (24 óra)",											// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"idõ átalakítása \"óra:perc:másodperc\" szöveggé (12 óra)",											// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"állomány mérete",																					// velikost souboru
IDF_FILE_ERROR,				"hibás mûvelet",																					// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"szöveg mérete adott hosszal",																		// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"lemez típusa (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",													// zjištìní typu disku
IDF_TEXT_FORMAT2,			"szám átalakítása szöveggé - 2 számjegy",															// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"szám átalakítása szöveggé - 8 HEX számjegy",														// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"elõjeles egész szám, 3 byte",																		// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"elõjel nélküli egész szám, 3 byte",																// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"párbeszéd ablakok",																				// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"párbeszédpanel (visszaad 1=OK, 2=Mégse, 3=Megszakít, 4=Újra, 5=Ignorál, 6=Igen, 7=Nem)",			// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"szöveg",																							// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"címmezõ",																							// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"ikon (0=nincs, 1=hiba, 2=kérdés, 3=figyelmeztetés, 4=információ)",									// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"nyomógombok (0=OK, 1=OK/Mégse, 2=Megszakít/Újra/Ignorál, 3=Igen/Nem/Mégse, 4=Igen/Nem, 5=Újra/mégse)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"implicit nyomógomb (1-tõl 3-ig)",																	// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"új sor",																							// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"szöveg megadása",																					// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1. sora a felszólításnak",																			// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2. sora a felszólításnak",																			// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3. sora a felszólításnak",																			// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"elõre beállított szöveg a megadásra",																// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"CD kilökése",																						// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"bitek száma egy mintára (8 vagy 16)",																// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"jel frekvencia (Hz)",																				// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"sztereofónikus a hang?",																			// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"hang hossza (másodperc)",																			// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"átalakítás 8 bitre",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"átalakítás 16 bitre",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"vátalakítás sztereora",																			// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"átalakítás monora",																				// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"átalakítás 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"átalakítás 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"átalakítás 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"hangok összevonása",																				// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"hang gyorsaságának változtatása",																	// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"hang változtatásra",																				// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relatív gyorsaság változtatása (1 = megadás nélük)",												// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"tónus generátor",																					// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"tónus frekvenciája (Hz)",																			// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"tónus hossza (másodperc)",																			// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"felület",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"felület szélessége",																				// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"felület magassága",																				// zjištìní vıšky plochy
IDF_MAP_X,					"X koordináta",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"Y koordináta",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"felület",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"mezõ",																								// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"szám változó 1 (érték 0-tól 1023-ig)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"szám változó 2 (érték 0-tól 1023-ig)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"szám változó 3 (érték 0-tól 127-ig)",																// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"kapcsoló 1",																						// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"kapcsoló 2",																						// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"kapcsoló 3",																						// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"kapcsoló 4",																						// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"kapcsoló 5",																						// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"felületrõl kivágott rész másolása",																// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"felület kivágással",																				// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"kivágás X koordinátája",																			// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"kivágás Y koordinátája",																			// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"kivágás szélessége",																				// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"kivágás magassága",																				// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"konzol",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"szprájtok tömeges elmozdítása X irányban",															// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"szprájtok tömeges elmozdítása Y irányban",															// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"szprájtok ablakának bal oldala",																	// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"szprájtok ablakának alsó oldala",																	// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"szprájtok ablakának jobb oldala",																	// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"szprájtok ablakának felsõ oldala",																	// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"konzol üzemmód (a fõfüggvény elején kell lenie)",													// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"szöveg kimenete a konzolra",																		// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"szöveg bemenete a konzolról",																		// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"szöveg hiba jelentés kimenete a konzolra",															// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"program paraméterei (0 = program neve)",															// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"program neve teljes úttal",																		// jméno tohoto programu s plnou cestou
IDF_EXEC,					"program futtatása",																				// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"program futtatása várakozással",																	// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"joystick",																							// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"joystick X koordinátája",																			// souøadnice X joysticku
IDF_JOYSTICK_Y,				"joystick Y koordinátája",																			// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"joystick Z koordinátája",																			// souøadnice Z joysticku
IDF_JOYSTICK_1,				"joystick nyomógomb 1",																				// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"joystick nyomógomb 2",																				// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"joystick nyomógomb 3",																				// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"joystick nyomógomb 4",																				// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"szövegek és képek",																				// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"vezérlõ elem száma (0 = fõablak)",																	// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"vezérlõ elem/ablak törlése",																		// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"ablak kialakítása",																				// vytvoøení dialogového okna
IDF_WINDOW_X,				"vízszintes koordináta",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"függõleges koordináta",																			// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"szélesség",																						// šíøka prvku dialogového okna
IDF_WINDOW_H,				"magasság",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"szöveg",																							// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"láthatóság",																						// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"tilalom",																							// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"nyomógomb kialakítása",																			// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"nyomógomb leütése vagy vezérlõ elem változása",													// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"kiválasztónégyzet kialakítása",																	// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"írható sor kialakítása",																			// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"választókapcsoló kialakítása",																		// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"közös függvények az összes elem számára",															// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"írható mezõ kialakítása",																			// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"nyomógombok",																						// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"kapcsoló bekapcsolva",																				// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"kurzor fókusza",																					// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"implicit nyomógomb kialakítása",																	// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"ikon nyomógomb kialakítása",																		// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"csoport kialakítása",																				// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"lista kialakítása",																				// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"szöveg kialakítása",																				// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"legördülõ lista kialakítása",																		// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"írható legördülõ lista kialakítása",																// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"kövér betû",																						// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"betû szilárd szélessége",																			// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"választókapcsoló létrehozása - csoport kezdete",													// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"listák",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"adat hozzáadása a listához",																		// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"lista kiürítése",																					// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"írható lista kialakítása",																			// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"3 állapotú kiválasztónégyzet kialakítása",															// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"kapcsoló ismeretlen állapotban",																	// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"ablak kialakítása bezárási lehetõség nélkül",														// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"ikon",																								// ikona prvku dialogového okna
IDF_WINICON_NEW,			"ikon kialakítása",																					// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"szprájt (SPR)",																					// sprajt (data ze souboru)
IDF_2PI,					"2*pi (= 360 fok)",																					// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"1 pixeles távolság (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"fázis",																							// fáze sprajtu
IDF_SPRITE_STATUS,			"állapot",																							// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"egész képernyõs üzemmód",																			// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"billentyûzet memória törlése",																		// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"pozíció a hang lejátszásban",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"szüneteltetés/folytatás a hang lejátszásban",														// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"állományok listája",																				// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"felületek egyenlõsége",																			// operátor porovnání ploch
IDF_EQU_PIC,				"képek egyenlõsége",																				// operátor porovnání obrázkù
IDF_EQU_SPR,				"szprájtok egyenlõsége",																			// operátor porovnání sprajtù
IDF_EQU_SND,				"hangok egyenlõsége",																				// operátor porovnání zvukù
IDF_EQU_MUS,				"zenék egyenlõsége",																				// operátor porovnání hudeb
IDF_NET_GROUP,				"komunikáció",																						// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"DirectPlay hálózati támogatás",																	// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"összeköttetések listája",																			// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"aktív összeköttetés",																				// aktivní spojení DirectPlay
IDF_GAME_LIST,				"játékok listája",																					// seznam bìících her DirectPlay
IDF_GAME_ACT,				"aktív játék",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"játékosok listája",																				// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"aktív játékos",																					// aktivní hráè DirectPlay
IDF_GAME_N1,				"játék szám paramétere 1 (-16384-tól +16383-ig)",													// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"játék szám paramétere 2 (-16384-tól +16383-ig)",													// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"játék szám paramétere 3 (-16384-tól +16383-ig)",													// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"játék szám paramétere 4 (-16384-tól +16383-ig)",													// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"játék szám paramétere 5 (-16384-tól +16383-ig)",													// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"játék szám paramétere 6 (-16384-tól +16383-ig)",													// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"játék szám paramétere 7 (-16384-tól +16383-ig)",													// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"játék szám paramétere 8 (-16384-tól +16383-ig)",													// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"játék kapcsolója 1",																				// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"játék kapcsolója 2",																				// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"játék kapcsolója 3",																				// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"játék kapcsolója 4",																				// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"játék kapcsolója 5",																				// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"játék kapcsolója 6",																				// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"játék kapcsolója 7",																				// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"játék kapcsolója 8",																				// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"játék beállítása",																					// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"vendéglátó (irányító számítógép)",																	// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"játékosok maximális száma (0 = korlátlan)",														// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"aktív játékos száma (-1 = nincs)",																	// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"adatok",																							// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"adat blok küldése/fogadása (-1 = mindenkinek/nincs)",												// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"szám",																								// èíslo dat DirectPlay
IDF_GAME_DATAT,				"szöveg",																							// text dat DirectPlay
IDF_GAME_DATAL,				"kapcsoló",																							// pøepínaè dat DirectPlay
IDF_GAME_IP,				"a számítógép IP címe",																				// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"egész szám 0-tól 255-ig (1 byte)",																	// èíslo bajt dat DirectPlay
IDF_INC,					"inkrementálás (hozzáad 1-et)",																		// funkce inkrementace èísla
IDF_DEC,					"dekrementálás (kivon 1-et)",																		// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"középre igazított szöveg kialakítása",																// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"nyomógomb az Esc billentyûnek (-1 = nincs)",														// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"kép szélessége",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"kép magassága",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"kép vízszintes elforgatása",																		// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"kép függõleges elforgatása",																		// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"képek",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"kép méretének változtatása",																		// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"kép",																								// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"szélesség (megadás nélkül = arányos a magasságal)",												// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"magasság (megadás nélkül = arányos a szélességel)",												// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"élek finomítása",																					// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (fényképek)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"rajzolás",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"kép kialakítása",																					// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"kép",																								// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"RichEdit szerkesztõ létrehozása",																	// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"betûk magassága (0 = átlagos)",																	// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"döntött betû",																						// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"aláhúzott betû",																					// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"áthúzott betû",																					// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"betû sarkakkal",																					// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"betûk relatív szélessége (0 = átlagos, 1 = alap)",													// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"szöveg hajlásának szöge",																			// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"jobbra igazított szöveg kialakítása",																// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"betû színe",																						// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"háttér színe",																						// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"vezérlõ elem betûje",																				// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"lejátszás gyorsasága (1 = átlagos)",																// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"megkülönböztetõ kód (0-tól 65535-ig)",																// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"állomány megnyitása párbeszédablak",																// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"állomány elmentése párbeszédablak",																// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"szöveg keresése párbeszédablak",																	// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"szín megadása párbeszédablak",																		// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"állomány álca",																					// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"elõreállított állomány neve",																		// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"állomány típusok megnevezése",																		// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"kép fény változása",																				// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"kép fény változtatásra",																			// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"kép fényessége (1 = átlagos)",																		// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"kép forgatása",																					// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"forgatott kép",																					// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"forgatás szöge",																					// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"hang dekompressziója",																				// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"szöveg UNICODE formátumban (2 byte)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"felület átalakítása képpé",																		// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"mezõ átalakítása képpé",																			// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"bit mûveletek",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"AND bit szorzás",																					// bitovı (binární) souèin AND
IDF_BIT_OR,					"OR bit összeadás",																					// bitovı (binární) souèet OR
IDF_BIT_XOR,				"XOR bit egyenlõtlenség",																			// bitová (binární) inverze XOR
IDF_BIT_NOT,				"NOT bit negáció",																					// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"maximális bit szám (dupla szó)",																	// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"bit rotáció balra",																				// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"bit rotáció jobbra",																				// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"egér ellenõrzése a vezérlõ elemben",																// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"belsõ szélesség",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"belsõ magasság",																					// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"betû csoport (1250=közép-európai, 1251=orosz, 1252=nyugati)",										// èíslo pouité znakové sady fontù
IDF_USERFONT,				"felhasználói betû",																				// jméno uivatelského fontu
IDF_ENUMFONTS,				"betûk listája",																					// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"új felület",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"felület szélesség",																				// šíøka nové plochy
IDF_MAP_NEW_H,				"felület magasság",																					// vıška nové plochy
IDF_WINDOW_TOP,				"mindig fent",																						// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"becenév (alias)",																					// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"komunikációs port",																				// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"portot kinyit (-1=hiba)",																			// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"portot bezár",																						// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"aktív port",																						// aktivní port
IDF_COM_NUM,				"szám (0-tól 255-ig)",																				// vstup/vıstup èísla
IDF_COM_TEXT,				"karakter (szöveg)",																				// vstup/vıstup znaku
IDF_COM_BAUD,				"átviteli sebesség",																				// pøenosová rychlost
IDF_COM_STOP,				"2 stop bit",																						// reim s 2 stopbity
IDF_COM_BITS,				"bitek száma (5-tõl 8-ig)",																			// poèet bitù na znak
IDF_COM_PARIT,				"paritás (0=nincs, 1=páratlan, 2=páros)",															// zvolená parita
IDF_COM_IN,					"adat volt fogadva",																				// byl pøijatı znak
IDF_COM_SEND,				"közvetítés engedélyezve (CTS, RTS)",																// povoleno vysílání
IDF_COM_RECEIVE,			"adat fogadás engedélyezve (DSR, DTR)",																// povolen pøíjem
IDF_PICTURE_MASK,			"kép álcázása",																						// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"kép",																								// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"álca",																								// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"mezõ szélessége a szöveg kiíráshoz (0 = nincs)",													// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"sor törés nélküli írható mezõ kialakítása",														// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"ablak változtatható mérete",																		// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"lehetséges az ablak bezárása",																		// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"maximalizált ablak",																				// maximalizace okna
IDF_WINDOW_MINIM,			"minimalizált ablak",																				// minimalizace okna
IDF_PROGRESS_NEW,			"folyamatjelzõ kialakítása",																		// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"vízszintes csúszka kialakítása",																	// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"függõleges csúszka kialakítása",																	// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"aktuális helyzet",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"keverõ berendezés",																				// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"keverõ berendezés",																				// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"cél jel",																							// volba cílového signálu
IDF_MIX_LINE_SRC,			"forrás jel (semmi=csak a cél jel)",																// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"jel típusa",																						// zjištìní typu signálu
IDF_MIX_CONTROL,			"vezérlõ elem",																						// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"vezérlõ elem típusa",																				// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"vezérlõ elem értéke (0-tól 1-ig)",																	// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"az elem érték kiválasztása",																		// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"irányított csatorna (-1=mind)",																	// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D grafika",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"3D grafikai ablak",																				// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X koordinátája a 3D grafikai ablaknak",															// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y koordinátája a 3D grafikai ablaknak",															// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"szélessége a 3D grafikai ablaknak",																// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"magassága a 3D grafikai ablaknak",																	// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"videómód (szélesség*magasság/bit)",																// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"grafikai háttér",																					// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"beállítások",																						// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"felületek kitöltése",																				// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"megvilágítás",																						// mód osvìtlení
IDF_DIRECT3D_SHADES,		"folyamatos árnyékolás",																			// mód stínování
IDF_DIRECT3D_INVERT,		"objektum inverzálása",																				// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objektumok",																						// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"fal",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"téglatest",																						// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"gömb",																								// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"henger",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"kúp",																								// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"klónozás",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"objektum szövegbõl",																				// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"objektum állományból",																				// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"aktív objektum (0=színhely, 1=kamera, 2=fény)",													// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"objektum törlése",																					// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"látható",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"kapcsolás",																						// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"objektum állományba",																				// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transzformáció",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"mérték X irányban",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"mérték Y irányban",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"mérték Z irányban",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"forgatás X tengely alapján",																		// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"forgatás Y tengely alapján",																		// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"forgatás Z tengely alapján",																		// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"eltolás X tengely alapján",																		// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"eltolás Y tengely alapján",																		// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"eltolás Z tengely alapján",																		// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"felszín",																							// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"szín (-1=belsõ, -2=átlagos)",																		// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"világítás színe",																					// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"homályosság (matt) (0=kikapcs., 5=fém, 50=mûanyag)",												// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"fény visszaverõdés színe",																			// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"textúra",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"textúra térképezése",																				// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"projekció típusa (0=felület, 1=henger, 2=gömb, 3=króm, 4=üveg)",									// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"projekció középpontjának X koordinátája",															// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"projekció középpontjának Y koordinátája",															// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"projekció középpontjának Z koordinátája",															// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"projekció forgatása X koordináta alapján",															// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"projekció forgatása Y koordináta alapján",															// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"projekció forgatása Z koordináta alapján",															// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"átlátszóság (1=normális, 11=tûz, 20=üveg, 54=áttakarás)",											// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"körvonalak (0=normális, 0.5=körvonalak)",															// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"módszer (0=címek, 1=csúcsok, 2=felületek)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"textúra eleje vízszintesen",																		// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"textúra eleje függõlegesen",																		// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"a textúra kicsinyítési fokozata vízszintessen",													// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"a textúra kicsinyítési fokozata függõlegessen",													// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"megvilágítás",																						// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"új fény kialakítása",																				// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"fény színe",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"fény típusa (1=pont, 2=henger, 3=irány)",															// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"fény hengerének szöge",																			// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"félárnyék szöge",																					// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"fény kiterjedése",																					// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"fény intenzitása (1=normális)",																	// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"lineáris gyengítés",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"kvadratikus gyengítés",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"projekció típusa (0=persp, 1=orto, 2=r-persp, 3=r-ortho)",											// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"színhely",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"színhely hátterének színe (-1=kikapcsolva, -2=nem inicializálni)",									// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"színhely hátterének textúrája",																	// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"köd színe (-1=kikapcsolva)",																		// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"köd típusa (0=lin, 1=exp, 2=kvadr, +4=korekció)",													// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"lineáris köd eleje",																				// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"lineáris köd vége",																				// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"exp. és kvadr. köd sûrûsége (0-tól 1-ig)",															// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"vetített sík távolsága",																			// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"elláthatóság távolsága",																			// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"felsõ alapzat létrehozása",																		// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"alsó alapzat létrehozása",																			// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"objektum keresése",																				// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"pont X koordinátája",																				// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"pont Y koordinátája",																				// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"kicsinyített textúrák kiszûrése",																	// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"2D objektumok",																					// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terep a képbõl",																					// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"terep magassága",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"vízszintes koordináta",																			// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"függõleges koordináta",																			// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"csoport",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"objektum összetettsége (2-tõl 100-ig)",															// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"forgatások sorrendje (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",									// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"vezérlõ (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"forgatható objektum",																				// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terén felületbõl",																					// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"szétáramló fény visszaverõdése (-1=implicit)",														// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"program aktív aplikáció",																			// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"pont távolsága",																					// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"pont szöge",																						// vıpoèet úhlu bodu
IDF_POLAR_X,				"pont X koordinátája",																				// souøadnice X bodu
IDF_POLAR_Y,				"pont Y koordinátája",																				// souøadnice Y bodu
IDF_FILE_LOGIC,				"logikai érték",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"textúrák csiszolása (1=nem)",																		// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"pontos idõ számláló",																				// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"szétáramló fény",																					// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"nagyított textúrák kiszûrése",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"távolított textúrák kiszûrése",																	// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"objektumok felületének kitöltése",																	// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"objektum megvilágítása",																			// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"objektum folytonos árnyékolása",																	// mód stínování
IDF_DIRECT3D_OMINFILTER,	"objektum kicsinyített textúráinak kiszûrése",														// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"objektum nagyított textúráinak kiszûrése",															// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"objektum távolított textúráinak kiszûrése",														// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"objektum látható oldala (0=mind kettõ, 1=eleje, 2=hátulja)",										// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"kialakít",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"objektum normalizálása",																			// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"kör",																								// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"háromszög",																						// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"torusz (paraméter = átmérõ 0-tól 1-ig)",															// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"statikus 2D objektum",																				// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"félteke",																							// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interfészvezérlõ (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",						// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"eltelt idõ",																						// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"renderelés gyorsasága",																			// rychlost renderování
IDF_DIRECT3D_FREE,			"szabad videomemória",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D kép",																							// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"textúrák",																							// skupina textur
IDF_DIRECT3D_STAGE,			"fokozat (0-tól 7-ig)",																				// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"színnel való mûvelet (1=kikapcs., 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",								// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"1. szín argumentuma (0=szín, 1=eredmény, 2=textúra, 3=faktor, 16=inverzitás)",						// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"2. szín argumentuma (0=szín, 1=eredmény, 2=textúra, 3=faktor, 16=inverzitás)",						// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"alfa mûvelet (1=kikapcs., 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"1. alfa argumentum (0=szín, 1=eredmény, 2=textúra, 3=faktor, 16=inverzitás)",						// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"2. alfa argumentum (0=szín, 1=eredmény, 2=textúra, 3=faktor, 16=inverzitás)",						// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"vízszintes címzési mód (1=ismétlés, 2=tükrözés, 3=lemetszés)",										// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"függõleges címzési mód (1=ismétlés, 2=tükrözés, 3=lemetszés)",										// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"távoli textúrák kifinomítása (0=átlagos)",															// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"csonkakúp (paraméter = átmérõ 0-tól 1-ig)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"textúrák faktorának színe",																		// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alfa összetevõ (0=átlátszóság egész 1=szín)",														// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"távoli textúrák fokozatának száma (0=mind)",														// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"renderelési csoport (0-7=objektumok, 8-11=átláthatóság, 12-15=képek)",								// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"mélységesen osztályozni a renderelési csoportot",													// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"elmenteni a mélységi információt",																	// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"mélység ellenõrzése (1 soha, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 mindig)",							// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"normál vektorok átszámítása (paraméter = finomítás szöge)",										// pøepoèet normál
IDF_DIRECT3D_RENDER,		"renderelés megjelenítés nélkül",																	// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"blokk a szövegbõl",																				// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"blokk elejének sora",																				// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"blokk elejének pozíciója",																			// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"blokk végének sora (-1=vége)",																		// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"blokk végének pozíciója (-1=vége)",																// pozice konce bloku
IDF_WINDOW_POS2,			"aktuális helyzet 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"nyomógombos kapcsoló kialakítása",																	// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"táblázat kialakítása (paraméter = oszlopok listája)",												// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"táblázat oszlopának szélessége",																	// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"árnyék kiterjedése (0=kikapcsolva)",																// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"táblázat oszlopának szöveg igazítása (0=balra, 1=jobbra, 2=középre)",								// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"vízszintes görgetõsáv kialakítása",																// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"függõleges görgetõsáv kialakítása",																// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"színek felcserélése",																				// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"elsõ szín",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"második szín",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"szín helyettesítése",																				// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"öreg szín",																						// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"új szín",																							// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"kép nyomtatása",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"objektum csökkent fokozatú részletességgel (-1=nincs)",											// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"távolság a részletesség fokozatának csökkentésére",												// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"hozzáad mintát a morfolásra (-1=újra indítani)",													// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"morfolás fokozata (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"objektum fényvisszaverõdés",																		// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dinamikus adatcsere DDE",																			// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"szerver neve/szerverek listája",																	// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"téma neve/témák listája",																			// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"elem neve/elemek listája",																			// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"a program elemet kínál (szerver)",																	// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"elem típusa (0-tól  7-ig, -1=nem érvényes elem)",													// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) szám",																							// èíslo DDE
IDF_DDE_BOOL,				"(1) logikai érték",																				// pøíznak DDE
IDF_DDE_TEXT,				"(2) szöveg",																						// text DDE
IDF_DDE_ICON,				"(3) mezõ",																							// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) kép",																							// obrázek DDE
IDF_DDE_SOUND,				"(5) hang",																							// zvuk DDE
IDF_DDE_MUSIC,				"(6) zene",																							// hudba DDE
IDF_DDE_SPRITE,				"(7) szprájt",																						// sprajt DDE
IDF_DDE_EXECUTE,			"parancs a végrehajtásra",																			// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL könyvtárak",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"könyvtár beolvasása",																				// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"könyvtár felszabadítása",																			// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"függvény importálása",																				// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"könyvtár identifikátora",																			// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"függvény neve",																					// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"paraméterek száma",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"függvény végrehajtása",																			// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"memória blokk létrehozása",																		// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"memória blokk felszabadítása",																		// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"memória blokk méretének változtatása",																// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"memória blokk címe",																				// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"új méret",																							// nová velikost bloku pamìti
IDF_MEMORY_READ,			"olvasás mutatója",																					// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"írás mutatója",																					// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"adat másolás",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"adatok összehasonlítása",																			// porovnání bloku dat
IDF_MEMORY_BYTES,			"elõjeles byte",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"elõjel nélküli byte",																				// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"elõjeles szó",																						// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"elõjel nélküli szó",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"elõjeles 3-byte",																					// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"elõjel nélüli 3-byte",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"elõjeles dupla szó",																				// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"elõjel nélküli dupla szó",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"reális szám 4 byte",																				// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"reális szám 8 byte",																				// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logikai érték",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"bináris nullával lezárt szöveg",																	// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"mutató a bináris nullával lezárt szövegre",														// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"szöveg megadott hosszal",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"szöveg mérete megadott hosszal",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"adatok olvasása az állományból",																	// ètení dat ze souboru
IDF_MEMORY_SAVE,			"adatok írása az állományba",																		// zápis dat do souboru
IDF_WINDOW_HANDLE,			"ablak elemének identifikátora",																	// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"hívott C konvenció",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"üzenet ablak kialakítása",																			// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"konfiguráció",																						// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"konfigurációs állomány",																			// jméno konfiguraèního souboru
IDF_INI_SECTION,			"paraméter osztály",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"paraméter neve",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"szöveges paraméter olvasása/írása",																// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"egész szám paraméter olvasása/írása",																// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"kulcsok csoportja (1=CURRENT_USER, 2=LOCAL_MACHINE)",												// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"kulcs neve",																						// plnı mázev klíèe registrù
IDF_REG_VALUE,				"elem neve",																						// název datové poloky
IDF_REG_STRING,				"szöveges elem olvasása/írása",																		// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"egész számú elem olvasása/írása",																	// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"3D objektum kialakítása a memória blokkból",														// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"csúcsok száma",																					// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"csúcsok",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normál vektorok (0=auto)",																			// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"textúrák térképezése (0=nincs)",																	// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"színek (0=nincs)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"sík felületek száma",																				// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"sík felületek",																					// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"textúra állományból",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"memória blokk 3D objektumból",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"utód (-1=elsõ, -2=szülõ)",																			// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
