// Nìmecky (German)
// 1252
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Gemeinsame Variable und Funktionen",																// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Lokale Variable und Funktionen",																	// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Grundelemente, Papierkorb",																		// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Bibliothek der Variablen und Funktionen",															// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"grundlegende Variable und Funktionen",																// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Neues Programm",																					// implicitní název nového programu
IDN_NEWDIR_NAME,			"Neuer Ordner",																						// implicitní název nové sloky
IDN_TEXTVZOR,				"[Beispiele]",																						// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Angewendet",																						// zobrazuje poèet pouití prvku
IDT_RADEK,					"Zeile",																							// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"Spalte",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"eingeschaltet",																					// text editoru hodnoty pøepínaèe
IDN_DATUM,					"Datum",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"Uhrzeit",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"Größe",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"frei",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"wiederholung",																						// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"regelmäßig",																						// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMO",																								// oznaèení DEMO verze
IDN_PROFI,					"Professional",																						// oznaèení verze Professional
IDN_LITE,					"Lite",																								// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Datei",																							// volba k vyvolání menu "Soubor"
IDN_START0,					"S&tart\tF5",																						// volba pro spuštìní programu
IDN_START,					"Startet das Programm.\nStart",																		// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"Ö&ffnen\tStrg+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Öffnet das Programm für die Bearbeitung.\nÖffnen",													// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Neu...\tStrg+N",																					// volba pro zaloení nového programu
IDN_NEW,					"Erstellt ein neues Programm.\nNeu",																// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"&Umbenennen...\tAlt+Enter",																		// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Benennt das Programm/den Ordner um (Musterprogramme und Ordner können nicht umbenannt werden).\nUmbenennen",	// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"&Kopieren...\tStrg+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Kopiert das gewählte Programm unter einen anderen Namen.\nKopieren",								// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"Neuer &Ordner...\tStrg+P",																			// volba k vytvoøení nové sloky
IDN_PATH,					"Erstellt einen neuen Ordner für die Programme.\nNeuer Ordner",										// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Löschen...\tEntf",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Löscht das Programm oder den Ordner (Musterprogramme und Ordner können nicht gelöscht werden).\nLöschen",	// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Kurzna&men",																						// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Programme und Bibliothek-Dateien wird gestalten mit Namen verkürzen auf 8 Zeichen.\nKurznamen",	// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Beenden\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Beendet die Applikation Peter.\nBeenden",															// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"Schrift&art",																						// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Schriftart der Programm&auswahl...",																// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Ändert die Darstellung der Schriftart im Fenster der Programm&auswahl.\nSchriftart der Programmauswahl",	// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Schriftart des Programm&editors...",																// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Ändert die Darstellung der Schriftart im Fenster des Programm&editors.\nSchriftart des Programmeditors",	// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Schriftart des &Texteditors...",																	// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Ändert die Darstellung der Schriftart im Fenster des Text&editors.\nSchriftart des Texteditors",	// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Schriftart des &Menüs...",																			// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Ändert die Darstellung der Schriftart des Menüs.\nSchriftart des Menüs",							// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Schriftart der &Statusleiste...",																	// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Ändert die Darstellung der Schriftart der Statusleiste.\nSchriftart der Statusleiste",				// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"S&prache",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automatisch",																						// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Wählt die Sprache automatisch nach der Systemeinstellung aus.\nAutomatisch",						// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Vorangehend\tCtrl+F9",																			// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Schaltet zwischen zwei zuletzt wählen Sprache.\nVorangehend",										// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Bulgarisch (Bulgarija)",																			// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Schaltet die Applikation Peter auf bulgarische Sprache um.\nBulgarisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"&Tschechisch (Cesky)",																				// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Schaltet die Applikation Peter auf tschechische Sprache um.\nTschechisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"&Dänisch (Danmark)",																				// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Schaltet die Applikation Peter auf dänische Sprache um.\nDänisch",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"Deutsch",																							// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Schaltet die Applikation Peter auf deutsche Sprache um.\nDeutsch",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Griechisch (Hellás)",																				// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Schaltet die Applikation Peter auf griechische Sprache um.\nGriechisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"&Englisch (English)",																				// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Schaltet die Applikation Peter auf englische Sprache um.\nEnglisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"S&panisch (España)",																				// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Schaltet die Applikation Peter auf spanische Sprache um.\nSpanisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finnisch (Finland)",																				// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Schaltet die Applikation Peter auf finnische Sprache um.\nFinnisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"&Französisch (France)",																			// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Schaltet die Applikation Peter auf französische Sprache um.\nFranzösisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"&Ungarisch (Magyar)",																				// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Schaltet die Applikation Peter auf ungarische Sprache um.\nUngarisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Isländisch (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Schaltet die Applikation Peter auf isländische Sprache um.\nIsländisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Italienisch (Italy)",																				// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Schaltet die Applikation Peter auf italienische Sprache um.\nItalienisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Holländisch (Nederland)",																			// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Schaltet die Applikation Peter auf holländische Sprache um.\nHolländisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Norwegisch (Norge)",																				// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Schaltet die Applikation Peter auf norwegische Sprache um.\nNorwegisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Polnisch (Po polsku)",																				// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Schaltet die Applikation Peter auf polnische Sprache um.\nPolnisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portugiesisch (Portugal)",																			// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Schaltet die Applikation Peter auf portugiesische Sprache um.\nPortugiesisch",						// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Rumänisch (România)",																				// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Schaltet die Applikation Peter auf rumänische Sprache um.\nRumänisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&Russisch (Po-rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Schaltet die Applikation Peter auf russische Sprache um.\nRussisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Serbokroatisch (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Schaltet die Applikation Peter auf serbokroatische Sprache um.\nSerbokroatisch",					// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"&Slowakisch (Po slovensky)",																		// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Schaltet die Applikation Peter auf slowakische Sprache um.\nSlowakisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albanisch (Shqipërisë)",																			// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Schaltet die Applikation Peter auf albanische Sprache um.\nAlbanisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Schwedisch (Swerige)",																				// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Schaltet die Applikation Peter auf schwedische Sprache um.\nSchwedisch",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Türkisch (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Schaltet die Applikation Peter auf türkische Sprache um.\nTürkisch",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"V&ietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Hilfe",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Hilfe\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Zeigt die Hilfe zum gewählten Element an.\nHilfe",													// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"Hilfe&themen",																						// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Zeigt die Hilfethemen an.\nHilfethemen",															// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Suchen in Hilfe",																					// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Sucht in Hilfe.\nSuchen in Hilfe",																	// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"Ü&ber die Applikation Peter",																		// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Zeigt Informationen über die Applikation Peter an, Versionsnummer und Copyright.\nÜber die Applikation Peter",	// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"S&chließen\tStrg+O",																				// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Schließt das bearbeitete Programm und öffnet ein anderes.\nSchließen",								// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Speichern\tStrg+S",																				// volba k uloení programu pøi editaci
IDN_SAVE,					"Speichert die im Programm durchgeführten Änderungen.\nSpeichern",									// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"&Nicht startbar speichern\tStrg+Alt+S",															// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Speichert das nicht startbare Programm (kleinerer Größe).\nNicht &startbar speichern",				// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Speichern &unter...\tStrg+Umschalt+S",																// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Speichert das Programm in die Datei mit einem anderem Namen oder auf ein anderes Laufwerk.\nSpeichern unter",	// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribution...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Speichert die unbearbeitbare Programmdistributionsversion (nur bei der Lizenz Professional).\nDistribution",	// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Ex&port...",																						// volba k exportování programu
IDN_EXPORT,					"Export das programm zum text form.\nExport",														// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Import das programm von text form.\nImport",														// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"&Bearbeiten",																						// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Rückgängig\tStrg+Z",																				// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Macht den letzten Vorgang rückgängig.\nRückgängig",												// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Wiederherstellen\tStrg+Y",																		// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Stellt den rückgängig gemachten Vorgang wieder her.\nWiederherstellen",							// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"A&usschneiden\tStrg+X",																			// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Schneidet die Auswahl aus und überträgt sie in die Zwischenablage.\nAusschneiden",					// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Kopieren\tStrg+C",																				// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Kopiert die Auswahl in die Zwischenablage.\nKopieren",												// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"&Einfügen\tStrg+V",																				// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Fügt den Inhalt der Zwischenablage an der Einfügemarke ein.\nEinfügen",							// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Löschen\tEntf",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Löscht die Auswahl.\nLöschen",																		// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"&Alles markieren\tStrg+A",																			// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Markiert alles.\nAlles markieren",																	// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Benützt den Dithering beim Import und der Verkleinerung des Bildes.\nDithering",					// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Ansicht",																							// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"Ver&größern\tStrg+[+]",																			// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Vergrößert den Maßstab der Ansicht.\nVergrößern",													// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Ver&kleinern\tStrg+[-]",																			// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Verkleinert den Maßstab der Ansicht.\nVerkleinern",												// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"Vor&hergehende Bearbeitung\tStrg+nach oben",														// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Kommt zu dem vorhergehend bearbeiteten Element zurück.\nVorhergehende Bearbeitung",				// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"Nach&folgendes Bearbeiten\tStrg+nach unten",														// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Kommt zu dem nachfolgend bearbeiteten Element zurück.\nNachfolgendes Bearbeiten",					// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"Text &suchen...\tStrg+F",																			// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Sucht den angegebenen Text.\nText suchen",															// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"A&ufwärts Text\tUmschalt+F3",																		// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Sucht das vorige Auftreten des gesuchten Textes.\nAufwärts Text",									// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"A&bwärts Text\tF3",																				// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Sucht das nächste Auftreten des gesuchten Textes.\nAbwärts Text",									// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Programm",																						// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Zusperren",																						// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Sperrt das Element gegen die Änderung zu.\nZusperren",												// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Ausschalten",																						// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Schaltet die Funktion des Elementes aus.\nAuschalten",												// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Beschriftung\tAlt+Enter",																			// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Bearbeitet die Beschriftung des Elementes.\nBeschriftung",											// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Implizite B&eschriftung",																			// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Gebraucht die implizite Beschriftung des Elementes.\nImplizite Beschriftung",						// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Ikon",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Bearbeitet das Ikon des Elementes.\nIkon",															// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Implizites I&kon",																					// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Gebraucht das implizite Ikon des Elementes.\nImplizites Ikon",										// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"&Deklaration",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Findet die Deklaration des Elementes.\nDeklaration",												// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"&Voriger Gebrauch",																				// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Findet den vorigen Gebrauch des Elementes.\nVoriger Gebrauch",										// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"&Nächster Gebrauch",																				// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Findet den nächsten Gebrauch des Elementes.\nNächster Gebrauch",									// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"Bi&ld",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"&Dimensionen...",																					// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Stellt die Gesamtdimensionen ein.\nDimensionen",													// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Raster",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Schaltet die Darstellung des Orientierungsrasters ein oder aus.\nRaster",							// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"&Bearbeiten...",																					// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Bearbeitet das Bild oder seinen Teil (Änderung des Größe, Drehung, Farben).\nBearbeiten",			// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"Block&abdruck",																					// volba k otisku bloku do obrázku
IDN_OTISK,					"Druckt den Block ins Bild ab.\nBlockabdruck",														// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horizontal",																						// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Spiegelt das Bild oder seinen Teil horizontal.\nHorizontal",										// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertikal",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Spiegelt das Bild oder seinen Teil vertikal.\nVertikal",											// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"&Links",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Dreht das Bild nach links (um 90 Grad entgegen dem Uhrzeigersinn).\nLinks",						// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"Re&chts",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Dreht das Bild nach rechts um (um 90 Grad im Uhrzeigersinn).\nRechts",								// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"&Zweifaches",																						// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Vergrößert die Größe des Bildes oder sein Teils auf das Zweifache.\nZweifaches",					// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"Häl&fte",																							// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Verkleinert die Größe des Bildes oder seines Teils auf die Hälfte.\nHälfte",						// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"&Größe...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Ändert die Größe des Bildes oder seines Teils wählbar.\nGröße",									// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"Verwechsl&ung",																					// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Wechselt im Bild oder in seinem Teil die Farben für die linke und rechte Maustaste.\nVerwechslung",	// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Ersatz",																							// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Ersetzt im Bild oder seinem Teil die Farbe der rechten Maustaste mit der Farbe für die linke Maustaste.\nErsatz",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Instrumente",																						// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Feder",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Zeichnet mit der Feder.\nFeder",																	// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"&Linie",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Zeichnet die Linie.\nLinie",																		// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"&Rechteck",																						// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Zeichnet das Rechteck.\nRechteck",																	// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"Ausgefülltes Re&chteck",																			// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Zeichnet das ausgefüllte Rechteck.\nAusgefülltes Rechteck",										// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Kreislinie",																						// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Zeichnet die Kreislinie.\nKreislinie",																// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Kre&is",																							// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Zeichnet den Kreis.\nKreis",																		// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Ellipse",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Zeichnet die Ellipse.\nEllipse",																	// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"&Oval",																							// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Zeichnet das Oval.\nOval",																			// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"Ku&gel",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Zeichnet die Kugel.\nKugel",																		// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"&Auswahl",																							// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Markiert den gewählten Teil als ausgewählt.\nAuswahl",												// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"&Spray",																							// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Zeichnet mit der Sprayfarbe.\nSpray",																// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"&Pipette",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Stellt die Farbe unter dem Kursor als ausgewählt ein.\nPipette",									// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"Füll&ung",																							// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Füllt die Fläche mit Farbe.\nFüllung",																// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Text",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Schreibt den Text aus.\nText",																		// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Stärke",																							// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Linienstärke &1 Punkt",																			// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Zeichnet die Linien mit einer Stärke von 1 Punkt.\nStärke 1 Punkt",								// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Linienstärke &2 Punkte",																			// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Zeichnet die Linien mit einer Stärke von 2 Punkten.\nStärke 2 Punkte",								// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Linienstärke &5 Punkte",																			// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Zeichnet die Linien mit einer Stärke von 5 Punkten.\nStärke 5 Punkte",								// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Linienstärke &9 Punkte",																			// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Zeichnet die Linien mit einer Stärke von 9 Punkten.\nStärke 9 Punkte",								// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Linienstärke 21 &Punkte",																			// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Zeichnet die Linien mit einer Stärke von 21 Punkten.\nStärke 21 Punkte",							// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"&Fläche",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Bearbeiten",																						// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Schaltet die Betriebsart der Bearbeitung der Flächenfelder ein oder aus.\nBearbeiten",				// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Füllung",																							// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Schaltet die Betriebsart der Füllung der Fläche mit dem Feld ein oder aus.\nFüllung",				// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Gegenstände",																						// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Bearbeitet der Gegenstände auf der Fläche.\nGegenstände",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Umschalter &1",																					// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Bearbeitet den Umschalter 1.\nUmschalter 1",														// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Umschalter &2",																					// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Bearbeitet den Umschalter 2.\nUmschalter 2",														// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Umschalter &3",																					// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Bearbeitet den Umschalter 3.\nUmschalter 3",														// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Umschalter &4",																					// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Bearbeitet den Umschalter 4.\nUmschalter 4",														// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Umschalter &5",																					// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Bearbeitet den Umschalter 5.\nUmschalter 5",														// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"&Nummer 1",																						// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Bearbeitet den numerischen Wert 1 (Bereich 0 bis 1023).\nNummer 1",								// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"N&ummer 2",																						// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Bearbeitet den numerischen Wert 2 (Bereich 0 bis 1023).\nNummer 2",								// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Nu&mmer 3",																						// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Bearbeitet den numerischen Wert 3 (Bereich 0 bis 127).\nNummer 3",									// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"&Sprite",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Eigenschaften",																					// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Stellt die Eigenschaften des Sprite (Anzahl der Phasen, Richtungen, ...) ein.\nEigenschaften",		// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Lässt die Betriebsart des Sprite-Testes an.\nTest",												// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"A&udio",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Wiedergeben",																						// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Lässt die Wiedergabe an.\nWiedergeben",															// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"&Anhalten",																						// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Hält die Wiedergabe an.\nAnhalten",																// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"&Beenden",																							// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Stellt die Wiedergabe ab.\nBeenden",																// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"Wieder&holung",																					// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Schaltet die Wiederholung der Wiedergabe ein oder aus.\nWiederholung",								// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"Au&fnehmen",																						// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Lässt das Aufnahme an.\nAufnehmen",																// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Musik",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Rückwärts",																						// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Rückt der Wiedergabe um 10 Sekunden nach hinten.\nRückwärts",										// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Vorwärts",																						// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Rückt der Wiedergabe um 10 Sekunden nach vorne.\nVorwärts",										// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"Über die Applikation Peter",																		// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Peter Version",																					// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Ing. Miroslav Nemecek",														// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Roznov pod Radhostem",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Tschechische Republik",																			// Èeská Republika
IDC_DEMOTEXT1,				"Die Demoversion ermöglicht weder das Speichern der Programme noch das Anlassen ",					// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"neuer oder geänderter Programme. Die Bearbeitungsmöglichkeiten,",									// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"die Hilfe und die Speicherung in die Bibliothek sind voll funktionell.",							// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Aktuelle Informationen über das Produkt erhalten Sie unter der Internet-Adresse:",					// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Bestellungen sind an folgende Adresse zu senden:",													// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LIZENZ",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"uneingeschränkt",																					// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"für 1 Computer",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"Computer",																							// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"Computer",																							// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Die Lite-Version bietet eine begrenzte programmatische Ausstattung",								// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(unfunktionelle Elemente sind mit grauen Ikonen bezeichnet).",										// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"Die Lite-Version ist eine FREEWARE; sie kann für private Zwecke frei",								// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"verbreitet werden. Für kommerzielle und schulische Nutzung ist die",								// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"Entrichtung einer Lizenzgebühr erforderlich (sieh www.gemtree.com).",								// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Text suchen",																						// titulek okna hledání textu
IDN_FINDTEXT,				"Geben Sie den gesuchten Text ein:",																// vızva k zadání textu k hledání
IDN_CANCEL0,				"Abbrechen",																						// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Dimensionen der Fläche",																			// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Breite:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Höhe:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Kann nicht geöffnet werden",																		// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"Das Programm kann nicht geöffnet werden.",															// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Anscheinend es ist bereits mit einem anderen Programm geöffnet",									// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"oder der Zugriff auf die Datei ist verboten.",														// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Lesefehler",																						// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Fehler beim Lesen des Programmes.",																// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"Das Programm ist beschädigt oder es wurde mit einer höheren",										// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"Editorversion erstellt und darum muss es nicht richtig funktionieren.",							// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Unfördern Befehle",																				// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Warnung: Das Programm verwendet Befehle, die von der Lite-Version",								// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"nicht unterstützt werden. Durch Speicherung des Programms",										// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"kann dieses funktionsunfähig gemacht werden.",														// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Bearbeiten des Bildes oder seines ausgewählten Teiles",											// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Spiegeln",																							// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horizontal",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertikal",																							// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Drehen",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 Pi (+90 Grad)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 Pi (-90 Grad)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 Pi (+67.5 Grad)",																				// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 Pi (-67.5 Grad)",																				// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 Pi (+60 Grad)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 Pi (-60 Grad)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 Pi (+45 Grad)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 Pi (-45 Grad)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 Pi (+30 Grad)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 Pi (-30 Grad)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 Pi (+22.5 Grad)",																				// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 Pi (-22.5 Grad)",																				// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Vergrößerung",																						// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Zweifaches",																						// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Hälfte",																							// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Wählbar",																							// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Farben",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Linke <-> rechte Taste",																			// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Linke -> rechte Taste",																			// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Dimensionen des Bildes",																			// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Dimensionen angegeben",																			// nadpis rámeèku volby jednotky
IDC_KROK,					"In &Schritten",																					// [1] volba jednotky v krocích
IDC_BOD,					"In &Punkten",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Vergrößerung des Bildes oder seines Teiles",														// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Aktuelle Dimensionen:",																			// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"Schritte",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"Punkte",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Neue Dimensionen",																					// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Breite:",																							// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Höhe:",																							// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"In Schritten",																						// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"In Punkten",																						// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"Prozentuell",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Ursprüngliches Verhältnis der Seiten (Verhältnis Breite/Höhe) bewahren",							// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Kanten verfeinern (genaue, aber langsame Überleitung)",											// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (für Lichtbilder einschalten, für Zeichnungen ausschalten)",								// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Auswahl der Farbe",																				// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Das Programm kann nicht erstellt werden",															// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Das Programm konnte nicht erstellt werden.",														// 1. øádek hlášení
IDN_JINE_JMENO,				"Versuchen Sie einen anderen Namen.",																// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Programm löschen",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Wollen Sie tatsächlich das ausgewählte Programm löschen?",											// 1. øádek hlášení
IDN_SELECT_DEL2,			"WARNUNG: Das Programm kann nicht mehr wiederhergestellt werden!",									// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Löschen des Ordners",																				// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Wollen Sie tatsächlich den ausgewählten Ordner löschen?",											// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Der Ordner kann nicht gelöscht werden",															// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Der Ordner kann nicht gelöscht werden, solange er nicht leer ist.",								// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Das Programm kann nicht gelöscht werden",															// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"Das Programm kann nicht gelöscht werden, es ist schreib- und löschgeschützt.",						// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Neuer Ordner",																						// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Wie ist der neue Name des Ordners?",																// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Der Ordner kann nicht erstellt werden",															// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Der Ordner konnte nicht erstellt werden.",															// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Der Ordner existiert",																				// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Vorsicht, ein solcher Ordner existiert schon.",													// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Das Programm existiert",																			// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Vorsicht, so ein Programm existiert schon.",														// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Neues Programm",																					// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Wie heißt das neue Programm?",																		// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Programmkopie",																					// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Wie heißt das kopierte Programm?",																	// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Sprite-Eigenschaften",																				// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animation",																						// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Verzögerung zwischen den Phasen:",																	// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"Millisekunden",																					// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Phasen pro Schritt (0 = sofort):",																	// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Darstellungsebene (0 = Gegenstände):",																// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Bilderzahl",																						// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Phasen für den Ruhezustand:",																		// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Phasen für die Bewegung:",																			// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Richtungen:",																						// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Bildmaß",																							// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Bildbreite:",																						// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Bildhöhe:",																						// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Sprite-Test",																						// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Fehler des Speicherns",																			// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"Das Programm kann nicht gespeichert werden.",														// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Überprüfen Sie, ob es nicht gestartet ist",														// 2. øádek hlášení
IDN_WRITEERR3,				"oder ob es nicht schreibgeschützt ist.",															// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"Speichern Sie das Programm im Bedarfsfall",														// 4. øádek hlášení
IDN_WRITEERR5,				"unter einem anderen Namen oder auf ein anderes Laufwerk.",											// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Das Programm wurde verändert",																		// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Der Programm wurde verändert.\nWollen sie die Änderungen speichern?",								// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Das Element wird verwendet",																		// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Warnung: das zu löschende Element wird im Programm verwendet.\nDurch seine Löschung löschen Sie auch etwaige Unterzweige des Elementes.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Unwiederherstellbares Löschen",																	// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Warnung: sie löschen ein Bibliothek-Element.\nDie Löschung ist unwiederbringlich, das Element kann nicht wiederhergestellt werden.",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Speicherplatzmangel",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Es gibt nicht genügend Speicherplatz zur Durchführung der gewünschten Operation!\n\nMachen Sie Raum auf der Windows-System-Festplatte frei,\nbeziehungsweise überprüfen Sie die Einstellung des virtuellen Windows-Speichers.\nDas Programm kann sich nun in einem instabilen Zustand befinden,\ndarum beenden Sie es möglichst schnell.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"Ich bedauere, das Programm wird wegen Speicherplatzmangel beendet!",								// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Beschädigte Lizenzdaten",																			// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Die Lizenzdaten wurden beschädigt. Starten Sie wieder den Installator der Applikation Peter für die Reparatur der Lizenzdaten.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Ende des zeitlich begrenzten Betriebes",															// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Der zeitlich begrenzte Betrieb der Applikation Peter ist abgelaufen.",								// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Es nähert sich das Ende des zeitlich begrenzten Betriebes",										// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"Der Betrieb der Applikation Peter ist zeitlich begrenzt.\nDie Anzahl der übrigbleibenden Tage bis zum Betriebsende:",	// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"Systemfehler",																						// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Mangel an Systemmitteln zum Starten des Programmes PETER.EXE.",									// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Das Programm ist beschädigt",																		// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Das Programm PETER.EXE ist beschädigt, es kann nicht gestartet werden.",							// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"In eine andere Datei speichern",																	// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programme",																						// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Alle Dateien",																						// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Die Distributionsversion des Programmes speichern",												// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Das Programm existiert schon",																		// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Warnung: die zu speichernde Datei dieses Namens existiert schon.\n\nSie speichern eine nicht bearbeitbare Programmversion.\nWenn das zu speichernde Programm ein Quellprogramm ist,\nwird die Programm-Quellform unwiederbringlich verloren.\n\nWollen Sie fortsetzen und die Datei umschreiben?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Nicht startbares Programm",																		// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Dieses Programm wurde mit dem Programmiermittel Peter hergestellt.\nJetzt ist es in einer nicht startbaren Form gespeichert.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Schrifteinstellung",																				// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Muster:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Schließen der gewählten Wörterbücher.",															// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Standardschrift",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Fett",																								// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Kursiv",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Unterstrichen",																					// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Durchgestrichen",																					// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Serifenlos",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"Mit Serifen",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Mit festem Abstand",																				// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Aus der Liste aussuchen",																			// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Liste der Schriftarten:",																			// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Höhe:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Breite[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Darstellung",																						// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Aussehen",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Ordner und Name zu Programm-export",																// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Name zu Programm-import",																			// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Peter Programm",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"leeres Feld",																						// prázdnı implicitní pøedmìt
IDF_GROUP,					"Gruppe",																							// skupina prvkù
IDF_IF,						"bedingter Vollzug der Befehle",																	// záhlaví podmínky
IDF_IF_COND,				"wenn es gilt, dass",																				// test podmínky (IF)
IDF_IF_YES,					"dann führe durch",																					// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"sonst führe durch",																				// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"bedingte Wiederholung der Befehle",																// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"solange es gilt",																					// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"wiederhole die Befehle",																			// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"brich die Wiederholung ab",																		// pøerušení smyèky (BREAK)
IDF_MINUS,					"negatives Vorzeichen",																				// záporné znaménko "-" v èísle
IDF_CASE,					"Mehrstufige Verzweigung der Befehle",																// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"für den Wert des Ausdruckes",																		// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"führe die Befehle aus, falls",																		// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"der Ausdruck ist gleich dem Wert",																	// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"ansonsten führe die Befehle aus",																	// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"numerische Konstante",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"Exponent",																							// exponent v èísle
IDF_EQU,					"ist gleich",																						// podmínka =
IDF_NEQU,					"ist nicht gleich",																					// podmínka <>
IDF_EQGR,					"ist größer oder gleich",																			// podmínka >=
IDF_EQLT,					"ist kleiner oder gleich",																			// podmínka <=
IDF_GR,						"ist größer als",																					// podmínka >
IDF_LT,						"ist kleiner als",																					// podmínka <
IDF_AND,					"und gleichzeitig",																					// logickı souèin
IDF_OR,						"oder",																								// logickı souèet
IDF_XOR,					"entweder-oder (ausschließliches \"oder\")",														// logickı vıhradní souèet
IDF_NOT,					"wenn es nicht gilt, dass",																			// logická negace
IDF_ADD,					"Summe",																							// souèet èísel
IDF_SUB,					"Differenz",																						// rozdíl èísel
IDF_MUL,					"Vielfaches",																						// násobek èísel
IDF_DIV,					"Anteil",																							// podíl èísel
IDF_REAL,					"Nummer",																							// èíselná promìnná
IDF_ICON,					"Gegenstand",																						// pøedmìtová promìnná
IDF_SND,					"Audio",																							// zvuková promìnná
IDF_MUS,					"Musik",																							// hudební promìnná
IDF_FNC,					"Funktion",																							// funkce
IDF_MAP,					"Fläche",																							// promìnná plochy
IDF_SPRITE,					"Sprite",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"Programmsteuerung - Erweiterung",																	// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"Text",																								// textová promìnná
IDF_WINDOWS,				"Fenster",																							// skupina prvkù pro øízení oken
IDF_PAR,					"Eingangsvariable",																					// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"Ausgangsvariable",																					// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"Fläche - Erweiterung",																				// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"Liste",																							// záhlaví seznamu (LIST)
IDF_OPER,					"Programmsteuerung",																				// skupina prvkù pro øízení programu
IDF_KROK,					"Schritt",																							// Petøík popojít o krok vpøed
IDF_VLEVO,					"links",																							// Petøík otoèit doleva
IDF_VPRAVO,					"rechts",																							// Petøík otoèit doprava
IDF_VZAD,					"nach hinten",																						// Petøík otoèit vzad
IDF_PETRIK,					"Peter",																							// skupina prvkù Petøíka
IDF_BOOL,					"Flag",																								// logická promìnná
IDF_TEXT_CONST,				"Textkonstante",																					// textová konstanta
IDF_TRUE,					"ja",																								// logickı pøíznak TRUE
IDF_FALSE,					"nein",																								// logickı pøíznak FALSE
IDF_PETRA,					"Luzia",																							// skupina prvkù Lucky
IDF_PETRA_KROK,				"Schritt",																							// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"links",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"rechts",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"nach hinten",																						// Lucka otoèit vzad
IDF_RYCHLE,					"sichtbar",																							// viditelnost Petøíka
IDF_EXIT,					"Ende der Funktion",																				// pøerušení funkce
IDF_PETRA_RYCHLE,			"sichtbar",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"Audio und Musik",																					// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"Gegenstand vor Peter",																				// pøedmìt pøed Petøíkem
IDF_SMER,					"Richtung",																							// smìr otoèení Petøíka
IDF_POZICEX,				"horizontale Position",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"vertikale Position",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"Gegenstand vor Luzia",																				// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"Richtung",																							// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"horizontale Position",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"vertikale Position",																				// vertikální souøadnice Lucky
IDF_CONST,					"Berechnungen",																						// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"arithmetische Operationen",																		// skupina èíselnıch operátorù
IDF_FUNC,					"Funktionen",																						// skupina èíselnıch funkcí
IDF_POROVNANI,				"Vergleich",																						// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logische Operationen",																				// skupina logickıch prvkù
IDF_MOD,					"Modulo",																							// èíselnı operátor modulo
IDF_SIN,					"Sinus",																							// funkce sinus
IDF_COS,					"Kosinus",																							// funkce kosinus
IDF_TG,						"Tangens",																							// funkce tangens
IDF_COTG,					"Kotangens",																						// funkce kotangens
IDF_ARCSIN,					"Arkussinus",																						// funkce arcus sinus
IDF_ARCCOS,					"Arkuskosinus",																						// funkce arcus kosinus
IDF_ARCTG,					"Arkustangens",																						// funkce arcus tangens
IDF_ARCCOTG,				"Arkuskotangens",																					// funkce arcus kotangens
IDF_PI,						"Pi",																								// Ludolfovo èíslo (pí)
IDF_INTEGER,				"ganzzahliger Teil",																				// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"dezimaler Teil",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"absoluter Wert",																					// funkce absolutní hodnoty
IDF_SQRT,					"zweite Wurzel",																					// funkce druhá mocnina
IDF_FACT,					"Fakultät",																							// funkce faktoriál
IDF_RAND,					"zufällige Nummer (0 <= x < 1)",																	// náhodné èíslo
IDF_EUL,					"Eulersche Konstante",																				// Eulerova konstanta (e)
IDF_DEGRAD,					"Überleitung Grad zu Radiant",																		// funkce konverze stupòù na radiány
IDF_RADDEG,					"Überleitung Radiant zu Grad",																		// funkce konverze radiánù na stupnì
IDF_LOG,					"dekadischer Logarithmus",																			// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"natürlicher Logarithmus",																			// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"natürliche exponentielle Funktion",																// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"Potenz",																							// operátor mocniny
IDF_UHEL,					"Winkel, Richtung",																					// skupina úhlù (smìrù)
IDF_UHEL0,					"nach rechts (0 Pi, das ist 0 Grad)",																// smìr vpravo
IDF_UHEL45,					"nach rechts oben (1/4 Pi, das ist 45 Grad)",														// smìr vpravo nahoru
IDF_UHEL90,					"nach oben (1/2 Pi, das ist 90 Grad)",																// smìr nahoru
IDF_UHEL135,				"nach links oben (3/4 Pi, das ist 135 Grad)",														// smìr vlevo nahoru
IDF_UHEL180,				"nach links (1 Pi, das ist 180 Grad)",																// smìr vlevo
IDF_UHEL225,				"nach links unten (1 1/4 Pi, das ist 225 Grad)",													// smìr vlevo dolù
IDF_UHEL270,				"nach unten (1 1/2 Pi, das ist 270 Grad)",															// smìr dolù
IDF_UHEL315,				"nach rechts unten (1 3/4 Pi, das ist 315 Grad)",													// smìr vpravo dolù
IDF_COMMAND,				"Steuerung",																						// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"Warten (ohne Vorgabe = 0.05 s)",																	// pøíkaz pro èekání
IDF_KLAV,					"Tastatur",																							// skupina ovládání klávesnice
IDF_KLAV_TEST,				"Die Taste ist gedrückt",																			// test stisknuté klávesy
IDF_KLAV_VKEY,				"Eingabe der Taste (wartet nicht auf das Drücken)",													// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"Eingabe des Zeichens (wartet nicht auf das Drücken)",												// vstup znaku bez èekání
IDF_KLAV_VK,				"Tasten",																							// skupina kódù kláves
IDF_KLAV_FX,				"Funktionstasten",																					// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"Buchstaben",																						// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numerische Tastatur",																				// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"Zeichentasten",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"Steuertasten",																						// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"Durchsichtigkeit",																					// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Einfg",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 Ende",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 nach unten",																						// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 Bild ab",																						// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 nach links",																						// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 nach rechts",																					// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Pos 1",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 nach oben",																						// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 Bild auf",																						// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			", Entf",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"x",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num",																								// kód numerické klávesy Num Lock
IDF_VK_1,					"1 !",																								// kód klávesy 1 !
IDF_VK_2,					"2 @ (2 \")",																						// kód klávesy 2 @
IDF_VK_3,					"3 # (3 §)",																						// kód klávesy 3 #
IDF_VK_4,					"4 $",																								// kód klávesy 4 $
IDF_VK_5,					"5 %",																								// kód klávesy 5 %
IDF_VK_6,					"6 ^ (6 &)",																						// kód klávesy 6 ^
IDF_VK_7,					"7 & (7 /)",																						// kód klávesy 7 &
IDF_VK_8,					"8 * (8 ( )",																						// kód klávesy 8 *
IDF_VK_9,					"9 (  (9 ) )",																						// kód klávesy 9 (
IDF_VK_0,					"0 ) (0 =)",																						// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~ (^ °)",																						// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _ (ß ?)",																						// kód klávesy - _
IDF_VK_ROVNITKO,			"= + (´ `)",																						// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ | (# \')",																						// kód klávesy \ |
IDF_VK_LLOMENA,				"[ { (ü Ü)",																						// kód klávesy [ {
IDF_VK_RLOMENA,				"] } (+ *)",																						// kód klávesy ] }
IDF_VK_STREDNIK,			"; : (ö Ö)",																						// kód klávesy ; :
IDF_VK_RCARKA,				"\' \" (ä Ä)",																						// kód klávesy ' "
IDF_VK_CARKA,				", < (, ;)",																						// kód klávesy , <
IDF_VK_TECKA,				". > (. :)",																						// kód klávesy . >
IDF_VK_LOMITKO,				"/ ? (- _)",																						// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"Windows-Menü links",																				// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Rücktaste",																						// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"lokales Menü",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"nach links",																						// kód klávesy Vlevo
IDF_VK_RIGHT,				"nach rechts",																						// kód klávesy Vpravo
IDF_VK_UP,					"nach oben",																						// kód klávesy Nahoru
IDF_VK_DOWN,				"nach unten",																						// kód klávesy Dolù
IDF_VK_INSERT,				"Einfg",																							// kód klávesy Insert
IDF_VK_DELETE,				"Entf",																								// kód klávesy Delete
IDF_VK_HOME,				"Pos 1",																							// kód klávesy Home
IDF_VK_END,					"Ende",																								// kód klávesy End
IDF_VK_PAGEUP,				"Bild auf",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Bild ab",																							// kód klávesy Page Down
IDF_VK_PRINT,				"Druck",																							// kód klávesy Print Screen
IDF_VK_SCROLL,				"Rollen",																							// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"Umschalt links",																					// kód klávesy Levı Shift
IDF_VK_CTRL,				"Strg links",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"Alt links",																						// kód klávesy Levı Alt
IDF_VK_SPACE,				"Leertaste",																						// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"Maus",																								// skupina prvkù myši
IDF_MOUSE_L,				"linke Maustaste wird gehalten",																	// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"rechte Maustaste wird gehalten",																	// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"Mausposition in horizontaler Richtung",															// horizontální souøadnice myši
IDF_MOUSE_Y,				"Mausposition in vertikaler Richtung",																// vertikální souøadnice myši
IDF_EQU_TEXT,				"Kongruenz der Texte",																				// operátor porovnání textù
IDF_EQU_ICO,				"Kongruenz der Gegenstände",																		// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"Sprite - Erweiterung",																				// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"Fenster hat den Rand",																				// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"Fenster hat den Titel",																			// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"Programmparameter",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"Rückkehrkode",																						// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"Bild",																								// promìnná obrázku
IDF_REPEAT,					"Wiederholung der Befehle mit Anzahl",																// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"für die Anzahl der Wiederholungen",																// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"Flächenrand",																						// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horizontal",																						// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertikal",																							// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"Richtung",																							// smìr sprajtu
IDF_SPRITE_MOVE,			"in Bewegung",																						// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"sichtbar",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"Anzahl",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"Index",																							// index seznamu
IDF_LIST_AUTO,				"Index-Zuwachs",																					// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Peter - Erweiterung",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Luzia - Erweiterung",																				// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"numerischer Wert 1 (Bereich 0 bis 1023)",															// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"numerischer Wert 1 (Bereich 0 bis 1023)",															// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"numerischer Wert 2 (Bereich 0 bis 1023)",															// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"numerischer Wert 2 (Bereich 0 bis 1023)",															// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"numerischer Wert 3 (Bereich 0 bis 127)",															// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"numerischer Wert 3 (Bereich 0 bis 127)",															// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"Umschalter 1",																						// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"Umschalter 1",																						// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"Umschalter 2",																						// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"Umschalter 2",																						// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"Umschalter 3",																						// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"Umschalter 3",																						// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"Umschalter 4",																						// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"Umschalter 4",																						// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"Umschalter 5",																						// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"Umschalter 5",																						// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"Texte",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"linker Teil des Textes",																			// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"Länge des linken Teils des Textes",																// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"rechter Teil des Textes",																			// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"Beginn des rechten Teils des Textes",																// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"mittlerer Teil des Textes",																		// funkce støední èásti textu
IDF_TEXT_MID_POS,			"Beginn des mittleren Teils des Textes",															// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"Länge des mittleren Teils des Textes",																// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"Länge des Textes",																					// funkce zjištìní délky textu
IDF_TEXT_ADD,				"Zusammenlegung der Texte",																			// operátor pro slouèení textù
IDF_TEXT_SCAN,				"Überleitung der Nummer aus der Textgestalt",														// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"Überleitung der Nummer in die Textgestalt",														// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"alphabetischer Vergleich der Texte",																// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"Überleitung zu kleinen Buchstaben",																// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"Überleitung zu großen Buchstaben",																	// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"Suchen der Position mit Text (-1 = keine)",														// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"Eingangstext",																						// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"gesuchter Text",																					// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"Informationstext",																					// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"Überschrift des Fensters",																			// titulek hlavního okna (textová promìnná)
IDF_ORD,					"Überleitung des Zeichens zum numerischen Kode",													// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"Überleitung des numerischen Kode zum Zeichen",														// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"Audio",																							// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"Audiowiedergabe",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"Abstellen der Audiowiedergabe (ohne Eingabe = alle)",												// vypnutí zvuku
IDF_COLOR,					"Farbe",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"Graphik",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"Federfarbe",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"Federstärke",																						// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"Punkt",																							// nakreslení grafického bodu
IDF_POINT_X,				"horizontale X-Koordinate des Punktes",																// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertikale Y-Koordinate des Punktes",																// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"Linie",																							// nakreslení èáry
IDF_LINE_X1,				"horizontale X1-Koordinate der Linie",																// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertikale Y1-Koordinate der Linie",																// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horizontale X2-Koordinate der Linie",																// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertikale Y2-Koordinate der Linie",																// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"Rechteck",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horizontale X1-Koordinate des Rechteckes",															// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertikale Y1-Koordinate des Rechteckes",															// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horizontale X2-Koordinate des Rechteckes",															// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertikale Y2-Koordinate des Rechteckes",															// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"Ausgefülltes Rechteck",																			// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horizontale X1-Koordinate des ausgefüllten Rechteckes",											// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertikale Y1-Koordinate des ausgefüllten Rechteckes",												// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horizontale X2-Koordinate des ausgefüllten Rechteckes",											// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertikale Y2-Koordinate des ausgefüllten Rechteckes",												// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"Füllung",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horizontale X-Koordinate der Füllung",																// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertikale Y-Koordinate der Füllung",																// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"Kreislinie",																						// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horizontale X-Koordinate der Mitte",																// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertikale Y-Koordinate der Mitte",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"Halbmesser",																						// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"Kreis",																							// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horizontale X-Koordinate der Mitte",																// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertikale Y-Koordinate der Mitte",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"Halbmesser",																						// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"Dreieck",																							// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horizontale X1-Koordinate des Dreiecks",															// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertikale Y1-Koordinate des Dreiecks",																// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horizontale X2-Koordinate des Dreiecks",															// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertikale Y2-Koordinate des Dreiecks",																// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horizontale X3-Koordinate des Dreiecks",															// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertikale Y3-Koordinate des Dreiecks",																// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"Kugel",																							// nakreslení koule
IDF_SPHERE_X,				"horizontale X-Koordinate der Mitte",																// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertikale Y-Koordinate der Mitte",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"Halbmesser",																						// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"Änderung der Farbhelligkeit",																		// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"Helligkeit der Farbe (0 bis 1)",																	// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"Eingabe der Taste (wartet auf das Drücken)",														// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"Eingabe des Zeichens (wartet auf das Drücken)",													// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"keine Taste gedrückt",																				// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"Windows-Menü rechts",																				// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Umschalt rechts",																					// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"Strg rechts",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"Alt Gr (Alt rechts)",																				// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"Zustand des Num",																					// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"Zustand des Caps Lock",																			// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"Zustand des Rollens",																				// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"Zustand des Einfügens",																			// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"Klicken mit der linken Maustaste",																	// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"Klicken mit der rechten Maustaste",																// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"Doppelklicken mit der linken Maustaste",															// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"Doppelklicken mit der rechten Maustaste",															// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"Maustest im Bereich",																				// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horizontale X-Koordinate des Bereichsbeginns",														// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertikale Y-Koordinate des Bereichsbeginns",														// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"Bereichsbreite",																					// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"Bereichshöhe",																						// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"Ausdruck des Textes",																				// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horizontale X-Koordinate des Textes",																// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertikale Y-Koordinate des Textes",																// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"Winkel der Textorientierung",																		// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"Höhe der Zeichen",																					// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"relative Breite der Zeichen (1 = üblich)",															// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"fettgedruckter Text",																				// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"Kursivschrift",																					// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"Unterstreichung",																					// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"Durchstreichen",																					// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"Serifen",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"Schreibmaschine",																					// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"Text zum Ausdruck",																				// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"Anzahl der Zeilen des Textes",																		// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"Zeile des Textes",																					// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"Nummer der Textzeile",																				// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"Audiotest (ohne Eingabe = Alle Audiowiedergaben)",													// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"Anzahl der Wiederholungen (0 = ständig)",															// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"Gegenstand auf der Position mit Peter",															// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"Gegenstand auf der Position mit Luzia",															// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"Zeichnen des Bildes",																				// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"Bild zum Zeichnen",																				// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horizontale X-Koordinate des Bildes",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertikale Y-Koordinate des Bildes",																// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horizontale X-Koordinate des Ausschnittes",														// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertikale Y-Koordinate des Ausschnittes",															// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"Breite des Ausschnittes",																			// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"Höhe des Ausschnittes",																			// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"Verwahrung des Flächenausschnittes als Bild",														// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"Verwahrung des Flächenausschnittes als Gegenstand",												// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"Sprache (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",														// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"Audio zur Wiedergabe",																				// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"Audiolautstärke (0 bis 1)",																		// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"Stereoabgleich (-1 = links bis +1 = rechts)",														// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"Audiowiedergabe abbrechen",																		// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"Kommentar",																						// komentáø
IDF_SOUND_FUNCTIONS,		"Audiofunktionen",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"Einstellung der Gestalt des Mauszeigers",															// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"Bild des Mauszeigers (ohne Eingabe = ursprünglich)",												// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horizontale X-Koordinate des Bereichsbeginns",														// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertikale Y-Koordinate des Bereichsbeginns",														// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"Bereichsbreite",																					// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"Bereichshöhe",																						// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"Musikwiedergabe",																					// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"wiederholte Musikwiedergabe",																		// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"Beenden der Musikwiedergabe",																		// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"Musikwiedergabe anhalten/fortsetzen ",																// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"Test der Musikwiedergabe",																			// test pøehrávání hudby
IDF_MUSIC_POS,				"Position in der Musikwiedergabe",																	// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"Länge der Musikwiedergabe",																		// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"Zusammenlegung der Farbkomponenten zur Farbe",														// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"rote Komponente (0 bis 1)",																		// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"grüne Komponente (0 bis 1)",																		// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"blaue Komponente (0 bis 1)",																		// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"Einlesen der Farbe des Punktes",																	// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horizontale X-Koordinate für das Einlesen der Farbe des Punktes",									// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertikale Y-Koordinate für das Einlesen der Farbe des Punktes",									// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"zweite Potenz",																					// funkce druhá mocnina
IDF_MUSIC_GROUP,			"Musik",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"Audio-CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"CD-Wiedergabe ab der vergebenen Spur (ohne Eingabe = 1)",											// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"Beenden der CD-Wiedergabe",																		// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"CD-Wiedergabe anhalten/fortsetzen ",																// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"Test der CD-Wiedergabe",																			// test pøehrávání CD
IDF_CD_LENGTH,				"ganze Länge",																						// celková délka CD
IDF_CD_TRACKS,				"Anzahl der Spuren",																				// poèet stop CD
IDF_CD_POS,					"Position vom Beginn",																				// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"wiedergegebene Spur",																				// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"Länge der wiedergegebenen Spur",																	// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"Position vom Beginn der Spur",																		// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"Dateien",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"grundlegende Operationen",																			// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"neue Datei",																						// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"neuer Ordner",																						// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"Löschen der Datei oder des Ordners",																// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"Test der Existenz",																				// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"aktives Laufwerk und aktiver Ordner",																// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"Kapazität des Laufwerks",																			// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"freier Speicherplatz auf dem Laufwerk",															// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"Name des Laufwerks",																				// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"Seriennummer des Laufwerks",																		// zjištìní sériového èísla disku
IDF_FILE_READ,				"aktive Datei (Ordner) für das Lesen",																// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"aktive Datei (Ordner) für das Schreiben",															// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"Kopie der Datei",																					// provedení kopie souboru
IDF_FILE_MOVE,				"Verschiebung/Umbenennung der Datei (des Ordners)",													// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"Laufwerk",																							// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"Parameter",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"Attribut R/O (nur für das Lesen)",																	// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"Attribut HID (verdeckt)",																			// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"Attribut SYS (Systemattribut)",																	// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"Attribut DIR (Ordner)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"Attribut ARC (archivalisch)",																		// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"Attribut TEMP (vorübergehend)",																	// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"Attribut COMP (komprimiert)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"Attribut OFF (unzugänglich)",																		// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"Datum und Zeit der Erstellung",																	// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"Datum und Zeit des letzten Zugriffs",																// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"Datum und Zeit der letzten Modifizierung",															// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"Daten",																							// skupina dat souborù
IDF_FILE_BYTES,				"ganzzahlige Nummer mit Vorzeichen, 1 Byte",														// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"ganzzahlige Nummer ohne Vorzeichen, 1 Byte",														// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"ganzzahlige Nummer mit Vorzeichen, 2 Bytes",														// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"ganzzahlige Nummer ohne Vorzeichen, 2 Bytes",														// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"ganzzahlige Nummer mit Vorzeichen, 4 Bytes",														// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"ganzzahlige Nummer ohne Vorzeichen, 4 Bytes",														// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"dezimale Nummer, 4 Bytes",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"dezimale Nummer, 8 Bytes",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"Text mit binärer Null abgeschlossen (ASCIIZ)",														// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"Text mit Zeilenende abgeschlossen",																// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"Text mit fester Länge",																			// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"Gegenstand (ICO)",																					// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"Bild (BMP, JPG)",																					// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"Audio (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"Musik (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"Zeiger des Lesens",																				// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"Zeiger des Schreibens",																			// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"Datum und Zeit",																					// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"Aktuelles Datum und Zeit (Anzahl der Sekunden seit dem 1.1.1601)",									// aktuální datum a èas
IDF_DATETIME_UTC,			"Überleitung der Ortszeit zur Weltzeit",															// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"Überleitung der Weltzeit zur Ortszeit",															// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"Zusammenlegung der Komponenten des Datums und der Zeit",											// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"Jahr",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"Monat",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"Tag",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"Stunde",																							// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"Minute",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"Sekunde",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"Millisekunde",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"Jahr aus dem Datum und der Uhrzeit",																// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"Monat aus dem Datum und der Uhrzeit",																// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"Tag aus dem Datum und der Uhrzeit",																// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"Wochentag aus dem Datum und der Uhrzeit (0 = Sonntag, 1 = Montag, ...)",							// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"Stunde aus dem Datum und der Uhrzeit",																// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"Minute aus dem Datum und der Uhrzeit",																// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"Sekunde aus dem Datum und der Uhrzeit",															// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"Millisekunde aus dem Datum und der Uhrzeit",														// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"Überleitung des Datums zum Text \"Tag.Monat.Jahr\"",												// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"Überleitung des Datums zum Text \"Monat/Tag/Jahr\"",												// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"Überleitung des Datums zum Text \"Jahr-Monat-Tag\"",												// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"Überleitung der Zeit zum Text \"Stunde:Minute:Sekunde\" (24 Stunden)",								// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"Überleitung der Zeit zum Text \"Stunde:Minute:Sekunde x\" (12 Stunden)",							// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"Größe der Datei",																					// velikost souboru
IDF_FILE_ERROR,				"Flag des Operationsfehlers",																		// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"Länge des Textes mit fester Länge",																// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"Typ des Laufwerks (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",												// zjištìní typu disku
IDF_TEXT_FORMAT2,			"Überleitung der Nummer zum Text - 2 Ziffern",														// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"Überleitung der Nummer zum Text - 8 HEX-Ziffern",													// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"ganzzahlige Nummer mit Vorzeichen, 3 Bytes",														// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"ganzzahlige Nummer ohne Vorzeichen, 3 Bytes",														// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"Dialoge",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"Bestätigungsdialog (liefert 1=OK, 2 und 3=Abbrechen, 4=Wiederholen, 5=Ignorieren, 6=Ja, 7=Nein)",	// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"Text",																								// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"Überschrift",																						// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"Ikon (0=nichts, 1=Fehler, 2=Frage, 3=Warnung, 4=Information)",										// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"Schaltflächen (0=OK, 1=OK/Abbrechen, 2=Abbrechen/Wiederholen/Ignorieren, 3=Ja/Nein/Abbrechen, 4=Ja/Nein, 5=Wiederholen/Abbrechen)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"Implizite Schaltfläche (1 bis 3)",																	// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"Weitere Zeile",																					// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"Texteingabe",																						// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1. Zeile der Aufforderung",																		// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2. Zeile der Aufforderung",																		// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3. Zeile der Aufforderung",																		// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"Voreingestellter Text zur Eingabe ",																// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"Ausschieben der CD",																				// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"Bitzahl pro Muster (8 oder 16)",																	// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"Abtastfrequenz (Hz)",																				// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"Ist das Audio stereophon?",																		// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"Audiolänge (Sekunden)",																			// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"Umwandlung zu 8 Bit",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"Umwandlung zu 16 Bit",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"Umwandlung zum Stereo",																			// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"Umwandlung zum Mono",																				// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"Umwandlung zu 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"Umwandlung zu 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"Umwandlung zu 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"Audiomischen",																						// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"Änderung der Audiowiedergabegeschwindigkeit",														// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"Audio zur Konvertierung",																			// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relative Änderung der Überspielgeschwindigkeit (1 = ohne Änderung)",								// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"Tongenerator",																						// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"Tonfrequenz (Hz)",																					// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"Tonlänge (Sekunden)",																				// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"Fläche",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"Flächenbreite",																					// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"Flächenhöhe",																						// zjištìní vıšky plochy
IDF_MAP_X,					"X-Koordinate",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"Y-Koordinate",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"Fläche",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"Gegenstand",																						// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"Zahlenwert 1 (Bereich 0 bis 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"Zahlenwert 2 (Bereich 0 bis 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"Zahlenwert 1 (Bereich 0 bis 127)",																	// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"Umschalter 1",																						// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"Umschalter 2",																						// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"Umschalter 3",																						// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"Umschalter 4",																						// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"Umschalter 5",																						// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"Kopie des Flächenausschnittes",																	// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"Fläche mit Ausschnitt",																			// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"X-Koordinate des Ausschnittes",																	// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"Y-Koordinate des Ausschnittes",																	// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"Ausschnittsbreite",																				// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"Ausschnittshöhe",																					// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"Konsole",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"Sammelverschiebung der Sprites in X-Richtung",														// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"Sammelverschiebung der Sprites in Y-Richtung",														// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"Linker Rand des Sprite-Fensters",																	// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"Unterer Rand des Sprite-Fensters",																	// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"Rechter Rand des Sprite-Fensters",																	// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"Oberer Rand des Sprite-Fensters",																	// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"Betriebsart der Konsole (am Anfang der Hauptfunktion anzuführen)",									// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"Textausgang zur Konsole",																			// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"Texteingang von der Konsole",																		// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"Fehlertextausgang zur Konsole",																	// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"Progammparameter (0 = Programmname)",																// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"Programmname mit Vollpfad",																		// jméno tohoto programu s plnou cestou
IDF_EXEC,					"Programmanlauf",																					// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"Programmanlauf mit Warten",																		// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"Joystick",																							// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"X-Koordinate des Joysticks",																		// souøadnice X joysticku
IDF_JOYSTICK_Y,				"Y-Koordinate des Joysticks",																		// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"Z-Koordinate des Joysticks",																		// souøadnice Z joysticku
IDF_JOYSTICK_1,				"Taste 1 des Joysticks",																			// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"Taste 2 des Joysticks",																			// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"Taste 3 des Joysticks",																			// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"Taste 4 des Joysticks",																			// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"Texte und Bilder",																					// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"Nummer des Elementes (0 = Hauptfenster)",															// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"Löschung eines Elementes oder eines Fensters",														// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"Bildung eines Fensters",																			// vytvoøení dialogového okna
IDF_WINDOW_X,				"horizontale Koordinate",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"vertikale Koordinate",																				// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"Breite",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"Höhe",																								// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"Text",																								// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"Sichtbarkeit",																						// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"Verbot",																							// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"Bildung einer Schaltfläche",																		// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"Drücken einer Schaltfläche oder Änderung eines Elementes",											// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"Bildung einer Checkbox",																			// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"Bildung einer Bearbeitungszeile",																	// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"Bildung eines Umschalters",																		// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"Gemeinsame Funktionen für alle Elemente",															// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"Bildung eines Bearbeitungsfeldes",																	// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"Schaltflächen",																					// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"Schalter ein",																						// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"Eingangsausrichtung",																				// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"Bildung einer impliziten Schaltfläche",															// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"Bildung einer Ikonschaltfläche",																	// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"Bildung eines Rahmens",																			// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"Bildung einer Liste",																				// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"Bildung eines Textes",																				// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"Bildung einer Drop-down-Liste",																	// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"Bildung einer Drop-down-Liste mit Bearbeitung",													// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"Hervorgehobene Schrift",																			// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"Schrift mit festem Abstand",																		// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"Bildung eines Umschalters, Gruppenanfang",															// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"Listen",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"Zugabe einer Position in die Liste",																// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"Leerung der Liste",																				// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"Bildung einer Liste mit Bearbeitung",																// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"Bildung einer 3-Zustands-Box",																		// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"Schalter in unbestimmtem Zustand",																	// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"Bildung eines Fensters ohne Schließungsmöglichkeit",												// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"Ikon",																								// ikona prvku dialogového okna
IDF_WINICON_NEW,			"Bildung eines Ikons",																				// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"Sprite (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*Ludolfsche Zahl (= 360 Grad)",																	// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"Abstand eines Punktes (= 1/32)",																	// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"Phase",																							// fáze sprajtu
IDF_SPRITE_STATUS,			"Zustand",																							// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"Ganzbildschirm-Betriebsart",																		// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"Leerung des Tastenpuffers",																		// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"Position im Audiowiedergeben",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"Audiowiedergabe anhalten/fortsetzen",																// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"Dateienliste",																						// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"Kongruenz der Flächen",																			// operátor porovnání ploch
IDF_EQU_PIC,				"Kongruenz der Bilder",																				// operátor porovnání obrázkù
IDF_EQU_SPR,				"Kongruenz der Sprites",																			// operátor porovnání sprajtù
IDF_EQU_SND,				"Audio-Kongruenz",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"Kongruenz der Musik",																				// operátor porovnání hudeb
IDF_NET_GROUP,				"Kommunikation",																					// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"Netzunterstützung DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"Liste der Verbindungen",																			// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"Aktive Verbindung",																				// aktivní spojení DirectPlay
IDF_GAME_LIST,				"Liste der Spiele",																					// seznam bìících her DirectPlay
IDF_GAME_ACT,				"Aktives Spiel",																					// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"Liste der Spieler",																				// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"Aktiver Spieler",																					// aktivní hráè DirectPlay
IDF_GAME_N1,				"Zahlenparameter des Spieles 1 (-16384 bis +16383)",												// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"Zahlenparameter des Spieles 2 (-16384 bis +16383)",												// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"Zahlenparameter des Spieles 3 (-16384 bis +16383)",												// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"Zahlenparameter des Spieles 4 (-16384 bis +16383)",												// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"Zahlenparameter des Spieles 5 (-16384 bis +16383)",												// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"Zahlenparameter des Spieles 6 (-16384 bis +16383)",												// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"Zahlenparameter des Spieles 7 (-16384 bis +16383)",												// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"Zahlenparameter des Spieles 8 (-16384 bis +16383)",												// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"Umschalter des Spieles 1",																			// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"Umschalter des Spieles 2",																			// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"Umschalter des Spieles 3",																			// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"Umschalter des Spieles 4",																			// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"Umschalter des Spieles 5",																			// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"Umschalter des Spieles 6",																			// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"Umschalter des Spieles 7",																			// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"Umschalter des Spieles 8",																			// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"Einstellung des Spieles",																			// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"Wirt (Steuerrechner)",																				// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"Höchtanzahl der Spieler (0 = unbeschränkt)",														// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"Nummer des aktiven Spielers (-1 = keiner)",														// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"Daten",																							// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"Senden/Empfang eines Datenblocks (-1 = allen/keiner)",												// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"Nummer",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"Text",																								// text dat DirectPlay
IDF_GAME_DATAL,				"Umschalter",																						// pøepínaè dat DirectPlay
IDF_GAME_IP,				"IP-Adresse dieses Rechners",																		// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"ganzzahlige Nummer 0 bis 255 (Byte)",																// èíslo bajt dat DirectPlay
IDF_INC,					"Inkrementieren (eine 1 wird zugezählt)",															// funkce inkrementace èísla
IDF_DEC,					"Dekrementieren (eine 1 wird abgezählt)",															// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"Bildung eines zentrierten Textes",																	// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"Schaltfläche für die Esc-Taste (-1 = keine)",														// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"Bildbreite",																						// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"Bildhöhe",																							// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"horizontales Spiegeln des Bildes",																	// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"vertikales Spiegeln des Bildes",																	// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"Bilder",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"Änderung der Bildgröße",																			// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"Bild",																								// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"Breite (ohne Eingabe = höhenproportional)",														// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"Höhe (ohne Eingabe = breitenproportional)",														// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"Kanten verfeinern",																				// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"Dithering (Fotografie)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"Zeichnen",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"Bildung eines Bildes",																				// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"Bild",																								// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"Bildung des Editors RichEdit",																		// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"Zeichenhöhe (0 = gewöhnlich)",																		// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"Breite Schrift",																					// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"Unterstrichene Schrift",																			// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"Durchgestrichene Schrift",																			// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"Serifenschrift",																					// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"relative Zeichenbreite (0 = gewöhnlich, 1 = grundlegend)",											// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"Winkel der Textneigung",																			// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"Bildung eines rechtsbündigen Textes",																// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"Schriftfarbe",																						// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"Untergrundfarbe",																					// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"Elementfarbe",																						// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"Geschwindigkeit der Wiedergabe (1 = gewöhnlich)",													// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"Unterscheidungscode (0 bis 65535)",																// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"Eingabe der zu öffnenden Datei",																	// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"Eingabe der zu speichernden Datei",																// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"Eingabe des zu suchenden Textes",																	// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"Eingabe der Farbe",																				// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"Dateienmaske",																						// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"Voreingestellter Dateiname",																		// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"Name des Dateityps",																				// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"Änderung der Bildhelligkeit",																		// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"Bild zur Bildhelligkeitsänderung",																	// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"Bildhelligkeit (1 = gewöhnlich)",																	// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"Bilddrehen",																						// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"Zu drehendes Bild",																				// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"Drehwinkel",																						// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"Audiodekompression",																				// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"Text ist im UNICODE-Format (2 Bytes)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"Umwandlung der Fläche zu einem Bild",																// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"Umwandlung des Gegenstandes zu einem Bild",														// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"Bitoperationen",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"Bitprodukt AND",																					// bitovı (binární) souèin AND
IDF_BIT_OR,					"Bitsumme OR",																						// bitovı (binární) souèet OR
IDF_BIT_XOR,				"Bitinversion XOR",																					// bitová (binární) inverze XOR
IDF_BIT_NOT,				"Bitergänzung NOT",																					// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"Maximalbitnummer (Doppelwort)",																	// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"Bitrotation nach links",																			// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"Bitrotation nach rechts",																			// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"Maustest im Element",																				// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"Innere Breite",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"Innere Höhe",																						// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"Zeichnesatz (1250 = mitteleuropäisch, 1251 = russisch, 1252 = westlich)",							// èíslo pouité znakové sady fontù
IDF_USERFONT,				"Benutzerschrift",																					// jméno uivatelského fontu
IDF_ENUMFONTS,				"Schriftartenliste",																				// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"neue Fläche",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"Flächenbreite",																					// šíøka nové plochy
IDF_MAP_NEW_H,				"Flächenhöhe",																						// vıška nové plochy
IDF_WINDOW_TOP,				"immer oben",																						// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"Spitzname (alias)",																				// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"Kommunikationport",																				// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"Öffnung des Ports (-1=Fehler)",																	// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"Schließung des Ports",																				// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"Aktivport",																						// aktivní port
IDF_COM_NUM,				"Nummer (0 bis 255)",																				// vstup/vıstup èísla
IDF_COM_TEXT,				"Zeichen (Text)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"Übertragungs-Schnelligkeit",																		// pøenosová rychlost
IDF_COM_STOP,				"2 Stopbit",																						// reim s 2 stopbity
IDF_COM_BITS,				"Bitzahl (5 bis 8)",																				// poèet bitù na znak
IDF_COM_PARIT,				"Parität (0=keiner, 1=ungerade, 2=gerade)",															// zvolená parita
IDF_COM_IN,					"Zeichen ist angenommt",																			// byl pøijatı znak
IDF_COM_SEND,				"Sendung ist möglich (CTS, RTS)",																	// povoleno vysílání
IDF_COM_RECEIVE,			"Empfang ist möglich (DSR, DTR)",																	// povolen pøíjem
IDF_PICTURE_MASK,			"Bildtarnung",																						// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"Bild",																								// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"Maske",																							// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"Feldbreite zu Ausdruck des Textes (0 = keine)",													// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"Bildung eines Bearbeitungsfeldes ohne Abknickung",													// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"stellbar Größe des Fensters",																		// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"Fenster kann sein eingeschlossen",																	// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"maximieren des Fensters",																			// maximalizace okna
IDF_WINDOW_MINIM,			"minimieren des Fensters",																			// minimalizace okna
IDF_PROGRESS_NEW,			"Bildung einer Laufanzeige",																		// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"Bildung einer horizontale Spannungsteilers",														// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"Bildung einer vertikale Spannungsteilers",															// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"Aktuelle Position",																				// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"Mixgerät",																							// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"Mixgerät",																							// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"Zielsignal",																						// volba cílového signálu
IDF_MIX_LINE_SRC,			"Quellesignal (keine=nur Zielsignal)",																// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"Typ des Signals",																					// zjištìní typu signálu
IDF_MIX_CONTROL,			"Steuerung",																						// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"Typ der Steuerung",																				// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"Wert der Steuerung (0 bis 1)",																		// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"Auswahl des Wert",																					// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"kontrolliert Kanal (-1=Alles)",																	// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D Graphik",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"3D Graphik-Fenster",																				// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X-Koordinate des 3D Graphik-Fensters",																// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y-Koordinate des 3D Graphik-Fensters",																// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"Breite des 3D Graphik-Fensters",																	// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"Höhe des 3D Graphik-Fensters",																		// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"Video-Mode (Breite*Höhe/Bit)",																		// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"graphisch Hintergrund",																			// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"Justierung",																						// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"ausfüllen der Flächen",																			// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"Beleuchtung",																						// mód osvìtlení
IDF_DIRECT3D_SHADES,		"stufenlos Schattierung",																			// mód stínování
IDF_DIRECT3D_INVERT,		"verdrehen des Objektes",																			// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"Objekte",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"Wand",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"Würfel",																							// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"Kugel",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"Zylinder",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"Konus",																							// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"klonen",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"Objekt von Textes",																				// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"Objekt von Datei",																					// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"Nummer des Objektes (0=Szene, 1=Kamera, 2=Licht)",													// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"Löschung eines Objektes",																			// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"sichtbar",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"anschließen",																						// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"Objekt ins Datei",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"Transformation",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"Maß im X-Richtung",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"Maß im Y-Richtung",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"Maß im Z-Richtung",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"Umdrehung nach X-Achse",																			// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"Umdrehung nach Y-Achse",																			// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"Umdrehung nach Z-Achse",																			// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"Verschiebung im X-Richtung",																		// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"Verschiebung im Y-Richtung",																		// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"Verschiebung im Z-Richtung",																		// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"Oberfläche",																						// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"Farbe (-1=intern, -2=implizit)",																	// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"Lichtstärke-Farbe",																				// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"Mattheit (0=aus, 5=Erz, 50=Plast)",																// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"Spiegelung-Farbe",																					// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"Textur",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"Textur-Mappierung",																				// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"Projektion-Typ (0=Fläche, 1=Zylinder, 2=Kugel, 3=Chrom, 4=Linse)",									// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"X-Koordinate der Projektion-Mitte",																// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"Y-Koordinate der Projektion-Mitte",																// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"Z-Koordinate der Projektion-Mitte",																// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"Umdrehung der Projektion nach X-Achse",															// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"Umdrehung der Projektion nach Y-Achse",															// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"Umdrehung der Projektion nach Z-Achse",															// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"Durchsichtigkeit (1=normal, 11=Feuer, 20=Glas, 54=Verdeck)",										// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"Konturen (0=normal, 0.5=Konturen)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"Methode (0=Adressen, 1=Scheitel, 2=Flächen)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"horizontal Textur-Anfang",																			// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"vertikal Textur-Anfang",																			// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"horizontal Textur-Maß",																			// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"vertikal Textur-Maß",																				// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"Beleuchtung",																						// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"bilden neu Licht",																					// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"Licht-Farbe",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"Licht-Typ (1=punktförmig, 2=keglig, 3=gerichtet)",													// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"Lichtkegel-Winkel",																				// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"Halbschatten-Winkel",																				// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"Licht-Reichweite",																					// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"Light-Intensität (1=normal)",																		// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"linear Schwächung",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"quadratisch Schwächung",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"Projektion-Typ (0=persp, 1=ortho, 2=r-persp, 3=r-ortho)",											// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"Szene",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"Hintergrund-Farbe der Szene (-1=aus, -2=nicht initialisieren)",									// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"Hintergrund-Textur der Szene",																		// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"Nebel-Farbe (-1=aus)",																				// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"Nebel-Typ (0=lin, 1=exp, 2=quadr, +4=Berichtigung)",												// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"linear Nebel-Beginn",																				// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"linear Nebel-Ende",																				// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"exp. und quadr. Nebel-Dichte (0 bis 1)",															// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"Distanz der Projektions-Fläche",																	// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"Distanz der Sichtweite",																			// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"bilden Oberbase",																					// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"bilden Unterbase",																					// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"aussuchen des Objektes",																			// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"X-Koordinate des Punktes",																			// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"Y-Koordinate des Punktes",																			// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"Filtration der verkleinert Textur",																// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"2D Objekt",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"Terrain von Bild",																					// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"Terrain-Niveau",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"horizontale Koordinate",																			// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"vertikale Koordinate",																				// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"Gruppe",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"Kompliziertheit des Objektes (2 bis 100)",															// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"Umdrehung-Folge (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",										// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"Regler (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"Rotationsobjekt",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"Terrain von Fläche",																				// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"Reflex des zerstreut Lichtes (-1=implizit)",														// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"Programm ist aktive Applikation",																	// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"Distanz des Punktes",																				// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"Winkel des Punktes",																				// vıpoèet úhlu bodu
IDF_POLAR_X,				"X-Koordinate des Punktes",																			// souøadnice X bodu
IDF_POLAR_Y,				"Y-Koordinate des Punktes",																			// souøadnice Y bodu
IDF_FILE_LOGIC,				"logischer Wert",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"Tilgung der Textur (1=nein)",																		// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"pünktlich Zeit-Zählgerät",																			// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"zerstreut Licht",																					// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"Filtration der vergrößert Textur",																	// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"Filtration der fernstehend Textur",																// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"ausfüllen der Objekt-Flächen",																		// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"Objekt-Beleuchtung",																				// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"stufenlos Schattierung des Objektes",																// mód stínování
IDF_DIRECT3D_OMINFILTER,	"Filtration der verkleinert Objekt-Textur",															// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"Filtration der vergrößert Objekt-Textur",															// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"Filtration der fernstehend Objekt-Textur",															// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"visibel Objekt-Seite (0=beide, 1=vorder, 2=hinter)",												// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"bilden",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"normalisieren des Objektes",																		// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"Kreis",																							// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"Dreieck",																							// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"Torus (Parameter = Durchmesser 0 bis 1)",															// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"statisch 2D Objekt",																				// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"Halbkugel",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"Schnittstelle (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",							// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"vergangen Zeit",																					// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"Einrahmung-Geschwindigkeit",																		// rychlost renderování
IDF_DIRECT3D_FREE,			"frei Video-Speicher",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D Bild",																							// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"Texturen",																							// skupina textur
IDF_DIRECT3D_STAGE,			"Stufe (0 bis 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"Farbe-Operation (1=aus, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"Farbe-Argument 1 (0=Farbe, 1=Resultat, 2=Textur, 3=Faktor, 16=Umkehr)",							// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"Farbe-Argument 2 (0=Farbe, 1=Resultat, 2=Textur, 3=Faktor, 16=Umkehr)",							// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"Alpha-Operation (1=aus, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"Alpha-Argument 1 (0=Farbe, 1=Resultat, 2=Textur, 3=Faktor, 16=Umkehr)",							// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"Alpha-Argument 2 (0=Farbe, 1=Resultat, 2=Textur, 3=Faktor, 16=Umkehr)",							// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"horizontale Adressierung (1=Wiederholung, 2=Spiegelung, 3=Begrenzung)",							// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"vertikale Adressierung (1=Wiederholung, 2=Spiegelung, 3=Begrenzung)",								// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"Verfeinerung der fernstehend Textur (0=üblich)",													// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"Konoid (Parameter = Durchmesser 0 bis 1)",															// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"Farbe des Textur-Faktors",																			// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alpha Komponente (0=Durchsichtigkeit bis 1=Farbe)",												// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"Anzahl der Niveaus der fernstehend Textur (0=alles)",												// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"Render-Gruppe (0-7=Objekte, 8-11=durchsichtig, 12-15=Bild)",										// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"tiefschürfend Sortierung die Render-Gruppe",														// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"schreiben die tiefschürfend Information",															// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"tiefschürfend Test (1 niemals, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 immer)",							// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"Rechnung die Normalen (Parameter = Winkel für Verfeinerung)",										// pøepoèet normál
IDF_DIRECT3D_RENDER,		"Render ohne Darstellung",																			// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"Textblock",																						// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"Zeile des Block-Beginns",																			// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"Position des Block-Beginns",																		// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"Zeile der Block-Endes (-1=Ende)",																	// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"Position der Block-Endes (-1=Ende)",																// pozice konce bloku
IDF_WINDOW_POS2,			"Aktuelle Position 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"Bildung einer Umschaltfläche",																		// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"Bildung einer Tafel (Parameter = Titel-Liste)",													// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"Breite der Tafelspalte",																			// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"Distanz der Schatten-Reichweite (0=abschalten)",													// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"Einordnung der Tafelspalte (0=links, 1=rechts, 2=zentrieren)",										// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"Bildung einer horizontale Gleiteners",																// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"Bildung einer vertikale Gleiteners",																// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"Verwechslung die Farben",																			// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"erste Farbe",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"zweite Farbe",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"Entschädigung der Farbe",																			// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"urtümlich Farbe",																					// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"neu Farbe",																						// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"drücken das Bild",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"Objekt mit abbauen Detail-Niveau (-1=keine)",														// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"Distanz für abbauen Detail-Niveau",																// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"zugeben Vorlage für Morph (-1=Reset)",																// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"Morph-Stufe (0...1...2...)",																		// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"Linse-Abglanz",																					// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"Dynamisch Daten-Austausch DDE",																	// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"Name der Server/Liste der Server",																	// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"Name des Thema/Liste der Themata",																	// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"Name der Angabe/Liste der Angaben",																// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"Programm ist Angabegeber (ist Server)",															// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"Typ der Angabe (0 bis 7, -1=ungültig Angabe)",														// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) Nummer",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) Flag",																							// pøíznak DDE
IDF_DDE_TEXT,				"(2) Text",																							// text DDE
IDF_DDE_ICON,				"(3) Gegenstand",																					// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) Bild",																							// obrázek DDE
IDF_DDE_SOUND,				"(5) Audio",																						// zvuk DDE
IDF_DDE_MUSIC,				"(6) Musik",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) Sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"Befehl zu Vollzug",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL Bibliotheken",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"einlesen die Bibliothek",																			// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"entspannen die Bibliothek",																		// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"importieren die Funktion",																			// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"Identifizierer der Bibliothek",																	// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"Name der Funktion",																				// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"Anzahl des Parameter",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"vollziehen die Funktion",																			// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"bilden den Speicher-Block",																		// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"entspannen den Speicher-Block",																	// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"Größe-Änderung den Speicher-Block",																// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"Adresse den Speicher-Block",																		// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"neu Größe",																						// nová velikost bloku pamìti
IDF_MEMORY_READ,			"Zeiger des Lesens",																				// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"Zeiger des Schreibens",																			// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"Kopie der Daten",																					// kopie bloku dat
IDF_MEMORY_COMPARE,			"Vergleich der Daten",																				// porovnání bloku dat
IDF_MEMORY_BYTES,			"Byte mit Vorzeichen",																				// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"Byte ohne Vorzeichen",																				// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"Wort mit Vorzeichen",																				// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"Wort ohne Vorzeichen",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-Byte mit Vorzeichen",																			// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-Byte ohne Vorzeichen",																			// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"Zweiwort mit Vorzeichen",																			// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"Zweiwort ohne Vorzeichen",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"dezimale Nummer 4 Bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"dezimale Nummer 8 Bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logisch Wert",																						// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"Text mit Null abgeschlossen",																		// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"Zeiger an des Texts mit Null abgeschlossen",														// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"Text mit fester Länge",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"Länge des Textes mit fester Länge",																// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"Lesen der Daten aus der Datei",																	// ètení dat ze souboru
IDF_MEMORY_SAVE,			"Schreiben der Daten in der Datei",																	// zápis dat do souboru
IDF_WINDOW_HANDLE,			"Identifizierer des Fensterelements",																// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"Rufkonvention C",																					// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"Bildung einer Falte",																				// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"Konfiguration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"Konfiguration-Datei",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"Parameter-Sektion",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"Parameter-Name",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"lesen/einschreiben text Parameter",																// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"lesen/einschreiben numerisch Parameter",															// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"Schlüssel-Gruppe (1=CURRENT_USER, 2=LOCAL_MACHINE)",												// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"Schlüssel-Name",																					// plnı mázev klíèe registrù
IDF_REG_VALUE,				"Angabe-Name",																						// název datové poloky
IDF_REG_STRING,				"lesen/einschreiben text Angabe",																	// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"lesen/einschreiben numerisch Angabe",																// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"bilden neu 3D Objekt von Speicher-Block",															// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"Anzahl der Scheitel",																				// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"Scheitel",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"Normalen (0=auto)",																				// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"Textur-Mappierung (0=keine)",																		// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"Farben (0=keine)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"Anzahl der Dreiecke",																				// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"Dreiecke",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"Textur von Datei",																					// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"Speicher-Block von 3D Objekt",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"Finden des Nachkommes (-1=erste, -2=Eltern)",														// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
