// Rusky (Russian)
// 1251
// [0] Rщznй texty
IDN_MAINFRAME,				"Пётр",																								// jmйno aplikace Petr v nadpisu hlavnнho okna
IDN_NADPISOBJ,				"Общие переменные и функции",																		// titulek okna globбlnнch promмnnэch
IDN_NADPISLOC,				"Локальные переменные и функции",																	// titulek okna lokбlnнch promмnnэch
IDN_NADPISSTR,				"Основные элементы, корзина",																		// titulek okna stavebnнch prvkщ a koљe
IDN_NADPISCLS,				"Библиотека переменных и функций",																	// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"основные переменные и функции",																	// popis prvku "Skupina" se zбkladnнmi prvky u novйho programu
IDN_NEWFILE_NAME,			"Новая программа",																					// implicitnн nбzev novйho programu
IDN_NEWDIR_NAME,			"Новая папка",																						// implicitnн nбzev novй sloћky
IDN_TEXTVZOR,				"[примеры]",																						// nбzev vzorovйho adresбшe v knihovnм
IDN_STAT_REF,				"Употреблено",																						// zobrazuje poиet pouћitн prvku
IDT_RADEK,					"строка",																							// zkratka pro "шбdek", pouћнvб se pшi editaci textu
IDT_POZICE,					"столбец",																							// zkratka pro "pozice", pouћнvб se pшi editaci textu
IDN_ZAPNUTO,				"включено",																							// text editoru hodnoty pшepнnaиe
IDN_DATUM,					"дата",																								// text pro informaиnн шбdek o souboru v oknм vэbмru souborщ
IDN_CAS,					"время",																							// text pro informaиnн шбdek o souboru v oknм vэbмru souborщ
IDN_VELIKOST,				"размер",																							// text pro informaиnн шбdek o souboru v oknм vэbмru souborщ
IDN_VOLNE,					"свободно",																							// text pro informaиnн шбdek o souboru v oknм vэbмru souborщ
IDN_KB,						"КБ",																								// oznaиenн "Kilobajty"
IDN_MB,						"МБ",																								// oznaиenн "Megabajty"
IDN_OPAKOVANI,				"повторение",																						// text indikujнcн opakovбnн pшehrбvбnн zvuku (ve jmйnu souboru WAV) - malэmi pнsmeny!
IDN_OPAKOVANE,				"повторено",																						// alternativnн text indikujнcн opakovбnн pшehrбvбnн zvuku (ve jmйnu souboru WAV) - malэmi pнsmeny!
IDN_DEMO,					"ДЕМО",																								// oznaиenн DEMO verze
IDN_PROFI,					"Профессионал",																						// oznaиenн verze Professional
IDN_LITE,					"Lite",																								// oznaиenн LITE verze
// [1] Menu "Soubor" vэbмru programщ - doplтuje menu "Soubor" editoru
IDN_FILE0,					"&Файл",																							// volba k vyvolбnн menu "Soubor"
IDN_START0,					"&Старт\tF5",																						// volba pro spuљtмnн programu
IDN_START,					"Старт программы.\nСтарт",																			// [2] nбpovмda k volbм pro spuљtмnн programu
IDN_OPEN0,					"&Открыть\tCtrl+O",																					// volba k otevшenн programu k editaci
IDN_OPEN,					"Открыть программу для редактирования.\nОткрыть",													// [2] nбpovмda k volbм pro otevшenн programu k editaci
IDN_NEW0,					"&Новый...\tCtrl+N",																				// volba pro zaloћenн novйho programu
IDN_NEW,					"Создать новую программу.\nНовый",																	// [2] nбpovмda k volbм pro zaloћenн novйho programu
IDN_RENAME0,				"Переи&меновать...\tAlt+Enter",																		// volba ke zmмnм jmйna programu nebo sloћky
IDN_RENAME,					"Изменить имя программы/папки (нельзя переименовать примеры программ/папки).\nПереименовать",		// [2] nбpovмda k volbм pro zmмnu jmйna programu nebo sloћky
IDN_NEWCOPY0,				"Копи&ровать...\tCtrl+C",																			// volba k vytvoшenн kopie programu
IDN_NEWCOPY,				"Копировать избранную программу под другим именем.\nКопировать",									// [2] nбpovмda k volbм pro vytvoшenн kopie programu
IDN_PATH0,					"Новая &папка...\tCtrl+P",																			// volba k vytvoшenн novй sloћky
IDN_PATH,					"Создать новую папку для программ.\nНовая папка",													// [2] nбpovмda k volbм pro vytvoшenн novй sloћky
IDN_DELETE0,				"С&тереть...\tСтереть",																				// volba ke zruљenн programu nebo sloћky
IDN_DELETE,					"Удалить программу/папку (нельзя удалить примеры программ/папки).\nУдалить",						// [2] nбpovмda k volbм pro zruљenн programu nebo sloћky
IDN_SHORTNAME0,				"Краткие &имена",																					// !!! volba k zapnutн/vypnutн krбtkэch jmen souborщ
IDN_SHORTNAME,				"Программы/библиотеки файлов будут созданы с обрезанными до 8 букв именами.\nКраткие имена",		// [2] !!! nбpovмda k volbм pro zapnutн/vypnutн krбtkэch jmen souborщ
IDN_EXIT0,					"&Конец\tAlt+F4",																					// volba k ukonиenн aplikace Petr
IDN_EXIT,					"Завершить программу Пётр.\nКонец",																	// [2] nбpovмda k volbм pro ukonиenн aplikace Petr
// [1] Podmenu "Pнsmo" je souибstн menu "Soubor"
IDN_SETUP0,					"&Установка шрифта",																				// volba k vyvolбnн podmenu "Pнsmo"
IDN_SETUP10,				"Шрифт &выбранной программы...",																	// volba k nastavenн pнsma ve vэbмru programu
IDN_SETUP1,					"Установить шрифт в окне выбранной программы.\nШрифт выбранной программы",							// [2] nбpovмda k volbм pro nastavenн pнsma ve vэbмru programu
IDN_SETUP20,				"Шрифт &редактора программы...",																	// volba k nastavenн pнsma v editoru programu
IDN_SETUP2,					"Установить шрифт в окне редактора программы.\nШрифт редактора программы",							// [2] nбpovмda k volbм pro nastavenн pнsma v editoru programu
IDN_SETUP30,				"Шрифт редактора &текста...",																		// volba k nastavenн pнsma v editoru textu
IDN_SETUP3,					"Установить шрифт в окне редактора текста.\nШрифт редактора текста",								// [2] nбpovмda k volbм pro nastavenн pнsma v editoru textu
IDN_SETUP40,				"Шрифт &меню...",																					// volba k nastavenн pнsma nabнdky (menu)
IDN_SETUP4,					"Установить шрифт меню.\nШрифт меню",																// [2] nбpovмda k volbм pro nastavenн pнsma nabнdky (menu)
IDN_SETUP50,				"Шрифт окна &состояния...",																			// volba k nastavenн pнsma stavovй liљty
IDN_SETUP5,					"Установить шрифт окна состояния.\nШрифт окна состояния",											// [2] nбpovмda k volbм pro nastavenн pнsma stavovй liљty
// [1] Podmenu "Jazyk" - je souибstн menu "Soubor"
IDN_JAZYK0,					"&Язык",																							// volba k vyvolбnн podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Автоматически",																					// volba pro automatickэ vэbмr jazyku
IDN_JAZYKAUT,				"Выбрать язык автоматически согласно установки системы.\nАвтоматически",							// [2] nбpovмda k volbм pro automatickэ vэbмr jazyku
IDN_JAZYKPRE0,				"&Предыдущий\tCtrl+F9",																				// volba k navrбcenн k pшedchбzejнcнmu jazyku
IDN_JAZYKPRE,				"Переключить на предыдущий язык.\nПредыдущий",														// [2] nбpovмda k volbм pro navrбcenн k pшedchбzejнcнmu jazyku
IDN_JAZYKBUL0,				"Болгарский (Bulgarija)",																			// volba pro pшepnutн aplikace Petr na bulharskэ jazyk
IDN_JAZYKBUL,				"Переключить программу Петр на болгарский язык.\nБолгарский ",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na bulharskэ jazyk
IDN_JAZYKCZ0,				"Чешский (Cesky)",																					// volba pro pшepnutн aplikace Petr na иeskэ jazyk
IDN_JAZYKCZ,				"Переключить программу Пётр на чешский язык.\nЧешский",												// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na иeskэ jazyk
IDN_JAZYKDAN0,				"Датский (Danmark)",																				// volba pro pшepnutн aplikace Petr na dбnskэ jazyk
IDN_JAZYKDAN,				"Переключить программу Пётр на датский язык.\nДатский ",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na dбnskэ jazyk
IDN_JAZYKGER0,				"Немецкий (Deutsch)",																				// volba pro pшepnutн aplikace Petr na nмmeckэ jazyk
IDN_JAZYKGER,				"Переключить программу Пётр на немецкий язык.\nНемецкий ",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na nмmeckэ jazyk
IDN_JAZYKREC0,				"Греческий (Hellas)",																				// volba pro pшepnutн aplikace Petr na шeckэ jazyk
IDN_JAZYKREC,				"Переключить программу Пётр на греческий язык.\nГреческий ",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na шeckэ jazyk
IDN_JAZYKENG0,				"Английский (English)",																				// volba pro pшepnutн aplikace Petr na anglickэ jazyk
IDN_JAZYKENG,				"Переключить программу Пётр на английский язык.\nАнглийский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na anglickэ jazyk
IDN_JAZYKSPA0,				"Испанский (Espana)",																				// volba pro pшepnutн aplikace Petr na љpanмlskэ jazyk
IDN_JAZYKSPA,				"Переключить программу Пётр на испанский язык.\nИспанский",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na љpanмlskэ jazyk
IDN_JAZYKFIN0,				"Финский (Finland)",																				// volba pro pшepnutн aplikace Petr na finskэ jazyk
IDN_JAZYKFIN,				"Переключить программу Пётр на финский язык.\nФинский",												// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na finskэ jazyk
IDN_JAZYKFRA0,				"Французский (France)",																				// volba pro pшepnutн aplikace Petr na francouzskэ jazyk
IDN_JAZYKFRA,				"Переключить программу Пётр на французский язык.\nФранцузский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na fracouzskэ jazyk
IDN_JAZYKMAD0,				"Венгерский (Magyar)",																				// volba pro pшepnutн aplikace Petr na maпarskэ jazyk
IDN_JAZYKMAD,				"Переключить программу Пётр на венгерский язык.\nВенгерский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na maпarskэ jazyk
IDN_JAZYKISL0,				"Исландский (Island)",																				// volba pro pшepnutн aplikace Petr na islandskэ jazyk
IDN_JAZYKISL,				"Переключить программу Пётр на исландский язык.\nИсландский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na islandskэ jazyk
IDN_JAZYKITA0,				"Итальянский (Italy)",																				// volba pro pшepnutн aplikace Petr na italskэ jazyk
IDN_JAZYKITA,				"Переключить программу Пётр на итальянский язык.\nИтальянский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na italskэ jazyk
IDN_JAZYKHOL0,				"Голандский (Nederland)",																			// volba pro pшepnutн aplikace Petr na holandskэ jazyk
IDN_JAZYKHOL,				"Переключить программу Пётр на голандский язык.\nГоландский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na holandskэ jazyk
IDN_JAZYKNOR0,				"Новежский (Norge)",																				// volba pro pшepnutн aplikace Petr na norskэ jazyk
IDN_JAZYKNOR,				"Переключить программу Пётр на норвежский язык.\nНорвежский",										// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na norskэ jazyk
IDN_JAZYKPOL0,				"Польский (Po polsku)",																				// volba pro pшepnutн aplikace Petr na polskэ jazyk
IDN_JAZYKPOL,				"Переключить программу Пётр на польский язык.\nПольский",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na polskэ jazyk
IDN_JAZYKPOR0,				"Португальский (Portugal)",																			// volba pro pшepnutн aplikace Petr na portugalskэ jazyk
IDN_JAZYKPOR,				"Переключить программу Пётр на португальский язык.\nПортугальский",									// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na portugalskэ jazyk
IDN_JAZYKRUM0,				"Румынский (Romania)",																				// volba pro pшepnutн aplikace Petr na rumunskэ jazyk
IDN_JAZYKRUM,				"Переключить программу Пётр на румынский язык.\nРумынский",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na rumunskэ jazyk
IDN_JAZYKRUS0,				"Русский",																							// volba pro pшepnutн aplikace Petr na ruskэ jazyk
IDN_JAZYKRUS,				"Переключить программу Пётр на русский язык.\nРусский",												// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na ruskэ jazyk
IDN_JAZYKSRB0,				"Сербохорватский (Serbo-Croat)",																	// volba pro pшepnutн aplikace Petr na srbochorvбtskэ jazyk
IDN_JAZYKSRB,				"Переключить программу Пётр на сербохорватский язык.\nСербохорватский ",							// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na srbochorvбtskэ jazyk
IDN_JAZYKSLO0,				"Словацкий (Po slovensky)",																			// volba pro pшepnutн aplikace Petr na slovenskэ jazyk
IDN_JAZYKSLO,				"Переключить программу Пётр на словацкий язык.\nСловацкий",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na slovenskэ jazyk
IDN_JAZYKALB0,				"Албанский (Shqiperise)",																			// volba pro pшepnutн aplikace Petr na albбnskэ jazyk
IDN_JAZYKALB,				"Переключить программу Пётр на албанский язык.\nАлбанский",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na albбnskэ jazyk
IDN_JAZYKSWE0,				"Шведский (Swerige)",																				// volba pro pшepnutн aplikace Petr na љvйdskэ jazyk
IDN_JAZYKSWE,				"Переключить программу Пётр на шведский язык.\nШведский",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na љvйdskэ jazyk
IDN_JAZYKTUR0,				"Турецкий (Turkiye)",																				// volba pro pшepnutн aplikace Petr na tureckэ jazyk
IDN_JAZYKTUR,				"Переключить программу Пётр на турецкий язык.\nТурецкий",											// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na tureckэ jazyk
IDN_JAZYKVIE0,				"&Vietnamese (Vietnamese)",																			// volba pro pшepnutн aplikace Petr na vietnamskэ jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na vietnamskэ jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pшepnutн aplikace Petr na arabskэ jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na arabskэ jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pшepnutн aplikace Petr na hebrejskэ jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nбpovмda k volbм pro pшepnutн aplikace Petr na hebrejskэ jazyk
// [1] Menu "Pomoc" (Nбpovмda)
IDN_HLP0,					"&Справка",																							// volba k vyvolбnн menu "Pomoc" (Nбpovмda)
IDN_HELP0,					"&Справка\tF1",																						// volba k vyvolбnн kontextovй nбpovмdy
IDN_HELP,					"Показать справку по выбранному элементу.\nСправка",												// [2] nбpovмda k volbм pro vyvolбnн kontextovй nбpovмdy
IDN_HELPT0,					"Со&держание",																						// volba k vyvolбnн zбkladnн nбpovмdy (tйmata)
IDN_HELPT,					"Показать содержание справки.\nСодержание",															// [2] nбpovмda k volbм pro vyvolбnн zбkladnн nбpovмdy (tйmata)
IDN_HELPF0,					"&Поиск справки",																					// volba k vyvolбnн rejstшнku a hledбnн v nбpovмdм
IDN_HELPF,					"Поиск справки.\nПоиск справки",																	// [2] nбpovмda k volbм pro vyvolбnн rejstшнku a hledбnн v nбpovмdм
IDN_ABOUT0,					"&О программе Петр",																				// volba k vyvolбnн informacн o aplikaci Petr
IDN_ABOUT,					"Показать информацию о программе Петр, номер версии и авторские права.\nО программе Петр",			// [2] nбpovмda k volbм pro vyvolбnн informacн o aplikaci Petr
// [1] Menu "Soubor" editoru - doplтuje menu "Soubor" vэbмru programщ
IDN_CLOSE0,					"&Закрыть\tCtrl+O",																					// volba k uzavшenн editovanйho programu, nбvrat do vэbмru programu
IDN_CLOSE,					"Закрыть редактируемую программу и открыть другую.\nЗакрыть",										// [2] nбpovмda k volbм pro uzavшenн editovanйho programu a nбvratu do vэbмru programu
IDN_SAVE0,					"Со&хранить\tCtrl+S",																				// volba k uloћenн programu pшi editaci
IDN_SAVE,					"Сохранить изменения в программе.\nСохранить",														// [2] nбpovмda k volbм pro uloћenн programu pшi editaci
IDN_SAVEN0,					"Сохранить как &неисполняемую\tCtrl+Alt+S",															// volba k nespustitelnйmu uloћenн programu (bez spustitelnйho kуdu)
IDN_SAVEN,					"Сохранить программу как неисполняемую (меньше размер).\nСохранить как неисполняемую",				// [2] nбpovмda k volbм pro nespustitelnй uloћenн programu (bez spustitelnйho kуdu)
IDN_SAVE_AS0,				"Сохранить к&ак...\tCtrl+Shift+S",																	// volba k uloћenн programu do jinйho souboru nebo na jinэ disk
IDN_SAVE_AS,				"Сохранить программу под другим именем или на другой диск.\nСохранить как",							// [2] nбpovмda k volbм pro uloћenн programu do jinйho souboru nebo na jinэ disk
IDN_SAVE_REL0,				"&Дистрибутив...",																					// volba k uloћenн programu do distribuиnн needitovatelnй verze
IDN_SAVE_REL,				"Сохранить дистрибутив, не редактированую версию программы (только для лицензии Профессионал).\nДистрибутив",	// [2] nбpovмda k volbм pro uloћenн programu do distribuиnн needitovatelnй verze
IDN_EXPORT0,				"&Экспорт...",																						// volba k exportovбnн programu
IDN_EXPORT,					"Экспорт программы в текстовый формат.\nЭкспорт",													// [2] nбpovмda k volbм pro exportovбnн programu
IDN_IMPORT0,				"&Импорт...",																						// volba k importovбnн programu
IDN_IMPORT,					"Импорт программы из текстовой формы.\nИмпорт",														// [2] nбpovмda k volbм pro importovбnн programu
// [1] Menu "Ъpravy" (Editace)
IDN_EDIT0,					"&Редактировать",																					// volba k vyvolбnн menu "Ъpravy" (Editace)
IDN_UNDO0,					"&Отменить\tCtrl+Z",																				// volba k navrбcenн provedenэch zmмn UNDO
IDN_UNDO,					"Отменить последнее действие.\nОтменить",															// [2] nбpovмda k volbм pro navrбcenн provedenэch zmмn UNDO
IDN_REDO0,					"&Повторить\tCtrl+Y",																				// volba k odvolбnн navrбcenэch zmмn REDO
IDN_REDO,					"Повторить отмененное последнее действие.\nПовторить",												// [2] nбpovмda k volbм pro odvolбnн navrбcenэch zmмn REDO
IDN_CUT0,					"&Вырезать\tCtrl+X",																				// volba k vyjmutн oznaиenйho bloku do schrбnky CUT
IDN_CUT,					"Вырезать выбранное и поместить в буфер обмена.\nВырезать",											// [2] nбpovмda k volbм pro vyjmutн oznaиenйho bloku do schrбnky CUT
IDN_COPY0,					"&Копировать\tCtrl+C",																				// volba ke kopii oznaиenйho bloku do schrбnky COPY
IDN_COPY,					"Копировать выбранное  в буфер обмена.\nКопировать",												// [2] nбpovмda k volbм pro kopii oznaиenйho bloku do schrбnky COPY
IDN_PASTE0,					"В&ставить\tCtrl+V",																				// volba k vloћenн bloku ze schrбnky PASTE
IDN_PASTE,					"Вставить содержимое буфера обмена в текущую позицию.\nВставить",									// [2] nбpovмda k volbм pro vloћenн bloku ze schrбnky PASTE
IDN_CLEAR0,					"&Удалить\tУдалить",																				// volba ke zruљenн oznaиenйho bloku CLEAR
IDN_CLEAR,					"Удалить выбранное.\nУдалить",																		// [2] nбpovмda k volbм pro zruљenн oznaиenйho bloku CLEAR
IDN_ALL0,					"В&ыбрать все\tCtrl+A",																				// volba k oznaиenн vљeho jako blok SELECT ALL
IDN_ALL,					"Выбрать все.\nВыбрать все",																		// [2] nбpovмda k volbм pro oznaиenн vљeho jako blok SELECT ALL
IDN_DITHER0,				"&Дизеринг",																						// volba k zapnutн/vypnutн ditheringu (rastrovanй zobrazenн barev)
IDN_DITHER,					"Применить дизеринг при импорте и уменьшении картинок.\nДизеринг",									// [2] nбpovмda k volbм pro zapnutн/vypnutн ditheringu (rastrovanйho zobrazenн barev)
// [1] Menu "Zobrazenн"
IDN_ZOBRAZ0,				"&Вид",																								// volba k vyvolбnн menu "Zobrazenн"
IDN_IN0,					"Зуум &наезд\tCtrl+[+]",																			// volba ke zvмtљenн mмшнtka zobrazenн (ZOOM IN)
IDN_IN,						"Увеличение масштаба изображения (наезд).\nЗуум наезд",												// [2] nбpovмda k volbм pro zvмtљenн mмшнtka zobrazenн (ZOOM IN)
IDN_OUT0,					"Зуум &откат\tCtrl+[-]",																			// volba ke zmenљenн mмшнtka zobrazenн (ZOOM OUT)
IDN_OUT,					"Уменьшение масштаба изображения (откат).\nЗуум откат",												// [2] nбpovмda k volbм pro zmenљenн mмшнtka zobrazenн (ZOOM OUT)
IDN_HIST_PREV0,				"&Предыдущее редактирование\tCtrl+Up",																// volba k navrбcenн zpмt v historii editacн
IDN_HIST_PREV,				"Возврат к предыдущему редактируемому элементу.\nПредыдущее редактирование",						// [2] nбpovмda k volbм pro navrбcenн zpмt v historii editacн
IDN_HIST_NEXT0,				"&Следующее редактирование\tCtrl+Down",																// volba k posunu vpшed v historii editacн
IDN_HIST_NEXT,				"Возврат к следующему редактируемому элементу.\nСледующее редактирование",							// [2] nбpovмda k volbм pro posun vpшed v historii editacн
IDN_FIND0,					"Поиск &текста...\tCtrl+F",																			// volba k vyvolбnн dialogu k hledбnн textu
IDN_FIND,					"Поиск введенного текста.\nПоиск текста",															// [2] nбpovмda k volbм pro vyvolбnн dialogu k hledбnн textu
IDN_FIND_PREV0,				"П&редыдущий текст\tShift+F3",																		// volba k opakovбnн hledбnн textu zpмt
IDN_FIND_PREV,				"Поиск прежде просмотренного текста.\nПредыдущий текст",											// [2] nбpovмda k volbм pro opakovбnн hledбnн textu zpмt
IDN_FIND_NEXT0,				"С&ледующий текст\tF3",																				// volba k opakovбnн hledбnн textu vpшed
IDN_FIND_NEXT,				"Поиск следующего текста.\nСледующий текст",														// [2] nбpovмda k volbм pro hledбnн textu vpшed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Программа",																						// volba k vyvolбnн menu "Program"
IDN_LOCK0,					"&Замок",																							// volba k uzamknutн/odemknutн vybranйho prvku
IDN_LOCK,					"Поставить замок от изменений.\nЗамок",																// [2] nбpovмda k volbм pro uzamknutн/odemknutн vybranйho prvku
IDN_OFF0,					"&Выключить",																						// volba k vypnutн/zapnutн funkиnosti vybranйho prvku
IDN_OFF,					"Выключить функционирование элемента.\nВыключить",													// [2] nбpovмda k volbм pro vypnutн/zapnutн funkиnosti vybranйho prvku
IDN_EDIT_NAME0,				"&Описание\tAlt+Enter",																				// volba k vyvolбnн editace textu prvku
IDN_EDIT_NAME,				"Редактировать описание элемента.\nОписание",														// [2] nбpovмda k volbм pro vyvolбnн editace textu prvku
IDN_DEF_NAME0,				"Описание по &умолчанию",																			// volba k zapnutн/vypnutн implicitnнho textu prvku
IDN_DEF_NAME,				"Использовать описание элемента по умолчанию.\nОписание по умолчанию",								// [2] nбpovмda k volbм pro zapnutн/vypnutн implicitnнho textu prvku
IDN_EDIT_ICON0,				"&Икона",																							// volba k vyvolбnн editace ikony prvku
IDN_EDIT_ICON,				"Редактировать икону элемента.\nИкона",																// [2] nбpovмda k volbм pro vyvolбnн editace ikony prvku
IDN_DEF_ICON0,				"Ико&на по умолчанию",																				// volba k zapnutн/vypnutн implicitnн ikony prvku
IDN_DEF_ICON,				"Использовать икону элемента по умолчанию.\nИкона по умолчанию",									// [2] nбpovмda k volbм pro zapnutн/vypnutн implicitnн ikony prvku
IDN_REF_DEF0,				"&Декларация",																						// volba k nalezenн deklarace prvku
IDN_REF_DEF,				"Найти декларацие элемента.\nДекларация",															// [2] nбpovмda k volbм pro nalezenн deklarace prvku
IDN_REF_PREV0,				"&Предыдущее использование",																		// volba k nalezenн pшedeљlйho pouћitн prvku
IDN_REF_PREV,				"Найти предыдущее использование элемента.\nПредыдущее использование",								// [2] nбpovмda k volbм pro nalezenн pшedeљlйho pouћitн prvku
IDN_REF_NEXT0,				"&Следущее использование",																			// volba k nalezenн dalљнho pouћitн prvku
IDN_REF_NEXT,				"Найти следущее использование элемента.\nСледущее использование",									// [2] nбpovмda k volbм pro nalezenн dalљнho pouћitн prvku
// [1] Menu "Obrбzek" - editace obrбzkщ a ikon
IDN_OBRAZEK0,				"&Картинка",																						// volba k vyvolбnн menu "Obrбzek"
IDN_DIMEN0,					"&Размеры...",																						// volba k nastavenн rozmмrщ obrбzku nebo plochy
IDN_DIMEN,					"Установить общие размеры.\nРазмеры",																// [2] nбpovмda k volbм pro nastavenн rozmмrщ obrбzku nebo plochy
IDN_RASTR0,					"Рас&тр",																							// volba k vypnutн/zapnutн rastru v obrбzku nebo ploљe
IDN_RASTR,					"Включить/выключить ориентацию растра дисплея.\nРастр",												// [2] nбpovмda k volbм pro vypnutн/zapnutн rastru v obrбzku nebo ploљe
IDN_EDITBLOK0,				"Ред&актировать...",																				// volba k vyvolбnн okna konverzн obrбzku
IDN_EDITBLOK,				"Редактировать картинку/часть (размер, поворот, цвет).\nРедактировать",								// [2] nбpovмda k volbм pro vyvolбnн okna konverzн obrбzku
IDN_OTISK0,					"&Штамп блока",																						// volba k otisku bloku do obrбzku
IDN_OTISK,					"Штамповать блок на картинку.\nШтамп блока",														// [2] nбpovмda k volbм pro otisk bloku do obrбzku
IDN_YFLIP0,					"&Горизонтально",																					// volba k horizontбlnнmu pшevrбcenн obrбzku
IDN_YFLIP,					"Отразить картинку/часть горизонтально.\nГоризонтально",											// [2] nбpovмda k volbм pro horizontбlnн pшevrбcenн obrбzku
IDN_XFLIP0,					"&Вертикально",																						// volba k vertikбlnнmu pшevrбcenн obrбzku
IDN_XFLIP,					"Отразить картинку/часть вертикально.\nВертикально",												// [2] nбpovмda k volbм pro vertikбlnн pшevrбcenн obrбzku
IDN_LROT0,					"В&лево",																							// volba k rotaci obrбzku vlevo (proti smмru hodinovэch ruиiиek)
IDN_LROT,					"Повернуть картинку влево (на 90 градусов против часовой стрелки).\nВлево",							// [2] nбpovмda k volbм pro rotaci obrбzku vlevo (proti smмru hodinovэch ruиiиek)
IDN_RROT0,					"В&право",																							// volba k rotaci obrбzku vpravo (ve smмru hodinovэch ruиiиek)
IDN_RROT,					"Повернуть картинку вправо (на 90 градусов по часовой стрелке).\nВправо",							// [2] nбpovмda k volbм pro rotaci obrбzku vpravo (ve smмru hodinovэch ruиiиek)
IDN_MUL20,					"&Удвоить",																							// volba ke zvмtљenн obrбzku na dvojnбsobek
IDN_MUL2,					"Увеличить размер картинки или ее части вдвое.\nУдвоить",											// [2] nбpovмda k volbм pro zvмtљenн obrбzku na dvojnбsobek
IDN_DIV20,					"Полов&ина",																						// volba ke zmenљenн obrбzku na polovinu
IDN_DIV2,					"Уменьшить размер картинки или ее части наполовину.\nПоловина",										// [2] nбpovмda k volbм pro zmenљenн obrбzku na polovinu
IDN_MULDIV0,				"Раз&мер...",																						// volba k vyvolбnн okna pro volitelnou zmмnu velikosti obrбzku
IDN_MULDIV,					"Изменить произвольно размер картинки или ее части.\nРазмер",										// [2] nбpovмda k volbм pro vyvolбnн okna pro volitelnou zmмnu velikosti obrбzku
IDN_XCOL0,					"&Обмен",																							// volba k zбmмnм barev pro levй a pravй tlaинtko myљi v obrбzku
IDN_XCOL,					"Обмен цветов левой и правой кнопки мыши для картинки или ее части.\nОбмен",						// [2] nбpovмda k volbм pro zбmмnu barev pro levй a pravй tlaинtko myљi v obrбzku
IDN_SCOL0,					"&Замена",																							// volba k nбhradм barvy pro pravй tlaинtko barvou pro levй tlaинtko myљi v obrбzku
IDN_SCOL,					"Замена цвета левой кнопки мыши на цвет правой кнопки для картинки или ее части.\nЗамена",			// [2] nбpovмda k volbм pro nбhradu barvy pro pravй tlaинtko barvou pro levй tlaинtko myљi v obrбzku
// [1] Menu "Nбstroje" - editace obrбzkщ a ikon
IDN_NASTROJE0,				"&Инструменты",																						// volba k vyvolбnн menu "Nбstroje"
IDN_PEN0,					"&Перо",																							// volba k zapnutн kreslenн pomocн pera
IDN_PEN,					"Рисовать при помощи пера.\nПеро",																	// [2] nбpovмda k volbм pro zapnutн kreslenн pomocн pera
IDN_LINE0,					"&Линия",																							// volba k zapnutн kreslenн ибry
IDN_LINE,					"Рисовать линию.\nЛиния",																			// [2] nбpovмda k volbм pro zapnutн kreslenн ибry
IDN_BOX0,					"Прямо&угольник",																					// volba k zapnutн kreslenн obdйlnнku bez vэplnм
IDN_BOX,					"Рисовать прямоугольник.\nПрямоугольник",															// [2] nбpovмda k volbм pro zapnutн kreslenн obdйlnнku bez vэplnм
IDN_FILLBOX0,				"&Заполненный прямоугольник",																		// volba k zapnutн kreslenн obdйlnнku s vэplnн
IDN_FILLBOX,				"Рисовать заполненный прямоугольник.\nЗаполненный прямоугольник",									// [2] nбpovмda k volbм pro zapnutн kreslenн obdйlnнku s vэplnн
IDN_CIRCLE0,				"&Окружность",																						// volba k zapnutн kreslenн kruћnice bez vэplnм
IDN_CIRCLE,					"Рисовать окружность.\nОкружность",																	// [2] nбpovмda k volbм pro zapnutн kreslenн kruћnice bez vэplnм
IDN_FILLCIRCLE0,			"Кру&г",																							// volba k zapnutн kreslenн kruhu s vэplnн
IDN_FILLCIRCLE,				"Рисовать круг.\nКруг",																				// [2] nбpovмda k volbм pro zapnutн kreslenн kruhu s vэplnн
IDN_ELLIPSE0,				"&Эллипс",																							// volba k zapnutн kreslenн elipsy bez vэplnм
IDN_ELLIPSE,				"Рисовать эллипс.\nЭллипс",																			// [2] nбpovмda k zapnutн kreslenн elipsy bez vэplnм
IDN_FILLELLIPSE0,			"Заполне&нный эллипс",																				// volba k zapnutн kreslenн elipsy s vэplnн
IDN_FILLELLIPSE,			"Рисовать заполненный эллипс.\nЗаполненный эллипс",													// [2] nбpovмda k volbм pro zapnutн kreslenн elipsy s vэplnн
IDN_SPHERE0,				"Сф&ера",																							// volba k zapnutн kreslenн koule
IDN_SPHERE,					"Рисовать сферу.\nСфера",																			// [2] nбpovмda k volbм pro zapnutн kreslenн koule
IDN_SELECT0,				"Вы&бор",																							// volba k zapnutн reћimu prбce s blokem
IDN_SELECT,					"Выбрать определенную часть.\nВыбор",																// [2] nбpovмda k volbм pro zapnutн reћimu prбce s blokem
IDN_SPRAY0,					"Спр&ей",																							// volba k zapnutн kreslenн pomocн spreje
IDN_SPRAY,					"Рисовать спреем.\nСпрей",																			// [2] nбpovмda k volbм pro zapnutн kreslenн pomocн spreje
IDN_PIPE0,					"П&ипетка",																							// volba k nabrбnн barvy z obrбzku
IDN_PIPE,					"Установить цвет под курсором.\nПипетка",															// [2] nбpovмda k volbм pro nabrбnн barvy z obrбzku
IDN_FILL0,					"Зак&расить",																						// volba k zapnutн reћimu vyplтovбnн plochy
IDN_FILL,					"Закрасить поверхность краской.\nЗакрасить",														// [2] nбpovмda k volbм pro zapnutн reћimu vyplтovбnн plochy
IDN_TEXT0,					"&Текст",																							// volba k vyvolбnн psanн textu do obrбzku
IDN_TEXT,					"Писать текст.\nТекст",																				// [2] nбpovмda k volbм pro vyvolбnн psanн textu do obrбzku
// [1] Menu "Tlouљќka" - editace obrбzkщ a ikon
IDN_TLOUSTKA0,				"Тол&щина",																							// volba k vyvolбnн menu "Tlouљќka"
IDN_WIDTH10,				"Толщина &1 пиксел",																				// volba k nastavenн tlouљќky pera 1 bod
IDN_WIDTH1,					"Рисовать линии толщиной 1 пиксел.\nТолщина 1 пиксел",												// [2] nбpovмda k volbм pro nastavenн tlouљќky pera 1 bod
IDN_WIDTH20,				"Толщина &2 пиксел",																				// volba k nastavenн tlouљќky pera 2 body
IDN_WIDTH2,					"Рисовать линии толщиной 2 пиксела.\nТолщина 2 пиксел",												// [2] nбpovмda k volbм pro nastavenн tlouљќky pera 2 body
IDN_WIDTH30,				"Толщина &5 пикселей",																				// volba k nastavenн tlouљќky pera 5 bodщ
IDN_WIDTH3,					"Рисовать линии толщиной 5 пикселей.\nТолщина 5 пикселей",											// [2] nбpovмda k volbм pro nastavenн tlouљќky pera 5 bodщ
IDN_WIDTH40,				"Толщина &9 пикселей",																				// volba k nastavenн tlouљќky pera 9 bodщ
IDN_WIDTH4,					"Рисовать линии толщиной 9 пикселей.\nТолщина 9 пикселей",											// [2] nбpovмda k volbм pro nastavenн tlouљќky pera 9 bodщ
IDN_WIDTH50,				"Толщина 21 &пиксел",																				// volba k nastavenн tlouљќky pera 21 bodщ
IDN_WIDTH5,					"Рисовать линии толщиной 21 пиксел.\nТолщина 21 пиксел",											// [2] nбpovмda k volbм pro nastavenн tlouљќky pera 21 bodщ
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"&Лист",																							// volba k vyvolбnн menu "Plocha"
IDN_EDITMAP0,				"Ре&дактирование",																					// volba k zapnutн/vypnutн mуdu editace polниek plochy
IDN_EDITMAP,				"Включить/выключить режим редактирования листа.\nРедактирование",									// [2] nбpovмda k volbм pro zapnutн/vypnutн mуdu editace polниek plochy
IDN_FILLMAP0,				"&Заполнение",																						// volba k zapnutн/vypnutн mуdu vyplтovбnн plochy polниkem
IDN_FILLMAP,				"Включить/выключить режим заполнения листа предметами.\nЗаполнение",								// [2] nбpovмda k volbм pro zapnutн/vypnutн mуdu vyplтovбnн plochy polниkem
IDN_MAP0,					"&Предметы",																						// volba k pшepnutн plochy na editaci pшedmмtщ
IDN_MAP,					"Редактирование предметов на листе.\nПредметы",														// [2] nбpovмda k volbм pro pшepnutн plochy na editaci pшedmмtщ
IDN_SWC10,					"Флаг &1",																							// volba k pшepnutн plochy na editaci pшepнnaиe 1
IDN_SWC1,					"Редактировать флаг 1.\nФлаг 1",																	// [2] nбpovмda k volbм pro pшepnutн plochy na editaci pшepнnaиe 1
IDN_SWC20,					"Флаг &2",																							// volba k pшepnutн plochy na editaci pшepнnaиe 2
IDN_SWC2,					"Редактировать флаг 2.\nФлаг 2",																	// [2] nбpovмda k volbм pro pшepnutн plochy na editaci pшepнnaиe 2
IDN_SWC30,					"Флаг &3",																							// volba k pшepnutн plochy na editaci pшepнnaиe 3
IDN_SWC3,					"Редактировать флаг 3.\nФлаг 3",																	// [2] nбpovмda k volbм pro pшepnutн plochy na editaci pшepнnaиe 3
IDN_SWC40,					"Флаг &4",																							// volba k pшepnutн plochy na editaci pшepнnaиe 4
IDN_SWC4,					"Редактировать флаг 4.\nФлаг 4",																	// [2] nбpovмda k volbм pro pшepnutн plochy na editaci pшepнnaиe 4
IDN_SWC50,					"Флаг &5",																							// volba k pшepnutн plochy na editaci pшepнnaиe 5
IDN_SWC5,					"Редактировать флаг5.\nФлаг 5",																		// [2] nбpovмda k volbм pro pшepnutн plochy na editaci pшepнnaиe 5
IDN_SWCN10,					"&Число 1",																							// volba k pшepnutн plochy na editaci инselnй hodnoty 1
IDN_SWCN1,					"Редактировать число 1 (от 0 до 1023).\nЧисло 1",													// [2] nбpovмda k volbм pro pшepnutн plochy na editaci инselnй hodnoty 1
IDN_SWCN20,					"Ч&исло 2",																							// volba k pшepnutн plochy na editaci инselnй hodnoty 2
IDN_SWCN2,					"Редактировать число 2 (от 0 до 1023).\nЧисло 2",													// [2] nбpovмda k volbм pro pшepnutн plochy na editaci инselnй hodnoty 2
IDN_SWCN30,					"Чи&сло 3",																							// volba k pшepnutн plochy na editaci инselnй hodnoty 3
IDN_SWCN3,					"Редактировать число 3 (от 0 до 1023).\nЧисло 3",													// [2] nбpovмda k volbм pro pшepnutн plochy na editaci инselnй hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"Сп&райт",																							// volba k vyvolбnн menu "Sprajt"
IDN_SPRITEPAR0,				"&Свойства",																						// volba k vyvolбnн okna pro nastavenн vlastnostн sprajtu
IDN_SPRITEPAR,				"Установить свойства спрайта (количество фаз, направления ...).\nСвойства",							// [2] nбpovмda k volbм pro vyvolбnн okna k nastavenн vlastnostн sprajtu
IDN_TEST0,					"&Тест",																							// volba k vyvolбnн okna pro test sprajtu
IDN_TEST,					"Начать тест спрайта.\nТест",																		// [2] nбpovмda k volbм pro vyvolбnн okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplтuje menu "Hudba"
IDN_SOUND0,					"Зв&ук",																							// volba k vyvolбnн menu "Zvuk"
IDN_PLAY0,					"&Играть",																							// volba ke spuљtмnн pшehrбvбnн zvuku nebo hudby (PLAY)
IDN_PLAY,					"Начать проигрывание звука/музыки.\nИграть",														// [2] nбpovмda k volbм pro spuљtмnн pшehrбvбnн zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"П&ауза",																							// volba k pozastavenн pшehrбvбnн zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Сделать паузу в проигрывании.\nПауза",																// [2] nбpovмda k volbм pro pozastavenн pшehrбvбnн zvuku nebo hudby (PAUSE)
IDN_STOP0,					"Ст&оп",																							// volba k zastavenн pшehrбvбnн zvuku nebo hudby (STOP)
IDN_STOP,					"Остановить проигрывание.\nСтоп",																	// [2] nбpovмda k volbм pro zastavenн pшehrбvбnн zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Цикл",																							// volba k zapnutн/vypnutн opakovanйho pшehrбvбnн zvuku nebo hudby (LOOP)
IDN_LOOP,					"Включить/выключить повторное проигрывание.\nЦикл",													// [2] nбpovмda k volbм pro zapnutн/vypnutн opakovanйho pшehrбvбnн zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Запись",																							// volba ke spuљtмnн nahrбvбnн zvuku (RECORD)
IDN_RECORD,					"Начать запись.\nЗапись",																			// [2] nбpovмda k volbм pro spuљtмnн nahrбvбnн zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplтuje menu "Zvuk"
IDN_MUSIC0,					"&Музыка",																							// volba k vyvolбnн menu "Hudba"
IDN_REW0,					"&Назад",																							// volba k posunu pшehrбvбnн hudby o 10 sekund zpмt
IDN_REW,					"Перемотка назад на 10 секунд.\nНазад",																// [2] nбpovмda k volbм pro posun pшehrбvбnн hudby o 10 sekund zpмt
IDN_FRW0,					"&Вперед",																							// volba k posunu pшehrбvбnн hudby o 10 sekund vpшed
IDN_FRW,					"Перемотка вперед на 10 секунд.\nВперед",															// [2] nбpovмda k volbм pro posun pшehrбvбnн hudby o 10 sekund vpшed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"О программе Петр",																					// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Версия программы",																					// text pшed oznaиenнm verze v oknм
IDC_COPYNAME,				"Copyright © 1999-2012 Miroslav Nemecek",															// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// nбzev firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSИ
IDC_ADRMESTO,				"Roznov pod Radhostem",																				// Roћnov pod Radhoљtмm
IDC_REPUBLIKA,				"Czech Republic",																					// Иeskб Republika
IDC_DEMOTEXT1,				"Демоверсия не может сохранять или исполнять новые",												// 1. (ze 3) шбdek informaиnнho textu v oknм DEMO verze
IDC_DEMOTEXT2,				"или измененные программы. Редактирование возможно,",												// 2. (ze 3) шбdek informaиnнho textu v oknм DEMO verze
IDC_DEMOTEXT3,				"справка и сохранение в библиотеку полностью функционирует.",										// 3. (ze 3) шбdek informaиnнho textu v oknм DEMO verze
IDC_DEMOTEXT4,				"Актуальная информация о программе находится по адресу:",											// informaиnн text v oknм DEMO verze "aktuбlnн informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Заказы направляйте по адресу:",																	// informaиnн text v oknм DEMO verze "objednбvky ... na adresu:"
IDC_LICTITLE,				"ЛИЦЕНЗИЯ",																							// nadpis licenиnнch informacн v oknм PLNЙ verze
IDC_LICTITLE0,				"неограниченная",																					// poиet licencн neomezenэ - v oknм PLNЙ verze
IDC_LICTITLE1,				"для 1 компьютера",																					// poиet licencн pro 1 poинtaи - v oknм PLNЙ verze
IDC_LICTITLE2,				"компьютеров",																						// poиet licencн pro 2 aћ 4 poинtaиe - v oknм PLNЙ verze
IDC_LICTITLE3,				"компьютеров",																						// poиet licencн pro 5 a vнce poинtaищ - v oknм PLNЙ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Лайт версия Питера имеет ограниченные возможности",												// 1. (z 5) шбdek informaиnнho textu v oknм LITE verze
IDC_LITETEXT2,				"программирования (неработающие элементы имеют серые иконы),",										// 2. (z 5) шбdek informaиnнho textu v oknм LITE verze
IDC_LITETEXT3,				"это FREEWARE и распространяется бесплатно для личного",											// 3. (z 5) шбdek informaиnнho textu v oknм LITE verze
IDC_LITETEXT4,				"использования. Для коммерческого использования и для школ плата ",									// 4. (z 5) шбdek informaиnнho textu v oknм LITE verze
IDC_LITETEXT5,				"взымается в соответствии с таблицей на странице www.gemtree.com.",									// 5. (z 5) шбdek informaиnнho textu v oknм LITE verze
// [3] Dialog hledбnн textu
IDN_FIND_DIALOG,			"Поиск текста",																						// titulek okna hledбnн textu
IDN_FINDTEXT,				"Введите текст для поиска:",																		// vэzva k zadбnн textu k hledбnн
IDN_CANCEL0,				"Отмена",																							// text tlaинtka Storno (CANCEL) (vyuћнvб se i u jinэch dialogщ a v interpreteru v dialogu zadбnн textu)
// [3] Dialog zadбnн rozmмru plochy
IDN_MAPDIMEN,				"Размеры листа",																					// titulek okna zadбnн rozmмrщ plochy
IDN_SIRKA,					"Ширина:",																							// nadpis pшed polem pro zadбnн љншky (vyuћнvб se i u jinэch dialogщ)
IDN_VYSKA,					"Высота:",																							// nadpis pшed polem pro zadбnн vэљky (vyuћнvб se i u jinэch dialogщ)
// [3] Dialog hlбљenн chyby pшi otevшenн programu k editaci
IDN_OPENERR,				"Ошибка открытия",																					// titulek okna hlбљenн chyby otevшenн programu k editaci
IDN_OPENERR1,				"Программа не может бить открыта.",																	// 1. шбdek okna hlбљenн chyby otevшenн programu k editaci (nбsleduje oddмlovacн prбzdnэ шбdek)
IDN_OPENERR2,				"Возможно, уже открыта другим приложением",															// 2. шбdek okna hlбљenн chyby otevшenн programu k editaci
IDN_OPENERR3,				"или доступ к файлу запрещен.",																		// 3. шбdek okna hlбљenн chyby otevшenн programu k editaci
// [3] Dialog hlбљenн chyby pшi иtenн ze souboru
IDN_READERR,				"Ошибка чтения",																					// titulek okna hlбљenн chyby иtenн souboru
IDN_READERR1,				"Ошибка чтения программы.",																			// 1. шбdek okna hlбљenн chyby иtenн souboru (nбsleduje oddмlovacн prбzdnэ шбdek)
IDN_READERR2,				"Программа повреждена или была создана более новым",												// 2. шбdek okna hlбљenн chyby иtenн souboru
IDN_READERR3,				"редактором и поэтому не может работать корректно.",												// 3. шбdek okna hlбљenн chyby иtenн souboru
// [3] Dialog hlбљenн chyby pro Lite verzi
IDN_LITEERR,				"Неподдерживаемые команды",																			// titulek okna hlбљenн chyby Lite verze
IDN_LITEERR1,				"Предупреждение: Программа использует команды, которые",											// 1. шбdek okna hlбљenн chyby Lite verze
IDN_LITEERR2,				"не поддерживает Лайт версия Питера. При сохранении",												// 2. шбdek okna hlбљenн chyby Lite verze
IDN_LITEERR3,				"программа станет неработоспособной.",																// 3. шбdek okna hlбљenн chyby Lite verze
// [3] Dialog pro konverzi obrбzku (otбиenн, velikost, barvy)
IDN_PICBLOK,				"Изменение картинки или ее части",																	// titulek okna pro konverze obrбzku
IDN_PREVRACENI,				"Отразить",																							// nadpis rбmeиku operacн pшevrбcenн
IDN_YFLIP_TXT,				"Горизонтально",																					// popis tlaинtka pro horizontбlnн pшevrбcenн
IDN_XFLIP_TXT,				"Вертикально",																						// popis tlaинtka pro vertikбlnн pшevrбcenн
IDN_OTOCENI,				"Вращать",																							// nadpis rбmeиku operacн rotace
IDN_LROT_TXT,				"+1/2 пи (+90 град.)",																				// popis tlaинtka pro otoиenн o 90 stupтщ vlevo
IDN_RROT_TXT,				"-1/2 пи (-90 град.)",																				// popis tlaинtka pro otoиenн o 90 stupтщ vpravo
IDN_LROT67_TXT,				"+3/8 пи (+67,5 град.)",																			// popis tlaинtka pro otoиenн o 67.5 stupтщ vlevo
IDN_RROT67_TXT,				"-3/8 пи (-67,5 град.)",																			// popis tlaинtka pro otoиenн o 67.5 stupтщ vpravo
IDN_LROT60_TXT,				"+1/3 пи (+60 град.)",																				// popis tlaинtka pro otoиenн o 60 stupтщ vlevo
IDN_RROT60_TXT,				"-1/3 пи (-60 град.)",																				// popis tlaинtka pro otoиenн o 60 stupтщ vpravo
IDN_LROT45_TXT,				"+1/4 пи (+45 град.)",																				// popis tlaинtka pro otoиenн o 45 stupтщ vlevo
IDN_RROT45_TXT,				"-1/4 пи (-45 град.)",																				// popis tlaинtka pro otoиenн o 45 stupтщ vpravo
IDN_LROT30_TXT,				"+1/6 пи (+30 град.)",																				// popis tlaинtka pro otoиenн o 30 stupтщ vlevo
IDN_RROT30_TXT,				"-1/6 пи (-30 град.)",																				// popis tlaинtka pro otoиenн o 30 stupтщ vpravo
IDN_LROT22_TXT,				"+1/8 пи (+22,5 град.)",																			// popis tlaинtka pro otoиenн o 22.5 stupтщ vlevo
IDN_RROT22_TXT,				"-1/8 пи (-22,5 град.)",																			// popis tlaинtka pro otoиenн o 22.5 stupтщ vpravo
IDN_ZVETSENI,				"Размер",																							// nadpis rбmeиku operacн zmмny velikosti
IDN_MUL2_TXT,				"Удвоить",																							// popis tlaинtka pro zdvojnбsobenн obrбzku
IDN_DIV2_TXT,				"Половина",																							// popis tlaинtka pro zmenљenн obrбzku na polovinu
IDN_MULDIV_TXT,				"Произвольно",																						// popis tlaинtka pro volitelnou velikost obrбzku
IDN_BARVY,					"Цвета",																							// nadpis rбmeиku operacн s barvami
IDN_XCOL_TXT,				"Левая <-> правая кнопка",																			// popis tlaинtka pro zбmмnu barev pro levй a pravй tlaинtko myљi
IDN_SCOL_TXT,				"Левая -> правая кнопка",																			// popis tlaинtka pro nбhradu barvy pravйho tlaинtka barvou levйho tlaинtka
// [3] Dialog nastavenн rozmмrщ obrбzku
IDN_PICDIMEN,				"Размеры картинки",																					// titulek okna pro nastavenн rozmмrщ obrбzku
IDN_ROZMERY,				"Размеры даны",																						// nadpis rбmeиku volby jednotky
IDC_KROK,					"В &шагах",																							// [1] volba jednotky v krocнch
IDC_BOD,					"В &пикселях",																						// [1] volba jednotky v bodech
// [3] Dialog volitelnй zmмny velikosti obrбzku
IDN_PICRESIZE,				"Изменение размеров картинки или ее части",															// titulek okna pro volitelnou zmмnu velikosti obrбzku
IDN_SOUCASNE_ROZMERY,		"Актуальные размеры:",																				// nadpis pшed zobrazenнm souиasnэch rozmмrщ
IDN_KROKU,					"шагов",																							// text za ъdajem velikosti obrбzku v krocнch (pouћнvб i okno pro nastavenн vlastnostн sprajtщ)
IDN_BODU,					"пикселей",																							// text za ъdajem velikosti obrбzku v bodech
IDN_NOVE_ROZMERY,			"Новые размеры",																					// nadpis rбmeиku pro nastavenн novэch rozmмrщ obrбzku
IDN_SIRKA2,					"Ширина:",																							// nadpis nad sloupeиkem zobrazenн љншky obrбzku
IDN_VYSKA2,					"Высота:",																							// nadpis nad sloupeиkem zobrazenн vэљky obrбzku
IDN_PICRESIZE_STEP,			"В шагах",																							// [1] volba rozmмrщ zadanэch v krocнch
IDN_PICRESIZE_POINT,		"В пикселях",																						// [1] volba rozmмrщ zadanэch v bodech
IDN_PICRESIZE_PROC,			"В процентах",																						// [1] volba rozmмrщ zadanэch v procentech
IDN_PICRESIZE_PROP,			"Сохранять соотношение сторон (ширина/высота)",														// [1] pшepнnaи zachovбnн pomмrщ stran obrбzku
IDN_PICRESIZE_INT,			"Спрямить линии (точно, но медленно)",																// [1] pшepнnaи zjemnмnн hran - interpolace
IDN_PICRESIZE_DITH,			"Дизеринг (включить для фото, выключить для рисунков)",												// [1] pшepнnaи pouћitн ditheringu
// [3] Dialog vэbмru barvy
IDN_SELECT_COLOR,			"Выбор цвета",																						// titulek okna vэbмru barvy
// [3] Dialog hlбљenн chyby vytvoшenн novйho programu
IDN_SELECT_CREATE,			"Ошибка создания программы",																		// titulek okna hlбљenн chyby vytvoшenн programu
IDN_SELECT_CREATE1,			"Невозможно создать программу.",																	// 1. шбdek hlбљenн
IDN_JINE_JMENO,				"Попробуйте другое имя.",																			// 2. шбdek hlбљenн (pozor - pouћнvб se i u jinэch chybovэch hlбљenн)
// [3] Dialog potvrzenн ruљenн programu
IDN_SELECT_DEL,				"Удаление программы",																				// titulek okna potvrzenн ruљenн programu
IDN_SELECT_DEL1,			"Действительно хотите удалить программу?",															// 1. шбdek hlбљenн
IDN_SELECT_DEL2,			"ПРЕДУПРЕЖДЕНИЕ: восстановление программы будет невозможно!",										// 2. шбdek hlбљenн
// [3] Dialog potvrzenн ruљenн sloћky
IDN_SELECT_DELDIR,			"Удаление папки",																					// titulek okna potvrzenн ruљenн sloћky
IDN_SELECT_DELDIR1,			"Действительно хотите удалить папку?",																// hlбљenн okna
// [3] Dialog hlбљenн chyby ruљenн sloћky
IDN_SELECT_DELDIRERROR,		"Ошибка удаления папки",																			// titulek okna hlбљenн chyby ruљenн sloћky
IDN_SELECT_DELDIRERROR1,	"Папка не может быть удалена, т. к. она не пустая.",												// hlбљenн okna
// [3] Dialog hlбљenн chyby ruљenн programu
IDN_SELECT_DELERROR,		"Ошибка удаления программы",																		// titulek okna hlбљenн chyby ruљenн programu
IDN_SELECT_DELERROR1,		"Программа только для чтения не может быть удалена.",												// hlбљenн okna
// [3] Dialog vytvoшenн novй sloћky
IDN_SELECT_DIR,				"Новая папка",																						// titulek okna vytvoшenн novй sloћky
IDN_SELECT_DIR1,			"Какое будет имя для новой папки?",																	// vэzva v oknм
// [3] Dialog hlбљenн chyby vytvoшenн sloћky
IDN_SELECT_DIRCREATE,		"Ошибка создания папки",																			// titulek okna hlбљenн chyby vytvoшenн sloћky
IDN_SELECT_DIRCREATE1,		"Папка не может быть создана.",																		// 1. шбdek hlбљenн (nбsleduje 2. шбdek "Zkuste jinй jmйno")
// [3] Dialog hlбљenн chyby existujнcн sloћky pшi vytvбшenн novй sloћky
IDN_SELECT_DIREXIST,		"Папка уже существует",																				// titulek okna hlбљenн chyby existujнcн sloћky
IDN_SELECT_DIREXIST1,		"Внимание - такая папка уже существует.",															// 1. шбdek hlбљenн (nбsleduje 2. шбdek "Zkuste jinй jmйno")
// [3] Dialog hlбљenн chyby existujнcнho programu pшi vytvбшenн novйho programu
IDN_SELECT_EXIST,			"Программа уже существует",																			// titulek okna hlбљenн chyby existujнcнho programu
IDN_SELECT_EXIST1,			"Внимание - такая программа уже существует.",														// 1. шбdek hlбљenн (nбsleduje 2. шбdek "Zkuste jinй jmйno")
// [3] Dialog vytvoшenн novйho programu
IDN_SELECT_NEW,				"Новая программа",																					// titulek okna vytvoшenн novйho programu
IDN_SELECT_NEW1,			"Какое будет имя для новой программы?",																// vэzva v oknм
// [3] Dialog vytvoшenн kopie programu
IDN_SELECT_NEWCOPY,			"Копия программы",																					// titulek okna vytvoшenн kopie programu
IDN_SELECT_NEWCOPY1,		"Какое будет имя для копии программы?",																// vэzva v oknм
// [3] Dialog nastavenн vlastnostн sprajtu
IDN_SPRITEDIMEN,			"Свойства спрайта",																					// titulek okna nastavenн vlastnostн sprajtu
IDN_ANIMACE,				"Анимация",																							// nadpis rбmeиku pro nastavenн animacн sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Задержка между фазами:",																			// nadpis pшed zadбnнm prodlevy mezi fбzemi
IDN_MILISEKUND,				"миллисекунд",																						// text "milisekund" za nastavenнm prodlevy mezi fбzemi
IDN_FAZI_NA_KROK,			"Фазы на шаг (0 = немедленно):",																	// nadpis pшed zadбnнm poиtu fбzн na krok
IDN_HLADINA_K_ZOBRAZENI,	"Показываемый уровень:",																			// nadpis pшed zadбnнm hladiny k zobrazenн sprajtu
IDN_POCET_OBRAZKU,			"Количество картинок",																				// nadpis rбmeиku pro nastavenн poиtu obrбzkщ sprajtu
IDN_FAZI_PRO_KLID,			"Неподвижные фазы:",																				// nadpis pшed zadбnнm fбzн pro klidovэ stav sprajtu
IDN_FAZI_PRO_POHYB,			"Подвижные фазы:",																					// nadpis pшed zadбnнm fбzн pro pohyb sprajtu
IDN_SMERU,					"Направления:",																						// nadpis pшed zadбnнm poиtu smмrщ sprajtu
IDN_ROZMER_OBRAZKU,			"Размер картинки",																					// nadpis rбmeиku pro nastavenн rozmмrщ obrбzku sprajtu
IDN_SIRKA_OBRAZKU,			"Ширина картинки:",																					// nadpis pшed zadбnнm љншky obrбzku sprajtu
IDN_VYSKA_OBRAZKU,			"Высота картинки:",																					// nadpis pшed zadбnнm vэљky obrбzku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Тест спрайта",																						// titulek okna testu sprajtu
// [3] Dialog chybovйho hlбљenн chyby uloћenн programu
IDN_WRITEERR,				"Ошибка сохранения",																				// titulek chybovйho hlбљenн chyby uloћenн programu
IDN_WRITEERR1,				"Программа не может быть сохранена.",																// 1. шбdek hlбљenн (nбsleduje prбzdnэ oddмlovacн шбdek)
IDN_WRITEERR2,				"Проверьте, возможно программа запущена или",														// 2. шбdek hlбљenн
IDN_WRITEERR3,				"защищена от записи.",																				// 3. шбdek hlбљenн (nбsleduje prбzdnэ oddмlovacн шбdek)
IDN_WRITEERR4,				"Если нужно, сохраните программу под",																// 4. шбdek hlбљenн
IDN_WRITEERR5,				"другим именем или на другой диск.",																// 5. шбdek hlбљenн
// [3] Dialog dotazu, zda mб bэt zmмnмnэ program uloћen
IDN_FILEMODICAP,			"Программа изменена",																				// titulek okna dotazu, zda mб bэt program uloћen
IDN_FILEMODI,				"Программа изменена.\nСохранить изменения?",														// text okna
// [3] Dialog dotazu, zda mб bэt pouћнvanэ prvek zruљen
IDN_TESTREFER2,				"Элемент используется",																				// titulek okna varovбnн, ћe ruљenб poloћka je v programu pouћнvбna
IDN_TESTREFER,				"Предупреждение - элемент используется программой.\nСтирая элемент вы также сотрете часть программы.",	// text okna
// [3] Dialog dotazu, zda mб bэt zruљen prvek z knihovny
IDN_CLASSDEL2,				"Невосстановимое стирание",																			// titulek okna varovбnн, ћe ruљenэ prvek z knihovny nebude moћnй obnovit
IDN_CLASSDEL,				"Предупреждение - вы стираете элемент библиотеки.\nНевосстановимое стирание элемента.",				// text okna
// [3] Dialog chybovйho hlбљenн o nedostatku pamмti
IDN_MEMERR_NADPIS,			"Не хватает памяти",																				// titulek okna chybovйho hlбљenн pшi nedostatku pamмti (pouћнvб se i pro interpreter)
IDN_MEMERR_TEXT,			"Не хватает памяти для выполнения операции!\n\nОсвободите место на системном диске\nили проверьте установки для виртуальной памяти.\nПрограмма работает нестабильно, закройте ее как можно скорее.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"К сожалению, программа будет закрыта из-за недостатка памяти!",									// text okna hlбљenн pro interpreter
// [3] Dialog hlбљenн poљkozenн licenиnнch dat
IDN_LICERR2,				"Лицензионная информация повреждена",																// titulek okna hlбљenн o poљkozenэch licenиnнch datech
IDN_LICERR,					"Лицензионная информация повреждена. Для восстановления снова запустите инсталятор программы Питер.",	// text okna
// [3] Dialog hlбљenн o konci иasovм omezenй licence
IDN_LICTIMEERR2,			"Период ограниченной лицензии окончился",															// titulek okna hlбљenн o ukonиenн иasovм omezenй doby provozu aplikace Petr
IDN_LICTIMEERR,				"Период ограниченной лицензии программы Питер окончился.",											// text okna
// [3] Dialog hlбљenн o blнћнcнm se konci иasovм omezenй licence
IDN_LICTIME1,				"Период ограниченной лицензии окончился",															// titulek okna hlбљenн o blнћнcнm se konci иasovм omezenйho provozu Petra
IDN_LICTIME2,				"Период лицензии Питера ограничен.\nОсталось дней:",												// text okna
// [3] Dialog hlбљenн o chybм systйmovэch prostшedkщ
IDN_RESOURCE_ERR1,			"Ошибка системы",																					// titulek okna hlбљenн o nedostatku prostшedkщ
IDN_RESOURCE_ERR2,			"Не хватает системных ресурсов для запуска программы PETER.EXE.",									// text okna
// [3] Dialog hlбљenн o chybм poљkozenн programu
IDN_DAMAGE_ERR1,			"Программа повреждена",																				// titulek okna hlбљenн o poљkozenйm programu
IDN_DAMAGE_ERR2,			"Программа PETER.EXE повреждена, старт не возможен.",												// text okna
// [3] Dialog uloћenн do jinйho souboru
IDN_SAVE_AS1,				"Сохранить как другой файл",																		// titulek okna uloћenн do jinйho souboru
IDN_PROGRAMY,				"Программы",																						// nбzev souborщ typu "program" v oknм uloћenн
IDN_VSECHNY_SOUBORY,		"Все файлы",																						// nбzev souborщ typu "vљechny soubory" v oknм uloћenн (pouћнvб se i pro interpreter v dialozнch vэbмru souborщ)
IDN_SAVE_DISTR1,			"Сохранить дистрибутивную версию программы",														// nadpis okna uloћenн distribuиnн verze programu
IDN_SAVE_DISTR2,			"Программа уже существует",																			// titulek dialogu potvrzenн pшepisu distribuиnн verze
IDN_SAVE_DISTR3,			"Предупреждение - сохраняемый файл  уже существует.\n\nВы сохраняете дистрибутивную нередактируемую версию\nпрограммы и вся исходная информация будет потеряна.\n\nХотите продолжить и перезаписать файл?",	// text dialogu potvrzenн pшepisu distribuиnн verze
// [3] Dialog interpreteru hlбљenн nespustitelnйho programu
IDN_NESPUSTITELNY,			"Неисполняемая программа",																			// titulek okna hlбљenн nespustitelnйho programu
IDN_NESPUSTITELNY2,			"Эта программа была создана программными инструментами Питера\nи теперь сохранена в неисполняемой форме.",	// text okna hlбљenн
// [3] Dialog nastavenн pнsma oken stromщ
IDN_SETUP,					"Установка шрифта",																					// titulek okna nastavenн pнsma oken stromщ
IDN_SETUP_VZOR,				"Пример:",																							// nadpis nad textem vzorku pнsma
IDN_SETUP_VZOR2,			"Это пример текста.",																				// vzorek textu pнsma (text by mмl obsahovat nejrщznмjљн znaky s diakritikou)
IDN_SETUP_STD,				"Стандартный шрифт",																				// volba pro zapnutн standardnнho typu pнsma
IDN_SETUP_BOLD,				"Полужирный",																						// volba pro zapnutн tuиnйho pнsma
IDN_SETUP_ITALIC,			"Курсив",																							// volba pro zapnutн љikmйho pнsma
IDN_SETUP_UNDERLINE,		"Подчеркнутый",																						// volba pro zapnutн podtrћenйho pнsma
IDN_SETUP_STRIKEOUT,		"Перечеркнутый",																					// volba pro zapnutн pшeљkrtnutйho pнsma
IDN_SETUP_NORMAL,			"Arial",																							// volba pro zapnutн bмћnйho pнsma bez patiиek (ARIAL)
IDN_SETUP_SERIF,			"Serif",																							// volba pro zapnutн pнsma s patiиkami (SERIF)
IDN_SETUP_COURIER,			"Courier",																							// volba pro zapnutн pнsma s pevnou rozteин (COURIER)
IDN_SETUP_USER,				"Выбрать из списка",																				// volba pro zapnutн pнsma s volbou ze seznamu typщ pнsem
IDN_SETUP_TYP,				"Список шрифтов:",																					// nadpis okna pro volbu typu pнsma
IDN_SETUP_HEIGHT,			"Высота:",																							// nadpis okna pro volbu vэљky pнsma
IDN_SETUP_WIDTH,			"Ширина%:",																							// nadpis okna pro volbu љншky pнsma
IDN_SETUP_RAM1,				"Эффекты",																							// nadpis rбmeиku volby efektщ pнsma (tuиnй, kurzнva, podtrћenй a pшeљkrtnutй)
IDN_SETUP_RAM2,				"Форма",																							// nadpis rбmeиku volby vzhledu pнsma (patiиky, pevnб rozteи, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Папка и имя для экспорта программы",																// nadpis okna k volbм cнle pro export programu
IDN_IMPORT2,				"Имя импортированной программы",																	// nadpis okna k volbм importovanйho programu
IDN_EXPIMP,					"Программы Питера",																					// nбzev souborщ s programy Petra
// [4] Stavebnн prvky programu
IDF_NONE,					"пустое место",																						// prбzdnэ implicitnн pшedmмt
IDF_GROUP,					"группа",																							// skupina prvkщ
IDF_IF,						"условное исполнение команд",																		// zбhlavн podmнnky
IDF_IF_COND,				"если ",																							// test podmнnky (IF)
IDF_IF_YES,					"тогда",																							// vмtev pшi splnмnн podmнnky (THEN)
IDF_IF_NO,					"иначе",																							// vмtev pшi nesplnмnн podmнnky (ELSE)
IDF_WHILE,					"условное повторение команд (цикл)",																// zбhlavн smyиky s podmнnkou
IDF_WHILE_COND,				"пока",																								// test smyиky s podmнnkou (WHILE)
IDF_WHILE_BODY,				"повторять",																						// tмlo smyиky s podmнnkou (DO)
IDF_WHILE_BREAK,			"прервать",																							// pшeruљenн smyиky (BREAK)
IDF_MINUS,					"знак \"-\" минус",																					// zбpornй znamйnko "-" v инsle
IDF_CASE,					"разветвленная управляющая структура",																// zбhlavн konstrukce vмtvenн
IDF_CASE_SUM,				"для величины выражения",																			// vмtvнcн hodnota konstrukce vмtvenн (SWITCH)
IDF_CASE_ON,				"выполнить команды если",																			// jedna vмtev konstrukce vмtvenн (CASE)
IDF_CASE_EQU,				"выражение равно",																					// testovanб hodnota konstrukce vмtvenн (ON)
IDF_CASE_DEF,				"иначе выполнить команды",																			// implicitnн vмtev konstrukce vмtvenн (DEFAULT)
IDF_NUM,					"числовая константа",																				// инselnб konstanta
IDF_0,						"0",																								// инslice 0
IDF_1,						"1",																								// инslice 1
IDF_2,						"2",																								// инslice 2
IDF_3,						"3",																								// инslice 3
IDF_4,						"4",																								// инslice 4
IDF_5,						"5",																								// инslice 5
IDF_6,						"6",																								// инslice 6
IDF_7,						"7",																								// инslice 7
IDF_8,						"8",																								// инslice 8
IDF_9,						"9",																								// инslice 9
IDF_DOT,					".",																								// desetinnб teиka v инsle
IDF_EXP,					"экспонента",																						// exponent v инsle
IDF_EQU,					"равно",																							// podmнnka =
IDF_NEQU,					"не равно",																							// podmнnka <>
IDF_EQGR,					"больше или равно",																					// podmнnka >=
IDF_EQLT,					"меньше или равно",																					// podmнnka <=
IDF_GR,						"больше чем",																						// podmнnka >
IDF_LT,						"меньше чем",																						// podmнnka <
IDF_AND,					"и",																								// logickэ souиin
IDF_OR,						"или",																								// logickэ souиet
IDF_XOR,					"исключающее или",																					// logickэ vэhradnн souиet
IDF_NOT,					"если не",																							// logickб negace
IDF_ADD,					"сумма",																							// souиet инsel
IDF_SUB,					"разность",																							// rozdнl инsel
IDF_MUL,					"умножение",																						// nбsobek инsel
IDF_DIV,					"деление",																							// podнl инsel
IDF_REAL,					"число",																							// инselnб promмnnб
IDF_ICON,					"предмет",																							// pшedmмtovб promмnnб
IDF_SND,					"звук",																								// zvukovб promмnnб
IDF_MUS,					"музыка",																							// hudebnн promмnnб
IDF_FNC,					"функция",																							// funkce
IDF_MAP,					"лист",																								// promмnnб plochy
IDF_SPRITE,					"спрайт",																							// promмnnб sprajtu
IDF_OPER_EXTRA,				"управление программой - расширение",																// skupina prvkщ pro rozљншenй шнzenн programщ
IDF_TEXT,					"текст",																							// textovб promмnnб
IDF_WINDOWS,				"окна",																								// skupina prvkщ pro шнzenн oken
IDF_PAR,					"ввод переменных",																					// vstupnн promмnnй v oknм mнstnнch promмnnэch a funkcн
IDF_OUT,					"вывод переменной",																					// vэstupnн promмnnб v oknм mнstnнch promмnnэch a funkcн
IDF_MAP_EXTRA,				"лист - расширение",																				// skupina prvkщ pro prбci s plochou - rozљншenн
IDF_LIST,					"список",																							// zбhlavн seznamu (LIST)
IDF_OPER,					"управление программой",																			// skupina prvkщ pro шнzenн programu
IDF_KROK,					"шаг",																								// Petшнk popojнt o krok vpшed
IDF_VLEVO,					"влево",																							// Petшнk otoиit doleva
IDF_VPRAVO,					"вправо",																							// Petшнk otoиit doprava
IDF_VZAD,					"назад",																							// Petшнk otoиit vzad
IDF_PETRIK,					"Петер",																							// skupina prvkщ Petшнka
IDF_BOOL,					"флаг",																								// logickб promмnnб
IDF_TEXT_CONST,				"текстовая константа",																				// textovб konstanta
IDF_TRUE,					"да",																								// logickэ pшнznak TRUE
IDF_FALSE,					"нет",																								// logickэ pшнznak FALSE
IDF_PETRA,					"Люси",																								// skupina prvkщ Lucky
IDF_PETRA_KROK,				"шаг",																								// Lucka popojнt o krok vpшed
IDF_PETRA_VLEVO,			"влево",																							// Lucka otoиit doleva
IDF_PETRA_VPRAVO,			"вправо",																							// Lucka otoиit doprava
IDF_PETRA_VZAD,				"назад",																							// Lucka otoиit vzad
IDF_RYCHLE,					"видимый",																							// viditelnost Petшнka
IDF_EXIT,					"конец функции",																					// pшeruљenн funkce
IDF_PETRA_RYCHLE,			"видимый",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"звук и музыка",																					// skupina prvkщ pro zvuk, hudbu a CD
IDF_PREDMET,				"предмет перед Питером",																			// pшedmмt pшed Petшнkem
IDF_SMER,					"направление",																						// smмr otoиenн Petшнka
IDF_POZICEX,				"горизонтальная позиция",																			// horizontбlnн souшadnice Petшнka
IDF_POZICEY,				"вертикальная позиция",																				// vertikбlnн souшadnice Petшнka
IDF_PETRA_PREDMET,			"предмет перед Люси",																				// pшedmмt pшed Luckou
IDF_PETRA_SMER,				"направление",																						// smмt otoиenн Lucky
IDF_PETRA_POZICEX,			"горизонтальная позиция",																			// horizontбlnн souшadnice Lucky
IDF_PETRA_POZICEY,			"вертикальная позиция",																				// vertikбlnн souшadnice Lucky
IDF_CONST,					"калькуляция",																						// skupina prvkщ инselnэch a logickэch operacн
IDF_VYPOC,					"арифметические операции",																			// skupina инselnэch operбtorщ
IDF_FUNC,					"функции",																							// skupina инselnэch funkcн
IDF_POROVNANI,				"сравнение",																						// skupina porovnбvacнch operбtorщ
IDF_LOG_OPER,				"логические операции",																				// skupina logickэch prvkщ
IDF_MOD,					"модуль",																							// инselnэ operбtor modulo
IDF_SIN,					"синус",																							// funkce sinus
IDF_COS,					"косинус",																							// funkce kosinus
IDF_TG,						"тангенс",																							// funkce tangens
IDF_COTG,					"котангенс",																						// funkce kotangens
IDF_ARCSIN,					"арксинус",																							// funkce arcus sinus
IDF_ARCCOS,					"арккосинус",																						// funkce arcus kosinus
IDF_ARCTG,					"арктангенс",																						// funkce arcus tangens
IDF_ARCCOTG,				"арккотангенс",																						// funkce arcus kotangens
IDF_PI,						"Пи",																								// Ludolfovo инslo (pн)
IDF_INTEGER,				"целочисленная часть",																				// funkce odstranмnн desetinnй ибsti инsla
IDF_FRAC,					"дробная часть",																					// funkce odstranмnн celoинselnй ибsti инsla
IDF_ABS,					"абсолютная величина",																				// funkce absolutnн hodnoty
IDF_SQRT,					"квадратный корень",																				// funkce druhб mocnina
IDF_FACT,					"факториал",																						// funkce faktoriбl
IDF_RAND,					"случайное число (0 <= x < 1)",																		// nбhodnй инslo
IDF_EUL,					"Эйлерова константа",																				// Eulerova konstanta (e)
IDF_DEGRAD,					"перевод градусов в радианы",																		// funkce konverze stupтщ na radiбny
IDF_RADDEG,					"перевод радианов в градусы",																		// funkce konverze radiбnщ na stupnм
IDF_LOG,					"десятичный логарифм",																				// funkce dekadickэ logaritmus (zбklad 10)
IDF_LN,						"натуральный логарифм",																				// funkce pшirozenэ logaritmus (zбklad e)
IDF_PEXP,					"натуральная экспонента",																			// funkce pшirozenэ exponent (zбklad e)
IDF_MOCN,					"степень",																							// operбtor mocniny
IDF_UHEL,					"угол, направление",																				// skupina ъhlщ (smмrщ)
IDF_UHEL0,					"вправо (0 пи, 0 градусов)",																		// smмr vpravo
IDF_UHEL45,					"вправо вверх (1/4 пи, 45 градусов)",																// smмr vpravo nahoru
IDF_UHEL90,					"вверх (1/2 пи, 90 градусов)",																		// smмr nahoru
IDF_UHEL135,				"влево вверх (3/4 пи, 135 градусов)",																// smмr vlevo nahoru
IDF_UHEL180,				"влево (1 пи, 180 градусов)",																		// smмr vlevo
IDF_UHEL225,				"влево вниз (1 1/4 пи, 225 градусов)",																// smмr vlevo dolщ
IDF_UHEL270,				"вниз (1 1/2 пи, 270 градусов)",																	// smмr dolщ
IDF_UHEL315,				"вправо вниз (1 3/4 пи, 315 градусов)",																// smмr vpravo dolщ
IDF_COMMAND,				"управление",																						// skupina prvkщ ovlбdбnн (klбvesnice, myљ, joystick, dialogy)
IDF_WAIT,					"ожидание (по умолчанию= 0.05 с)",																	// pшнkaz pro иekбnн
IDF_KLAV,					"клавиатура",																						// skupina ovlбdбnн klбvesnice
IDF_KLAV_TEST,				"клавиша нажата",																					// test stisknutй klбvesy
IDF_KLAV_VKEY,				"ввод с клавиатуры (не ждет нажатия)",																// vstup klбvesy bez иekбnн
IDF_KLAV_CHAR,				"ввод знака (не ждет нажатия)",																		// vstup znaku bez иekбnн
IDF_KLAV_VK,				"клавишы",																							// skupina kуdщ klбves
IDF_KLAV_FX,				"клавишы функций",																					// skupina kуdщ funkиnнch klбves
IDF_KLAV_PISM,				"буквы",																							// skupina kуdщ klбves pнsmen
IDF_KLAV_NUM,				"цифровая клавиатура",																				// skupina kуdщ klбves numerickй klбvesnice
IDF_KLAV_RUZNE,				"знаковые клавишы",																					// skupina kуdщ znakovэch klбves
IDF_KLAV_RID,				"клавишы управления",																				// skupina kуdщ шнdicнch klбves
IDF_TRANSPARENT,			"прозрачность",																						// zprщhlednмnн okna
IDF_F1,						"F1",																								// kуd klбvesy F1
IDF_F2,						"F2",																								// kуd klбvesy F2
IDF_F3,						"F3",																								// kуd klбvesy F3
IDF_F4,						"F4",																								// kуd klбvesy F4
IDF_F5,						"F5",																								// kуd klбvesy F5
IDF_F6,						"F6",																								// kуd klбvesy F6
IDF_F7,						"F7",																								// kуd klбvesy F7
IDF_F8,						"F8",																								// kуd klбvesy F8
IDF_F9,						"F9",																								// kуd klбvesy F9
IDF_F10,					"F10",																								// kуd klбvesy F10
IDF_F11,					"F11",																								// kуd klбvesy F11
IDF_F12,					"F12",																								// kуd klбvesy F12
IDF_A,						"Ф",																								// kуd klбvesy A
IDF_B,						"И",																								// kуd klбvesy B
IDF_C,						"С",																								// kуd klбvesy C
IDF_D,						"В",																								// kуd klбvesy D
IDF_E,						"У",																								// kуd klбvesy E
IDF_F,						"А",																								// kуd klбvesy F
IDF_G,						"П",																								// kуd klбvesy G
IDF_H,						"Р",																								// kуd klбvesy H
IDF_I,						"Ш",																								// kуd klбvesy I
IDF_J,						"О",																								// kуd klбvesy J
IDF_K,						"Л",																								// kуd klбvesy K
IDF_L,						"Д",																								// kуd klбvesy L
IDF_M,						"Ь",																								// kуd klбvesy M
IDF_N,						"Т",																								// kуd klбvesy N
IDF_O,						"Щ",																								// kуd klбvesy O
IDF_P,						"З",																								// kуd klбvesy P
IDF_Q,						"Й",																								// kуd klбvesy Q
IDF_R,						"К",																								// kуd klбvesy R
IDF_S,						"Ы",																								// kуd klбvesy S
IDF_T,						"Е",																								// kуd klбvesy T
IDF_U,						"Г",																								// kуd klбvesy U
IDF_V,						"М",																								// kуd klбvesy V
IDF_W,						"Ц",																								// kуd klбvesy W
IDF_X,						"Ч",																								// kуd klбvesy X
IDF_Y,						"Н",																								// kуd klбvesy Y
IDF_Z,						"Я",																								// kуd klбvesy Z
IDF_VK_NUM0,				"0 Ins",																							// kуd numerickй klбvesy 0 Ins
IDF_VK_NUM1,				"1 End",																							// kуd numerickй klбvesy 1 End
IDF_VK_NUM2,				"2 Down",																							// kуd numerickй klбvesy 2 dolщ
IDF_VK_NUM3,				"3 PgDn",																							// kуd numerickй klбvesy 3 PgDn
IDF_VK_NUM4,				"4 Left",																							// kуd numerickй klбvesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kуd numerickй klбvesy 5
IDF_VK_NUM6,				"6 Right",																							// kуd numerickй klбvesy 6 vpravo
IDF_VK_NUM7,				"7 Home",																							// kуd numerickй klбvesy 7 Home
IDF_VK_NUM8,				"8 Up",																								// kуd numerickй klбvesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp",																							// kуd numerickй klбvesy 9 PgUp
IDF_VK_NUMTECKA,			". Del",																							// kуd numerickй klбvesy . Del
IDF_VK_NUMPLUS,				"+",																								// kуd numerickй klбvesy +
IDF_VK_NUMMINUS,			"-",																								// kуd numerickй klбvesy -
IDF_VK_NUMKRAT,				"*",																								// kуd numerickй klбvesy *
IDF_VK_NUMDELENO,			"/",																								// kуd numerickй klбvesy /
IDF_VK_NUMENTER,			"Enter",																							// kуd numerickй klбvesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kуd numerickй klбvesy Num Lock
IDF_VK_1,					"1 !",																								// kуd klбvesy 1 !
IDF_VK_2,					"2 @ (2 \")",																						// kуd klбvesy 2 @
IDF_VK_3,					"3 №",																								// kуd klбvesy 3 #
IDF_VK_4,					"4 $ (4 ;)",																						// kуd klбvesy 4 $
IDF_VK_5,					"5 %",																								// kуd klбvesy 5 %
IDF_VK_6,					"6 ^ (6 :)",																						// kуd klбvesy 6 ^
IDF_VK_7,					"7 ?",																								// kуd klбvesy 7 &
IDF_VK_8,					"8 *",																								// kуd klбvesy 8 *
IDF_VK_9,					"9 (",																								// kуd klбvesy 9 (
IDF_VK_0,					"0 )",																								// kуd klбvesy 0 )
IDF_VK_LCARKA,				"Ё",																								// kуd klбvesy ` ~
IDF_VK_POMLCKA,				"- _",																								// kуd klбvesy - _
IDF_VK_ROVNITKO,			"= +",																								// kуd klбvesy = +
IDF_VK_ZLOMITKO,			"\\ /",																								// kуd klбvesy \ |
IDF_VK_LLOMENA,				"Х",																								// kуd klбvesy [ {
IDF_VK_RLOMENA,				"Ъ",																								// kуd klбvesy ] }
IDF_VK_STREDNIK,			"Ж",																								// kуd klбvesy ; :
IDF_VK_RCARKA,				"Э",																								// kуd klбvesy ' "
IDF_VK_CARKA,				"Б",																								// kуd klбvesy , <
IDF_VK_TECKA,				"Ю",																								// kуd klбvesy . >
IDF_VK_LOMITKO,				". ,",																								// kуd klбvesy / ?
IDF_VK_ESC,					"Esc",																								// kуd klбvesy Esc
IDF_VK_TAB,					"Tab",																								// kуd klбvesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kуd klбvesy Caps Lock
IDF_VK_WIN,					"меню Windows влево",																				// kуd klбvesy Menu Windows vlevo
IDF_VK_BS,					"Back Space",																						// kуd klбvesy Back Space
IDF_VK_ENTER,				"Enter",																							// kуd klбvesy Enter
IDF_VK_MENU,				"локальное меню",																					// kуd klбvesy Lokбlnн menu
IDF_VK_LEFT,				"влево",																							// kуd klбvesy Vlevo
IDF_VK_RIGHT,				"вправо",																							// kуd klбvesy Vpravo
IDF_VK_UP,					"вверх",																							// kуd klбvesy Nahoru
IDF_VK_DOWN,				"вниз",																								// kуd klбvesy Dolщ
IDF_VK_INSERT,				"Insert",																							// kуd klбvesy Insert
IDF_VK_DELETE,				"Delete",																							// kуd klбvesy Delete
IDF_VK_HOME,				"Home",																								// kуd klбvesy Home
IDF_VK_END,					"End",																								// kуd klбvesy End
IDF_VK_PAGEUP,				"Page Up",																							// kуd klбvesy Page Up
IDF_VK_PAGEDOWN,			"Page Down",																						// kуd klбvesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kуd klбvesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kуd klбvesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kуd klбvesy Pause
IDF_VK_SHIFT,				"Shift левый",																						// kуd klбvesy Levэ Shift
IDF_VK_CTRL,				"Ctrl левый",																						// kуd klбvesy Levэ Ctrl
IDF_VK_ALT,					"Alt левый",																						// kуd klбvesy Levэ Alt
IDF_VK_SPACE,				"пробел",																							// kуd klбvesy Mezera (mezernнk)
IDF_MOUSE,					"мышь",																								// skupina prvkщ myљi
IDF_MOUSE_L,				"левая кнопка мыши нажата",																			// pшнznak drћenйho levйho tlaинtka myљi
IDF_MOUSE_R,				"правая кнопка мыши нажата",																		// pшнznak drћenйho pravйho tlaинtka myљi
IDF_MOUSE_X,				"горизонтальная позиция мыши",																		// horizontбlnн souшadnice myљi
IDF_MOUSE_Y,				"вертикальная позиция мыши",																		// vertikбlnн souшadnice myљi
IDF_EQU_TEXT,				"сравнение текста",																					// operбtor porovnбnн textщ
IDF_EQU_ICO,				"сравнение предметов",																				// operбtor porovnбnн pшedmмtщ
IDF_SPRITE_EXTRA,			"спрайты - расширение",																				// skupina prvkщ pro prбci se sprajty - rozљншenн
IDF_WINDOW_FRAME,			"окно имеет границу",																				// pшнznak zobrazenн okraje okna
IDF_WINDOW_CAPTION,			"окно имеет заголовок",																				// pшнznak zobrazenн titulku okna
IDF_COMMAND_LINE,			"параметры программы",																				// parametry programu z pшнkazovйho шбdku (prvek v mнstnнch promмnnэch hlavnн funkce programu)
IDF_RETURN_CODE,			"код возврата",																						// nбvratovэ kуd programu (prvek v mнstnнch promмnnэch hlavnн funkce programu)
IDF_PIC,					"картинка",																							// promмnnб obrбzku
IDF_REPEAT,					"повторяющаяся команда с подсчетом повторов",														// zбhlavн smyиky se zadanэm poиtem opakovбnн
IDF_REPEAT_N,				"для количества  повторов",																			// zadбnн poиtu opakovбnн smyиky (FOR)
IDF_OKRAJ,					"граница листа",																					// pшedmмt okraje plochy (neplatnэ pшedmмt)
IDF_SPRITE_X,				"горизонтальный",																					// horizontбlnн souшadnice sprajtu
IDF_SPRITE_Y,				"вертикальный",																						// vertikбlnн souшadnice sprajtu
IDF_SPRITE_SMER,			"направление",																						// smмr sprajtu
IDF_SPRITE_MOVE,			"движение",																							// pшнznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"видимый",																							// pшнznak viditelnosti sprajtu
IDF_LIST_SIZE,				"количество",																						// velikost seznamu (poиet prvkщ)
IDF_LIST_INDEX,				"индекс",																							// index seznamu
IDF_LIST_AUTO,				"инкремент индекса",																				// pшнrustek indexu seznamu
IDF_PETER_EXTRA,			"Питер - расширение",																				// skupina rozљiшujнcнch prvkщ Petшнka
IDF_PETRA_EXTRA,			"Люси - расширение",																				// skupina rozљiшujнcнch prvkщ Lucky
IDF_PETER_SWCN1,			"числовая величина 1 (от 0 до 1023)",																// инselnб hodnota 1 na pozici s Petшнkem
IDF_PETRA_SWCN1,			"числовая величина 1 (от 0 до 1023)",																// инselnб hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"числовая величина 2 (от 0 до 1023)",																// инselnб hodnota 2 na pozici s Petшнkem
IDF_PETRA_SWCN2,			"числовая величина 2 (от 0 до 1023)",																// инselnб hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"числовая величина 3 (от 0 до 127)",																// инselnб hodnota 3 na pozici s Petшнkem
IDF_PETRA_SWCN3,			"числовая величина 3 (от 0 до 127)",																// инselnб hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"флаг 1",																							// pшepнnaи 1 na pozici s Petшнkem
IDF_PETRA_SWC1,				"флаг 1",																							// pшepнnaи 1 na pozici s Luckou
IDF_PETER_SWC2,				"флаг 2",																							// pшepнnaи 2 na pozici s Petшнkem
IDF_PETRA_SWC2,				"флаг 2",																							// pшepнnaи 2 na pozici s Luckou
IDF_PETER_SWC3,				"флаг 3",																							// pшepнnaи 3 na pozici s Petшнkem
IDF_PETRA_SWC3,				"флаг 3",																							// pшepнnaи 3 na pozici s Luckou
IDF_PETER_SWC4,				"флаг 4",																							// pшepнnaи 4 na pozici s Petшнkem
IDF_PETRA_SWC4,				"флаг 4",																							// pшepнnaи 4 na pozici s Luckou
IDF_PETER_SWC5,				"флаг 5",																							// pшepнnaи 5 na pozici s Petшнkem
IDF_PETRA_SWC5,				"флаг 5",																							// pшepнnaи 5 na pozici s Luckou
IDF_TEXT_GROUP,				"техты",																							// skupina prvkщ pro prбci s textem
IDF_TEXT_LEFT,				"левая часть текста",																				// funkce levй ибsti textu
IDF_TEXT_LEFT_LEN,			"длина левой части текста",																			// dйlka pro funkci levй ибsti textu
IDF_TEXT_RIGHT,				"правая часть текста",																				// funkce pravй ибsti textu
IDF_TEXT_RIGHT_POS,			"начало правой части текста",																		// poибtek pro funkci pravй ибsti textu
IDF_TEXT_MID,				"средняя часть текста",																				// funkce stшednн ибsti textu
IDF_TEXT_MID_POS,			"начало средней части текста",																		// poибtek pro funkci stшednн ибsti textu
IDF_TEXT_MID_LEN,			"длина средней части текста",																		// dйlka pro funkci stшednн ибsti textu
IDF_TEXT_LEN,				"длина текста",																						// funkce zjiљtмnн dйlky textu
IDF_TEXT_ADD,				"слияние текста",																					// operбtor pro slouиenн textщ
IDF_TEXT_SCAN,				"перевод числа из текстовой формы",																	// funkce pro pшevod инsla z textovйho zбpisu na инslo
IDF_TEXT_FORMAT,			"перевод числа в текстовую форму",																	// funkce pro pшevod инsla do textovйho zбpisu
IDF_TEXT_GT,				"алфавитное сравнение текста",																		// operбtor pro abecednн porovnбnн textщ
IDF_TEXT_LOWER,				"превратить в малые буквы",																			// funkce pro pшevod textu na malб pнsmena
IDF_TEXT_UPPER,				"превратить в большые буквы",																		// funkce pro pшevod textu na velkб pнsmena
IDF_TEXT_FIND,				"поиск позиции текста (-1 = ничего)",																// funkce pro vyhledбnн textovйho шetмzce v jinйm textu
IDF_TEXT_INPUT,				"ввод текста",																						// zadanэ vstupnн text pro textovй funkce
IDF_TEXT_FIND_SUB,			"текст для поиска",																					// zadanэ text k hledбnн pro funkci vyhledбnн textu
IDF_STATUS_LINE,			"информационный текст",																				// stavovэ шбdek hlavnнho okna (textovб promмnnб)
IDF_CAPTION,				"заголовок окна",																					// titulek hlavnнho okna (textovб promмnnб)
IDF_ORD,					"превратить знак в цифровой код",																	// funkce pro konverzi jednoho znaku na инselnэ kуd (poшadн znaku v ASCII tabulce)
IDF_CHAR,					"превратить цифровой код в знак",																	// funkce pro konverzi инselnйho kуdu (poшadн v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"звук",																								// skupina prvkщ pro prбci se zvukem
IDF_SOUND_PLAY,				"играть звук",																						// pшehrбtн zvuku
IDF_SOUND_STOP,				"остановить звук (по умолчанию = все)",																// vypnutн zvuku
IDF_COLOR,					"цвет",																								// barevnб konstanta pro zadбnн barvy
IDF_GRAPH_GROUP,			"графика",																							// skupina prvkщ pro prбci s grafikou a obrбzky
IDF_GRAPH_COLOR,			"цвет пера",																						// zadбnн barvy pera pro grafickй pшнkazy
IDF_GRAPH_WIDTH,			"ширина пера",																						// zadбnн tlouљќky pera pro grafickй pшнkazy
IDF_POINT,					"точка",																							// nakreslenн grafickйho bodu
IDF_POINT_X,				"горизонтальная координата точки X",																// horizontбlnн souшadnice X kreslenйho bodu
IDF_POINT_Y,				"вертикальная координата точки Y",																	// vertikбlnн souшadnice Y kreslenйho bodu
IDF_LINE,					"линия",																							// nakreslenн ибry
IDF_LINE_X1,				"горизонтальная координата линии X1",																// 1. horizontбlnн souшadnice X kreslenй ибry
IDF_LINE_Y1,				"вертикальная координата линии Y1",																	// 1, vertikбlnн souшadnice Y kreslenй ибry
IDF_LINE_X2,				"горизонтальная координата линии X2",																// 2. horizontбlnн souшadnice X kreslenй ибry
IDF_LINE_Y2,				"вертикальная координата линии Y2",																	// 2. vertikбlnн souшadnice Y kreslenй ибry
IDF_BOX,					"прямоугольник",																					// nakreslenн obdйlnнku bez vэplnм
IDF_BOX_X1,					"горизонтальная координата прямоугольника X1",														// 1. horizontбlnн souшadnice X kreslenйho obdйlnнku bez vэplnм
IDF_BOX_Y1,					"вертикальная координата прямоугольника Y1",														// 1. vertikбlnн souшadnice Y kreslenйho obdйlnнku bez vэplnм
IDF_BOX_X2,					"горизонтальная координата прямоугольника X2",														// 2. horizontбlnн souшadnice X kreslenйho obdйlnнku bez vэplnм
IDF_BOX_Y2,					"вертикальная координата прямоугольника Y2",														// 2. vertikбlnн souшadnice Y kreslenйho obdйlnнku bez vэplnм
IDF_BOX_FILL,				"заполненый прямоугольник",																			// nakreslenн obdйlnнku s vэplnн
IDF_BOX_FILL_X1,			"горизонтальная координата заполненного прямоугольника X1",											// 1. horizontбlnн souшadnice X kreslenйho obdйlnнku s vэplnн
IDF_BOX_FILL_Y1,			"вертикальная координата заполненного прямоугольника Y1",											// 1. vertikбlnн souшadnice Y kreslenйho obdйlnнku s vэplnн
IDF_BOX_FILL_X2,			"горизонтальная координата заполненного прямоугольника X2",											// 2. horizontбlnн souшadnice X kreslenйho obdйlnнku s vэplnн
IDF_BOX_FILL_Y2,			"вертикальная координата заполненного прямоугольника Y2",											// 2. vertikбlnн souшadnice Y kreslenйho obdйlnнku s vэplnн
IDF_FILL,					"заполнитель",																						// vэplт plochy (vylitн barvou)
IDF_FILL_X,					"горизонтальная координата заполнителя X",															// horizontбlnн souшadnice X k vyplnмnн plochy
IDF_FILL_Y,					"вертикальная координата заполнителя Y",															// vertikбlnн souшadnice Y k vyplnмnн plochy
IDF_CIRCLE,					"окружность",																						// nakreslenн kruћnice bez vэplnм
IDF_CIRCLE_X,				"горизонтальная координата центра X",																// horizontбlnн souшadnice X stшedu kreslenй kruћnice bez vэplnм
IDF_CIRCLE_Y,				"вертикальная координата центра Y",																	// vertikбlnн souшadnice Y stшedu kreslenй kruћnice bez vэplnм
IDF_CIRCLE_R,				"радиус",																							// polomмr kreslenй kruћnice bez vэplnм
IDF_CIRCLE_FILL,			"круг",																								// nakreslenн kruhu s vэplnн
IDF_CIRCLE_FILL_X,			"горизонтальная координата центра X",																// horizontбlnн souшadnice X stшedu kreslenйho kruhu s vэplnн
IDF_CIRCLE_FILL_Y,			"вертикальная координата центра Y",																	// vertikбlnн souшadnice Y kreslenйho kruhu s vэplnн
IDF_CIRCLE_FILL_R,			"радиус",																							// polomмr kreslenйho kruhu s vэplnн
IDF_TRIANGLE,				"треугольник",																						// nakreslenн trojъhelnнku (s vэplnн)
IDF_TRIANGLE_X1,			"горизонтальная координата треугольника X1",														// 1. horizontбlnн souшadnice X kreslenйho trojъhelnнku
IDF_TRIANGLE_Y1,			"вертикальная координата треугольника Y1",															// 1. vertikбlnн souшadnice Y kreslenйho trojъhelnнku
IDF_TRIANGLE_X2,			"горизонтальная координата треугольника X2",														// 2. horizontбlnн souшadnice X kreslenйho trojъhelnнku
IDF_TRIANGLE_Y2,			"вертикальная координата треугольника Y2",															// 2. vertikбlnн souшadnice Y kreslenйho trojъhelnнku
IDF_TRIANGLE_X3,			"горизонтальная координата треугольника X3",														// 3. horizontбlnн souшadnice X kreslenйho trojъhelnнku
IDF_TRIANGLE_Y3,			"вертикальная координата треугольника Y3",															// 3. vertikбlnн souшadnice Y kreslenйho trojъhelnнku
IDF_SPHERE,					"сфера",																							// nakreslenн koule
IDF_SPHERE_X,				"горизонтальная координата центра X",																// horizontбlnн souшadnice X stшedu kreslenй koule
IDF_SPHERE_Y,				"вертикальная координата центра Y",																	// vertikбlnн souшadnice Y stшedu kreslenй koule
IDF_SPHERE_R,				"радиус",																							// polomмr stшedu kreslenй koule
IDF_COLOR_LEVEL,			"изменить яркость цвета",																			// funkce pro zmмnu jasu barvy
IDF_COLOR_LEVEL_N,			"яркость цвета (от 0 до 1)",																		// poћadovanэ jas barvy pro funkci zmмny jasu barvy
IDF_KLAV_VKEY_WAIT,			"ввод клавиши (ждет нажатия)",																		// funkce pro vstup klбvesy s иekбnнm na stisk
IDF_KLAV_CHAR_WAIT,			"ввод знака (ждет нажатия)",																		// funkce pro vstup znaku s иekбnнm na stisk
IDF_VK_NOKEY,				"клавиша не нажата",																				// kуd klбvesy, nenн-li ћбdnб klбvesa stisknuta
IDF_VK_WINR,				"меню Windows правое",																				// kуd klбvesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Shift правый",																						// kуd klбvesy Pravэ Shift
IDF_VK_CTRLR,				"Ctrl правый",																						// kуd klбvesy Pravэ Ctrl
IDF_VK_ALTR,				"Alt правый",																						// kуd klбvesy Pravэ Alt
IDF_STATUS_NUMLOCK,			"статус Num Lock",																					// prvek stavu indikбtoru Num Lock
IDF_STATUS_CAPSLOCK,		"статус Caps Lock",																					// prvek stavu indikбtoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"статус Scroll Lock",																				// prvek stavu indikбtoru Scroll Lock
IDF_STATUS_INSERT,			"статус Insert",																					// prvek stavu indikбtoru Insert
IDF_MOUSE_LCLICK,			"клик левой кнопкой мыши",																			// pшнznak kliknutн levэm tlaинtkem myљi
IDF_MOUSE_RCLICK,			"клик правой кнопкой мыши",																			// pшнznak kliknutн pravэm tlaинtkem myљi
IDF_MOUSE_LDCLICK,			"двойной клик левой кнопкой мыши",																	// pшнznak dvojkliknutн levэm tlaинtkem myљi
IDF_MOUSE_RDCLICK,			"двойной клик правой кнопкой мыши",																	// pшнznak dvojkliknutн pravэm tlaинtkem myљi
IDF_MOUSE_REGION,			"тест мыши в регионе",																				// funkce pro test souшadnic myљi v zadanй oblasti
IDF_MOUSE_REGION_X,			"горизонтальная координата начала региона X",														// horizontбlnн souшadnice X poибtku testovanй oblasti funkce pro test myљi v oblasti
IDF_MOUSE_REGION_Y,			"вертикальная координата начала региона Y",															// vertikбlnн souшadnice Y poибtku testovanй oblasti funkce pro test myљi v oblasti
IDF_MOUSE_REGION_W,			"ширина региона",																					// љншka testovanй oblasti funkce pro test myљi v oblasti
IDF_MOUSE_REGION_H,			"высота региона",																					// vэљka testovanй oblasti funkce pro test myљi v oblasti
IDF_GRAPH_TEXT,				"изображение текста",																				// vэpis textu v grafickйm reћimu
IDF_GRAPH_TEXT_X,			"горизонтальная координата текста X",																// horizontбlnн souшadnice X k vэpisu grafickйho textu
IDF_GRAPH_TEXT_Y,			"вертикальная координата текста Y",																	// vertikбlnн souшadnice Y k vэpisu grafickйho textu
IDF_GRAPH_TEXT_ANGLE,		"угол ориентации текста",																			// ъhel orientace vypisovanйho grafickйho textu (smмr textu)
IDF_GRAPH_TEXT_H,			"высота знаков",																					// vэљka znakщ vypisovanйho grafickйho textu
IDF_GRAPH_TEXT_W,			"относительная ширина знаков (1 = обычно)",															// relativnн љншka znakщ vypisovanйho grafickйho textu
IDF_GRAPH_TEXT_BOLD,		"полужирный",																						// pшнznak tuиnйho textu pro vypisovanэ grafickэ text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"курсив",																							// pшнznak љikmйho textu pro vypisovanэ grafickэ text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"подчеркнутый",																						// pшнznak podtrћenн pro vypisovanэ grafickэ text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"перечеркнутый",																					// pшнznak pшeљkrtnutн pro vypisovanэ grafickэ text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"serif",																							// pшнznak patiиek vypisovanйho grafickйho textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"courier",																							// pшнznak pevnэch rozteин znakщ vypisovanйho grafickйho textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"текст для отображения",																			// zadanэ text k vэpisu vypisovanйho grafickйho textu
IDF_TEXTLINE_NUM,			"количество строк",																					// funkce pro zjiљtмnн poиtu шбdkщ textu
IDF_TEXTLINE_GET,			"строка",																							// funkce pro zнskбnн jednoho шбdku vнceшбdkovйho textu
IDF_TEXTLINE_INDEX,			"номер строки",																						// инslo шбdku pro funkci zнskбnн jednoho шбdku textu z vнceшбdkovйho textu
IDF_SOUND_TEST,				"тест звука (по умолчанию = все звуки)",															// funkce pro test pшehrбvбnн zvuku
IDF_SOUND_PLAY_LOOP,		"число повторов (0 = непрерывно)",																	// zadanэ poиet opakovбnн pшehrбvбnн zvuku (je to parametr pшнkazu pro pшehrбvбnн zvuku)
IDF_PREDMET_POZ,			"предмет на позиции Питера",																		// pшedmмt na pozici s Petшнkem
IDF_PETRA_PREDMET_POZ,		"предмет на позиции Люси",																			// pшedmмt na pozici s Luckou
IDF_PIC_DISP,				"рисовать картинку",																				// pшнkaz pro vykreslenн obrбzku
IDF_PIC_BACK,				"картинка для рисования",																			// obrбzek k vykreslenн pro pшнkaz vykreslenн obrбzku
IDF_PIC_X,					"горизонтальная координата картинки X",																// horizontбlnн souшadnice X k vykreslenн obrбzku
IDF_PIC_Y,					"вертикальная координата картинки Y",																// vertikбlnн souшadnice Y k vykreslenн obrбzku
IDF_PIC_BLOCK_X,			"горизонтальная координата выреза X",																// horizontбlnн souшadnice X vэшezu v obrбzku k vykreslenн
IDF_PIC_BLOCK_Y,			"вертикальная координата выреза Y",																	// vertikбlnн souшadnice Y vэшezu v obrбzku k vykreslenн
IDF_PIC_BLOCK_W,			"ширина выреза",																					// љншka vэшezu v obrбzku k vykreslenн
IDF_PIC_BLOCK_H,			"высота выреза",																					// vэљka vэшezu v obrбzku k vykreslenн
IDF_PIC_GET,				"сохранить вырез с листа как картинку",																// funkce pro zнskбnн vэшezu z okna jako obrбzek
IDF_ICON_GET,				"сохранить вырез с листа как предмет",																// funkce pro zнskбnн vэшezu z okna jako pшedmмt
IDF_LANGUAGE,				"язык (0=авто, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivnн jazyk
IDF_SOUND_PLAY_SOUND,		"звук для проигрывания",																			// zvuk k pшehrбtн (je to parametr pшнkazu pro pшehrбvбnн zvuku)
IDF_SOUND_PLAY_VOL,			"громкость звука (от 0 до 1)",																		// hlasitost pшehrбvanйho zvuku (je to parametr pшнkazu pro pшehrбvбnн zvuku)
IDF_SOUND_PLAY_BAL,			"балланс (от -1 = левый до +1 = правый)",															// stereofonnн pшehrбvбnн zvuku (je to parametr pшнkazu pro pшehrбvбnн zvuku)
IDF_SOUND_PLAY_STOP,		"прекратить играть звук",																			// pшнznak pшeruљenн starйho zvuku, je-li jiћ pшehrбvбn (je to parametr pшнkazu pro pшehrбvбnн zvuku)
IDF_COMMENT,				"комментарий",																						// komentбш
IDF_SOUND_FUNCTIONS,		"звуковые функции",																					// skupina zvukovэch funkcн
IDF_MOUSE_CURSOR,			"установка формы курсора мыши",																		// pшнkaz pro nastavenн vzhledu kurzoru myљi
IDF_MOUSE_CURSOR_PIC,		"картинка курсора мыши (по умолчанию = оригинальная)",												// obrбzek myљi pro pшнkaz nastavenн vzhledu kurzoru myљi
IDF_MOUSE_CURSOR_X,			"горизонтальная координата начала региона X",														// horizontбlnн souшadnice X oblasti pro pшнkaz nastavenн vzhledu kurzoru myљi
IDF_MOUSE_CURSOR_Y,			"вертикальная координата начала региона Y",															// vertikбlnн souшadnice Y oblasti pro pшнkaz nastavenн vzhledu kurzoru myљi
IDF_MOUSE_CURSOR_W,			"ширина региона",																					// љншka oblasti pro pшнkaz nastavenн vzhledu kurzoru myљi
IDF_MOUSE_CURSOR_H,			"высота региона",																					// vэљka oblasti pro pшнkaz nastavenн vzhledu kurzoru myљi
IDF_MUSIC_PLAY,				"играть музыку",																					// pшнkaz pro pшehrбtн hudby (PLAY)
IDF_MUSIC_LOOP,				"играть музыку повторно",																			// pшнkaz pro opakovanй pшehrбvбnн hudby (LOOP)
IDF_MUSIC_STOP,				"прекратить играть музыку",																			// pшнkaz pro zastavenн pшehrбvбnн hudby (STOP)
IDF_MUSIC_PAUSE,			"пауза/продолжать играть музыку",																	// pшнkaz pro pozastavenн/pokraиovбnн v pшehrбvбnн hudby (PAUSE)
IDF_MUSIC_TEST,				"тест проигрывания музыки",																			// test pшehrбvбnн hudby
IDF_MUSIC_POS,				"позиция в проигрываемой музыке",																	// pozice v pшehrбvбnн hudby
IDF_MUSIC_LEN,				"длина проигрываемой музыки",																		// dйlka pшehrбvanй hudby
IDF_COLOR_SYNTH,			"сложить цветовые компоненты в цвет",																// funkce pro slouиenн barevnэch sloћek do barev
IDF_COLOR_SYNTH_RED,		"красная компонента (от 0 до 1)",																	// иervenб sloћka funkce pro slouиenн barevnэch sloћek do barvy
IDF_COLOR_SYNTH_GREEN,		"зеленая компонента (от 0 до 1)",																	// zelenб sloћka funkce pro slouиenн barevnэch sloћek do barvy
IDF_COLOR_SYNTH_BLUE,		"голубая компонента (от 0 до 1)",																	// modrб sloћka funkce pro slouиenн barevnэch sloћek do barvy
IDF_GET_POINT,				"получить цвет пикселя",																			// funkce pro zjiљtмnн barvy bodu z okna
IDF_GET_POINT_X,			"горизонтальная координата пикселя X",																// horizontбlnн souшadnice X funkce pro zjiљtмnн barvy bodu z okna
IDF_GET_POINT_Y,			"горизонтальная координата пикселя Y",																// vertikбlnн souшadnice Y funkce pro zjiљtмnн barvy bodu z okna
IDF_SQR,					"степень корня",																					// funkce druhб mocnina
IDF_MUSIC_GROUP,			"музыка",																							// skupina prvkщ pro prбci s hudbou
IDF_CD_GROUP,				"аудио CD",																							// skupina prvkщ pro prбci se zvukovэm CD
IDF_CD_PLAY,				"играть CD с заданной дорожки (по умолчанию = 1)",													// pшehrбtн CD od zadanй stopy (PLAY)
IDF_CD_STOP,				"прекратить играть CD",																				// zastavenн pшehrбvбnн CD (STOP)
IDF_CD_PAUSE,				"пауза/продолжать играть CD",																		// pozastavenн/pokraиovбnн v pшehrбvбnн CD (PAUSE)
IDF_CD_TEST,				"тест проигрывания CD",																				// test pшehrбvбnн CD
IDF_CD_LENGTH,				"общая длина",																						// celkovб dйlka CD
IDF_CD_TRACKS,				"количество дорожек",																				// poиet stop CD
IDF_CD_POS,					"позиция от начала",																				// pozice pшehrбvбnн od zaибtku CD
IDF_CD_TRACK,				"дорожка для проигрывания",																			// инslo pшehrбvanй stopy CD
IDF_CD_TRACK_LENGTH,		"длина дорожки для проигрывания",																	// dйlka pшehrбvanй stopy CD
IDF_CD_TRACK_POS,			"позиция от начала дорожки",																		// pozice pшehrбvбnн od zaибtku stopy CD
IDF_FILE_GROUP,				"файлы",																							// skupina prvkщ pro prбci se soubory
IDF_FILE_FILEGROUP,			"основные операции",																				// skupina prvkщ pro zбkladnн operace se soubory
IDF_FILE_FILENEW,			"новый файл",																						// vytvoшenн novйho souboru
IDF_FILE_DIRNEW,			"новая папка",																						// vytvoшenн novйho adresбшe
IDF_FILE_DELETE,			"стереть файл или папку",																			// zruљenн souboru nebo adresбшe
IDF_FILE_TEST,				"тест существования",																				// test existence souboru nebo adresбшe
IDF_FILE_ACT,				"активный диск или папка",																			// nastavenн aktivnнho disku a adresбшe
IDF_FILE_DISKSIZE,			"размер диска",																						// zjiљtмnн celkovй kapacity disku
IDF_FILE_DISKFREE,			"свободное место на диске",																			// zjiљtмnн volnйho mнsta na disku
IDF_FILE_DISKLABEL,			"метка диска",																						// zjiљtмnн/nastavenн jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"серийный номер диска",																				// zjiљtмnн sйriovйho инsla disku
IDF_FILE_READ,				"активный файл/папка для чтения",																	// aktivnн soubor pro иtenн dat ze souboru
IDF_FILE_WRITE,				"активный файл/папка для записи",																	// aktivnн soubor pro zбpis dat do souboru
IDF_FILE_COPY,				"копия файла",																						// provedenн kopie souboru
IDF_FILE_MOVE,				"перемещение/переименование файла/папки",															// provedenн pшesunu/pшejmenovбnн souboru nebo adresбшe
IDF_FILE_DISKGROUP,			"диск",																								// skupina prvkщ pro prбci s diskem
IDF_FILE_ATTRIB,			"аттрибуты",																						// skupina prvkщ pro prбci s parametry souborщ a adresбшщ
IDF_FILE_RO,				"аттрибут R/O (только для чтения)",																	// atribut R/O souboru nebo adresбшe
IDF_FILE_HID,				"аттрибут HID (скрытый)",																			// atribut HID souboru nebo adresбшe
IDF_FILE_SYS,				"аттрибут SYS (системный)",																			// atribut SYS souboru nebo adresбшe
IDF_FILE_DIR,				"аттрибут DIR (папка)",																				// atribut DIR souboru nebo adresбшe
IDF_FILE_ARC,				"аттрибут ARC (архивный)",																			// atribut ARC souboru nebo adresбшe
IDF_FILE_TMP,				"аттрибут TEMP (временный)",																		// atribut TEMP souboru nebo adresбшe
IDF_FILE_CMP,				"аттрибут COMP (сжатый)",																			// atribut COMP souboru nebo adresбшe
IDF_FILE_OFF,				"аттрибут OFF (недоступный)",																		// atribut OFF souboru nebo adresбшe
IDF_FILE_CREATE,			"дата и время создания",																			// datum a иas vytvoшenн souboru nebo adresбшe
IDF_FILE_OPEN,				"дата и время открытия",																			// datum a иas poslednнho pшнstupu k souboru nebo adresбшi (иtenн)
IDF_FILE_MODI,				"дата и время изменения",																			// datum a иas poslednн modifikace souboru nebo adresбшe (zбpis)
IDF_FILE_DATA,				"данные",																							// skupina dat souborщ
IDF_FILE_BYTES,				"целое число со знаком, 1 байт",																	// celй инslo se znamйnkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"целое число без знака, 1 байт",																	// celй инslo bez znamйnka 1 bajt (data souboru)
IDF_FILE_WORDS,				"целое число со знаком, 2 байта",																	// celй инslo se znamйnkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"целое число без знака, 2 байта",																	// celй инslo bez znamйnka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"целое число со знаком, 4 байта",																	// celй инslo se znamйnkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"целое число без знака, 4 байта",																	// celй инslo bez znamйnka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"десятичное число, 4 байта",																		// desetinnй инslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"десятичное число, 8 байтов",																		// desetinnй инslo 8 bajtщ (data souboru)
IDF_FILE_TEXT0,				"текст закончен бинарным нулем (ASCIIZ)",															// text zakonиenэ binбrnн nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"текст закончен концом строки",																		// text zakonиenэ koncem шбdku (data souboru)
IDF_FILE_TEXTN,				"текст фиксированной длины",																		// text s pevnou dйlkou (data souboru)
IDF_FILE_ICON,				"предмет (ICO)",																					// pшedmмt ICO (data souboru)
IDF_FILE_PICTURE,			"картинка (BMP, JPG)",																				// obrбzek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"звук (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"музыка (MID, RMI)",																				// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"указатель чтения",																					// ukazatel иtenн ze vstupnнho souboru
IDF_FILE_WRITEOFF,			"указатель записи",																					// ukazatel zбpisu do vэstupnнho souboru
IDF_DATETIME_GROUP,			"дата и время",																						// skupina prvkщ pro prбci s datem a иasem
IDF_DATETIME_CURRENT,		"настоящая дата и время (число секунд с 1.1.1601)",													// aktuбlnн datum a иas
IDF_DATETIME_UTC,			"превратить местное время в мировое время",															// funkce pro konverzi mнstnнho иasu na svмtovэ UTC
IDF_DATETIME_LOCAL,			"превратить мировое время в  местное время",														// funkce pro konverzi svмtovйho иasu UTC na mнstnн
IDF_DATETIME_COMP,			"слияние компонентов даты и времени",																// funkce pro slouиenн poloћek data a иasu
IDF_DATETIME_COMP_YEAR,		"год",																								// rok pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_COMP_MONTH,	"месяц",																							// mмsнc pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_COMP_DAY,		"день",																								// den pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_COMP_HOUR,		"час",																								// hodina pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_COMP_MINUTE,	"минута",																							// minuta pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_COMP_SECONDE,	"секунда",																							// sekunda pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_COMP_MSECONDE,	"милисекунда",																						// milisekunda pro funkci slouиenн poloћek data a иasu
IDF_DATETIME_GET_YEAR,		"год с даты и времени",																				// zнskбnн poloћky roku z data a иasu
IDF_DATETIME_GET_MONTH,		"месяц с даты и времени",																			// zнskбnн poloћky mмsнce z data a иasu
IDF_DATETIME_GET_DAY,		"день с даты и времени",																			// zнskбnн poloћky dne z data a иasu
IDF_DATETIME_GET_WEEK,		"день недели с даты и времени (0 = воскресенье, 1 = понедельник, ...)",								// zнskбnн poloћky dne v tэdnu z data a иasu
IDF_DATETIME_GET_HOUR,		"час с даты и времени",																				// zнskбnн poloћky hodiny z data a иasu
IDF_DATETIME_GET_MINUTE,	"минута с даты и времени",																			// zнskбnн poloћky minuty z data a иasu
IDF_DATETIME_GET_SECONDE,	"секунда с даты и времени",																			// zнskбnн poloћky sekundy z data a иasu
IDF_DATETIME_GET_MSECONDE,	"милисекунда с даты и времени",																		// zнskбnн poloћky milisekundy z data a иasu
IDF_DATETIME_DATEEUR,		"перевод даты в текст \"день.месяц.год\"",															// funkce pro konverzi data na text v evropskйm formбtu
IDF_DATETIME_DATEUSA,		"перевод даты в текст \"месяц/день/год\"",															// funkce pro konverzi data na text v americkйm formбtu
IDF_DATETIME_DATEJAP,		"перевод даты в текст \"год-месяц-день\"",															// funkce pro konverzi data na text v japonskйm formбtu
IDF_DATETIME_TIME24,		"перевод времени в текст \"час:минута:секунда\" (24 часа)",											// funkce pro konverzi иasu na text s formбtem 24 hodin
IDF_DATETIME_TIME12,		"перевод времени в текст \"час:минута:секунда x\" (12 часов)",										// funkce pro konverzi иasu na text s formбtem 12 hodin
IDF_FILE_SIZE,				"размер файла",																						// velikost souboru
IDF_FILE_ERROR,				"флаг ошибки операции",																				// pшнznak chyby souborovй operace
IDF_FILE_TEXTN_LEN,			"длина текста фиксированной длины",																	// nastavenн dйlky textu s pevnou dйlkou (data souboru)
IDF_FILE_DISK_TYPE,			"тип диска (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",														// zjiљtмnн typu disku
IDF_TEXT_FORMAT2,			"перевод числа в текст - 2 цифры",																	// funkce pro pшevod инsla na textovэ tvar vyjбdшenэ 2 инslicemi (0 aћ 99)
IDF_TEXT_FORMATH,			"перевод числа в текст - 8 цифр HEX",																// funkce pro pшevod инsla na textovэ tvar vyjбdшenэ 8 hexadecimбlnнmi инslicemi
IDF_FILE_3BYTES,			"целое число со знаком, 3 байта",																	// celй инslo se znamйnkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"целое число без знака, 3 байта",																	// celй инslo bez znamйnka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"диалоги",																							// skupina prvkщ pro dialogovб okna
IDF_DIALOG_BOX,				"диалог подтверждения (1=OK, 2=Cancel, 3=Abort, 4=Retry, 5=Ignore, 6=Да, 7=Нет)",					// potvrzovacн dialog
IDF_DIALOG_BOX_TEXT,		"текст",																							// text pro zobrazenн v potvrzovacнm dialogu
IDF_DIALOG_BOX_CAPTION,		"надпись",																							// nadpis okna potvrzovacнho dialogu
IDF_DIALOG_BOX_ICON,		"икона (0=ничего, 1=ошибка, 2=вопрос, 3=предупреждение, 4=информация)",								// ikona potvrzovacнho dialogu
IDF_DIALOG_BOX_BUTTON,		"кнопки (0=OK, 1=OK/Cancel, 2=Abort/Retry/Ignore, 3=Yes/No/Cancel, 4=Yes/No, 5=Retry/Cancel)",		// tlaинtka potvrzovacнho dialogu
IDF_DIALOG_BOX_DEFAULT,		"кнопка по умолчанию (от 1 до 3)",																	// implicitnн tlaинtko potvrzovacнho dialogu
IDF_TEXT_CRLF,				"следующая строка",																					// textovб konstanta - dalљн шбdek (CR/LF)
IDF_DIALOG_TEXT,			"ввод текста",																						// dialog pro zadбnн textu
IDF_DIALOG_TEXT1,			"1ая строка сообщения",																				// 1. шбdek vэzvy k zobrazenн v dialogu zadбnн textu
IDF_DIALOG_TEXT2,			"2ая строка сообщения",																				// 2. шбdek vэzvy k zobrazenн v dialogu zadбnн textu
IDF_DIALOG_TEXT3,			"3я строка сообщения",																				// 3. шбdek vэzvy k zobrazenн v dialogu zadбnн textu
IDF_DIALOG_TEXT_PAR,		"текст, подготовленный для ввода",																	// pшednastavenэ text k zadбnн v dialogu zadбnн textu
IDF_CD_EJECT,				"вынуть CD",																						// vysunutн CD (EJECT)
IDF_SOUND_BIT,				"число бит для звука (8 или 16)",																	// funkce zjiљtмnн poиtu bitщ na vzorek zvuku
IDF_SOUND_FREQ,				"частота звука (Hz)",																				// funkce zjiљtмnн vzorkovacнho kmitoиtu zvuku
IDF_SOUND_STEREO,			"звук стерео?",																						// funkce testu, zda je zvuk stereofonnн
IDF_SOUND_LENGTH,			"длина звука (sekund)",																				// funkce zjiљtмnн dйlky zvuku
IDF_SOUND_CONV_8BIT,		"превратить в 8 бит",																				// funkce pro konverzi zvuku na vzorek 8 bitщ
IDF_SOUND_CONV_16BIT,		"превратить в 16 бит",																				// funkce pro konverzi zvuku na vzorek 16 bitщ
IDF_SOUND_CONV_STEREO,		"превратить в стерео",																				// funkce pro konverzi zvuku na stereofonnн
IDF_SOUND_CONV_MONO,		"превратить в моно",																				// funkce pro konverzi zvuku na monofonnн
IDF_SOUND_CONV_11025,		"превратить в 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"превратить в 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"превратить в 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"слияние звуков",																					// operбtor pro slouиenн zvukщ
IDF_SOUND_SPEED,			"изменить скорость звука",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"звук для измениния",																				// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"относительное изменение скорости (1 = без изменения)",												// poћadovanб zmмna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"генератор тона",																					// tуnovэ sinusovэ generбtor k vygenerovбnн zvuku stбlйho tуnu
IDF_TONGEN_F,				"частота тона (Hz)",																				// frekvence tуnu pro tуnovэ generбtor
IDF_TONGEN_T,				"длина тона (секунд)",																				// dйlka tуnu pro tуnovэ generбtor
IDF_MAP_GROUP,				"лист",																								// skupina prvkщ pro prбci s plochou
IDF_MAP_WIDTH,				"ширина листа",																						// zjiљtмnн љншky plochy
IDF_MAP_HEIGHT,				"высота листа",																						// zjiљtмnн vэљky plochy
IDF_MAP_X,					"координата X",																						// souшadnice X pro funkce naиtenн prvku z plochy
IDF_MAP_Y,					"координата Y",																						// souшadnice Y pro funkce naиtenн prvku z plochy
IDF_MAP_INPUT,				"лист",																								// vstupnн plocha pro funkce naиtenн prvku z plochy
IDF_MAP_ICON,				"предмет",																							// funkce pro zjiљtмnн pшedmмtu z plochy
IDF_MAP_NUM1,				"числовая величина 1 (от 0 до 1023)",																// funkce pro zjiљtмnн инselnй hodnoty 1 z plochy
IDF_MAP_NUM2,				"числовая величина 2 (от 0 до 1023)",																// funkce pro zjiљtмnн инselnй hodnoty 2 z plochy
IDF_MAP_NUM3,				"числовая величина 3 (от 0 до 127)",																// funkce pro zjiљtмnн инselnй hodnoty 3 z plochy
IDF_MAP_SWC1,				"флаг 1",																							// funkce pro zjiљtмnн pшepнnaиe 1 z plochy
IDF_MAP_SWC2,				"флаг 2",																							// funkce pro zjiљtмnн pшepнnaиe 2 z plochy
IDF_MAP_SWC3,				"флаг 3",																							// funkce pro zjiљtмnн pшepнnaиe 3 z plochy
IDF_MAP_SWC4,				"флаг 4",																							// funkce pro zjiљtмnн pшepнnaиe 4 z plochy
IDF_MAP_SWC5,				"флаг 5",																							// funkce pro zjiљtмnн pшepнnaиe 5 z plochy
IDF_MAP_COPY,				"копирование вырезки с листа",																		// kopie ибsti plochy do jinй plochy
IDF_MAP_COPY_INPUT,			"лист с вырезом",																					// plocha s vэшezem pro funkci kopнrovбnн vэшezu plochy do jinй plochy
IDF_MAP_COPY_X,				"координата вырезки X",																				// souшadnice X vэшezu pro funkci kopнrovбnн vэшezu plochy do jinй plochy
IDF_MAP_COPY_Y,				"координата вырезки Y",																				// souшadnice Y vэшezu pro funkci kopнrovбnн vэшezu plochy do jinй plochy
IDF_MAP_COPY_W,				"ширина вырезки ",																					// љншka vэшezu pro funkci kopнrovбnн vэшezu plochy do jinй plochy
IDF_MAP_COPY_H,				"высота вырезки ",																					// vэљka vэшezu pro funkci kopнrovбnн vэшezu plochy do jinй plochy
IDF_CONSOLE_GROUP,			"консоль",																							// skupina prvkщ pro prбci s konzolou
IDF_SPRITE_SHIFT_X,			"двигать все спрайты в направлении X",																// hromadnэ posun sprajtщ ve smмru X
IDF_SPRITE_SHIFT_Y,			"двигать все спрайты в направлении Y",																// hromadnэ posun sprajtщ ve smмru Y
IDF_SPRITE_WIN_X1,			"левый край окна спрайтов",																			// levэ okraj okna pro zobrazenн sprajtщ
IDF_SPRITE_WIN_Y1,			"нижний край окна спрайтов",																		// dolnн okraj okna pro zobrazenн sprajtщ
IDF_SPRITE_WIN_X2,			"правый край окна спрайтов",																		// pravэ okraj okna pro zobrazenн sprajtщ
IDF_SPRITE_WIN_Y2,			"верхний край окна спрайтов",																		// hornн okraj okna pro zobrazenн sprajtщ
IDF_CONSOLE_ON,				"режим консоли (нужно использовать для основных функций)",											// zapnutн reћimu konzoly
IDF_CONSOLE_OUT,			"ввод текста в консоль",																			// vэstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"ввод текста из консоли",																			// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"ошибка ввода текста в консоль",																	// chybovэ vэstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"параметр программы (0 = имя программы)",															// funkce pro zjiљtмnн jednoho parametru programu (zadanйho z pшнkazovйho шбdku)
IDF_EXEC_NAME,				"имя программы с полным путем",																		// jmйno tohoto programu s plnou cestou
IDF_EXEC,					"выполнение программы",																				// spuљtмnн zadanйho programu bez иekбnн na dokonиenн
IDF_EXEC_WAIT,				"выполнение программы с ожиданием",																	// spuљtмnн zadanйho programu s иekбnнm na dokonиenн a s nбvratem kуdu
IDF_JOYSTICK_GROUP,			"джойстик",																							// skupina prvkщ pro prбci s joystickem
IDF_JOYSTICK_X,				"координата X джойстика",																			// souшadnice X joysticku
IDF_JOYSTICK_Y,				"координата Y джойстика",																			// souшadnice Y joysticku
IDF_JOYSTICK_Z,				"координата Z джойстика",																			// souшadnice Z joysticku
IDF_JOYSTICK_1,				"кнопка 1 джойстика",																				// tlaинtko 1 joysticku
IDF_JOYSTICK_2,				"кнопка 2 джойстика",																				// tlaинtko 2 joysticku
IDF_JOYSTICK_3,				"кнопка 3 джойстика",																				// tlaинtko 3 joysticku
IDF_JOYSTICK_4,				"кнопка 4 джойстика",																				// tlaинtko 4 joysticku
IDF_WINDOWNEW_GROUP,		"тексты и картинки",																				// skupina dialogovэch prvkщ texty a obrбzky
IDF_WINDOW_ID,				"число элементов (0 = главное окно)",																// инslo aktivnнho prvku dialogovйho okna
IDF_WINDOW_DEL,				"стереть элемент/окно",																				// zruљenн prvku dialogovйho okna
IDF_WINDOW_NEW,				"создать окно",																						// vytvoшenн dialogovйho okna
IDF_WINDOW_X,				"горизонтальная координата",																		// horizontбlnн souшadnice prvku v dialogovйm oknм
IDF_WINDOW_Y,				"вертикальная координата",																			// vertikбlnн souшadnice prvku v dialogovйm oknм
IDF_WINDOW_W,				"ширина",																							// љншka prvku dialogovйho okna
IDF_WINDOW_H,				"высота",																							// vэљka prvku dialogovйho okna
IDF_WINDOW_TEXT,			"текст",																							// text prvku dialogovйho okna
IDF_WINDOW_VISIBLE,			"видимость",																						// viditelnost prvku dialogovйho okna
IDF_WINDOW_DISABLE,			"недоступно",																						// zбkaz prvku dialogovйho okna
IDF_BUTTON_NEW,				"создать кнопку",																					// vytvoшenн tlaинtka v dialogovйm oknм (BUTTON)
IDF_BUTTON_CLICK,			"кнопка нажата или элемент изменен",																// stisk tlaинtka nebo zmмna prvku dialogovйho okna
IDF_BUTTONCHECK_NEW,		"создать флажок (checkbox)",																		// vytvoшenн zaљkrtбvacнho boxu dialogovйho okna (CHECKBOX)
IDF_EDIT_NEW,				"создать строку редактирования",																	// vytvoшenн editaиnнho шбdku dialogovйho okna (EDIT)
IDF_BUTTONRADIO_NEW,		"создать выключатель",																				// vytvoшenн pшepнnaиe dialogovйho okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"функции общие для всех элементов",																	// skupina prvkщ pro шнzenн prvkщ dialogovйho okna
IDF_MEMO_NEW,				"создать поле редактирования",																		// vytvoшenн editaиnнho pole dialogovйho okna (MEMO)
IDF_WINCONTROL_GROUP,		"кнопки",																							// skupina prvkщ pro vytvбшenн tlaинtek dialogovйho okna
IDF_CHECKBOX_ON,			"выключатель вкл/выкл",																				// pшнznak zapnutн pшepнnaиe dialogovйho okna (CHECK)
IDF_FOCUS,					"ввод направления",																					// prvek dialogovйho okna se vstupnнm zamмшenнm (FOCUS)
IDF_DEFBUTTON_NEW,			"создать кнопку по умолчанию",																		// vytvoшenн implicitnнho tlaинtka dialogovйho okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"создать кнопку-иконку",																			// vytvoшenн ikonovйho tlaинtka dialogovйho okna
IDF_GROUPBOX_NEW,			"создать рамку",																					// vytvoшenн rбmeиku v dialogovйm oknм
IDF_LISTBOX_NEW,			"создать список",																					// vytvoшenн bмћnйho seznamu v dialogovйm oknм (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"создать текст",																					// vytvoшenн textu v dialogovйm oknм (STATIC TEXT)
IDF_COMBOBOX_NEW,			"создать выпадающий список",																		// vytvoшenн rozbalovacнho seznamu v dialogovйm oknм (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"создать выпадающий список с редактированием",														// vytvoшenн rozbalovacнho seznamu s editacн v dialogovйm oknм (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"полужирный (BOLD)",																				// zvэraznмnй pнsmo prvku dialogovйho okna (BOLD)
IDF_FONTFIXED,				"COURIER",																							// pнsmo s pevnou rozteин prvku dialogovйho okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"создать ггуппы выключателей - начало",																// vytvoшenн prvnнho pшepнnaиe skupiny pшepнnaищ v dialogovйm oknм (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"списки",																							// skupina prvkщ pro prбci se seznamy v dialogovйm oknм
IDF_LISTBOX_ADD,			"добавить содержание в список",																		// pшidбnн poloћky do seznamu dialogovйho okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"стереть список",																					// vyprбzdnмnн seznamu dialogovйho okna (LISTBOX)
IDF_LISTEDIT_NEW,			"создать список с редактированием",																	// vytvoшenн seznamu s editacн v dialogovйm oknм (COMBOBOX)
IDF_BUTTON3_NEW,			"создание тройственного бокса",																		// vytvoшenн 3-stavovйho boxu v dialogovйm oknм (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"выключатель в неопределенном состоянии",															// pшнznak neurиitйho stavu tlaинtka dialogovйho okna
IDF_WINDOWRO_NEW,			"создание окна без возможности закрытия",															// vytvoшenн dialogovйho okna bez moћnosti uzavшenн
IDF_WINDOW_ICON,			"иконка",																							// ikona prvku dialogovйho okna
IDF_WINICON_NEW,			"создать иконку",																					// vytvoшenн prvku zobrazenн ikony v dialogovйm oknм
IDF_FILE_SPRITE,			"спрайт (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*Пи (= 360 градусов)",																			// 2*pi (2*Ludolfovo инslo)
IDF_BOD32,					"дистанция 1 пиксель (= 1/32)",																		// инselnб konstanta vzdбlenosti 1 grafickйho bodu
IDF_M1,						"-1",																								// инselnб konstanta инsla -1
IDF_SPRITE_FAZE,			"фаза",																								// fбze sprajtu
IDF_SPRITE_STATUS,			"состояние",																						// stav sprajtu (stavovэ indikбtor)
IDF_FULLSCREEN,				"полноэкранный режим",																				// ovlбdбnн celoobrazovkovйho reћimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"очищение буфера клавиш",																			// vyprбzdnмnн zбsobnнku klбves (FLUSH)
IDF_SOUND_POS,				"позиция в проигываемом звуке",																		// pozice v pшehrбvбnн zvuku
IDF_SOUND_PAUSE,			"пауза/продолжение проигрывания звука",																// pozastavit/pokraиovat v pшehrбvбnн zvuku (PAUSE)
IDF_FILE_LIST,				"список файлов",																					// zjiљtмnн seznamu souborщ zadanэch pomocн masky
IDF_EQU_MAP,				"идентичность листов",																				// operбtor porovnбnн ploch
IDF_EQU_PIC,				"идентичность картинок",																			// operбtor porovnбnн obrбzkщ
IDF_EQU_SPR,				"идентичность спрайтов",																			// operбtor porovnбnн sprajtщ
IDF_EQU_SND,				"идентичность звуков",																				// operбtor porovnбnн zvukщ
IDF_EQU_MUS,				"идентичность музыки",																				// operбtor porovnбnн hudeb
IDF_NET_GROUP,				"связь",																							// skupina pro obsluhu komunikacн
IDF_DIRECTPLAY_GROUP,		"сетевая потдержка DirectPlay",																		// skupina pro obsluhu hernн sнtм DirectPlay
IDF_CONNECT_LIST,			"список соединений",																				// seznam moћnэch spojenн DirectPlay
IDF_CONNECT_ACT,			"активное соединение",																				// aktivnн spojenн DirectPlay
IDF_GAME_LIST,				"список игр",																						// seznam bмћнcнch her DirectPlay
IDF_GAME_ACT,				"активная игра",																					// aktivnн hra DirectPlay
IDF_PLAYER_LIST,			"список игроков",																					// seznam zapojenэch hrбищ DirectPlay
IDF_PLAYER_ACT,				"активный игрок",																					// aktivnн hrби DirectPlay
IDF_GAME_N1,				"числовой параметр игры 1 (от -16384 до +16383)",													// инselnэ parametr 1 hry DirectPlay
IDF_GAME_N2,				"числовой параметр игры 2 (от -16384 до +16383)",													// инselnэ parametr 2 hry DirectPlay
IDF_GAME_N3,				"числовой параметр игры 3 (от -16384 до +16383)",													// инselnэ parametr 3 hry DirectPlay
IDF_GAME_N4,				"числовой параметр игры 4 (от -16384 до +16383)",													// инselnэ parametr 4 hry DirectPlay
IDF_GAME_N5,				"числовой параметр игры 5 (от -16384 до +16383)",													// инselnэ parametr 5 hry DirectPlay
IDF_GAME_N6,				"числовой параметр игры 6 (от -16384 до +16383)",													// инselnэ parametr 6 hry DirectPlay
IDF_GAME_N7,				"числовой параметр игры 7 (от -16384 до +16383)",													// инselnэ parametr 7 hry DirectPlay
IDF_GAME_N8,				"числовой параметр игры 8 (от -16384 до +16383)",													// инselnэ parametr 8 hry DirectPlay
IDF_GAME_L1,				"флаг игры 1",																						// pшepнnaи 1 hry DirectPlay
IDF_GAME_L2,				"флаг игры 2",																						// pшepнnaи 2 hry DirectPlay
IDF_GAME_L3,				"флаг игры 3",																						// pшepнnaи 3 hry DirectPlay
IDF_GAME_L4,				"флаг игры 4",																						// pшepнnaи 4 hry DirectPlay
IDF_GAME_L5,				"флаг игры 5",																						// pшepнnaи 5 hry DirectPlay
IDF_GAME_L6,				"флаг игры 6",																						// pшepнnaи 6 hry DirectPlay
IDF_GAME_L7,				"флаг игры 7",																						// pшepнnaи 7 hry DirectPlay
IDF_GAME_L8,				"флаг игры 8",																						// pшepнnaи 8 hry DirectPlay
IDF_GAME_GROUP,				"установки игры",																					// skupina pro nastavenн parametrщ hry
IDF_GAME_HOST,				"хост (управляющий компьютер)",																		// pшнznak, ћe poинtaи je hostitel DirectPlay
IDF_PLAYER_MAX,				"максимум игроков (0 = неограничен)",																// maximбlnн poиet hrбищ DirectPlay
IDF_PLAYER_INX,				"номер активного игрока (-1 = нет)",																// инslo aktivnнho hrбиe DirectPlay
IDF_GAME_DATA_GROUP,		"данные",																							// skupina pro pшenos dat DirectPlay
IDF_GAME_PACKET,			"отправка/получение блока данных (-1 = всем/никому)",												// obsluha pшenosu dat DirectPlay
IDF_GAME_DATAN,				"число",																							// инslo dat DirectPlay
IDF_GAME_DATAT,				"текст",																							// text dat DirectPlay
IDF_GAME_DATAL,				"флаг",																								// pшepнnaи dat DirectPlay
IDF_GAME_IP,				"IP адрес этого компьютера",																		// zjiљtмnн IP adresy poинtaиe
IDF_GAME_DATAB,				"целое число от 0 до 255 (байт)",																	// инslo bajt dat DirectPlay
IDF_INC,					"инкремент (добавление 1)",																			// funkce inkrementace инsla
IDF_DEC,					"декремент (вычитание 1)",																			// funkce dekrementace инsla
IDF_WINTEXT_NEW_CENTER,		"создание центрированного текста",																	// vytvoшenн centrovanйho textu v dialogovйm oknм
IDF_BUTTON_ESC,				"кнопка для Esc (-1 = нет)",																		// prvek dialogovйho okna obsluhujнcн klбvesu Esc
IDF_PICTURE_WIDTH,			"ширина картинки",																					// funkce zjiљtмnн љншky obrбzku
IDF_PICTURE_HEIGHT,			"высота картинки",																					// funkce zjiљtмnн vэљky obrбzku
IDF_PICTURE_XFLIP,			"горизонтальное отражение картинки",																// funkce pro horizontбlnн pшevrбcenн obrбzku (podle osy ve smмru Y)
IDF_PICTURE_YFLIP,			"вертикальное отражение картинки",																	// funkce pro vertikбlnн pшevrбcenн obrбzku (podle osy ve smмru X)
IDF_PICTURE_GROUP,			"картинки",																							// skupina prvkщ pro prбci s obrбzky
IDF_PICTURE_ZOOM,			"изменить размер картинки",																			// funkce pro zmмnu velikosti obrбzku
IDF_PICTURE_ZOOM_PIC,		"картинка",																							// obrбzek pro funkci zmмny velikosti obrбzku
IDF_PICTURE_ZOOM_WIDTH,		"ширина (по умолчанию = пропорционально высоте)",													// љншka pro funkci zmмny velikosti obrбzku
IDF_PICTURE_ZOOM_HEIGHT,	"высота (по умолчанию = пропорционально ширине)",													// vэљka pro funkci zmмny velikosti obrбzku
IDF_PICTURE_ZOOM_INT,		"утончить границы",																					// pшнznak zjemnмnн hran pro funkci zmмny velikosti obrбzku
IDF_PICTURE_ZOOM_DITH,		"дизеринг (фотография)",																			// pшнznak ditheringu pro funkci zmмny velikosti obrбzku
IDF_GRAPHIC_GROUP,			"рисование",																						// skupina prvkщ pro grafiku (kreslenн)
IDF_WINPIC_NEW,				"создать картинку",																					// vytvoшenн prvku obrбzku v dialogovйm oknм
IDF_WINDOW_PIC,				"картинка",																							// obrбzek prvku dialogovйho okna
IDF_RICHEDIT_NEW,			"создать редактор RichEdit",																		// vytvoшenн editaиnнho pole RichEdit v dialogovйm oknм
IDF_FONTHEIGHT,				"высота знака (0 = обычная)",																		// vэљka znakщ textu prvku dialogovйho okna
IDF_FONTITALIC,				"курсив",																							// љikmй pнsmo textu prvku dialogovйho okna (ITALIC)
IDF_FONTUNDER,				"подчеркнутый",																						// podtrћenй pнsmo textu prvku dialogovйho okna (UNDERLINE)
IDF_FONTSTRIKE,				"перечеркнутый",																					// pшeљkrtnutй pнsmo textu prvku dialogovйho okna (OVERSTRIKE)
IDF_FONTSERIF,				"шрифт SERIF ",																						// patiиkovй pнsmo textu prvku dialogovйho okna (SERIF)
IDF_FONTWIDTH,				"относительная ширина знака (0 = обычная, 1 = базисная)",											// relativnн љншka znakщ textu prvku dialogovйho okna
IDF_FONTANGLE,				"угол наклона текста",																				// ъhel sklonu textu prvku dialogovйho okna
IDF_WINTEXT_NEW_RIGHT,		"создание текста выравненого справа",																// vytvoшenн textu zarovnanйho vpravo v dialogovйm oknм
IDF_FONTCOL,				"цвет знака",																						// barva pнsma textu prvku dialogovйho okna
IDF_FONTBACK,				"цвет фона",																						// barva pozadн textu prvku dialogovйho okna (BACKGROUND)
IDF_FONTGROUP,				"шрифт элемента",																					// skupina pro ovlбdбnн pнsma prvku dialogovйho okna
IDF_SOUND_PLAY_SPEED,		"скорость проигрывания (1 = обычная)",																// rychlost pшehrбvбnн zvuku (parametr pшнkazu pro pшehrбvбnн zvuku)
IDF_SOUND_DISTINGUISH,		"активный звук (от 0 до 65535)",																	// rozliљovacн kуd zvuku
IDF_DIALOG_OPEN,			"ввод файла для открытия",																			// dialog zadбnн souboru k otevшenн
IDF_DIALOG_SAVE,			"ввод файла для сохранения",																		// dialog zadбnн souboru k uloћenн
IDF_DIALOG_FIND,			"ввод файла для поиска",																			// dialog zadбnн textu k hledбnн (rezervovбno, v souиasnй verzi nepouћito)
IDF_DIALOG_COLOR,			"ввод цвета",																						// dialog zadбnн barvy (rezervovбno, v souиasnй verzi nepouћito)
IDF_DIALOG_EXT,				"файловая маска",																					// seznam masek souborщ pro dialogy zadбnн souboru k otevшenн a uloћenн
IDF_DIALOG_NAME,			"подготовленное имя файла",																			// pшednastavenй jmйno souboru pro dialogy zadбnн souboru k otevшenн a uloћenн
IDF_DIALOG_FILES,			"название типа файлов",																				// seznam nбzvщ souborщ pro dialogy zadбnн souboru k otevшenн a uloћenн
IDF_PICTURE_LEVEL,			"изменить яркость картинки",																		// funkce zmмny jasu obrбzku
IDF_PICTURE_LEVEL_PIC,		"картинка для изменения яркости",																	// obrбzek pro funkci zmмny jasu obrбzku
IDF_PICTURE_LEVEL_N,		"яркость картинки (1 = обычная)",																	// poћadovanэ jas obrбzku funkce zmмny jasu obrбzku
IDF_PICTURE_ROTATE,			"повернуть картинку",																				// funkce pro rotaci obrбzku
IDF_PICTURE_ROTATE_PIC,		"картинка для поворота",																			// obrбzek pro funkci rotace obrбzku
IDF_PICTURE_ROTATE_ANGLE,	"угол поворота",																					// ъhel otoиenн pro funkci rotace obrбzku
IDF_SOUND_CONV_PCM,			"декомпрессия звука",																				// dekomprese zvuku na formбt PCM
IDF_FILE_TEXT_UNICODE,		"текст в формате UNICODE (2 байта)",																// pшнznak textu ve formбtu UNICODE (data souboru)
IDF_MAP_PICTURE,			"конвертировать лист в картинку",																	// funkce pro konverzi plochy na obrбzek
IDF_ICON_PICTURE,			"конвертировать предмет в картинку",																// funkce pro konverzi pшedmмtu na obrбzek
IDF_BIT_GROUP,				"побитная операция",																				// skupina bitovэch (binбrnнch) operacн
IDF_BIT_AND,				"побитное умножение AND",																			// bitovэ (binбrnн) souиin AND
IDF_BIT_OR,					"побитная сумма OR",																				// bitovэ (binбrnн) souиet OR
IDF_BIT_XOR,				"побитная инверсия XOR",																			// bitovб (binбrnн) inverze XOR
IDF_BIT_NOT,				"побитное дополнение NOT",																			// bitovэ (binбrnн) doplnмk NOT
IDF_BIT_MAX,				"максимальное бинарное число (двойное слово)",														// konstanta - maximбlnн bitovй (binбrnн) инslo, dvojslovo
IDF_BIT_LEFT,				"циклический сдвиг влево",																			// bitovб (binбrnн) rotace vlevo
IDF_BIT_RIGHT,				"циклический сдвиг вправо",																			// bitovб (binбrnн) rotace vpravo
IDF_MOUSE_ITEM,				"тест мыши на элементе",																			// test myљi, zda se nachбzн nad zadanэm prvkem dialogovйho okna
IDF_WINDOW_W_INT,			"внутренняя ширина",																				// vnitшnн љншka prvku dialogovйho okna (klientskб љншka)
IDF_WINDOW_H_INT,			"внутренняя высота",																				// vnitшnн vэљka prvku dialogovйho okna (klientskб vэљka)
IDF_CODEPAGE,				"знаковый набор (1250=восточноевропейский, 1251=русский, 1252=западный)",							// инslo pouћitй znakovй sady fontщ
IDF_USERFONT,				"шрифт пользователя",																				// jmйno uћivatelskйho fontu
IDF_ENUMFONTS,				"список шрифтов",																					// zjiљtмnн seznamu systйmovэch fontщ
IDF_MAP_NEW,				"новый лист",																						// vytvoшenн novй plochy
IDF_MAP_NEW_W,				"ширина листа",																						// љншka novй plochy
IDF_MAP_NEW_H,				"высота листа",																						// vэљka novй plochy
IDF_WINDOW_TOP,				"всегда сверху",																					// pшнznak okna, kterй je vћdy nahoшe
IDF_VZOR2,					"[CD-ROM]",																							// nбzev vzorovйho adresбшe v knihovnм CD-ROM
IDF_ALIAS,					"прозвище (alias)",																					// !!! pшezdнvka (alias) souboru nebo sloћky
IDF_COM_GROUP,				"коммуникационный порт",																			// skupina pro obsluhu komunikaиnнch portщ
IDF_COM_OPEN,				"открыть порт (-1=ошибка)",																			// pшнkaz k otevшenн komunikaиnнho portu
IDF_COM_CLOSE,				"закрыть порт",																						// pшнkaz k zavшenн komunikaиnнho portu
IDF_COM_ID,					"активный порт",																					// aktivnн port
IDF_COM_NUM,				"число (от 0 до 255)",																				// vstup/vэstup инsla
IDF_COM_TEXT,				"знак (текст)",																						// vstup/vэstup znaku
IDF_COM_BAUD,				"скорость передачи",																				// pшenosovб rychlost
IDF_COM_STOP,				"2 стоп-бита",																						// reћim s 2 stopbity
IDF_COM_BITS,				"количество битов (от 5 до 8)",																		// poиet bitщ na znak
IDF_COM_PARIT,				"четность (0=нет, 1=нечет, 2=чет)",																	// zvolenб parita
IDF_COM_IN,					"знак получен",																						// byl pшijatэ znak
IDF_COM_SEND,				"передача разрешена (CTS, RTS)",																	// povoleno vysнlбnн
IDF_COM_RECEIVE,			"прием разрешен (DSR, DTR)",																		// povolen pшнjem
IDF_PICTURE_MASK,			"маска картинки",																					// funkce k maskovбnн obrбzku
IDF_PICTURE_MASK_PIC,		"картинка",																							// obrбzek k maskovбnн obrбzku
IDF_PICTURE_MASK_MASK,		"маска",																							// maska k maskovбnн obrбzku
IDF_GRAPH_AREA_WIDTH,		"ширина поля для показа текста (0 = нет)",															// љншka pole k centrovбnн vypisovanйho textu
IDF_RICHMEMO_NEW,			"создать поле редактирования без свертки",															// vytvoшenн editaиnнho pole dialogovйho okna bez zalamovбnн шбdku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"окно переменного размера",																			// dialogovй okno mб mмnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"окно можно закрыть",																				// povolenн/zбkaz uzavшenн dialogovйho okna
IDF_WINDOW_MAXIM,			"окно максимально",																					// maximalizace okna
IDF_WINDOW_MINIM,			"окно минимально",																					// minimalizace okna
IDF_PROGRESS_NEW,			"создать индикатор прогресса",																		// vytvoшenн dialogovйho prvku indikбtoru prщbмhu (progressbar)
IDF_HTRACKBAR_NEW,			"создать горизонтальную прокрутку",																	// vytvoшenн dialogovйho prvku horizontбlnнho jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"создать вертикальную прокрутку",																	// vytvoшenн dialogovйho prvku vertikбlnнho jezdce (trackbar)
IDF_WINDOW_POS,				"актуальная позиция",																				// aktuбlnн pozice v dialogovйm prvku
IDF_MIX_GROUP,				"миксер",																							// skupina mixбћnнho zaшнzenн
IDF_MIX_DEVICE,				"миксер",																							// volba smмљovacнho zaшнzenн
IDF_MIX_LINE_DST,			"входной сигнал",																					// volba cнlovйho signбlu
IDF_MIX_LINE_SRC,			"выходной сигнал (нет=только входной сигнал)",														// volba zdrojovйho signбlu
IDF_MIX_LINE_TYPE,			"тип сигнала",																						// zjiљtмnн typu signбlu
IDF_MIX_CONTROL,			"элемент управления",																				// volba ovlбdacнho prvku
IDF_MIX_CONTROL_TYPE,		"тип элемента управления",																			// zjiљtмnн typu prvku
IDF_MIX_CONTROL_VAL,		"величина элемента управления (от 0 до 1)",															// nastavenн hodnoty prvku
IDF_MIX_CONTROL_LIST,		"выбор элемента управления",																		// vэbмr hodnoty prvku
IDF_MIX_CHANNEL,			"упраляемый канал (-1=все)",																		// volba ovlбdanйho kanбlu
IDF_DIRECT3D_GROUP,			"3D графика",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"окно 3D графики",																					// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X координата окна 3D графики",																		// definice souшadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y координата окна 3D графики",																		// definice souшadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"ширина окна 3D графики",																			// definice љншky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"высота окна 3D графики",																			// definice vэљky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"видеорежим (ширина*высота/бит)",																	// seznam/vэbмr videomуdщ
IDF_DIALOG_GRAPHIC,			"фон графики",																						// zapnuto grafickй pozadн dialogovэch oken
IDF_DIRECT3D_SETTING_GROUP,	"установки",																						// skupina nastavenн Direct3D
IDF_DIRECT3D_WIREFRAME,		"заполнить поверхности",																			// mуd vyplтovбnн
IDF_DIRECT3D_LIGHTON,		"свет",																								// mуd osvмtlenн
IDF_DIRECT3D_SHADES,		"плавное затенение",																				// mуd stнnovбnн
IDF_DIRECT3D_INVERT,		"инверсия объекта",																					// invertovat objekt (pшevrбtit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"объекты",																							// skupina objektщ Direct3D
IDF_DIRECT3D_WALL,			"стена",																							// vytvoшenн stмny
IDF_DIRECT3D_CUBE,			"куб",																								// vytvoшenн krychle
IDF_DIRECT3D_SPHERE,		"сфера",																							// vytvoшenн koule
IDF_DIRECT3D_CYLINDER,		"циллиндр",																							// vytvoшenн vбlce
IDF_DIRECT3D_CONE,			"конус",																							// vytvoшenн kuћele
IDF_DIRECT3D_CLONE,			"клон",																								// vytvoшenн klonu
IDF_DIRECT3D_TEXT,			"объект из текста",																					// vytvoшenн objektu z textu
IDF_DIRECT3D_FILE,			"объект из файла",																					// vytvoшenн objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"активный объект (0=сцена, 1=камера, 2=свет)",														// aktivnн objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"удалить объект",																					// zruљenн objektu
IDF_DIRECT3D_VISIBLE,		"видимый",																							// zviditelnмnн objektu
IDF_DIRECT3D_LINK,			"ярлык",																							// pшipojenн jinйho objektu
IDF_DIRECT3D_SAVE,			"объект в файл",																					// uloћenн objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"трансформации",																					// transformace objektщ
IDF_DIRECT3D_SCALEX,		"шкала в направлении X",																			// nastavenн mмшнtka ve smмru X
IDF_DIRECT3D_SCALEY,		"шкала в направлении Y",																			// nastavenн mмшнtka ve smмru Y
IDF_DIRECT3D_SCALEZ,		"шкала в направлении Z",																			// nastavenн mмшнtka ve smмru Z
IDF_DIRECT3D_ROTATEX,		"вращение вокруг оси X",																			// nastavenн rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"вращение вокруг оси Y",																			// nastavenн rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"вращение вокруг оси Z",																			// nastavenн rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"сдвиг по оси X",																					// nastavenн posunu ve smмru X
IDF_DIRECT3D_TRANSY,		"сдвиг по оси Y",																					// nastavenн posunu ve smмru Y
IDF_DIRECT3D_TRANSZ,		"сдвиг по оси Z",																					// nastavenн posunu ve smмru Z
IDF_DIRECT3D_MAT_GROUP,		"поверхность",																						// skupina pro nastavenн povrchu
IDF_DIRECT3D_COLOR,			"цвет (-1=внутренний, -2=по умолчанию)",															// nastavenн barvy objektu
IDF_DIRECT3D_EMISSIVE,		"цвет светимости",																					// nastavenн barvy svнtivosti
IDF_DIRECT3D_POWER,			"матовость (0=off, 5=металл, 50=пластик)",															// nastavenн matnosti
IDF_DIRECT3D_SPECULAR,		"цвет отражения",																					// nastavenн barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"текстура",																							// obrбzek textury
IDF_DIRECT3D_TEXTMAP,		"нанесение текстуры",																				// pшнkaz pro mapovбnн textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"тип проекциии (0=плоская, 1=циллиндрическая, 2=сферическая, 3=хром, 4=линзы)",						// typ projekce mapovбnн
IDF_DIRECT3D_TEXTMAP_OX,	"X координата центра проекции",																		// souшadnice X stшedu porjekce mapovбnн
IDF_DIRECT3D_TEXTMAP_OY,	"Y координата центра проекции",																		// souшadnice Y stшedu projekce mapovбnн
IDF_DIRECT3D_TEXTMAP_OZ,	"Z координата центра проекции",																		// souшadnice Z stшedu projekce mapovбnн
IDF_DIRECT3D_TEXTMAP_RX,	"вращение проекции вокруг оси X",																	// otoиenн projekce mapovбnн podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"вращение проекции вокруг оси Y",																	// otoиenн projekce mapovбnн podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"вращение проекции вокруг оси Z",																	// otoиenн projekce mapovбnн podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"прозрачность (1=нормаль, 11=огонь, 20=стекло, 54=перекрытие)",										// nastavenн prщhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"контуры (0=нормаль, 0.5=контуры)",																	// nastavenн referenиnн ъrovnм alfa kanбlu
IDF_DIRECT3D_TEXTMAP_METHOD,"метод (0=адреса, 1=вершины, 2=поверхности)",														// metoda mapovбnн textury
IDF_DIRECT3D_TEXTMAP_OU,	"горизонтальное начало текстуры",																	// poибtek textury vodorovnм
IDF_DIRECT3D_TEXTMAP_OV,	"вертикальное начало текстуры",																		// poибtek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"горизонтальная шкала уменьшения текстуры",															// mмшнtko textury vodorovnм
IDF_DIRECT3D_TEXTMAP_SV,	"вертикальная шкала уменьшения текстуры",															// mмшнtko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"свет",																								// skupina pro ovlбdбnн svмtel
IDF_DIRECT3D_LIGHT,			"создать новый источник света",																		// vytvoшenн svмtla
IDF_DIRECT3D_LIGHT_COLOR,	"цвет источника света",																				// nastavenн barvy svмtla
IDF_DIRECT3D_LIGHT_TYPE,	"тип осветителя (1=точка, 2=пятно, 3=направленный)",												// volba typu svмtla
IDF_DIRECT3D_LIGHT_UMBRA,	"угол светового конуса",																			// nastavenн ъhle kuћele svмtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"угол полутени",																					// nastavenн ъhle polostнnu
IDF_DIRECT3D_LIGHT_RANGE,	"угол света",																						// vzdбlenost dopadu svмtla
IDF_DIRECT3D_LIGHT_CATTEN,	"сила света (1=нормаль)",																			// nastavenн intenzity svмtla
IDF_DIRECT3D_LIGHT_LATTEN,	"линейное ослабление",																				// lineбrnн zeslabenн svмtla
IDF_DIRECT3D_LIGHT_QATTEN,	"квадратичное ослабление",																			// kvadratickй zeslabenн svмtla
IDF_DIRECT3D_PROJECTION,	"тип проекции (0=персп, 1=орто, 2=р-персп, 3=р-орто)",												// nastavenн typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"сцена",																							// skupina pro шнzenн scйny
IDF_DIRECT3D_SCENE_COLOR,	"цвет фона сцены (-1=выкл, -2=не инициализирован)",													// nastavenн barvy pozadн scйny
IDF_DIRECT3D_SCENE_TEXTURE,	"текстура фона сцены",																				// nastavenн textury pozadн scйny
IDF_DIRECT3D_FOG_COLOR,		"цвет тумана (-1=выкл)",																			// nastavenн barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"тип тумана (0=лин, 1=эксп, 2=квадр, +4=коррекция)",												// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"начало линейного тумана",																			// nastavenн zaибtku mlhy
IDF_DIRECT3D_FOG_END,		"конец линейного тумана",																			// nastavenн konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"плотность эксп. и квадр. тумана (от 0 до 1)",														// nastavenн hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"расстояние от плана проекции",																		// nastavenн vzdбlenosti promнtacн roviny
IDF_DIRECT3D_VIEW_BACK,		"дистанция видимости",																				// nastavenн vzdбlenosti dohledu
IDF_DIRECT3D_UPPER,			"создать верхнее основание",																		// vytvбшet hornн podstavu objektu
IDF_DIRECT3D_LOWER,			"создать нижнее основание",																			// vytvбшet dolnн podstavu objektu
IDF_DIRECT3D_PICK,			"найти объект",																						// vyhledбnн objektu
IDF_DIRECT3D_PICK_X,		"X координата точки",																				// souшadnice X k vyhledбnн objektu
IDF_DIRECT3D_PICK_Y,		"Y координата точки",																				// souшadnice Y k vyhledбnн objektu
IDF_DIRECT3D_MINFILTER,		"фильтр уменьшения текстуры",																		// nastavenн filtrace zmenљenэch textur
IDF_DIRECT3D_2DOBJECT,		"2D объект",																						// vytvoшenн 2D objektu
IDF_DIRECT3D_TERRAIN,		"местность с картинки",																				// vytvoшenн terйnu z obrбzku
IDF_DIRECT3D_LEVEL,			"уровень местности",																				// zjiљtмnн ъrovnм terйnu
IDF_DIRECT3D_LEVEL_X,		"горизонтальная координата",																		// horizontбlnн souшadnice pro zjiљtмnн ъrovnм
IDF_DIRECT3D_LEVEL_Y,		"вертикальная координата",																			// vertikбlnн souшadnice pro zjiљtмnн ъrovnм
IDF_DIRECT3D_EMPTY,			"группа",																							// vytvoшenн skupiny objektщ
IDF_DIRECT3D_SPLITS,		"сложность объекта (от 2 до 100)",																	// nastavenн ъrovnм sloћitosti objektu
IDF_DIRECT3D_ORDER,			"порядок вращения (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",										// nastavenн poшadн provбdмnэch rotacн
IDF_DIRECT3D_DRIVER,		"драйвер (0=авто, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaиe
IDF_DIRECT3D_ROTARY,		"вращаемый объект",																					// vytvoшenн rotaиnнho objektu
IDF_DIRECT3D_TERRAIN_MAP,	"местность с листа",																				// vytvoшenн terйnu z plochy
IDF_DIRECT3D_AMBIREF,		"отражение окружающего света (-1=по умолчанию)",													// nastavenн barvy rozptэlenйho svмtla
IDF_ACTIVE,					"программа является активной аппликацией",															// program je aktivnн aplikacн systйmu Windows
IDF_POLAR_RADIUS,			"расстояние до точки",																				// vэpoиet vzdбlenosti bodu
IDF_POLAR_ANGLE,			"угол точки",																						// vэpoиet ъhlu bodu
IDF_POLAR_X,				"X координата точки",																				// souшadnice X bodu
IDF_POLAR_Y,				"Y координата точки",																				// souшadnice Y bodu
IDF_FILE_LOGIC,				"логическая величина",																				// uloћenн logickй hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"сглаживание текстуры (1=нет)",																		// stupeт vyhlazenн ditheringu textur
IDF_PRECISE_TIMER,			"прецезионный счетчик времени",																		// pшesnэ инtaи pro mмшenн иasu
IDF_DIRECT3D_AMBIENT,		"окружающий свет",																					// nastavenн rozptэlenйho svмtla
IDF_DIRECT3D_MAGFILTER,		"фильтр увеличения текстуры",																		// nastavenн filtrace textur
IDF_DIRECT3D_MIPFILTER,		"фильтр дальних текстур",																			// nastavenн filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"заливка поверхностей объекта",																		// mуd vyplтovбnн
IDF_DIRECT3D_OLIGHTON,		"свет объекта",																						// mуd osvмtlenн
IDF_DIRECT3D_OSHADES,		"плавное затенение объекта",																		// mуd stнnovбnн
IDF_DIRECT3D_OMINFILTER,	"фильтр уменьшения текстуры объекта",																// nastavenн filtrace zmenљenэch textur
IDF_DIRECT3D_OMAGFILTER,	"фильтр увеличения текстуры объекта",																// nastavenн filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"фильтр дальней текстуры объекта",																	// nastavenн filtrace textur
IDF_DIRECT3D_OCULLING,		"видимая сторона объекта (0=обе, 1=фронт, 2=тыл)",													// zobrazenй strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"создать",																							// skupina vytvoшenн objektщ
IDF_DIRECT3D_NORM,			"нормализация объекта",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"окружность",																						// vytvoшenн kruhu
IDF_DIRECT3D_TRIANGLE,		"треугольник",																						// vytvoшenн trojъhelnнku
IDF_DIRECT3D_TORUS,			"тор (параметр = диаметр от 0 до 1)",																// vytvoшenн torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"статичный 2D объект",																				// vytvoшenн statickйho 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"полусфера",																						// vytvoшenн polokoule
IDF_DIRECT3D_INTERFACE,		"интерфейс (0=авто, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",								// volba rozhranн 3D
IDF_DIRECT3D_ELAPSED,		"время выполнение",																					// иas ubмhlэ od poslednнho renderovбnн
IDF_DIRECT3D_SPEED,			"скорость рендеринга",																				// rychlost renderovбnн
IDF_DIRECT3D_FREE,			"свободная видеопамять",																			// zjiљtмnн volnй videopamмti
IDF_DIRECT3D_PICTURE,		"2D картинка",																						// vytvoшenн 2D obrбzku
IDF_DIRECT3D_TEXT_GROUP,	"текстуры",																							// skupina textur
IDF_DIRECT3D_STAGE,			"шаги (от 0 до 7)",																					// volba stupnм textur
IDF_DIRECT3D_COLOROP,		"цветовые операции (1=выкл, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",									// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"первый цветовой аргумент (0=цвет, 1=результат, 2=текстура, 3=фактор, 16=инверсия)",				// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"второй цветовой аргумент (0=цвет, 1=результат, 2=текстура, 3=фактор, 16=инверсия)",				// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"альфа операция (1=выкл, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanбlem
IDF_DIRECT3D_ALPHAARG1,		"первый альфа аргумент (0=цвет, 1=результат, 2=текстура, 3=фактор, 16=инверсия)",					// volba argumentu 1 operace s alfa kanбlem
IDF_DIRECT3D_ALPHAARG2,		"второй альфа аргумент (0=цвет, 1=результат, 2=текстура, 3=фактор, 16=инверсия)",					// volba argumentu 2 operace s alfa kanбlem
IDF_DIRECT3D_ADDRESSU,		"режим горизонтальной адресации (1=повтор, 2=зеркало, 3=обрезание)",								// volba horizontбlnнho adresovбnн textur
IDF_DIRECT3D_ADDRESSV,		"режим ввертикальной адресации (1=повтор, 2=зеркало, 3=обрезание)",									// volba vertikбlnнho adresovбnн textur
IDF_DIRECT3D_BIAS,			"блюр дальних текстур (0=по умолчанию)",															// nastavenн stupnм zjemnмnн vzdбlenэch textur
IDF_DIRECT3D_CONE2,			"усеченный конус (параметр = диаметр от 0 до 1)",													// vytvoшenн komolйho kuћele
IDF_DIRECT3D_TFACTOR,		"фактор цвета текстуры",																			// nastavenн barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"альфа компонент (от 0=прозрачность до 1=цвет)",													// alfa sloћka funkce pro slouиenн barevnэch sloћek do barvy
IDF_DIRECT3D_MIPMAPS,		"число дальних текстур (0=все)",																	// nastavenн poиtu ъrovnн vzdбlenэch textur
IDF_DIRECT3D_ZGROUP,		"группа рендеринга (0-7=объекты, 8-11=пленки, 12-15=картинки)",										// nastavenн renderovacн skupiny
IDF_DIRECT3D_ZSORT,			"глубина сортировки групп рендеринга",																// hloubkovй tшнdмnн renderovacн skupiny
IDF_DIRECT3D_ZWRITE,		"записать информацию о глубине",																	// uklбdat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"тест глубины (1 никогда, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 всегда)",								// provбdмnэ hloubkovэ test
IDF_DIRECT3D_NORMALS,		"калькуляция нормалей (параметр = угол сглаживания)",												// pшepoиet normбl
IDF_DIRECT3D_RENDER,		"рендерить без отображения",																		// renderovбnн scйny bez zobrazenн
IDF_TEXT_BLOCK,				"текстовый блок",																					// vyjmutн bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"линия начала блока",																				// шбdek poибtku bloku
IDF_TEXT_BLOCK_BEGPOS,		"позиция начала блока",																				// pozice poибtku bloku
IDF_TEXT_BLOCK_ENDLINE,		"линия конца блока (-1=конец)",																		// шбdek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"позиция конца блока (-1=конец)",																	// pozice konce bloku
IDF_WINDOW_POS2,			"актуальная позиция 2",																				// aktuбlnн pozice 2 v dialogovйm prvku
IDF_BUTTONCHECK_NEW2,		"создать кнопку выключателя",																		// vytvoшenн tlaинtkovйho pшepнnaиe dialogovйho okna
IDF_TABLE_NEW,				"создать таблицу (параметр = список титулов)",														// vytvoшenн tabulky dialogovйho okna
IDF_TABLE_WIDTH,			"ширина столбца",																					// nastavenн љншky sloupce tabulky dialogovйho okna
IDF_SHADOW_RANGE,			"размер тени (0=выкл)",																				// nastavenн vzdбlenosti dopadu stнnu 3D objektu
IDF_TABLE_ALIGN,			"выровнять столбец (0=влево, 1=вправо, 2=по центру)",												// nastavenн zarovnбvбnн sloupce tabulky dialogovйho okna
IDF_HSCROLLBAR_NEW,			"создать горизонтальную прокрутку",																	// vytvoшenн horizontбlnнho posuvnнku
IDF_VSCROLLBAR_NEW,			"создать вертикальную прокрутку",																	// vytvoшenн vertikбlnнho posuvnнku
IDF_PICTURE_XCOL,			"замена цветов",																					// zбmмna barev v obrбzku
IDF_PICTURE_XCOL1,			"первый цвет",																						// prvnн barva k zбmмnм barev v obrбzku
IDF_PICTURE_XCOL2,			"второй цвет",																						// druhб barva k zбmмnм barev v obrбzku
IDF_PICTURE_SCOL,			"переставить цвета",																				// nбhrada barvy v obrбzku
IDF_PICTURE_SCOL1,			"старый цвет",																						// pщvodnн barva k nбhradм barvy v obrбzku
IDF_PICTURE_SCOL2,			"новый цвет",																						// novб barva k nбhradм barvy v obrбzku
IDF_PRINT_PICTURE,			"напечатать картинку",																				// tisk obrбzku na tiskбrnu
IDF_DIRECT3D_LOD_OBJECT,	"объект с уменьшенным уровнем детализации (-1=нет)",												// definice objektu se snнћenou ъrovnн detailщ
IDF_DIRECT3D_LOD_DISTANCE,	"дистанция для уменьшения уровня детализации ",														// vzdбlenost pro snнћenн ъrovnм detailщ
IDF_DIRECT3D_MORPH_MODEL,	"добавить узор для морфинга (-1=перезагрузка)",														// pшidбnн vzoru pro morfovбnн objektu
IDF_DIRECT3D_MORPH_LEVEL,	"шаг морфинга (0...1...2...)",																		// nastavenн stupnм morfovбnн objektu
IDF_DIRECT3D_LENSFLARE,		"линзовый отблеск",																					// vytvoшenн иoиkovйho odlesku
IDF_DDE_GROUP,				"динамическая смена данных DDE",																	// skupina obsluhy DDE (dynamickб vэmмna dat)
IDF_DDE_APP,				"имя сервера/список серверов",																		// jmйno aplikace pro DDE, seznam aplikacн DDE
IDF_DDE_TOPIC,				"имя темата/список темат",																			// jmйno tйmatu pro DDE, seznam tйmat DDE
IDF_DDE_ITEM,				"имя позиции/список позиций",																		// jmйno poloћky pro DDE, seznam poloћek DDE
IDF_DDE_SERVER,				"программа выдаёшь позицию (есть сервер)",															// program poskytuje poloћku ostatnнm programщm
IDF_DDE_TYPE,				"тип позицие (0 до 7, -1=недействительная позиция)",												// typ poloћky pro DDE
IDF_DDE_NUMBER,				"(0) номер",																						// инslo DDE
IDF_DDE_BOOL,				"(1) признак",																						// pшнznak DDE
IDF_DDE_TEXT,				"(2) текст",																						// text DDE
IDF_DDE_ICON,				"(3) предмет",																						// pшedmмt DDE
IDF_DDE_PICTURE,			"(4) картинка",																						// obrбzek DDE
IDF_DDE_SOUND,				"(5) звук",																							// zvuk DDE
IDF_DDE_MUSIC,				"(6) музыка",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) спрайт",																						// sprajt DDE
IDF_DDE_EXECUTE,			"команда к проведению",																				// pшнkaz k provedenн DDE
IDF_DLL_GROUP,				"библиотеки DLL",																					// skupina funkcн pro knihovny DLL
IDF_DLL_LOAD,				"начитать библиотеку",																				// naиtenн knihovny DLL do pamмti
IDF_DLL_FREE,				"уволить библиотеку",																				// uvolnмnн knihovny z pamмti
IDF_DLL_IMPORT,				"импортировать функцию",																			// importovбnн funkce z knihovny
IDF_DLL_IMPORT_LIB,			"идентификатор библиотеки",																			// identifikбtor knihovny pro importovбnн funkce
IDF_DLL_IMPORT_NAME,		"имя функцие",																						// jmйno importovanй funkce
IDF_DLL_IMPORT_PAR,			"количество параметров",																			// poиet parametrщ importovanй funkce
IDF_DLL_EXEC,				"проведение функцие",																				// provedenн funkce z knihovny DLL
IDF_MEMORY_NEW,				"создание запоминающего блоку",																		// vytvoшenн bloku pamмti
IDF_MEMORY_FREE,			"снятие запоминающего блоку",																		// uvolnмnн bloku pamмti
IDF_MEMORY_RESIZE,			"изменение размера запоминающего блоку",															// zmмna velikosti bloku pamмti
IDF_MEMORY_RESIZE_ADR,		"адрес запоминающего блоку",																		// adresa bloku pamмti
IDF_MEMORY_RESIZE_NEW,		"новый размер",																						// novб velikost bloku pamмti
IDF_MEMORY_READ,			"показатель чтения",																				// adresa pro иtenн z pamмti
IDF_MEMORY_WRITE,			"показатель записа",																				// adresa zбpisu do pamмti
IDF_MEMORY_COPY,			"копия дат",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"сравнение дат",																					// porovnбnн bloku dat
IDF_MEMORY_BYTES,			"байт со знаком",																					// иtenн/zбpis bajtu se znamйnkem
IDF_MEMORY_BYTEU,			"байт без знака",																					// иtenн/zбpis bajtu bez znamйnka
IDF_MEMORY_WORDS,			"слово со знаком",																					// иtenн/zбpis slova se znamйnkem
IDF_MEMORY_WORDU,			"слово без знака",																					// иtenн/zбpis slova bez znamйnka
IDF_MEMORY_3BYTES,			"3-байт со знаком",																					// иtenн/zбpis 3-bajtu se znamйnkem
IDF_MEMORY_3BYTEU,			"3-байт без знака",																					// иtenн/zбpis 3-bajtu bez znamйnka
IDF_MEMORY_DWORDS,			"двухслово со знаком",																				// иtenн/zбpis dvouslova se znamйnkem
IDF_MEMORY_DWORDU,			"двухслово без знака",																				// иtenн/zбpis dvouslova bez znamйnka
IDF_MEMORY_FLOAT,			"реально номер 4 байты",																			// иtenн/zбpis reбlnйho инsla 4 bajty
IDF_MEMORY_DOUBLE,			"реально номер 8 байтов",																			// иtenн/zбpis reбlnйho инsla 4 bajty
IDF_MEMORY_BOOL,			"логическое значение",																				// иtenн/zбpis logickй hodnoty
IDF_MEMORY_TEXT0,			"текст закончен нулем",																				// иtenн/zбpis textu zakonиenйho nulou
IDF_MEMORY_TEXT0P,			"показатель на текст закончен нулем",																// иtenн/zбpis ukazatele na text zakonиenэ nulou
IDF_MEMORY_TEXTN,			"текст фиксированной длины",																		// иtenн/zбpis textu s pevnou dйlkou
IDF_MEMORY_TEXTN_LEN,		"длина текста фиксированной длины",																	// definice dйlky textu s pevnou dйlkou
IDF_MEMORY_LOAD,			"чтение дат из файла",																				// иtenн dat ze souboru
IDF_MEMORY_SAVE,			"запись дат до файла",																				// zбpis dat do souboru
IDF_WINDOW_HANDLE,			"идентификатор оконного элемента",																	// zjiљtмnн identifikбtoru okennнho prvku
IDF_DLL_IMPORT_C,			"вызывающия конвенция C",																			// volacн konvence C pro importovanou funkci
IDF_TABS_NEW,				"создать tabs",																						// vytvoшenн zбloћek v dialogovйm oknм
IDF_INI_GROUP,				"configuration",																					// skupina funkcн pro uklбdбnн konfigurace programu
IDF_INI_FILE,				"configuration fike",																				// jmйno konfiguraиnнho souboru
IDF_INI_SECTION,			"parameter section",																				// nбzev sekce konfiguraиnнch parametrщ
IDF_INI_VALUE,				"parameter name",																					// jmйno konfiguraиnнho parametru
IDF_INI_STRING,				"read/write text prameter",																			// иtenн/zбpis hodnoty textovйho konfiguraиnнho parametru
IDF_INI_NUM,				"read/write integer prameter",																		// иtenн/zбpis hodnoty celoинselnйho konfiguraиnнho parametru
IDF_REG_KEY,				"key group (1=CURRENT_USER, 2=LOCAL_MACHINE)",														// urиenн skupiny klнищ registrщ
IDF_REG_SUBKEY,				"key name",																							// plnэ mбzev klниe registrщ
IDF_REG_VALUE,				"entry name",																						// nбzev datovй poloћky
IDF_REG_STRING,				"read/write text entry",																			// иtenн/zбpis textovй poloћky registrщ
IDF_REG_NUM,				"read/write integer entry",																			// иtenн/zбpis celoинselnй poloћky registrщ
IDF_MEMORY_3D,				"create 3D object from memory blocks",																// vytvoшenн 3D objektu z pamмќovэch blokщ
IDF_MEMORY_3D_VN,			"number of vertices",																				// poиet vrcholщ 3D objektu
IDF_MEMORY_3D_VERT,			"vertices",																							// buffer vrcholщ 3D objektu
IDF_MEMORY_3D_NORM,			"normals (0=auto)",																					// buffer normбl 3D objektu
IDF_MEMORY_3D_TEXT,			"texture mapping (0=none)",																			// buffer mapovбnн textur 3D objektu
IDF_MEMORY_3D_COL,			"colors (0=none)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"number of faces",																					// poиet ploљek 3D objektu
IDF_MEMORY_3D_FACE,			"faces",																							// buffer ploљek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"texture from file",																				// naиtenн textury ze souboru
IDF_DIRECT3D_MEMORY,		"memory block from 3D object",																		// export 3D objektu do pamмќovйho bloku
IDF_DIRECT3D_CHILD,			"find child (-1=first, -2=parent)",																	// nalezenн prvnнho/dalљнho potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocн UDP paketщ
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavenн cнlovй IP adresy pro odesнlanй UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavenн cнlovйho portu pro odesнlanй UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavenн velikosti pшijнmacнho UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjiљtмnн IP adresy naposledy pшijatйho UDP paketu, pшijнmacн IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pшнjem UDP paketщ
IDF_UDP_MEM,				"binary packet",																					// pшнjem/odeslбnн binбrnнho UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pшнjem/odeslбnн textovйho UDP paketu
