// Dánsky (Danish)
// 1252
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Globale variabler og funktioner",																	// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Lokale variabler og funktioner",																	// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Basis elementer og affald",																		// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Bibliotek for variabler og funktioner",															// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"Basis variabler og funktioner",																	// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Nyt program",																						// implicitní název nového programu
IDN_NEWDIR_NAME,			"Ny folder",																						// implicitní název nové sloky
IDN_TEXTVZOR,				"[eksempler]",																						// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Brugt",																							// zobrazuje poèet pouití prvku
IDT_RADEK,					"række",																							// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"kolonne",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"tændt",																							// text editoru hodnoty pøepínaèe
IDN_DATUM,					"dato",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"tid",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"størrelse",																						// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"ledig",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"gentag",																							// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"gentaget",																							// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMO",																								// oznaèení DEMO verze
IDN_PROFI,					"Professionel",																						// oznaèení verze Professional
IDN_LITE,					"Let",																								// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Fil",																								// volba k vyvolání menu "Soubor"
IDN_START0,					"S&tart\tF5",																						// volba pro spuštìní programu
IDN_START,					"Starter programmet.\nStart",																		// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Åben\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Åbner programmet, så der kan redigeres.\nÅben",													// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Ny...\tCtrl+N",																					// volba pro zaloení nového programu
IDN_NEW,					"Laver et nyt program.\nNy",																		// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"&Omdøb...\tAlt+Enter",																				// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Omdøber program/folderen (man kan ikke omdøbe eksempel programmer og foldere).\nOmdøb",			// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"&Kopier...\tCtrl+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Kopierer det valgte program til et andet navn.\nKopier",											// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"N&y folder...\tCtrl+P",																			// volba k vytvoøení nové sloky
IDN_PATH,					"Laver en ny folder til programmer.\nNew Folder",													// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Slet...\tSlet",																					// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Sletter programmet eller folderen (man kan ikke slette eksempel programmer eller foldere).\nSlet",	// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Korte na&vne",																						// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Program/folder vil blive lavet med forkortede navne med 8 karakterer\nKorte navne",				// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"Sl&ut\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Afslutter Peter programmet.\nAfslut",																// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"&Font Setup",																						// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Font i programmer &Vælg...",																		// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Sætter fonten i vinduet programvalg.\nFont i programvalg",											// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Font i program &editor...",																		// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Sætter font i vinduet til program editor.\nFont i program editor",									// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Font i &teks Editor...",																			// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Sætter font i tekst editor vinduet.\nFont i tekst editor",											// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Font i &menu...",																					// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Sætter font i menu.\nFont i menu",																	// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Font i status &bjælken...",																		// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Sætter fonten i statusbjælken.\nFont i statusbjælke",												// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"S&prog",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automatisk",																						// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Vælger sproget automatisk efter systemets indstillinger.\nAutomatisk",								// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"T&idligere\tCtrl+F9",																				// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Skifter imellem de to sidst brugte sprog.\nTidligere",												// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Bulgarsk (Bulgarija)",																				// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Skifter Peter til bulgarsk.\nBulgarsk",															// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"&Tjekkisk (Cesky)",																				// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Skifter Peter til tjekkisk.\nTjekkisk",															// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"Dansk",																							// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Skifter Peter til dansk.\nDansk",																	// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"T&ysk (Deutsch)",																					// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Skifter Peter til tysk.\nTysk",																	// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Græsk (Hellás)",																					// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Skifter Peter til græsk.\nGræsk",																	// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"&Engelsk (English)",																				// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Skifter Peter til engelsk.\nEngelsk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"S&pansk (España)",																					// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Skifter Peter til spansk.\nSpansk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finsk (Finland)",																					// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Skifter Peter til finsk.\nFinsk",																	// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"&Fransk (France)",																					// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Skifter Peter til fransk.\nFransk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"&Ungarsk (Magyar)",																				// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Skifter Peter til ungarsk.\nUngarsk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Islandsk (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Skifter Peter til islandsk.\nIslandsk",															// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Italiensk (Italy)",																				// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Skifter Peter til italiensk.\nItaliensk",															// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Hollandsk (Nederland)",																			// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Skifter Peter til hollandsk.\nHollandsk",															// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Norsk (Norge)",																					// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Skifter Peter til norsk.\nNorsk",																	// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Polsk (Po polsku)",																				// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Skifter Peter til polsk.\nPolsk",																	// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portugesisk (Portugal)",																			// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Skifter Peter til portugesisk.\nPortugesisk",														// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Romansk (România)",																				// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Skifter Peter til romansk.\nRomansk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&Russisk (Po-rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Skifter Peter til russisk.\nRussisk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Serbo-kroatisk (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Skifter Peter til serbo-kroatisk.\nSerbo-kroatisk",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"&Slovakkisk (Po slovensky)",																		// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Skifter Peter til slovakkisk.\nSlovakkisk",														// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albansk (Shqipërisë)",																				// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Skifter Peter til albansk.\nAlbansk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Svensk (Swerige)",																					// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Skifter Peter til svensk.\nSvensk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Tyrkisk (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Skifter Peter til tyrkisk.\nTyrkisk",																// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"&Vietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Hjælp",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Hjælp\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Viser hjælp for det valgte element.\nHjælp",														// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"Hjælp &Indhold",																					// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Viser indholdsfortegnelse for hjælp.\nHjælp Indhold",												// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Søg i hjælp",																						// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Søger i hjælp.\nSøg i hjælp",																		// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"&Om Peter programmet",																				// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Viser information om Peter programmet, versionsnummer og kopiret.\nOm Peter programmet",			// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Luk\tCtrl+O",																						// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Lukker editeringsprogrammet og åbner et andet.\nLuk",												// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Gem\tCtrl+S",																						// volba k uloení programu pøi editaci
IDN_SAVE,					"Gemmer ændringerne som er lavet i programmet.\nGem",												// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"G&em som ikke-eksekverbar\tCtrl+Alt+S",															// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Gemmer programmet som ikke-eksekverbar (fylder mindre).\nGem som ikke-eksekverbar",				// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Ge&m som...\tCtrl+Shift+S",																		// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Gemmer programmet under et andet navn eller et andet sted.\nGem som",								// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribuer...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Gemmer som distribution, ikke redigerbar version (kun med Professional licens).\nDistribuer",		// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Ek&port...",																						// volba k exportování programu
IDN_EXPORT,					"Eksporter programmet til tekstformat.\nEkport",													// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Imports et program fra tekst format.\nImport",														// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"&Rediger",																							// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Fortryd\tCtrl+Z",																					// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Fortryder en lavet handling.\nFortryd",															// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Genetabler\tCtrl+Y",																				// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Genetablerer den seneste fortrudte handling.\nGenetabler",											// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"&Klip\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Klipper valgt og flytter den til klippebordet.\nKlip",												// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"K&opier\tCtrl+C",																					// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Kopierer valg til klippebordet.\nKopier",															// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"&Sæt ind\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Sætter klippebordets indhold ind det valgte sted.\nSæt ind",										// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"Sl&et\tSlet",																						// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Sletter det valgte.\nSlet",																		// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"&Vælg alt\tCtrl+A",																				// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Vælger alt.\nVælg alt",																			// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Bruger dithering når man importerer eller skalerer billeder.\nDithering",							// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Se",																								// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"Zoom &Ind\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Forøger skærmens skalering.\nZoom Ind",															// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Zoom &ud\tCtrl+[-]",																				// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Formindsker skærmens skalering.\nZoom ud",															// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"&Tidligere ændrede\tCtrl+Up",																		// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Returnerer til det sidst ændrede element.\nTidligere ændrede",										// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"&Næste ændrede\tCtrl+Down",																		// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Returnerer til det næste ændrede element.\nNæste ændrede",											// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Find tekst...\tCtrl+F",																			// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Finder den indskrevne tekst.\nFind tekst",															// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"Ti&dligere tekst\tShift+F3",																		// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Finder en tidligere forekomst af teksten.\nTidligere tekst",										// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"Næ&ste tekst\tF3",																					// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Finder den næste forekomst af teksten.\nNæste tekst",												// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Program",																							// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Lås",																								// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Låser elementet så det ikke kan ændres.\nLås",														// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Slå fra",																							// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Slår elementets funktion fra/nSlå fra",															// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Beskrivelse\tAlt+Enter",																			// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Ændrer beskrivelsen af elementet .\nBeskrivelse",													// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Oprindelig b&eskrivelse",																			// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Bruger den oprindelige beskrivelse af elementet.\nOprindelig beskrivelse",							// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Ikon",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Ændrer elementets ikon.\nIkon",																	// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Oprindelig i&kon",																					// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Bruger elementets oprindelige ikon.\nOprindelig ikon",												// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"E&rklæring",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Finder elementets erklæring.\nErklæring",															// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"&Tidligere anvendelse",																			// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Finder elementets tidligere anvendelse.\nTidligere anvendelse",									// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"&Næste anvendelse",																				// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Finder elementets næste anvendelse.\nNæste anvendelse",											// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Billede",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"&Dimensioner...",																					// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Sætter generelle dimensioner.\nDimensioner",														// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Raster",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Slår rastervisning til/fra .\nRaster",																// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"Æ&ndr...",																							// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Ændrer billedet eller dets dele (ændr størrelse, rotation, farve valg).\nÆndr",					// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Blok stempel",																					// volba k otisku bloku do obrázku
IDN_OTISK,					"Stempler blokken på billedet.\nBlok stempel",														// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horisontal",																						// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Flipper billedet eller dets dele horisontalt.\nHorisontal",										// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertikalt",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Flipper billedet eller dets dele vertikalt.\nVertikalt",											// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"Ven&stre",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Roterer billedet til venstre(med 90 grader mod uret).\nVenstre",									// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"Hø&jre",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Roterer billedet til højre(med 90 grader med uret).\nHøjre",										// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"F&ordobbel",																						// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Forstørrer billedet eller dets dele to gange.\nFordobbel",											// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"H&alver",																							// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Halverer billedet eller dets dele.\nHalver",														// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"Til&pas",																							// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Tilpasser billedets størrelse eller dets dele efter valg.\nTilpas",								// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"B&yt",																								// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Bytter højre og venstre museknaps farver i billedet eller dets dele.\nByt",						// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Erstatning",																						// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Erstatter venstre museknap farve med venstre museknap farve i billedet eller dets dele.\nErstatning",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Værktøj",																							// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Pen",																								// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Tegner med pennen.\nPen",																			// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"&Linie",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Tegner en linie.\nLinie",																			// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"&Boks",																							// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Tegner en boks.\nBoks",																			// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"Fyldt b&oks",																						// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Tegner en fyldt boks.\nFyldt boks",																// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Cirkel",																							// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Tegner en cirkel.\nCirkel",																		// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Fyldt ci&rkel",																					// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Tegner en fyldt cirkel.\nFyldt cirkel",															// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Ellipse",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Tegner en ellipse (oval).\nEllipse",																// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"Fyl&dt ellipse",																					// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Tegner en fyldt ellipse (oval).\nFyldt ellipse",													// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"&Sfære",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Tegner en sfære (kugle).\nSfære",																	// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"&Valgt",																							// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Udvælger dele.\nValgt",																			// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"Spr&ay",																							// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Tegner med spray.\nSpray",																			// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"P&ipette",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Sætter farven under som den valgte.\nPipette",														// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"&Fylder",																							// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Fylder overfladen med en farve.\nFylder",															// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Tekst",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Skriver teksten.\nTekst",																			// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Tykkelse",																						// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Tykkelse &1 pixel",																				// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Tegner en streg med tykkelsen 1 pixel.\nTykkelse 1 pixel",											// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Tykkelse &2 pixels",																				// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Tegner en streg med tykkelsen 2 pixels.\nTykkelse 2 pixels",										// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Tykkelse &5 pixels",																				// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Tegner en streg med tykkelsen 5 pixels.\nTykkelse 5 pixels",										// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Tykkelse &9 pixels",																				// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Tegner en streg med tykkelsen 9 pixels.\nTykkelse 9 pixels",										// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Tykkelse 21 &pixels",																				// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Tegner en streg med tykkelsen 21 pixels.\nTykkelse 21 pixels",										// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"&Ark",																								// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"Ændrin&g",																							// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Sætter ændrings tilstanden til/fra for ark delene.\nÆndring",										// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Fyldning",																						// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Sætter fyldnings tilstanden til/fra for ark delene.\nFyldning",									// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"D&ele",																							// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Ændrer delene på arket.\nDele",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Flag &1",																							// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Ændrer flag 1.\nFlag 1",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Flag &2",																							// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Ændrer flag 2.\nFlag 2",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Flag &3",																							// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Ændrer flag 3.\nFlag 3",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Flag &4",																							// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Ændrer flag 4.\nFlag 4",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Flag &5",																							// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Ændrer flag 5.\nFlag 5",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"&Numerisk værdi 1",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Ændrer numerisk værdi 1 (fra 0 til 1023).\nNumerisk værdi 1",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"N&umerisk værdi  2",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Ændrer numerisk værdi 2 (fra 0 til 1023).\nNumerisk værdi 2",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Nu&merisk værdi 3",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Ændrer numerisk værdi 3 (fra 0 til 127).\nNumerisk værdi 3",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"S&prite",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Egenskaber",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Sætter spritens egenskaber (antal sider, retning, ...).\nEgenskaber",								// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Starter spriten i testtilstand.\nTest",															// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"&Lyd",																								// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Spil",																							// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Starter afspilning.\nSpil",																		// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"&Pause",																							// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pauser Afspilning.\nPause",																		// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"S&top",																							// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Stops afspilning.\nStop",																			// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Loop",																							// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Slår gentagelse af afspilningen fra/til.\nLoop",													// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Optag",																							// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Optager.\nOptag",																					// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Musik",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"Spol til&bage",																					// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Flytter afspilningen 10 sekunder tilbage.\nSpol tilbage",											// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"Spol &frem",																						// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Flytter afspilningen 10 sekunder frem.\nSpol frem",												// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"Om Peter programmet",																				// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Peter version",																					// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Kopiret © 1999-2012 Miroslav Nemecek",																// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Roznov pod Radhostem",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Den Tjekkiske Republik",																			// Èeská Republika
IDC_DEMOTEXT1,				"Demoversionen kan ikke gemme eller afvikle de nye",												// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"eller ændrede programmer. Mulighederne for ændringer,",											// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"hjælp og at gemme i biblioteket er fuldt funktionelle.",											// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Opdateret produkt information kan findes på den følgende Internet adresse:",						// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Bestillinger kan sendes til følgende adresse:",													// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENS",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"Ubegrænset",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"for 1 computer",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"computers",																						// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"computers",																						// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Lite version af Peter leverer et begrænset programmerings miljø ",									// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(ikke fungerende elementer er mærket med grå ikoner). Lite version",								// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"er FREEWARE og må distribueres og bruges frit til private",										// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"anvendelser. For kommerciel brug og skoler er licens betalingen",									// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"forlangt efter specifikationerne på adressen www.gemtree.com.",									// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Find Tekst",																						// titulek okna hledání textu
IDN_FINDTEXT,				"Skriv teksten der skal findes:",																	// vızva k zadání textu k hledání
IDN_CANCEL0,				"Annuller",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Ark dimensioner",																					// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Bredde:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Højde:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Åbningsfejl",																						// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"Programmet kan ikke åbnes.",																		// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Det kan allerede være åbnet af et andet",															// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"program eller tilgangen til filen er nægtet.",														// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Læsefejl",																							// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Program læsefejl.",																				// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"Programmet er beskadiget eller det var lavet af den nyere",										// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"version editor og det virker måske ikke af den grund.",											// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Ikke understøttet kommandoer",																		// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Advarsel: Dette program bruger kommandoer der ikke",												// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"understøttes af Lite version af Peter programmet.",												// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"Hvis programmet gemmes kan det blive ikke fungerende.",											// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Modifikation af billede eller dets valgte del",													// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Flip",																								// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horisontalt",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertikalt",																						// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Roter",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 grader)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 grader)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 grader)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 grader)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 grader)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 grader)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 grader)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 grader)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 grader)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 grader)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 grader)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 grader)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Tilpas",																							// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Fordobbel",																						// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Halver",																							// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Valgfrit",																							// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Farver",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Venstre <-> højre knap",																			// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Venstre -> højre knap",																			// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Billedets dimensioner",																			// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Dimensioner specificeret",																			// nadpis rámeèku volby jednotky
IDC_KROK,					"I &trin",																							// [1] volba jednotky v krocích
IDC_BOD,					"I &pixels",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Tilpas billede eller dets dele",																	// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Faktiske dimensioner:",																			// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"trin",																								// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"pixels",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Nye dimensioner",																					// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Bredde:",																							// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Højde:",																							// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"I trin",																							// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"I pixels",																							// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"Procent",																							// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Behold sidernes størrelse (størrelse højde/bredde)",												// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Gør kanter bedre (akkurat, men langsommere convertering)",											// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (TIL for fotografi, FRA for tegning)",													// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Farvevalg",																						// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Fejl, kan ikke lave programmet",																	// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Kan ikke lave programmet.",																		// 1. øádek hlášení
IDN_JINE_JMENO,				"Prøv et andet navn.",																				// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Program sletning",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Vil du virkelig slette det valgte program?",														// 1. øádek hlášení
IDN_SELECT_DEL2,			"ADVARSEL: Det vil ikke være muligt at gendanne programmet!",										// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Folder sletning",																					// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Vil du virkelig slette den valgte folder?",														// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Folder sletnings fejl",																			// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Folderen kan ikke slettes, hvis den ikke er tom.",													// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Program sletnings fejl",																			// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"Programmet kan ikke slettes, det er et program der kun kan læses.",								// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Ny folder",																						// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Hvad skal folderen hedde?",																		// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Fejl kan ikke oprette folder",																		// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Folderen kan ikke oprettes.",																		// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Folderen eksisterer allerede",																		// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Bemærk - der findes allerede en folder med det navn.",												// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Program eksisterer allerede",																		// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Bemærk - der findes allerede et program med det navn.",											// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Nyt Program",																						// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Hvad skal programmet hedde?",																		// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Program kopi",																						// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Hvad skal det kopierede program hedde?",															// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Sprite egenskaber",																				// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animation",																						// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Forsink mellem faser:",																			// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"millisekunder",																					// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Faser per skridt (0 = omgående):",																	// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Niveauer der skal vises (0 = Dele):",																// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Antal billeder",																					// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Stillestående faser:",																				// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Bevægende faser:",																					// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Retning:",																							// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Billede størrelse",																				// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Billedbredde:",																					// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Billedhøjde:",																						// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Sprite test",																						// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Gem fejl",																							// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"Programmet kan ikke gemmes.",																		// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Tjek, om det kører eller",																			// 2. øádek hlášení
IDN_WRITEERR3,				"det er beskyttet imod gemning.",																	// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"Hvis nødvendigt, gem programmet under",															// 4. øádek hlášení
IDN_WRITEERR5,				"et andet navn eller til en anden disk.",															// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Program ændret",																					// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Program ændret.\nØnsker du at gemme ændringerne?",													// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Elementet er i brug",																				// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Advarsel - slettede elementer bliver brugt i programmet.\nVed at slette, sletter du det tilhørende undertræ af dets elementer.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Uigenkaldelig sletning",																			// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Advarsel - du sletter et bibliotekselement.\nDenne sletning er uigenkaldelig, det vil ikke være muligt at genetablere elementet.",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"For lidt hukommelse",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"For lidt hukommelse for operationen!\n\nFrigør plads på Windows system disken \neller tjek opsætningen for den virtuelle hukommelse.\nDette program kan nu være i en ustabil tilstand.\ntDerfor afslut hurtigst muligt.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"Undskyld, dette program vil blive afsluttet på grund af manglende hukommelse!",					// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Beskadiget licens data",																			// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Licens dataene er beskadiget. Geninstaller Peter programmet for at korrigere dette.",				// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Afslutning af tidsbegrænset aktivitet",															// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Den tidsbegrænsede aktivitetsperiode for Peter programmet er udløbet.",							// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Afslutning af tidsbegrænset aktivitet",															// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"Peter programmet er tidsbegrænset.\nAntal dage tilbage ind til aktiviteter afsluttes:",			// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"System fejl",																						// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Ikke nok system ressourcer til at køre programmet PETER.EXE.",										// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Program beskadiget",																				// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Program PETER.EXE beskadiget, kunne ikke starte.",													// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Gem til en anden fil",																				// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programmer",																						// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Alle filer",																						// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Gem distributionsversion af programmet ",															// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Programmet eksisterer allerede",																	// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Advarsel - Et program med det navn eksisterer allerede.\n\nDu gemme distributionen til en version der ikke kan ændres\nmed dette program og hvis det overskrevne program er\net kildeprogram, vil al kilde information blive tabt.\n\nVil du virkelig fortsætte og overskrive filen?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Ikke eksekverbar program",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Dette program var lavet med programmeringsværktøjet Peter\nog det er nu gemt i et ikke eksekverbart format.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Font opsætning",																					// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Eksempel:",																						// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Dette er et tekst eksempel æøå ÆØÅ.",																// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Standard font",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Fed",																								// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Italic",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Underlinieret",																					// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Gennemstreget",																					// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Uden serifs",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"Med serifs",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Fikseret vidde",																					// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Valgt fra liste",																					// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Font liste Typenavne:",																			// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Højde:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Bredde[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Effekter",																							// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Form",																								// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Folder og navn til program eksport",																// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Importeret programs navn",																			// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Peter programmer",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"tomt kvadrat",																						// prázdnı implicitní pøedmìt
IDF_GROUP,					"gruppe",																							// skupina prvkù
IDF_IF,						"betinget afvikling af kommandoer",																	// záhlaví podmínky
IDF_IF_COND,				"hvis sand",																						// test podmínky (IF)
IDF_IF_YES,					"så gør",																							// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"ellers gør",																						// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"betinget gentagelse af kommandoer",																// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"så længe er sand",																					// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"gentag kommandoer",																				// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"afbryd afvikling",																					// pøerušení smyèky (BREAK)
IDF_MINUS,					"negativt tegn",																					// záporné znaménko "-" v èísle
IDF_CASE,					"flergrenet kontrol struktur",																		// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"for værdi af udsagn",																				// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"afvikl kommandoer hvis",																			// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"udsagn er lig med",																				// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"ellers afvikl kommandoer",																			// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"numerisk konstant",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"eksponent",																						// exponent v èísle
IDF_EQU,					"er lig med",																						// podmínka =
IDF_NEQU,					"er ikke lig med",																					// podmínka <>
IDF_EQGR,					"er større end eller lig med",																		// podmínka >=
IDF_EQLT,					"er mindre end eller lig med",																		// podmínka <=
IDF_GR,						"er større end",																					// podmínka >
IDF_LT,						"er mindre end",																					// podmínka <
IDF_AND,					"og",																								// logickı souèin
IDF_OR,						"eller",																							// logickı souèet
IDF_XOR,					"enten eller (eksklusiv eller)",																	// logickı vıhradní souèet
IDF_NOT,					"er ikke sand at",																					// logická negace
IDF_ADD,					"læg til",																							// souèet èísel
IDF_SUB,					"træk fra",																							// rozdíl èísel
IDF_MUL,					"gør til flere (multiplicer)",																		// násobek èísel
IDF_DIV,					"del",																								// podíl èísel
IDF_REAL,					"nummer",																							// èíselná promìnná
IDF_ICON,					"genstand",																							// pøedmìtová promìnná
IDF_SND,					"lyd",																								// zvuková promìnná
IDF_MUS,					"musik",																							// hudební promìnná
IDF_FNC,					"funktion",																							// funkce
IDF_MAP,					"ark",																								// promìnná plochy
IDF_SPRITE,					"sprite",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"program kontrol - udvidelse",																		// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"tekst",																							// textová promìnná
IDF_WINDOWS,				"vinduer",																							// skupina prvkù pro øízení oken
IDF_PAR,					"input variabler",																					// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"output variabler",																					// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"ark - udvidelse",																					// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"liste",																							// záhlaví seznamu (LIST)
IDF_OPER,					"program kontrol",																					// skupina prvkù pro øízení programu
IDF_KROK,					"skridt",																							// Petøík popojít o krok vpøed
IDF_VLEVO,					"venstre",																							// Petøík otoèit doleva
IDF_VPRAVO,					"højre",																							// Petøík otoèit doprava
IDF_VZAD,					"vend rundt",																						// Petøík otoèit vzad
IDF_PETRIK,					"Peter",																							// skupina prvkù Petøíka
IDF_BOOL,					"flag",																								// logická promìnná
IDF_TEXT_CONST,				"tekst konstant",																					// textová konstanta
IDF_TRUE,					"ja",																								// logickı pøíznak TRUE
IDF_FALSE,					"nej",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucy",																								// skupina prvkù Lucky
IDF_PETRA_KROK,				"skridt",																							// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"venstre",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"højre",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"vend rundt",																						// Lucka otoèit vzad
IDF_RYCHLE,					"synlig",																							// viditelnost Petøíka
IDF_EXIT,					"afslut funktion",																					// pøerušení funkce
IDF_PETRA_RYCHLE,			"synlig",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"lyd og musik",																						// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"genstand foran Peter",																				// pøedmìt pøed Petøíkem
IDF_SMER,					"retning",																							// smìr otoèení Petøíka
IDF_POZICEX,				"horisontal position",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"vertikal position",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"genstand foran Lucy",																				// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"retning",																							// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"horisontal position",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"vertikal position",																				// vertikální souøadnice Lucky
IDF_CONST,					"beregninger",																						// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"aritmiske operationer",																			// skupina èíselnıch operátorù
IDF_FUNC,					"funktioner",																						// skupina èíselnıch funkcí
IDF_POROVNANI,				"sammenligninger",																					// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logiske operationer",																				// skupina logickıch prvkù
IDF_MOD,					"modulus",																							// èíselnı operátor modulo
IDF_SIN,					"sinus",																							// funkce sinus
IDF_COS,					"cosinus",																							// funkce kosinus
IDF_TG,						"tangent",																							// funkce tangens
IDF_COTG,					"cotangent",																						// funkce kotangens
IDF_ARCSIN,					"arc sin",																							// funkce arcus sinus
IDF_ARCCOS,					"arc cos",																							// funkce arcus kosinus
IDF_ARCTG,					"arc tan",																							// funkce arcus tangens
IDF_ARCCOTG,				"arc cotan",																						// funkce arcus kotangens
IDF_PI,						"pi",																								// Ludolfovo èíslo (pí)
IDF_INTEGER,				"integer del",																						// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"devisor del",																						// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"absolut værdi",																					// funkce absolutní hodnoty
IDF_SQRT,					"kvadratrod",																						// funkce druhá mocnina
IDF_FACT,					"devisor",																							// funkce faktoriál
IDF_RAND,					"tilfældigt nummer (0 <= x < 1)",																	// náhodné èíslo
IDF_EUL,					"Euler konstant",																					// Eulerova konstanta (e)
IDF_DEGRAD,					"konverter grad til radian",																		// funkce konverze stupòù na radiány
IDF_RADDEG,					"konverter radian to grad",																			// funkce konverze radiánù na stupnì
IDF_LOG,					"decadiske logaritmer",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"naturlige logaritmer",																				// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"naturlige eksponentiel funktion",																	// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"grad af",																							// operátor mocniny
IDF_UHEL,					"vinkel, retning",																					// skupina úhlù (smìrù)
IDF_UHEL0,					"højre (0 pi, er 0 grader)",																		// smìr vpravo
IDF_UHEL45,					"højre op (1/4 pi, er 45 grader)",																	// smìr vpravo nahoru
IDF_UHEL90,					"op (1/2 pi, er 90 grader)",																		// smìr nahoru
IDF_UHEL135,				"venstre op (3/4 pi, er 135 grader)",																// smìr vlevo nahoru
IDF_UHEL180,				"venstre (1 pi, er 180 grader)",																	// smìr vlevo
IDF_UHEL225,				"venstre ned (1 1/4 pi, er 225 grader)",															// smìr vlevo dolù
IDF_UHEL270,				"ned (1 1/2 pi, er 270 grader)",																	// smìr dolù
IDF_UHEL315,				"højre ned (1 3/4 pi, er 315 grader)",																// smìr vpravo dolù
IDF_COMMAND,				"kontroller",																						// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"vent (standard = 0.05 s)",																			// pøíkaz pro èekání
IDF_KLAV,					"keyboard",																							// skupina ovládání klávesnice
IDF_KLAV_TEST,				"tast er trykket",																					// test stisknuté klávesy
IDF_KLAV_VKEY,				"tast input (venter ikke på tryk)",																	// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"karakter input (venter ikke på tryk)",																// vstup znaku bez èekání
IDF_KLAV_VK,				"taster",																							// skupina kódù kláves
IDF_KLAV_FX,				"funktions taster",																					// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"bogstaver",																						// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numerisk keyboard",																				// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"karakter taster",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"kontrol taster",																					// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"gennemsigtighed",																					// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 End",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 Down",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 PgDn",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 Left",																							// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 Right",																							// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Home",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 Up",																								// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Del",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 !",																								// kód klávesy 1 !
IDF_VK_2,					"2 @",																								// kód klávesy 2 @
IDF_VK_3,					"3 #",																								// kód klávesy 3 #
IDF_VK_4,					"4 $",																								// kód klávesy 4 $
IDF_VK_5,					"5 %",																								// kód klávesy 5 %
IDF_VK_6,					"6 ^",																								// kód klávesy 6 ^
IDF_VK_7,					"7 &",																								// kód klávesy 7 &
IDF_VK_8,					"8 *",																								// kód klávesy 8 *
IDF_VK_9,					"9 (",																								// kód klávesy 9 (
IDF_VK_0,					"0 )",																								// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~",																								// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _",																								// kód klávesy - _
IDF_VK_ROVNITKO,			"= +",																								// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ |",																								// kód klávesy \ |
IDF_VK_LLOMENA,				"[ {",																								// kód klávesy [ {
IDF_VK_RLOMENA,				"] }",																								// kód klávesy ] }
IDF_VK_STREDNIK,			"; :",																								// kód klávesy ; :
IDF_VK_RCARKA,				"\' \"",																							// kód klávesy ' "
IDF_VK_CARKA,				", <",																								// kód klávesy , <
IDF_VK_TECKA,				". >",																								// kód klávesy . >
IDF_VK_LOMITKO,				"/ ?",																								// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"venstre Windows menu tast",																		// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Tilbage",																							// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"lokal menu",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"Venstre",																							// kód klávesy Vlevo
IDF_VK_RIGHT,				"Højre",																							// kód klávesy Vpravo
IDF_VK_UP,					"Op",																								// kód klávesy Nahoru
IDF_VK_DOWN,				"Ned",																								// kód klávesy Dolù
IDF_VK_INSERT,				"Indsæt",																							// kód klávesy Insert
IDF_VK_DELETE,				"Slet",																								// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"End",																								// kód klávesy End
IDF_VK_PAGEUP,				"Pg Up",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Pg Dn",																							// kód klávesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"venstre Shift",																					// kód klávesy Levı Shift
IDF_VK_CTRL,				"venstre Ctrl",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"venstre Alt",																						// kód klávesy Levı Alt
IDF_VK_SPACE,				"spacebar (mellemrum)",																				// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"mus",																								// skupina prvkù myši
IDF_MOUSE_L,				"venstre museknap holdes nede",																		// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"højre museknap holdes nede",																		// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"mus position i horisontal retning",																// horizontální souøadnice myši
IDF_MOUSE_Y,				"mus position i vertikal retning",																	// vertikální souøadnice myši
IDF_EQU_TEXT,				"tekst identitet",																					// operátor porovnání textù
IDF_EQU_ICO,				"genstand identitet",																				// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"sprites - udvidelse",																				// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"vindue har kanter",																				// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"vindue har overskrift",																			// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"program parametre",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"returner kode",																					// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"billede",																							// promìnná obrázku
IDF_REPEAT,					"kommandoo gentages med specifikt antal afviklinger",												// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"for antal gentagelser",																			// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"ark kant",																							// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horisontal",																						// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertikal",																							// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"retning",																							// smìr sprajtu
IDF_SPRITE_MOVE,			"bevægelse",																						// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"synlig",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"nummer",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"indeks",																							// index seznamu
IDF_LIST_AUTO,				"indeks forøg",																						// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Peter - udvidelse",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucy - udvidelse",																					// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"numerisk værdi 1 (fra 0 til 1023)",																// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"numerisk værdi 1 (fra 0 til 1023)",																// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"numerisk værdi 2 (fra 0 til 1023)",																// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"numerisk værdi 2 (fra 0 til 1023)",																// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"numerisk værdi 3 (fra 0 til 127)",																	// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"numerisk værdi 3 (fra 0 til 127)",																	// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"flag 1",																							// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"flag 1",																							// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"flag 2",																							// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"flag 2",																							// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"flag 3",																							// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"flag 3",																							// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"flag 4",																							// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"flag 4",																							// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"flag 5",																							// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"flag 5",																							// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"tekster",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"venstre del af tekst",																				// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"længde af venstre del af tekst",																	// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"højre del af tekst",																				// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"begyndelsen af højre del af tekst",																// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"midterste del af tekst",																			// funkce støední èásti textu
IDF_TEXT_MID_POS,			"begyndelsen af midterste del af tekst",															// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"længde af midterste del af tekst",																	// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"længde af tekst",																					// funkce zjištìní délky textu
IDF_TEXT_ADD,				"sammensæt  tekster",																				// operátor pro slouèení textù
IDF_TEXT_SCAN,				"konvertering af nummer fra tekst form",															// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"konvertering af nummer til tekstform",																// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"alfabetisk sammenligning af tekster",																// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"konverter til små bogstaver",																		// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"konverter til store bogstaver",																	// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"find tekst position (-1 = ingen)",																	// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"input tekst",																						// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"tekst der skal findes",																			// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"informations tekst",																				// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"vindues overskrift",																				// titulek hlavního okna (textová promìnná)
IDF_ORD,					"konverter bogstav til numerisk kode",																// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"konverter numerisk kode til bogstav",																// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"lyd",																								// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"spil lyd",																							// pøehrátí zvuku
IDF_SOUND_STOP,				"stop lyd (standard = alle)",																		// vypnutí zvuku
IDF_COLOR,					"farve",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"grafik",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"pen farve",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"pen bredde",																						// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"punkt",																							// nakreslení grafického bodu
IDF_POINT_X,				"horisontal X koordinat for punkt",																	// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertikal Y koordinat for punkt",																	// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"linie",																							// nakreslení èáry
IDF_LINE_X1,				"horisontal X1 koordinat for linie",																// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertikal Y1 koordinat for linie",																	// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horisontal X2 koordinat for linie",																// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertikal Y2 koordinat for linie",																	// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"boks",																								// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horisontal X1 koordinat for boks",																	// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertikal Y1 koordinat for boks",																	// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horisontal X2 koordinat for boks",																	// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertikal Y2 koordinat for boks",																	// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"fyldtboks",																						// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horisontal X1 koordinat for fyldtboks",															// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertikal Y1 koordinat for fyldtboks",																// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horisontal X2 koordinat for fyldtboks",															// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertikal Y2 koordinat for fyldtboks",																// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"filler",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horisontal X koordinat for filler",																// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertikal Y koordinat for filler",																	// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"cirkel",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horisontal X koordinat til center",																// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertikal Y koordinat til center",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"radius",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"fyldt cirkel",																						// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horisontal X koordinat til center",																// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertikal Y koordinat til center",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"radius",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"trekant",																							// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horisontal X1 koordinat for trekant",																// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertikal Y1 koordinat for trekant",																// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horisontal X2 koordinat for trekant",																// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertikal Y2 koordinat for trekant",																// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horisontal X3 koordinat for trekant",																// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertikal Y3 koordinat for trekant",																// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"sfære",																							// nakreslení koule
IDF_SPHERE_X,				"horisontal X koordinat til center",																// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertikal Y koordinat til center",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"radius",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"ændr farve tonen",																					// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"farve tone (0 til 1)",																				// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"taste input (venter på at blive trykket)",															// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"bogstav input (venter på at blive trykket)",														// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"ingen tast trykket",																				// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"højre Windows menu key",																			// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"højre Shift",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"højre Ctrl",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"højre Alt",																						// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"status for Num Lock",																				// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"status for Caps Lock",																				// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"status for Scroll Lock",																			// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"status for Insert",																				// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"klik med venstre muse knap",																		// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"klik med højre muse knap",																			// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"dobbelt klik med venstre muse knap",																// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"dobbelt klik med højre muse knap",																	// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"muse test i området",																				// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horisontal X koordinat for begyndelsen af regionen",												// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertikal Y koordinat for begyndelsen af regionen",													// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"bredden af regionen",																				// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"højde af regionen",																				// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"vis tekst",																						// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horisontal X koordinat for tekst",																	// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertikal Y koordinat for tekst",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"vinkel orientering for tekst",																		// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"højde af bogstaver",																				// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"relative bredde af bogstaver (1 = normal)",														// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"fed",																								// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"italic",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"linje under",																						// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"gennemstreget",																					// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"serifs",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"typewriter",																						// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"tekst der skal vises",																				// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"antal tekst linier",																				// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"tekst linie",																						// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"tekst linie nummer",																				// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"lyd test (standard = alle lyde)",																	// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"repetition nummer (0 = hele tiden)",																// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"genstand ved Peter\'s position",																	// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"genstand ved Lucy\'s position",																	// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"tegn billede",																						// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"billede der skal tegnes",																			// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horisontal X koordinat for billede",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertikal Y koordinat for billede",																	// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horisontal X koordinat for udklip",																// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertikal Y koordinat for udklip",																	// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"bredden af udklippet",																				// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"højden af udklippet",																				// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"behold udklip fra ark som billede",																// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"behold udklip fra ark som genstand",																// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"sprog (0=auto, 5=CZ,6=DK, 7=D, 9=USA, 27=SK)",														// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"lyd som kan afspilles",																			// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"lydstyrke (0 til 1)",																				// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"stereofonisk balance (-1 = venstre til +1 = højre)",												// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"afbryd spillende lyd",																				// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"kommentar",																						// komentáø
IDF_SOUND_FUNCTIONS,		"lyd funktioner",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"sætter form af muse cursor (markør)",																// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"billede som muse cursor (standard = original)",													// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horisontal X koordinat for regionens begyndelse",													// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertikal Y koordinat for regionens begyndelse",													// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"bredde af regionen",																				// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"højde af regionen",																				// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"spil musik",																						// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"spil musik gentaget",																				// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"stop spillende musik",																				// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"pause/fortsæt spillende musik",																	// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test spillende musik",																				// test pøehrávání hudby
IDF_MUSIC_POS,				"position i musikken som afspilles",																// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"længde af musikken som afspilles",																	// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"sammensæt farve komponenter til farve",															// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"rødt komponent (0 til 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"grønt komponent (0 til 1)",																		// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"blå komponent (0 til 1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"tag pixels farve",																					// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horisontal X koordinat for getting farve of pixel",												// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertikal Y koordinat for getting farve of pixel",													// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"potens",																							// funkce druhá mocnina
IDF_MUSIC_GROUP,			"musik",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"audio CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"spil CD fra ønsket spor (standard = 1)",															// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"stop afspiller CD",																				// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"pause/fortsæt afspilling af CD",																	// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test CD som spiller",																				// test pøehrávání CD
IDF_CD_LENGTH,				"total længde",																						// celková délka CD
IDF_CD_TRACKS,				"antal spor",																						// poèet stop CD
IDF_CD_POS,					"position fra begyndelsen",																			// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"spor som afspilles",																				// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"længde af spor som afspilles",																		// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"position fra sporets begyndelse",																	// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"filer",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"basis operationer",																				// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"ny fil",																							// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"ny folder",																						// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"delete fil eller folder",																			// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"test om ekisterer",																				// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"aktiv disk og folder",																				// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"disk kapacitet",																					// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"fri disk plads",																					// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"disk indholds mærkat",																				// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"disk serie nummer",																				// zjištìní sériového èísla disku
IDF_FILE_READ,				"aktiv fil/folder til læsning",																		// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"aktive fil/folder til skrivning",																	// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"fil kopier",																						// provedení kopie souboru
IDF_FILE_MOVE,				"fil (folder) flyt/nyt navn",																		// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disk",																								// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"egenskaber",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"egenskaben R/O (læs-kun)",																			// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"egenskaben HID (skjult)",																			// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"egenskaben SYS (system)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"egenskaben DIR (folder)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"egenskaben ARC (arkiv)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"egenskaben TEMP (temporær, midlertidig)",															// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"egenskaben COMP (komprimeret)",																	// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"egenskaben OFF (offline)",																			// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"dato og tid for oprettelse",																		// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"sidste tilgangs dato og tid",																		// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"sidste skrive dato og tid",																		// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"data",																								// skupina dat souborù
IDF_FILE_BYTES,				"integer nummer med markør, 1 byte",																// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"integer nummer uden markør, 1 byte",																// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"integer nummer med markør, 2 bytes",																// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"integer nummer uden markør, 2 bytes",																// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"integer nummer med markør, 4 bytes",																// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"integer nummer uden markør, 4 bytes",																// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"decimal nummer, 4 bytes",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"decimal nummer, 8 bytes",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"tekst afsluttet med binært null (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"tekst afsluttet med  EOL (afslutning af linje)",													// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"tekst med fast længde",																			// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"genstand (ICO)",																					// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"billede (BMP, JPG)",																				// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"lyd (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"musik (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"læs peger",																						// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"skriv peger",																						// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"dato og tid",																						// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"aktuel dato og tid (antal sekunder siden 1. januar 1601)",											// aktuální datum a èas
IDF_DATETIME_UTC,			"konverter lokal tid til verdens tid",																// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"konverter verdens tid til lokal tid",																// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"sammensæt komponenter af dato and tid",															// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"år",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"måned",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"dag",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"time",																								// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minut",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"sekund",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"millisekund",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"år fra dato og tid",																				// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"månede fra dato og tid",																			// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"dag fra dato og tid",																				// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"dag i ugen fra dato og tid (0 = søndag, 1 = mandag, ...)",											// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"time fra dato og tid",																				// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minut fra dato og tid",																			// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"sekund fra dato og tid",																			// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"millisekund fra dato og tid",																		// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"konverter dato til tekst \"dag.måned.år\"",														// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"konverter dato til tekst \"måned/dag/år\"",														// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"konverter dato til tekst \"år-måned-dag\"",														// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"konverter tid til tekst \"time:minut:sekund\" (24 timer)",											// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"konverter tid til tekst \"time:minut:sekund x\" (12 timer)",										// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"størrelse af fil",																					// velikost souboru
IDF_FILE_ERROR,				"operations fejl flag",																				// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"længde af tekst med fast længde",																	// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"disk type (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",														// zjištìní typu disku
IDF_TEXT_FORMAT2,			"konverter nummer til tekst - 2 cifre",																// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"konverter nummer til tekst - 8 HEX cifre",															// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"integer nummer med markør, 3 bytes",																// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"integer nummer med markør, 3 bytes",																// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"dialoger",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"bekræftelses dialog (return 1=OK, 2=Annuler, 3=Abort, 4=Gentag, 5=Ignorer, 6=Ja, 7=Nej)",			// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"tekst",																							// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"overskrift",																						// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"ikon (0=ingen, 1=fejl, 2=spørgsmål, 3=advarsel, 4=information)",									// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"knapper (0=OK, 1=OK/Annuler, 2=Abort/gentag/Ignorer, 3=Ja/Nej/Annuler, 4=Ja/Nej, 5=Gentag/Annuler)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"standard knap (1 til 3)",																			// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"næste linie",																						// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"indsæt tekst",																						// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1. linie af besked",																				// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2. linie af besked",																				// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3. linie af besked",																				// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"forberedt tekst som indsættes",																	// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"skub CD ud",																						// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"antal bits pr. sample (8 eller 16)",																// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"sample frekvens (Hz)",																				// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"er lyden sterefonisk?",																			// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"længden af lyd (sekunder)",																		// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"konverter til 8 bits",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"konverter til 16 bits",																			// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"konverter til stereo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"konverter til mono",																				// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"konverter til 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"konverter til 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"konverter til 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"sammensætning af lyde",																			// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"ændr lydens hastighed",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"lyd til konvertering",																				// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relativ ændring af hastighed (1 = unden ændringer)",												// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"tone generator",																					// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"tonens frekvens (Hz)",																				// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"længden af tonen (sekunder)",																		// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"ark",																								// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"bredden af arket",																					// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"højden af arket",																					// zjištìní vıšky plochy
IDF_MAP_X,					"X koordinat",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"Y koordinat",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"ark",																								// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"genstand",																							// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"numerisk værdi 1 (fra 0 til 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"numerisk værdi 2 (fra 0 til 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"numerisk værdi 3 (fra 0 til 127)",																	// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"flag 1",																							// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"flag 2",																							// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"flag 3",																							// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"flag 4",																							// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"flag 5",																							// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"kopier udklip fra arket",																			// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"ark med udklip",																					// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"X koordinat for udklip",																			// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"Y koordinat for udklip",																			// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"udklippets bredde",																				// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"udklippets højde",																					// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"konsol",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"flyt alle sprites i X retning",																	// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"flyt alle sprites i Y retning",																	// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"venstre kant af sprite vinduet",																	// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"nedre kant af sprite vinduet",																		// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"højre kant af sprite vinduet",																		// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"øvre kant af sprite vinduet",																		// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"konsol tilstand (skal bruges ved begyndelsen af hovedfunktionen (main))",							// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"tekst output til konsol",																			// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"tekst input fra konsol",																			// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"fejl tekst output til konsol",																		// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"program parameter (0 = program navn)",																// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"program navn med fuld sti",																		// jméno tohoto programu s plnou cestou
IDF_EXEC,					"program afvikling",																				// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"program afvikling med pause",																		// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"joystick",																							// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"X koordinat for joystick",																			// souøadnice X joysticku
IDF_JOYSTICK_Y,				"Y koordinat for joystick",																			// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"Z koordinat for joystick",																			// souøadnice Z joysticku
IDF_JOYSTICK_1,				"knap 1 på joystick",																				// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"knap 2 på joystick",																				// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"knap 3 på joystick",																				// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"knap 4 på joystick",																				// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"tekster og billeder",																				// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"element nummer (0 = hoved vindue)",																// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"slet element/vindue",																				// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"lav vindue",																						// vytvoøení dialogového okna
IDF_WINDOW_X,				"horisontal koordinat",																				// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"vertikal koordinat",																				// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"bredde",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"højde",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"tekst",																							// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"synlig",																							// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"ude af funktion",																					// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"lav knap",																							// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"knap tryk eller element ændring",																	// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"lav tjekboks",																						// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"lav edit linie",																					// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"lav switch (kontakt)",																				// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"funktioner ens for alle elementer",																// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"lav ændringsområde (edit field)",																	// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"knapper",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"slå til/fra",																						// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"input fokus",																						// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"lav standard knap",																				// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"lav ikon knap",																					// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"lav ramme",																						// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"lav listeboks",																					// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"lav tekst",																						// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"lav drop-down listeboks",																			// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"lav drop-down listeboks med edit",																	// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"fed",																								// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"fast pitch",																						// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"lav switch - gruppe begyndelsen",																	// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"listebokse",																						// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"tilføj indsæt i listeboks",																		// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"tom listeboks",																					// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"lav listeboks med edit",																			// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"lav 3-tilstands tjekboks",																			// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"switch i udefineret tilstand",																		// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"lav vindue som ikke kan lukkes",																	// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"ikon",																								// ikona prvku dialogového okna
IDF_WINICON_NEW,			"lav ikon",																							// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"sprite (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*pi (= 360 grader)",																				// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"afstand for 1 pixel (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"fase",																								// fáze sprajtu
IDF_SPRITE_STATUS,			"tilstand",																							// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"full screen mode (fuldskærmstilstand)",															// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"tøm taste buffer (lager)",																			// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"position i spillende lyd",																			// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"pause/fortsæt afspilling af lyd",																	// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"fil liste",																						// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"ark identitet",																					// operátor porovnání ploch
IDF_EQU_PIC,				"billede identitet",																				// operátor porovnání obrázkù
IDF_EQU_SPR,				"sprite identitet",																					// operátor porovnání sprajtù
IDF_EQU_SND,				"lyd identitet",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"musik identitet",																					// operátor porovnání hudeb
IDF_NET_GROUP,				"kommunikation",																					// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"net understøttet DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"liste over net enheder",																			// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"aktiv netenhed",																					// aktivní spojení DirectPlay
IDF_GAME_LIST,				"liste over spil",																					// seznam bìících her DirectPlay
IDF_GAME_ACT,				"aktivt spil",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"list over spillere",																				// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"aktiv spiller",																					// aktivní hráè DirectPlay
IDF_GAME_N1,				"numerisk spil parameter 1 (-16384 til +16383)",													// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"numerisk spil parameter 2 (-16384 til +16383)",													// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"numerisk spil parameter 3 (-16384 til +16383)",													// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"numerisk spil parameter 4 (-16384 til +16383)",													// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"numerisk spil parameter 5 (-16384 til +16383)",													// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"numerisk spil parameter 6 (-16384 til +16383)",													// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"numerisk spil parameter 7 (-16384 til +16383)",													// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"numerisk spil parameter 8 (-16384 til +16383)",													// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"spil flag 1",																						// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"spil flag 2",																						// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"spil flag 3",																						// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"spil flag 4",																						// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"spil flag 5",																						// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"spil flag 6",																						// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"spil flag 7",																						// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"spil flag 8",																						// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"spil setup",																						// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"host (kontrol computer)",																			// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"maximum antal spillere (0 = ubegrænset)",															// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"aktivt spiller nummer (-1 = ingen)",																// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"data",																								// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"data blok send/modtag (-1 = til alle/ingen)",														// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"nummer",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"tekst",																							// text dat DirectPlay
IDF_GAME_DATAL,				"flag",																								// pøepínaè dat DirectPlay
IDF_GAME_IP,				"IP adresse for denne computer",																	// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"integer nummer 0 til 255 (byte)",																	// èíslo bajt dat DirectPlay
IDF_INC,					"forøg (tilføjer 1)",																				// funkce inkrementace èísla
IDF_DEC,					"formindsk (fratrækker 1)",																			// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"lav centreret tekst",																				// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"knap som Esc key (-1 = ingen)",																	// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"billede bredde",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"billede højde",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"horisontal flip af billede",																		// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"vertikal flip af billede",																			// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"billeder",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"ændr billede størrelse",																			// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"billede",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"bredde (standard = proportional til højden)",														// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"højde (standard = proportional til bredden)",														// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"gør kanter finere",																				// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (fotografisk)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"tegning",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"lav billede",																						// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"billede",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"lav RichEdit editor",																				// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"højden af bogstaver (0 = normal)",																	// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"italic",																							// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"linje under",																						// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"gennemstreg",																						// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"serifs",																							// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"relative bredde for bogstaver (0 = normal, 1 = udgangspunkt)",										// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"tekst hældningsvinkel",																			// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"lav højre justeret tekst",																			// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"bogstav farve",																					// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"baggrunds farve",																					// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"font i element",																					// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"hastighed for afspiller (1 = normal)",																// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"forskelskode (0 til 65535)",																		// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"skriv fil, der skal åbnes",																		// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"skriv fil, der skal gemmes",																		// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"skriv tekst, der skal findes",																		// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"skriv farve",																						// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"fil maske",																						// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"forberedt filnavn",																				// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"fil type navn",																					// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"ændr billedets tone",																				// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"billede som skal have ændret tone",																// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"billede tone (1 = normal)",																		// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"roter billede",																					// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"billede som skal roteres",																			// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"rotationsvinkel",																					// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"lyd dekompression",																				// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"tekst er i UNICODE format (2 bytes)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"konverter ark til billede",																		// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"konverter genstand til billede",																	// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"bit operationer",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"AND bit produkt",																					// bitovı (binární) souèin AND
IDF_BIT_OR,					"OR bit sum",																						// bitovı (binární) souèet OR
IDF_BIT_XOR,				"XOR bit ombytning",																				// bitová (binární) inverze XOR
IDF_BIT_NOT,				"NOT bit komplement",																				// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"maksimum bit nummer (doubleword)",																	// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"bit roter venstre",																				// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"bit roter højre",																					// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"test mus i element",																				// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"intern bredde",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"intern højde",																						// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"sæt alfabet (1250=østeuropa, 1251=russisk, 1252=vestlig)",											// èíslo pouité znakové sady fontù
IDF_USERFONT,				"bruger font",																						// jméno uivatelského fontu
IDF_ENUMFONTS,				"font liste",																						// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"nyt ark",																							// vytvoøení nové plochy
IDF_MAP_NEW_W,				"ark bredde",																						// šíøka nové plochy
IDF_MAP_NEW_H,				"ark højde",																						// vıška nové plochy
IDF_WINDOW_TOP,				"altid forrest",																					// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"alias navn",																						// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"kommunikationsport",																				// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"åbn port (-1=fejl)",																				// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"luk port",																							// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"aktiv port",																						// aktivní port
IDF_COM_NUM,				"nummer (0 til 255)",																				// vstup/vıstup èísla
IDF_COM_TEXT,				"karakter (tekst)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"baud rate",																						// pøenosová rychlost
IDF_COM_STOP,				"2 stop bits",																						// reim s 2 stopbity
IDF_COM_BITS,				"antal bits (5 til 8)",																				// poèet bitù na znak
IDF_COM_PARIT,				"paritet (0=ingen, 1=ulige, 2=lige)",																// zvolená parita
IDF_COM_IN,					"karakter var modtaget",																			// byl pøijatı znak
IDF_COM_SEND,				"sending er tilladt (CTS, RTS)",																	// povoleno vysílání
IDF_COM_RECEIVE,			"modtagelse er tilladt (DSR, DTR)",																	// povolen pøíjem
IDF_PICTURE_MASK,			"billed maskering",																					// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"billede",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"maske",																							// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"område bredde som viser tekst (0 = ingen)",														// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"lav edit område uden linjeskift",																	// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"vindue der kan ændre størrelse",																	// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"vindue kan lukkes",																				// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"vindue er maksimeret",																				// maximalizace okna
IDF_WINDOW_MINIM,			"vindue er minimeret",																				// minimalizace okna
IDF_PROGRESS_NEW,			"lav progressbar",																					// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"lav horisontal trackbar",																			// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"lav vertikal trackbar",																			// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"aktuel position",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"mixer enhed",																						// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"mixer enhed",																						// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"destinations linie",																				// volba cílového signálu
IDF_MIX_LINE_SRC,			"kilde linie (ingen=kun destinations linie)",														// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"linie type",																						// zjištìní typu signálu
IDF_MIX_CONTROL,			"kontroller genstand",																				// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"kontroller genstands type",																		// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"værdi af kontroller genstand (0 til 1)",															// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"valg af genstands værdi",																			// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"kontrolleret kanal (-1=alle)",																		// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D grafik",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"3D grafik vindue",																					// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X koordinat for 3D grafik vindue",																	// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y koordinat for 3D grafik vindue",																	// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"bredde af 3D grafik vindue",																		// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"højde af 3D grafik vindue",																		// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"videomode (bredde*højde/bits)",																	// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"grafisk baggrund",																					// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"opsætning",																						// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"filling overflader",																				// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"belysning",																						// mód osvìtlení
IDF_DIRECT3D_SHADES,		"jævn skygge",																						// mód stínování
IDF_DIRECT3D_INVERT,		"objekt ombytning",																					// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objekter",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"mur",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"kube",																								// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"sfære",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"cylinder",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"kegle",																							// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"klon",																								// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"objekt fra tekst",																					// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"objekt fra fil",																					// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"aktiv objekt (0=scene, 1=kamera, 2=lys)",															// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"slet objekt",																						// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"synlig",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"link",																								// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"objekt til fil",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformationer",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"skaler i X retning",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"skaler i Y retning",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"skaler i Z retning",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"rotation om X-aksen",																				// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"rotation om Y-aksen",																				// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"rotation om Z-aksen",																				// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"flyt i X retning",																					// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"flyt i Y retning",																					// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"flyt i Z retning",																					// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"overflade",																						// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"farve (-1=intern, -2=standard)",																	// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"udsendt farve",																					// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"dæmpning (0=fra, 5=metal, 50=plastik)",															// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"reflekterende farve",																				// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"tekstur",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"tekstur mapning",																					// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"projektor type (0=flad, 1=cylinder, 2=sfære, 3=chrom, 4=linse)",									// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"X koordinater for projektor center",																// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"Y  koordinater for projektor center",																// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"Z  koordinater for projektor center",																// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"rotation af projektor om X-aksen",																	// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"rotation af projektor om Y-aksen",																	// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"rotation af projektor om Z-aksen",																	// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"gennemsigtighed (1=normal, 11=ild, 20=glas, 54=overlappet)",										// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"konturer (0=normal, 0.5=konturer)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"methode (0=adresser, 1=diagonaler, 2=sider)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"horisontal oprindelse af tekstur",																	// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"vertikal oprindelse af tekstur",																	// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"horisontal mindskningsgrad for tekstur",															// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"vertikal mindskningsgrad for tekstur",																// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"belysning",																						// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"lav nyt lys",																						// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"lys farve",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"lys type (1=punkt, 2=spot, 3=directional)",														// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"vinkel for lyskegle",																				// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"skygge vinkel",																					// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"lys rækkevidde",																					// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"lysintensitet (1=normal)",																			// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"lineær svækkelse",																					// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"kvadratisk svækkelse",																				// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"projektions type (0=persp, 1=ortho, 2=r-persp, 3=r-ortho)",										// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"scene",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"scene baggrundsfarve (-1=fra, -2=ingen initialisering)",											// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"scene baggrundstekstur",																			// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"tåge farve (-1=fra)",																				// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"tåge type (0=lin, 1=exp, 2=quadr, +4=korrektion)",													// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"start af lineær tåge",																				// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"slutning af lineær tåge",																			// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"tykkelse af exp. og quadr. tåge (0 til 1)",														// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"distancen af projektionsplanet",																	// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"synlig rækkevidde afstand",																		// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"lav øvre base",																					// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"lav nedre base",																					// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"søg objekt",																						// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"X koordinat for punkt",																			// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"Y koordinat for punkt",																			// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"tekstur minimerings filter",																		// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"2D objekt",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terræn fra billede",																				// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"terræn niveau",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"horisontal koordinat",																				// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"vertikal koordinat",																				// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"gruppe",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"kompleksitet af objekt (2 til 100)",																// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"rotationsorden (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",										// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"driver (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"roterende objekt",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terræn fra ark",																					// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"reflektion af rumlys (-1=standard)",																// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"programmet er den aktive applikation",																// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"distance til punkt",																				// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"vinkel til punkt",																					// vıpoèet úhlu bodu
IDF_POLAR_X,				"X koordinat for punkt",																			// souøadnice X bodu
IDF_POLAR_Y,				"Y koordinat for punkt",																			// souøadnice Y bodu
IDF_FILE_LOGIC,				"logisk værdi",																						// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"udjævning af teksturer (1=nej)",																	// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"præcis tids tæller",																				// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"rumlys",																							// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"tekstur forstørrelses filter",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"langtvæk tekstur filter",																			// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"filling objekt overflader",																		// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"objekt belysning",																					// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"objekt udjævn skygge",																				// mód stínování
IDF_DIRECT3D_OMINFILTER,	"objekt tekstur minimerings filter",																// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"objekt tekstur forstørrelses filter",																// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"langtvæk objekt tekstur filter",																	// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"synlig objekt side (0=begge, 1=forside, 2=bag)",													// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"lav",																								// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"objekt normalisering",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"cirkel",																							// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"trekant",																							// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"torus/ring (parameter = diameter 0 til 1)",														// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"statisk 2D objekt",																				// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"halvkugle",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interface (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",								// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"gået tid",																							// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"rendering hastighed",																				// rychlost renderování
IDF_DIRECT3D_FREE,			"fri videohukommelse",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D billede",																						// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"teksturer",																						// skupina textur
IDF_DIRECT3D_STAGE,			"scene (0 til 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"farve operation (1=fra, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"første farve argument (0=farve, 1=resultat, 2=tekstur, 3=faktor, 16=ombytning)",					// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"anden farve argument (0=farve, 1=resultat, 2=tekstur, 3=faktor, 16=ombytning)",					// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"alpha operation (1=fra, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"første alpha argument (0=farve, 1=resultat, 2=tekstur, 3=faktor, 16=ombytning)",					// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"anden alpha argument (0=farve, 1=resultat, 2=tekstur, 3=faktor, 16=ombytning)",					// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"horisontal adresserings tilstand (1=gentag, 2=spejl, 3=hold)",										// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"vertikal adresserings tilstand (1=gentag, 2=spejl, 3=hold)",										// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"udviskning af langtvæk teksturer (0=standard)",													// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"omvendt kegle (parameter = diameter 0 til 1)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"farve for tekstur faktor",																			// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alpha komponent (0=gennemsigtighed til 1=farve)",													// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"antal langtvæk teksturer (0=alle)",																// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"render gruppe (0-7=objekter, 8-11=gennemsigtig, 12-15=billeder)",									// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"dybde sorter render gruppe",																		// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"skriv dybde information",																			// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"dybde test (1 aldrig, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 altid)",									// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"beregn normaler (parameter = vinkel for udjævning)",												// pøepoèet normál
IDF_DIRECT3D_RENDER,		"render uden at vise",																				// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"tekst blok",																						// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"linie som begynder blokken",																		// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"position for begyndelsen af blokken",																// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"linie som afslutter blokken (-1=ende)",															// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"positionen som afslutter blokken (-1=ende)",														// pozice konce bloku
IDF_WINDOW_POS2,			"aktuel position 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"lav switch knap",																					// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"lav tabel (parameter = liste over titler)",														// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"bredden af tabel kolonne",																			// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"skygge rækkevidde (0=fra)",																		// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"juster tabel kolonner (0=venstre, 1=højre, 2=center)",												// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"lav horisontal scrollbar",																			// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"lav vertikal scrollbar",																			// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"udveksl farver",																					// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"første farve",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"anden farve",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"erstat farve",																						// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"gammel farve",																						// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"ny farve",																							// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"print billede",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"objekt med reduceret detalje niveau (-1=ingen)",													// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"afstand for detalje niveau reduktion",																// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"tilføj mønstre til morfning (-1=reset)",															// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"morfnings scene (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"linse skin",																						// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dynamic data exchange DDE",																		// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"server navn/liste over servere",																	// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"emne navn/liste over emner",																		// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"indsæt navn/liste over indsættelser",																// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"program leverer indsættelse (det er server)",														// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"type indsæt (0 til 7, -1=invalid indsæt)",															// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) nummer",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) flag",																							// pøíznak DDE
IDF_DDE_TEXT,				"(2) tekst",																						// text DDE
IDF_DDE_ICON,				"(3) genstand",																						// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) billede",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) lyd",																							// zvuk DDE
IDF_DDE_MUSIC,				"(6) musik",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"kommando at afvikle",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL biblioteker",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"indlæs bibliotek",																					// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"frit bibliotek",																					// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"importer funktion",																				// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"biblioteksindentifikator",																			// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"funktions navn",																					// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"antal parametere",																					// poèet parametrù importované funkce
IDF_DLL_EXEC,				"afvikl funktion",																					// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"lav hukommelsesblok",																				// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"fri hukommelsesblok",																				// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"ændr størrelse på hukommelsesblok",																// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"hukommelsesblok adresse",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"ny størrelse",																						// nová velikost bloku pamìti
IDF_MEMORY_READ,			"læs peger",																						// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"skriv peger",																						// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"data kopi",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"data sammenligning",																				// porovnání bloku dat
IDF_MEMORY_BYTES,			"byte med markør",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"byte uden markør",																					// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"ord med markør",																					// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"ord uden makør",																					// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-byte med markør",																				// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-byte uden markør",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"dobbeltord med markør",																			// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"dobbeltord uden markør",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"decimal nummer 4 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"decimal nummer 8 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logisk værdi",																						// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"tekst afsluttet af null",																			// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"peger til tekst afsluttet af null",																// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"tekst med fast længde",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"længde af tekst med fast længde",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"læs data fra fil",																					// ètení dat ze souboru
IDF_MEMORY_SAVE,			"skriv data til fil",																				// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identifikator til vindueselement",																	// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"kalder konversion C",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"lav tabs",																							// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"konfiguration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"konfigurations fil",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"parameter sektion",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"parameter navn",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"læs/skriv tekst parameter",																		// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"læs/skriv integer parameter",																		// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"nøgle gruppe (1=CURRENT_USER, 2=LOCAL_MACHINE)",													// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"nøgle navn",																						// plnı mázev klíèe registrù
IDF_REG_VALUE,				"indsæt navn",																						// název datové poloky
IDF_REG_STRING,				"læs/skriv tekst indsæt",																			// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"læs/skriv integer indsæt",																			// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"lav 3D objekt fra hukommelsesblok",																// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"antal diagonaler",																					// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"diagonaler",																						// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normaler (0=auto)",																				// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"tekstur mapning (0=ingen)",																		// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"farver (0=ingen)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"antal sider",																						// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"sider",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"tekstur fra fil",																					// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"hukommelsesblok fra 3D objekt",																	// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"find barn (-1=første, -2=forældre)",																// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
