// Bulharsky (Bulgaria)
// 1251
// [0] Rùzné texty
IDN_MAINFRAME,				"Ï¸òğ",																								// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Îáùèå ïåğåìåííûå è ôóíêöèè",																		// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Ìåñòíûå ïåğåìåííûå è ôóíêöèè",																		// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Îñíîâíûå ıëåìåíòû, êîğçèíà",																		// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Áèáëèîòåêà ïåğåìåííûõ è ôóíêöèé",																	// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"îñíîâíûå ïåğåìåííûå è ôóíêöèè",																	// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Íîâàÿ ïğîãğàììà",																					// implicitní název nového programu
IDN_NEWDIR_NAME,			"Íîâàÿ ñîñòàâëÿşùàÿ",																				// implicitní název nové sloky
IDN_TEXTVZOR,				"[ïğèìåğû]",																						// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Óïîòğåáëåíî",																						// zobrazuje poèet pouití prvku
IDT_RADEK,					"ñòğ",																								// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"ïîç",																								// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"âêëş÷åíî",																							// text editoru hodnoty pøepínaèe
IDN_DATUM,					"äàòà",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"âğåìÿ",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"ğàçìåğ",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"ñâîáîäíî",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"ÊÁ",																								// oznaèení "Kilobajty"
IDN_MB,						"ÌÁ",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"ïîâòîğåíèå",																						// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV)
IDN_OPAKOVANE,				"ïîâòîğåíî",																						// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV)
IDN_DEMO,					"ÄÅÌÎ",																								// oznaèení DEMOverze
IDN_PROFI,					"Ïğîôåññèîíàëü",																					// oznaèení verze Professional
IDN_LITE,					"Lite",																						// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Ñîáğàíèå",																						// volba k vyvolání menu "Soubor"
IDN_START0,					"Ñ&òàğò\tF5",																						// volba pro spuštìní programu
IDN_START,					"Ñïóñòèò ïğîãğàììó.\nÑòàğò",																		// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Îòêğûòü\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Îòêğûåò ïğîãğàììó äëÿ îáğàáîòêè.\nÎòêğûòü",														// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Íîâûé...\tCtrl+N",																				// volba pro zaloení nového programu
IDN_NEW,					"Ñîçäàåò íîâóş ïğîãğàììó.\nÍîâûé",																	// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"Ïåğåè&ìåíîâàòü...\tAlt+Enter",																		// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Èçìåíèò èìÿ ïğîãğàììè/ñîñòàâëÿşùåé (íåâîçìîæíî ïåğåèìåíîâàòü ïğèìåğíûå ïğîãğàììè è ñîñòàâëÿşùèå).\ntÏåğåèìåíîâàòü",	// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"Êîïè&ğîâàòü...\tCtrl+C",																			// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Êîïèğóåò èçáğàííóş ïğîãğàììó ïîä äğóãîå èìÿ.\nÊîïèğîâàòü",											// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"Íîâàÿ &ñîñòàâëÿşùàÿ...\tCtrl+P",																	// volba k vytvoøení nové sloky
IDN_PATH,					"Ñîçäàåò íîâóş ñîñòàâëÿşùóş äëÿ ïğîãğàììè.\nÍîâàÿ ñîñòàâëÿşùàÿ",									// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Ñòåğåòü...\tDelete",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Ñòåğåò ïğîãğàììó èëè ñîñòàâëÿşùóş (íåâîçìîæíî ñòåğåòü ïğèìåğíûå ïğîãğàììè è ñîñòàâëÿşùèå).\nÑòåğåòü",	// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Krátká j&ména",																					// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Programy a soubory knihovny bude vytváøet s jmény zkrácenımi na 8 znakù.\nKrátká jména",			// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Êîíåö\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Îêîí÷èò àïïëèêàöèş Ï¸òğ.\nÊîíåö",																	// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"&Ïèñüìî",																							// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Ïèñüìî &âûáîğó ïğîãğàìì...",																		// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Íàñòàâè âèä ïèñüìà â îêíå âûáîğó ïğîãğàìì.\nÏèñüìî âûáîğó ïğîãğàìì",								// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Ïèñüìî &ıäèòîğà ïğîãğàììè...",																		// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Íàñòàâè âèä ïèñüìà â îêíàõ ıäèòîğà ïğîãğàììè.\nÏèñüìî ıäèòîğà ïğîãğàììè",							// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Ïèñüìî ıäèòîğà &òåêñòó...",																		// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Íàñòàâè âèä ïèñüìà â îêíå ıäèòîğà òåêñòó.\nÏèñüìî ıäèòîğà òåêñòó",									// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Ïèñüìî &ìåíş...",																					// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Íàñòàâè âèä ïèñüìà ìåíş.\nÏèñüìî ìåíş",															// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Ïèñüìî &ñîñòîÿíåãî áàãåòà...",																		// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Íàñòàâè âèä ïèñüìà ñîñòîÿíåãî áàãåòà.\nÏèñüìî ñîñòîÿíåãî áàãåòà",									// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&ßçûê",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Àâòîìàòè÷åñêè",																					// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Èçáåğå ÿçûê àâòîìàòè÷åñêè ïî óñòàíîâêè ñèñòåìà.\nÀâòîìàòè÷åñêè",									// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Pøedcházející\tCtrl+F9",																			// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Pøepíná mezi dvìma naposledy zvolenımi jazyky.\nPøedcházející",									// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Bulgarian (Bulgarija)",																			// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Switches Peter application to the Bulgarian language.\nBulgarian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"Ïî-&÷åøñêè (Ñesky)",																				// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà ÷åøñêèé ÿçûê.\nÏî-÷åøñêè",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"Dánsky (Danmark)",																					// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Pøepne aplikaci Petr na dánskı jazyk.\nDánsky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"Ïî-&ãåğìàíñêè (Deutsch)",																			// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà ãåğìàíñêèé ÿçûê.\nÏî-ãåğìàíñêè",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Øecky (Hellás)",																					// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Pøepne aplikaci Petr na øeckı jazyk.\nØecky",														// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"Ïî-àíã&ëèéñêè (English)",																			// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà àíãëèéñêèé ÿçûê.\nÏî-àíãëèéñêè",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"Ïî-&èñïàíñêè  (Espana)",																			// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà èñïàíñêèé ÿçûê.\nÏî-èñïàíñêè",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finsky (Finland)",																					// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Pøepne aplikaci Petr na finskı jazyk.\nFinsky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"Ïî-&ôğàíöóçñêè (France)",																			// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà ôğàíöóçñêèé ÿçûê.\nÏî-ôğàíöóçñêè",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"Maïarsky (Magyar)",																				// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Pøepne aplikaci Petr na maïarskı jazyk.\nMaïarsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Islandsky (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Pøepne aplikaci Petr na islandskı jazyk.\nIslandsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Ïî-&èòàëüÿíñêè (Italy)",																			// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà èòàëüÿíñêèé ÿçûê.\nÏî-èòàëüÿíñêè",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Holandsky (Nederland)",																			// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Pøepne aplikaci Petr na holandskı jazyk.\nHolandsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Norsky (Norge)",																					// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Pøepne aplikaci Petr na norskı jazyk.\nNorsky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Ïî-&ïîëüñêè (Po polsku)",																			// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà ïîëüñêèé ÿçûê.\nÏî-ïîëüñêè",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portugalsky (Portugal)",																			// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Pøepne aplikaci Petr na portugalskı jazyk.\nPortugalsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Romanian (România)",																				// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Switches Peter application to the Romanian language.\nRomanian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&ğóññêè",																							// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Pøepne aplikaci Petr na ruskı jazyk.\nRusky",														// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Serbo-Croat (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Switches Peter application to the Serbo-Croat language.\nSerbo-Croat",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"Ïî-&ñëîâàöêè (Slovensky)",																			// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Ïåğåêëş÷è àïïëèêàöèş Ï¸òğ íà ñëîâàöêèé ÿçûê.\nÏî-ñëîâàöêè",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albanian (Shqipërisë)",																			// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Switches Peter application to the Albanian language.\nAlbanian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Švédsky (Swerige)",																				// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Pøepne aplikaci Petr na švédskı jazyk.\nŠvédsky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Turecky (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Pøepne aplikaci Petr na tureckı jazyk.\nTurecky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"Vietnamese (Vietnamese)",																				// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Pomoc",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Nápovìda\tF1",																					// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Zobrazí nápovìdu pro vybranı prvek.\nNápovìda",													// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"&Témata nápovìdy",																					// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Zobrazí témata nápovìdy.\nTémata nápovìdy",														// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Hledat v nápovìdì",																				// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Vyhledává v nápovìdì.\nHledat v nápovìdì",															// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"&O aplikaci Petr",																					// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Zobrazí informace o aplikaci Petr, èíslo verze a copyright.\nO aplikaci Petr",						// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Zavøít\tCtrl+O",																					// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Zavøe editovanı program a otevøe jinı.\nZavøít",													// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Uloit\tCtrl+S",																					// volba k uloení programu pøi editaci
IDN_SAVE,					"Uloí zmìny provedené v programu.\nUloit",														// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"Uloit &nespustitelnì\tCtrl+Alt+S",																// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Uloí program nespustitelnı (menší velikost).\nUloit nespustitelnì",								// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Uloit &jako...\tCtrl+Shift+S",																	// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Uloí program do souboru jiného jména nebo na jinı disk.\nUloit jako",							// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribuce...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Uloí distribuèní needitovatelnou verzi programu (pouze u licence Professional).\nDistribuce",		// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Ex&port...",																						// volba k exportování programu
IDN_EXPORT,					"Exportuje program do textového tvaru.\nExport",													// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Importuje program z textového tvaru.\nImport",														// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"Úpr&avy",																							// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Zpìt\tCtrl+Z",																					// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Navrátí poslední provedenou zmìnu.\nZpìt",															// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Odvolat\tCtrl+Y",																					// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Odvolá navrácení provedené zmìny.\nOdvolat",														// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"&Vyjmout\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Vyjme vybranou èást a uloí ji do schránky.\nVyjmout",												// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Kopie\tCtrl+C",																					// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Zkopíruje vybranou èást do schránky.\nKopie",														// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"V&loit\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Navrátí obsah schránky a vloí ho na aktuální pozici.\nVloit",									// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"Z&rušit\tDelete",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Zruší vybranou èást.\nZrušit",																		// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Vybr&at vše\tCtrl+A",																				// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Vybere vše.\nVybrat vše",																			// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Pøi importu a zmenšování obrázkù pouije dithering.\nDithering",									// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Zobrazení",																						// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"Z&vìtšit\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Zvìtší mìøítko zobrazení.\nZvìtšit",																// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Z&menšit\tCtrl+[-]",																				// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Zmenší mìøítko zobrazení.\nZmenšit",																// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"&Pøedešlá editace\tCtrl+nahoru",																	// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Navrátí k pøedešlému editovanému prvku.\nPøedešlá editace",										// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"&Následující editace\tCtrl+dolù",																	// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Navrátí k následujícímu editovanému prvku.\nNásledující editace",									// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Hledání textu...\tCtrl+F",																		// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Nalezne zadanı text.\nHledání textu",																// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"&Zpìtnì text\tShift+F3",																			// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Nalezne pøedešlı vıskyt hledaného textu.\nZpìtnì text",											// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"&Další text\tF3",																					// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Nalezne další vıskyt hledaného textu.\nDalší text",												// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"P&rogram",																							// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Zamknout",																						// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Uzamkne prvek proti modifikaci.\nZamknout",														// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Vypnout",																							// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Vypne funkci prvku.\nVypnout",																		// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Popis\tAlt+Enter",																				// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Edituje popis prvku.\nPopis",																		// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Implicitní p&opis",																				// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Pouije implicitní popis prvku.\nImplicitní popis",												// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Ikona",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Edituje ikonu prvku.\nIkona",																		// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Implicitní i&kona",																				// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Pouije implicitní ikonu prvku.\nImplicitní ikona",												// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"&Deklarace",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Nalezne deklaraci prvku.\nDeklarace",																// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"Pø&edešlé pouití",																				// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Nalezne pøedešlé pouití prvku.\nPøedešlé pouití",												// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"D&alší pouití",																					// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Nalezne další pouití prvku.\nDalší pouití",														// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Obrázek",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"Roz&mìry...",																						// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Nastaví celkové rozmìry.\nRozmìry",																// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Rastr",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Zapne nebo vypne zobrazení orientaèního rastru.\nRastr",											// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"Úpr&avy...",																						// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Upraví obrázek nebo jeho èást (zmìna velikosti, otáèení, barvy).\nÚpravy",							// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Otisk bloku",																						// volba k otisku bloku do obrázku
IDN_OTISK,					"Otiskne blok do obrázku.\nOtisk bloku",															// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horizontálnì",																					// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Pøevrátí obrázek nebo jeho èást horizontálnì.\nHorizontálnì",										// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertikálnì",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Pøevrátí obrázek nebo jeho èást vertikálnì.\nVertikálnì",											// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"V&levo",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Otoèí obrázek doleva (o 90 stupòù proti smìru hodinovıch ruèièek).\nVlevo",						// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"V&pravo",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Otoèí obrázek doprava (o 90 stupòù ve smìru hodinovıch ruèièek).\nVpravo",							// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"&Dvojnásobek",																						// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Zvìtší velikost obrázku nebo jeho èásti na dvojnásobek.\nDvojnásobek",								// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"Polov&ina",																						// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Zmenší velikost obrázku nebo jeho èásti na polovinu.\nPolovina",									// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"V&elikost...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Zmìní velikost obrázku nebo jeho èásti volitelnì.\nVelikost",										// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"&Zámìna",																							// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Zamìní v obrázku nebo jeho èásti barvy levého a pravého tlaèítka myši.\nZámìna",					// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Náhrada",																							// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Nahradí v obrázku nebo jeho èásti barvu pravého tlaèítka myši barvou levého tlaèítka.\nNáhrada",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Nástroje",																						// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Pero",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Kreslí pomocí pera.\nPero",																		// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"Èá&ra",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Kreslí èáru.\nÈára",																				// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"Ob&délník",																						// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Kreslí obdélník.\nObdélník",																		// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"&Vyplnìnı obdélník",																				// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Kreslí vyplnìnı obdélník.\nVyplnìnı obdélník",														// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Krunice",																						// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Kreslí krunici.\nKrunice",																		// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Kru&h",																							// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Kreslí kruh.\nKruh",																				// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Elipsa",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Kreslí elipsu.\nElipsa",																			// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"&Ovál",																							// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Kreslí ovál.\nOvál",																				// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"Ko&ule",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Kreslí kouli.\nKoule",																				// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"Vı&bìr",																							// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Oznaèí zvolenou èást jako vybranou.\nVıbìr",														// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"&Sprej",																							// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Kreslí pomocí spreje.\nSprej",																		// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"K&apátko",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Nastaví barvu pod kurzorem jako vybranou.\nKapátko",												// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"Vıp&lò",																							// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Vyplní plochu barvou.\nVıplò",																		// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Text",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Vypíše text.\nText",																				// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Tlouška",																						// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Tlouška èar &1 bod",																				// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Kreslí èáry tloušky 1 bod.\nTlouška èar 1 bod",													// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Tlouška èar &2 body",																				// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Kreslí èáry tloušky 2 body.\nTlouška èar 2 body",												// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Tlouška èar &5 bodù",																				// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Kreslí èáry tloušky 5 bodù.\nTlouška èar 5 bodù",												// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Tlouška èar &9 bodù",																				// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Kreslí èáry tloušky 9 bodù.\nTlouška èar 9 bodù",												// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Tlouška èar 21 &bodù",																			// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Kreslí èáry tloušky 21 bodù.\nTlouška èar 21 bodù",												// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"P&locha",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Editace",																							// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Zapne nebo vypne mód editace políèek plochy.\nEditace",											// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Vıplò",																							// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Zapne nebo vypne mód vıplnìní plochy políèkem.\nVıplò",											// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Pøedmìty",																						// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Editace pøedmìtù na ploše.\nPøedmìty",																// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Pøepínaè &1",																						// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Editace pøepínaèe 1.\nPøepínaè 1",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Pøepínaè &2",																						// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Editace pøepínaèe 2.\nPøepínaè 2",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Pøepínaè &3",																						// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Editace pøepínaèe 3.\nPøepínaè 3",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Pøepínaè &4",																						// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Editace pøepínaèe 4.\nPøepínaè 4",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Pøepínaè &5",																						// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Editace pøepínaèe 5.\nPøepínaè 5",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"Èí&slo 1",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Editace èíselné hodnoty 1 (rozsah 0 a 1023).\nÈíslo 1",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"Èís&lo 2",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Editace èíselné hodnoty 2 (rozsah 0 a 1023).\nÈíslo 2",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Èísl&o 3",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Editace èíselné hodnoty 3 (rozsah 0 a 127).\nÈíslo 3",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"Sp&rajt",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Vlastnosti",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Nastaví vlastnosti sprajtu (poèet fází, smìrù, ...).\nVlastnosti",									// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Spustí mód testu sprajtu.\nTest",																	// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"Zv&uk",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Pøehrát",																							// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Spustí pøehrávání.\nPøehrát",																		// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"P&ozastavit",																						// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pozastaví pøehrávání.\nPozastavit",																// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"Za&stavit",																						// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Zastaví pøehrávání.\nZastavit",																	// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"Opa&kovanì",																						// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Zapne nebo vypne opakování pøehrávání.\nOpakovanì",												// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Nahrát",																							// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Spustí nahrávání.\nNahrát",																		// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Hudba",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Zpìt",																							// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Posune pøehrávání o 10 sekund zpìt.\nZpìt",														// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Vpøed",																							// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Posune pøehrávání o 10 sekund vpøed.\nVpøed",														// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"O aplikaci Petr",																					// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Petr verze",																						// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Miroslav Nemecek",														// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Ronov pod Radhoštìm",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Èeská republika",																					// Èeská Republika
IDC_DEMOTEXT1,				"Demoverze neumoòuje ukládání programù ani spouštìní",												// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"novıch èi zmìnìnıch programù. Editaèní monosti,",													// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"nápovìda a ukládání do knihovny jsou plnì funkèní.",												// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Aktuální informace o produktu získáte na internetovské adrese:",									// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Objednávky je moné zasílat na adresu:",															// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENCE",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"neomezená",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"pro 1 poèítaè",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"poèítaèe",																							// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"poèítaèù",																							// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Lite version of the Peter provides limited programmatic equipment",								// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(unfunctional elements are marked by grayed icons). Lite version",									// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"is FREEWARE and may be distributed and used freely for private",									// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"purposes. For commercial uses and for schools the license payment",								// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"is required by further specifications on the address www.gemtree.com.",							// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Hledání textu",																					// titulek okna hledání textu
IDN_FINDTEXT,				"Zadejte hledanı text:",																			// vızva k zadání textu k hledání
IDN_CANCEL0,				"Storno",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Rozmìry plochy",																					// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Šíøka:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Vıška:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Nelze otevøít",																					// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"Program nelze otevøít.",																			// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Zøejmì je ji otevøen jinım programem",															// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"nebo je pøístup k souboru zakázán.",																// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Chyba ètení",																						// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Chyba pøi ètení programu.",																		// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"Program je poškozen nebo byl vytvoøen vyšší",														// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"verzí editoru a nemusí proto správnì fungovat.",													// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Unsupported Commands",																				// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Warning: The program uses commands which are not",													// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"supported by the Lite version of the Peter application.",											// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"By saving the program it can become unfunctional.",												// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Úpravy obrázku nebo jeho vybrané èásti",															// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Pøevrácení",																						// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horizontálnì",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertikálnì",																						// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Otoèení",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 stupòù)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 stupòù)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 stupòù)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 stupòù)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 stupòù)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 stupòù)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 stupòù)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 stupòù)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 stupòù)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 stupòù)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 stupòù)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 stupòù)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Zvìtšení",																							// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Dvojnásobek",																						// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Polovina",																							// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Volitelné",																						// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Barvy",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Levé <-> pravé tlaèítko",																			// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Levé -> pravé tlaèítko",																			// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Rozmìry obrázku",																					// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"rozmìry udány",																					// nadpis rámeèku volby jednotky
IDC_KROK,					"v &krocích",																						// [1] volba jednotky v krocích
IDC_BOD,					"v &bodech",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Zmìna velikosti obrázku nebo jeho èásti",															// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"souèasné rozmìry:",																				// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"krokù",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"bodù",																								// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"nové rozmìry",																						// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"šíøka:",																							// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"vıška:",																							// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"v krocích",																						// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"v bodech",																							// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"v procentech",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"zachovat pùvodní pomìr stran (pomìr šíøka/vıška)",													// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"zjemnit hrany (pøesnı, ale pomalı pøevod)",														// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"dithering (zapnout pro fotografie, vypnout pro kresby)",											// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Vıbìr barvy",																						// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Program nelze vytvoøit",																			// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Program se nepodaøilo vytvoøit.",																	// 1. øádek hlášení
IDN_JINE_JMENO,				"Zkuste jiné jméno.",																				// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Rušení programu",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Opravdu chcete zrušit zvolenı program?",															// 1. øádek hlášení
IDN_SELECT_DEL2,			"VAROVÁNÍ: program ji nebude moné obnovit!",														// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Rušení sloky",																					// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Opravdu chcete zrušit zvolenou sloku?",															// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Sloku nelze zrušit",																				// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Sloku nelze zrušit, pokud není prázdná.",															// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Program nelze zrušit",																				// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"Program nelze zrušit, je chránìn proti zápisu a rušení.",											// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Nová sloka",																						// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Jak se bude nová sloka jmenovat?",																// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Sloku nelze vytvoøit",																			// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Sloku se nepodaøilo vytvoøit.",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Sloka existuje",																					// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Pozor - taková sloka ji existuje.",																// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Program existuje",																					// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Pozor - takovı program ji existuje.",																// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Novı program",																						// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Jak se bude novı program jmenovat?",																// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Kopie programu",																					// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Jak se bude zkopírovanı program jmenovat?",														// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Vlastnosti sprajtu",																				// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"animace",																							// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Prodleva mezi fázemi:",																			// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"milisekund",																						// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Fází na krok (0 = ihned):",																		// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Hladina k zobrazení (0 = pøedmìty):",																// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"poèet obrázkù",																					// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Fází pro klid:",																					// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Fází pro pohyb:",																					// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Smìrù:",																							// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"rozmìr obrázku",																					// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Šíøka obrázku:",																					// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Vıška obrázku:",																					// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Test sprajtu",																						// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Chyba uloení",																					// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"Program nelze uloit.",																			// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Zkontrolujte, zda není spuštìn",																	// 2. øádek hlášení
IDN_WRITEERR3,				"nebo zda není chránìn proti zápisu.",																// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"V pøípadì potøeby ulote program",																	// 4. øádek hlášení
IDN_WRITEERR5,				"do jiného jména èi na jinı disk.",																	// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Program zmìnìn",																					// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Program byl zmìnìn.\nChcete zmìny uloit?",														// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Poloka je pouívána",																				// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Varování - rušená poloka je v programu pouívána.\nJejím zrušením zrušíte i pøípadné podvìtve poloky.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Neobnovitelné rušení",																				// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Varování - rušíte prvek z knihovny.\nZrušení je nenávratné, prvek nebude moné obnovit.",			// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Nedostatek pamìti",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Není dost pamìti k provedení poadované operace!\n\nUvolnìte místo na systémovém disku Windows\npøíp. zkontrolujte nastavení virtuální pamìti Windows.\nProgram se mùe nyní nacházet v nestabilním stavu,\nproto jej, prosím, pokud mono urychlenì ukonèete.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"Lituji, program bude ukonèen z dùvodu nedostatku pamìti!",											// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Poškozená licenèní data",																			// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Licenèní data byla poškozena. Spuste znovu instalátor aplikace Petr pro opravu licenèních dat.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Konec èasovì omezeného provozu",																	// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Ubìhla èasovì omezená doba provozu aplikace Petr.",												// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Blíící se konec èasovì omezeného provozu",														// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"Provoz aplikace Petr je èasovì omezen.\nPoèet zbıvajících dnù do konce provozu:",					// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"Chyba systému",																					// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Nedostatek systémovıch prostøedkù ke spuštìní programu PETER.EXE.",								// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Program poškozen",																					// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Program PETER.EXE poškozen, nelze spustit.",														// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Uloit do jiného souboru",																			// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programy",																							// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Všechny soubory",																					// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Uloit distribuèní verzi programu",																// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Program ji existuje",																				// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Varování - ukládanı soubor tohoto jména ji existuje.\nUkládáte distribuèní needitovatelnou verzi programu\na je-li pøepisovanı program zdrojovım programem,\nbyl by nenávratnì ztracen zdrojovı tvar programu.\nChcete pokraèovat a pøepsat soubor?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Nespustitelnı program",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Tento program byl vytvoøen programovacím nástrojem Petr\n a je nyní uloen v nespustitelné formì.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Nastavení písma",																					// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Vzorek:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Pøíklad háèkù a èárek pro èeskı text.",															// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"standardní písmo",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"tuèné",																							// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"kurzíva",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"podtreno",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"pøeškrtnuto",																						// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"bez patièek",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"s patièkami",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"s pevnou rozteèí",																					// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"vybrat ze seznamu",																				// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Seznam typù písem:",																				// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Vıška:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Šíøka[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Efekty",																							// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Vzhled",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Sloka a jméno k exportu programu",																// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Jméno importovaného programu",																		// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Programy Petra",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"prázdné políèko",																					// prázdnı implicitní pøedmìt
IDF_GROUP,					"skupina",																							// skupina prvkù
IDF_IF,						"podmínìné provedení pøíkazù",																		// záhlaví podmínky
IDF_IF_COND,				"platí-li, e",																						// test podmínky (IF)
IDF_IF_YES,					"potom proveï",																						// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"jinak proveï",																						// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"podmínìné opakování pøíkazù",																		// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"dokud platí",																						// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"opakuj pøíkazy",																					// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"pøeruš opakování",																					// pøerušení smyèky (BREAK)
IDF_MINUS,					"záporné znaménko",																					// záporné znaménko "-" v èísle
IDF_CASE,					"vícestupòové vìtvení pøíkazù",																		// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"pro hodnotu vırazu",																				// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"proveï pøíkazy v pøípadì, e",																		// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"vıraz je roven hodnotì",																			// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"jinak proveï pøíkazy",																				// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"èíselná konstanta",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"exponent",																							// exponent v èísle
IDF_EQU,					"je rovno",																							// podmínka =
IDF_NEQU,					"není rovno",																						// podmínka <>
IDF_EQGR,					"je vìtší nebo rovno",																				// podmínka >=
IDF_EQLT,					"je menší nebo rovno",																				// podmínka <=
IDF_GR,						"je vìtší ne",																						// podmínka >
IDF_LT,						"je menší ne",																						// podmínka <
IDF_AND,					"a souèasnì",																						// logickı souèin
IDF_OR,						"nebo",																								// logickı souèet
IDF_XOR,					"buï anebo (vıhradní nebo)",																		// logickı vıhradní souèet
IDF_NOT,					"neplatí-li, e",																					// logická negace
IDF_ADD,					"souèet",																							// souèet èísel
IDF_SUB,					"rozdíl",																							// rozdíl èísel
IDF_MUL,					"násobek",																							// násobek èísel
IDF_DIV,					"podíl",																							// podíl èísel
IDF_REAL,					"èíslo",																							// èíselná promìnná
IDF_ICON,					"pøedmìt",																							// pøedmìtová promìnná
IDF_SND,					"zvuk",																								// zvuková promìnná
IDF_MUS,					"hudba",																							// hudební promìnná
IDF_FNC,					"funkce",																							// funkce
IDF_MAP,					"plocha",																							// promìnná plochy
IDF_SPRITE,					"sprajt",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"øízení programu - rozšíøení",																		// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"text",																								// textová promìnná
IDF_WINDOWS,				"okna",																								// skupina prvkù pro øízení oken
IDF_PAR,					"vstupní promìnné",																					// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"vıstupní promìnná",																				// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"plocha - rozšíøení",																				// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"seznam",																							// záhlaví seznamu (LIST)
IDF_OPER,					"øízení programu",																					// skupina prvkù pro øízení programu
IDF_KROK,					"krok",																								// Petøík popojít o krok vpøed
IDF_VLEVO,					"vlevo",																							// Petøík otoèit doleva
IDF_VPRAVO,					"vpravo",																							// Petøík otoèit doprava
IDF_VZAD,					"vzad",																								// Petøík otoèit vzad
IDF_PETRIK,					"Petøík",																							// skupina prvkù Petøíka
IDF_BOOL,					"pøíznak",																							// logická promìnná
IDF_TEXT_CONST,				"textová konstanta",																				// textová konstanta
IDF_TRUE,					"ano",																								// logickı pøíznak TRUE
IDF_FALSE,					"ne",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucka",																							// skupina prvkù Lucky
IDF_PETRA_KROK,				"krok",																								// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"vlevo",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"vpravo",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"vzad",																								// Lucka otoèit vzad
IDF_RYCHLE,					"viditelnı",																						// viditelnost Petøíka
IDF_EXIT,					"konec funkce",																						// pøerušení funkce
IDF_PETRA_RYCHLE,			"viditelná",																						// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"zvuk a hudba",																						// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"pøedmìt pøed Petøíkem",																			// pøedmìt pøed Petøíkem
IDF_SMER,					"smìr",																								// smìr otoèení Petøíka
IDF_POZICEX,				"horizontální pozice",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"vertikální pozice",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"pøedmìt pøed Luckou",																				// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"smìr",																								// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"horizontální pozice",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"vertikální pozice",																				// vertikální souøadnice Lucky
IDF_CONST,					"vıpoèty",																							// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"aritmetické operace",																				// skupina èíselnıch operátorù
IDF_FUNC,					"funkce",																							// skupina èíselnıch funkcí
IDF_POROVNANI,				"porovnání",																						// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logické operace",																					// skupina logickıch prvkù
IDF_MOD,					"modulo",																							// èíselnı operátor modulo
IDF_SIN,					"sinus",																							// funkce sinus
IDF_COS,					"cosinus",																							// funkce kosinus
IDF_TG,						"tangens",																							// funkce tangens
IDF_COTG,					"cotangens",																						// funkce kotangens
IDF_ARCSIN,					"arcus sinus",																						// funkce arcus sinus
IDF_ARCCOS,					"arcus cosinus",																					// funkce arcus kosinus
IDF_ARCTG,					"arcus tangens",																					// funkce arcus tangens
IDF_ARCCOTG,				"arcus cotangens",																					// funkce arcus kotangens
IDF_PI,						"Ludolfovo èíslo",																					// Ludolfovo èíslo (pí)
IDF_INTEGER,				"celoèíselná èást",																					// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"desetinná èást",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"absolutní hodnota",																				// funkce absolutní hodnoty
IDF_SQRT,					"druhá odmocnina",																					// funkce druhá mocnina
IDF_FACT,					"faktoriál",																						// funkce faktoriál
IDF_RAND,					"náhodné èíslo (0 <= x < 1)",																		// náhodné èíslo
IDF_EUL,					"Eulerova konstanta",																				// Eulerova konstanta (e)
IDF_DEGRAD,					"pøevod stupòù na radiány",																			// funkce konverze stupòù na radiány
IDF_RADDEG,					"pøevod radiánù na stupnì",																			// funkce konverze radiánù na stupnì
IDF_LOG,					"dekadickı logaritmus",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"pøirozenı logaritmus",																				// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"pøirozenı exponent",																				// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"mocnina",																							// operátor mocniny
IDF_UHEL,					"úhel, smìr",																						// skupina úhlù (smìrù)
IDF_UHEL0,					"vpravo (0 pi, tj 0 stupòù)",																		// smìr vpravo
IDF_UHEL45,					"vpravo nahoru (1/4 pi, tj. 45 stupòù)",															// smìr vpravo nahoru
IDF_UHEL90,					"nahoru (1/2 pi, tj. 90 stupòù)",																	// smìr nahoru
IDF_UHEL135,				"vlevo nahoru (3/4 pi, tj. 135 stupòù)",															// smìr vlevo nahoru
IDF_UHEL180,				"vlevo (1 pi, tj. 180 stupòù)",																		// smìr vlevo
IDF_UHEL225,				"vlevo dolù (1 1/4 pi, tj. 225 stupòù)",															// smìr vlevo dolù
IDF_UHEL270,				"dolù (1 1/2 pi, tj. 270 stupòù)",																	// smìr dolù
IDF_UHEL315,				"vpravo dolù (1 3/4 pi, tj. 315 stupòù)",															// smìr vpravo dolù
IDF_COMMAND,				"ovládání",																							// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"èekání (bez zadání = 0.05 s)",																		// pøíkaz pro èekání
IDF_KLAV,					"klávesnice",																						// skupina ovládání klávesnice
IDF_KLAV_TEST,				"je stisknuta klávesa",																				// test stisknuté klávesy
IDF_KLAV_VKEY,				"vstup klávesy (neèeká na stisk)",																	// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"vstup znaku (neèeká na stisk)",																	// vstup znaku bez èekání
IDF_KLAV_VK,				"klávesy",																							// skupina kódù kláves
IDF_KLAV_FX,				"funkèní klávesy",																					// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"písmena",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numerická klávesnice",																				// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"znakové klávesy",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"øídicí klávesy",																					// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"transparency",																						// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0	Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1	End",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2	dolù",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3	PgDn",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4	vlevo",																							// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6	vpravo",																							// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7	Home",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8	nahoru",																							// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9	PgUp",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			".	Del",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1	!",																								// kód klávesy 1 !
IDF_VK_2,					"2	@",																								// kód klávesy 2 @
IDF_VK_3,					"3	#",																								// kód klávesy 3 #
IDF_VK_4,					"4	$",																								// kód klávesy 4 $
IDF_VK_5,					"5	%",																								// kód klávesy 5 %
IDF_VK_6,					"6	^",																								// kód klávesy 6 ^
IDF_VK_7,					"7	&",																								// kód klávesy 7 &
IDF_VK_8,					"8	*",																								// kód klávesy 8 *
IDF_VK_9,					"9	(",																								// kód klávesy 9 (
IDF_VK_0,					"0	)",																								// kód klávesy 0 )
IDF_VK_LCARKA,				"`	~",																								// kód klávesy ` ~
IDF_VK_POMLCKA,				"-	_",																								// kód klávesy - _
IDF_VK_ROVNITKO,			"=	+",																								// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\  |",																							// kód klávesy \ |
IDF_VK_LLOMENA,				"[	{",																								// kód klávesy [ {
IDF_VK_RLOMENA,				"]	}",																								// kód klávesy ] }
IDF_VK_STREDNIK,			";	:",																								// kód klávesy ; :
IDF_VK_RCARKA,				"\'  \"",																							// kód klávesy ' "
IDF_VK_CARKA,				",	<",																								// kód klávesy , <
IDF_VK_TECKA,				".	>",																								// kód klávesy . >
IDF_VK_LOMITKO,				"/	?",																								// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"menu Windows vlevo",																				// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Back Space",																						// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"lokální menu",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"vlevo",																							// kód klávesy Vlevo
IDF_VK_RIGHT,				"vpravo",																							// kód klávesy Vpravo
IDF_VK_UP,					"nahoru",																							// kód klávesy Nahoru
IDF_VK_DOWN,				"dolù",																								// kód klávesy Dolù
IDF_VK_INSERT,				"Insert",																							// kód klávesy Insert
IDF_VK_DELETE,				"Delete",																							// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"End",																								// kód klávesy End
IDF_VK_PAGEUP,				"Page Up",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Page Down",																						// kód klávesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"Shift vlevo",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"Ctrl vlevo",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"Alt vlevo",																						// kód klávesy Levı Alt
IDF_VK_SPACE,				"mezera",																							// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"myš",																								// skupina prvkù myši
IDF_MOUSE_L,				"levé tlaèítko myši dreno",																		// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"pravé tlaèítko myši dreno",																		// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"pozice myši v horizontálním smìru",																// horizontální souøadnice myši
IDF_MOUSE_Y,				"pozice myši ve vertikálním smìru",																	// vertikální souøadnice myši
IDF_EQU_TEXT,				"shodnost textù",																					// operátor porovnání textù
IDF_EQU_ICO,				"shodnost pøedmìtù",																				// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"sprajty - rozšíøení",																				// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"okno má okraj",																					// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"okno má titulek",																					// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"parametry programu",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"návratovı kód",																					// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"obrázek",																							// promìnná obrázku
IDF_REPEAT,					"opakování pøíkazù s poètem",																		// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"pro poèet opakování",																				// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"okraj plochy",																						// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horizontálnì",																						// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertikálnì",																						// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"smìr",																								// smìr sprajtu
IDF_SPRITE_MOVE,			"v pohybu",																							// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"viditelnı",																						// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"poèet",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"index",																							// index seznamu
IDF_LIST_AUTO,				"inkrementace indexu",																				// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Petøík - rozšíøení",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucka - rozšíøení",																				// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"èíselná hodnota 1 (rozsah 0 a 1023)",																// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"èíselná hodnota 1 (rozsah 0 a 1023)",																// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"èíselná hodnota 2 (rozsah 0 a 1023)",																// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"èíselná hodnota 2 (rozsah 0 a 1023)",																// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"èíselná hodnota 3 (rozsah 0 a 127)",																// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"èíselná hodnota 3 (rozsah 0 a 127)",																// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"pøepínaè 1",																						// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"pøepínaè 1",																						// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"pøepínaè 2",																						// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"pøepínaè 2",																						// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"pøepínaè 3",																						// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"pøepínaè 3",																						// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"pøepínaè 4",																						// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"pøepínaè 4",																						// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"pøepínaè 5",																						// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"pøepínaè 5",																						// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"texty",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"levá èást textu",																					// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"délka levé èásti textu",																			// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"pravá èást textu",																					// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"poèátek pravé èásti textu",																		// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"støední èást textu",																				// funkce støední èásti textu
IDF_TEXT_MID_POS,			"poèátek støední èásti textu",																		// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"délka støední èásti textu",																		// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"délka textu",																						// funkce zjištìní délky textu
IDF_TEXT_ADD,				"slouèení textù",																					// operátor pro slouèení textù
IDF_TEXT_SCAN,				"pøevod èísla z textového tvaru",																	// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"pøevod èísla na textovı tvar",																		// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"abecední porovnání textù",																			// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"pøevod na malá písmena",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"pøevod na velká písmena",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"nalezení pozice s textem (-1 = není)",																// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"vstupní text",																						// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"hledanı text",																						// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"informaèní text",																					// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"nadpis okna",																						// titulek hlavního okna (textová promìnná)
IDF_ORD,					"pøevod znaku na èíselnı kód",																		// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"pøevod èíselného kódu na znak",																	// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"zvuk",																								// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"pøehrátí zvuku",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"vypnutí zvuku (bez zadání = vše)",																	// vypnutí zvuku
IDF_COLOR,					"barva",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"grafika",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"barva pera",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"tlouška pera",																					// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"bod",																								// nakreslení grafického bodu
IDF_POINT_X,				"horizontální souøadnice bodu X",																	// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertikální souøadnice bodu Y",																		// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"èára",																								// nakreslení èáry
IDF_LINE_X1,				"horizontální souøadnice èáry X1",																	// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertikální souøadnice èáry Y1",																	// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horizontální souøadnice èáry X2",																	// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertikální souøadnice èáry Y2",																	// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"obdélník",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horizontální souøadnice obdélníku X1",																// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertikální souøadnice obdélníku Y1",																// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horizontální souøadnice obdélníku X2",																// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertikální souøadnice obdélníku Y2",																// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"vyplnìnı obdélník",																				// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horizontální souøadnice vyplnìného obdélníku X1",													// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertikální souøadnice vyplnìného obdélníku Y1",													// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horizontální souøadnice vyplnìného obdélníku X2",													// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertikální souøadnice vyplnìného obdélníku Y2",													// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"vıplò",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horizontální souøadnice vıplnì X",																	// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertikální souøadnice vıplnì Y",																	// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"krunice",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horizontální souøadnice støedu X",																	// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertikální souøadnice støedu Y",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"polomìr",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"kruh",																								// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horizontální souøadnice støedu X",																	// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertikální souøadnice støedu Y",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"polomìr",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"trojúhelník",																						// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horizontální souøadnice trojúhelníku X1",															// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertikální souøadnice trojúhelníku Y1",															// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horizontální souøadnice trojúhelníku X2",															// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertikální souøadnice trojúhelníku Y2",															// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horizontální souøadnice trojúhelníku X3",															// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertikální souøadnice trojúhelníku Y3",															// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"koule",																							// nakreslení koule
IDF_SPHERE_X,				"horizontální souøadnice støedu X",																	// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertikální souøadnice støedu Y",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"polomìr",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"zmìna jasu barvy",																					// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"jas barvy (0 a 1)",																				// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"vstup klávesy (èeká na stisk)",																	// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"vstup znaku (èeká na stisk)",																		// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"ádná klávesa nestisknuta",																		// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"menu Windows vpravo",																				// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Shift vpravo",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"Ctrl vpravo",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"Alt vpravo",																						// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"stav Num Lock",																					// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"stav Caps Lock",																					// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"stav Scroll Lock",																					// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"stav Insert",																						// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"klik levım tlaèítkem myši",																		// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"klik pravım tlaèítkem myši",																		// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"dvojklik levım tlaèítkem myši",																	// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"dvojklik pravım tlaèítkem myši",																	// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"test myši v oblasti",																				// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horizontální souøadnice X poèátku oblasti",														// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertikální souøadnice Y poèátku oblasti",															// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"šíøka oblasti",																					// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"vıška oblasti",																					// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"vıpis textu",																						// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horizontální souøadnice X textu",																	// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertikální souøadnice Y textu",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"úhel orientace textu",																				// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"vıška znakù",																						// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"relativní šíøka znakù (1 = bìná)",																// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"tuènı text",																						// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"kurzíva",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"podtrení",																						// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"pøeškrtnutí",																						// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"patièky",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"psací stroj",																						// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"text k vıpisu",																					// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"poèet øádkù textu",																				// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"øádek textu",																						// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"èíslo øádku textu",																				// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"test zvuku (bez zadání = všechny zvuky)",															// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"poèet opakování (0 = trvale)",																		// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"pøedmìt na pozici s Petøíkem",																		// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"pøedmìt na pozici s Luckou",																		// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"vykreslení obrázku",																				// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"obrázek k vykreslení",																				// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horizontální souøadnice obrázku X",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertikální souøadnice obrázku Y",																	// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horizontální souøadnice vıøezu X",																	// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertikální souøadnice vıøezu Y",																	// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"šíøka vıøezu",																						// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"vıška vıøezu",																						// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"úschova vıøezu z plochy jako obrázek",																// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"úschova vıøezu z plochy jako pøedmìt",																// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"jazyk (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"zvuk k pøehrátí",																					// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"hlasitost zvuku (0 a 1)",																			// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"stereofonní vyváení (-1 = vlevo a +1 = vpravo)",													// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"pøerušit hrající zvuk",																			// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"komentáø",																							// komentáø
IDF_SOUND_FUNCTIONS,		"zvukové funkce",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"nastavení vzhledu kurzoru myši",																	// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"obrázek kurzoru myši (bez zadání = pùvodní)",														// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horizontální souøadnice X poèátku oblasti",														// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertikální souøadnice Y poèátku oblasti",															// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"šíøka oblasti",																					// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"vıška oblasti",																					// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"pøehrátí hudby",																					// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"opakované pøehrávání hudby",																		// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"zastavit pøehrávání hudby",																		// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"pozastavit/pokraèovat v pøehrávání hudby",															// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test pøehrávání hudby",																			// test pøehrávání hudby
IDF_MUSIC_POS,				"pozice v pøehrávání hudby",																		// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"délka pøehrávané hudby",																			// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"slouèení barevnıch sloek do barvy",																// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"èervená sloka (0 a 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"zelená sloka (0 a 1)",																			// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"modrá sloka (0 a 1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"naètení barvy bodu",																				// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horizontální souøadnice X k naètení barvy bodu",													// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertikální souøadnice Y k naètení barvy bodu",														// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"druhá mocnina",																					// funkce druhá mocnina
IDF_MUSIC_GROUP,			"hudba",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"audio CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"pøehrátí CD od zadané stopy (bez zadání = 1)",														// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"zastavení pøehrávání CD",																			// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"pozastavení/pokraèování pøehrávání CD",															// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test pøehrávání CD",																				// test pøehrávání CD
IDF_CD_LENGTH,				"celková délka",																					// celková délka CD
IDF_CD_TRACKS,				"poèet stop",																						// poèet stop CD
IDF_CD_POS,					"pozice od zaèátku",																				// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"pøehrávaná stopa",																					// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"délka pøehrávané stopy",																			// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"pozice od zaèátku stopy",																			// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"soubory",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"základní operace",																					// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"novı soubor",																						// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"novı adresáø",																						// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"zrušení souboru nebo adresáøe",																	// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"test existence",																					// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"aktivní disk a adresáø",																			// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"kapacita disku",																					// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"volné místo disku",																				// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"jmenovka disku",																					// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"sériové èíslo disku",																				// zjištìní sériového èísla disku
IDF_FILE_READ,				"aktivní soubor (adresáø) pro ètení",																// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"aktivní soubor (adresáø) pro zápis",																// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"kopie souboru",																					// provedení kopie souboru
IDF_FILE_MOVE,				"pøesun/pøejmenování souboru (adresáøe)",															// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disk",																								// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"parametry",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"atribut R/O (pouze pro ètení)",																	// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"atribut HID (skrytı)",																				// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"atribut SYS (systémovı)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"atribut DIR (adresáø)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"atribut ARC (archivní)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"atribut TEMP (pøechodnı)",																			// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"atribut COMP (zkomprimovanı)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"atribut OFF (nepøístupnı)",																		// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"datum a èas vytvoøení",																			// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"datum a èas posledního pøístupu",																	// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"datum a èas poslední modifikace",																	// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"data",																								// skupina dat souborù
IDF_FILE_BYTES,				"celé èíslo se znaménkem, 1 bajt",																	// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"celé èíslo bez znaménka, 1 bajt",																	// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"celé èíslo se znaménkem, 2 bajty",																	// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"celé èíslo bez znaménka, 2 bajty",																	// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"celé èíslo se znaménkem, 4 bajty",																	// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"celé èíslo bez znaménka, 4 bajty",																	// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"desetinné èíslo, 4 bajty",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"desetinné èíslo, 8 bajtù",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"text zakonèenı binární nulou (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"text zakonèenı koncem øádku",																		// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"text s pevnou délkou",																				// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"pøedmìt (ICO)",																					// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"obrázek (BMP, JPG)",																				// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"zvuk (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"hudba (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"ukazatel ètení",																					// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"ukazatel zápisu",																					// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"datum a èas",																						// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"aktuální datum a èas (poèet sekund od 1.1.1601)",													// aktuální datum a èas
IDF_DATETIME_UTC,			"pøevod místního èasu na svìtovı",																	// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"pøevod svìtového èasu na místní",																	// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"slouèení poloek data a èasu",																		// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"rok",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"mìsíc",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"den",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"hodina",																							// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minuta",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"sekunda",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"milisekunda",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"rok z data a èasu",																				// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"mìsíc z data a èasu",																				// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"den z data a èasu",																				// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"den v tıdnu z data a èasu (0 = nedìle, 1 = pondìlí, ...)",											// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"hodina z data a èasu",																				// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minuta z data a èasu",																				// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"sekunda z data a èasu",																			// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"milisekunda z data a èasu",																		// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"pøevod data na text \"den.mìsíc.rok\"",															// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"pøevod data na text \"mìsíc/den/rok\"",															// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"pøevod data na text \"rok-mìsíc-den\"",															// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"pøevod èasu na text \"hodina:minuta:sekunda\" (24 hodin)",											// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"pøevod èasu na text \"hodina:minuta:sekunda x\" (12 hodin)",										// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"velikost souboru",																					// velikost souboru
IDF_FILE_ERROR,				"pøíznak chyby operace",																			// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"délka textu s pevnou délkou",																		// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"typ disku (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",														// zjištìní typu disku
IDF_TEXT_FORMAT2,			"pøevod èísla na text - 2 èíslice",																	// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"pøevod èísla na text - 8 èíslic HEX",																// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"celé èíslo se znaménkem, 3 bajty",																	// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"celé èíslo bez znaménka, 3 bajty",																	// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"dialogy",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"potvrzovací dialog (vrací 1=OK, 2=Storno, 3=Pøerušit, 4=Znovu, 5=Ignorovat, 6=Ano, 7=Ne)",			// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"text",																								// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"nadpis",																							// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"ikona (0=nic, 1=chyba, 2=dotaz, 3=varování, 4=informace)",											// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"tlaèítka (0=OK, 1=OK/Storno, 2=Pøerušit/Znovu/Ignorovat, 3=Ano/Ne/Storno, 4=Ano/Ne, 5=Znovu/Storno)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"implicitní tlaèítko (1 a 3)",																		// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"další øádek",																						// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"zadání textu",																						// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1. øádek vızvy",																					// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2. øádek vızvy",																					// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3. øádek vızvy",																					// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"pøednastavenı text k zadání",																		// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"vysunutí CD",																						// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"poèet bitù na vzorek (8 nebo 16)",																	// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"vzorkovací kmitoèet (Hz)",																			// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"je zvuk stereofonní?",																				// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"délka zvuku (sekund)",																				// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"konverze na 8 bitù",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"konverze na 16 bitù",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"konverze na stereo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"konverze na mono",																					// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"konverze na 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"konverze na 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"konverze na 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"slouèení zvukù",																					// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"zmìna rychlosti zvuku",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"zvuk ke konverzi",																					// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relativní zmìna rychlosti (1 = beze zmìny)",														// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"tónovı generátor",																					// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"frekvence tónu (Hz)",																				// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"délka tónu (sekund)",																				// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"plocha",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"šíøka plochy",																						// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"vıška plochy",																						// zjištìní vıšky plochy
IDF_MAP_X,					"souøadnice X",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"souøadnice Y",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"plocha",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"pøedmìt",																							// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"èíselná hodnota 1 (rozsah 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"èíselná hodnota 2 (rozsah 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"èíselná hodnota 3 (rozsah 0 a 127)",																// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"pøepínaè 1",																						// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"pøepínaè 2",																						// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"pøepínaè 3",																						// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"pøepínaè 4",																						// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"pøepínaè 5",																						// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"kopie vıøezu plochy",																				// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"plocha s vıøezem",																					// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"souøadnice X vıøezu",																				// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"souøadnice Y vıøezu",																				// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"šíøka vıøezu",																						// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"vıška vıøezu",																						// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"konzola",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"hromadnı posun sprajtù ve smìru X",																// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"hromadnı posun sprajtù ve smìru Y",																// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"levı okraj okna sprajtù",																			// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"dolní okraj okna sprajtù",																			// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"pravı okraj okna sprajtù",																			// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"horní okraj okna sprajtù",																			// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"reim konzoly (nutno uvést na zaèátku hlavní funkce)",												// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"vıstup textu na konzolu",																			// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"vstup textu z konzoly",																			// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"chybovı vıstup textu na konzolu",																	// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"parametr programu (0 = jméno programu)",															// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"jméno programu s plnou cestou",																	// jméno tohoto programu s plnou cestou
IDF_EXEC,					"spuštìní programu",																				// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"spuštìní programu s èekáním",																		// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"pákovı ovladaè",																					// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"souøadnice X pákového ovladaèe",																	// souøadnice X joysticku
IDF_JOYSTICK_Y,				"souøadnice Y pákového ovladaèe",																	// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"souøadnice Z pákového ovladaèe",																	// souøadnice Z joysticku
IDF_JOYSTICK_1,				"tlaèítko 1 pákového ovladaèe",																		// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"tlaèítko 2 pákového ovladaèe",																		// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"tlaèítko 3 pákového ovladaèe",																		// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"tlaèítko 4 pákového ovladaèe",																		// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"texty a obrázky",																					// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"èíslo prvku (0 = hlavní okno)",																	// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"zrušení prvku nebo okna",																			// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"vytvoøení okna",																					// vytvoøení dialogového okna
IDF_WINDOW_X,				"horizontální souøadnice",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"vertikální souøadnice",																			// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"šíøka",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"vıška",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"text",																								// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"viditelnost",																						// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"zákaz",																							// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"vytvoøení tlaèítka",																				// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"stisk tlaèítka nebo zmìna prvku",																	// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"vytvoøení zaškrtávacího boxu",																		// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"vytvoøení editaèního øádku",																		// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"vytvoøení pøepínaèe",																				// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"spoleèné funkce pro všechny prvky",																// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"vytvoøení editaèního pole",																		// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"tlaèítka",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"pøepínaè zapnut",																					// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"vstupní zamìøení",																					// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"vytvoøení implicitního tlaèítka",																	// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"vytvoøení ikonového tlaèítka",																		// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"vytvoøení rámeèku",																				// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"vytvoøení seznamu",																				// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"vytvoøení textu",																					// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"vytvoøení rozbalovacího seznamu",																	// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"vytvoøení rozbalovacího seznamu s editací",														// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"zvıraznìné písmo",																					// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"písmo s pevnou rozteèí",																			// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"vytvoøení pøepínaèe - zaèátek skupiny",															// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"seznamy",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"pøidání poloky do seznamu",																		// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"vyprázdnìní seznamu",																				// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"vytvoøení seznamu s editací",																		// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"vytvoøení 3-stavového boxu",																		// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"pøepínaè v neurèitém stavu",																		// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"vytvoøení okna bez monosti uzavøení",																// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"ikona",																							// ikona prvku dialogového okna
IDF_WINICON_NEW,			"vytvoøení ikony",																					// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"sprajt (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*Ludolfovo èíslo (= 360 stupòù)",																	// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"vzdálenost 1 bodu (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"fáze",																								// fáze sprajtu
IDF_SPRITE_STATUS,			"stav",																								// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"celoobrazovkovı reim",																			// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"vyprázdnìní zásobníku kláves",																		// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"pozice v pøehrávání zvuku",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"pozastavit/pokraèovat v pøehrávání zvuku",															// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"seznam souborù",																					// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"shodnost ploch",																					// operátor porovnání ploch
IDF_EQU_PIC,				"shodnost obrázkù",																					// operátor porovnání obrázkù
IDF_EQU_SPR,				"shodnost sprajtù",																					// operátor porovnání sprajtù
IDF_EQU_SND,				"shodnost zvukù",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"shodnost hudby",																					// operátor porovnání hudeb
IDF_NET_GROUP,				"sí",																								// skupina pro obsluhu sítì
IDF_DIRECTPLAY_GROUP,		"síová podpora DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"seznam spojení",																					// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"aktivní spojení",																					// aktivní spojení DirectPlay
IDF_GAME_LIST,				"seznam her",																						// seznam bìících her DirectPlay
IDF_GAME_ACT,				"aktivní hra",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"seznam hráèù",																						// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"aktivní hráè",																						// aktivní hráè DirectPlay
IDF_GAME_N1,				"èíselnı parametr hry 1 (-16384 a +16383)",														// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"èíselnı parametr hry 2 (-16384 a +16383)",														// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"èíselnı parametr hry 3 (-16384 a +16383)",														// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"èíselnı parametr hry 4 (-16384 a +16383)",														// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"èíselnı parametr hry 5 (-16384 a +16383)",														// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"èíselnı parametr hry 6 (-16384 a +16383)",														// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"èíselnı parametr hry 7 (-16384 a +16383)",														// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"èíselnı parametr hry 8 (-16384 a +16383)",														// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"pøepínaè hry 1",																					// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"pøepínaè hry 2",																					// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"pøepínaè hry 3",																					// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"pøepínaè hry 4",																					// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"pøepínaè hry 5",																					// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"pøepínaè hry 6",																					// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"pøepínaè hry 7",																					// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"pøepínaè hry 8",																					// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"nastavení hry",																					// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"hostitel (øídicí poèítaè)",																		// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"maximálnì hráèù (0 = neomezeno)",																	// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"èíslo aktivního hráèe (-1 = není)",																// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"data",																								// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"odeslání/pøíjem bloku dat (-1 = všem/není)",														// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"èíslo",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"text",																								// text dat DirectPlay
IDF_GAME_DATAL,				"pøepínaè",																							// pøepínaè dat DirectPlay
IDF_GAME_IP,				"IP adresa tohoto poèítaèe",																		// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"celé èíslo 0 a 255 (bajt)",																		// èíslo bajt dat DirectPlay
IDF_INC,					"inkrementace (pøiète 1)",																			// funkce inkrementace èísla
IDF_DEC,					"dekrementace (odeète 1)",																			// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"vytvoøení textu vystøedìného",																		// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"tlaèítko pro klávesu Esc (-1 = není)",																// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"šíøka obrázku",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"vıška obrázku",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"horizontální pøevrácení obrázku",																	// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"vertikální pøevrácení obrázku",																	// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"obrázky",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"zmìna velikosti obrázku",																			// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"obrázek",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"šíøka (bez zadání = úmìrná k vıšce)",																// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"vıška (bez zadání = úmìrná k šíøce)",																// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"zjemnit hrany",																					// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (fotografie)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"kreslení",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"vytvoøení obrázku",																				// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"obrázek",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"vytvoøení editoru RichEdit",																		// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"vıška znakù (0 = bìná)",																			// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"šikmé písmo",																						// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"podtrené písmo",																					// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"pøeškrtnuté písmo",																				// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"písmo s patièkami",																				// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"relativní šíøka znakù (0 = bìná, 1 = základní)",													// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"úhel sklonu textu",																				// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"vytvoøení textu zarovnaného vpravo",																// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"barva písma",																						// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"barva pozadí",																						// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"písmo prvku",																						// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"rychlost pøehrávání (1 = bìná)",																	// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"distinguish code (0 to 65535)",																		// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"zadání souboru k otevøení",																		// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"zadání souboru k uloení",																			// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"zadání textu k hledání",																			// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"zadání barvy",																						// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"maska souborù",																					// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"pøednastavené jméno souboru",																		// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"název souborù",																					// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"zmìna jasu obrázku",																				// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"obrázek ke zmìnì jasu",																			// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"jas obrázku (1 = bìnı)",																			// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"otoèení obrázku",																					// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"obrázek k otoèení",																				// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"úhel otoèení",																						// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"dekomprese zvuku",																					// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"text je ve formátu UNICODE (2 bajty)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"konverze plochy na obrázek",																		// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"konverze pøedmìtu na obrázek",																		// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"bitové operace",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"bitovı souèin AND",																				// bitovı (binární) souèin AND
IDF_BIT_OR,					"bitovı souèet OR",																					// bitovı (binární) souèet OR
IDF_BIT_XOR,				"bitová inverze XOR",																				// bitová (binární) inverze XOR
IDF_BIT_NOT,				"bitovı doplnìk NOT",																				// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"maximální bitové èíslo (dvojslovo)",																// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"bitová rotace vlevo",																				// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"bitová rotace vpravo",																				// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"test myši v prvku",																				// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"vnitøní šíøka",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"vnitøní vıška",																					// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"znaková sada (1250=støedoevropská, 1251=ruská, 1252=západní)",										// èíslo pouité znakové sady fontù
IDF_USERFONT,				"uivatelskı font",																					// jméno uivatelského fontu
IDF_ENUMFONTS,				"seznam fontù",																						// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"nová plocha",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"šíøka plochy",																						// šíøka nové plochy
IDF_MAP_NEW_H,				"vıška plochy",																						// vıška nové plochy
IDF_WINDOW_TOP,				"vdy nahoøe",																						// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"pøezdívka (alias)",																				// pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"communication port",																				// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"open port (-1=error)",																				// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"close port",																						// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"active port",																						// aktivní port
IDF_COM_NUM,				"number (0 to 255)",																				// vstup/vıstup èísla
IDF_COM_TEXT,				"character (text)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"baud rate",																						// pøenosová rychlost
IDF_COM_STOP,				"2 stop bits",																						// reim s 2 stopbity
IDF_COM_BITS,				"number of bits (5 to 8)",																			// poèet bitù na znak
IDF_COM_PARIT,				"parity (0=none, 1=odd, 2=even)",																	// zvolená parita
IDF_COM_IN,					"character was received",																			// byl pøijatı znak
IDF_COM_SEND,				"sending is allowed (CTS, RTS)",																				// povoleno vysílání
IDF_COM_RECEIVE,			"receiving is allowed (DSR, DTR)",																				// povolen pøíjem
IDF_PICTURE_MASK,			"picture masking",																					// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"picture",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"mask",																								// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"field width to text display (0 = none)",															// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"create edit field without wrap",																	// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"resizable window",																					// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"window may be closed",																				// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"window is maximized",																				// maximalizace okna
IDF_WINDOW_MINIM,			"window is minimized",																				// minimalizace okna
IDF_PROGRESS_NEW,			"create progressbar",																				// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"create horizontal trackbar",																		// vytvoøení dialogového prvku horizontálního táhla (trackbar)
IDF_VTRACKBAR_NEW,			"create vertical trackbar",																			// vytvoøení dialogového prvku vertikálního táhla (trackbar)
IDF_WINDOW_POS,				"actual position",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"mixer",																							// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"mixer device",																						// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"destination line",																					// volba cílového signálu
IDF_MIX_LINE_SRC,			"source line (none=only destination line)",															// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"type of line",																						// zjištìní typu signálu
IDF_MIX_CONTROL,			"control item",																						// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"type of control item",																				// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"value of control item (0 to 1)",																	// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"selection of control item",																		// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"controlled channel (-1=all)",																		// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D graphics",																							// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"3D graphics window",																					// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X coordinate of 3D graphics window",																	// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y coordinate of 3D graphics window",																	// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"width of 3D graphics window",																			// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"height of 3D graphics window",																		// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"videomode (width*height/bits)",																			// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"graphic background",																				// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"settings",																							// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"filling surfaces",																				// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"lighting",																							// mód osvìtlení
IDF_DIRECT3D_SHADES,		"smooth shading",																					// mód stínování
IDF_DIRECT3D_INVERT,		"object inversion",																					// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objects",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"wall",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"cube",																								// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"sphere",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"cylinder",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"cone",																								// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"clone",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"object from text",																					// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"object from file",																					// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"active object (0=scene, 1=camera, 2=light)",														// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"delete object",																					// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"visible",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"link",																								// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"object to file",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformations",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"scale in X direction",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"scale in Y direction",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"scale in Z direction",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"rotation around X-axis",																			// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"rotation around Y-axis",																			// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"rotation around Z-axis",																			// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"translation in X direction",																		// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"translation in Y direction",																		// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"translation in Z direction",																		// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"surface",																							// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"color (-1=internal, -2=default)",																				// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"emissive color",																					// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"dimness (0=off, 5=metal, 50=plastic)",																// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"reflectance color",																				// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"texture",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"texture mapping",																					// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"projection type (0=flat, 1=cylinder, 2=sphere, 3=chrome, 4=lens)",											// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"X coordinate of projection center",																		// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"Y coordinate of projection center",																		// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"Z coordinate of projection center",																		// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"rotation of projection around X-axis",																		// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"rotation of projection around Y-axis",																		// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"rotation of projection around Z-axis",																		// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"transparency (1=normal, 11=fire, 20=glass, 54=overlap)",											// nastavení prùhlednosti
IDF_DIRECT3D_ALPHAREF,		"contours (0=normal, 0.5=contours)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"method (0=addresses, 1=vertices, 2=faces)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"horizontal origin of texture",																		// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"vertical origin of texture",																			// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"horizontal decrease grade of texture",																// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"vertical decrease grade of texture",																// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"lighting",																							// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"create new light",																					// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"light color",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"light type (1=point, 2=spot, 3=directional)",							// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"angle of light cone",																						// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"penumbra angle",																					// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"light range",																						// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"light intensity (1=normal)",																		// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"linear attenuation",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"quadratic attenuation",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"projection type (0=persp, 1=ortho, 2=r-persp, 3=r-ortho)",												// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"scene",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"scene background color (-1=off, -2=no initialization)",											// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"scene background texture",																				// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"fog color (-1=off)",																						// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"fog type (0=lin, 1=exp, 2=quadr, +4=correction)",													// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"start of linear fog",																					// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"end of linear fog",																					// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"density of exp. and quadr. fog (0 to 1)",																// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"distance of projection plane",																		// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"visual range distance",																				// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"create upper base",																				// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"create lower base",																				// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"search object",																				// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"X coordinate of point",																				// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"Y coordinate of point",																				// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"texture minification filter",																			// nastavení filtrace textur
IDF_DIRECT3D_2DOBJECT,		"2D object",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terrain from picture",																	// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"terrain level",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"horizontal coordinate",																	// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"vertical coordinate",																	// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"group",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"complexity of object (2 to 100)",																	// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"order of rotations (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",									// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"driver (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",											// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"rotary object",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terrain from sheet",																	// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"reflection of ambient light (-1=default)",														// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"program is active application",																		// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"distance of point",																					// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"angle of point",																						// vıpoèet úhlu bodu
IDF_POLAR_X,				"X coordinate of point",																				// souøadnice X bodu
IDF_POLAR_Y,				"Y coordinate of point",																				// souøadnice Y bodu
IDF_FILE_LOGIC,				"logical value",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"smoothing of textures (1=no)",																	// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"precise time counter",																				// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"ambient light",																				// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"texture magnification filter",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"faraway texture filter",																		// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"filling object surfaces",																			// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"object lighting",																				// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"object smooth shading",																		// mód stínování
IDF_DIRECT3D_OMINFILTER,	"object texture minification filter",															// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"object texture magnification filter",															// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"faraway object texture filter",																// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"visible object side (0=both, 1=front, 2=back)",												// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"create",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"object normalization",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"circle",																								// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"triangle",																							// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"torus (parameter = diameter 0 to 1)",																// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"static 2D object",																					// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"hemisphere",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interface (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",						// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"elapsed time",																						// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"rendering speed",																				// rychlost renderování
IDF_DIRECT3D_FREE,			"free videomemory",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D picture",																						// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"textures",																							// skupina textur
IDF_DIRECT3D_STAGE,			"stage (0 to 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"color operation (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",											// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"first color argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"second color argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"alpha operation (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"first alpha argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"second alpha argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"horizontal addressing mode (1=repeat, 2=mirror, 3=clamp)",									// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"vertical addressing mode (1=repeat, 2=mirror, 3=clamp)",									// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"blurring of faraway textures (0=default)",																// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"truncated cone (parameter = diameter 0 to 1)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"color of texture factor",																			// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alpha component (0=transparency to 1=color)",															// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"number of faraway textures (0=all)",																// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"render group (0-7=objects, 8-11=transparent, 12-15=pictures)",										// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"depth sort render group",																			// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"write depth information",																			// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"depth test (1 never, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 always)",									// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"calculate normals (parameter = angle for smoothing)",												// pøepoèet normál
IDF_DIRECT3D_RENDER,		"render without displaying",																		// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"text block",																						// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"line of the block beginning",																		// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"position of the block beginning",																	// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"line of the block end (-1=end)",																	// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"position of the block end (-1=end)",																// pozice konce bloku
IDF_WINDOW_POS2,			"actual position 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"create switch button",																				// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"create table (parameter = list of titles)",														// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"width of table column",																			// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"shadow range (0=off)",																				// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"align of table column (0=left, 1=right, 2=center)",												// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"create horizontal scrollbar",																		// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"create vertical scrollbar",																		// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"exchange colors",																					// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"first color",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"second color",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"replace color",																					// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"old color",																						// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"new color",																						// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"print picture",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"object with reduced detail level (-1=none)",														// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"distance for detail level reduction",																// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"add pattern for morphing (-1=reset)",																// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"morphing stage (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"lens flare",																						// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dynamic data exchange DDE",																		// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"server name/list of servers",																		// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"topic name/list of topics",																		// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"entry name/list of entries",																		// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"program provides entry (it is server)",															// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"type of entry (0 to 7, -1=invalid entry)",															// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) number",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) flag",																							// pøíznak DDE
IDF_DDE_TEXT,				"(2) text",																							// text DDE
IDF_DDE_ICON,				"(3) item",																							// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) picture",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) sound",																						// zvuk DDE
IDF_DDE_MUSIC,				"(6) music",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"command to execute",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL libraries",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"load library",																						// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"free library",																						// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"import function",																					// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"library identifier",																				// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"function name",																					// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"number of parameters",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"execute function",																					// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"create memory block",																				// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"free memory block",																				// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"change size of memory block",																		// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"address of memory block",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"new size",																							// nová velikost bloku pamìti
IDF_MEMORY_READ,			"read pointer",																						// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"write pointer",																					// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"data copy",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"data comparison",																					// porovnání bloku dat
IDF_MEMORY_BYTES,			"byte with sign",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"byte without sign",																					// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"word with sign",																					// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"word without sign",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-byte with sign",																					// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-byte without sign",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"doubleword with sign",																				// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"doubleword without sign",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"decimal number 4 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"decimal number 8 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logical value",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"text terminated by null",																			// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"pointer to text terminated by null",																// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"text with fixed length",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"length of text with fixed length",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"read data from file",																				// ètení dat ze souboru
IDF_MEMORY_SAVE,			"write data to file",																				// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identifier of window element",																		// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"calling convention C",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"create tabs",																						// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"configuration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"configuration fike",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"parameter section",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"parameter name",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"read/write text prameter",																			// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"read/write integer prameter",																		// ètení/zápis hodnoty èíselného konfiguraèního parametru
IDF_REG_KEY,				"key group (1=CURRENT_USER, 2=LOCAL_MACHINE)",														// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"key name",																							// plnı mázev klíèe registrù
IDF_REG_VALUE,				"entry name",																						// název datové poloky
IDF_REG_STRING,				"read/write text entry",																			// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"read/write integer entry",																			// ètení/zápis èíselné poloky registrù
IDF_MEMORY_3D,				"create 3D object from memory blocks",																// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"number of vertices",																				// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"vertices",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normals (0=auto)",																					// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"texture mapping (0=none)",																			// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"colors (0=none)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"number of faces",																					// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"faces",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"texture from file",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"memory block from 3D object",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"find child (-1=first, -2=parent)",																	// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
