// Polsky (Polish)
// 1250
// [0] Rùzné texty
IDN_MAINFRAME,				"Piotr",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Globalne przemieniane i funkcje",																	// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Lokalne przemieniane i funkcje",																	// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Podstawowe elementy, kosz",																		// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Biblioteka przemienianych i funkcij",																// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"podstawowe przemieniane i funkcje",																// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Nowy program",																						// implicitní název nového programu
IDN_NEWDIR_NAME,			"Nowy katalog",																						// implicitní název nové sloky
IDN_TEXTVZOR,				"[wzory]",																							// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"U¿ywany",																							// zobrazuje poèet pouití prvku
IDT_RADEK,					"wiersz",																							// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"pozycja",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"zapiêty",																							// text editoru hodnoty pøepínaèe
IDN_DATUM,					"data",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"czas",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"rozmiar",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"wolne",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"powtarzenie",																						// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV)
IDN_OPAKOVANE,				"powtarzeno",																						// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV)
IDN_DEMO,					"DEMO",																								// oznaèení DEMOverze
IDN_PROFI,					"Professional",																						// oznaèení verze Professional
IDN_LITE,					"Lite",																						// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Plik",																							// volba k vyvolání menu "Soubor"
IDN_START0,					"S&tart\tF5",																						// volba pro spuštìní programu
IDN_START,					"Uruchomi program.\nStart",																			// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Otworzyæ\tCtrl+O",																				// volba k otevøení programu k editaci
IDN_OPEN,					"Otworzy program do edycjê.\nOtworzyæ",																// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Nowy...\tCtrl+N",																					// volba pro zaloení nového programu
IDN_NEW,					"Utworzy nowy program.\nNowy",																		// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"Prze&mianowaæ...\tAlt+Enter",																		// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Zmieni imiê programu/katalogu (nie mo¿na przemianowaæ wzorowe programy i katalogy).\nPrzemianowaæ",	// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"Kopiow&aæ...\tCtrl+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Skopiuje wybrany program pod inne imiê.\nKopiowaæ",												// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"No&wy katalog...\tCtrl+P",																			// volba k vytvoøení nové sloky
IDN_PATH,					"Utworzy nowy katalog dla programów.\nNowy katalog",												// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Usun¹æ...\tDelete",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Usunie program albo katalog (nie mo¿na usuwaæ wzorowe programy i katalogy).\nUsun¹æ",				// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Krátká j&ména",																					// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Programy a soubory knihovny bude vytváøet s jmény krácenımi na 8 znakù.\nKrátká jména",			// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Koniec\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Zakoñczy aplikacjê Piotr.\nKoniec",																// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"&Pismo",																							// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Pismo &wyboru programu...",																		// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Ustawi wygl¹d pisma w oknie wyboru programu.\nPismo wyboru programu",								// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Pismo &edytoru programu...",																		// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Ustawi wygl¹d pisma w oknach edytoru programu.\nPismo edytoru programu",							// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Pismo edytoru &tekstu...",																			// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Ustawi wygl¹d pisma w oknie edytoru tekstu.\nPismo edytoru tekstu",								// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Pismo &menu...",																					// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Ustawi wygl¹d pisma menu.\nPismo menu",															// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Pismo &statutnej listwi..",																		// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Ustawi wygl¹d pisma statutnej (informacyjnej) listwi.\nPismo statutnej listwi",					// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&Jêzyk",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automatyczne",																					// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Wybierze jêzyk automatyczne wed³ug ustawienia systemu.\nAutomatyczne",								// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Poprzedny\tCtrl+F9",																				// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Prze³¹czy miêdzy dwuma ostatnio wybranymi jêzykami.\nPoprzedny",									// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Po bu³garsku (Bulgarija)",																			// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Prze³¹czy aplikacjê Piotr w jêzyk bu³garski.\nPo bu³garsku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"Po &czesku (Èesky)",																				// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Prze³¹czy aplikacjê Piotr w jêzyk czeski.\nPo czesku",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"Po duñsku (Danmark)",																				// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Prze³¹czy aplikacjê Piotr w jêzyk duñski.\nPo duñsku",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"Po &niemiecku (Deutsch)",																			// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Prze³¹czy aplikacjê Piotr w jêzyk niemiecki.\nPo niemiecku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Po grecku (Hellás)",																				// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Prze³¹czy aplikacjê Piotr w jêzyk grecki.\nPo grecku",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"Po an&gielsku (English)",																			// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Prze³¹czy aplikacjê Piotr w jêzyk angielski.\nPo angielsku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"Po &hiszpañsku (Espaòa)",																			// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Prze³¹czy aplikacjê Piotr w jêzyk hiszpañski.\nPo hiszpañsku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Po fiñsku (Finland)",																				// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Prze³¹czy aplikacjê Piotr w jêzyk fiñski.\nPo fiñsku",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"Po &francusku (France)",																			// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Prze³¹czy aplikacjê Piotr w jêzyk francuski.\nPo francusku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"Po &wêgiersku (Magyar)",																			// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Prze³¹czy aplikacjê Piotr w jêzyk wêgierski.\nPo wêgiersku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Po islandsku (Island)",																			// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Prze³¹czy aplikacjê Piotr w jêzyk islandski.\nPo islandsku",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Po &w³osku (Italy)",																				// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Prze³¹czy aplikacjê Piotr w jêzyk w³oski.\nPo w³osku",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Po holendersku (Nederland)",																		// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Prze³¹czy aplikacjê Piotr w jêzyk holenderski.\nPo holendersku",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Po norwesku (Norge)",																				// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Prze³¹czy aplikacjê Piotr w jêzyk norweski.\nPo norwesku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Po &polsku",																						// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Prze³¹czy aplikacjê Piotr w jêzyk polski.\nPo polsku",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Po portugalsku (Portugal)",																		// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Prze³¹czy aplikacjê Piotr w jêzyk portugalski.\nPo portugalsku",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Po rumuñsku (România)",																			// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Prze³¹czy aplikacjê Piotr w jêzyk rumuñski.\nPo rumuñsku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"Po &rosyjsku (Rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Prze³¹czy aplikacjê Piotr w jêzyk rosyjski.\nPo rosyjsku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Po serbochorvatsku (Serbo-Croat)",																	// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Prze³¹czy aplikacjê Piotr w jêzyk serbochorvatski.\nPo serbochorvatsku",							// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"Po &s³owacku (Slovensky)",																			// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Prze³¹czy aplikacjê Piotr w jêzyk s³owacki.\nPo s³owacku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Po albañsku (Shqipërisë)",																			// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Prze³¹czy aplikacjê Piotr w jêzyk albañski.\nPo albañsku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Po szwedzku (Swerige)",																			// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Prze³¹czy aplikacjê Piotr w jêzyk szwedzki.\nPo szwedzku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Po turecku (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Prze³¹czy aplikacjê Piotr w jêzyk turecki.\nPo turecku",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"Vietnamese (Vietnamese)",																				// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Pomoc",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Pomoc\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Poka¿e pomoc do wybranego elementu.\nPomoc",														// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"&Tematy pomocy",																					// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Poka¿e tematy pomocy.\nTematy pomocy",																// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"Sz&ukaæ w pomocy",																					// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Wyszukuje w pomocy.\nSzukaæ w pomocy",																// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"&O aplikacji Piotr",																				// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Poka¿e informacje o aplikacji Piotr, numer wersji i copyright.\nO aplikacji Piotr",				// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Zamkn¹æ\tCtrl+O",																					// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Zamknie edytowany program i otworzy inny.\nZamkn¹æ",												// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Zapisaæ\tCtrl+S",																					// volba k uloení programu pøi editaci
IDN_SAVE,					"Zapisze zmiany wykonane w programu.\nZapisaæ",														// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"Zapisaæ &nieuruchomienie\tCtrl+Alt+S",																// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Zapisze program nieuruchomieny (mniejszy rozmiar).\nZapisaæ nieuruchomienie",						// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Zapisaæ &jak...\tCtrl+Shift+S",																	// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Zapisze program do pliku innego imienia lub do innego dysku.\nZapisaæ jak",						// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Dystrybucja...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Zapisze dystrybuczn¹ nieedycyjn¹ wersji programu (tylko przy licencji Professional).\nDystrybucja",	// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Eks&port...",																						// volba k exportování programu
IDN_EXPORT,					"Eksportuje program w tekstovu formu.\nExport",														// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Importuje program z textove formy.\nImport",														// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"&Edytowaæ",																						// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Przywróciæ\tCtrl+Z",																				// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Przywróci wstecz stan przed wykonaniem zmiany.\nPrzywróciæ",										// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Odwo³aæ\tCtrl+Y",																					// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Odwo³a przywrócenie stanu przed wykonaniem zmiany.\nOdwo³aæ",										// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"W&yj¹æ\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Wyjmie wybran¹ czêœæ i zapisze j¹ w skrzynkê.\nWyj¹æ",												// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Kopiowaæ\tCtrl+C",																				// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Skopiuje wybran¹ czêœæ w skrzynkê.\nKopiowaæ",														// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"&W³o¿yæ\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"W³o¿y zawartoœæ skrzynki do aktualnego miejsca.\nW³o¿yæ",											// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Usun¹æ\tDelete",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Usunie wybran¹ czêœæ.\nUsun¹æ",																	// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Wybr&aæ wszystko\tCtrl+A",																			// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Wybierze wszystko.\nWybraæ wszystko",																// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Przy importu i zmniejszanii obrazków u¿yje dithering.\nDithering",									// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Spojrzenie",																						// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"&Powiêkszyæ\tCtrl+[+]",																			// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Powiêkszy skalê spojrzenia.\nPowiêkszyæ",															// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"&Zmniejszyæ\tCtrl+[-]",																			// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Zmniejszy skalê spojrzenia.\nZmniejszyæ",															// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"Edycja p&oprzednia\tCtrl+do góry",																	// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Powróci do edytowanego elementu poprzedniego.\nEdycja poprzednia",									// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"Edycja &nastêpna \tCtrl+na dó³",																	// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Powróci do edytowanego elementu nastêpnego.\nEdycja nastêpna",										// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Szukanie tekstu...\tCtrl+F",																		// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Wyszuka zadany tekst.\nSzukanie tekstu",															// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"&Tekst poprzedni\tShift+F3",																		// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Wyszuka poprzednie istnienie szukanego tekstu.\nTekst poprzedni",									// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"Te&kst nastêpny\tF3",																				// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Wyszuka nastêpne istnienie szukanego tekstu.\nTekst nastêpny",										// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"P&rogram",																							// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Zamkn¹æ",																							// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Zamknie element przeciw modyfikacji.\nZamkn¹æ",													// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Wy³¹czyæ",																						// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Wy³¹czy funkcjê elementu.\nWy³¹czyæ",																// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Opis\tAlt+Enter",																					// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Edytuje opis elementu.\nOpis",																		// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Opi&s domyœlny",																					// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"U¿yje domyœlny opis elementu.\nOpis domyœlny",														// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Ikona",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Edytuje ikonê elementu.\nIkona",																	// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"I&kona domyœlna",																					// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"U¿yje domyœln¹ ikonê elementu.\nIkona domyœlna",													// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"&Deklaracja",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Wyszuka deklaracjê elementu.\nDeklaracja",															// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"U¿ycie &poprzednie",																				// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Wyszuka poprzednie u¿ycie elementu.\nU¿ycie poprzednie",											// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"U¿ycie &nastêpne",																					// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Wyszuka nastêpne u¿ycie elementu.\nU¿ycie nastêpne",												// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Obrazek",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"Roz&miary...",																						// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Ustawi ogólnych rozmiarów.\nRozmiary",																// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Rastr",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"W³¹czy albo wy³¹czy wyœwietlanie rastru orientacnego.\nRastr",										// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"&Edycje...",																						// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Edytuje obrazek albo jego czêœæ (zmiana wielkoœci, rotacja, kolory).\nEdycje",						// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Odcisk bloku",																					// volba k otisku bloku do obrázku
IDN_OTISK,					"Odciœnie blok do obrazku.\nOdcisk bloku",															// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horyzontalnie",																					// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Przewróci obrazek albo jego czêœæ horyzontalnie.\nHoryzontalnie",									// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertykalnie",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Przewróci obrazek albo jego czêœæ vertykalnie.\nVertykalnie",										// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"Na &lewo",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Rotuje obrazek na lewo (o 90 stopni przeciw kierunkowi wskazówek zegarovych).\nNa lewo",			// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"Na &prawo",																						// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Rotuje obrazek na prawo (o 90 stopni w kierunkowi wskazówek zegarovych).\nNa prawo",				// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"&Podwójny",																						// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Powiêkszy rozmiar obrazku albo jego czêœci na podwójny.\nPodwójny",								// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"Po³ow&iczny",																						// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Zmniejszy rozmiar obrazku albo jego czêœci na po³owiczny.\nPo³owiczny",							// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"&Rozmiar...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Zmieni rozmiar obrazku albo jego czêœci opcjonalnie.\nRozmiar",									// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"&Zamiana",																							// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Zamieni w obrazku albo jego czêœci kolory lewego i prawego przycisku myszy.\nZamiana",				// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Zast¹pienie",																						// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Zast¹pi w obrazku albo jego czêœci kolor prawej klawiszy myszy przez kolor klawiszy lewej.\nZast¹pienie",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Narzêdzia",																						// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Pióro",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Rysuje za pomoc¹ pióra.\nPióro",																	// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"Lin&ia",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Rysuje liniê.\nLinia",																				// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"Pro&stok¹ta",																						// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Rysuje prostok¹ta.\nProstok¹ta",																	// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"&Wype³niany prostok¹t",																			// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Rysuje wype³nianego prostok¹ta.\nWype³niany prostok¹t",											// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Obwód",																							// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Rysuje obwód.\nObwód",																				// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Ko³&o",																							// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Rysuje ko³o.\nKo³o",																				// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Elipsa",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Rysuje elipsê.\nElipsa",																			// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"&Owal",																							// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Rysuje owala.\nOwal",																				// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"K&ula",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Rysuje kulê.\nKula",																				// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"Wy&bór",																							// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Oznaczy dowolnu czêœæ ¿e jest wybrana.\nWybór",													// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"&Opryskiwacz",																						// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Rysuje za pomoc¹ opryskiwacza.\nOpryskiwacz",														// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"Pipetk&a",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Ustawi kolor pod kursorem jak wybrany.\nPipetka",													// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"Wype³&niæ",																						// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Wype³ni powierzchniê kolorem.\nWype³niæ",															// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Tekst",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Wypisze tekst.\nTekst",																			// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Grubka",																							// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Grubka linij &1 punkt",																			// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Rysuje linie grubky 1 punkt.\nGrubka linij 1 punkt",												// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Grubka linij &2 punkty",																			// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Rysuje linie grubky 2 punkty.\nGrubka linij 2 punkty",												// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Grubka linij &5 punktów",																			// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Rysuje linie grubky 5 punktów.\nGrubka linij 5 punktów",											// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Grubka linij &9 punktów",																			// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Rysuje linie grubky 9 punktów.\nGrubka linij 9 punktów",											// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Grubka linij 21 &punktów",																			// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Rysuje linie grubky 21 punktów.\nGrubka linij 21 punktów",											// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"&Obszar",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Edycja",																							// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"W³¹czy albo wy³¹czy tryb edycje pol obszaru.\nEdycja",												// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Wype³niæ",																						// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"W³¹czy albo wy³¹czy tryb wype³niania obszaru polem.\nWype³niæ",									// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Przedmioty",																						// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Edytuje przedmioty w obszaru.\nPrzedmioty",														// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Prze³¹cznik &1",																					// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Edytuje prze³¹cznik 1.\nPrze³¹cznik 1",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Prze³¹cznik &2",																					// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Edytuje prze³¹cznik 2.\nPrze³¹cznik 2",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Prze³¹cznik &3",																					// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Edytuje prze³¹cznik 3.\nPrze³¹cznik 3",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Prze³¹cznik &4",																					// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Edytuje prze³¹cznik 4.\nPrze³¹cznik 4",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Prze³¹cznik &5",																					// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Edytuje prze³¹cznik 5.\nPrze³¹cznik 5",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"Nu&mer 1",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Edytuje numern¹ wartoœæ 1 (zakres od 0 do 1023).\nNumer 1",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"Num&er 2",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Edytuje numern¹ wartoœæ 2 (zakres od 0 do 1023).\nNumer 2",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Nume&r 3",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Edytuje numern¹ wartoœæ 3 (zakres od 0 do 127).\nNumer 3",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"Sp&rajt",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&W³asnoœci",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Ustawi w³asnoœci sprajtu (liczba faz, kierunków, ...).\nW³asnoœci",								// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Uruchomi tryb testu sprajtu.\nTest",																// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"DŸ&wiêk",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Przegraæ",																						// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Rozpocznie przegrawanie.\nPrzegraæ",																// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"Pauz&owaæ",																						// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pauzuje przegrawanie.\nPauzowaæ",																	// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"Za&trzymaæ",																						// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Zatrzyma przegrawanie.\nZatrzymaæ",																// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"Powtarzeno",																						// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"W³¹czy albo wy³¹czy powtarzenie przegrawania.\nPowtarzeno",										// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Nagraæ",																							// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Rozpocznie nagrywanie.\nNagraæ",																	// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Muzyka",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Powrót",																							// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Posunie przegrawanie o 10 sekundê wstecz.\nPowrót",												// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Naprzód",																							// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Posunie przegrawanie o 10 sekundê naprzód.\nNaprzód",												// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"O aplikacji Piotr",																				// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Piotr wersja",																						// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Miroslav Nemecek",														// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Ronov pod Radhoštìm",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Èeská republika",																					// Èeská Republika
IDC_DEMOTEXT1,				"Demoversja nie pozwoli zapisywanie programów ni uruchamianie",										// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"nowych lub zmianianych programów. Edycyjne mo¿liwoœci,",											// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"pomoc i zapisywanie do biblioteki siê pe³nie funkcyjne.",											// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Aktualne informacje o produktu uzyskacie pod adresem internetowym:",								// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Zamówienia jest mo¿liwe przesy³aæ na adres:",														// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENCJA",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"nieograniczona",																					// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"dla 1 komputera",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"komputery",																						// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"komputerów",																						// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Lite version of the Peter provides limited programmatic equipment",								// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(unfunctional elements are marked by grayed icons). Lite version",									// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"is FREEWARE and may be distributed and used freely for private",									// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"purposes. For commercial uses and for schools the license payment",								// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"is required by further specifications on the address www.gemtree.com.",							// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Szukanie tekstu",																					// titulek okna hledání textu
IDN_FINDTEXT,				"Zadajcie szukany tekst:",																			// vızva k zadání textu k hledání
IDN_CANCEL0,				"Anuluj",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Rozmiary obszaru",																					// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Szerokoœæ:",																						// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Wysokoœæ:",																						// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Nie mo¿na otworzyæ",																				// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"Program nie mo¿na otworzyæ.",																		// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Widocznie jest ju¿ otwarty inn¹ aplikacj¹",														// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"albo jest dostêp do pliku zakazany.",																// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"B³¹d czytania",																					// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"B³¹d przy czytaniu programu.",																		// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"Program jest uszkodzony albo by³ utworzony wysz¹",													// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"wersj¹ edytoru i niemusi dlatego poprawnie pracowaæ.",												// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Unsupported Commands",																				// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Warning: The program uses commands which are not",													// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"supported by the Lite version of the Peter application.",											// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"By saving the program it can become unfunctional.",												// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Edycje obrazku albo jego wybranej czês\'ci",														// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Przewrócenie",																						// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horyzontalnie",																					// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertykalnie",																						// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Rotacja",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 stopni)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 stopni)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 stopni)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 stopni)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 stopni)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 stopni)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 stopni)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 stopni)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 stopni)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 stopni)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 stopni)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 stopni)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Rozmiar",																							// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Podwójny",																							// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Po³owiczny",																						// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Opcjonalny",																						// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Kolory",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Lewy <-> prawy przycisk",																			// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Lewy -> prawy przycisk",																			// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Rozmiary obrazku",																					// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Rozmiary zadane",																					// nadpis rámeèku volby jednotky
IDC_KROK,					"W &krokach",																						// [1] volba jednotky v krocích
IDC_BOD,					"W &punktach",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Zmiana wielkoœci obrazku albo jego czêœci",														// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Aktualne rozmiary:",																				// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"kroków",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"punktów",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Nove rozmiary",																					// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Szerokoœæ:",																						// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Wysokoœæ:",																						// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"W krokach",																						// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"W punktach",																						// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"W procentach",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Zachowaæ oryginalny stosunek stron (stosunek szerokoœæ/wysokoœæ)",									// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Wyg³adziæ kanty (dok³adna, ale powolna konwersja)",												// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (w³¹czyæ dla fotografij, wy³¹czyæ dla rysunków)",										// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Wybór koloru",																						// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Program nie mo¿na utworzyæ",																		// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Program siê nieuda³o utworzyæ.",																	// 1. øádek hlášení
IDN_JINE_JMENO,				"Spróbuj inne imiê.",																				// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Usuwanie programu",																				// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Czy na pewno chciecie usun¹æ wybrany program?",													// 1. øádek hlášení
IDN_SELECT_DEL2,			"OSTRZE¯ENIE: program ju¿ niebêdzie mo¿liwe odnowiæ!",												// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Usuwanie katalogu",																				// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Czy na pewno chciecie usun¹æ wybrany katalog?",													// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Katalog nie mo¿na usun¹æ",																			// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Katalog nie mo¿na usun¹æ, je¿eli niejest pusty.",													// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Program nie mo¿na usun¹æ",																			// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"Program nie mo¿na usun¹æ, jest chroniony przeciw zapisu i usuwania.",								// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Nowy katalog",																						// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Jak siê bêdzie nowy katalog mianowaæ?",															// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Katalog nie mo¿na utworzyæ",																		// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Katalog siê nieuda³o utworzyæ.",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Katalog istnieje",																					// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Uwaga - taki katalog ju¿ istnieje.",																// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Program istnieje",																					// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Uwaga - taki program ju¿ istnieje.",																// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Nowy program",																						// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Jak siê bêdzie nowy program mianowaæ?",															// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Kopia programu",																					// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Jak siê bêdzie skopiowany program mianowaæ?",														// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"W³asnoœci sprajtu",																				// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Anymacje",																							// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"OpóŸnienie miêdzy fazami:",																		// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"milisekund",																						// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Faz do kroku (0 = zaraz):",																		// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Poziom dla wyœwietlania (0 = przedmioty):",														// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Liczba obrazków",																					// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Faz dla spokoju:",																					// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Faz dla ruchu:",																					// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Kierunków:",																						// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Rozmiar obrazku",																					// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Szerokoœæ obrazku:",																				// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Wysokoœæ obrazku:",																				// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Test sprajtu",																						// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"B³¹d zapisania",																					// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"Program nie mo¿na zapisaæ.",																		// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Skontroluj, czy niejest uruchomiony",																// 2. øádek hlášení
IDN_WRITEERR3,				"albo czy niejest chroniony przeciw zapisu.",														// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"W przypadku potrzeby zapisz program",																// 4. øádek hlášení
IDN_WRITEERR5,				"do innego imienia czy do innego dysku.",															// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Program zmianiany",																				// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Program by³ zmianiany.\nChciecie zmiany zapisaæ?",													// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Element jest u¿ywany",																				// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Ostrze¿enie - usuwany element jest w programu u¿ywany.\nJego usuniêtiem usuniecie tak¿e ewentualne podga³êzie elementu.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Nieodnowiene usuwanie",																			// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Ostrze¿enie - usuwacie element z biblioteki.\nUsuwanie jest niepowrótne, element niebêdzie mo¿liwe odnowiæ.",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Brak pamiêci",																						// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Niejest dosyæ pamiêci do wykonania ¿¹danej operacje!\n\nUwolnicie miejsce na systemowym dysku Windows\npo przypadku. skontrolujcie ustawienie wirtualnej pamiêci Windows.\nProgram siê mo¿e teraz znajdowaæ w niestabilnym stanu,\ndlatego go, proszê, je¿eli mo¿liwe przyœpieszonie zakoñczycie.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"¯a³ujê, program bêdzie zakoñczeny z powodu braku pamiêci!",										// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Uszkodzone dane licencijne",																		// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Licencijne dane by³y uszkodzone. Uruchomicie ponownie instalator aplikacje Piotr dla poprawki danych licencijnych.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Koniec czasowe ograniczone eksploatacji",															// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Min¹³ czasowe ograniczony czas eksploatacji aplikacje Piotr.",										// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Zbli¿acij siê koniec czasowe ograniczone eksploatacji",											// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"Eksploatacja aplikacje Piotr jest czasowe ograniczona.\nLiczba pozostawszich dni do koñca eksploatacji:",	// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"B³¹d systemu",																						// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Brak systemowych œrodków na uruchomienie programu PETER.EXE.",										// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Program uszkodzony",																				// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Program PETER.EXE uszkodzony, nie mo¿na uruchomiæ.",												// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Zapisaæ do innego pliku",																			// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programy",																							// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Wszystkie pliki",																					// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Zapisaæ dystrybuczn¹ wersj¹ programu",																// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Program ju¿ istnieje",																				// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Ostrze¿enie - zapisywany plik tego imienia ju¿ istnieje.\n\nZapisywacie dystrybuczn¹ nieedycyjn¹ wersj¹ programu\ni je¿eli jest przepisany program Ÿród³ovym programem,\nby³by niepowrótne zgubiony z\'ród³ovy kszta³t programu.\n\nChciecie kontynuowaæ i przepisaæ plik?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Nieuruchomieny program",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Ten program by³ utworzony programowacym narzêdziem Piotr\ni jest teraz zapisan w nieuruchomiene formie.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Ustawienie pisma",																					// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Próbka:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Czêœæ bie¿¹cego tekstu dla próbki.",																// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Standardowe pismo",																				// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"T³uste",																							// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Ukoœne",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Podkreœlane",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Przekreœlane",																						// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Bez piêtek",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"Z piêtkami",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Ze sta³ymi odleg³oœciami",																			// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Wybraæ z listy",																					// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Lista typów pisem:",																				// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Wysok.:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Szerok.[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Styl",																								// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Wygl¹d",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Sloka a jméno k exportu programu",																// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Jméno importovaného programu",																		// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Programy Petra",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"puste pole",																						// prázdnı implicitní pøedmìt
IDF_GROUP,					"grupa",																							// skupina prvkù
IDF_IF,						"warunkowe wykonanie nakazów",																		// záhlaví podmínky
IDF_IF_COND,				"je¿eli jest",																						// test podmínky (IF)
IDF_IF_YES,					"zatem wykonaj",																					// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"inaczej wykonaj",																					// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"warunkowe powtarzenie nakazów",																	// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"dopóki jest",																						// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"powtarzaj nakazy",																					// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"przerwij powtarzenie",																				// pøerušení smyèky (BREAK)
IDF_MINUS,					"negatywny znaczek",																				// záporné znaménko "-" v èísle
IDF_CASE,					"wiêcejstopniowe ga³¹Ÿnie nakazów",																	// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"dla wartoœci wyra¿enia",																			// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"wykonaj nakazy w przypadku, ¿e",																	// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"wyra¿enie jest równe wartoœci",																	// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"inaczej wykonaj nakazy",																			// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"numerna niezmienna",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"eksponent",																						// exponent v èísle
IDF_EQU,					"jest równe",																						// podmínka =
IDF_NEQU,					"niejest równe",																					// podmínka <>
IDF_EQGR,					"jest wiêksze albo równe",																			// podmínka >=
IDF_EQLT,					"jest mniejsze albo równe",																			// podmínka <=
IDF_GR,						"jest wiêksze ni¿",																					// podmínka >
IDF_LT,						"jest mniejsze ni¿",																				// podmínka <
IDF_AND,					"i jednoczeœnie",																					// logickı souèin
IDF_OR,						"albo",																								// logickı souèet
IDF_XOR,					"albo albo (wy³¹czne albo)",																		// logickı vıhradní souèet
IDF_NOT,					"je¿eli niejest",																					// logická negace
IDF_ADD,					"dodaæ",																							// souèet èísel
IDF_SUB,					"odj¹æ",																							// rozdíl èísel
IDF_MUL,					"mno¿yæ",																							// násobek èísel
IDF_DIV,					"dzieliæ",																							// podíl èísel
IDF_REAL,					"numer",																							// èíselná promìnná
IDF_ICON,					"przedmiot",																						// pøedmìtová promìnná
IDF_SND,					"dŸwiêk",																							// zvuková promìnná
IDF_MUS,					"muzyka",																							// hudební promìnná
IDF_FNC,					"funkcja",																							// funkce
IDF_MAP,					"obszar",																							// promìnná plochy
IDF_SPRITE,					"sprajt",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"kierowanie programem - rozszerzenie",																// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"tekst",																							// textová promìnná
IDF_WINDOWS,				"okna",																								// skupina prvkù pro øízení oken
IDF_PAR,					"wstêpne przemieniane",																				// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"wystêpna przemieniana",																			// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"obszar - rozszerzenie",																			// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"lista",																							// záhlaví seznamu (LIST)
IDF_OPER,					"kierowanie programem",																				// skupina prvkù pro øízení programu
IDF_KROK,					"krok",																								// Petøík popojít o krok vpøed
IDF_VLEVO,					"na lewo",																							// Petøík otoèit doleva
IDF_VPRAVO,					"na prawo",																							// Petøík otoèit doprava
IDF_VZAD,					"nazad",																							// Petøík otoèit vzad
IDF_PETRIK,					"Piotrzik",																							// skupina prvkù Petøíka
IDF_BOOL,					"flaga",																							// logická promìnná
IDF_TEXT_CONST,				"tekstowa niezmienna",																				// textová konstanta
IDF_TRUE,					"tak",																								// logickı pøíznak TRUE
IDF_FALSE,					"nie",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucia",																							// skupina prvkù Lucky
IDF_PETRA_KROK,				"krok",																								// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"na lewo",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"na prawo",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"nazad",																							// Lucka otoèit vzad
IDF_RYCHLE,					"widoczny",																							// viditelnost Petøíka
IDF_EXIT,					"wyjœcie funkcje",																					// pøerušení funkce
IDF_PETRA_RYCHLE,			"widoczna",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"dŸwiêk i muzyka",																					// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"przedmiot przed Piotrzikem",																		// pøedmìt pøed Petøíkem
IDF_SMER,					"kierunek",																							// smìr otoèení Petøíka
IDF_POZICEX,				"horyzontalna pozycja",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"vertykalna pozycja",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"przedmiot przed Luci¹",																			// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"kierunek",																							// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"horyzontalna pozycja",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"vertykalna pozycja",																				// vertikální souøadnice Lucky
IDF_CONST,					"obliczenia",																						// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"arytmetyczne operacje",																			// skupina èíselnıch operátorù
IDF_FUNC,					"funkcje",																							// skupina èíselnıch funkcí
IDF_POROVNANI,				"porównanie",																						// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logiczne operacje",																				// skupina logickıch prvkù
IDF_MOD,					"modulo",																							// èíselnı operátor modulo
IDF_SIN,					"sinus",																							// funkce sinus
IDF_COS,					"kosinus",																							// funkce kosinus
IDF_TG,						"tangenta",																							// funkce tangens
IDF_COTG,					"kotangenta",																						// funkce kotangens
IDF_ARCSIN,					"arkus sinus",																						// funkce arcus sinus
IDF_ARCCOS,					"arkus kosinus",																					// funkce arcus kosinus
IDF_ARCTG,					"arkus tangenta",																					// funkce arcus tangens
IDF_ARCCOTG,				"arkus kotangenta",																					// funkce arcus kotangens
IDF_PI,						"Ludolfuw numer",																					// Ludolfovo èíslo (pí)
IDF_INTEGER,				"ca³onumerna czêœæ",																				// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"dziesiêtna czêœæ",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"absolutna wartoœæ",																				// funkce absolutní hodnoty
IDF_SQRT,					"pierwiastek drugiego stopnia",																		// funkce druhá mocnina
IDF_FACT,					"faktorial",																						// funkce faktoriál
IDF_RAND,					"losowy numer (0 <= x < 1)",																		// náhodné èíslo
IDF_EUL,					"Ejlerowa niezmienna",																				// Eulerova konstanta (e)
IDF_DEGRAD,					"konwersja stopni do radyanów",																		// funkce konverze stupòù na radiány
IDF_RADDEG,					"konwersja radyanów do stopni",																		// funkce konverze radiánù na stupnì
IDF_LOG,					"dekadycki logarytm",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"naturalny logarytm",																				// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"naturalna eksponencialna funkcja",																	// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"potêga",																							// operátor mocniny
IDF_UHEL,					"k¹t, kierunek",																					// skupina úhlù (smìrù)
IDF_UHEL0,					"na prawo (0 pi, tzn. 0 stopni)",																	// smìr vpravo
IDF_UHEL45,					"na prawo do góry (1/4 pi, tzn. 45 stopni)",														// smìr vpravo nahoru
IDF_UHEL90,					"do góry (1/2 pi, tzn. 90 stopni)",																	// smìr nahoru
IDF_UHEL135,				"na lewo do góry (3/4 pi, tzn. 135 stopni)",														// smìr vlevo nahoru
IDF_UHEL180,				"na lewo (1 pi, tzn. 180 stopni)",																	// smìr vlevo
IDF_UHEL225,				"na lewo na dó³ (1 1/4 pi, tzn. 225 stopni)",														// smìr vlevo dolù
IDF_UHEL270,				"na dó³ (1 1/2 pi, tzn. 270 stopni)",																// smìr dolù
IDF_UHEL315,				"na prawo na dó³ (1 3/4 pi, tzn. 315 stopni)",														// smìr vpravo dolù
IDF_COMMAND,				"kierowanie",																						// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"czekanie (domyœlnie = 0.05 sek.)",																	// pøíkaz pro èekání
IDF_KLAV,					"klawiatura",																						// skupina ovládání klávesnice
IDF_KLAV_TEST,				"jest wciœniêty klawisz",																			// test stisknuté klávesy
IDF_KLAV_VKEY,				"wstêp klawisza (nieczeka na wciœniêcie)",															// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"wstêp znaku (nieczeka na wcis\'niêcie)",															// vstup znaku bez èekání
IDF_KLAV_VK,				"klawisze",																							// skupina kódù kláves
IDF_KLAV_FX,				"funkcyjny klawisze",																				// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"litery",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numerna klawiatura",																				// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"znakowy klawisze",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"kontrolnie klawisze",																				// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"przejrzystnost",																					// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 End",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 na dó³",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 PgDn",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 na lewo",																						// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 na prawo",																						// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Home",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 do góry",																						// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Del",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 !",																								// kód klávesy 1 !
IDF_VK_2,					"2 @ (2 \")",																						// kód klávesy 2 @
IDF_VK_3,					"3 #",																								// kód klávesy 3 #
IDF_VK_4,					"4 $ (4 ¤)",																						// kód klávesy 4 $
IDF_VK_5,					"5 %",																								// kód klávesy 5 %
IDF_VK_6,					"6 ^ (6 &)",																						// kód klávesy 6 ^
IDF_VK_7,					"7 & (7 /)",																						// kód klávesy 7 &
IDF_VK_8,					"8 * (8 ( )",																						// kód klávesy 8 *
IDF_VK_9,					"9 (  (9 ) )",																						// kód klávesy 9 (
IDF_VK_0,					"0 ) (0 =)",																						// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~ (² ~)",																						// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _ (+ ?)",																						// kód klávesy - _
IDF_VK_ROVNITKO,			"= + (\' *)",																						// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ | (ó Ÿ)",																						// kód klávesy \ |
IDF_VK_LLOMENA,				"[ { (¿ ñ)",																						// kód klávesy [ {
IDF_VK_RLOMENA,				"] } (œ æ)",																						// kód klávesy ] }
IDF_VK_STREDNIK,			"; : (³ £)",																						// kód klávesy ; :
IDF_VK_RCARKA,				"\' \" (¹ ê)",																						// kód klávesy ' "
IDF_VK_CARKA,				", < (, ;)",																						// kód klávesy , <
IDF_VK_TECKA,				". > (. :)",																						// kód klávesy . >
IDF_VK_LOMITKO,				"/ ? (- _)",																						// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"menu Windows na lewo",																				// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Back Space",																						// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"lokalne menu",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"na lewo",																							// kód klávesy Vlevo
IDF_VK_RIGHT,				"na prawo",																							// kód klávesy Vpravo
IDF_VK_UP,					"do góry",																							// kód klávesy Nahoru
IDF_VK_DOWN,				"na dó³",																							// kód klávesy Dolù
IDF_VK_INSERT,				"Insert",																							// kód klávesy Insert
IDF_VK_DELETE,				"Delete",																							// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"End",																								// kód klávesy End
IDF_VK_PAGEUP,				"Page Up",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Page Down",																						// kód klávesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"Shift lewy",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"Ctrl lewy",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"Alt lewy",																							// kód klávesy Levı Alt
IDF_VK_SPACE,				"szparnik",																							// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"mysz",																								// skupina prvkù myši
IDF_MOUSE_L,				"lewy przycisk myszy trzymany",																		// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"prawy przycisk myszy trzymany",																	// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"pozycja myszy w horyzontalnym kierunku",															// horizontální souøadnice myši
IDF_MOUSE_Y,				"pozycja myszy w vertykalnym kierunku",																// vertikální souøadnice myši
IDF_EQU_TEXT,				"zgoda tekstów",																					// operátor porovnání textù
IDF_EQU_ICO,				"zgoda przedmiotów",																				// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"sprajty - rozszerzenie",																			// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"okno ma skraj",																					// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"okno ma nag³ówek",																					// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"parametry programu",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"powrótowy kod",																					// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"obrazek",																							// promìnná obrázku
IDF_REPEAT,					"powtarzenie nakazów z liczb¹",																		// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"dla liczbu powtarzenij",																			// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"skraj obszaru",																					// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horyzontalnie",																					// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertykalnie",																						// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"kierunek",																							// smìr sprajtu
IDF_SPRITE_MOVE,			"w ruchu",																							// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"widoczny",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"liczba",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"indeks",																							// index seznamu
IDF_LIST_AUTO,				"podwy¿szenie indeksu",																				// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Piotrzik - rozszerzenie",																			// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucia - rozszerzenie",																				// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"numerna wartoœæ 1 (zakres od 0 do 1023)",															// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"numerna wartoœæ 1 (zakres od 0 do 1023)",															// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"numerna wartoœæ 2 (zakres od 0 do 1023)",															// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"numerna wartoœæ 2 (zakres od 0 do 1023)",															// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"numerna wartoœæ 3 (zakres od 0 do 127)",															// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"numerna wartoœæ 3 (zakres od 0 do 127)",															// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"prze³¹cznik 1",																					// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"prze³¹cznik 1",																					// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"prze³¹cznik 2",																					// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"prze³¹cznik 2",																					// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"prze³¹cznik 3",																					// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"prze³¹cznik 3",																					// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"prze³¹cznik 4",																					// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"prze³¹cznik 4",																					// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"prze³¹cznik 5",																					// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"prze³¹cznik 5",																					// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"teksty",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"lewa czêœæ tekstu",																				// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"d³ugoœæ lewej czêœci tekstu",																		// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"prawa czêœæ tekstu",																				// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"pocz¹tek prawej czêœci tekstu",																	// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"œrednia czêœæ tekstu",																				// funkce støední èásti textu
IDF_TEXT_MID_POS,			"pocz¹tek œredniej czêœci tekstu",																	// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"d³ugoœæ œredniej czêœci tekstu",																	// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"d³ugoœæ tekstu",																					// funkce zjištìní délky textu
IDF_TEXT_ADD,				"po³¹czenie tekstów",																				// operátor pro slouèení textù
IDF_TEXT_SCAN,				"konwersja numeru z tekstowego kszta³tu",															// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"pøevod èísla na textovı tvar",																		// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"abecední porovnání textù",																			// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"pøevod na malá písmena",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"pøevod na velká písmena",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"nalezení pozice s textem (-1 = není)",																// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"vstupní text",																						// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"hledanı text",																						// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"informaèní text",																					// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"nadpis okna",																						// titulek hlavního okna (textová promìnná)
IDF_ORD,					"pøevod znaku na èíselnı kód",																		// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"pøevod èíselného kódu na znak",																	// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"zvuk",																								// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"pøehrátí zvuku",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"vypnutí zvuku (bez zadání = vše)",																	// vypnutí zvuku
IDF_COLOR,					"barva",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"grafika",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"barva pera",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"tlouška pera",																					// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"bod",																								// nakreslení grafického bodu
IDF_POINT_X,				"horizontální souøadnice bodu X",																	// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertikální souøadnice bodu Y",																		// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"èára",																								// nakreslení èáry
IDF_LINE_X1,				"horizontální souøadnice èáry X1",																	// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertikální souøadnice èáry Y1",																	// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horizontální souøadnice èáry X2",																	// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertikální souøadnice èáry Y2",																	// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"obdélník",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horizontální souøadnice obdélníku X1",																// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertikální souøadnice obdélníku Y1",																// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horizontální souøadnice obdélníku X2",																// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertikální souøadnice obdélníku Y2",																// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"vyplnìnı obdélník",																				// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horizontální souøadnice vyplnìného obdélníku X1",													// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertikální souøadnice vyplnìného obdélníku Y1",													// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horizontální souøadnice vyplnìného obdélníku X2",													// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertikální souøadnice vyplnìného obdélníku Y2",													// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"vıplò",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horizontální souøadnice vıplnì X",																	// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertikální souøadnice vıplnì Y",																	// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"krunice",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horizontální souøadnice støedu X",																	// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertikální souøadnice støedu Y",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"polomìr",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"kruh",																								// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horizontální souøadnice støedu X",																	// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertikální souøadnice støedu Y",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"polomìr",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"trojúhelník",																						// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horizontální souøadnice trojúhelníku X1",															// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertikální souøadnice trojúhelníku Y1",															// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horizontální souøadnice trojúhelníku X2",															// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertikální souøadnice trojúhelníku Y2",															// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horizontální souøadnice trojúhelníku X3",															// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertikální souøadnice trojúhelníku Y3",															// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"koule",																							// nakreslení koule
IDF_SPHERE_X,				"horizontální souøadnice støedu X",																	// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertikální souøadnice støedu Y",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"polomìr",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"zmìna jasu barvy",																					// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"jas barvy (0 a 1)",																				// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"vstup klávesy (èeká na stisk)",																	// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"vstup znaku (èeká na stisk)",																		// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"ádná klávesa nestisknuta",																		// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"menu Windows vpravo",																				// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Shift vpravo",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"Ctrl vpravo",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"Alt vpravo",																						// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"stav Num Lock",																					// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"stav Caps Lock",																					// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"stav Scroll Lock",																					// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"stav Insert",																						// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"klik levım tlaèítkem myši",																		// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"klik pravım tlaèítkem myši",																		// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"dvojklik levım tlaèítkem myši",																	// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"dvojklik pravım tlaèítkem myši",																	// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"test myši v oblasti",																				// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horizontální souøadnice X poèátku oblasti",														// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertikální souøadnice Y poèátku oblasti",															// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"šíøka oblasti",																					// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"vıška oblasti",																					// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"vıpis textu",																						// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horizontální souøadnice X textu",																	// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertikální souøadnice Y textu",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"úhel orientace textu",																				// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"vıška znakù",																						// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"relativní šíøka znakù (1 = bìná)",																// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"tuènı text",																						// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"kurzíva",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"podtrení",																						// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"pøeškrtnutí",																						// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"patièky",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"psací stroj",																						// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"text k vıpisu",																					// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"poèet øádkù textu",																				// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"øádek textu",																						// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"èíslo øádku textu",																				// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"test zvuku (bez zadání = všechny zvuky)",															// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"poèet opakování (0 = trvale)",																		// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"pøedmìt na pozici s Petøíkem",																		// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"pøedmìt na pozici s Luckou",																		// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"vykreslení obrázku",																				// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"obrázek k vykreslení",																				// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horizontální souøadnice obrázku X",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertikální souøadnice obrázku Y",																	// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horizontální souøadnice vıøezu X",																	// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertikální souøadnice vıøezu Y",																	// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"šíøka vıøezu",																						// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"vıška vıøezu",																						// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"úschova vıøezu z plochy jako obrázek",																// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"úschova vıøezu z plochy jako pøedmìt",																// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"jazyk (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"zvuk k pøehrátí",																					// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"hlasitost zvuku (0 a 1)",																			// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"stereofonní vyváení (-1 = vlevo a +1 = vpravo)",													// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"pøerušit hrající zvuk",																			// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"komentáø",																							// komentáø
IDF_SOUND_FUNCTIONS,		"zvukové funkce",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"nastavení vzhledu kurzoru myši",																	// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"obrázek kurzoru myši (bez zadání = pùvodní)",														// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horizontální souøadnice X poèátku oblasti",														// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertikální souøadnice Y poèátku oblasti",															// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"šíøka oblasti",																					// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"vıška oblasti",																					// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"pøehrátí hudby",																					// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"opakované pøehrávání hudby",																		// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"zastavit pøehrávání hudby",																		// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"pozastavit/pokraèovat v pøehrávání hudby",															// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test pøehrávání hudby",																			// test pøehrávání hudby
IDF_MUSIC_POS,				"pozice v pøehrávání hudby",																		// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"délka pøehrávané hudby",																			// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"slouèení barevnıch sloek do barvy",																// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"èervená sloka (0 a 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"zelená sloka (0 a 1)",																			// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"modrá sloka (0 a 1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"naètení barvy bodu",																				// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horizontální souøadnice X k naètení barvy bodu",													// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertikální souøadnice Y k naètení barvy bodu",														// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"druhá mocnina",																					// funkce druhá mocnina
IDF_MUSIC_GROUP,			"hudba",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"audio CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"pøehrátí CD od zadané stopy (bez zadání = 1)",														// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"zastavení pøehrávání CD",																			// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"pozastavení/pokraèování pøehrávání CD",															// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test pøehrávání CD",																				// test pøehrávání CD
IDF_CD_LENGTH,				"celková délka",																					// celková délka CD
IDF_CD_TRACKS,				"poèet stop",																						// poèet stop CD
IDF_CD_POS,					"pozice od zaèátku",																				// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"pøehrávaná stopa",																					// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"délka pøehrávané stopy",																			// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"pozice od zaèátku stopy",																			// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"soubory",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"základní operace",																					// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"novı soubor",																						// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"novı adresáø",																						// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"zrušení souboru nebo adresáøe",																	// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"test existence",																					// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"aktivní disk a adresáø",																			// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"kapacita disku",																					// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"volné místo disku",																				// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"jmenovka disku",																					// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"sériové èíslo disku",																				// zjištìní sériového èísla disku
IDF_FILE_READ,				"aktivní soubor (adresáø) pro ètení",																// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"aktivní soubor (adresáø) pro zápis",																// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"kopie souboru",																					// provedení kopie souboru
IDF_FILE_MOVE,				"pøesun/pøejmenování souboru (adresáøe)",															// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disk",																								// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"parametry",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"atribut R/O (pouze pro ètení)",																	// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"atribut HID (skrytı)",																				// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"atribut SYS (systémovı)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"atribut DIR (adresáø)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"atribut ARC (archivní)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"atribut TEMP (pøechodnı)",																			// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"atribut COMP (zkomprimovanı)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"atribut OFF (nepøístupnı)",																		// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"datum a èas vytvoøení",																			// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"datum a èas posledního pøístupu",																	// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"datum a èas poslední modifikace",																	// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"data",																								// skupina dat souborù
IDF_FILE_BYTES,				"celé èíslo se znaménkem, 1 bajt",																	// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"celé èíslo bez znaménka, 1 bajt",																	// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"celé èíslo se znaménkem, 2 bajty",																	// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"celé èíslo bez znaménka, 2 bajty",																	// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"celé èíslo se znaménkem, 4 bajty",																	// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"celé èíslo bez znaménka, 4 bajty",																	// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"desetinné èíslo, 4 bajty",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"desetinné èíslo, 8 bajtù",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"text zakonèenı binární nulou (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"text zakonèenı koncem øádku",																		// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"text s pevnou délkou",																				// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"pøedmìt (ICO)",																					// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"obrázek (BMP, JPG)",																				// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"zvuk (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"hudba (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"ukazatel ètení",																					// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"ukazatel zápisu",																					// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"datum a èas",																						// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"aktuální datum a èas (poèet sekund od 1.1.1601)",													// aktuální datum a èas
IDF_DATETIME_UTC,			"pøevod místního èasu na svìtovı",																	// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"pøevod svìtového èasu na místní",																	// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"slouèení poloek data a èasu",																		// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"rok",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"mìsíc",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"den",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"hodina",																							// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minuta",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"sekunda",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"milisekunda",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"rok z data a èasu",																				// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"mìsíc z data a èasu",																				// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"den z data a èasu",																				// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"den v tıdnu z data a èasu (0 = nedìle, 1 = pondìlí, ...)",											// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"hodina z data a èasu",																				// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minuta z data a èasu",																				// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"sekunda z data a èasu",																			// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"milisekunda z data a èasu",																		// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"pøevod data na text \"den.mìsíc.rok\"",															// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"pøevod data na text \"mìsíc/den/rok\"",															// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"pøevod data na text \"rok-mìsíc-den\"",															// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"pøevod èasu na text \"hodina:minuta:sekunda\" (24 hodin)",											// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"pøevod èasu na text \"hodina:minuta:sekunda x\" (12 hodin)",										// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"velikost souboru",																					// velikost souboru
IDF_FILE_ERROR,				"pøíznak chyby operace",																			// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"délka textu s pevnou délkou",																		// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"typ disku (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",														// zjištìní typu disku
IDF_TEXT_FORMAT2,			"pøevod èísla na text - 2 èíslice",																	// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"pøevod èísla na text - 8 èíslic HEX",																// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"celé èíslo se znaménkem, 3 bajty",																	// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"celé èíslo bez znaménka, 3 bajty",																	// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"dialogy",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"potvrzovací dialog (vrací 1=OK, 2=Storno, 3=Pøerušit, 4=Znovu, 5=Ignorovat, 6=Ano, 7=Ne)",			// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"text",																								// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"nadpis",																							// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"ikona (0=nic, 1=chyba, 2=dotaz, 3=varování, 4=informace)",											// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"tlaèítka (0=OK, 1=OK/Storno, 2=Pøerušit/Znovu/Ignorovat, 3=Ano/Ne/Storno, 4=Ano/Ne, 5=Znovu/Storno)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"implicitní tlaèítko (1 a 3)",																		// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"další øádek",																						// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"zadání textu",																						// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1. øádek vızvy",																					// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2. øádek vızvy",																					// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3. øádek vızvy",																					// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"pøednastavenı text k zadání",																		// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"vysunutí CD",																						// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"poèet bitù na vzorek (8 nebo 16)",																	// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"vzorkovací kmitoèet (Hz)",																			// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"je zvuk stereofonní?",																				// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"délka zvuku (sekund)",																				// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"konverze na 8 bitù",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"konverze na 16 bitù",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"konverze na stereo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"konverze na mono",																					// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"konverze na 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"konverze na 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"konverze na 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"slouèení zvukù",																					// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"zmìna rychlosti zvuku",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"zvuk ke konverzi",																					// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relativní zmìna rychlosti (1 = beze zmìny)",														// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"tónovı generátor",																					// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"frekvence tónu (Hz)",																				// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"délka tónu (sekund)",																				// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"plocha",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"šíøka plochy",																						// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"vıška plochy",																						// zjištìní vıšky plochy
IDF_MAP_X,					"souøadnice X",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"souøadnice Y",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"plocha",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"pøedmìt",																							// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"èíselná hodnota 1 (rozsah 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"èíselná hodnota 2 (rozsah 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"èíselná hodnota 3 (rozsah 0 a 127)",																// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"pøepínaè 1",																						// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"pøepínaè 2",																						// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"pøepínaè 3",																						// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"pøepínaè 4",																						// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"pøepínaè 5",																						// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"kopie vıøezu plochy",																				// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"plocha s vıøezem",																					// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"souøadnice X vıøezu",																				// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"souøadnice Y vıøezu",																				// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"šíøka vıøezu",																						// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"vıška vıøezu",																						// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"konzola",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"hromadnı posun sprajtù ve smìru X",																// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"hromadnı posun sprajtù ve smìru Y",																// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"levı okraj okna sprajtù",																			// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"dolní okraj okna sprajtù",																			// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"pravı okraj okna sprajtù",																			// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"horní okraj okna sprajtù",																			// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"reim konzoly (nutno uvést na zaèátku hlavní funkce)",												// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"vıstup textu na konzolu",																			// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"vstup textu z konzoly",																			// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"chybovı vıstup textu na konzolu",																	// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"parametr programu (0 = jméno programu)",															// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"jméno programu s plnou cestou",																	// jméno tohoto programu s plnou cestou
IDF_EXEC,					"spuštìní programu",																				// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"spuštìní programu s èekáním",																		// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"pákovı ovladaè",																					// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"souøadnice X pákového ovladaèe",																	// souøadnice X joysticku
IDF_JOYSTICK_Y,				"souøadnice Y pákového ovladaèe",																	// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"souøadnice Z pákového ovladaèe",																	// souøadnice Z joysticku
IDF_JOYSTICK_1,				"tlaèítko 1 pákového ovladaèe",																		// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"tlaèítko 2 pákového ovladaèe",																		// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"tlaèítko 3 pákového ovladaèe",																		// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"tlaèítko 4 pákového ovladaèe",																		// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"texty a obrázky",																					// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"èíslo prvku (0 = hlavní okno)",																	// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"zrušení prvku nebo okna",																			// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"vytvoøení okna",																					// vytvoøení dialogového okna
IDF_WINDOW_X,				"horizontální souøadnice",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"vertikální souøadnice",																			// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"šíøka",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"vıška",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"text",																								// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"viditelnost",																						// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"zákaz",																							// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"vytvoøení tlaèítka",																				// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"stisk tlaèítka nebo zmìna prvku",																	// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"vytvoøení zaškrtávacího boxu",																		// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"vytvoøení editaèního øádku",																		// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"vytvoøení pøepínaèe",																				// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"spoleèné funkce pro všechny prvky",																// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"vytvoøení editaèního pole",																		// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"tlaèítka",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"pøepínaè zapnut",																					// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"vstupní zamìøení",																					// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"vytvoøení implicitního tlaèítka",																	// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"vytvoøení ikonového tlaèítka",																		// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"vytvoøení rámeèku",																				// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"vytvoøení seznamu",																				// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"vytvoøení textu",																					// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"vytvoøení rozbalovacího seznamu",																	// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"vytvoøení rozbalovacího seznamu s editací",														// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"zvıraznìné písmo",																					// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"písmo s pevnou rozteèí",																			// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"vytvoøení pøepínaèe - zaèátek skupiny",															// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"seznamy",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"pøidání poloky do seznamu",																		// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"vyprázdnìní seznamu",																				// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"vytvoøení seznamu s editací",																		// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"vytvoøení 3-stavového boxu",																		// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"pøepínaè v neurèitém stavu",																		// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"vytvoøení okna bez monosti uzavøení",																// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"ikona",																							// ikona prvku dialogového okna
IDF_WINICON_NEW,			"vytvoøení ikony",																					// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"sprajt (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*Ludolfovo èíslo (= 360 stupòù)",																	// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"vzdálenost 1 bodu (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"fáze",																								// fáze sprajtu
IDF_SPRITE_STATUS,			"stav",																								// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"celoobrazovkovı reim",																			// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"vyprázdnìní zásobníku kláves",																		// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"pozice v pøehrávání zvuku",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"pozastavit/pokraèovat v pøehrávání zvuku",															// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"seznam souborù",																					// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"shodnost ploch",																					// operátor porovnání ploch
IDF_EQU_PIC,				"shodnost obrázkù",																					// operátor porovnání obrázkù
IDF_EQU_SPR,				"shodnost sprajtù",																					// operátor porovnání sprajtù
IDF_EQU_SND,				"shodnost zvukù",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"shodnost hudby",																					// operátor porovnání hudeb
IDF_NET_GROUP,				"sí",																								// skupina pro obsluhu sítì
IDF_DIRECTPLAY_GROUP,		"síová podpora DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"seznam spojení",																					// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"aktivní spojení",																					// aktivní spojení DirectPlay
IDF_GAME_LIST,				"seznam her",																						// seznam bìících her DirectPlay
IDF_GAME_ACT,				"aktivní hra",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"seznam hráèù",																						// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"aktivní hráè",																						// aktivní hráè DirectPlay
IDF_GAME_N1,				"èíselnı parametr hry 1 (-16384 a +16383)",														// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"èíselnı parametr hry 2 (-16384 a +16383)",														// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"èíselnı parametr hry 3 (-16384 a +16383)",														// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"èíselnı parametr hry 4 (-16384 a +16383)",														// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"èíselnı parametr hry 5 (-16384 a +16383)",														// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"èíselnı parametr hry 6 (-16384 a +16383)",														// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"èíselnı parametr hry 7 (-16384 a +16383)",														// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"èíselnı parametr hry 8 (-16384 a +16383)",														// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"pøepínaè hry 1",																					// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"pøepínaè hry 2",																					// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"pøepínaè hry 3",																					// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"pøepínaè hry 4",																					// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"pøepínaè hry 5",																					// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"pøepínaè hry 6",																					// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"pøepínaè hry 7",																					// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"pøepínaè hry 8",																					// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"nastavení hry",																					// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"hostitel (øídicí poèítaè)",																		// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"maximálnì hráèù (0 = neomezeno)",																	// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"èíslo aktivního hráèe (-1 = není)",																// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"data",																								// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"odeslání/pøíjem bloku dat (-1 = všem/není)",														// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"èíslo",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"text",																								// text dat DirectPlay
IDF_GAME_DATAL,				"pøepínaè",																							// pøepínaè dat DirectPlay
IDF_GAME_IP,				"IP adresa tohoto poèítaèe",																		// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"celé èíslo 0 a 255 (bajt)",																		// èíslo bajt dat DirectPlay
IDF_INC,					"inkrementace (pøiète 1)",																			// funkce inkrementace èísla
IDF_DEC,					"dekrementace (odeète 1)",																			// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"vytvoøení textu vystøedìného",																		// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"tlaèítko pro klávesu Esc (-1 = není)",																// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"šíøka obrázku",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"vıška obrázku",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"horizontální pøevrácení obrázku",																	// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"vertikální pøevrácení obrázku",																	// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"obrázky",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"zmìna velikosti obrázku",																			// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"obrázek",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"šíøka (bez zadání = úmìrná k vıšce)",																// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"vıška (bez zadání = úmìrná k šíøce)",																// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"zjemnit hrany",																					// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (fotografie)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"kreslení",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"vytvoøení obrázku",																				// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"obrázek",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"vytvoøení editoru RichEdit",																		// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"vıška znakù (0 = bìná)",																			// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"šikmé písmo",																						// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"podtrené písmo",																					// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"pøeškrtnuté písmo",																				// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"písmo s patièkami",																				// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"relativní šíøka znakù (0 = bìná, 1 = základní)",													// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"úhel sklonu textu",																				// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"vytvoøení textu zarovnaného vpravo",																// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"barva písma",																						// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"barva pozadí",																						// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"písmo prvku",																						// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"rychlost pøehrávání (1 = bìná)",																	// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"distinguish code (0 to 65535)",																		// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"zadání souboru k otevøení",																		// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"zadání souboru k uloení",																			// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"zadání textu k hledání",																			// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"zadání barvy",																						// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"maska souborù",																					// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"pøednastavené jméno souboru",																		// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"název souborù",																					// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"zmìna jasu obrázku",																				// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"obrázek ke zmìnì jasu",																			// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"jas obrázku (1 = bìnı)",																			// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"otoèení obrázku",																					// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"obrázek k otoèení",																				// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"úhel otoèení",																						// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"dekomprese zvuku",																					// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"text je ve formátu UNICODE (2 bajty)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"konverze plochy na obrázek",																		// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"konverze pøedmìtu na obrázek",																		// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"bitové operace",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"bitovı souèin AND",																				// bitovı (binární) souèin AND
IDF_BIT_OR,					"bitovı souèet OR",																					// bitovı (binární) souèet OR
IDF_BIT_XOR,				"bitová inverze XOR",																				// bitová (binární) inverze XOR
IDF_BIT_NOT,				"bitovı doplnìk NOT",																				// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"maximální bitové èíslo (dvojslovo)",																// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"bitová rotace vlevo",																				// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"bitová rotace vpravo",																				// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"test myši v prvku",																				// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"vnitøní šíøka",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"vnitøní vıška",																					// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"znaková sada (1250=støedoevropská, 1251=ruská, 1252=západní)",										// èíslo pouité znakové sady fontù
IDF_USERFONT,				"uivatelskı font",																					// jméno uivatelského fontu
IDF_ENUMFONTS,				"seznam fontù",																						// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"nowy obszar",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"szerokoœæ obszaru",																				// šíøka nové plochy
IDF_MAP_NEW_H,				"obszar",																							// vıška nové plochy
IDF_WINDOW_TOP,				"vdy nahoøe",																						// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"pøezdívka (alias)",																				// pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"communication port",																				// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"open port (-1=error)",																				// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"close port",																						// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"active port",																						// aktivní port
IDF_COM_NUM,				"number (0 to 255)",																				// vstup/vıstup èísla
IDF_COM_TEXT,				"character (text)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"baud rate",																						// pøenosová rychlost
IDF_COM_STOP,				"2 stop bits",																						// reim s 2 stopbity
IDF_COM_BITS,				"number of bits (5 to 8)",																			// poèet bitù na znak
IDF_COM_PARIT,				"parity (0=none, 1=odd, 2=even)",																	// zvolená parita
IDF_COM_IN,					"character was received",																			// byl pøijatı znak
IDF_COM_SEND,				"sending is allowed (CTS, RTS)",																				// povoleno vysílání
IDF_COM_RECEIVE,			"receiving is allowed (DSR, DTR)",																				// povolen pøíjem
IDF_PICTURE_MASK,			"picture masking",																					// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"picture",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"mask",																								// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"field width to text display (0 = none)",															// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"create edit field without wrap",																	// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"resizable window",																					// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"window may be closed",																				// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"window is maximized",																				// maximalizace okna
IDF_WINDOW_MINIM,			"window is minimized",																				// minimalizace okna
IDF_PROGRESS_NEW,			"create progressbar",																				// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"create horizontal trackbar",																		// vytvoøení dialogového prvku horizontálního táhla (trackbar)
IDF_VTRACKBAR_NEW,			"create vertical trackbar",																			// vytvoøení dialogového prvku vertikálního táhla (trackbar)
IDF_WINDOW_POS,				"actual position",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"mixer",																							// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"mixer device",																						// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"destination line",																					// volba cílového signálu
IDF_MIX_LINE_SRC,			"source line (none=only destination line)",															// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"type of line",																						// zjištìní typu signálu
IDF_MIX_CONTROL,			"control item",																						// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"type of control item",																				// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"value of control item (0 to 1)",																	// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"selection of control item",																		// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"controlled channel (-1=all)",																		// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D graphics",																							// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"3D graphics window",																					// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X coordinate of 3D graphics window",																	// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y coordinate of 3D graphics window",																	// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"width of 3D graphics window",																			// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"height of 3D graphics window",																		// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"videomode (width*height/bits)",																						// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"graphic background",																				// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"settings",																							// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"filling surfaces",																				// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"lighting",																							// mód osvìtlení
IDF_DIRECT3D_SHADES,		"smooth shading",																					// mód stínování
IDF_DIRECT3D_INVERT,		"object inversion",																					// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objects",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"wall",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"cube",																								// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"sphere",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"cylinder",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"cone",																								// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"clone",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"object from text",																					// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"object from file",																					// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"active object (0=scene, 1=camera, 2=light)",														// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"delete object",																					// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"visible",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"link",																								// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"object to file",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformations",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"scale in X direction",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"scale in Y direction",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"scale in Z direction",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"rotation around X-axis",																			// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"rotation around Y-axis",																			// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"rotation around Z-axis",																			// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"translation in X direction",																		// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"translation in Y direction",																		// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"translation in Z direction",																		// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"surface",																							// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"color (-1=internal, -2=default)",																				// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"emissive color",																					// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"dimness (0=off, 5=metal, 50=plastic)",																// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"reflectance color",																				// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"texture",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"texture mapping",																					// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"projection type (0=flat, 1=cylinder, 2=sphere, 3=chrome, 4=lens)",											// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"X coordinate of projection center",																		// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"Y coordinate of projection center",																		// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"Z coordinate of projection center",																		// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"rotation of projection around X-axis",																		// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"rotation of projection around Y-axis",																		// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"rotation of projection around Z-axis",																		// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"transparency (1=normal, 11=fire, 20=glass, 54=overlap)",											// nastavení prùhlednosti
IDF_DIRECT3D_ALPHAREF,		"contours (0=normal, 0.5=contours)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"method (0=addresses, 1=vertices, 2=faces)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"horizontal origin of texture",																		// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"vertical origin of texture",																			// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"horizontal decrease grade of texture",																// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"vertical decrease grade of texture",																// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"lighting",																							// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"create new light",																					// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"light color",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"light type (1=point, 2=spot, 3=directional)",							// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"angle of light cone",																						// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"penumbra angle",																					// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"light range",																						// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"light intensity (1=normal)",																		// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"linear attenuation",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"quadratic attenuation",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"projection type (0=persp, 1=ortho, 2=r-persp, 3=r-ortho)",												// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"scene",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"scene background color (-1=off, -2=no initialization)",											// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"scene background texture",																				// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"fog color (-1=off)",																						// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"fog type (0=lin, 1=exp, 2=quadr, +4=correction)",													// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"start of linear fog",																					// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"end of linear fog",																					// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"density of exp. and quadr. fog (0 to 1)",																// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"distance of projection plane",																		// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"visual range distance",																				// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"create upper base",																				// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"create lower base",																				// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"search object",																				// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"X coordinate of point",																				// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"Y coordinate of point",																				// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"texture minification filter",																			// nastavení filtrace textur
IDF_DIRECT3D_2DOBJECT,		"2D object",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terrain from picture",																	// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"terrain level",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"horizontal coordinate",																	// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"vertical coordinate",																	// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"group",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"complexity of object (2 to 100)",																	// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"order of rotations (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",									// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"driver (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",											// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"rotary object",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terrain from sheet",																	// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"reflection of ambient light (-1=default)",														// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"program is active application",																		// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"distance of point",																					// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"angle of point",																						// vıpoèet úhlu bodu
IDF_POLAR_X,				"X coordinate of point",																				// souøadnice X bodu
IDF_POLAR_Y,				"Y coordinate of point",																				// souøadnice Y bodu
IDF_FILE_LOGIC,				"logical value",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"smoothing of textures (1=no)",																	// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"precise time counter",																				// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"ambient light",																				// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"texture magnification filter",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"faraway texture filter",																		// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"filling object surfaces",																			// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"object lighting",																				// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"object smooth shading",																		// mód stínování
IDF_DIRECT3D_OMINFILTER,	"object texture minification filter",															// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"object texture magnification filter",															// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"faraway object texture filter",																// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"visible object side (0=both, 1=front, 2=back)",												// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"create",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"object normalization",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"circle",																								// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"triangle",																							// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"torus (parameter = diameter 0 to 1)",																// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"static 2D object",																					// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"hemisphere",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interface (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",						// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"elapsed time",																						// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"rendering speed",																				// rychlost renderování
IDF_DIRECT3D_FREE,			"free videomemory",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D picture",																						// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"textures",																							// skupina textur
IDF_DIRECT3D_STAGE,			"stage (0 to 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"color operation (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",											// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"first color argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"second color argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"alpha operation (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"first alpha argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"second alpha argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"horizontal addressing mode (1=repeat, 2=mirror, 3=clamp)",									// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"vertical addressing mode (1=repeat, 2=mirror, 3=clamp)",									// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"blurring of faraway textures (0=default)",																// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"truncated cone (parameter = diameter 0 to 1)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"color of texture factor",																			// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alpha component (0=transparency to 1=color)",															// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"number of faraway textures (0=all)",																// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"render group (0-7=objects, 8-11=transparent, 12-15=pictures)",										// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"depth sort render group",																			// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"write depth information",																			// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"depth test (1 never, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 always)",									// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"calculate normals (parameter = angle for smoothing)",												// pøepoèet normál
IDF_DIRECT3D_RENDER,		"render without displaying",																		// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"text block",																						// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"line of the block beginning",																		// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"position of the block beginning",																	// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"line of the block end (-1=end)",																	// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"position of the block end (-1=end)",																// pozice konce bloku
IDF_WINDOW_POS2,			"actual position 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"create switch button",																				// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"create table (parameter = list of titles)",														// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"width of table column",																			// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"shadow range (0=off)",																				// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"align of table column (0=left, 1=right, 2=center)",												// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"create horizontal scrollbar",																		// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"create vertical scrollbar",																		// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"exchange colors",																					// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"first color",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"second color",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"replace color",																					// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"old color",																						// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"new color",																						// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"print picture",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"object with reduced detail level (-1=none)",														// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"distance for detail level reduction",																// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"add pattern for morphing (-1=reset)",																// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"morphing stage (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"lens flare",																						// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dynamic data exchange DDE",																		// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"server name/list of servers",																		// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"topic name/list of topics",																		// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"entry name/list of entries",																		// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"program provides entry (it is server)",															// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"type of entry (0 to 7, -1=invalid entry)",															// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) number",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) flag",																							// pøíznak DDE
IDF_DDE_TEXT,				"(2) text",																							// text DDE
IDF_DDE_ICON,				"(3) item",																							// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) picture",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) sound",																						// zvuk DDE
IDF_DDE_MUSIC,				"(6) music",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"command to execute",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL libraries",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"load library",																						// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"free library",																						// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"import function",																					// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"library identifier",																				// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"function name",																					// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"number of parameters",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"execute function",																					// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"create memory block",																				// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"free memory block",																				// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"change size of memory block",																		// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"address of memory block",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"new size",																							// nová velikost bloku pamìti
IDF_MEMORY_READ,			"read pointer",																						// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"write pointer",																					// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"data copy",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"data comparison",																					// porovnání bloku dat
IDF_MEMORY_BYTES,			"byte with sign",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"byte without sign",																					// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"word with sign",																					// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"word without sign",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-byte with sign",																					// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-byte without sign",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"doubleword with sign",																				// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"doubleword without sign",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"decimal number 4 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"decimal number 8 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logical value",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"text terminated by null",																			// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"pointer to text terminated by null",																// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"text with fixed length",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"length of text with fixed length",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"read data from file",																				// ètení dat ze souboru
IDF_MEMORY_SAVE,			"write data to file",																				// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identifier of window element",																		// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"calling convention C",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"create tabs",																						// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"configuration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"configuration fike",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"parameter section",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"parameter name",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"read/write text prameter",																			// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"read/write integer prameter",																		// ètení/zápis hodnoty èíselného konfiguraèního parametru
IDF_REG_KEY,				"key group (1=CURRENT_USER, 2=LOCAL_MACHINE)",														// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"key name",																							// plnı mázev klíèe registrù
IDF_REG_VALUE,				"entry name",																						// název datové poloky
IDF_REG_STRING,				"read/write text entry",																			// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"read/write integer entry",																			// ètení/zápis èíselné poloky registrù
IDF_MEMORY_3D,				"create 3D object from memory blocks",																// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"number of vertices",																				// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"vertices",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normals (0=auto)",																					// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"texture mapping (0=none)",																			// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"colors (0=none)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"number of faces",																					// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"faces",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"texture from file",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"memory block from 3D object",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"find child (-1=first, -2=parent)",																	// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
