// Španìlsky (Spanish)
// 1252
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Funciones y Variables Globales",																	// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Funciones y Variables Locales",																	// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Elementos Básicos, Papelera",																		// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Biblioteca de Funciones y Variables",																// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"funciones y variables básicas",																	// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Nuevo Programa",																					// implicitní název nového programu
IDN_NEWDIR_NAME,			"Nueva Carpeta",																					// implicitní název nové sloky
IDN_TEXTVZOR,				"[ejemplos]",																						// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Usado",																							// zobrazuje poèet pouití prvku
IDT_RADEK,					"fila",																								// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"columna",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"activo",																							// text editoru hodnoty pøepínaèe
IDN_DATUM,					"fecha",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"hora",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"tamaño",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"libre",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"repetir",																							// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"repetido",																							// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMO",																								// oznaèení DEMO verze
IDN_PROFI,					"Profesional",																						// oznaèení verze Professional
IDN_LITE,					"Lite",																								// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Fichero",																							// volba k vyvolání menu "Soubor"
IDN_START0,					"&Ejecutar\tF5",																					// volba pro spuštìní programu
IDN_START,					"Ejecuta el programa.\nEjecutar",																	// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Abrir\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Abre el programa para su edición.\nAbrir",															// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Nuevo...\tCtrl+N",																				// volba pro zaloení nového programu
IDN_NEW,					"Crea un nuevo programa.\nNuevo",																	// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"&Renombrar...\tAlt+Enter",																			// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Renombra el programa/carpeta (no se pueden renombrar los programas y carpetas de ejemplo).\nRenombrar",	// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"&Copiar...\tCtrl+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Copia el programa seleccionado con otro nombre.\nCopiar",											// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"Nueva Car&peta...\tCtrl+P",																		// volba k vytvoøení nové sloky
IDN_PATH,					"Crea una nueva carpeta para programas.\nNueva carpeta",											// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Borrar...\tBorrar",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Borra el programa o carpeta (no se pueden borrar los programas y carpetas de ejemplo).\nBorrar",	// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"No&mbres Cortos",																					// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Los ficheros de programas/librerías se crearán con nombres abreviados de 8 caracteres.\nNombres Cortos",	// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Salir\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Apaga la aplicación de Peter.\nSalir",																// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"Configurar Tipo de &Letra",																		// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Tipo de Letra del &Selector de Programa...",														// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Fija el tipo de letra en la ventana de selección de programa.\nTipo de Letra del Selector de Programa",	// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Tipo de Letra del &Editor de Programa...",															// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Selecciona el tipo de letra en la ventana del editor de programa.\nTipo de Letra del Editor de Programa",	// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Tipo de Letra del Editor de &Texto...",															// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Selecciona el tipo de letra en la ventana del editor de texto.\nTipo de Letra del Editor de Texto",	// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Tipo de Letra de &Menú...",																		// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Selecciona el tipo de letra del menú.\nTipo de Letra de Menú",										// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Tipo de Letra de la &Barra de Estado...",															// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Selecciona el tipo de letra de la barra de estado.\nTipo de Letra de Barra de Estado",				// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&Idioma",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automático",																						// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Selecciona el idioma automáticamente, de acuerdo con la configuración del sistema.\nAutomático",	// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Previo\tCtrl+F9",																					// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Conmuta entre los dos últimos idiomas empleados.\nPrevio",											// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Búlgaro (Bulgarija)",																				// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Cambia la aplicación de Peter al idioma búlgaro.\nBúlgaro",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"&Checo (Cesky)",																					// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Cambia la aplicación de Peter al idioma checo.\nCheco",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"&Danés (Danmark)",																					// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Cambia la aplicación de Peter al idioma danés.\nDanés",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"A&lemán (Deutsch)",																				// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Cambia la aplicación de Peter al idioma alemán.\nAlemán",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Griego (Hellás)",																					// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Cambia la aplicación de Peter al idioma griego.\nGriego",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"&Inglés (English)",																				// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Cambia la aplicación de Peter al idioma inglés.\nInglés",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"Español",																							// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Cambia la aplicación de Peter al idioma español.\nEspañol",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finés (Finland)",																					// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Cambia la aplicación de Peter al idioma finés.\nFinés",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"&Francés (France)",																				// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Cambia la aplicación de Peter al idioma francés.\nFrancés",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"&Húngaro (Magyar)",																				// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Cambia la aplicación de Peter al idioma húngaro.\nHúngaro",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Islandés (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Cambia la aplicación de Peter al idioma islandés.\nIslandés",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Italiano (Italy)",																					// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Cambia la aplicación de Peter al idioma italiano.\nItaliano",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Holandés (Nederland)",																				// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Cambia la aplicación de Peter al idioma holandés.\nHolandés",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Noruega (Norge)",																					// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Cambia la aplicación de Peter al idioma noruego.\nNoruego",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Polaco (Po polsku)",																				// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Cambia la aplicación de Peter al idioma polaco.\nPolaco",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portugués (Portugal)",																				// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Cambia la aplicación de Peter al idioma portugués.\nPortugués",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Rumano (România)",																					// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Cambia la aplicación de Peter al idioma rumano.\nRumano",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&Ruso (Po-rusky)",																					// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Cambia la aplicación de Peter al idioma ruso.\nRuso",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Serbo-Croata (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Cambia la aplicación de Peter al idioma Serbo-Croata.\nSerbo-Croata",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"E&slovaco (Po slovensky)",																			// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Cambia la aplicación de Peter al idioma eslovaco.\nEslovaco",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albano (Shqipërisë)",																				// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Cambia la aplicación de Peter al idioma albano.\nAlbano",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Sueco (Swerige)",																					// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Cambia la aplicación de Peter al idioma sueco.\nSueco",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Turco (Türkiye)",																					// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Cambia la aplicación de Peter al idioma turco.\nTurco",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"Vietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Ayuda",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Ayuda\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Muestra Ayuda para el elemento seleccionado.\nAyuda",												// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"Ayuda &Contenidos",																				// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Muestra los contenidos de Ayuda.\nAyuda Contenidos",												// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Búsqueda en Ayuda",																				// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Busca en Ayuda.\nBuscar en Ayuda",																	// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"Acerca de la Aplicación de &Peter",																// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Muestra información acerca de la Aplicación de Peter, versión y copyright.\nAcerca de la Aplicación de Peter",	// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Cerrar\tCtrl+O",																					// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Cierra el programa de edición y abre otro.\nCerrar",												// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Guardar\tCtrl+S",																					// volba k uloení programu pøi editaci
IDN_SAVE,					"Guarda los cambios efectuados en el programa.\nGuardar",											// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"Guardar como &No-ejecutable\tCtrl+Alt+S",															// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Guarda el programa como no ejecutable (menos tamaño).\nGuardar como No-ejecutable",				// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Guardar c&omo...\tCtrl+Shift+S",																	// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Guarda el programa en un fichero con distinto nombre o en otro disco.\nGuardar Como",				// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribución...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Guardar la distribución, versión de programa no editable (sólo con la licencia Profesional).\nDistribución",	// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"E&xportar...",																						// volba k exportování programu
IDN_EXPORT,					"Exporta el programa a formato texto.\nExportar",													// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Importar...",																						// volba k importování programu
IDN_IMPORT,					"Importa un programa desde el formato texto.\nImportar",											// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"&Editar",																							// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Deshacer\tCtrl+Z",																				// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Deshace la última acción realizada.\nDeshacer",													// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Repetir\tCtrl+Y",																					// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Repite la última acción deshecha.\nRepetir",														// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"C&ortar\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Corta lo seleccionado y lo traslada al portapapeles.\nCortar",										// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Copiar\tCtrl+C",																					// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Copia lo seleccionado en el portapapeles.\nCopiar",												// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"&Pegar\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Pega el contenido del portapapeles en la posición actual.\nCortar",								// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Borrar\tBorrar",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Borra lo seleccionado.\nBorrar",																	// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Seleccionar &Todo\tCtrl+A",																		// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Selecciona todo.\nSeleccionar Todo",																// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"D&ifuminar",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Difuminado y mezcla de colores para dibujos.\nDifuminar",											// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Ver",																								// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"&Más Zoom\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Aumenta las dimensiones de la visualización.\nMás Zoom",											// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Me&nos Zoom\tCtrl+[-]",																			// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Disminuye las dimensiones de la visualización.\nMenos Zoom",										// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"Edición &Anterior\tCtrl+arriba",																	// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Vuelve al elemento editado anteriormente.\nEdición Anterior",										// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"Edición &Siguiente\tCtrl+abajo",																	// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Vuelve al elemento que se editó después del actual.\nEdición Siguiente",							// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Buscar Texto...\tCtrl+F",																			// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Busca el texto introducido.\nBuscar Texto",														// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"Texto An&terior\tShift+F3",																		// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Busca la aparición anterior del texto.\nTexto Anterior",											// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"Texto Sigui&ente\tF3",																				// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Busca la aparición siguiente del texto.\nTexto Siguiente",											// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Programa",																						// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Proteger",																						// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Protege el elemento de modificaciones.\nProteger",													// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Apagar",																							// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Desactiva el elemento.\nApagar",																	// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Descripción\tAlt+Enter",																			// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Edita la descripción del elemento.\nDescripción",													// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Descripción p&or defecto",																			// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Emplea la descripción por defecto del elemento.\nDescripción por defecto",							// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Icono",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Edita el icono del elemento.\nIcono",																// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Ico&no por defecto",																				// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Emplea el icono por defecto del elemento.\nIcono por defecto",										// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"De&claración",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Busca la declaración del elemento.\nDeclaración",													// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"&Uso Anterior",																					// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Busca el anterior uso del elemento.\nUso Anterior",												// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"Uso &Siguiente",																					// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Busca el siguiente uso del elemento.\nUso Siguiente",												// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Dibujo",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"&Dimensiones...",																					// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Fija las dimensiones generales.\nDimensiones",														// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Cuadrícula",																						// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Activa o no la visualización de la cuadrícula.\nCuadrícula",										// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"&Editar...",																						// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Edita el dibujo o sus características (escalado, rotación, color).\nEditar",						// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Tampón de Bloque",																				// volba k otisku bloku do obrázku
IDN_OTISK,					"Pega el bloque sobre el dibujo.\nTampón de Bloque",												// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horizontal",																						// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Voltea el dibujo o una parte horizontalmente.\nHorizontal",										// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertical",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Voltea el dibujo o una parte verticalmente.\nVertical",											// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"Iz&quierda",																						// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Rota el dibujo a la izquierda (90 grados en el sentido contrario a las agujas del reloj).\nIzquierda",	// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"De&recha",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Rota el dibujo a la derecha (90 grados en el sentido de las agujas del reloj).\nDerecha",			// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"D&oble",																							// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Duplica el tamaño del dibujo o de parte de él.\nDoble",											// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"&Mitad",																							// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Disminuye a la mitad el tamaño del dibujo o de parte de él.\nMitad",								// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"Esca&lar...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Define el tamaño del dibujo o parte de él.\nEscalar",												// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"&Intercambio",																						// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Intercambia los colores correspondientes a los botones del ratón en el dibujo o en parte de él.\nIntercambio",	// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Sustitución",																						// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Sustituye el color correspondiente al botón derecho por el del izquierdo en el dibujo o en parte de él.\nSustitución",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Herramientas",																					// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"Lá&piz",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Dibuja con el lápiz.\nLápiz",																		// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"&Línea",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Dibuja una línea.\nLínea",																			// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"Cua&dro",																							// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Dibuja un cuadro.\nCuadro",																		// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"Cuadro Relle&no",																					// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Dibuja un cuadro relleno.\nCuadro Relleno",														// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Círculo",																							// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Dibuja un círculo.\nCírculo",																		// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Círcul&o Rellen&o",																				// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Dibuja un círculo relleno.\nCírculo Relleno",														// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Elipse",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Dibuja una elipse.\nElipse",																		// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"Elipse Rellen&a",																					// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Dibuja una elipse rellena.\nElipse Rellena",														// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"Es&fera",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Dibuja una esfera.\nEsfera",																		// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"&Selección",																						// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Selecciona la parte indicada.\nSelección",															// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"Spra&y",																							// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Dibuja con spray.\nSpray",																			// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"P&ipeta",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Selecciona el color señalado con el cursor.\nPipeta",												// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"&Relleno",																							// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Rellena la superficie con un color.\nRelleno",														// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Texto",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Escribe el texto.\nTexto",																			// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Grosor",																							// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Grosor &1 Pixel",																					// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Dibuja las líneas con grosor 1 pixel.\nGrosor &1 Pixel",											// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Grosor &2 Pixeles",																				// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Dibuja las líneas con grosor 2 pixeles.\nGrosor &2 Pixeles",										// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Grosor &5 Pixeles",																				// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Dibuja las líneas con grosor 5 pixeles.\nGrosor &5 Pixeles",										// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Grosor &9 Pixeles",																				// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Dibuja las líneas con grosor 9 pixeles.\nGrosor &9 Pixeles",										// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Grosor 21 &Pixeles",																				// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Dibuja las líneas con grosor 21 pixeles.\nGrosor 21 Pixeles",										// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"&Hoja",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Editar",																							// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Activa o no el modo edición de los objetos de la hoja.\nEditar",									// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Rellenar",																						// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Activa o no el modo rellenar la hoja con el objeto.\nRellenar",									// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Objetos",																							// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Edita los objetos de la hoja.\nObjetos",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Flag &1",																							// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Edita flag 1.\nFlag 1",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Flag &2",																							// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Edita flag 2.\nFlag 2",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Flag &3",																							// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Edita flag 3.\nFlag 3",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Flag &4",																							// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Edita flag 4.\nFlag 4",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Flag &5",																							// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Edita flag 5.\nFlag 5",																			// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"Valor &Numérico 1",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Edita el valor numérico 1 (de 0 a 1023).\nValor Numérico 1",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"Valor N&umérico 2",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Edita el valor numérico 2 (de 0 a 1023).\nValor Numérico 2",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Valor Nu&mérico 3",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Edita el valor numérico 3 (de 0 a 127).\nValor Numérico 3",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"A&nimación",																						// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Propiedades",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Define las propiedades de la animación (número de fases, direcciones, ...).\nPropiedades",			// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Arranca el modo test de la animación.\nTest",														// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"&Sonido",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Sonar",																							// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Comienza a sonar.\nSonar",																			// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"Pa&usa",																							// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pausa del sonido.\nPausa",																			// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"Pa&rar",																							// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Termina de sonar.\nParar",																			// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Bucle",																							// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Activa o no la repetición del sonido o la música.\nBucle",											// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Grabar",																							// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Comienza la grabación.\nGrabar",																	// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Música",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"R&ebobinar",																						// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Rebobina la música 10 segundos.\nRebobinar",														// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Adelante",																						// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Adelanta la música 10 segundos.\nAdelante",														// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"Acerca de la Aplicación de Peter",																	// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"versión de Peter",																					// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Miroslav Nemecek",															// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Roznov pod Radhostem",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Czech Republic",																					// Èeská Republika
IDC_DEMOTEXT1,				"La versión demo no puede grabar ni ejecutar los nuevos",											// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"programas ni los modificados. Las posibilidades de edición,",										// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"ayuda y grabación en la biblioteca están totalmente operativas.",									// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"La información actualizada del producto puede obtenerse en la dirección:",							// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Los pedidos pueden enviarse a la siguiente dirección:",											// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENCIA",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"ilimitada",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"para 1 ordenador",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"ordenadores",																						// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"ordenadores",																						// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"La versión Lite de Peter permite el uso de un conjunto limitado de órdenes",						// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(los elementos no incluidos aparecen marcados en gris). La versión Lite",							// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"es FREEWARE y puede ser distribuido y empleado con libertad para usos",							// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"privados. Cuando el fin es comercial o educacional la licencia para",								// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"es de pago más aclaraciones, en la dirección www.gemtree.com.",									// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Encontrar Texto",																					// titulek okna hledání textu
IDN_FINDTEXT,				"Introducir el texto que se busca:",																// vızva k zadání textu k hledání
IDN_CANCEL0,				"Cancelar",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Dimensiones de la Hoja",																			// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Ancho:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Alto:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Error de Apertura",																				// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"El programa no se puede abrir.",																	// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Puede que esté ya abierto por otra",																// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"aplicación o no esté permitido abrir el fichero.",													// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Error de Lectura",																					// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Error al leer el programa.",																		// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"El programa está dañado o se creó con una versión",												// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"más moderna de editor y por tanto puede no funcionar correctamente.",								// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Comandos No Soportados",																			// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Atención: El programa usa comandos que no se",														// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"incluyen en la versión Lite de la Aplicación de Peter.",											// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"Al salvar el programa puede que éste deje de funcionar.",											// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Modificaciones del Dibujo o su Parte Seleccionada",												// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Voltear",																							// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horizontal",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertical",																							// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Rotar",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 grados)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 grados)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 grados)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 grados)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 grados)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 grados)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 grados)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 grados)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 grados)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 grados)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 grados)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 grados)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Escalar",																							// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Doble",																							// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Mitad",																							// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Opcional",																							// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Colores",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Botón Izquierda <-> Derecho",																		// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Botón Izquierda -> Derecho",																		// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Dimensiones del Dibujo",																			// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Dimensiones Especificadas",																		// nadpis rámeèku volby jednotky
IDC_KROK,					"En &Pasos",																						// [1] volba jednotky v krocích
IDC_BOD,					"En Pi&xeles",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Definir Tamaño del Dibujo o parte de él",															// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Dimensiones Actuales:",																			// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"pasos",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"pixeles",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Nuevas Dimensiones",																				// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Ancho:",																							// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Alto:",																							// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"En Pasos",																							// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"En Pixeles",																						// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"Porcentaje",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Mantener la relación de aspecto (ancho/alto)",														// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Detección de bordes (conversión exacta, pero más lenta)",											// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Difuminar (ON para fotografías, OFF para dibujos)",												// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Selección de Color",																				// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Error de Creación de Programa",																	// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"No se puede crear el programa.",																	// 1. øádek hlášení
IDN_JINE_JMENO,				"Pruebe otro nombre.",																				// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Borrar Programa",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"¿Confirma que quiere borrar el programa seleccionado?",											// 1. øádek hlášení
IDN_SELECT_DEL2,			"ATENCIÓN: ¡No será posible recuperar el programa!",												// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Borrar Carpeta",																					// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"¿Confirma que quiere borrar la carpeta seleccionada?",												// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Error de Borrado de Carpeta",																		// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"La carpeta no se puede borrar si no está vacía.",													// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Error de Borrado de Programa",																		// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"El programa no se puede borrar, sólo permite su lectura.",											// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Nueva Carpeta",																					// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Introduzca el nombre de la nueva carpeta:",														// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Error de Creación de Carpeta",																		// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"La carpeta no puede ser creada.",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Carpeta Ya Existe",																				// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Atención - ya existe una carpeta con ese nombre.",													// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Programa Ya Existe",																				// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Atención - ya existe un programa con ese nombre.",													// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Programa Nuevo",																					// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Introduzca el nombre del nuevo programa:",															// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Copiar Programa",																					// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Introduzca un nombre para la copia del programa:",													// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Propiedades Animación",																			// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animación",																						// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Retardo Entre Fases:",																				// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"milisegundos",																						// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Fases por Paso (0 = Inmediatamente):",																// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Nivel que se Muestra (0 = Objetos):",																// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Número de Dibujos",																				// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Fases en Reposo:",																					// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Fases en Movimiento:",																				// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Direcciones:",																						// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Dimensión del Dibujo",																				// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Ancho del Dibujo:",																				// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Alto del Dibujo:",																					// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Test de la Animación",																				// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Error al Guardar",																					// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"El programa no se puede grabar.",																	// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Compruebe que no está siendo ejecutado ni",														// 2. øádek hlášení
IDN_WRITEERR3,				"está protegido contra escritura.",																	// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"Si es necesario, grabe el programa con",															// 4. øádek hlášení
IDN_WRITEERR5,				"un nombre diferente o en una ubicación distinta.",													// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"El Programa Ha Cambiado",																			// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"El programa ha cambiado.\n¿Quiere guardar los cambios?",											// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"El Elemento Está En Uso",																			// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Atención - el elemento borrado se utiliza en el programa.\nAl borrarlo también se borrarán las subestructuras propias del elemento.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Borrado Irrevesible",																				// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Atención - borrará el elemenro de la biblioteca.\nEste borrado es irreversible, no será posible la recuperación del elemento.",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Memoria Insuficiente",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"¡Memoria insuficiente para realizar la operación solicitada!\n\nEste programa puede mostrarse inestable ahora,\npor lo que debe quitarlo cuanto antes.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"¡Lamentablemente, este programa se terminará por falta de memoria!",								// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Datos de Licencia Dañados",																		// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Los datos de la licencia son incorrectos. Instale de nuevo la Aplicación de Peter para corregirlos.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Término de la Validez Temporal",																	// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Ha caducado el tiempo de actividad de la Aplicación de Peter.",									// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Término de la Validez Temporal",																	// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"El tiempo de validez de la Aplicación de Peter es limitado.\nDías que quedan de validez:",			// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"Error de Sistema",																					// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Recursos de sistema insuficientes para ejecutar PETER.EXE.",										// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Programa Dañado",																					// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"La Aplicación PETER.EXE está dañada, no arrancará.",												// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Guardar en Otro Fichero",																			// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programas",																						// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Todos los ficheros",																				// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Guardar la Versión de Distribución del Programa",													// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"El Programa Ya Existe",																			// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Atención - el fichero ya existe.\n\nVa a grabar la versión no editable de la distribución\nde este programa y si el programa sobreescrito es\nun programa fuente, toda la información fuente se perderá.\n\n¿Quiere continuar y sobreescribir el fichero?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Programa no ejecutable",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Este programa se creó con la herramienta de programación de Peter\ny está almacenada en formato no ejecutable.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Configurar Tipo de Letra",																			// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Muestra:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Texto de Muestra.",																				// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Tipo de Letra Estándar",																			// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Negrita",																							// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Cursiva",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Subrayada",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Tachada",																							// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Sin Marbetes",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"Con Marbetes",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Ancho de letra Fijo",																				// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Seleccionado de la Lista",																			// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Lista de Estilos para Tipo de Letra:",																// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Alto:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Ancho[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Efectos",																							// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Forma",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Carpeta y nombre para exportar el programa",														// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Nombre del programa importado",																	// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Programas de Peter",																				// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"cuadrado vacío",																					// prázdnı implicitní pøedmìt
IDF_GROUP,					"grupo",																							// skupina prvkù
IDF_IF,						"ejecución condicional de comandos",																// záhlaví podmínky
IDF_IF_COND,				"si es válido",																						// test podmínky (IF)
IDF_IF_YES,					"entonces",																							// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"si no",																							// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"repetición condicional de comandos",																// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"mientras sea válido",																				// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"repetir",																							// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"acabar ejecución",																					// pøerušení smyèky (BREAK)
IDF_MINUS,					"signo negativo",																					// záporné znaménko "-" v èísle
IDF_CASE,					"ejecución multicondicional de comandos",															// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"expresión que se evalúa",																			// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"ejecuta tras evaluar que",																			// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"la expresión es igual a",																			// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"si ningún caso se cumple",																			// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"constante numérica",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"exponente",																						// exponent v èísle
IDF_EQU,					"es igual que",																						// podmínka =
IDF_NEQU,					"es distinto que",																					// podmínka <>
IDF_EQGR,					"es mayor o igual que",																				// podmínka >=
IDF_EQLT,					"es menor o igual que",																				// podmínka <=
IDF_GR,						"es mayor que",																						// podmínka >
IDF_LT,						"es menor que",																						// podmínka <
IDF_AND,					"y",																								// logickı souèin
IDF_OR,						"o",																								// logickı souèet
IDF_XOR,					"uno u otro (pero no ambos)",																		// logickı vıhradní souèet
IDF_NOT,					"negación de",																						// logická negace
IDF_ADD,					"suma",																								// souèet èísel
IDF_SUB,					"resta",																							// rozdíl èísel
IDF_MUL,					"multiplicación",																					// násobek èísel
IDF_DIV,					"división",																							// podíl èísel
IDF_REAL,					"número",																							// èíselná promìnná
IDF_ICON,					"objeto",																							// pøedmìtová promìnná
IDF_SND,					"sonido",																							// zvuková promìnná
IDF_MUS,					"música",																							// hudební promìnná
IDF_FNC,					"función",																							// funkce
IDF_MAP,					"hoja",																								// promìnná plochy
IDF_SPRITE,					"animación",																						// promìnná sprajtu
IDF_OPER_EXTRA,				"control de programa - extensión",																	// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"texto",																							// textová promìnná
IDF_WINDOWS,				"ventanas",																							// skupina prvkù pro øízení oken
IDF_PAR,					"variables de entrada",																				// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"variable de salida",																				// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"hoja - extensión",																					// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"lista",																							// záhlaví seznamu (LIST)
IDF_OPER,					"control de programa",																				// skupina prvkù pro øízení programu
IDF_KROK,					"paso",																								// Petøík popojít o krok vpøed
IDF_VLEVO,					"izquierda",																						// Petøík otoèit doleva
IDF_VPRAVO,					"derecha",																							// Petøík otoèit doprava
IDF_VZAD,					"media vuelta",																						// Petøík otoèit vzad
IDF_PETRIK,					"Peter",																							// skupina prvkù Petøíka
IDF_BOOL,					"flag",																								// logická promìnná
IDF_TEXT_CONST,				"constante de texto",																				// textová konstanta
IDF_TRUE,					"sí",																								// logickı pøíznak TRUE
IDF_FALSE,					"no",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucy",																								// skupina prvkù Lucky
IDF_PETRA_KROK,				"paso",																								// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"izquierda",																						// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"derecha",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"media vuelta",																						// Lucka otoèit vzad
IDF_RYCHLE,					"visible",																							// viditelnost Petøíka
IDF_EXIT,					"final de función",																					// pøerušení funkce
IDF_PETRA_RYCHLE,			"visible",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"sonido y música",																					// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"objeto delante de Peter",																			// pøedmìt pøed Petøíkem
IDF_SMER,					"dirección",																						// smìr otoèení Petøíka
IDF_POZICEX,				"posición horizontal",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"posición vertical",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"objeto delante de Lucy",																			// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"dirección",																						// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"posición horizontal",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"posición vertical",																				// vertikální souøadnice Lucky
IDF_CONST,					"cálculos",																							// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"operaciones aritméticas",																			// skupina èíselnıch operátorù
IDF_FUNC,					"funciones",																						// skupina èíselnıch funkcí
IDF_POROVNANI,				"comparaciones",																					// skupina porovnávacích operátorù
IDF_LOG_OPER,				"operaciones lógicas",																				// skupina logickıch prvkù
IDF_MOD,					"módulo",																							// èíselnı operátor modulo
IDF_SIN,					"seno",																								// funkce sinus
IDF_COS,					"coseno",																							// funkce kosinus
IDF_TG,						"tangente",																							// funkce tangens
IDF_COTG,					"cotangente",																						// funkce kotangens
IDF_ARCSIN,					"arco seno",																						// funkce arcus sinus
IDF_ARCCOS,					"arco coseno",																						// funkce arcus kosinus
IDF_ARCTG,					"arco tangente",																					// funkce arcus tangens
IDF_ARCCOTG,				"arco cotangente",																					// funkce arcus kotangens
IDF_PI,						"pi",																								// Ludolfovo èíslo (pí)
IDF_INTEGER,				"parte entera",																						// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"parte decimal",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"valor absoluto",																					// funkce absolutní hodnoty
IDF_SQRT,					"raíz cuadrada",																					// funkce druhá mocnina
IDF_FACT,					"factorial",																						// funkce faktoriál
IDF_RAND,					"número aleatorio (0 <= x < 1)",																	// náhodné èíslo
IDF_EUL,					"número e",																							// Eulerova konstanta (e)
IDF_DEGRAD,					"convertir grados a radianes",																		// funkce konverze stupòù na radiány
IDF_RADDEG,					"convertir radianes a grados",																		// funkce konverze radiánù na stupnì
IDF_LOG,					"logaritmo decimal",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"logaritmo neperiano",																				// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"función exponencial natural",																		// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"potencia",																							// operátor mocniny
IDF_UHEL,					"ángulo, dirección",																				// skupina úhlù (smìrù)
IDF_UHEL0,					"derecha (0 pi ó 0 grados)",																		// smìr vpravo
IDF_UHEL45,					"derecha arriba (1/4 pi ó 45 grados)",																// smìr vpravo nahoru
IDF_UHEL90,					"arriba (1/2 pi ó 90 grados)",																		// smìr nahoru
IDF_UHEL135,				"izquierda arriba (3/4 pi ó 135 grados)",															// smìr vlevo nahoru
IDF_UHEL180,				"izquierda (1 pi ó 180 grados)",																	// smìr vlevo
IDF_UHEL225,				"izquierda abajo (1 y 1/4 pi ó 225 grados)",														// smìr vlevo dolù
IDF_UHEL270,				"abajo (1 y 1/2 pi ó 270 grados)",																	// smìr dolù
IDF_UHEL315,				"derecha abajo (1 y 3/4 pi ó 315 grados)",															// smìr vpravo dolù
IDF_COMMAND,				"controles",																						// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"esperar (por defecto = 0.05 s)",																	// pøíkaz pro èekání
IDF_KLAV,					"teclado",																							// skupina ovládání klávesnice
IDF_KLAV_TEST,				"hay tecla pulsada",																				// test stisknuté klávesy
IDF_KLAV_VKEY,				"tecla de entrada (no espera que se presione)",														// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"carácter de entrada (no espera que se presione)",													// vstup znaku bez èekání
IDF_KLAV_VK,				"teclas",																							// skupina kódù kláves
IDF_KLAV_FX,				"teclas de función",																				// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"letras",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"teclado numérico",																					// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"teclas de signos",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"teclas de control",																				// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"transparencia",																					// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 Fin",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 Abajo",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 AvPág",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 Izquierda",																						// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 Derecha",																						// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Inicio",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 Arriba",																							// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 RePág",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Supr",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Intro",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Bloq Num",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 !",																								// kód klávesy 1 !
IDF_VK_2,					"2 \"",																								// kód klávesy 2 @
IDF_VK_3,					"3 ·",																								// kód klávesy 3 #
IDF_VK_4,					"4 $",																								// kód klávesy 4 $
IDF_VK_5,					"5 %",																								// kód klávesy 5 %
IDF_VK_6,					"6 &",																								// kód klávesy 6 ^
IDF_VK_7,					"7 /",																								// kód klávesy 7 &
IDF_VK_8,					"8 (",																								// kód klávesy 8 *
IDF_VK_9,					"9 )",																								// kód klávesy 9 (
IDF_VK_0,					"0 =",																								// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~",																								// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _",																								// kód klávesy - _
IDF_VK_ROVNITKO,			"= +",																								// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ |",																								// kód klávesy \ |
IDF_VK_LLOMENA,				"[ {",																								// kód klávesy [ {
IDF_VK_RLOMENA,				"] }",																								// kód klávesy ] }
IDF_VK_STREDNIK,			"; :",																								// kód klávesy ; :
IDF_VK_RCARKA,				"\' \"",																							// kód klávesy ' "
IDF_VK_CARKA,				", <",																								// kód klávesy , <
IDF_VK_TECKA,				". >",																								// kód klávesy . >
IDF_VK_LOMITKO,				"/ ?",																								// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Bloq Mayús",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"tecla Windows izquierda",																			// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Borrar",																							// kód klávesy Back Space
IDF_VK_ENTER,				"Intro",																							// kód klávesy Enter
IDF_VK_MENU,				"menú local",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"Izquierda",																						// kód klávesy Vlevo
IDF_VK_RIGHT,				"Derecha",																							// kód klávesy Vpravo
IDF_VK_UP,					"Arriba",																							// kód klávesy Nahoru
IDF_VK_DOWN,				"Abajo",																							// kód klávesy Dolù
IDF_VK_INSERT,				"Insert",																							// kód klávesy Insert
IDF_VK_DELETE,				"Supr",																								// kód klávesy Delete
IDF_VK_HOME,				"Inicio",																							// kód klávesy Home
IDF_VK_END,					"Fin",																								// kód klávesy End
IDF_VK_PAGEUP,				"RePág",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"AvPág",																							// kód klávesy Page Down
IDF_VK_PRINT,				"Impr Pant",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Bloq Despl",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pausa",																							// kód klávesy Pause
IDF_VK_SHIFT,				"Shift izdo",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"Ctrl izdo",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"Alt izdo",																							// kód klávesy Levı Alt
IDF_VK_SPACE,				"barra espaciadora",																				// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"ratón",																							// skupina prvkù myši
IDF_MOUSE_L,				"botón izquierdo del ratón pulsado",																// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"botón derecho del ratón pulsado",																	// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"posición del ratón en la dirección horizontal ",													// horizontální souøadnice myši
IDF_MOUSE_Y,				"posición del ratón en la dirección vertical",														// vertikální souøadnice myši
IDF_EQU_TEXT,				"idéntico texto",																					// operátor porovnání textù
IDF_EQU_ICO,				"idéntico tipo de objeto",																			// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"animaciones - extensión",																			// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"ventana con borde",																				// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"ventana con barra superior",																		// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"parámetros de programa",																			// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"código respuesta",																					// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"dibujo",																							// promìnná obrázku
IDF_REPEAT,					"repetición de comandos un número de veces",														// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"número de iteraciones",																			// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"borde de la hoja",																					// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horizontal",																						// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertical",																							// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"dirección",																						// smìr sprajtu
IDF_SPRITE_MOVE,			"movimiento",																						// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"visible",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"número",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"índice",																							// index seznamu
IDF_LIST_AUTO,				"incremento del índice",																			// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Peter - extensión",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucy - extensión",																					// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"valor numérico 1 (rango 0 a 1023)",																// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"valor numérico 1 (rango 0 a 1023)",																// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"valor numérico 2 (rango 0 a 1023)",																// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"valor numérico 2 (rango 0 a 1023)",																// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"valor numérico 3 (rango 0 a 127)",																	// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"valor numérico 3 (rango 0 a 127)",																	// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"flag 1",																							// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"flag 1",																							// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"flag 2",																							// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"flag 2",																							// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"flag 3",																							// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"flag 3",																							// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"flag 4",																							// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"flag 4",																							// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"flag 5",																							// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"flag 5",																							// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"textos",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"parte izquierda del texto",																		// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"longitud de la parte izquierda",																	// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"parte derecha del texto",																			// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"comienzo de la parte derecha",																		// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"parte interna del texto",																			// funkce støední èásti textu
IDF_TEXT_MID_POS,			"comienzo de la parte interna",																		// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"longitud de la parte interna",																		// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"longitud del texto",																				// funkce zjištìní délky textu
IDF_TEXT_ADD,				"unión de textos",																					// operátor pro slouèení textù
IDF_TEXT_SCAN,				"conversión de número de formato texto",															// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"conversión de número a formato texto",																// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"comparación alfabética de textos",																	// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"convertir a minúsculas",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"convertir a mayúsculas",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"buscar posición en texto (-1 = no se encuentra)",													// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"texto de entrada",																					// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"texto buscado",																					// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"texto informativo",																				// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"barra superior de la ventana",																		// titulek hlavního okna (textová promìnná)
IDF_ORD,					"convertir carácter a código numérico",																// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"convertir código numérico a carácter",																// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"sonido",																							// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"ejecutar sonido",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"parar sonido (por defecto, todos)",																// vypnutí zvuku
IDF_COLOR,					"color",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"gráfico",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"color del lápiz",																					// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"grosor del lápiz",																					// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"punto",																							// nakreslení grafického bodu
IDF_POINT_X,				"horizontal, coordenada X del punto",																// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertical, coordenada Y del punto",																	// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"línea",																							// nakreslení èáry
IDF_LINE_X1,				"horizontal, coordenada X1 de la línea",															// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertical, coordenada Y1 del punto",																// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horizontal, coordenada X2 de la línea",															// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertical, coordenada Y2 de la línea",																// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"cuadro",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horizontal, coordenada X1 del cuadro",																// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertical, coordenada Y1 del cuadro",																// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horizontal, coordenada X2 del cuadro",																// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertical, coordenada Y2 del cuadro",																// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"cuadro relleno",																					// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horizontal, coordenada X1 del cuadro relleno",														// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertical, coordenada Y1 del cuadro relleno",														// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horizontal, coordenada X2 del cuadro relleno",														// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertical, coordenada Y2 del cuadro relleno",														// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"relleno",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horizontal, coordenada X del relleno",																// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertical, coordenada Y del relleno",																// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"círculo",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horizontal, coordenada X del centro",																// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertical, coordenada Y del centro",																// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"radio",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"círculo relleno",																					// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horizontal, coordenada X del centro",																// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertical, coordenada Y del centro",																// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"radio",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"triángulo",																						// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horizontal, coordenada X1 del triángulo",															// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertical, coordenada Y1 del triángulo",															// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horizontal, coordenada X2 del triángulo",															// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertical, coordenada Y2 del triángulo",															// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horizontal, coordenada X3 del triángulo",															// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertical, coordenada Y3 del triángulo",															// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"esfera",																							// nakreslení koule
IDF_SPHERE_X,				"horizontal, coordenada X del centro",																// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertical, coordenada Y del centro",																// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"radio",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"cambiar la componente brillo",																		// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"componente brillo (0 a 1)",																		// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"tecla de entrada (espera que se presione)",														// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"carácter de entrada (espera que se presione)",														// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"no hay tecla pulsada",																				// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"tecla Windows derecha",																			// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Shift dcho",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"Ctrl dcho",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"Alt dcho",																							// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"estado de Bloq Num",																				// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"estado de Bloq Mayús",																				// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"estado de Bloq Despl",																				// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"estado de Insert",																					// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"click con el botón izquierdo",																		// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"click con el botón derecho",																		// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"doble click con el botón izquierdo",																// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"doble click con el botón derecho",																	// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"test de ratón en la región",																		// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horizontal, coordenada X de comienzo de la región",												// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertical, coordenada Y de comienzo de la región",													// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"ancho de la región",																				// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"alto de la región",																				// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"visualizar texto",																					// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horizontal, coordenada X del texto",																// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertical, coordenada Y del texto",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"ángulo de orientación del texto",																	// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"alto de los caracteres",																			// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"ancho relativo de los caracteres (1 = normal)",													// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"negrita",																							// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"cursiva",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"subrayada",																						// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"tachada",																							// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"marbetes",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"máquina de escribir",																				// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"texto que se muestra",																				// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"número de líneas de texto",																		// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"línea de texto",																					// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"número de la línea de texto",																		// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"prueba de sonido (por defecto = todos los sonidos)",												// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"número de repeticiones (0 = permanentemente)",														// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"objeto en la posición de Peter",																	// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"objeto en la posición de Lucy",																	// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"dibujar",																							// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"objeto que se dibuja",																				// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horizontal, coordenada X del dibujo",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertical, coordenada Y del dibujo",																// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horizontal, coordenada X del recorte",																// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertical, coordenada Y del recorte",																// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"ancho del recorte",																				// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"alto del recorte",																					// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"pasar recorte de hoja a dibujo",																	// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"pasar recorte de hoja a objeto",																	// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"idioma (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"sonido que se ejecuta",																			// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"volumen del sonido (0 a 1)",																		// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"balance estereofónico (-1 = izda a +1 = dcha)",													// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"parar sonido",																						// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"comentario",																						// komentáø
IDF_SOUND_FUNCTIONS,		"funciones de sonido",																				// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"configurar aspecto del puntero",																	// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"dibujo del puntero (por defecto = original)",														// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horizontal, coordenada X del comienzo de la región",												// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertical, coordenada Y del comienzo de la región",													// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"ancho de la región",																				// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"alto de la región",																				// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"ejecutar música",																					// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"ejecutar música repetidamente",																	// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"parar música",																						// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"pausa/continuar música",																			// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test de música",																					// test pøehrávání hudby
IDF_MUSIC_POS,				"posición en el tiempo de duración",																// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"duración de la música",																			// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"componentes del color",																			// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"componente rojo (0 a 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"componente verde (0 a 1)",																			// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"componente azul (0 a 1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"leer color del pixel",																				// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horizontal, coordenada X del pixel que se lee",													// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertical, coordenada Y del pixel que se lee",														// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"al cuadrado",																						// funkce druhá mocnina
IDF_MUSIC_GROUP,			"música",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"CD audio",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"arrancar CD desde la pista solicitada (por defecto = 1)",											// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"parar CD",																							// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"pausa/continuar CD",																				// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test del CD",																						// test pøehrávání CD
IDF_CD_LENGTH,				"longitud total",																					// celková délka CD
IDF_CD_TRACKS,				"número de pistas",																					// poèet stop CD
IDF_CD_POS,					"posición desde el comienzo",																		// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"pista que se ejecuta",																				// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"duración de la pista actual",																		// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"posición desde el comienzo de la pista",															// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"ficheros",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"operaciones básicas",																				// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"nuevo fichero",																					// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"nueva carpeta",																					// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"borrar fichero o carpeta",																			// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"probar si existe",																					// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"disco y carpeta activos",																			// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"capacidad de disco",																				// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"espacio libre en disco",																			// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"etiqueta de disco",																				// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"número de serie de disco",																			// zjištìní sériového èísla disku
IDF_FILE_READ,				"fichero/carpeta activos para lectura",																// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"fichero/carpeta activos para escritura",															// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"copiar fichero",																					// provedení kopie souboru
IDF_FILE_MOVE,				"mover/renombrar fichero (carpeta)",																// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disco",																							// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"atributos",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"atributo R/O (sólo lectura)",																		// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"atributo HID (oculto)",																			// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"atributo SYS (sistema)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"atributo DIR (carpeta)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"atributo ARC (fichero)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"atributo TEMP (temporal)",																			// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"atributo COMP (comprimido)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"atributo OFF (fuera de línea)",																	// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"fecha y hora de creación",																			// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"fecha y hora del último acceso",																	// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"fecha y hora de la última modificación",															// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"datos",																							// skupina dat souborù
IDF_FILE_BYTES,				"número entero con signo, 1 byte",																	// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"número entero sin signo, 1 byte",																	// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"número entero con signo, 2 bytes",																	// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"número entero sin signo, 2 bytes",																	// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"número entero con signo, 4 bytes",																	// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"número entero sin signo, 4 bytes",																	// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"número decimal, 4 bytes",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"número decimal, 8 bytes",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"texto acabado con nulo binario (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"texto acabado con fin de línea",																	// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"texto de longitud fija",																			// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"objeto (ICO)",																						// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"dibujo (BMP, JPG)",																				// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"sonido (WAV, MP3)",																				// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"música (MID, RMI)",																				// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"puntero de lectura",																				// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"puntero de escritura",																				// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"fecha y hora",																						// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"fecha y hora actual (número de segundos desde el 1 de Enero de 1601)",								// aktuální datum a èas
IDF_DATETIME_UTC,			"convertir hora local a hora internacional",														// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"convertir hora internacional a hora local",														// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"unir fecha y hora",																				// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"año",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"mes",																								// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"día",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"hora",																								// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minuto",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"segundo",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"milisegundo",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"año desde fecha y hora",																			// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"mes desde fecha y hora",																			// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"día desde fecha y hora",																			// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"día de la semana desde fecha y hora (0 = domingo, 1 = lunes, ...)",								// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"hora desde fecha y hora",																			// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minuto desde fecha y hora",																		// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"segundo desde fecha y hora",																		// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"milisegundo desde fecha y hora",																	// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"convertir fecha a texto \"día.mes.año\"",															// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"convertir fecha a texto \"mes/día/año\"",															// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"convertir fecha a texto \"año-mes-día\"",															// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"convertir hora a texto \"hora:minuto:segundo\" (24 horas)",										// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"convertir hora a texto \"hora:minuto:segundo x\" (12 horas)",										// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"tamaño de fichero",																				// velikost souboru
IDF_FILE_ERROR,				"flag de error en la operación",																	// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"longitud del texto de longitud fija",																// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"tipo de disco (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",													// zjištìní typu disku
IDF_TEXT_FORMAT2,			"convertir número a texto - 2 dígitos",																// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"convertir número a texto - 8 dígitos HEX",															// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"número entero con signo, 3 bytes",																	// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"número entero sin signo, 3 bytes",																	// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"mensajes",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"mensajes de confirmación (devuelve 1=OK, 2=Cancelar, 3=Abortar, 4=Reintentar, 5=Ignorar, 6=Sí, 7=No)",	// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"texto",																							// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"encabezamiento",																					// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"icono (0=nada, 1=error, 2=pregunta, 3=precaución, 4=información)",									// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"botones (0=OK, 1=OK/Cancelar, 2=Abortar/Reintentar/Ignorar, 3=Sí/No/Cancelar, 4=Sí/No, 5=Reintentar/Cancelar)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"botón por defecto (1 a 3)",																		// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"siguiente línea",																					// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"introducir texto",																					// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1ª línea de mensaje",																				// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2ª línea de mensaje",																				// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3ª línea de mensaje",																				// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"texto listo para introducir",																		// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"expulsar CD",																						// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"número de bits por muestra (8 ó 16)",																// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"frecuencia de muestreo (Hz)",																		// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"¿es estereofónico?",																				// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"duración del sonido (segundos)",																	// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"convertir a 8 bits",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"convertir a 16 bits",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"convertir a estéreo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"convertir a mono",																					// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"convertir a 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"convertir a 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"convertir a 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"mezcla de sonidos",																				// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"cambiar velocidad de sonido",																		// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"sonido que se convierte",																			// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"cambio relativo de velocidad (1 = sin cambios)",													// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"generador de tonos",																				// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"frecuencia de tono (Hz)",																			// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"duración de tono (segundos)",																		// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"hoja",																								// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"ancho de hoja",																					// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"alto de hoja",																						// zjištìní vıšky plochy
IDF_MAP_X,					"coordenada X",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"coordenada Y",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"hoja",																								// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"objeto",																							// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"valor numérico 1 (rango 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"valor numérico 2 (rango 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"valor numérico 3 (rango 0 a 127)",																	// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"flag 1",																							// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"flag 2",																							// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"flag 3",																							// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"flag 4",																							// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"flag 5",																							// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"copiar recorte de la hoja",																		// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"hoja con recorte",																					// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"coordenada X del recorte",																			// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"coordenada Y del recorte",																			// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"ancho del recorte",																				// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"alto del recorte",																					// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"consola",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"mover todas las animaciones en dirección X",														// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"mover todas las animaciones en dirección Y",														// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"borde izquierdo de la ventana de animaciones",														// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"borde inferior de la ventana de animaciones",														// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"borde derecho de la ventana de animaciones",														// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"borde superior de la ventana de animaciones",														// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"modo consola (debe usarse al comienzo de la función principal)",									// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"salida de texto a consola",																		// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"entrada de texto desde consola",																	// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"salida de mensaje de error a consola",																// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"parámetro de programa (0 = nombre del programa)",													// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"nombre del programa con ruta completa",															// jméno tohoto programu s plnou cestou
IDF_EXEC,					"ejecución del programa",																			// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"ejecución del programa con espera",																// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"joystick",																							// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"coordenada X del joystick",																		// souøadnice X joysticku
IDF_JOYSTICK_Y,				"coordenada Y del joystick",																		// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"coordenada Z del joystick",																		// souøadnice Z joysticku
IDF_JOYSTICK_1,				"botón 1 del joystick",																				// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"botón 2 del joystick",																				// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"botón 3 del joystick",																				// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"botón 4 del joystick",																				// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"textos y dibujos",																					// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"número del elemento (0 = ventana principal)",														// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"borrar elemento/ventana",																			// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"crear ventana",																					// vytvoøení dialogového okna
IDF_WINDOW_X,				"coordenada horizontal",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"coordenada vertical",																				// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"ancho",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"alto",																								// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"texto",																							// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"visible",																							// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"deshabilitar",																						// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"crear botón",																						// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"botón pulsado o cambio del elemento",																// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"crear cuadro de opción",																			// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"crear línea de edición",																			// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"crear selector",																					// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"funciones comunes para todos los elementos",														// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"crear campo de edición",																			// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"botones",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"activar o no",																						// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"foco de entrada",																					// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"crear botón por defecto",																			// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"crear botón de icono",																				// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"crear marco",																						// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"crear lista",																						// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"crear texto",																						// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"crear lista desplegable",																			// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"crear lista desplegable con edición",																// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"negrita",																							// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"ancho de letra fijo",																				// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"crear selector - primero de grupo",																// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"listas",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"añadir entrada a lista",																			// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"vaciar lista",																						// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"crear lista con edición",																			// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"crear cuadro de opción triestado",																	// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"conmutar a estado indefinido",																		// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"crear ventana sin posibilidad de cierre",															// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"icono",																							// ikona prvku dialogového okna
IDF_WINICON_NEW,			"crear icono",																						// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"animación (SPR)",																					// sprajt (data ze souboru)
IDF_2PI,					"2*pi (= 360 grados)",																				// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"distancia de 1 pixel (=1/32 paso)",																// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"fase",																								// fáze sprajtu
IDF_SPRITE_STATUS,			"estado",																							// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"modo pantalla completa",																			// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"limpiar buffer de teclas",																			// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"instante en ejecución del sonido",																	// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"pausa/continuar sonando",																			// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"lista de ficheros",																				// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"idéntica hoja",																					// operátor porovnání ploch
IDF_EQU_PIC,				"idéntico dibujo",																					// operátor porovnání obrázkù
IDF_EQU_SPR,				"idéntica animación",																				// operátor porovnání sprajtù
IDF_EQU_SND,				"idéntico sonido",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"idéntica música",																					// operátor porovnání hudeb
IDF_NET_GROUP,				"comunicación",																						// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"soporte de red DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"lista de conexiones",																				// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"conexión activa",																					// aktivní spojení DirectPlay
IDF_GAME_LIST,				"lista de juegos",																					// seznam bìících her DirectPlay
IDF_GAME_ACT,				"juego activo",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"lista de jugadores",																				// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"jugador activo",																					// aktivní hráè DirectPlay
IDF_GAME_N1,				"parámetro numérico de juego 1 (-16384 a +16383)",													// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"parámetro numérico de juego 2 (-16384 a +16383)",													// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"parámetro numérico de juego 3 (-16384 a +16383)",													// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"parámetro numérico de juego 4 (-16384 a +16383)",													// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"parámetro numérico de juego 5 (-16384 a +16383)",													// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"parámetro numérico de juego 6 (-16384 a +16383)",													// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"parámetro numérico de juego 7 (-16384 a +16383)",													// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"parámetro numérico de juego 8 (-16384 a +16383)",													// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"flag de juego 1",																					// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"flag de juego 2",																					// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"flag de juego 3",																					// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"flag de juego 4",																					// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"flag de juego 5",																					// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"flag de juego 6",																					// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"flag de juego 7",																					// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"flag de juego 8",																					// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"configuración del juego",																			// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"servidor (ordenador de control)",																	// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"máximo de jugadores (0 = sin límite)",																// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"número de jugadores activos (-1 = ninguno)",														// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"datos",																							// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"enviar/recibir bloque de datos (-1 = a todos/ninguno)",											// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"número",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"texto",																							// text dat DirectPlay
IDF_GAME_DATAL,				"flag",																								// pøepínaè dat DirectPlay
IDF_GAME_IP,				"dirección IP de este ordenador",																	// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"número entero 0 a 255 (byte)",																		// èíslo bajt dat DirectPlay
IDF_INC,					"incremento (añade 1)",																				// funkce inkrementace èísla
IDF_DEC,					"decremento (resta 1)",																				// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"crear texto centrado",																				// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"botón para la tecla Esc (-1 = ninguno)",															// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"ancho de dibujo",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"alto de dibujo",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"voltear dibujo horizontalmente",																	// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"voltear dibujo verticalmente",																		// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"dibujos",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"cambiar tamaño de dibujo",																			// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"dibujo",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"ancho (por defecto = proporcional al alto)",														// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"alto (por defecto = proporcional al ancho)",														// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"mejorar bordes",																					// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"difuminado (fotografía)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"dibujar",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"crear dibujo",																						// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"dibujo",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"crear editor RTF",																					// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"alto de caracteres (0 = normal)",																	// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"cursiva",																							// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"subrayada",																						// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"tachada",																							// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"marbetes",																							// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"ancho relativo de caracteres (0 = normal, 1 = básico)",											// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"ángulo de pendiente del texto",																	// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"crear texto alineado a la derecha",																// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"color de carácter",																				// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"color de fondo",																					// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"tipo de letra del elemento",																		// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"velocidad de ejecución (1 = normal)",																// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"código sonido (0 a 65535)",																		// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"introducir fichero que se abre",																	// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"introducir fichero que se graba",																	// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"introducir texto que se busca",																	// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"introducir color",																					// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"máscara de fichero",																				// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"nombre de fichero preparado",																		// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"nombre del tipo de ficheros",																		// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"cambiar brillo de dibujo",																			// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"dibujo que cambia de brillo",																		// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"brillo de dibujo (1 = normal)",																	// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"rotar dibujo",																						// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"dibujo que se rota",																				// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"ángulo de rotación",																				// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"descompresión de sonido",																			// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"texto en formato UNICODE (2 bytes)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"convertir hoja a dibujo",																			// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"convertir objeto a dibujo",																		// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"operaciones binarias",																				// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"AND producto binario",																				// bitovı (binární) souèin AND
IDF_BIT_OR,					"OR suma binaria",																					// bitovı (binární) souèet OR
IDF_BIT_XOR,				"XOR inversión binaria",																			// bitová (binární) inverze XOR
IDF_BIT_NOT,				"NOT complemento binario",																			// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"máximo número binario (palabra doble)",															// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"rotar bit a izquierda",																			// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"rotar bit a derecha",																				// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"comprobar ratón en elemento",																		// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"ancho interno",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"alto interno",																						// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"juego de carácter (1250=europa este, 1251=ruso, 1252=oeste)",										// èíslo pouité znakové sady fontù
IDF_USERFONT,				"tipo de letra de usuario",																			// jméno uivatelského fontu
IDF_ENUMFONTS,				"lista de tipo de letra",																			// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"nueva hoja",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"ancho de hoja",																					// šíøka nové plochy
IDF_MAP_NEW_H,				"alto de hoja",																						// vıška nové plochy
IDF_WINDOW_TOP,				"siempre arriba",																					// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"nickname (alias)",																					// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"puerto de comunicaciones",																			// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"abrir puerto (-1=error)",																			// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"cerrar puerto",																					// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"puerto activo",																					// aktivní port
IDF_COM_NUM,				"número (0 a 255)",																					// vstup/vıstup èísla
IDF_COM_TEXT,				"carácter (texto)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"velocidad de régimen binario",																		// pøenosová rychlost
IDF_COM_STOP,				"2 bits de parada",																					// reim s 2 stopbity
IDF_COM_BITS,				"número de bits (5 a 8)",																			// poèet bitù na znak
IDF_COM_PARIT,				"paridad (0=ninguna, 1=impar, 2=par)",																// zvolená parita
IDF_COM_IN,					"carácter recibido",																				// byl pøijatı znak
IDF_COM_SEND,				"envío permitido (CTS, RTS)",																		// povoleno vysílání
IDF_COM_RECEIVE,			"recepción permitida (DSR, DTR)",																	// povolen pøíjem
IDF_PICTURE_MASK,			"máscara de dibujo",																				// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"dibujo",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"máscara",																							// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"ancho de campo para visualizar texto (0 = ninguno)",												// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"crear campo de edición sin salto",																	// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"ventana que puede cambiar su tamaño",																// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"ventana que puede cerrarse",																		// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"ventana maximizada",																				// maximalizace okna
IDF_WINDOW_MINIM,			"ventana minimizada",																				// minimalizace okna
IDF_PROGRESS_NEW,			"crear barra de progreso",																			// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"crear barra de arrastre horizontal",																// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"crear barra de arrastre vertical",																	// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"posición actual",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"mesa de mezclas",																					// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"mesa de mezclas",																					// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"salida de línea",																					// volba cílového signálu
IDF_MIX_LINE_SRC,			"entrada de línea (nada=sólo salida de línea)",														// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"tipo de línea",																					// zjištìní typu signálu
IDF_MIX_CONTROL,			"objeto de control",																				// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"tipo de objeto de control",																		// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"valor del objeto de control (0 a 1)",																// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"selección del valor del objeto",																	// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"canal controlado (-1=todos)",																		// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"gráficos 3D",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"ventana de gráficos 3D",																			// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"coordenada X de la ventana de gráficos 3D",														// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"coordenada Y de la ventana de gráficos 3D",														// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"ancho de la ventana de gráficos 3D",																// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"alto de la ventana de gráficos 3D",																// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"modo de video (ancho*alto/bits)",																	// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"fondo gráfico",																					// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"configuraciones",																					// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"superficies de relleno",																			// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"iluminación",																						// mód osvìtlení
IDF_DIRECT3D_SHADES,		"sombreado suave",																					// mód stínování
IDF_DIRECT3D_INVERT,		"inversión de objeto",																				// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objetos",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"pared",																							// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"cubo",																								// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"esfera",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"cilindro",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"cono",																								// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"clonar",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"objeto desde texto",																				// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"objeto desde fichero",																				// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"activar objeto (0=escena, 1=cámara, 2=luz)",														// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"borrar objeto",																					// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"visible",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"enlace",																							// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"objeto a fichero",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformaciones",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"dimensionar en dirección X",																		// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"dimensionar en dirección Y",																		// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"dimensionar en dirección Z",																		// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"rotación alrededor del eje X",																		// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"rotación alrededor del eje Y",																		// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"rotación alrededor del eje Z",																		// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"traslación en dirección X",																		// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"traslación en dirección Y",																		// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"traslación en dirección Z",																		// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"superficie",																						// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"color (-1=interno, -2=por defecto)",																// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"emisión del color",																				// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"oscurecimiento (0=off, 5=metal, 50=plástico)",														// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"reflectancia del color",																			// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"textura",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"trazado de la textura",																			// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"tipo de proyección (0=plano, 1=cilindro, 2=esfera, 3=cromatada, 4=lentes)",						// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"coordenada X del centro de proyección",															// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"coordenada Y del centro de proyección",															// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"coordenada Z del centro de proyección",															// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"rotación de la proyección alrededor del eje X",													// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"rotación de la proyección alrededor del eje Y",													// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"rotación de la proyección alrededor del eje Z",													// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"transparencia (1=normal, 11=fuego, 20=cristal, 54=superpuesta)",									// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"contornos (0=normal, 0.5=contornos)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"método (0=direcciones, 1=vértices, 2=caras)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"origen horizontal de la textura",																	// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"origen vertical de la textura",																	// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"degradado horizontal de la textura",																// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"degradado vertical de la textura",																	// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"iluminación",																						// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"crear nueva luz",																					// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"color de luz",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"tipo de luz (1=punto, 2=foco, 3=direccional)",														// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"ángulo del cono de luz",																			// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"ángulo de penumbra",																				// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"rango de luz",																						// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"intensidad de luz (1=normal)",																		// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"atenuación lineal",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"atenuación cuadrado",																				// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"tipo de proyección (0=persp, 1=orto, 2=r-persp, 3=r-orto)",										// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"escena",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"color de la escena de fondo (-1=off, -2=sin iniciar)",												// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"textura de la escena de fondo",																	// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"color de niebla (-1=off)",																			// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"tipo de niebla (0=lin, 1=exp, 2=cuadr, +4=corrección)",											// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"comienzo de niebla lineal",																		// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"fin de niebla lineal",																				// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"densidad de niebla exp. y cuadr. (0 a 1)",															// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"distancia del plano de proyección",																// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"horizonte visual",																					// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"crear base superior",																				// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"crear base inferior",																				// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"buscar objeto",																					// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"coordenada X del punto",																			// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"coordenada Y del punto",																			// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"filtro de disminución de textura",																	// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"objeto 2D",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terreno desde dibujo",																				// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"nivel de terreno",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"coordenada horizontal",																			// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"coordenada vertical",																				// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"grupo",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"complejidad del objeto (2 a 100)",																	// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"orden de rotaciones (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",									// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"driver (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"objeto rotatorio",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terreno desde hoja",																				// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"reflexión de luz ambiente (-1=por defecto)",														// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"el programa es la aplicación activa",																// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"distancia de punto",																				// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"ángulo de punto",																					// vıpoèet úhlu bodu
IDF_POLAR_X,				"coordenada X de punto",																			// souøadnice X bodu
IDF_POLAR_Y,				"coordenada Y de punto",																			// souøadnice Y bodu
IDF_FILE_LOGIC,				"valor lógico",																						// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"suavizado de texturas (1=no)",																		// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"contador de tiempo preciso",																		// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"luz ambiente",																						// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"filtro de aumento de textura",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"filtro de alejamiento de textura",																	// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"rellenar superficies del objeto",																	// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"iluminación del objeto",																			// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"sombreado gradual del objeto",																		// mód stínování
IDF_DIRECT3D_OMINFILTER,	"filtro de disminución de textura del objeto",														// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"filtro de aumento de textura del objeto",															// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"filtro de alejamiento de textura del objeto",														// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"lado visible del objeto (0=ambos, 1=delantero, 2=trasero)",										// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"crear",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"normalización del objeto",																			// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"círculo",																							// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"triángulo",																						// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"toroide (parámetro = diámetro 0 a 1)",																// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"objeto estático 2D",																				// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"semiesfera",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interfaz (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",								// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"tiempo transcurrido",																				// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"velocidad de trazado 3D",																			// rychlost renderování
IDF_DIRECT3D_FREE,			"videomemoria libre",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"dibujo 2D",																						// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"texturas",																							// skupina textur
IDF_DIRECT3D_STAGE,			"capas (0 a 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"operación con color (1=off, 2=arg1, 3=arg2, 4-6=PROD, 7-11=SUMA)",									// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"primer argumento del color (0=color, 1=resultado, 2=textura, 3=factor, 16=complemento)",			// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"segundo argumento del color (0=color, 1=resultado, 2=textura, 3=factor, 16=complemento)",			// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"operación con alfa (1=off, 2=arg1, 3=arg2, 4-6=PROD, 7-11=SUMA)",									// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"primer argumento de alfa (0=color, 1=resultado, 2=textura, 3=factor, 16=complemento)",				// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"segundo argumento de alfa (0=color, 1=resultado, 2=textura, 3=factor, 16=complemento)",			// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"modo de dirección horizontal (1=repetir, 2=espejo, 3=enmarcado)",									// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"modo de dirección vertical (1=repetir, 2=espejo, 3=enmarcado)",									// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"borrosidad del alejamiento de texturas (0=por defecto)",											// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"cono truncado (parámetro = diámetro 0 a 1)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"color del factor de textura",																		// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"componente alfa (0=transparencia a 1=color)",														// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"número de texturas de alejamiento (0=todas)",														// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"grupo de trazado 3D (0-7=objetos, 8-11=transparente, 12-15=dibujos)",								// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"nivel de profundidad del grupo de trazado 3D",														// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"guardar la información de profundidad",															// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"test de profundidad (1 nunca, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 siempre)",						// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"calcular normales (parámetro = ángulo de suavizado)",												// pøepoèet normál
IDF_DIRECT3D_RENDER,		"trazado 3D sin mostrar",																			// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"bloque de texto",																					// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"línea del comienzo de bloque",																		// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"posición del comienzo del bloque",																	// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"línea del fin de bloque (-1=final)",																// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"posición del fin de bloque (-1=final)",															// pozice konce bloku
IDF_WINDOW_POS2,			"posición 2 actual ",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"crear botón conmutador",																			// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"crear tabla (parámetro = lista de títulos)",														// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"ancho de columna de tabla",																		// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"grado de sombra (0=off)",																			// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"alineado de columna de tabla (0=izq, 1=dch, 2=centr)",												// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"crear barra de desplazamiento horizontal",															// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"crear barra de desplazamiento vertical",															// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"intercambio de colores",																			// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"primer color",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"segundo color",																					// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"sustituir color",																					// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"color antiguo",																					// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"color nuevo",																						// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"imprimir dibujo",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"objeto con reducido nivel de detalle (-1=ninguno)",												// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"distancia para reducción del nivel de detalle",													// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"añadir patrón para transfiguración (-1=reset)",													// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"etapa de transfiguración (0...1...2...)",															// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"lens flare",																						// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dynamic data exchange DDE",																		// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"server name/list of servers",																		// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"topic name/list of topics",																		// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"entry name/list of entries",																		// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"program provides entry (it is server)",															// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"type of entry (0 to 7, -1=invalid entry)",															// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) number",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) flag",																							// pøíznak DDE
IDF_DDE_TEXT,				"(2) text",																							// text DDE
IDF_DDE_ICON,				"(3) item",																							// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) picture",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) sound",																						// zvuk DDE
IDF_DDE_MUSIC,				"(6) music",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"command to execute",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL libraries",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"load library",																						// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"free library",																						// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"import function",																					// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"library identifier",																				// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"function name",																					// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"number of parameters",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"execute function",																					// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"create memory block",																				// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"free memory block",																				// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"change size of memory block",																		// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"address of memory block",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"new size",																							// nová velikost bloku pamìti
IDF_MEMORY_READ,			"read pointer",																						// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"write pointer",																					// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"data copy",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"data comparison",																					// porovnání bloku dat
IDF_MEMORY_BYTES,			"byte with sign",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"byte without sign",																				// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"word with sign",																					// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"word without sign",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-byte with sign",																					// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-byte without sign",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"doubleword with sign",																				// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"doubleword without sign",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"decimal number 4 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"decimal number 8 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logical value",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"text terminated by null",																			// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"pointer to text terminated by null",																// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"text with fixed length",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"length of text with fixed length",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"read data from file",																				// ètení dat ze souboru
IDF_MEMORY_SAVE,			"write data to file",																				// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identifier of window element",																		// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"calling convention C",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"crear tabs",																						// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"configuration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"configuration fike",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"parameter section",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"parameter name",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"read/write text prameter",																			// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"read/write integer prameter",																		// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"key group (1=CURRENT_USER, 2=LOCAL_MACHINE)",														// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"key name",																							// plnı mázev klíèe registrù
IDF_REG_VALUE,				"entry name",																						// název datové poloky
IDF_REG_STRING,				"read/write text entry",																			// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"read/write integer entry",																			// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"create 3D object from memory blocks",																// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"number of vertices",																				// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"vertices",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normals (0=auto)",																					// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"texture mapping (0=none)",																			// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"colors (0=none)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"number of faces",																					// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"faces",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"texture from file",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"memory block from 3D object",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"find child (-1=first, -2=parent)",																	// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
