// Francouzsky (Français)
// 1252
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Variables et Fonctions Globales",																	// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Variables et Fonctions Locales",																	// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Eléments de base, Corbeille",																		// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Bibliothèque des variables et fonctions",															// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"variables et fonctions de base",																	// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Nouveau Programme",																				// implicitní název nového programu
IDN_NEWDIR_NAME,			"Nouveau Dossier",																					// implicitní název nové sloky
IDN_TEXTVZOR,				"[exemples]",																						// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Utilisés",																							// zobrazuje poèet pouití prvku
IDT_RADEK,					"ligne",																							// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"colonne",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"activé",																							// text editoru hodnoty pøepínaèe
IDN_DATUM,					"date",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"heure",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"taille",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"libres",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"répétition",																						// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"répété",																							// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMONSTRATION",																					// oznaèení DEMO verze
IDN_PROFI,					"Professionnel",																					// oznaèení verze Professional
IDN_LITE,					"Version allégée",																					// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Fichiers",																						// volba k vyvolání menu "Soubor"
IDN_START0,					"Dé&marrer\tF5",																					// volba pro spuštìní programu
IDN_START,					"Démarre le programme.\nDémarrer",																	// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Ouvrir\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Ouvre le programme pour l\'éditer (modifier).\nOuvrir",											// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Nouveau...\tCtrl+N",																				// volba pro zaloení nového programu
IDN_NEW,					"Crée un nouveau programme.\nNouveau",																// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"&Renommer...\tAlt+Entrée",																			// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Renomme le programme/dossier (ne peut renommer des programmes et des dossiers d\'exemple).\nRenommer",	// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"&Copier...\tCtrl+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Copie le programme sélectionné sous un autre nom.\nCopier",										// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"Nouveau &Dossier...\tCtrl+P",																		// volba k vytvoøení nové sloky
IDN_PATH,					"Crée un nouveau dossier pour les programmes.\nNouveau Dossier",									// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Supprimer...\tSupprimer",																			// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Supprime le programme ou le dossier (ne peut supprimer les programmes et les dossiers d\'exemple ).\nSupprimer",	// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Noms Co&urts",																						// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Les fichiers de programmes ou de la bibliothèque auront des noms raccourcis (8 caractères).\nNoms Raccourcis",	// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Quitter\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Quitter PETER.\nQuitter",																			// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"Définir &Police de caractères",																	// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Police de caractères de &Sélectionner le Programme...",											// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Modifie police dans fenêtre \"Sélectionner le programme\".\nPolice de \"Sélectionner le Programme\"",	// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Police de l\'&Editeur de programme...",															// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Modifie police dans fenêtre \"Editeur de programme\".\nPolice Editeur de Programme",				// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Police de l\'Editeur de &Texte...",																// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Modifie la police dans fenêtre \"Editeur de texte\".\nPolice Editeur de Texte",					// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Police du &Menu...",																				// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Modifie police du Menu.\nPolice du Menu",															// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Police &Barre d\'Etat ...",																		// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Modifie police barre d\'état.\nPolice Barre d\'Etat",												// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&Langue",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automatique",																						// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Sélection automatique de la langue selon configuration système.\nAutomatique",						// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Précédent\tCtrl+F9",																				// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Bascule entre les deux langues dernièrement utilisées.\nPrécédent",								// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Bulgare (Bulgarija)",																				// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Bascule le programme Peter en langue bulgare.\nBulgare",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"&Tchèque (Cesky)",																					// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Bascule le programme Peter en langue tchèque.\nTchèque",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"&Danois (Danmark)",																				// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Bascule le programme Peter en langue danoise.\nDanois",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"A&llemand (Deutsch)",																				// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Bascule le programme Peter en langue allemande.\nAllemand",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Grec (Hellàs)",																					// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Bascule le programme Peter en langue grecque.\nGrec",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"Angla&is (English)",																				// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Bascule le programme Peter en langue anglaise.\nAnglais",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"Spa&nish (España)",																				// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Bascule le programme Peter en langue espagnole.\nEspagnol",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finlandais (Suomi)",																				// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Bascule le programme Peter en langue finnoise.\nFinlandais",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"Français",																							// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Bascule le programme Peter en langue française.\nFrançais",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"&Hongrois (Magyar)",																				// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Bascule le programme Peter en langue hongroise.\nHongrois",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Islandais (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Bascule le programme Peter en langue islandaise.\nIslandais",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Italian (Italy)",																					// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Bascule le programme Peter en langue italienne.\nItalien",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Néerlandais (Nederland)",																			// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Bascule le programme Peter en langue néerlandaise.\nNéerlandais",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Norvégien (Norge)",																				// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Bascule le programme Peter en langue norvégienne.\nNorvégien",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Polish (Po polsku)",																				// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Bascule le programme Peter en langue polonaise.\nPolonais",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portugais (Portugal)",																				// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Bascule le programme Peter en langue portugaise.\nPortugais",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Roumain (România)",																				// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Bascule le programme Peter en langue roumaine.\nRoumain",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&Russe (Po-rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Bascule le programme Peter en langue russe.\nRusse",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Serbo-Croate (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Bascule le programme Peter en langue serbo-croate.\nSerbo-Croate",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"&Slovak (Po slovensky)",																			// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Bascule le programme Peter en langue slovaque.\nSlovaque",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albanian (Shqipërisë)",																			// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Bascule le programme Peter en langue albanaise.\nAlbanais",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Suédois (Swerige)",																				// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Bascule le programme Peter en langue suédoise.\nSuédois",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Turc (Türkiye)",																					// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Bascule le programme Peter en langue turque.\nTurc",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"&Vietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Aide",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Aide\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Affiche l\'aide pour l\'élément sélectionné.\nAide",												// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"&Contenu de l\'aide",																				// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Affiche le contenu de l\'Aide.\nContenu de l\'Aide",												// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Rechercher dans l\'Aide",																			// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Rechercher dans l\'Aide.\nRechercher dans l\'Aide",												// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"Au &sujet de Peter",																				// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Affiche des informations sur le programme Peter, numéro de version et copyright.\nAu sujet de Peter",	// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Fermer\tCtrl+O",																					// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Ferme le programme édité et en ouvre un autre.\nFermer",											// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Enregistrer\tCtrl+S",																				// volba k uloení programu pøi editaci
IDN_SAVE,					"Sauvegarde les modifications opérées dans le programme.\nEnregistrer",								// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"Enregistrer en tant que &Non-exécutable\tCtrl+Alt+S",												// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Enregistrer le programme comme non-exécutable (encombrement moindre).\nEnregistrer comme non-exécutable",	// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Enregistrer &sous...\tCtrl+Shift+S",																// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Enregistrer le programme dans un fichier de nom différent ou sur un autre disque.\nEnregistrer sous",	// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribution...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Sauvegarde la version distribution non modifiable (seulement avec la licence professionnelle).\nDistribution",	// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Ex&porter...",																						// volba k exportování programu
IDN_EXPORT,					"Exporte le programme sous forme de texte.\nExporter",												// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Importer...",																						// volba k importování programu
IDN_IMPORT,					"Importer un programme depuis sa forme texte.\nImporter",											// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"&Editer (modifier)",																				// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Annuler\tCtrl+Z",																					// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Annule la dernière action exécutée.\nAnnuler",														// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Refaire\tCtrl+Y",																					// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Refaire l\'action annulée auparavant.\nRefaire",													// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"Cou&per\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Couper l\'élément sélectionné et le mettre dans le presse-papiers.\nCouper",						// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Copier\tCtrl+C",																					// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Copie la sélection dans le presse-papiers.\nCopier",												// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"C&oller\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Insère le contenu du presse-papier à la position actuelle.\nColler",								// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Supprimer\tSupprimer",																			// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Supprime la sélection.\nSupprimer",																// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Sélectionner&Tout\tCtrl+A",																		// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Sélectionner tout.\nSélectionner tout",															// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Utilise le dithering lors de l\'importation et de la réduction des images\nDithering",				// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"Affi&chage",																						// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"Zoom &+\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Augmente l\'échelle de visualisation.\nZoom +",													// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Zoom &-\tCtrl+[-]",																				// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Diminue l\'échelle d\'affichage.\nZoom -",															// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"Edition &précédente\tCtrl+Haut",																	// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Retour à l\'élément édité précédemment.\nEdition précédente",										// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"Edition &suivante\tCtrl+Bas",																		// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Va à l\'élément édité suivant.\nEdition suivante",													// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Trouver le texte...\tCtrl+F",																		// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Trouver le texte indiqué.\nTrouver le texte",														// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"T&exte précédent\tMAJ+F3",																			// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Recherche de la précédente apparition du texte recherché.\nTexte précédent",						// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"Te&xte suivant\tF3",																				// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Recherche de la prochaine apparition du texte recherché.\nTexte suivant",							// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Programme",																						// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Verrouiller",																						// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Verrouillage de l\'élément contre toute modification.\nVerrouiller",								// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Désactiver",																						// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Désactive le fonctionnement de l\'élément.\nDésactiver",											// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"De&scription\tAlt+Entrée",																			// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Editer (modifier) la description de l\'élément.\nDescription",										// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Description par Dé&faut",																			// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Utiliser la description par défaut de l\'élément.\nDescription par défaut",						// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Icône",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Modifier l\'icône de l\'élément.\nIcône",															// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Icô&ne par Défaut",																				// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Utiliser l\'icône par défaut de l\'élément.\nIcône par défaut",									// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"Décl&aration",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Trouver la déclaration de l\'élément.\nDéclaration",												// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"&Précédente utilisation",																			// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Trouver une précédente utilisation de l\'élément.\nPrécédente utilisation",						// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"&Utilisation suivante",																			// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Trouver l\'utilisation suivante de l\'élément.\nUtilisation suivante",								// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Image",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"&Dimensions...",																					// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Etablit les dimensions générales.\nDimensions",													// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Raster (grille)",																					// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Active/Désactive l\'affichage du raster d\'orientation.\nRaster",									// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"&Editer...",																						// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Edite l\'image ou une partie (redimensionnement, rotation,  permuter couleurs).\nEditer",			// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Appliquer le tampon",																				// volba k otisku bloku do obrázku
IDN_OTISK,					"Applique le tampon à l\'image.\nAppliquer le tampon",												// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horizontal",																						// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Faire pivoter horizontalement l\'image ou une partie.\nHorizontal",								// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertical",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Faire pivoter verticalement l\'image ou une partie.\nVertical",									// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"&Gauche",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Rotation de l\'image à gauche (de 90 degrés en sens inverse des aiguilles d\'une montre).\nGauche",	// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"Dr&oite",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Rotation de l\'image à droite (de 90 degrés dans le sens horaire).\nDroite",						// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"Do&ubler",																							// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Multiplier par deux la taille de l\'image (ou d\'une partie).\nDoubler",							// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"D&iviser par deux",																				// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Diviser par deux la taille de l\'image (ou d\'une partie).\nDiviser par deux",						// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"Redi&mensionner...",																				// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Redimensionner l\'image (ou partie) selon vos critères.\nRedimensionner",							// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"&Permuter couleurs",																				// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Permuter dans l\'image (ou partie) les couleurs affectées aux boutons droit et gauche de la souris.\nPermuter couleurs",	// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Substitution",																					// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Remplacer dans l\'image (ou une partie) la couleur \"bouton droit de souris\'\' par la couleur \"bouton gauche\".\nSubstitution",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Outils",																							// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Stylo",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Dessiner avec le stylo.\nStylo",																	// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"&Ligne",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Dessiner une ligne.\nTrait",																		// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"&Boîte",																							// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Dessiner une boîte.\nBoîte",																		// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"Boîte &Pleine",																					// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Dessiner une boîte pleine.\nBoîte Pleine",															// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Cercle",																							// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Dessiner un cercle.\nCercle",																		// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Ce&rcle Plein",																					// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Dessiner un cercle plein.\nCercle Plein",															// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Ellipse",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Dessiner une ellipse.\nEllipse",																	// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"Ellipse plei&ne",																					// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Dessiner une ellipse pleine.\nEllipse Pleine",														// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"Sp&hère",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Dessiner une sphère.\nSphère",																		// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"Sélecti&on",																						// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Marquer la partie choisie comme sélectionnée.\nSélection",											// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"Aéro&graphe",																						// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Dessiner à l\'aérographe.\nAérographe",															// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"P&ipette",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Assigne comme couleur sélectionnée celle sous le curseur.\nPipette",								// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"Re&mplisseur",																						// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Remplir une surface avec une couleur.\nRemplisseur",												// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Texte",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Ecrire le texte.\nTexte",																			// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"E&paisseur",																						// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Epaisseur &1 Pixel",																				// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Tracer des traits épais d\'1 pixel.\nEpaisseur 1 Pixel",											// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Epaisseur &2 Pixels",																				// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Tracer des traits épais de 2 pixels.\nEpaisseur 2 Pixels",											// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Epaisseur &5 Pixels",																				// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Tracer des traits épais de 5 pixels.\nEpaisseur 5 Pixels",											// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Epaisseur &9 Pixels",																				// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Tracer des traits épais de 9 pixels.\nEpaisseur 9 Pixels",											// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Epaisseur 21 &Pixels",																				// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Tracer des traits épais de 21 pixels.\nEpaisseur 21 Pixels",										// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"Fe&uille",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Edition",																							// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Active/Désactive le mode \"édition\" des items de la feuille.\nEdition",							// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"Rem&plissage",																						// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Active/Désactive le mode \"remplissage\" de la feuille par l\'item.\nFilling",						// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Items",																							// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Editer les items situés sur la feuille.\nItems",													// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Drapeau &1",																						// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Editer le drapeau 1.\nDrapeau 1",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Drapeau &2",																						// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Editer le drapeau 2.\nDrapeau 2",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Drapeau &3",																						// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Editer le drapeau 3.\nDrapeau 3",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Drapeau &4",																						// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Editer le drapeau 4.\nDrapeau 4",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Drapeau &5",																						// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Editer le drapeau 5.\nDrapeau 5",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"Valeur &Numérique 1",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Editer la valeur numérique 1 (étendue 0 à 1023).\nValeur numérique 1",								// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"Valeur N&umérique 2",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Editer la valeur numérique 2 (étendue 0 à 1023).\nValeur Numérique 2",								// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Valeur Nu&mérique 3",																				// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Editer la valeur numérique 3 (étendue 0 à 127).\nValeur Numérique 3",								// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"&Sprite",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Propriétés",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Etablir les propriétés du sprite (nombre de phases, directions...).\nPropriétés",					// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Démarre le mode test du sprite.\nTest",															// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"&Son",																								// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Lecture (jouer le son)",																			// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Commencer à jouer le son.\nLecture",																// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"&Pause",																							// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pause dans l\'écoute.\nPause",																		// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"&Stop",																							// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Arrêt de l\'écoute.\nStop",																		// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Boucle",																							// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Active/Désactive la répétition de l\'écoute.\nBoucle",												// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Enregistrer",																						// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Commencer l\'enregistrement.\nEnregistrer",														// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Musique",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Rembobiner",																						// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Rembobiner en arrière de10 secondes.\nRembobiner",													// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Avancer",																							// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Avancer de 10 secondes.\nAvancer",																	// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"Au sujet du Programme Peter",																		// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Version de Peter",																					// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Miroslav Nemecek",															// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																						// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Roznov pod Radhostem",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"République Tchèque",																				// Èeská Republika
IDC_DEMOTEXT1,				"La version de démonstration ne peut sauvegarder ou exécuter les",									// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"programmes créés ou modifiés . Les possibilités d\'édition ,",										// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"d\'aide et d\'enregistrement dans la bibliothèque sont totalement fonctionnelles .",				// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"On peut obtenir des informations à jour sur le produit à l\'adresse Internet suivante :",			// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Les commandes peuvent être adressées à :",															// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENSE",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"illimitée",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"pour 1 ordinateur",																				// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"ordinateurs",																						// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"ordinateurs",																						// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"La version \'Lite\' (allégée) du programme Peter fournit des possibilités limitées de programmation ",	// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(les éléments non fonctionnels sont indiqués par des icônes en grisé). La version \'Lite\'",		// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"est FREEWARE et peut être distribuée et utilisée librement",										// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"pour des usages privés . Pour un usage commercial et pour les écoles le paiement d\'une licence",	// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"est nécessaire - pour plus de précisions se connecter à : www.gemtree.com.",						// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Trouver le texte",																					// titulek okna hledání textu
IDN_FINDTEXT,				"Taper le texte à rechercher :",																	// vızva k zadání textu k hledání
IDN_CANCEL0,				"Annuler",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Dimensions de la feuille",																			// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Largeur:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Hauteur:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Impossible d\'ouvrir",																				// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"Le programme ne peut être ouvert.",																// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Peut-être déja ouvert par un autre ",																// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"programme ou bien l\'accès aux données est refusé .",												// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Erreur de lecture",																				// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Erreur à la lecture du programme .",																// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"Le programme est endommagé ou a été créé avec une version",										// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"plus récente de l\'éditeur et pourrait donc ne pas fonctionner correctement .",					// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Commandes non prises en charge",																	// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Avertissement: Ce programme utilise des commandes qui ne sont pas",								// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"prises en charge par la version \'Lite\' de Peter .",												// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"La sauvegarde de ce programme le rendra peut-être inutilisable .",									// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Modifications de l\'image ou de la partie sélectionnée",											// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Pivoter",																							// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horizontalement",																					// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Verticalement",																					// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Rotation",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 degrés)",																				// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 degrés)",																				// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 degrés)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 degrés)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 degrés)",																				// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 degrés)",																				// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 degrés)",																				// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 degrés)",																				// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 degrés)",																				// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 degrés)",																				// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 degrés)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 degrés)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Redimensionner",																					// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Doubler",																							// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Diviser par deux",																					// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Optionnel (selon vos critères)",																	// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Couleurs",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Bouton Gauche <-> Bouton Droit",																	// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Bouton Gauche -> Bouton Droit",																	// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Dimensions de l\'image",																			// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Dimensions Spécifiées",																			// nadpis rámeèku volby jednotky
IDC_KROK,					"En &Pas",																							// [1] volba jednotky v krocích
IDC_BOD,					"En Pi&xels",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Redimensionner l\'image (ou une partie)",															// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Dimensions actuelles :",																			// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"pas",																								// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"pixels",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Nouvelles dimensions",																				// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Largeur :",																						// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Hauteur :",																						// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"En pas",																							// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"En pixels",																						// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"Pourcentage",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Conserver le rapport d\'origine des côtés(rapport largeur/hauteur)",								// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Affiner le pourtour (conversion précise mais lente)",												// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (ON pour photos, OFF pour dessins)",														// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Sélectionner la couleur",																			// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Erreur dans la création du programme",																// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Impossible de créer le programme. ",																// 1. øádek hlášení
IDN_JINE_JMENO,				"Essayez un autre nom.",																			// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Effacer le programme",																				// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Voulez-vous vraiment effacer le programme sélectionné ?",											// 1. øádek hlášení
IDN_SELECT_DEL2,			"ATTENTION : le programme en question va être définitivement supprimé !",							// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Suppression du dossier",																			// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Voulez-vous vraiment supprimer le dossier sélectionné ?",											// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Impossible de supprimer ce dossier ",																// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Le dossier ne peut être supprimé s\'il n\'est pas vide .",											// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Impossible de supprimer ce programme ",															// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"Ce programme ne peut être supprimé, il est protégé contre l\'écriture et l\'effacement .",			// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Nouveau dossier",																					// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Quel est le nom du nouveau dossier ?",																// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Impossible de créer le dossier ",																	// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Le dossier n\'a pu être créé .",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Le dossier existe déjà .",																			// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Attention - un dossier du même nom existe déjà !",													// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Le programme existe déjà ",																		// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Attention - un programme du même nom existe déjà !",												// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Nouveau programme",																				// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Quel est le nom du nouveau programme ?",															// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Copie de programme",																				// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Quel sera le nom du programme copié ?",															// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Propriétés des Sprites",																			// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animation",																						// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Délai entre différentes phases:",																	// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"millisecondes",																					// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Phases par pas (0 = Immédiatement):",																// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Niveau devant être affiché (0 = Items):",															// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Nombre d\'images",																					// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Phases d\'immobilité :",																			// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Phases de mouvement :",																			// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Directions:",																						// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Dimensions de l\'image",																			// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Largeur de l\'image :",																			// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Hauteur de l\'image :",																			// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Test du sprite",																					// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Erreur à la sauvegarde",																			// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"Impossible de sauvegarder ce programme .",															// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Vérifiez s\'il ne tourne pas toujours ou",															// 2. øádek hlášení
IDN_WRITEERR3,				"s\'il ne serait pas protégé contre l\'enregistrement .",											// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"Si besoin, sauvegardez ce programme sous",															// 4. øádek hlášení
IDN_WRITEERR5,				"un nom différent ou sur un disque différent .",													// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Programme modifié ",																				// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Programme modifié.\nVoulez-vous enregistrer les changements ?",									// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Cet élément est utilisé",																			// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"ATTENTION - l\'élément que vous allez supprimer est utilisé dans le programme.\nEn le supprimant vous supprimez également les sous-éléments de son arborescence .",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Suppression définitive ",																			// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"ATTENTION - vous effacez un élément de la bibliothèque.\nCet effacement est irréversible ; l\'élément ne pourra être restauré .",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Mémoire insuffisante",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Mémoire insuffisante pour exécuter l\'opération demandée!\n\nLibérez espace mémoire sur disque système Window\nou vérifiez réglages mémoire virtuelle Windows.\n Ce programme est peut-être à présent dans un état instable,\npar conséquent quittez-le aussi rapidement que possible .",	// text okna
IDN_LOADER_MEMERR_TEXT,		"Désolé, ce programme va être arrêté pour cause de mémoire insuffisante !",							// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Informations de licence endommagées",																// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Les informations de licence ont été endommagées . Lancer de nouveau l\'installation de Peter afin de corriger les informations de licence.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Fin d\'activité à temps limité",																	// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"La période d\'activité limitée dans le temps de l\'application Peter a expiré .",					// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Fin d\'activité à temps limité .",																	// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"L\'activité de l\'application Peter est limitée dans le temps.\nNombre de jours restant avant la désactivation:",	// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"Erreur système",																					// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Ressources système insuffisantes pour faire tourner PETER.EXE.",									// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Programme endommagé",																				// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Le programme PETER.EXE est endommagé et n\'a pu démarrer .",										// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Enregistrer dans un autre fichier",																// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programmes",																						// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Tous fichiers",																					// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Sauvegarder une version \"distribution\" du programme ",											// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Le programme existe déjà ",																		// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Attention - le fichier que vous sauvegardez existe déjà.\n\nVous êtes en train de sauvegarder la version distribuable non modifiable\nde ce programme et si vous sauvegardez par-dessus\nun programme-source, toutes les informations-source seront perdues.\n\nVoulez-vous continuer et écrire par-dessus ce fichier ?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Programme non-exécutable",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Ce programme a été créé avec l\'outil de programmation Peter\net est maintenant stocké sous forme non-exécutable .",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Définir la Police de caractères",																	// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Echantillon:",																						// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Ceci est un échantillon de texte .",																// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Police Standard",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Gras",																								// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Italique",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Souligner",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Barrer",																							// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Sans sérifs",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"Avec Sérifs",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Inclinaison Fixe",																					// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Sélectionner à partir de la liste",																// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Liste des polices de caractères :",																// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Hauteur:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Largeur[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Effets",																							// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Forme",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Dossier et nom pour l\'exportation du programme",													// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Nom du programme importé",																			// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Programmes Peter",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"carré vide",																						// prázdnı implicitní pøedmìt
IDF_GROUP,					"groupe",																							// skupina prvkù
IDF_IF,						"exécution conditionnelle de commandes",															// záhlaví podmínky
IDF_IF_COND,				"si valide",																						// test podmínky (IF)
IDF_IF_YES,					"alors faire",																						// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"sinon faire",																						// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"répétition conditionnelle de commandes",															// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"tant qu\'est valide",																				// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"répéter les commandes",																			// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"interrompre l\'exécution",																			// pøerušení smyèky (BREAK)
IDF_MINUS,					"signe négatif",																					// záporné znaménko "-" v èísle
IDF_CASE,					"structure de contrôle multibranche",																// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"pour la valeur de l\'expression",																	// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"exécuter les commandes au cas où",																	// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"l\'expression est égale à",																		// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"sinon exécuter les commandes",																		// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"constante numérique",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"exposant",																							// exponent v èísle
IDF_EQU,					"est égal à",																						// podmínka =
IDF_NEQU,					"n\'est pas égal à",																				// podmínka <>
IDF_EQGR,					"est supérieur ou égal à",																			// podmínka >=
IDF_EQLT,					"est inférieur ou égal à",																			// podmínka <=
IDF_GR,						"est supérieur à",																					// podmínka >
IDF_LT,						"est inférieur à",																					// podmínka <
IDF_AND,					"et",																								// logickı souèin
IDF_OR,						"ou",																								// logickı souèet
IDF_XOR,					"soit ...soit... (ou exclusif)",																	// logickı vıhradní souèet
IDF_NOT,					"si pas valide que",																				// logická negace
IDF_ADD,					"ajouter",																							// souèet èísel
IDF_SUB,					"soustraire",																						// rozdíl èísel
IDF_MUL,					"multiplier",																						// násobek èísel
IDF_DIV,					"diviser",																							// podíl èísel
IDF_REAL,					"nombre",																							// èíselná promìnná
IDF_ICON,					"item",																								// pøedmìtová promìnná
IDF_SND,					"son",																								// zvuková promìnná
IDF_MUS,					"musique",																							// hudební promìnná
IDF_FNC,					"fonction",																							// funkce
IDF_MAP,					"feuille",																							// promìnná plochy
IDF_SPRITE,					"sprite",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"contrôle du programme - extension",																// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"texte",																							// textová promìnná
IDF_WINDOWS,				"fenêtres",																							// skupina prvkù pro øízení oken
IDF_PAR,					"variables d\'entrée",																				// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"variables de sortie",																				// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"feuille - extension",																				// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"liste",																							// záhlaví seznamu (LIST)
IDF_OPER,					"contrôle du programme",																			// skupina prvkù pro øízení programu
IDF_KROK,					"pas",																								// Petøík popojít o krok vpøed
IDF_VLEVO,					"à gauche",																							// Petøík otoèit doleva
IDF_VPRAVO,					"à droite",																							// Petøík otoèit doprava
IDF_VZAD,					"demi-tour",																						// Petøík otoèit vzad
IDF_PETRIK,					"Peter",																							// skupina prvkù Petøíka
IDF_BOOL,					"drapeau",																							// logická promìnná
IDF_TEXT_CONST,				"constante textuelle",																				// textová konstanta
IDF_TRUE,					"oui",																								// logickı pøíznak TRUE
IDF_FALSE,					"non",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucy",																								// skupina prvkù Lucky
IDF_PETRA_KROK,				"pas",																								// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"à gauche",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"à droite",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"demi-tour",																						// Lucka otoèit vzad
IDF_RYCHLE,					"visible",																							// viditelnost Petøíka
IDF_EXIT,					"fin de la fonction",																				// pøerušení funkce
IDF_PETRA_RYCHLE,			"visible",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"son et musique",																					// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"item devant Peter",																				// pøedmìt pøed Petøíkem
IDF_SMER,					"direction",																						// smìr otoèení Petøíka
IDF_POZICEX,				"position horizontale",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"position verticale",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"item devant Lucy",																					// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"direction",																						// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"position horizontale",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"position verticale",																				// vertikální souøadnice Lucky
IDF_CONST,					"calculs",																							// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"opérations arithmétiques",																			// skupina èíselnıch operátorù
IDF_FUNC,					"fonctions",																						// skupina èíselnıch funkcí
IDF_POROVNANI,				"comparaisons",																						// skupina porovnávacích operátorù
IDF_LOG_OPER,				"opérations logiques",																				// skupina logickıch prvkù
IDF_MOD,					"modulo",																							// èíselnı operátor modulo
IDF_SIN,					"sinus",																							// funkce sinus
IDF_COS,					"cosinus",																							// funkce kosinus
IDF_TG,						"tangente",																							// funkce tangens
IDF_COTG,					"cotangente",																						// funkce kotangens
IDF_ARCSIN,					"arc sinus",																						// funkce arcus sinus
IDF_ARCCOS,					"arc cosinus",																						// funkce arcus kosinus
IDF_ARCTG,					"arc tangente",																						// funkce arcus tangens
IDF_ARCCOTG,				"arc cotangente",																					// funkce arcus kotangens
IDF_PI,						"Pi",																								// Ludolfovo èíslo (pí)
IDF_INTEGER,				"partie entière",																					// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"partie décimale",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"valeur absolue",																					// funkce absolutní hodnoty
IDF_SQRT,					"racine carrée",																					// funkce druhá mocnina
IDF_FACT,					"factorielle",																						// funkce faktoriál
IDF_RAND,					"nombre aléatoire (0 <= x < 1)",																	// náhodné èíslo
IDF_EUL,					"constante d\'Euler",																				// Eulerova konstanta (e)
IDF_DEGRAD,					"convertir les degrés en radians",																	// funkce konverze stupòù na radiány
IDF_RADDEG,					"convertir les radians en degrés",																	// funkce konverze radiánù na stupnì
IDF_LOG,					"logarithme décimal",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"logarithme naturel",																				// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"fonction exponentielle naturelle",																	// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"puissance",																						// operátor mocniny
IDF_UHEL,					"angle, direction",																					// skupina úhlù (smìrù)
IDF_UHEL0,					"vers la droite (0 pi, soit 0 degrés)",																// smìr vpravo
IDF_UHEL45,					"vers le haut à droite (1/4 pi, soit 45 degrés)",													// smìr vpravo nahoru
IDF_UHEL90,					"vers le haut (1/2 pi, soit 90 degrés)",															// smìr nahoru
IDF_UHEL135,				"vers le haut à gauche (3/4 pi, soit 135 degrés)",													// smìr vlevo nahoru
IDF_UHEL180,				"vers la gauche (1 pi, soit 180 degrés)",															// smìr vlevo
IDF_UHEL225,				"vers le bas à gauche (1 1/4 pi, soit 225 degrés)",													// smìr vlevo dolù
IDF_UHEL270,				"vers le bas (1 1/2 pi, soit 270 degrés)",															// smìr dolù
IDF_UHEL315,				"vers le bas à droite (1 3/4 pi, soit 315 degrés)",													// smìr vpravo dolù
IDF_COMMAND,				"contrôles",																						// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"attendre (par défaut = 0.05 sec.)",																// pøíkaz pro èekání
IDF_KLAV,					"clavier",																							// skupina ovládání klávesnice
IDF_KLAV_TEST,				"il y a une touche pressée",																		// test stisknuté klávesy
IDF_KLAV_VKEY,				"entrée touche (sans attente pression)",															// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"entrée caractère (n\'attend pas )",																// vstup znaku bez èekání
IDF_KLAV_VK,				"touches",																							// skupina kódù kláves
IDF_KLAV_FX,				"touches de fonction",																				// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"lettres",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"clavier numérique",																				// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"touches de caractères",																			// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"touches de contrôle",																				// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"transparence",																						// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Insertion",																						// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 Fin",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 Bas",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 PgDn (Bas Page)",																				// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 Gauche",																							// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 Droite",																							// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Home ",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 Haut",																							// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp (Haut Page)",																				// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Suppr",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Entrée",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Verr num",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 !",																								// kód klávesy 1 !
IDF_VK_2,					"2 @",																								// kód klávesy 2 @
IDF_VK_3,					"3 #",																								// kód klávesy 3 #
IDF_VK_4,					"4 $",																								// kód klávesy 4 $
IDF_VK_5,					"5 %",																								// kód klávesy 5 %
IDF_VK_6,					"6 ^",																								// kód klávesy 6 ^
IDF_VK_7,					"7 &",																								// kód klávesy 7 &
IDF_VK_8,					"8 *",																								// kód klávesy 8 *
IDF_VK_9,					"9 (",																								// kód klávesy 9 (
IDF_VK_0,					"0 )",																								// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~",																								// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _",																								// kód klávesy - _
IDF_VK_ROVNITKO,			"= +",																								// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ |",																								// kód klávesy \ |
IDF_VK_LLOMENA,				"[ {",																								// kód klávesy [ {
IDF_VK_RLOMENA,				"] }",																								// kód klávesy ] }
IDF_VK_STREDNIK,			"; :",																								// kód klávesy ; :
IDF_VK_RCARKA,				"\' \"",																							// kód klávesy ' "
IDF_VK_CARKA,				", <",																								// kód klávesy , <
IDF_VK_TECKA,				". >",																								// kód klávesy . >
IDF_VK_LOMITKO,				"/ ?",																								// kód klávesy / ?
IDF_VK_ESC,					"Echap",																							// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Verr Maj (Caps Lock)",																				// kód klávesy Caps Lock
IDF_VK_WIN,					" touche menu Windows gauche",																		// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Retour arrière",																					// kód klávesy Back Space
IDF_VK_ENTER,				"Entrée",																							// kód klávesy Enter
IDF_VK_MENU,				"menu local",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"Gauche",																							// kód klávesy Vlevo
IDF_VK_RIGHT,				"Droite",																							// kód klávesy Vpravo
IDF_VK_UP,					"Haut",																								// kód klávesy Nahoru
IDF_VK_DOWN,				"Bas",																								// kód klávesy Dolù
IDF_VK_INSERT,				"Insertion",																						// kód klávesy Insert
IDF_VK_DELETE,				"Suppr",																							// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"Fin",																								// kód klávesy End
IDF_VK_PAGEUP,				"Haut Page",																						// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Bas Page",																							// kód klávesy Page Down
IDF_VK_PRINT,				"Impr écran",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Arrêt défilement",																					// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"Maj gauche",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"Ctrl gauche",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"Alt gauche",																						// kód klávesy Levı Alt
IDF_VK_SPACE,				"barre d\'espacement",																				// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"souris",																							// skupina prvkù myši
IDF_MOUSE_L,				"bouton gauche souris maintenu",																	// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"bouton droit souris maintenu",																		// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"position de la souris dans direction horizontale",													// horizontální souøadnice myši
IDF_MOUSE_Y,				"position de la souris dans direction verticale",													// vertikální souøadnice myši
IDF_EQU_TEXT,				"identité du texte",																				// operátor porovnání textù
IDF_EQU_ICO,				"identité de l\'item",																				// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"sprites - extension",																				// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"la fenêtre a une bordure",																			// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"la fenêtre a un titre",																			// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"paramètres du programme",																			// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"code renvoyé",																						// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"image",																							// promìnná obrázku
IDF_REPEAT,					"répétition de commandes avec un chiffre précis",													// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"pour le nombre de répétitions",																	// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"bordure de feuille",																				// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horizontalement",																					// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"verticalement",																					// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"direction",																						// smìr sprajtu
IDF_SPRITE_MOVE,			"en mouvement",																						// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"visible",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"nombre",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"index",																							// index seznamu
IDF_LIST_AUTO,				"incrément de l\'index",																			// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Peter - extension",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucy - extension",																					// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"valeur numérique 1 (étendue 0 à 1023)",															// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"valeur numérique 1 (étendue 0 à 1023)",															// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"valeur numérique 2 (étendue 0 à 1023)",															// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"valeur numérique 2 (étendue 0 à 1023)",															// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"valeur numérique 3 (étendue 0 à 127)",																// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"valeur numérique 3 (étendue 0 à 127)",																// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"drapeau 1",																						// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"drapeau 1",																						// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"drapeau 2",																						// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"drapeau 2",																						// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"drapeau 3",																						// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"drapeau 3",																						// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"drapeau 4",																						// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"drapeau 4",																						// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"drapeau 5",																						// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"drapeau 5",																						// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"textes",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"partie gauche du texte",																			// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"longueur de la partie gauche du texte",															// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"partie droite du texte",																			// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"début de la partie droite du texte",																// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"partie médiane du texte",																			// funkce støední èásti textu
IDF_TEXT_MID_POS,			"début de la partie médiane du texte",																// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"longueur de la partie médiane du texte",															// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"longueur du texte",																				// funkce zjištìní délky textu
IDF_TEXT_ADD,				"fusion des textes",																				// operátor pro slouèení textù
IDF_TEXT_SCAN,				"conversion du nombre depuis sa forme textuelle",													// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"conversion du nombre en texte",																	// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"comparaison alphabétique de textes",																// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"convertir en minuscules",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"convertir en majuscules",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"trouver la position avec texte (-1 = aucune)",														// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"texte d\'entrée",																					// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"texte recherché",																					// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"texte d\'information",																				// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"intitulé de la fenêtre",																			// titulek hlavního okna (textová promìnná)
IDF_ORD,					"convertir le caractère en code numérique",															// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"convertir le code numérique en caractère",															// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"Son",																								// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"lecture du son",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"arrêt de la lecture (par défaut = tous les sons)",													// vypnutí zvuku
IDF_COLOR,					"couleur",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"graphisme",																						// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"couleur du stylo",																					// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"largeur d\'écriture",																				// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"point",																							// nakreslení grafického bodu
IDF_POINT_X,				"coordonnée horizontale X du point",																// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"coordonnée verticale Y du point",																	// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"ligne",																							// nakreslení èáry
IDF_LINE_X1,				"coordonnée horizontale X1 de la ligne",															// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"coordonnée verticale Y1 de la ligne",																// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"coordonnée horizontale X2 de la ligne",															// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"coordonnée verticale Y2 de la ligne",																// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"boîte",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"coordonnée horizontale X1 de la boîte",															// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"coordonnée verticale Y1 de la boîte",																// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"coordonnée horizontale X2 de la boîte",															// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"coordonnée verticale Y2 de la boîte",																// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"boîte pleine",																						// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"coordonnée horizontale X1 de la boîte pleine",														// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"coordonnée verticale Y1 de la boîte pleine",														// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"coordonnée horizontale X2 de la boîte pleine",														// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"coordonnée verticale Y2 de la boîte pleine",														// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"remplisseur",																						// vıplò plochy (vylití barvou)
IDF_FILL_X,					"coordonnée horizontale X du remplisseur",															// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"coordonnée verticale Y du remplisseur",															// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"cercle",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"coordonnée horizontale X du centre",																// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"coordonnée verticale Y du centre",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"rayon",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"cercle plein",																						// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"coordonnée horizontale X du centre",																// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"coordonnée verticale Y du centre",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"rayon",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"triangle",																							// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"coordonnée horizontale X1 du triangle",															// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"coordonnée verticale Y1 du triangle",																// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"coordonnée horizontale X2 du triangle",															// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"coordonnée verticale Y2 du triangle",																// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"coordonnée horizontale X3 du triangle",															// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"coordonnée verticale Y3 du triangle",																// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"sphère",																							// nakreslení koule
IDF_SPHERE_X,				"coordonnée horizontale X du centre",																// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"coordonnée verticale Y du centre",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"rayon",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"changer la luminosité de la couleur",																// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"luminosité de la couleur (0 à 1)",																	// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"entrée touche (attend pression)",																	// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"entrée caractère (attend pression)",																// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"aucune touche pressée",																			// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"touche menu Windows droite",																		// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Maj droit",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"Ctrl droit",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"Alt droit",																						// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"état de Verr Num (Num Lock)",																		// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"état de Verr Maj (Caps Lock)",																		// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"état de Scroll Lock (Arrêt défilement)",															// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"état de Insertion",																				// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"clic bouton gauche souris",																		// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"clic bouton droit souris",																			// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"double clic bouton gauche souris",																	// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"double clic bouton droit souris",																	// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"test de la souris dans le secteur",																// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"coordonnée horizontale X du début du secteur",														// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"coordonnée verticale Y du début du secteur",														// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"largeur du secteur",																				// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"hauteur du secteur",																				// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"affichage du texte",																				// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"coordonnée horizontale X du texte",																// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"coordonnée verticale Y du texte",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"angle d\'orientation du texte",																	// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"hauteur des caractères",																			// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"largeur relative des caractères (1 = usuelle)",													// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"gras",																								// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"italique",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"souligné",																							// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"barré",																							// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"sérifs",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"machine à écrire",																					// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"texte à afficher",																					// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"nombre de lignes du texte",																		// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"ligne de texte",																					// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"numéro de la ligne de texte",																		// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"test du son (par défaut = lecture de tous types de sons)",											// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"nombre de répétitions (0 = de façon permanente)",													// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"item à la position de Peter",																		// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"item à la position de Lucy",																		// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"dessiner l\'image",																				// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"image à dessiner",																					// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"coordonnée horizontale X de l\'image",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"coordonnée verticale Y de l\'image",																// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"coordonnée horizontale X de la découpe",															// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"coordonnée verticale Y de la découpe",																// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"largeur de la découpe",																			// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"hauteur de la découpe",																			// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"conserver la découpe de la feuille comme image",													// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"conserver la découpe de la feuille comme item",													// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"langue (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"son à lire",																						// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"volume du son (0 à 1)",																			// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"équilibrage stéréophonique (-1 = gauche à +1 = droite)",											// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"interrompre la lecture du son",																	// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"commentaire",																						// komentáø
IDF_SOUND_FUNCTIONS,		"fonctions audio",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"choisir la forme du curseur de la souris",															// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"image du curseur de la souris (par défaut = aspect d\'origine)",									// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"coordonnée horizontale X du début du secteur",														// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"coordonnée verticale Y du début du secteur",														// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"largeur du secteur",																				// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"hauteur du secteur",																				// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"jouer de la musique",																				// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"jouer la musique en boucle",																		// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"arrêter de jouer la musique",																		// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"mettre en pause/continuer le morceau",																// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test de lecture de la musique",																	// test pøehrávání hudby
IDF_MUSIC_POS,				"position dans le morceau joué",																	// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"durée du morceau joué",																			// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"combinaison des composantes couleur pour la couleur",												// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"composante rouge (0 à 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"composante verte (0 à 1)",																			// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"composante bleue (0 à1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"obtenir la couleur du pixel",																		// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"coordonnée horizontale X pour obtenir la couleur du pixel",										// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"coordonnée verticale Y pour obtenir la couleur du pixel",											// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"puissance au carré",																				// funkce druhá mocnina
IDF_MUSIC_GROUP,			"musique",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"CD audio",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"lecture du CD à partir de la piste spécifiée (par défaut = 1)",									// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"arrêt de la lecture du CD",																		// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"mettre en pause/continuer lecture du CD",															// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test de la lecture du CD",																			// test pøehrávání CD
IDF_CD_LENGTH,				"durée totale",																						// celková délka CD
IDF_CD_TRACKS,				"nombre de pistes",																					// poèet stop CD
IDF_CD_POS,					"position par rapport au début",																	// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"piste en lecture",																					// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"longueur de piste lue",																			// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"position par rapport au début de la piste",														// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"fichiers",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"opérations de base",																				// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"nouveau fichier",																					// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"nouveau dossier",																					// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"supprimer le fichier ou le dossier",																// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"test d\'existence",																				// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"disque et dossier actifs",																			// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"capacité du disque",																				// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"espace libre sur le disque",																		// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"nom de volume du disque",																			// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"numéro de série du disque",																		// zjištìní sériového èísla disku
IDF_FILE_READ,				"fichier ou dossier actif pour la lecture",															// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"fichier ou dossier actif pour l\'écriture",														// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"copie de fichier",																					// provedení kopie souboru
IDF_FILE_MOVE,				"Déplacer/Renommer fichier (dossier)",																// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disque",																							// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"attributs",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"attribut R/O (lecture seule)",																		// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"attribut HID (caché)",																				// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"attribut SYS (système)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"attribut DIR (dossier)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"attribut ARC (archive)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"attribut TEMP (temporaire)",																		// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"attribut COMP (compressé)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"attribut OFF (offline)",																			// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"date et heure de la création",																		// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"date et heure du dernier accès",																	// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"date et heure de la dernière modification",														// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"données",																							// skupina dat souborù
IDF_FILE_BYTES,				"nombre entier avec signe, 1 byte",																	// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"nombre entier sans signe, 1 byte",																	// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"nombre entier avec signe, 2 bytes",																// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"nombre entier sans signe, 2 bytes",																// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"nombre entier avec signe, 4 bytes",																// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"nombre entier sans signe, 4 bytes",																// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"nombre décimal, 4 bytes",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"nombre décimal, 8 bytes",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"texte terminé par un zéro binaire (ASCIIZ)",														// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"texte terminé par une fin de ligne",																// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"texte de longueur fixe",																			// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"item (ICO)",																						// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"image (BMP, JPG)",																					// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"son (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"musique (MID, RMI)",																				// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"pointeur de lecture",																				// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"pointeur d\'écriture",																				// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"date et heure",																					// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"date et heure actuels (nombre de secondes depuis le 1er Janvier 1601)",							// aktuální datum a èas
IDF_DATETIME_UTC,			"convertir l\'heure locale en heure mondiale",														// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"convertir l\'heure mondiale en heure locale",														// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"fusionner les composants de la date et de l\'heure",												// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"année",																							// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"mois",																								// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"jour",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"heure",																							// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minute",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"seconde",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"milliseconde",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"année de la date et de l\'heure",																	// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"mois de la date et de l\'heure",																	// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"jour de la date et de l\'heure",																	// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"jour de la semaine de la date et de l\'heure (0 = dimanche, 1 = lundi, ...)",						// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"heure de la date et de l\'heure",																	// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minute de la date et de l\'heure",																	// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"seconde de la date et de l\'heure",																// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"milliseconde de la date et de l\'heure",															// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"convertir la date en texte \"jour.mois.année\"",													// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"convertir la date en texte \"mois/jour/année\"",													// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"convertir la  date en texte \"année-mois-jour\"",													// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"convertir l\'heure en texte \"heure:minute:seconde\" (24 heures)",									// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"convertir l\'heure en texte \"heure:minute:seconde x\" (12 heures)",								// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"taille du fichier",																				// velikost souboru
IDF_FILE_ERROR,				"drapeau d\'erreur d\'opération",																	// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"longueur du texte de longueur fixe",																// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"type de disque (2=FD (disquette), 3=HD (disque dur), 4=NET, 5=CD, 6=RAM)",							// zjištìní typu disku
IDF_TEXT_FORMAT2,			"convertir le nombre en texte - 2 chiffres",														// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"convertir le nombre en texte - 8 chiffres HEX",													// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"nombre entier avec signe, 3 bytes",																// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"nombre entier sans signe, 3 bytes",																// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"dialogues",																						// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"dialogue de confirmation (renvoie 1=OK, 2=Annuler, 3=Abandon, 4=Réessayer, 5=Ignorer, 6=Oui, 7=Non)",	// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"texte",																							// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"légende",																							// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"icône (0=aucune, 1=erreur, 2=question, 3=avertissement, 4=information)",							// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"boutons (0=OK, 1=OK/Annuler, 2=Abandon/Réessayer/Ignorer, 3=Oui/Non/Annuler, 4=Oui/Non, 5=Réessaye/Annuler)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"bouton par défaut (1 à 3)",																		// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"ligne suivante",																					// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"entrée de texte",																					// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1ère ligne du message",																			// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2ème ligne du message",																			// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3ème ligne du message",																			// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"texte préparé pour entrée",																		// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"éjecter le CD",																					// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"nombre de bits par échantillon (8 ou 16)",															// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"fréquence d\'échantillonnage (Hz)",																// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"Le son est-il stéréophonique ?",																	// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"durée du son (secondes)",																			// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"convertir en 8 bits",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"convertir en 16 bits",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"convertir en stéréo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"convertir en mono",																				// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"convertir en 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"convertir en 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"convertir en 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"fusionner les sons",																				// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"modifier vitesse du son",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"son à convertir",																					// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"changement relatif de la vitesse (1 = inchangée)",													// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"générateur de tons",																				// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"fréquence du ton (Hz)",																			// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"durée du ton (secondes)",																			// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"feuille",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"largeur de la feuille",																			// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"hauteur de la feuille",																			// zjištìní vıšky plochy
IDF_MAP_X,					"coordonnée X",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"coordonnée Y",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"feuille",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"item",																								// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"valeur numérique 1 (étendue : 0 à 1023)",															// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"valeur numérique 2 (étendue : 0 à 1023)",															// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"valeur numérique 3 (étendue : 0 à 127)",															// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"drapeau 1",																						// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"drapeau 2",																						// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"drapeau 3",																						// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"drapeau 4",																						// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"drapeau 5",																						// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"copier la découpe depuis la feuille",																// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"feuille avec découpe",																				// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"coordonnée X de la découpe",																		// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"coordonnée Y de la découpe",																		// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"largeur de la découpe",																			// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"hauteur de la découpe",																			// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"console",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"déplacement de tous les sprites dans la direction X",												// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"déplacement de tous les sprites dans la direction Y",												// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"bord gauche de la fenêtre des sprites",															// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"bord inférieur de la fenêtre des sprites",															// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"bord droit de la fenêtre des sprites",																// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"bord supérieur de la fenêtre des sprites",															// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"mode console (doit être utilisé au début de la fonction principale)",								// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"sortie de texte vers console",																		// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"entrée de texte depuis console",																	// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"erreur de sortie de texte vers console",															// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"paramètre du programme (0 = nom du programme)",													// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"nom de programme avec chemin complet",																// jméno tohoto programu s plnou cestou
IDF_EXEC,					"exécution du programme",																			// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"exécution du programme avec attente",																// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"joystick",																							// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"coordonnée X du joystick",																			// souøadnice X joysticku
IDF_JOYSTICK_Y,				"coordonnée Y du joystick",																			// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"coordonnée Z du joystick",																			// souøadnice Z joysticku
IDF_JOYSTICK_1,				"bouton 1 du joystick",																				// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"bouton 2 du joystick",																				// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"bouton 3 du joystick",																				// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"bouton 4 du joystick",																				// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"textes et images",																					// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"numéro de l\'élément (0 = fenêtre principale)",													// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"supprimer un élément ou une fenêtre",																// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"créer une fenêtre",																				// vytvoøení dialogového okna
IDF_WINDOW_X,				"coordonnée horizontale",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"coordonnée verticale",																				// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"largeur",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"hauteur",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"texte",																							// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"visible",																							// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"désactiver",																						// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"créer un bouton",																					// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"pression sur un bouton ou modification d\'un élément",												// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"créer une boîte de contrôle",																		// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"créer une ligne d\'édition",																		// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"créer un commutateur",																				// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"fonctions communes à tous les éléments",															// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"créer un champ d\'édition",																		// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"boutons",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"commutateur  on/off",																				// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"ajustement de l\'entrée",																			// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"créer un bouton par défaut",																		// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"créer un bouton -icône",																			// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"créer un cadre",																					// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"créer une liste",																					// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"créer un texte",																					// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"créer une liste déroulante",																		// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"créer une liste déroulante avec édition",															// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"gras",																								// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"inclinaison fixe",																					// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"créer un commutateur - début du groupe",															// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"listes",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"ajouter une entrée à la liste",																	// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"vidage de la liste",																				// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"créer une liste avec édition",																		// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"créer une boîte de contrôle 3-états",																// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"commutateur dans un état indéterminé",																// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"créer une fenêtre sans possibilité de fermeture",													// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"icône",																							// ikona prvku dialogového okna
IDF_WINICON_NEW,			"créer une icône",																					// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"sprite (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*pi (= 360 degrés)",																				// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"distance de 1 pixel (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"phase",																							// fáze sprajtu
IDF_SPRITE_STATUS,			"état",																								// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"mode plein écran",																					// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"vidage du tampon clavier",																			// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"position de lecture du son",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"mettre en pause/continuer la lecture du son",														// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"liste des fichiers",																				// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"identité de la feuille",																			// operátor porovnání ploch
IDF_EQU_PIC,				"identité de l\'image",																				// operátor porovnání obrázkù
IDF_EQU_SPR,				"identité du sprite",																				// operátor porovnání sprajtù
IDF_EQU_SND,				"identité du son",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"identité de la musique",																			// operátor porovnání hudeb
IDF_NET_GROUP,				"communication",																					// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"support réseau DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"liste des connexions",																				// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"connexion active",																					// aktivní spojení DirectPlay
IDF_GAME_LIST,				"liste des jeux",																					// seznam bìících her DirectPlay
IDF_GAME_ACT,				"jeu actif",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"liste des joueurs",																				// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"joueur actif",																						// aktivní hráè DirectPlay
IDF_GAME_N1,				"paramètre numérique 1 du jeu (-16384 à +16383)",													// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"paramètre numérique 2 du jeu (-16384 à +16383)",													// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"paramètre numérique 3 du jeu (-16384 à +16383)",													// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"paramètre numérique 4 du jeu (-16384 à +16383)",													// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"paramètre numérique 5 du jeu (-16384 à +16383)",													// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"paramètre numérique 6 du jeu (-16384 à +16383)",													// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"paramètre numérique 7 du jeu (-16384 à +16383)",													// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"paramètre numérique 8 du jeu (-16384 à +16383)",													// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"drapeau 1 du jeu",																					// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"drapeau 2 du jeu",																					// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"drapeau 3 du jeu",																					// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"drapeau 4 du jeu",																					// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"drapeau 5 du jeu",																					// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"drapeau 6 du jeu",																					// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"drapeau 7 du jeu",																					// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"drapeau 8 du jeu",																					// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"installation du jeu",																				// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"hôte (ordinateur contrôle)",																		// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"nombre maximum de joueurs (0 = illimité)",															// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"numéro du joueur actif (-1 = aucun)",																// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"données",																							// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"envoyer/recevoir un bloc de données (-1 = à tous/aucun)",											// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"numéro",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"texte",																							// text dat DirectPlay
IDF_GAME_DATAL,				"drapeau",																							// pøepínaè dat DirectPlay
IDF_GAME_IP,				"adresse IP  de cet ordinateur",																	// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"nombre entier de 0 à 255 (Byte)",																	// èíslo bajt dat DirectPlay
IDF_INC,					"incrémenter (ajoute 1)",																			// funkce inkrementace èísla
IDF_DEC,					"décrémenter (soustrait 1)",																		// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"créer un texte centré",																			// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"bouton pour la touche  Echap (-1 = aucun)",														// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"largeur de l\'image",																				// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"hauteur de l\'image",																				// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"faire pivoter horizontalement l\'image",															// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"faire pivoter verticalement l\'image",																// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"images",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"modifier la taille de l\'image",																	// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"image",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"largeur (par défaut = proportionnelle à la hauteur)",												// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"hauteur (par défaut = proportionnelle à la largeur)",												// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"affiner les contours",																				// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (photographies)",																		// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"dessin",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"créer une image",																					// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"image",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"créer l\' éditeur RichEdit",																		// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"hauteur des caractères (0 = usuelle)",																// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"italique",																							// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"souligné",																							// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"barré",																							// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"sérifs",																							// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"largeur relative des caractères (0 = usuelle, 1 = basique)",										// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"angle d\'inclinaison du texte",																	// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"créer un texte aligné à droite",																	// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"couleur des caractères",																			// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"couleur d\'arrière-plan",																			// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"police de l\'élément",																				// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"vitesse de lecture  (1 = usuelle)",																// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"distinguish code (0 to 65535)",																	// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"taper le nom du fichier à ouvrir",																	// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"taper le nom du fichier à sauvegarder",															// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"taper le texte à trouver",																			// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"entrer la couleur",																				// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"masque de fichier",																				// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"nom présélectionné pour le fichier",																// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"nom du type de fichiers",																			// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"modifier la luminosité de l\'image",																// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"image pour changement luminosité",																	// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"intensité lumineuse de l\'image (1 = usuelle)",													// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"faire tourner l\'image",																			// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"image à faire tourner",																			// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"angle de rotation",																				// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"décompression du son",																				// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"le texte est au format UNICODE (2 bytes)",															// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"convertir la feuille en image",																	// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"convertir l\'item en image",																		// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"opérations sur les bits",																			// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"AND produit de bits",																				// bitovı (binární) souèin AND
IDF_BIT_OR,					"OR somme de bits",																					// bitovı (binární) souèet OR
IDF_BIT_XOR,				"XOR inversion de bits",																			// bitová (binární) inverze XOR
IDF_BIT_NOT,				"NOT complément de bits",																			// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"nombre maximum de bits (mot double)",																// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"rotation par bit vers la gauche",																	// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"rotation par bit vers la droite",																	// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"test de la souris dans l\'élément",																// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"largeur interne",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"hauteur interne",																					// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"réglage caractères (1250=Europe de l\'Est, 1251=Russe, 1252=Ouest)",								// èíslo pouité znakové sady fontù
IDF_USERFONT,				"police utilisateur",																				// jméno uivatelského fontu
IDF_ENUMFONTS,				"liste des polices",																				// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"nouvelle feuille",																					// vytvoøení nové plochy
IDF_MAP_NEW_W,				"largeur de la feuille",																			// šíøka nové plochy
IDF_MAP_NEW_H,				"hauteur de la feuille",																			// vıška nové plochy
IDF_WINDOW_TOP,				"toujours en haut",																					// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"pseudo (alias)",																					// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"port de communication",																			// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"ouvrir le port (-1=erreur)",																		// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"fermer le port",																					// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"port actif",																						// aktivní port
IDF_COM_NUM,				"numéro (0 à 255)",																					// vstup/vıstup èísla
IDF_COM_TEXT,				"caractère (text)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"taux de transfert (en bauds)",																		// pøenosová rychlost
IDF_COM_STOP,				"2 bits de stop",																					// reim s 2 stopbity
IDF_COM_BITS,				"nombre de bits (5 à 8)",																			// poèet bitù na znak
IDF_COM_PARIT,				"parité (0=aucune, 1=impair, 2=pair)",																// zvolená parita
IDF_COM_IN,					" un caractère reçu",																				// byl pøijatı znak
IDF_COM_SEND,				"émission autorisée (CTS, RTS)",																	// povoleno vysílání
IDF_COM_RECEIVE,			"réception autorisée (DSR, DTR)",																	// povolen pøíjem
IDF_PICTURE_MASK,			"masquage image",																					// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"image",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"masque",																							// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"largeur du champ de visualisation du texte (0 = aucun)",											// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"créer un champ d\'édition sans enroulement",														// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"fenêtre redimensionnable",																			// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"la fenêtre peut être fermée",																		// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"la fenêtre est maximisée",																			// maximalizace okna
IDF_WINDOW_MINIM,			"la fenêtre est minimisée",																			// minimalizace okna
IDF_PROGRESS_NEW,			"créer une barre d\'avancement",																	// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"créer une barre de défilement horizontal",															// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"créer une barre de défilement vertical",															// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"position actuelle",																				// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"table de mixage",																					// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"table de mixage",																					// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"signal de destination",																			// volba cílového signálu
IDF_MIX_LINE_SRC,			"signal source (aucun=uniquement signal de destination)",											// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"type de signal",																					// zjištìní typu signálu
IDF_MIX_CONTROL,			"item de contrôle",																					// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"type d\'item de contrôle",																			// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"valeur de l\'item de contrôle (0 à 1)",															// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"sélection de la valeur de l\'item",																// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"canal contrôlé (-1=tous)",																			// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"graphisme 3D",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"fenêtre graphique 3D",																				// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"coordonnées X de la fenêtre graphique 3D",															// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"coordonnées Y de la fenêtre graphique 3D",															// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"largeur de la fenêtre graphique 3D",																// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"hauteur de la fenêtre graphique 3D",																// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"mode vidéo (largeur*hauteur/bits)",																// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"arrière-plan graphique",																			// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"réglages",																							// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"remplissage des surfaces",																			// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"éclairage",																						// mód osvìtlení
IDF_DIRECT3D_SHADES,		"ombrage régulier",																					// mód stínování
IDF_DIRECT3D_INVERT,		"inversion de l\'objet",																			// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objets",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"mur",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"cube",																								// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"sphère",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"cylindre",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"cône",																								// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"cloner",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"objet depuis texte",																				// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"objet depuis fichier",																				// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"objet actif (0=scène, 1=caméra, 2=lumière)",														// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"supprimer un objet",																				// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"visible",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"lier",																								// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"objet vers fichier",																				// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformations",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"modifier dimensions dans la direction X",															// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"modifier dimensions dans la direction Y",															// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"modifier dimensions dans la direction Z",															// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"rotation autour de l\'axe X",																		// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"rotation autour de l\'axe Y",																		// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"rotation autour de l\'axe Z",																		// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"translation dans la direction X",																	// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"translation dans la direction Y",																	// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"translation dans la direction Z",																	// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"surface",																							// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"couleur (-1=interne, -2=par défaut)",																// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"couleur émissive",																					// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"matité (0=désactivé, 5=métal, 50=plastique)",														// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"couleur de réflexion",																				// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"texture",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"mappage de texture",																				// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"type de projection (0=plane, 1=cylindrique, 2=sphérique, 3=chrome, 4=loupe)",						// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"coordonnée X du centre de la projection",															// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"coordonnée Y du centre de la projection",															// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"coordonnée Z du centre de la projection",															// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"rotation de la projection autour de l\'axe X",														// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"rotation de la projection autour de l\'axe Y",														// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"rotation de la  projection autour de l\'axe Z",													// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"transparence (1=normal, 11=feu, 20=verre, 54=recouvrement)",										// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"contours (0=normal, 0.5=contours)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"méthode (0=adresses, 1=sommets, 2=faces)",															// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"origine horizontale de la texture",																// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"origine verticale de la texture",																	// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"degré de décroissance horizontale de la texture",													// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"degré de décroissance verticale de la texture",													// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"éclairage",																						// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"créer une nouvelle lumière",																		// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"couleur de lumière",																				// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"type de lumière (1=point, 2=spot, 3=directionnelle)",												// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"angle du pinceau lumineux",																		// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"angle de la pénombre",																				// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"portée de la lumiére",																				// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"intensité de la lumière (1=normale)",																// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"atténuation linéaire",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"atténuation quadratique",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"type de projection (0=persp, 1=ortho, 2=r-persp, 3=r-ortho)",										// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"scène",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"couleur d\'arrière-plan de la scène (-1=désactivé, -2=ne pas initialiser)",						// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"texture de l\'arrière-plan de la scène",															// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"couleur du brouillard (-1=désactivé)",																// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"type de brouillard (0=linéaire, 1=exponentiel, 2=quadratique, +4=correction)",						// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"début du brouillard linéaire",																		// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"fin du brouillard linéaire",																		// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"densité du brouillard ( exp. et quadr.) (0 à 1)",													// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"distance du plan de projection",																	// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"distance du champ de vision",																		// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"créer la base supérieure",																			// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"créer la base inférieure",																			// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"recherche de l\' objet",																			// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"coordonnée X du point",																			// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"coordonnée Y du point",																			// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"filtrage de la texture réduite",																	// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"objet 2D",																							// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terrain depuis image",																				// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"niveau du terrain",																				// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"coordonnée horizontale",																			// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"coordonnée verticale",																				// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"groupe",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"complexité de l\'objet (2 à 100)",																	// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"ordre des rotations (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",									// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"pilote (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"objet rotatif",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terrain depuis la feuille",																		// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"réflexion de la lumière ambiante (-1= par défaut)",												// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"ce programme est une application active",															// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"distance du point",																				// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"angle du point",																					// vıpoèet úhlu bodu
IDF_POLAR_X,				"coordonnée X du point",																			// souøadnice X bodu
IDF_POLAR_Y,				"coordonnée Y du point",																			// souøadnice Y bodu
IDF_FILE_LOGIC,				"valeur logique",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"adoucissement des textures (1=aucun)",																// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"compteur temporel précis",																			// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"lumière ambiante",																					// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"filtrage de la texture agrandie",																	// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"filtrage de la texture lointaine",																	// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"remplissage des surfaces de l\'objet",																// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"éclairage de l\'objet",																			// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"ombrage régulier de l\'objet",																		// mód stínování
IDF_DIRECT3D_OMINFILTER,	"filtrage de la texture d\'objet réduite",															// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"filtrage de la texture d\'objet agrandie",															// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"filtrage de la texture d\'objet lointaine",														// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"côté visible de l\'objet (0=les deux, 1=avant, 2=arrière)",										// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"créer",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"normaliser l\'objet",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"cercle",																							// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"triangle",																							// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"tore (paramètre = diamètre 0 à 1)",																// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"objet 2D statique",																				// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"hémisphère",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interface (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",								// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"temps écoulé",																						// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"vitesse de rendu",																					// rychlost renderování
IDF_DIRECT3D_FREE,			"mémoire vidéo libre",																				// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"image 2D",																							// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"textures",																							// skupina textur
IDF_DIRECT3D_STAGE,			"étape (0 to 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"opération sur couleur (1=désactivé, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",							// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"premier argument couleur (0=couleur, 1=résultat, 2=texture, 3=facteur, 16=inversion)",				// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"deuxième argument couleur (0=couleur, 1=résultat, 2=texture, 3=facteur, 16=inversion)",			// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"opération alpha (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"premier argument alpha (0=couleur, 1=résultat, 2=texture, 3=facteur, 16=inversion)",				// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"deuxième argument alpha (0=couleur, 1=résultat, 2=texture, 3=facteur, 16=inversion)",				// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"mode d\'adressage horizontal (1=répéter, 2=miroir, 3=délimitation)",								// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"mode d\'adressage vertical (1=répéter, 2=miroir, 3=délimitation)",									// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"estompage des textures dans le lointain (0=par défaut)",											// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"figure tronconique (paramètre = diamètre de 0 à 1)",												// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"couleur du facteur de texture",																	// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"composante alpha (de 0=transparence à 1=couleur)",													// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"nombre de textures dans le lointain (0=toutes)",													// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"groupe de rendu (0-7=objets, 8-11=transparent, 12-15=images)",										// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"sélection approfondie des groupes de rendu",														// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"écrire l\'information approfondie",																// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"test approfondi (1 jamais, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 toujours)",							// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"calcul des normales (paramètre = angle d\'adoucissement)",											// pøepoèet normál
IDF_DIRECT3D_RENDER,		"rendu sans affichage",																				// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"bloc de texte",																					// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"ligne du début du bloc",																			// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"position du début du bloc",																		// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"ligne de la fin du bloc (-1=fin)",																	// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"position de la fin du bloc (-1=fin)",																// pozice konce bloku
IDF_WINDOW_POS2,			"position actuelle 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"créer un bouton de commutation",																	// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"créer un tableau (paramètre = liste des titres)",													// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"largeur de colonne du tableau",																	// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"étendue de l\'ombre (0=désactivé)",																// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"alignement de la colonne du tableau (0=gauche, 1=droite, 2=centre)",								// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"créer une barre de défilement horizontal",															// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"créer une barre de défilement vertical",															// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"permuter les couleurs",																			// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"première couleur",																					// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"deuxième couleur",																					// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"remplacer la couleur",																				// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"ancienne couleur",																					// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"nouvelle couleur",																					// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"imprimer l\'image",																				// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"objet avec réduction du niveau de détail (-1=aucun)",												// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"distance pour réduction du niveau de détail",														// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"ajouter un modèle pour morphing (-1=réinitialiser)",												// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"étape de morphing (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"brillance de la lentille",																			// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"échange dynamique de données DDE",																	// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"nom de serveur/liste des serveurs",																// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"nom de thème/liste des thèmes",																	// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"nom de l\'entrée/liste des entrées",																// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"le programme procède lui-même aux entrées (est serveur)",											// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"type d\'entrée (0 to 7, -1=entrée invalide)",														// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) numéro",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) drapeau",																						// pøíznak DDE
IDF_DDE_TEXT,				"(2) texte",																						// text DDE
IDF_DDE_ICON,				"(3) item",																							// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) image",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) son",																							// zvuk DDE
IDF_DDE_MUSIC,				"(6) musique",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"commande à exécuter",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"bibliothèques de DLL",																				// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"charger la bibliothèque",																			// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"libérer la bibliothèque",																			// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"importer la fonction",																				// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"identifiant de la bibliothèque",																	// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"nom de la fonction",																				// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"nombre de paramètres",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"exécuter la fonction",																				// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"créer le bloc mémoire",																			// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"libérer le bloc mémoire",																			// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"modifier la taille du bloc mémoire",																// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"adresse du bloc mémoire",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"nouvelle taille",																					// nová velikost bloku pamìti
IDF_MEMORY_READ,			"pointeur de lecture",																				// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"pointeur d\'écriture",																				// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"copie de données",																					// kopie bloku dat
IDF_MEMORY_COMPARE,			"comparaison des données",																			// porovnání bloku dat
IDF_MEMORY_BYTES,			"byte avec signe",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"byte sans signe",																					// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"mot avec signe",																					// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"mot sans signe",																					// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-byte avec signe",																				// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-byte sans signe",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"mot double avec signe",																			// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"mot double sans signe",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"nombre décimal 4 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"nombre décimal 8 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"valeur logique",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"texte terminé par zéro",																			// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"pointeur vers texte terminé par zéro",																// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"texte de longueur fixe",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"longueur du texte de taille fixe",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"lire les données depuis le fichier",																// ètení dat ze souboru
IDF_MEMORY_SAVE,			"écrire les données dans le fichier",																// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identificateur de l\'élément  de fenêtre",															// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"convention d\'appel C",																			// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"créer des tabulations",																			// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"configuration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"fichier de configuration",																			// jméno konfiguraèního souboru
IDF_INI_SECTION,			"section des paramètres",																			// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"nom de paramètre",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"lire/écrire un paramètre de texte",																// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"lire/écrire un paramètre numérique",																// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"Classification de la  clé (1=CURRENT_USER, 2=LOCAL_MACHINE)",										// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"nom de la clé",																					// plnı mázev klíèe registrù
IDF_REG_VALUE,				"nom de la donnée entrée",																			// název datové poloky
IDF_REG_STRING,				"lire/écrire entrée textuelle",																		// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"lire/écrire entrée numérique",																		// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"créer l\'objet 3D à partir de blocs de mémoire",													// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"nombre de sommets",																				// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"sommets",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normales (0=auto)",																				// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"mappage des textures (0=aucun)",																	// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"couleurs (0=aucune)",																				// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"nombre de faces",																					// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"faces",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"texture from file",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"memory block from 3D object",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"find child (-1=first, -2=parent)",																	// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
