// Slovensky (Slovak)
// 1250
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Spoloèné premenné a funkcie",																		// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Miestne premenné a funkcie",																		// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Základné prvky, kôš",																				// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Kninica premennıch a funkcií",																	// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"základné premenné a funkcie",																		// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"Novı program",																						// implicitní název nového programu
IDN_NEWDIR_NAME,			"Nová zloka",																						// implicitní název nové sloky
IDN_TEXTVZOR,				"[vzory]",																							// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Pouité",																							// zobrazuje poèet pouití prvku
IDT_RADEK,					"riadok",																							// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"pozícia",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"zapnuté",																							// text editoru hodnoty pøepínaèe
IDN_DATUM,					"dátum",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"èas",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"ve¾kos",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"vo¾né",																							// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"opakovanie",																						// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"opakovane",																						// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMO",																								// oznaèení DEMO verze
IDN_PROFI,					"Professional",																						// oznaèení verze Professional
IDN_LITE,					"Lite",																								// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&Súbor",																							// volba k vyvolání menu "Soubor"
IDN_START0,					"Š&tart\tF5",																						// volba pro spuštìní programu
IDN_START,					"Spustí program.\nŠtart",																			// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Otvori\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Otvorí program pre editáciu.\nOtvori",															// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&Novı...\tCtrl+N",																					// volba pro zaloení nového programu
IDN_NEW,					"Vytvorí novı program.\nNovı",																		// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"Pre&menova...\tAlt+Enter",																		// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Zmení meno programu/zloky (nemono premenova vzorové programy a zloky).\nPremenova",			// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"Kopí&rova\tCtrl+C",																				// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Zkopíruje vybranı program a dá mu iné meno.\nKopírova",											// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"Nová z&loka...\tCtrl+P",																			// volba k vytvoøení nové sloky
IDN_PATH,					"Vytvorí novú zloku pre programy.\nNová zloka",													// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Zruši...\tDelete",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Zruší program alebo zloku (nemono ruši vzorové programy a zloky).\nZruši",					// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Krátke m&ená",																						// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"Programy a súbory knihovny budú vytvárané s menami skrátenımi na 8 znakov.\nKrátke mená",			// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"&Koniec\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Ukonèí aplikáciu Peter.\nKoniec",																	// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"&Písmo",																							// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Písmo &vıberu programu...",																		// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Nastaví podobu písma v okne vıberu programu.\nPísmo vıberu programu",								// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Písmo &editoru programu...",																		// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Nastaví podobu písma v oknách editoru programu.\nPísmo editoru programu",							// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Písmo editoru &textu...",																			// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Nastaví podobu písma v okne editoru textu.\nPísmo editoru textu",									// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Písmo &ponuky...",																					// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Nastaví podobu písma ponuky.\nPísmo ponuky",														// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Písmo &stavového riadku...",																		// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Nastaví podobu písma stavového (informaèného) riadku.\nPísmo stavového riadku",					// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&Jazyk",																							// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automaticky",																						// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Zvolí jazyk automaticky pod¾a nastavenia systému.\nAutomaticky",									// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Predchádzajúci\tCtrl+F9",																			// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Prepne medzi dvuma posledne zvolenımi jazykmi.\nPredchádzajúci",									// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Po bulharsky (Bulgarija)",																			// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Prepne aplikáciu Peter na bulharsky jazyk.\nPo bulharsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"Po è&esky (Èesky)",																				// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Prepne aplikáciu Peter na èeskı jazyk.\nPo èesky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"Po &dánsky (Danmark)",																				// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Prepne aplikáciu Peter na dánsky jazyk.\nPo dánsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"Po &nemecky (Deutsch)",																			// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Prepne aplikáciu Peter na nemeckı jazyk.\nPo nemecky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Po recky (Hellás)",																				// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Prepne aplikáciu Peter na reckı jazyk.\nPo recky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"Po an&glicky (English)",																			// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Prepne aplikáciu Peter na anglickı jazyk.\nPo anglicky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"Po španiel&sky (Espaòa)",																			// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Prepne aplikáciu Peter na španielsky jazyk.\nPo španielsky",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Po finsky (Finland)",																				// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Prepne aplikáciu Peter na finsky jazyk.\nPo finsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"Po &francúzsky (France)",																			// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Prepne aplikáciu Peter na francúzsky jazyk.\nPo francúzsky",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"Po &maïarsky (Magyar)",																			// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Prepne aplikáciu Peter na maïarsky jazyk.\nPo maïarsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Po islandsky (Island)",																			// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Prepne aplikáciu Peter na islandsky jazyk.\nPo islandsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Po taliansky (Italy)",																				// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Prepne aplikáciu Peter na taliansky jazyk.\nPo taliansky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Po holandsky (Nederland)",																			// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Prepne aplikáciu Peter na holandsky jazyk.\nPo holandsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Po norsky (Norge)",																				// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Prepne aplikáciu Peter na norsky jazyk.\nPo norsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Po po¾sky (Po polsku)",																			// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Prepne aplikáciu Peter na po¾skı jazyk.\nPo po¾sky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Po portugalsky (Portugal)",																		// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Prepne aplikáciu Peter na portugalsky jazyk.\nPo portugalsky",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Po rumunsky (România)",																			// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Prepne aplikáciu Peter na rumunsky jazyk.\nPo rumunsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"Po &rusky (Po-rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Prepne aplikáciu Peter na ruskı jazyk.\nPo rusky",													// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Po serbochorvatsky (Serbo-Croat)",																	// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Prepne aplikáciu Peter na serbochorvatsky jazyk.\nPo serbochorvatsky",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"Po slovensky",																						// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Prepne aplikáciu Peter na slovenskı jazyk.\nPo slovensky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Po albánsky (Shqipërisë)",																			// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Prepne aplikáciu Peter na albánsky jazyk.\nPo albánsky",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Po švédsky (Swerige)",																				// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Prepne aplikáciu Peter na švédsky jazyk.\nPo švédsky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Po turecky (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Prepne aplikáciu Peter na turecky jazyk.\nPo turecky",												// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"&Vietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Pomoc",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Pomoc\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Zobrazí pomoc pre vybranı prvok.\nPomoc",															// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"&Témy pomoci",																						// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Zobrazí témy pomoci.\nTémy pomoci",																// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&H¾ada v pomoci",																					// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Vyh¾adáva v pomoci.\nH¾ada v pomoci",																// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"&O aplikácii Peter",																				// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Zobrazí informácie o aplikácii Peter, èíslo verzie a copyright.\nO aplikácii Peter",				// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Zatvori\tCtrl+O",																				// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Zatvorí editovanı program a otvorí inı.\nZatvori",												// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Uloi\tCtrl+S",																					// volba k uloení programu pøi editaci
IDN_SAVE,					"Uloí zmeny vykonané v programu.\nUloi",															// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"Uloi &nespustite¾ne\tCtrl+Alt+S",																// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Uloí program ako nespustite¾nı (menšia ve¾kos).\nUloi nespustite¾ne",							// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Uloi &ako...\tCtrl+Shift+S",																		// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Uloí program do súboru s inım menom alebo na inı disk.\nUloi ako",								// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribúcia...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Uloí distribuènú needitovate¾nú verziu programu (len u licencie Professional).\nDistribúcia",		// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Ex&port...",																						// volba k exportování programu
IDN_EXPORT,					"Exportuje program do textového tvaru.\nExport",													// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Importuje program z textoveho tvaru.\nImport",														// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"Úpr&avy",																							// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Naspä\tCtrl+Z",																					// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Vráti stav pred vykonaním zmeny.\nNaspä",															// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Odvola\tCtrl+Y",																					// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Odvolá vrátenie stavu pred vykonaním zmeny.\nOdvola",												// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"&Vyòa\tCtrl+X",																					// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Vyjme vybranú èas a uloí ju do schránky.\nVyòa",												// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Kopírova\tCtrl+C",																				// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Zkopíruje vybranú èas do schránky.\nKopírova",													// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"V&loi\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Vloí obsah schránky na aktuálnu pozíciu.\nVloi",												// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Zruši\tDelete",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Zruší vybranú èas.\nZruši",																		// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Vybr&a všetko\tCtrl+A",																			// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Vyberie všetko.\nVybra všetko",																	// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"&Dithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Pri importe a zmenšovaní obrázkov pouije dithering.\nDithering",									// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&Zobrazenie",																						// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"Z&väèši\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Zväèší mierku zobrazenia.\nZväèši",																// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Z&menši\tCtrl+[-]",																				// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Zmenší mierku zobrazenia.\nZmenši",																// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"&Predošlá editácia\tCtrl+hore",																	// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Navráti k pøedošlému editovanému prvku.\nPredošlá editácia",										// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"&Nasledujúca editácia\tCtrl+dolu",																	// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Navráti k nasledujúcemu editovanému prvku.\nNasledujúca editácia",									// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&H¾adanie textu...\tCtrl+F",																		// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Nájde zadanı text.\nH¾adanie textu",																// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"&Dozadu text\tShift+F3",																			// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Nájde predošlı vıskyt h¾adaného textu.\nDozadu text",												// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"N&asledujúci text\tF3",																			// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Nájde nasledujúci vıskyt h¾adaného textu.\nDopredu text",											// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"P&rogram",																							// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Zamknú",																							// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Zamkne prvok proti modifikácii.\nZamknú",															// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Vypnú",																							// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Vypne funkciu prvku.\nVypnú",																		// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Popis\tAlt+Enter",																				// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Edituje popis prvku.\nPopis",																		// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Implicitnı p&opis",																				// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Pouije implicitnı popis prvku.\nImplicitnı popis",												// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Ikona",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Edituje ikonu prvku.\nIkona",																		// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Implicitná i&kona",																				// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Pouije implicitnú ikonu prvku.\nImplicitná ikona",												// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"&Deklarácia",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Nájde deklaráciu prvku.\nDeklarácia",																// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"Pr&edošlé pouitie",																				// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Nájde predošlé pouitie prvku.\nPredošlé pouitie",												// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"&Nasledujúce pouitie",																			// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Nájde nasledujúce pouitie prvku.\nNasledujúce pouitie",											// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Obrázok",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"Roz&mery...",																						// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Nastaví celkové rozmery.\nRozmery",																// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Raster",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Zapne alebo vypne zobrazenie orientaèného rastra.\nRaster",										// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"Úpr&avy...",																						// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Upraví obrázok alebo jeho èas (zmena ve¾kosti, otoèenie, farby).\nÚpravy",						// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"O&tlaèok bloku",																					// volba k otisku bloku do obrázku
IDN_OTISK,					"Otlaèí blok do obrázku.\nOtlaèok bloku",															// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horizontálne",																					// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Preklopí obrázok alebo jeho èas horizontálne.\nHorizontálne",										// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertikálne",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Preklopí obrázok alebo jeho èas vertikálne.\nVertikálne",											// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"V¾av&o",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Otoèí obrázok do¾ava (o 90 stupòov oproti smeru hodinovıch ruèièiek).\nV¾avo",						// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"V&pravo",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Otoèí obrázok doprava (o 90 stupòov vo smere hodinovıch ruèièiek).\nVpravo",						// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"&Dvojnásobok",																						// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Zväèší ve¾kos obrázku alebo jeho èasti na dvojnásobok.\nDvojnásobok",								// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"Polov&ica",																						// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Zmenší ve¾kos obrázku alebo jeho èasti na polovicu.\nPolovica",									// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"V&e¾kos...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Zmení ve¾kos obrázku alebo jeho èasti volite¾ne.\nVe¾kos",										// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"&Zámena",																							// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Zamení v obrázku alebo jeho èasti farby ¾avého a pravého tlaèítka myši.\nZámena",					// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"&Náhrada",																							// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Nahradí v obrázku alebo jeho èasti farbu pravého tlaèítka myši farbou ¾avého tlaèítka.\nNáhrada",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Nástroje",																						// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Pero",																							// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Kreslí pomocou pera.\nPero",																		// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"Èia&ra",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Kreslí èiaru.\nÈiara",																				// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"Ob&dånik",																						// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Kreslí obdånik.\nObdånik",																		// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"&Vyplnenı obdånik",																				// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Kreslí vyplnenı obdånik.\nVyplnenı obdånik",														// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Krunica",																						// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Kreslí krunicu.\nKrunica",																		// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Kru&h",																							// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Kreslí kruh.\nKruh",																				// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Elipsa",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Kreslí elipsu.\nElipsa",																			// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"&Ovál",																							// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Kreslí ovál.\nOvál",																				// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"G&u¾a",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Kreslí gu¾u.\nGu¾a",																				// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"Vı&ber",																							// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Oznaèí zvolenú èas ako vybranú.\nVıber",															// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"&Spray",																							// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Kreslí pomocou spraya.\nSpray",																	// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"Pipet&a",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Nastaví farbu pod kurzorom ako vybranú.\nPipeta",													// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"Vıp&lò",																							// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Vyplní plochu farbou.\nVıplò",																		// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Text",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Vypíše text.\nText",																				// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"&Hrúbka",																							// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Hrúbka èiar &1 bod",																				// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Kreslí èiary hrúbky 1 bod.\nHrúbka èiar 1 bod",													// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Hrúbka èiar &2 body",																				// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Kreslí èiary hrúbky 2 body.\nHrúbka èiar 2 body",													// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Hrúbka èiar &5 bodov",																				// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Kreslí èiary hrúbky 5 bodov.\nHrúbka èiar 5 bodov",												// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Hrúbka èiar &9 bodov",																				// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Kreslí èiary hrúbky 9 bodov.\nHrúbka èiar 9 bodov",												// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Hrúbka èiar 21 &bodov",																			// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Kreslí èiary hrúbky 21 bodov.\nHrúbka èiar 21 bodov",												// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"P&locha",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Editácia",																						// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Zapne alebo vypne mód editácie políèok plochy.\nEditácia",											// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Vıplò",																							// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Zapne alebo vypne mód vyplòovania plochy políèkom.\nVıplò",										// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Predmety",																						// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Edituje predmety na ploche.\nPredmety",															// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Prepínaè &1",																						// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Edituje prepínaè 1.\nPrepínaè 1",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Prepínaè &2",																						// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Edituje prepínaè 2.\nPrepínaè 2",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Prepínaè &3",																						// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Edituje prepínaè 3.\nPrepínaè 3",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Prepínaè &4",																						// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Edituje prepínaè 4.\nPrepínaè 4",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Prepínaè &5",																						// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Edituje prepínaè 5.\nPrepínaè 5",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"Èí&slo 1",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Edituje èíselnú hodnotu 1 (rozsah 0 a 1023).\nÈíslo 1",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"Èís&lo 2",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Edituje èíselnú hodnotu 2 (rozsah 0 a 1023).\nÈíslo 2",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Èísl&o 3",																							// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Edituje èíselnú hodnotu 3 (rozsah 0 a 127).\nÈíslo 3",											// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"Sp&rajt",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Vlastnosti",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Nastaví vlastnosti sprajtu (poèet fází, smerov, ...).\nVlastnosti",								// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Spustí mód testu sprajtu.\nTest",																	// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"Zv&uk",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Prehra",																							// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Spustí prehrávanie.\nPrehra",																		// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"Poza&stavi",																						// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pozastaví prehrávanie.\nPozastavi",																// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"&Zastavi",																						// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Zastaví prehrávanie.\nZastavi",																	// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Opakovane",																						// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Zapne alebo vypne opakovanie prehrávania.\nOpakovane",												// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Nahra",																							// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Spustí nahrávanie.\nNahra",																		// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Hudba",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Naspä",																							// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Posunie prehrávanie o 10 sekúnd naspä.\nNaspä",													// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Vpred",																							// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Posunie prehrávanie o 10 sekúnd vpred.\nVpred",													// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"O aplikácii Peter",																				// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Peter verzia",																						// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Ing. Miroslav Nìmeèek",														// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																		// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Ronov pod Radhoštìm",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Èeská republika",																					// Èeská Republika
IDC_DEMOTEXT1,				"Demoverzia neumoòuje ukladanie programov ani spúšanie",											// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"novıch èi zmenenıch programov. Editaèné monosti,",												// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"nápoveda a ukladanie do kninice sú plne funkèné.",												// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Aktuálne informácie o produktu získate na internetovskej adrese:",									// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"Objednávky je moné zasie¾a na adresu:",															// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENCIA",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"neobmedzená",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"pre 1 poèítaè",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"poèítaèe",																							// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"poèítaèov",																						// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Lite verzia aplikácie Peter poskytuje obmedzené programové vybavenie",								// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(nefunkèné prvky sú oznaèené zošednutımi ikonami). Lite verzia",									// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"je FREEWARE a je moné ju vo¾ne šíri a pouíva k súkromım",										// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"potrebám. Pre komerèné vyuitie a pre školy sa vyaduje licenènı",									// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"poplatok pod¾a bliších specifikácií na adrese www.gemtree.com.",									// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"H¾adanie textu",																					// titulek okna hledání textu
IDN_FINDTEXT,				"Zadajte h¾adanı text:",																			// vızva k zadání textu k hledání
IDN_CANCEL0,				"Storno",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Rozmery plochy",																					// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Šírka:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Vıška:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Nemono otvori",																					// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"Program nemono otvori.",																			// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"Zrejme je u otvorenı inım programom",																// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"alebo je prístup k súboru zakázanı.",																// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Chyba èítania",																					// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Chyba pri èítaní programu.",																		// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"Program je poškodenı alebo bol vytvorenı vyššou",													// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"verziou editoru a nemusí preto správne fungova.",													// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Nepodporované príkazy",																			// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Varovanie: Program pouíva príkazy nepodporované",													// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"Lite verziou aplikácie Peter. Uloením programu sa",												// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"program môe sta nefunkènım.",																	// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Úpravy obrázku alebo jeho vybranej èasti",															// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Preklopenie",																						// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horizontálne",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertikálne",																						// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Otoèenie",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 stupòov)",																			// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 stupòov)",																			// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 stupòov)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 stupòov)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 stupòov)",																			// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 stupòov)",																			// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 stupòov)",																			// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 stupòov)",																			// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 stupòov)",																			// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 stupòov)",																			// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 stupòov)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 stupòov)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Zväèšenie",																						// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Dvojnásobok",																						// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Polovica",																							// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Volite¾né",																						// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Farby",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"¼avé <-> pravé tlaèítko",																			// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"¼avé -> pravé tlaèítko",																			// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Rozmery obrázku",																					// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Rozmery sú zadané",																				// nadpis rámeèku volby jednotky
IDC_KROK,					"V &krokoch",																						// [1] volba jednotky v krocích
IDC_BOD,					"V &bodoch",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Zmena ve¾kosti obrázku alebo jeho èasti",															// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Súèasné rozmery:",																					// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"krokov",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"bodov",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"Nové rozmery",																						// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Šírka:",																							// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Vıška:",																							// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"V krokoch",																						// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"V bodoch",																							// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"V percentách",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Zachova pôvodnı pomer strán (pomer šírka/vıška)",													// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Zjemni hrany (presnı, ale pomalı prevod)",														// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (zapnú pre fotografie, vypnú pre kresby)",												// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Vıber farby",																						// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Program nemono vytvori",																			// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Program sa nepodarilo vytvori.",																	// 1. øádek hlášení
IDN_JINE_JMENO,				"Skúste iné meno.",																					// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Rušenie programu",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Naozaj chcete zruši zvolenı program?",															// 1. øádek hlášení
IDN_SELECT_DEL2,			"VAROVANIE: program u nebude mono obnovi!",														// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Rušenie zloky",																					// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Naozaj chcete zruši zvolenú zloku?",																// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Zloku nemono zruši",																			// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"Zloku nemono zruši, pokia¾ nieje prázdna.",														// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Program nemono zruši",																			// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"Program nemono zruši, je chránenı proti zápisu a rušeniu.",										// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"Nová zloka",																						// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"Ako sa bude nová zloka vola?",																	// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Zloku nemono vytvori",																			// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"Zloku sa nepodarilo vytvori.",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Zloka existuje",																					// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Pozor - taká zloka u existuje.",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Program existuje",																					// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Pozor - takı program u existuje.",																// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"Novı program",																						// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"Ako sa bude novı program vola?",																	// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Kópia programu",																					// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"Ako sa bude zkopírovanı program vola?",															// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Vlastnosti sprajtu",																				// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animácia",																							// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Èasovı odstup medzi fázami:",																		// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"milisekúnd",																						// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Fází na krok (0 = ihneï):",																		// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Hladina pre zobrazenie (0 = predmety):",															// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Poèet obrázkov",																					// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Fází pre pokoj:",																					// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Fází pre pohyb:",																					// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Smerov:",																							// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Rozmer obrázku",																					// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Šírka obrázku:",																					// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Vıška obrázku:",																					// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Test sprajtu",																						// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Chyba uloenia",																					// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"Program nemono uloi.",																			// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Zkontrolujte, èi nieje spustenı",																	// 2. øádek hlášení
IDN_WRITEERR3,				"alebo èi nieje chránenı proti zápisu.",															// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"V prípade potreby ulote program",																	// 4. øádek hlášení
IDN_WRITEERR5,				"s inım menom alebo na inı disk.",																	// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Program bol zmenenı",																				// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Program bol zmenenı.\nChcete zmeny uloi?",														// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Poloka je pouívaná",																				// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Varovanie - rušená poloka je v programu pouívaná.\nJej zrušením zrušíte i prípadné podvetvy poloky.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Neobnovite¾né rušenie",																			// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Varovanie - rušíte prvok z kninice.\nZrušenie je nenávratné, prvok nebude mono obnovi.",		// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Nedostatok pamäti",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Nieje dos pamäti na vykonanie poadovanej operácie!\n\nUvolnite miesto na systémovom disku Windows\npríp. zkontrolujte nastavenie virtuálnej pamäti Windows.\nProgram sa teraz môe nachádza v nestabilnom stave,\npreto ho, prosím, pokia¾ mono urıchlene ukonèite.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"¼utujem, program bude ukonèenı z dôvodu nedostatku pamäti!",										// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Poškodené licenèné údaje",																			// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"Licenèné údaje boly poškodené. Spuste znovu inštalátor aplikácie Peter pre opravu licenènıch údajov.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Koniec èasovo obmedzenej prevádzky",																// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"Uplynula obmedzená doba prevádzky aplikácie Peter.",												// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Blíiaci sa koniec èasovo obmedzenej prevádzky",													// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"Prevádzka aplikácie Peter je èasovo obmedzená.\nPoèet zvyšnıch dòov do konca prevádzky:",			// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"Chyba systému",																					// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Nedostatok systémovıch prostriedkov na spustenie programu PETER.EXE.",								// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Program poškodenı",																				// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Program PETER.EXE je poškodenı, nemono ho spusti.",												// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Uloi do iného súboru",																			// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programy",																							// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"Všetky súbory",																					// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Uloi distribuènú verziu programu",																// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Program u existuje",																				// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Varovanie - ukladanı súbor tohto mena u existuje.\n\nUkladáte distribuènú needitovate¾nú verziu programu\na ak je prepisovanı program zdrojovım programom,\njeho zdrojovı tvar by bol nenávratne ztratenı.\n\nChcete pokraèova a prepísa súbor?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Nespustite¾nı program",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"Tento program bol vytvorenı programovacím nástrojom Peter\na je teraz uloenı v nespustite¾nej forme.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Nastavenie písma",																					// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Vzorka:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"Ukáka, ako môe vyzera text s mäkèeòmi a dåòami.",												// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Štandardné písmo",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Tuèné",																							// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Kurzíva",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Podèiarknuté",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Preèiarknuté",																						// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Bez pätièiek",																						// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"S pätièkami",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"S pevnım rozostupom",																				// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Vybra zo zoznamu",																				// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"Zoznam typov písiem:",																				// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Vıška:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Šírka[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Styl",																								// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Vzh¾ad",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Zloka a meno k exportu programu",																	// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Meno importovaneho programu",																		// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Programy Petra",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"prázdne políèko",																					// prázdnı implicitní pøedmìt
IDF_GROUP,					"skupina",																							// skupina prvkù
IDF_IF,						"podmienené vykonanie príkazov",																	// záhlaví podmínky
IDF_IF_COND,				"ak platí, e",																						// test podmínky (IF)
IDF_IF_YES,					"potom vykonaj",																					// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"inak vykonaj",																						// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"podmienené opakovanie príkazov",																	// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"pokia¾ platí",																						// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"opakuj príkazy",																					// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"preruš opakovanie",																				// pøerušení smyèky (BREAK)
IDF_MINUS,					"záporné znamienko",																				// záporné znaménko "-" v èísle
IDF_CASE,					"viacstupòové vetvenie príkazov",																	// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"pre hodnotu vırazu",																				// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"vykonaj príkazy v prípade, e",																	// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"vıraz je rovnı hodnote",																			// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"inak vykonaj príkazy",																				// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"èíselná konštanta",																				// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"exponent",																							// exponent v èísle
IDF_EQU,					"je rovné",																							// podmínka =
IDF_NEQU,					"nieje rovné",																						// podmínka <>
IDF_EQGR,					"je väèšie alebo rovné",																			// podmínka >=
IDF_EQLT,					"je menšie alebo rovné",																			// podmínka <=
IDF_GR,						"je väèšie ako",																					// podmínka >
IDF_LT,						"je menšie ako",																					// podmínka <
IDF_AND,					"a súèasne",																						// logickı souèin
IDF_OR,						"alebo",																							// logickı souèet
IDF_XOR,					"buï alebo (vıhradné alebo)",																		// logickı vıhradní souèet
IDF_NOT,					"ak neplatí, e",																					// logická negace
IDF_ADD,					"súèet",																							// souèet èísel
IDF_SUB,					"rozdiel",																							// rozdíl èísel
IDF_MUL,					"násobok",																							// násobek èísel
IDF_DIV,					"podiel",																							// podíl èísel
IDF_REAL,					"èíslo",																							// èíselná promìnná
IDF_ICON,					"predmet",																							// pøedmìtová promìnná
IDF_SND,					"zvuk",																								// zvuková promìnná
IDF_MUS,					"hudba",																							// hudební promìnná
IDF_FNC,					"funkcia",																							// funkce
IDF_MAP,					"plocha",																							// promìnná plochy
IDF_SPRITE,					"sprajt",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"riadenie programu - rozšírenie",																	// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"text",																								// textová promìnná
IDF_WINDOWS,				"okná",																								// skupina prvkù pro øízení oken
IDF_PAR,					"vstupné premenné",																					// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"vıstupná premenná",																				// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"plocha - rozšírenie",																				// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"zoznam",																							// záhlaví seznamu (LIST)
IDF_OPER,					"riadenie programu",																				// skupina prvkù pro øízení programu
IDF_KROK,					"krok",																								// Petøík popojít o krok vpøed
IDF_VLEVO,					"v¾avo",																							// Petøík otoèit doleva
IDF_VPRAVO,					"vpravo",																							// Petøík otoèit doprava
IDF_VZAD,					"nazad",																							// Petøík otoèit vzad
IDF_PETRIK,					"Petrík",																							// skupina prvkù Petøíka
IDF_BOOL,					"príznak",																							// logická promìnná
IDF_TEXT_CONST,				"textová konštanta",																				// textová konstanta
IDF_TRUE,					"áno",																								// logickı pøíznak TRUE
IDF_FALSE,					"nie",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucka",																							// skupina prvkù Lucky
IDF_PETRA_KROK,				"krok",																								// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"v¾avo",																							// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"vpravo",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"nazad",																							// Lucka otoèit vzad
IDF_RYCHLE,					"vidite¾nı",																						// viditelnost Petøíka
IDF_EXIT,					"koniec funkcie",																					// pøerušení funkce
IDF_PETRA_RYCHLE,			"vidite¾ná",																						// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"zvuk a hudba",																						// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"predmet pred Petríkom",																			// pøedmìt pøed Petøíkem
IDF_SMER,					"smer",																								// smìr otoèení Petøíka
IDF_POZICEX,				"horizontálna pozícia",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"vertikálna pozícia",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"predmet pred Luckou",																				// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"smer",																								// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"horizontálna pozícia",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"vertikálna pozícia",																				// vertikální souøadnice Lucky
IDF_CONST,					"vıpoèty",																							// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"aritmetické operácie",																				// skupina èíselnıch operátorù
IDF_FUNC,					"funkcie",																							// skupina èíselnıch funkcí
IDF_POROVNANI,				"porovnanie",																						// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logické operácie",																					// skupina logickıch prvkù
IDF_MOD,					"modulo",																							// èíselnı operátor modulo
IDF_SIN,					"sínus",																							// funkce sinus
IDF_COS,					"kosínus",																							// funkce kosinus
IDF_TG,						"tangens",																							// funkce tangens
IDF_COTG,					"kotangens",																						// funkce kotangens
IDF_ARCSIN,					"arkussínus",																						// funkce arcus sinus
IDF_ARCCOS,					"arkuskosínus",																						// funkce arcus kosinus
IDF_ARCTG,					"arkustangens",																						// funkce arcus tangens
IDF_ARCCOTG,				"arkuskotangens",																					// funkce arcus kotangens
IDF_PI,						"Ludolfovo èíslo",																					// Ludolfovo èíslo (pí)
IDF_INTEGER,				"celoèíselná èas",																					// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"desatinná èas",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"absolútna hodnota",																				// funkce absolutní hodnoty
IDF_SQRT,					"druhá odmocnina",																					// funkce druhá mocnina
IDF_FACT,					"faktoriál",																						// funkce faktoriál
IDF_RAND,					"náhodné èíslo (0 <= x < 1)",																		// náhodné èíslo
IDF_EUL,					"Eulerova konštanta",																				// Eulerova konstanta (e)
IDF_DEGRAD,					"prevod stupòov na radiány",																		// funkce konverze stupòù na radiány
IDF_RADDEG,					"prevod radiánov na stupne",																		// funkce konverze radiánù na stupnì
IDF_LOG,					"dekadickı logaritmus",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"prirodzenı logaritmus",																			// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"prirodzená exponenciálna funkcia",																	// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"mocnina",																							// operátor mocniny
IDF_UHEL,					"uhol, smer",																						// skupina úhlù (smìrù)
IDF_UHEL0,					"vpravo (0 pi, tj. 0 stupòov)",																		// smìr vpravo
IDF_UHEL45,					"vpravo hore (1/4 pi, tj. 45 stupòov)",																// smìr vpravo nahoru
IDF_UHEL90,					"hore (1/2 pi, tj. 90 stupòov)",																	// smìr nahoru
IDF_UHEL135,				"v¾avo hore (3/4 pi, tj. 135 stupòov)",																// smìr vlevo nahoru
IDF_UHEL180,				"v¾avo (1 pi, tj. 180 stupòov)",																	// smìr vlevo
IDF_UHEL225,				"v¾avo dolu (1 1/4 pi, tj. 225 stupòov)",															// smìr vlevo dolù
IDF_UHEL270,				"dolu (1 1/2 pi, tj. 270 stupòov)",																	// smìr dolù
IDF_UHEL315,				"vpravo dolu (1 3/4 pi, tj. 315 stupòov)",															// smìr vpravo dolù
IDF_COMMAND,				"ovládanie",																						// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"èakanie (bez zadania = 0.05 s)",																	// pøíkaz pro èekání
IDF_KLAV,					"klávesnica",																						// skupina ovládání klávesnice
IDF_KLAV_TEST,				"je stisknutá klávesa",																				// test stisknuté klávesy
IDF_KLAV_VKEY,				"vstup klávesy (neèaká na stisk)",																	// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"vstup znaku (neèaká na stisk)",																	// vstup znaku bez èekání
IDF_KLAV_VK,				"klávesy",																							// skupina kódù kláves
IDF_KLAV_FX,				"funkèné klávesy",																					// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"písmená",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numerická klávesnica",																				// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"znakové klávesy",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"riadiace klávesy",																					// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"prieh¾adnost",																						// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 End",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 dolu",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 PgDn",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 v¾avo",																							// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 vpravo",																							// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Home",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 hore",																							// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Del",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 ! (+ 1)",																						// kód klávesy 1 !
IDF_VK_2,					"2 @ (¾ 2)",																						// kód klávesy 2 @
IDF_VK_3,					"3 # (š 3)",																						// kód klávesy 3 #
IDF_VK_4,					"4 $ (è 4)",																						// kód klávesy 4 $
IDF_VK_5,					"5 % ( 5)",																						// kód klávesy 5 %
IDF_VK_6,					"6 ^ ( 6)",																						// kód klávesy 6 ^
IDF_VK_7,					"7 & (ı 7)",																						// kód klávesy 7 &
IDF_VK_8,					"8 * (á 8)",																						// kód klávesy 8 *
IDF_VK_9,					"9 (  (í 9)",																						// kód klávesy 9 (
IDF_VK_0,					"0 ) (é 0)",																						// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~ (; °)",																						// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _ (= %)",																						// kód klávesy - _
IDF_VK_ROVNITKO,			"= + (´ ¡)",																						// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ | (ò ) )",																						// kód klávesy \ |
IDF_VK_LLOMENA,				"[ { (ú /)",																						// kód klávesy [ {
IDF_VK_RLOMENA,				"] } (ä ( )",																						// kód klávesy ] }
IDF_VK_STREDNIK,			"; : (ô \")",																						// kód klávesy ; :
IDF_VK_RCARKA,				"\' \" (§ !)",																						// kód klávesy ' "
IDF_VK_CARKA,				", < (, ?)",																						// kód klávesy , <
IDF_VK_TECKA,				". > (. :)",																						// kód klávesy . >
IDF_VK_LOMITKO,				"/ ? (- _)",																						// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"menu Windows v¾avo",																				// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Back Space",																						// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"lokálne menu",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"v¾avo",																							// kód klávesy Vlevo
IDF_VK_RIGHT,				"vpravo",																							// kód klávesy Vpravo
IDF_VK_UP,					"hore",																								// kód klávesy Nahoru
IDF_VK_DOWN,				"dolu",																								// kód klávesy Dolù
IDF_VK_INSERT,				"Insert",																							// kód klávesy Insert
IDF_VK_DELETE,				"Delete",																							// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"End",																								// kód klávesy End
IDF_VK_PAGEUP,				"Page Up",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Page Down",																						// kód klávesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"Shift ¾avı",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"Ctrl ¾avı",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"Alt ¾avı",																							// kód klávesy Levı Alt
IDF_VK_SPACE,				"medzerník",																						// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"myš",																								// skupina prvkù myši
IDF_MOUSE_L,				"¾avé tlaèítko myši je drané",																		// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"pravé tlaèítko myši je drané",																	// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"pozícia myši v horizontálnom smere",																// horizontální souøadnice myši
IDF_MOUSE_Y,				"pozícia myši vo vertikálnom smere",																// vertikální souøadnice myši
IDF_EQU_TEXT,				"zhodnos textov",																					// operátor porovnání textù
IDF_EQU_ICO,				"zhodnos predmetov",																				// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"sprajty - rozšírenie",																				// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"okno má okraj",																					// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"okno má titulok",																					// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"parametry programu",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"návratovı kód",																					// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"obrázok",																							// promìnná obrázku
IDF_REPEAT,					"opakovanie príkazov s poètom",																		// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"pre poèet opakovaní",																				// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"okraj plochy",																						// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horizontálne",																						// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertikálne",																						// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"smer",																								// smìr sprajtu
IDF_SPRITE_MOVE,			"v pohybu",																							// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"vidite¾nı",																						// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"poèet",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"index",																							// index seznamu
IDF_LIST_AUTO,				"inkrementácia indexu",																				// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Petrík - rozšírenie",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucka - rozšírenie",																				// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"èíselná hodnota 1 (rozsah 0 a 1023)",																// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"èíselná hodnota 1 (rozsah 0 a 1023)",																// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"èíselná hodnota 2 (rozsah 0 a 1023)",																// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"èíselná hodnota 2 (rozsah 0 a 1023)",																// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"èíselná hodnota 3 (rozsah 0 a 127)",																// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"èíselná hodnota 3 (rozsah 0 a 127)",																// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"prepínaè 1",																						// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"prepínaè 1",																						// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"prepínaè 2",																						// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"prepínaè 2",																						// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"prepínaè 3",																						// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"prepínaè 3",																						// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"prepínaè 4",																						// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"prepínaè 4",																						// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"prepínaè 5",																						// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"prepínaè 5",																						// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"texty",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"¾avá èas textu",																					// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"dåka ¾avej èasti textu",																			// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"pravá èas textu",																					// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"poèiatok pravej èasti textu",																		// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"stredná èas textu",																				// funkce støední èásti textu
IDF_TEXT_MID_POS,			"poèiatok strednej èasti textu",																	// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"dåka strednej èasti textu",																		// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"dåka textu",																						// funkce zjištìní délky textu
IDF_TEXT_ADD,				"zlúèenie textov",																					// operátor pro slouèení textù
IDF_TEXT_SCAN,				"prevod èísla z textového tvaru",																	// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"prevod èísla na textovı tvar",																		// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"abecedné porovnanie textov",																		// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"prevod na malé písmená",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"prevod na ve¾ké písmená",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"nájdenie pozície s textom (-1 = nieje)",															// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"vstupnı text",																						// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"h¾adanı text",																						// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"informaènı text",																					// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"nadpis okna",																						// titulek hlavního okna (textová promìnná)
IDF_ORD,					"prevod znaku na èíselnı kód",																		// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"prevod èíselného kódu na znak",																	// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"zvuk",																								// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"prehratie zvuku",																					// pøehrátí zvuku
IDF_SOUND_STOP,				"vypnutie zvuku (bez zadania = všetko)",															// vypnutí zvuku
IDF_COLOR,					"farba",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"grafika",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"farba pera",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"hrúbka pera",																						// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"bod",																								// nakreslení grafického bodu
IDF_POINT_X,				"horizontálna súradnica bodu X",																	// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertikálna súradnica bodu Y",																		// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"èiara",																							// nakreslení èáry
IDF_LINE_X1,				"horizontálna súradnica èiary X1",																	// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertikálna súradnica èiary Y1",																	// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horizontálna súradnica èiary X2",																	// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertikálna súradnica èiary Y2",																	// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"obdånik",																							// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horizontálna súradnica obdånika X1",																// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertikálna súradnica obdånika Y1",																// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horizontálna súradnica obdånika X2",																// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertikálna súradnica obdånika Y2",																// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"vyplnenı obdånik",																				// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horizontálna súradnica vyplneného obdånika X1",													// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertikálna súradnica vyplneného obdånika Y1",														// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horizontálna súradnica vyplneného obdånika X2",													// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertikálna súradnica vyplneného obdånika Y2",														// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"vıplò",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horizontálna súradnica vıplne X",																	// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertikálna súradnica vıplne Y",																	// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"krunica",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horizontálna súradnica stredu X",																	// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertikálna súradnica stredu Y",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"polomer",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"kruh",																								// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horizontálna súradnica stredu X",																	// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertikálna súradnica stredu Y",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"polomer",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"trojúholník",																						// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horizontálna súradnica trojúholníka X1",															// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertikálna súradnica trojúholníka Y1",																// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horizontálna súradnica trojúholníka X2",															// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertikálna súradnica trojúholníka Y2",																// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horizontálna súradnica trojúholníka X3",															// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertikálna súradnica trojúholníka Y3",																// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"gu¾a",																								// nakreslení koule
IDF_SPHERE_X,				"horizontálna súradnica stredu X",																	// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertikálna súradnica stredu Y",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"polomer",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"zmena jasu farby",																					// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"jas farby (0 a 1)",																				// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"vstup klávesy (èaká na stisk)",																	// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"vstup znaku (èaká na stisk)",																		// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"iadna klávesa nebola stisknutá",																	// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"menu Windows vpravo",																				// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"Shift pravı",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"Ctrl pravı",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"Alt pravı",																						// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"stav Num Lock",																					// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"stav Caps Lock",																					// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"stav Scroll Lock",																					// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"stav Insert",																						// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"klepnutie ¾avım tlaèítkom myši",																	// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"klepnutie pravım tlaèítkom myši",																	// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"poklepanie ¾avım tlaèítkom myši",																	// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"poklepanie pravım tlaèítkom myši",																	// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"test myši v oblasti",																				// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horizontálna súradnica X poèiatku oblasti",														// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertikálna súradnica Y poèiatku oblasti",															// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"šírka oblasti",																					// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"vıška oblasti",																					// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"vıpis textu",																						// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horizontálna súradnica X textu",																	// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertikálna súradnica Y textu",																		// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"úhol orientácie textu",																			// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"vıška znakov",																						// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"relatívna šírka znakov (1 = bená)",																// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"tuènı text",																						// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"kurzíva",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"podèiarknutie",																					// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"preèiarknutie",																					// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"pätièky",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"písací stroj",																						// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"text pre vıpis",																					// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"poèet riadkov textu",																				// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"riadok textu",																						// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"èíslo riadku textu",																				// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"test zvuku (bez zadania = všetky zvuky)",															// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"poèet opakovaní (0 = trvale)",																		// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"predmet na pozícii s Petríkom",																	// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"predmet na pozícii s Luckou",																		// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"vykreslenie obrázku",																				// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"obrázok pre vykreslenie",																			// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horizontálna súradnica obrázku X",																	// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertikálna súradnica obrázku Y",																	// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horizontálna súradnica vırezu X",																	// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertikálna súradnica vırezu Y",																	// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"šírka vırezu",																						// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"vıška vırezu",																						// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"úschova vırezu z plochy ako obrázok",																// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"úschova vırezu z plochy ako predmet",																// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"jazyk (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",															// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"zvuk pre prehratie",																				// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"hlasitos zvuku (0 a 1)",																			// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"stereofónne vyváenie (-1 = v¾avo a +1 = vpravo)",												// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"preruši hrajúci zvuk",																			// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"komentár",																							// komentáø
IDF_SOUND_FUNCTIONS,		"zvukové funkcie",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"nastavenie vzh¾adu kurzoru myši",																	// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"obrázok kurzoru myši (bez zadania = pôvodnı)",														// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horizontálna súradnica X poèiatku oblasti",														// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertikálna súradnica Y poèiatku oblasti",															// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"šírka oblasti",																					// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"vıška oblasti",																					// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"prehratie hudby",																					// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"opakované prehrávanie hudby",																		// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"zastavi prehrávanie hudby",																		// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"pozastavi/pokraèova v prehrávaní hudby",															// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test prehrávania hudby",																			// test pøehrávání hudby
IDF_MUSIC_POS,				"pozícia v prehrávaní hudby",																		// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"dåka prehrávanej hudby",																			// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"zlúèenie farebnıch zloiek do farby",																// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"èervená zloka (0 a 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"zelená zloka (0 a 1)",																			// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"modrá zloka (0 a 1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"zistenie farby bodu",																				// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horizontálna súradnica X pre zistenie farby bodu",													// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertikálna súradnica Y pre zistenie farby bodu",													// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"druhá mocnina",																					// funkce druhá mocnina
IDF_MUSIC_GROUP,			"hudba",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"audio CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"prehratie CD od zadanej stopy (bez zadania = 1)",													// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"zastavenie prehrávania CD",																		// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"pozastavenie/pokraèovanie prehrávania CD",															// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test prehrávania CD",																				// test pøehrávání CD
IDF_CD_LENGTH,				"celková dåka",																					// celková délka CD
IDF_CD_TRACKS,				"poèet stôp",																						// poèet stop CD
IDF_CD_POS,					"pozícia od zaèiatku",																				// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"prehrávaná stopa",																					// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"dåka prehrávanej stopy",																			// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"pozícia od zaèiatku stopy",																		// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"súbory",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"základné operácie",																				// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"novı súbor",																						// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"nová zloka",																						// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"zrušenie súboru alebo zloky",																		// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"test existencie",																					// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"aktívny disk a zloka",																			// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"kapacita disku",																					// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"vo¾né miesto na disku",																			// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"menovka disku",																					// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"sériové èíslo disku",																				// zjištìní sériového èísla disku
IDF_FILE_READ,				"aktívny súbor (zloka) pre èítanie",																// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"aktívny súbor (zloka) pre zápis",																	// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"kópia súboru",																						// provedení kopie souboru
IDF_FILE_MOVE,				"presun/premenovanie súboru (zloky)",																// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disk",																								// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"parametre",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"atribút R/O (len pre èítanie)",																	// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"atribút HID (skrytı)",																				// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"atribút SYS (systémovı)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"atribút DIR (zloka)",																				// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"atribút ARC (archívny)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"atribút TEMP (prechodnı)",																			// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"atribút COMP (skomprimovanı)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"atribút OFF (neprístupnı)",																		// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"dátum a èas vytvorenia",																			// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"dátum a èas posledného prístupu",																	// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"dátum a èas poslednej modifikácie",																// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"údaje",																							// skupina dat souborù
IDF_FILE_BYTES,				"celé èíslo so znamienkom, 1 bajt",																	// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"celé èíslo bez znamienka, 1 bajt",																	// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"celé èíslo so znamienkom, 2 bajty",																// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"celé èíslo bez znamienka, 2 bajty",																// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"celé èíslo so znamienkom, 4 bajty",																// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"celé èíslo bez znamienka, 4 bajty",																// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"desatinné èíslo, 4 bajty",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"desatinné èíslo, 8 bajtov",																		// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"text zakonèenı binárnou nulou (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"text zakonèenı koncom riadku",																		// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"text s pevnou dåkou",																				// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"predmet (ICO)",																					// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"obrázok (BMP, JPG)",																				// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"zvuk (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"hudba (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"ukazate¾ èítania",																					// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"ukazate¾ zápisu",																					// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"dátum a èas",																						// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"aktuálny dátum a èas (poèet sekúnd od 1.1.1601)",													// aktuální datum a èas
IDF_DATETIME_UTC,			"prevod miestneho èasu na svetovı",																	// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"prevod svetového èasu na miestny",																	// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"zlúèenie poloiek dátumu a èasu",																	// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"rok",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"mesiac",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"deò",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"hodina",																							// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minúta",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"sekunda",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"milisekunda",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"rok z dátumu a èasu",																				// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"mesiac z dátumu a èasu",																			// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"deò z dátumu a èasu",																				// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"deò v tıdni z dátumu a èasu (0 = nede¾a, 1 = pondelok, ...)",										// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"hodina z dátumu a èasu",																			// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minúta z dátumu a èasu",																			// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"sekunda z dátumu a èasu",																			// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"milisekunda z dátumu a èasu",																		// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"prevod dátumu na text \"deò.mesiac.rok\"",															// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"prevod dátumu na text \"mesiac/deò/rok\"",															// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"prevod dátumu na text \"rok-mesiac-deò\"",															// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"prevod èasu na text \"hodina:minúta:sekunda\" (24 hodín)",											// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"prevod èasu na text \"hodina:minúta:sekunda x\" (12 hodín)",										// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"ve¾kos súboru",																					// velikost souboru
IDF_FILE_ERROR,				"príznak chyby operácie",																			// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"dåka textu s pevnou dåkou",																		// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"typ disku (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",														// zjištìní typu disku
IDF_TEXT_FORMAT2,			"prevod èísla na text - 2 èíslice",																	// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"prevod èísla na text - 8 èíslic HEX",																// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"celé èíslo so znamienkom, 3 bajty",																// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"celé èíslo bez znamienka, 3 bajty",																// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"dialógy",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"potvrdzovací dialóg (vracia 1=OK, 2=Storno, 3=Preruši, 4=Opakova, 5=Ignorova, 6=Áno, 7=Nie)",	// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"text",																								// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"nadpis",																							// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"ikona (0=niè, 1=chyba, 2=dotaz, 3=varovanie, 4=informácia)",										// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"tlaèítka (0=OK, 1=OK/Storno, 2=Preruši/Opakova/Ignorova, 3=Áno/Nie/Storno, 4=Áno/Nie, 5=Opakova/Storno)",	// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"implicitné tlaèítko (1 a 3)",																		// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"ïalší riadok",																						// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"zadanie textu",																					// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1. riadok vızvy",																					// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2. riadok vızvy",																					// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3. riadok vızvy",																					// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"prednastavenı text na zadanie",																	// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"vysunutie CD",																						// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"poèet bitov na vzorku (8 alebo 16)",																// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"vzorkovací kmitoèet (Hz)",																			// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"je zvuk stereofónny?",																				// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"dåka zvuku (sekúnd)",																				// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"konverzia na 8 bitov",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"konverzia na 16 bitov",																			// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"konverzia na stereo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"konverzia na mono",																				// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"konverzia na 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"konverzia na 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"konverzia na 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"zlúèenie zvukov",																					// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"zmena rıchlosti zvuku",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"zvuk pre konverziu",																				// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relatívna zmena rıchlosti (1 = bez zmeny)",														// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"tónovı generátor",																					// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"frekvencia tónu (Hz)",																				// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"dåka tónu (sekúnd)",																				// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"plocha",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"šírka plochy",																						// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"vıška plochy",																						// zjištìní vıšky plochy
IDF_MAP_X,					"súradnica X",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"súradnica Y",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"plocha",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"predmet",																							// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"èíselná hodnota 1 (rozsah 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"èíselná hodnota 2 (rozsah 0 a 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"èíselná hodnota 3 (rozsah 0 a 127)",																// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"prepínaè 1",																						// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"prepínaè 2",																						// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"prepínaè 3",																						// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"prepínaè 4",																						// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"prepínaè 5",																						// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"kópia vırezu plochy",																				// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"plocha s vırezom",																					// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"súradnica X vırezu",																				// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"súradnica Y vırezu",																				// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"šírka vırezu",																						// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"vıška vırezu",																						// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"konzola",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"hromadnı posun sprajtov vo smere X",																// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"hromadnı posun sprajtov vo smere Y",																// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"¾avı okraj okna sprajtov",																			// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"dolnı okraj okna sprajtov",																		// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"pravı okraj okna sprajtov",																		// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"hornı okraj okna sprajtov",																		// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"reim konzoly (musí by na zaèiatku hlavnej funkcie)",												// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"vıstup textu na konzolu",																			// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"vstup textu z konzoly",																			// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"chybovı vıstup textu na konzolu",																	// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"parameter programu (0 = meno programu)",															// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"meno programu s plnou cestou",																		// jméno tohoto programu s plnou cestou
IDF_EXEC,					"spustenie programu",																				// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"spustenie programu s èakaním",																		// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"pákovı ovládaè",																					// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"súradnica X pákového ovládaèa",																	// souøadnice X joysticku
IDF_JOYSTICK_Y,				"súradnica Y pákového ovládaèa",																	// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"súradnica Z pákového ovládaèa",																	// souøadnice Z joysticku
IDF_JOYSTICK_1,				"tlaèítko 1 pákového ovládaèa",																		// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"tlaèítko 2 pákového ovládaèa",																		// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"tlaèítko 3 pákového ovládaèa",																		// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"tlaèítko 4 pákového ovládaèa",																		// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"texty a obrázky",																					// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"èíslo prvku (0 = hlavné okno)",																	// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"zrušenie prvku alebo okna",																		// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"vytvorenie okna",																					// vytvoøení dialogového okna
IDF_WINDOW_X,				"horizontálna súradnica",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"vertikálna súradnica",																				// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"šírka",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"vıška",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"text",																								// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"vidite¾nos",																						// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"zákaz",																							// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"vytvorenie tlaèítka",																				// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"stisk tlaèítka alebo zmena prvku",																	// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"vytvorenie zaškrkávacieho boxu",																	// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"vytvorenie editaèného riadku",																		// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"vytvorenie prepínaèa",																				// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"spoloèné funkcie pre všetky prvky",																// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"vytvorenie editaèného po¾a",																		// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"tlaèítka",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"prepínaè zapnutı",																					// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"vstupné zameranie",																				// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"vytvorenie implicitného tlaèítka",																	// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"vytvorenie ikonového tlaèítka",																	// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"vytvorenie rámèeka",																				// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"vytvorenie zoznamu",																				// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"vytvorenie textu",																					// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"vytvorenie rozba¾ovacieho zoznamu",																// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"vytvorenie rozba¾ovacieho zoznamu s editáciou",													// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"zvıraznené písmo",																					// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"písmo s pevnım rozostupom",																		// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"vytvorenie prepínaèa - zaèiatok skupiny",															// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"zoznamy",																							// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"pridanie poloky do zoznamu",																		// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"vyprázdnenie zoznamu",																				// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"vytvorenie zoznamu s editáciou",																	// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"vytvorenie 3-stavového boxu",																		// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"prepínaè v neurèitom stave",																		// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"vytvorenie okna bez monosti zatvorenia",															// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"ikona",																							// ikona prvku dialogového okna
IDF_WINICON_NEW,			"vytvorenie ikony",																					// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"sprajt (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*Ludolfovo èíslo (= 360 stupòov)",																// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"vzdialenos 1 bodu (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"fáza",																								// fáze sprajtu
IDF_SPRITE_STATUS,			"stav",																								// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"celoobrazovkovı reim",																			// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"vyprázdnenie zásobníka kláves",																	// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"pozícia v prehrávaní zvuku",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"pozastavi/pokraèova v prehrávaní zvuku",															// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"zoznam súborov",																					// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"zhodnos plôch",																					// operátor porovnání ploch
IDF_EQU_PIC,				"zhodnos obrázkov",																				// operátor porovnání obrázkù
IDF_EQU_SPR,				"zhodnos sprajtov",																				// operátor porovnání sprajtù
IDF_EQU_SND,				"zhodnos zvukov",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"zhodnos hudby",																					// operátor porovnání hudeb
IDF_NET_GROUP,				"komunikácia",																						// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"sieová podpora DirectPlay",																		// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"zoznam spojení",																					// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"aktívne spojenie",																					// aktivní spojení DirectPlay
IDF_GAME_LIST,				"zoznam hier",																						// seznam bìících her DirectPlay
IDF_GAME_ACT,				"aktívna hra",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"zoznam hráèov",																					// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"aktívny hráè",																						// aktivní hráè DirectPlay
IDF_GAME_N1,				"èíselnı parameter hry 1 (-16384 a +16383)",														// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"èíselnı parameter hry 2 (-16384 a +16383)",														// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"èíselnı parameter hry 3 (-16384 a +16383)",														// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"èíselnı parameter hry 4 (-16384 a +16383)",														// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"èíselnı parameter hry 5 (-16384 a +16383)",														// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"èíselnı parameter hry 6 (-16384 a +16383)",														// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"èíselnı parameter hry 7 (-16384 a +16383)",														// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"èíselnı parameter hry 8 (-16384 a +16383)",														// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"prepínaè hry 1",																					// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"prepínaè hry 2",																					// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"prepínaè hry 3",																					// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"prepínaè hry 4",																					// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"prepínaè hry 5",																					// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"prepínaè hry 6",																					// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"prepínaè hry 7",																					// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"prepínaè hry 8",																					// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"nastavenie hry",																					// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"hostite¾ (riadiaci poèítaè)",																		// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"maximálne hráèov (0 = neobmedzenı)",																// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"èíslo aktívneho hráèa (-1 = nieje)",																// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"údaje",																							// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"odoslanie/príjem bloku údajov (-1 = všetkım/nieje)",												// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"èíslo",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"text",																								// text dat DirectPlay
IDF_GAME_DATAL,				"prepínaè",																							// pøepínaè dat DirectPlay
IDF_GAME_IP,				"IP adresa tohto poèítaèa",																			// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"celé èíslo 0 a 255 (bajt)",																		// èíslo bajt dat DirectPlay
IDF_INC,					"inkrementácia (pripoèíta 1)",																		// funkce inkrementace èísla
IDF_DEC,					"dekrementácia (odpoèíta 1)",																		// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"vytvorenie textu centrovaného",																	// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"tlaèítko pre klávesu Esc (-1 = nieje)",															// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"šírka obrázku",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"vıška obrázku",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"horizontálne preklopenie obrázku",																	// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"vertikálne preklopenie obrázku",																	// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"obrázky",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"zmena ve¾kosti obrázku",																			// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"obrázok",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"šírka (bez zadania = úmerná k vıške)",																// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"vıška (bez zadania = úmerná k šírke)",																// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"zjemni hrany",																					// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (fotografie)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"kreslenie",																						// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"vytvorenie obrázku",																				// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"obrázok",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"vytvorenie editoru RichEdit",																		// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"vıška znakov (0 = bená)",																			// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"šikmé písmo",																						// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"podèiarknuté písmo",																				// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"preèiarknuté písmo",																				// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"písmo s pätièkami",																				// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"relatívna šírka znakov (0 = bená, 1 = základná)",													// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"úhol sklonu textu",																				// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"vytvorenie textu zarovnaného vpravo",																// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"farba písma",																						// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"farba pozadia",																					// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"písmo prvku",																						// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"rıchlos prehrávania (1 = bená)",																	// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"rozlišovací kód (0 a 65535)",																		// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"zadanie súboru na otvorenie",																		// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"zadanie súboru na uloenie",																		// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"zadanie textu na h¾adanie",																		// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"zadanie farby",																					// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"maska súborov",																					// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"prednastavené meno súboru",																		// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"názov typu súborov",																				// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"zmena jasu obrázku",																				// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"obrázok pre zmenu jasu",																			// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"jas obrázku (1 = benı)",																			// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"otoèenie obrázku",																					// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"otáèanı obrázok",																					// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"úhol otoèenia",																					// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"dekompresia zvuku",																				// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"text je vo formáte UNICODE (2 bajty)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"konverzia plochy na obrázok",																		// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"konverzia predmetu na obrázok",																	// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"bitové operácie",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"bitovı súèin AND",																					// bitovı (binární) souèin AND
IDF_BIT_OR,					"bitovı súèet OR",																					// bitovı (binární) souèet OR
IDF_BIT_XOR,				"bitová inverzia XOR",																				// bitová (binární) inverze XOR
IDF_BIT_NOT,				"bitovı doplnok NOT",																				// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"maximálne bitové èíslo (dvojslovo)",																// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"bitová rotácia v¾avo",																				// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"bitová rotácia vpravo",																			// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"test myši v prvku",																				// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"vnútorná šírka",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"vnútorná vıška",																					// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"znaková sada (1250=stredoeurópska, 1251=ruská, 1252=západná)",										// èíslo pouité znakové sady fontù
IDF_USERFONT,				"uívate¾ské písmo",																				// jméno uivatelského fontu
IDF_ENUMFONTS,				"zoznam písiem",																					// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"nová plocha",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"šírka plochy",																						// šíøka nové plochy
IDF_MAP_NEW_H,				"vıška plochy",																						// vıška nové plochy
IDF_WINDOW_TOP,				"vdy hore",																						// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"prezıvka (alias)",																					// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"komunikaènı port",																					// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"otvorenie portu (-1=chyba)",																		// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"zatvorenie portu",																					// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"aktívny port",																						// aktivní port
IDF_COM_NUM,				"èíslo (0 a 255)",																					// vstup/vıstup èísla
IDF_COM_TEXT,				"znak (text)",																						// vstup/vıstup znaku
IDF_COM_BAUD,				"prenosová rıchlos",																				// pøenosová rychlost
IDF_COM_STOP,				"2 stopbity",																						// reim s 2 stopbity
IDF_COM_BITS,				"poèet bitov (5 a 8)",																				// poèet bitù na znak
IDF_COM_PARIT,				"parita (0=nieje, 1=lichá, 2=sudá)",																// zvolená parita
IDF_COM_IN,					"bol prijatı znak",																					// byl pøijatı znak
IDF_COM_SEND,				"vysielanie dovolené (CTS, RTS)",																	// povoleno vysílání
IDF_COM_RECEIVE,			"príjem dovolenı (DSR, DTR)",																		// povolen pøíjem
IDF_PICTURE_MASK,			"maskovanie obrázku",																				// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"obrázok",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"maska",																							// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"šírka po¾a k vıpisu textu (0 = nieje)",															// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"vytvorenie editaèného po¾a bez zalamovania",														// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"menite¾ná ve¾kos okna",																			// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"moné zatvorenie okna",																			// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"okno maximalizované",																				// maximalizace okna
IDF_WINDOW_MINIM,			"okno minimalizované",																				// minimalizace okna
IDF_PROGRESS_NEW,			"vytvorenie indikátoru priebehu",																	// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"vytvorenie horizontálneho jazdca",																	// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"vytvorenie vertikálneho jazdca",																	// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"aktuálna pozícia",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"zmiešavacie zariadenie",																			// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"zmiešavacie zariadenie",																			// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"cie¾ovı signál",																					// volba cílového signálu
IDF_MIX_LINE_SRC,			"zdrojovı signál (niè=iba cie¾ovı signál)",															// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"typ signálu",																						// zjištìní typu signálu
IDF_MIX_CONTROL,			"ovládací prvok",																					// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"typ prvku",																						// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"hodnota prvku (0 a 1)",																			// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"vıber hodnoty prvku",																				// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"ovládanı kanál (-1=všetky)",																		// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D grafika",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"okno 3D grafiky",																					// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"súradnica X okna 3D grafiky",																		// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"súradnica Y okna 3D grafiky",																		// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"šírka okna 3D grafiky",																			// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"vıška okna 3D grafiky",																			// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"videomód (šírka*vıška/bitov)",																		// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"grafické pozadie",																					// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"nastavenie",																						// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"vyplòovanie plôch",																				// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"osvetlenie",																						// mód osvìtlení
IDF_DIRECT3D_SHADES,		"plynulé tieòovanie",																				// mód stínování
IDF_DIRECT3D_INVERT,		"inverzia objektu",																					// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objekty",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"stena",																							// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"krych¾a",																							// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"gu¾a",																								// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"valec",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"kuel",																							// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"klonovanie",																						// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"objekt z textu",																					// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"objekt zo súboru",																					// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"aktívny objekt (0=scéna, 1=kamera, 2=svetlo)",														// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"zrušenie objektu",																					// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"viditelnı",																						// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"pripojenie",																						// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"objekt do súboru",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformácia",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"mierka vo smere X",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"mierka vo smere Y",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"mierka vo smere Z",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"otoèenie pod¾a osi X",																				// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"otoèenie pod¾a osi Y",																				// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"otoèenie pod¾a osi Z",																				// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"posun vo smere X",																					// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"posun vo smere Y",																					// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"posun vo smere Z",																					// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"povrch",																							// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"farba (-1=vnútorná, 2=bená)",																		// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"farba svietivosti",																				// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"matnos (0=vyp, 5=kov, 50=plast)",																	// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"farba odzrcadlivosti",																				// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"textura",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"mapovanie textury",																				// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"typ projekcie (0=plocha, 1=valec, 2=gu¾a, 3=chrom, 4=sklo)",										// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"súradnica X stredu projekcie",																		// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"súradnica Y stredu projekcie",																		// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"súradnica Z stredu projekcie",																		// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"otoèenie projekcie pod¾a osi X",																	// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"otoèenie projekcie pod¾a osi Y",																	// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"otoèenie projekcie pod¾a osi Z",																	// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"prieh¾adnost (1=normal, 11=oheò, 20=sklo, 54=prekryv)",											// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"obrysy (0=normal, 0.5=obrysy)",																	// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"metóda (0=adresy, 1=vrcholy, 2=plôšky)",															// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"poèiatok textury vodorovne",																		// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"poèiatok textury svisle",																			// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"stupeò zmenšenia textury vodorovne",																// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"stupeò zmenšenia textury svisle",																	// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"osvetlenie",																						// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"vytvori nové svetlo",																				// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"farba svetla",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"typ svetla (1=bodové, 2=kuelové, 3=smerové)",														// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"úhel svetelného kuelu",																			// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"úhel polotiena",																					// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"dosah svetla",																						// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"intenzita svetla (1=normal)",																		// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"lineárne zoslabenie",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"kvadratické zoslabenie",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"typ projekcie (0=persp, 1=orto, 2=r-persp, 3=r-orto)",												// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"scéna",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"farba pozadia scény (-1=vypnuté, -2=neinicializova)",												// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"textura pozadia scény",																			// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"farba hmly (-1=vypnuté)",																			// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"typ hmly (0=lin, 1=exp, 2=kvadr, +4=korekcia)",													// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"zaèiatok lineárne hmly",																			// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"koniec lineárne hmly",																				// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"hustota exp. a kvadr. hmly (0 a 1)",																// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"vzdialenos premietacej roviny",																	// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"vzdialenos doh¾adu",																				// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"tvori hornú podstavu",																			// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"tvori dolnú podstavu",																			// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"vyh¾adanie objektu",																				// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"súradnica X bodu",																					// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"súradnica Y bodu",																					// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"filtrácia zmenšenıch textur",																		// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"2D objekt",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terén z obrázku",																					// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"úroveò terénu",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"horizontálna súradnica",																			// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"vertikálna súradnica",																				// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"skupina",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"sloitost objektu (2 a 100)",																		// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"poradie rotací (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",										// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"ovladaè (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"rotaènı objekt",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terén z plochy",																					// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"odraz rozptyleného svetla (-1=implicitnı)",														// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"program je aktívna aplikácia",																		// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"vzdialenos bodu",																					// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"úhol bodu",																						// vıpoèet úhlu bodu
IDF_POLAR_X,				"súradnica X bodu",																					// souøadnice X bodu
IDF_POLAR_Y,				"súradnica Y bodu",																					// souøadnice Y bodu
IDF_FILE_LOGIC,				"logická hodnota",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"vyhladzenie textur (1=nie)",																		// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"presnı èítaè èasu",																				// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"rozptylené svetlo",																				// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"filtrácia zväèšenıch textur",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"filtrácia vzdialenıch textur",																		// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"vyplòovanie plôch objektu",																		// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"osvetlenie objektu",																				// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"plynulé tieòovanie objektu",																		// mód stínování
IDF_DIRECT3D_OMINFILTER,	"filtrácia zmenšenıch textur objektu",																// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"filtrácia zväèšenıch textur objektu",																// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"filtrácia vzdialenıch textur objektu",																// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"vidite¾ná strana objektu (0=obe, 1=predná, 2=zadná)",												// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"vytvori",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"normalizácia objektu",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"kruh",																								// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"trojúholník",																						// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"torus (parameter = priemer 0 a 1)",																// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"statickı 2D objekt",																				// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"pologu¾a",																							// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"rozhranie (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",								// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"ubehlı èas",																						// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"rıchlos renderovania",																			// rychlost renderování
IDF_DIRECT3D_FREE,			"vo¾ná videopame",																					// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D obrázok",																						// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"textury",																							// skupina textur
IDF_DIRECT3D_STAGE,			"stupeò (0 a 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"operácia s farbou (1=vyp, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"argument 1 farby (0=farba, 1=vısledok, 2=textura, 3=faktor, 16=inverzia)",							// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"argument 2 farby (0=farba, 1=vısledok, 2=textura, 3=faktor, 16=inverzia)",							// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"operácia alfa kanálu (1=vyp, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",									// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"argument 1 alfa kanálu (0=farba, 1=vısledok, 2=textura, 3=faktor, 16=inverzia)",					// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"argument 2 alfa kanálu (0=farba, 1=vısledok, 2=textura, 3=faktor, 16=inverzia)",					// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"horizontálne adresovanie (1=opakovanie, 2=zrkadlenie, 3=orezanie)",								// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"vertikálne adresovanie (1=opakovanie, 2=zrkadlenie, 3=orezanie)",									// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"zjemienie vzdialenıch textur (0=bené)",															// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"komolı kuel (parameter = priemer 0 a 1)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"farba faktoru textur",																				// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alfa zloka (0=prieh¾adnost a 1=farba)",															// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"poèet úrovní vzdialenıch textur (0=všetky)",														// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"renderovacia skupina (0-7=objekty, 8-11=prieh¾adné, 12-15=obrázky)",								// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"h¾bkove triedi renderovaciu skupinu",																// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"uklada h¾bkovú informáciu",																		// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"h¾bkovı test (1 nikdy, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 vdy)",									// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"prepoèet normál (parameter = úhol pre zjemienie)",													// pøepoèet normál
IDF_DIRECT3D_RENDER,		"renderovanie bez zobrazenia",																		// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"blok textu",																						// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"riadok poèiatku bloku",																			// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"pozícia poèiatku bloku",																			// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"riadok konca bloku (-1=konec)",																	// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"pozícia konca bloku (-1=konec)",																	// pozice konce bloku
IDF_WINDOW_POS2,			"aktuálna pozícia 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"vytvorenie tlaèítkového prepínaèa",																// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"vytvorenie tabu¾ky (parameter = zoznam titulkov)",													// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"šírka st¾pca tabu¾ky",																				// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"dosah tiena (0=vypnutı)",																			// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"zarovnanie st¾pca tabu¾ky (0=v¾avo, 1=vpravo, 2=stred)",											// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"vytvorenie horizontálneho posuvníku",																// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"vytvorenie vertikálneho posuvníku",																// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"zámena farieb",																					// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"prvá farba",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"druhá farba",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"náhrada farby",																					// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"pôvodná farba",																					// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"nová farba",																						// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"tisk obrázku",																						// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"objekt so zníenou úrovòou detailov (-1=nieje)",													// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"vzdialenos pre zníenie úrovne detailov",															// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"prida vzor pre morfovanie (-1=resetova)",														// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"stupeò morfovania (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"objektívovı odlesk",																				// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dynamická vımena dat DDE",																			// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"meno serveru/zoznam serverov",																		// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"meno tématu/zoznam témat",																			// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"meno poloky/zoznam poloiek",																		// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"program poskytuje poloku (je server)",															// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"typ poloky (0 a 7, -1=neplatná poloka)",														// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) èíslo",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) príznak",																						// pøíznak DDE
IDF_DDE_TEXT,				"(2) text",																							// text DDE
IDF_DDE_ICON,				"(3) predmet",																						// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) obrázok",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) zvuk",																							// zvuk DDE
IDF_DDE_MUSIC,				"(6) hudba",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprajt",																						// sprajt DDE
IDF_DDE_EXECUTE,			"príkaz k vykonaniu",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"knihovny DLL",																						// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"naèíst knihovnu",																					// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"uvolni knihovnu",																					// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"importova funkciu",																				// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"identifikátor knihovny",																			// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"meno funkcie",																						// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"poèet parametrov",																					// poèet parametrù importované funkce
IDF_DLL_EXEC,				"vykonanie funkcie",																				// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"vytvorenie pameového bloku",																		// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"uvolnenie pameového bloku",																		// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"zmena ve¾kosti pameového bloku",																	// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"adresa pameového bloku",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"nová ve¾kos",																						// nová velikost bloku pamìti
IDF_MEMORY_READ,			"ukazatel èítania",																					// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"ukazatel zápisu",																					// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"kopia dat",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"porovnanie dat",																					// porovnání bloku dat
IDF_MEMORY_BYTES,			"bajt so znamienkom",																				// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"bajt bez znamienka",																				// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"slovo so znamienkom",																				// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"slovo bez znamienka",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-bajt so znamienkom",																				// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-bajt bez znamienka",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"dvojslovo so znamienkom",																			// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"dvojslovo bez znamienka",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"reálne èíslo 4 bajty",																				// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"reálne èíslo 8 bajtov",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logická hodnota",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"text zakonèenı nulou",																				// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"ukazatel na text zakonèenı nulou",																	// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"text s pevnou dåkou",																				// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"dåka textu s pevnou dåkou",																		// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"èítanie dat zo súboru",																			// ètení dat ze souboru
IDF_MEMORY_SAVE,			"zápis dat do súboru",																				// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identifikátor okenného prvku",																		// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"volacia konvencia C",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"vytvorenie záloiek",																				// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"konfigurácia",																						// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"konfiguraènı súbor",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"sekcia parametrov",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"meno parametru",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"èítanie/zápis textového parametru",																// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"èítanie/zápis celoèíselného parametru",															// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"skupina klíèov (1=CURRENT_USER, 2=LOCAL_MACHINE)",													// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"meno klíèa",																						// plnı mázev klíèe registrù
IDF_REG_VALUE,				"meno polôky",																						// název datové poloky
IDF_REG_STRING,				"èítanie/zápis textovej polôky",																	// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"èítanie/zápis celoèíselnej polôky",																// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"vytvorenie 3D objektu z pameovıch blokov",														// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"poèet vrcholov",																					// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"vrcholy",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normály (0=auto)",																					// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"mapovanie textur (0=nieje)",																		// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"barvy (0=nieje)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"poèet plošiek",																					// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"plošky",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"textura zo súboru",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"pameovı blok z 3D objektu",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"potomok (-1=prvı, -2=rodiè)",																		// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP pakety",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"vysielacia IP adresa",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"vysielaci port (-1=zatvorenie vysielania)",														// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"ve¾kos prijímacieho bufferu",																		// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"prijatá/prijímacia IP adresa",																		// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"prijatı/prijímaci port (-1=zatvorenie príjmu)",													// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binárny paket",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"textovı paket",																					// pøíjem/odeslání textového UDP paketu
