// Hebrejsky (Hebrew)
// 1255
// [0] Rùzné texty
IDN_MAINFRAME,				"Peter_Heb",																							// jméno aplikace Petr v nadpisu hlavního okna
IDN_NADPISOBJ,				"Thay ğôÒi tôÒng quaìt vaÌ chıìc nãng",																// titulek okna globálních promìnnıch
IDN_NADPISLOC,				"Thay ğôÒi bôò phâòn vaÌ chıìc nãng",																// titulek okna lokálních promìnnıch
IDN_NADPISSTR,				"Nguyên tôì cõ baÒn, thuÌng raìc",																	// titulek okna stavebních prvkù a koše
IDN_NADPISCLS,				"Library of Variables and Functions",																// titulek okna knihovny
IDN_ZAKLADNI_OBJEKTY,		"basic variables and functions",																	// popis prvku "Skupina" se základními prvky u nového programu
IDN_NEWFILE_NAME,			"New Program",																						// implicitní název nového programu
IDN_NEWDIR_NAME,			"New Folder",																						// implicitní název nové sloky
IDN_TEXTVZOR,				"[examples]",																						// název vzorového adresáøe v knihovnì
IDN_STAT_REF,				"Used",																								// zobrazuje poèet pouití prvku
IDT_RADEK,					"row",																								// zkratka pro "øádek", pouívá se pøi editaci textu
IDT_POZICE,					"column",																							// zkratka pro "pozice", pouívá se pøi editaci textu
IDN_ZAPNUTO,				"switched on",																						// text editoru hodnoty pøepínaèe
IDN_DATUM,					"date",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_CAS,					"time",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VELIKOST,				"size",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_VOLNE,					"free",																								// text pro informaèní øádek o souboru v oknì vıbìru souborù
IDN_KB,						"KB",																								// oznaèení "Kilobajty"
IDN_MB,						"MB",																								// oznaèení "Megabajty"
IDN_OPAKOVANI,				"repeat",																							// text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_OPAKOVANE,				"repeated",																							// alternativní text indikující opakování pøehrávání zvuku (ve jménu souboru WAV) - malımi písmeny!
IDN_DEMO,					"DEMO",																								// oznaèení DEMO verze
IDN_PROFI,					"Professional",																						// oznaèení verze Professional
IDN_LITE,					"Lite",																								// oznaèení LITE verze
// [1] Menu "Soubor" vıbìru programù - doplòuje menu "Soubor" editoru
IDN_FILE0,					"&File",																							// volba k vyvolání menu "Soubor"
IDN_START0,					"S&tart\tF5",																						// volba pro spuštìní programu
IDN_START,					"Starts the program.\nStart",																		// [2] nápovìda k volbì pro spuštìní programu
IDN_OPEN0,					"&Open\tCtrl+O",																					// volba k otevøení programu k editaci
IDN_OPEN,					"Opens the program for editing.\nOpen",																// [2] nápovìda k volbì pro otevøení programu k editaci
IDN_NEW0,					"&New...\tCtrl+N",																					// volba pro zaloení nového programu
IDN_NEW,					"Creates a new program.\nNew",																		// [2] nápovìda k volbì pro zaloení nového programu
IDN_RENAME0,				"&Rename...\tAlt+Enter",																			// volba ke zmìnì jména programu nebo sloky
IDN_RENAME,					"Renames the program/folder (cannot rename example programs and folders).\nRename",					// [2] nápovìda k volbì pro zmìnu jména programu nebo sloky
IDN_NEWCOPY0,				"&Copy...\tCtrl+C",																					// volba k vytvoøení kopie programu
IDN_NEWCOPY,				"Copies the selected program into other name.\nCopy",												// [2] nápovìda k volbì pro vytvoøení kopie programu
IDN_PATH0,					"New &Folder...\tCtrl+P",																			// volba k vytvoøení nové sloky
IDN_PATH,					"Creates a new folder for programs.\nNew Folder",													// [2] nápovìda k volbì pro vytvoøení nové sloky
IDN_DELETE0,				"&Delete...\tDelete",																				// volba ke zrušení programu nebo sloky
IDN_DELETE,					"Deletes the program or folder (cannot delete example programs and folders).\nDelete",				// [2] nápovìda k volbì pro zrušení programu nebo sloky
IDN_SHORTNAME0,				"Short Na&mes",																						// !!! volba k zapnutí/vypnutí krátkıch jmen souborù
IDN_SHORTNAME,				"A programs/library files will create with names shorted to 8 characters.\nShort Names",			// [2] !!! nápovìda k volbì pro zapnutí/vypnutí krátkıch jmen souborù
IDN_EXIT0,					"E&xit\tAlt+F4",																					// volba k ukonèení aplikace Petr
IDN_EXIT,					"Quits the Peter application.\nExit",																// [2] nápovìda k volbì pro ukonèení aplikace Petr
// [1] Podmenu "Písmo" je souèástí menu "Soubor"
IDN_SETUP0,					"Font S&etup",																						// volba k vyvolání podmenu "Písmo"
IDN_SETUP10,				"Font of Program &Select...",																		// volba k nastavení písma ve vıbìru programu
IDN_SETUP1,					"Sets font in the window of program select.\nFont of Program Select",								// [2] nápovìda k volbì pro nastavení písma ve vıbìru programu
IDN_SETUP20,				"Font of Program &Editor...",																		// volba k nastavení písma v editoru programu
IDN_SETUP2,					"Sets font in the windows of program editor.\nFont of Program Editor",								// [2] nápovìda k volbì pro nastavení písma v editoru programu
IDN_SETUP30,				"Font of &Text Editor...",																			// volba k nastavení písma v editoru textu
IDN_SETUP3,					"Sets font in the text editor window.\nFont of Text Editor",										// [2] nápovìda k volbì pro nastavení písma v editoru textu
IDN_SETUP40,				"Font of &Menu...",																					// volba k nastavení písma nabídky (menu)
IDN_SETUP4,					"Sets font of menu.\nFont of Menu",																	// [2] nápovìda k volbì pro nastavení písma nabídky (menu)
IDN_SETUP50,				"Font of Status &Bar...",																			// volba k nastavení písma stavové lišty
IDN_SETUP5,					"Sets font of status bar.\nFont of Status Bar",														// [2] nápovìda k volbì pro nastavení písma stavové lišty
// [1] Podmenu "Jazyk" - je souèástí menu "Soubor"
IDN_JAZYK0,					"&Language",																						// volba k vyvolání podmenu "Jazyk"
IDN_JAZYKAUT0,				"&Automatic",																						// volba pro automatickı vıbìr jazyku
IDN_JAZYKAUT,				"Selects language automatically according to the system setting.\nAutomatic",						// [2] nápovìda k volbì pro automatickı vıbìr jazyku
IDN_JAZYKPRE0,				"&Previous\tCtrl+F9",																				// volba k navrácení k pøedcházejícímu jazyku
IDN_JAZYKPRE,				"Switches between two last used languages.\nPrevious",												// [2] nápovìda k volbì pro navrácení k pøedcházejícímu jazyku
IDN_JAZYKBUL0,				"Bulgarian (Bulgarija)",																			// volba pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKBUL,				"Switches Peter application to the Bulgarian language.\nBulgarian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na bulharskı jazyk
IDN_JAZYKCZ0,				"&Czech (Cesky)",																					// volba pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKCZ,				"Switches Peter application to the Czech language.\nCzech",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na èeskı jazyk
IDN_JAZYKDAN0,				"&Danish (Danmark)",																				// volba pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKDAN,				"Switches Peter application to the Danish language.\nDanish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na dánskı jazyk
IDN_JAZYKGER0,				"&German (Deutsch)",																				// volba pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKGER,				"Switches Peter application to the German language.\nGerman",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na nìmeckı jazyk
IDN_JAZYKREC0,				"Greek (Hellás)",																					// volba pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKREC,				"Switches Peter application to the Greek language.\nGreek",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na øeckı jazyk
IDN_JAZYKENG0,				"&English",																							// volba pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKENG,				"Switches Peter application to the English language.\nEnglish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na anglickı jazyk
IDN_JAZYKSPA0,				"Spa&nish (España)",																				// volba pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKSPA,				"Switches Peter application to the Spanish language.\nSpanish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na španìlskı jazyk
IDN_JAZYKFIN0,				"Finnish (Finland)",																				// volba pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFIN,				"Switches Peter application to the Finnish language.\nFinnish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na finskı jazyk
IDN_JAZYKFRA0,				"&French (France)",																					// volba pro pøepnutí aplikace Petr na francouzskı jazyk
IDN_JAZYKFRA,				"Switches Peter application to the French language.\nFrench",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na fracouzskı jazyk
IDN_JAZYKMAD0,				"&Hungarian (Magyar)",																				// volba pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKMAD,				"Switches Peter application to the Hungarian language.\nHungarian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na maïarskı jazyk
IDN_JAZYKISL0,				"Icelandic (Island)",																				// volba pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKISL,				"Switches Peter application to the Icelandic language.\nIcelandic",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na islandskı jazyk
IDN_JAZYKITA0,				"Italian (Italy)",																					// volba pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKITA,				"Switches Peter application to the Italian language.\nItalian",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na italskı jazyk
IDN_JAZYKHOL0,				"Dutch (Nederland)",																				// volba pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKHOL,				"Switches Peter application to the Dutch language.\nDutch",											// [2] nápovìda k volbì pro pøepnutí aplikace Petr na holandskı jazyk
IDN_JAZYKNOR0,				"Norwegian (Norge)",																				// volba pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKNOR,				"Switches Peter application to the Norwegian language.\nNorwegian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na norskı jazyk
IDN_JAZYKPOL0,				"Polish (Po polsku)",																				// volba pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOL,				"Switches Peter application to the Polish language.\nPolish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na polskı jazyk
IDN_JAZYKPOR0,				"Portuguese (Portugal)",																			// volba pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKPOR,				"Switches Peter application to the Portuguese language.\nPortuguese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na portugalskı jazyk
IDN_JAZYKRUM0,				"Romanian (România)",																				// volba pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUM,				"Switches Peter application to the Romanian language.\nRomanian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na rumunskı jazyk
IDN_JAZYKRUS0,				"&Russian (Po-rusky)",																				// volba pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKRUS,				"Switches Peter application to the Russian language.\nRussian",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na ruskı jazyk
IDN_JAZYKSRB0,				"Serbo-Croat (Serbo-Croat)",																		// volba pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSRB,				"Switches Peter application to the Serbo-Croat language.\nSerbo-Croat",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na srbochorvátskı jazyk
IDN_JAZYKSLO0,				"&Slovak (Po slovensky)",																			// volba pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKSLO,				"Switches Peter application to the Slovak language.\nSlovak",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na slovenskı jazyk
IDN_JAZYKALB0,				"Albanian (Shqipërisë)",																			// volba pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKALB,				"Switches Peter application to the Albanian language.\nAlbanian",									// [2] nápovìda k volbì pro pøepnutí aplikace Petr na albánskı jazyk
IDN_JAZYKSWE0,				"Swedish (Swerige)",																				// volba pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKSWE,				"Switches Peter application to the Swedish language.\nSwedish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na švédskı jazyk
IDN_JAZYKTUR0,				"Turkish (Türkiye)",																				// volba pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKTUR,				"Switches Peter application to the Turkish language.\nTurkish",										// [2] nápovìda k volbì pro pøepnutí aplikace Petr na tureckı jazyk
IDN_JAZYKVIE0,				"Vietnamese (Vietnamese)",																			// volba pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKVIE,				"Switches Peter application to the Vietnamese language.\nVietnamese",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na vietnamskı jazyk
IDN_JAZYKARA0,				"Arabic (Arabic)",																			// volba pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKARA,				"Switches Peter application to the Arabic language.\nArabic",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na arabskı jazyk
IDN_JAZYKHEB0,				"Hebrew (Hebrew)",																			// volba pro pøepnutí aplikace Petr na hebrejskı jazyk
IDN_JAZYKHEB,				"Switches Peter application to the Hebrew language.\nHebrew",								// [2] nápovìda k volbì pro pøepnutí aplikace Petr na hebrejskı jazyk
// [1] Menu "Pomoc" (Nápovìda)
IDN_HLP0,					"&Help",																							// volba k vyvolání menu "Pomoc" (Nápovìda)
IDN_HELP0,					"&Help\tF1",																						// volba k vyvolání kontextové nápovìdy
IDN_HELP,					"Displays help for the selected element.\nHelp",													// [2] nápovìda k volbì pro vyvolání kontextové nápovìdy
IDN_HELPT0,					"Help &Contents",																					// volba k vyvolání základní nápovìdy (témata)
IDN_HELPT,					"Displays the help contents.\nHelp Contents",														// [2] nápovìda k volbì pro vyvolání základní nápovìdy (témata)
IDN_HELPF0,					"&Search in Help",																					// volba k vyvolání rejstøíku a hledání v nápovìdì
IDN_HELPF,					"Searches in the help.\nSearch in Help",															// [2] nápovìda k volbì pro vyvolání rejstøíku a hledání v nápovìdì
IDN_ABOUT0,					"&About Peter Application",																			// volba k vyvolání informací o aplikaci Petr
IDN_ABOUT,					"Displays information about the Peter application, version number and copyright.\nAbout Peter Application",	// [2] nápovìda k volbì pro vyvolání informací o aplikaci Petr
// [1] Menu "Soubor" editoru - doplòuje menu "Soubor" vıbìru programù
IDN_CLOSE0,					"&Close\tCtrl+O",																					// volba k uzavøení editovaného programu, návrat do vıbìru programu
IDN_CLOSE,					"Closes the editing program and opens another one.\nClose",											// [2] nápovìda k volbì pro uzavøení editovaného programu a návratu do vıbìru programu
IDN_SAVE0,					"&Save\tCtrl+S",																					// volba k uloení programu pøi editaci
IDN_SAVE,					"Saves the changes performed in the program.\nSave",												// [2] nápovìda k volbì pro uloení programu pøi editaci
IDN_SAVEN0,					"Save as &Nonexecutable\tCtrl+Alt+S",																// volba k nespustitelnému uloení programu (bez spustitelného kódu)
IDN_SAVEN,					"Saves the program as nonexecutable (less size).\nSave as Nonexecutable",							// [2] nápovìda k volbì pro nespustitelné uloení programu (bez spustitelného kódu)
IDN_SAVE_AS0,				"Save &As...\tCtrl+Shift+S",																		// volba k uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_AS,				"Saves the program into the file with a different name or to the different disk.\nSave As",			// [2] nápovìda k volbì pro uloení programu do jiného souboru nebo na jinı disk
IDN_SAVE_REL0,				"&Distribution...",																					// volba k uloení programu do distribuèní needitovatelné verze
IDN_SAVE_REL,				"Saves the distribution, not editable program version (only with the Professional license).\nDistribution",	// [2] nápovìda k volbì pro uloení programu do distribuèní needitovatelné verze
IDN_EXPORT0,				"Ex&port...",																						// volba k exportování programu
IDN_EXPORT,					"Exports the program into text form.\nExport",														// [2] nápovìda k volbì pro exportování programu
IDN_IMPORT0,				"&Import...",																						// volba k importování programu
IDN_IMPORT,					"Imports a program from text form.\nImport",														// [2] nápovìda k volbì pro importování programu
// [1] Menu "Úpravy" (Editace)
IDN_EDIT0,					"&Edit",																							// volba k vyvolání menu "Úpravy" (Editace)
IDN_UNDO0,					"&Undo\tCtrl+Z",																					// volba k navrácení provedenıch zmìn UNDO
IDN_UNDO,					"Undoes the last performed action.\nUndo",															// [2] nápovìda k volbì pro navrácení provedenıch zmìn UNDO
IDN_REDO0,					"&Redo\tCtrl+Y",																					// volba k odvolání navrácenıch zmìn REDO
IDN_REDO,					"Redoes the previously undone action.\nRedo",														// [2] nápovìda k volbì pro odvolání navrácenıch zmìn REDO
IDN_CUT0,					"Cu&t\tCtrl+X",																						// volba k vyjmutí oznaèeného bloku do schránky CUT
IDN_CUT,					"Cuts the selection and moves it to the clipboard.\nCut",											// [2] nápovìda k volbì pro vyjmutí oznaèeného bloku do schránky CUT
IDN_COPY0,					"&Copy\tCtrl+C",																					// volba ke kopii oznaèeného bloku do schránky COPY
IDN_COPY,					"Copies the selection to the clipboard.\nCopy",														// [2] nápovìda k volbì pro kopii oznaèeného bloku do schránky COPY
IDN_PASTE0,					"&Paste\tCtrl+V",																					// volba k vloení bloku ze schránky PASTE
IDN_PASTE,					"Inserts the clipboard contents at the actual position.\nPaste",									// [2] nápovìda k volbì pro vloení bloku ze schránky PASTE
IDN_CLEAR0,					"&Delete\tDelete",																					// volba ke zrušení oznaèeného bloku CLEAR
IDN_CLEAR,					"Deletes the selection.\nDelete",																	// [2] nápovìda k volbì pro zrušení oznaèeného bloku CLEAR
IDN_ALL0,					"Select &All\tCtrl+A",																				// volba k oznaèení všeho jako blok SELECT ALL
IDN_ALL,					"Selects all.\nSelect All",																			// [2] nápovìda k volbì pro oznaèení všeho jako blok SELECT ALL
IDN_DITHER0,				"D&ithering",																						// volba k zapnutí/vypnutí ditheringu (rastrované zobrazení barev)
IDN_DITHER,					"Uses dithering with the importing and decreasing of pictures.\nDithering",							// [2] nápovìda k volbì pro zapnutí/vypnutí ditheringu (rastrovaného zobrazení barev)
// [1] Menu "Zobrazení"
IDN_ZOBRAZ0,				"&View",																							// volba k vyvolání menu "Zobrazení"
IDN_IN0,					"Zoom &In\tCtrl+[+]",																				// volba ke zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_IN,						"Increases the scale of display.\nZoom In",															// [2] nápovìda k volbì pro zvìtšení mìøítka zobrazení (ZOOM IN)
IDN_OUT0,					"Zoom &Out\tCtrl+[-]",																				// volba ke zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_OUT,					"Decreases the scale of display.\nZoom Out",														// [2] nápovìda k volbì pro zmenšení mìøítka zobrazení (ZOOM OUT)
IDN_HIST_PREV0,				"&Previous Edit\tCtrl+Up",																			// volba k navrácení zpìt v historii editací
IDN_HIST_PREV,				"Returns to the previously edited element.\nPrevious Edit",											// [2] nápovìda k volbì pro navrácení zpìt v historii editací
IDN_HIST_NEXT0,				"&Next Edit\tCtrl+Down",																			// volba k posunu vpøed v historii editací
IDN_HIST_NEXT,				"Returns to the next edited element.\nNext Edit",													// [2] nápovìda k volbì pro posun vpøed v historii editací
IDN_FIND0,					"&Find Text...\tCtrl+F",																			// volba k vyvolání dialogu k hledání textu
IDN_FIND,					"Finds the entered text.\nFind Text",																// [2] nápovìda k volbì pro vyvolání dialogu k hledání textu
IDN_FIND_PREV0,				"P&revious Text\tShift+F3",																			// volba k opakování hledání textu zpìt
IDN_FIND_PREV,				"Finds a previous occurrence of the text.\nPrevious Text",											// [2] nápovìda k volbì pro opakování hledání textu zpìt
IDN_FIND_NEXT0,				"N&ext Text\tF3",																					// volba k opakování hledání textu vpøed
IDN_FIND_NEXT,				"Finds a next occurrence of the text.\nNext Text",													// [2] nápovìda k volbì pro hledání textu vpøed
// [1] Menu "Program" - editace stromu programu
IDN_PROGRAM0,				"&Program",																							// volba k vyvolání menu "Program"
IDN_LOCK0,					"&Lock",																							// volba k uzamknutí/odemknutí vybraného prvku
IDN_LOCK,					"Locks the element against modification.\nLock",													// [2] nápovìda k volbì pro uzamknutí/odemknutí vybraného prvku
IDN_OFF0,					"&Turn Off",																						// volba k vypnutí/zapnutí funkènosti vybraného prvku
IDN_OFF,					"Turnes off the function of element.\nTurn Off",													// [2] nápovìda k volbì pro vypnutí/zapnutí funkènosti vybraného prvku
IDN_EDIT_NAME0,				"&Description\tAlt+Enter",																			// volba k vyvolání editace textu prvku
IDN_EDIT_NAME,				"Edits description of the element.\nDescription",													// [2] nápovìda k volbì pro vyvolání editace textu prvku
IDN_DEF_NAME0,				"Default D&escription",																				// volba k zapnutí/vypnutí implicitního textu prvku
IDN_DEF_NAME,				"Uses default description of the element.\nDefault Description",									// [2] nápovìda k volbì pro zapnutí/vypnutí implicitního textu prvku
IDN_EDIT_ICON0,				"&Icon",																							// volba k vyvolání editace ikony prvku
IDN_EDIT_ICON,				"Edits icon of the element.\nIcon",																	// [2] nápovìda k volbì pro vyvolání editace ikony prvku
IDN_DEF_ICON0,				"Default I&con",																					// volba k zapnutí/vypnutí implicitní ikony prvku
IDN_DEF_ICON,				"Uses default icon of the element.\nDefault Icon",													// [2] nápovìda k volbì pro zapnutí/vypnutí implicitní ikony prvku
IDN_REF_DEF0,				"Decl&aration",																						// volba k nalezení deklarace prvku
IDN_REF_DEF,				"Finds declaration of the element.\nDeclaration",													// [2] nápovìda k volbì pro nalezení deklarace prvku
IDN_REF_PREV0,				"&Previous Use",																					// volba k nalezení pøedešlého pouití prvku
IDN_REF_PREV,				"Finds previous use of the element.\nPrevious Use",													// [2] nápovìda k volbì pro nalezení pøedešlého pouití prvku
IDN_REF_NEXT0,				"&Next Use",																						// volba k nalezení dalšího pouití prvku
IDN_REF_NEXT,				"Finds next use of the element.\nNext Use",															// [2] nápovìda k volbì pro nalezení dalšího pouití prvku
// [1] Menu "Obrázek" - editace obrázkù a ikon
IDN_OBRAZEK0,				"&Picture",																							// volba k vyvolání menu "Obrázek"
IDN_DIMEN0,					"&Dimensions...",																					// volba k nastavení rozmìrù obrázku nebo plochy
IDN_DIMEN,					"Sets general dimensions.\nDimensions",																// [2] nápovìda k volbì pro nastavení rozmìrù obrázku nebo plochy
IDN_RASTR0,					"&Raster",																							// volba k vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_RASTR,					"Turns on/off the orientation raster display.\nRaster",												// [2] nápovìda k volbì pro vypnutí/zapnutí rastru v obrázku nebo ploše
IDN_EDITBLOK0,				"&Edit...",																							// volba k vyvolání okna konverzí obrázku
IDN_EDITBLOK,				"Edits the picture or its part (resize, rotation, color exchange).\nEdit",							// [2] nápovìda k volbì pro vyvolání okna konverzí obrázku
IDN_OTISK0,					"&Block Stamp",																						// volba k otisku bloku do obrázku
IDN_OTISK,					"Stamps the block to the picture.\nBlock Stamp",													// [2] nápovìda k volbì pro otisk bloku do obrázku
IDN_YFLIP0,					"&Horizontal",																						// volba k horizontálnímu pøevrácení obrázku
IDN_YFLIP,					"Flips the picture or its part horizontally.\nHorizontal",											// [2] nápovìda k volbì pro horizontální pøevrácení obrázku
IDN_XFLIP0,					"&Vertical",																						// volba k vertikálnímu pøevrácení obrázku
IDN_XFLIP,					"Flips the picture or its part vertically.\nVertical",												// [2] nápovìda k volbì pro vertikální pøevrácení obrázku
IDN_LROT0,					"&Left",																							// volba k rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_LROT,					"Rotate the picture to the left (by 90 degrees counter-clockwise).\nLeft",							// [2] nápovìda k volbì pro rotaci obrázku vlevo (proti smìru hodinovıch ruèièek)
IDN_RROT0,					"Ri&ght",																							// volba k rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_RROT,					"Rotate the picture to the right (by 90 degrees clockwise).\nRight",								// [2] nápovìda k volbì pro rotaci obrázku vpravo (ve smìru hodinovıch ruèièek)
IDN_MUL20,					"D&ouble",																							// volba ke zvìtšení obrázku na dvojnásobek
IDN_MUL2,					"Increases size of the picture or its part twice.\nDouble",											// [2] nápovìda k volbì pro zvìtšení obrázku na dvojnásobek
IDN_DIV20,					"H&alf",																							// volba ke zmenšení obrázku na polovinu
IDN_DIV2,					"Decreases size of the picture or its part by a half.\nHalf",										// [2] nápovìda k volbì pro zmenšení obrázku na polovinu
IDN_MULDIV0,				"Res&ize...",																						// volba k vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_MULDIV,					"Resizes the picture or its part optionally.\nResize",												// [2] nápovìda k volbì pro vyvolání okna pro volitelnou zmìnu velikosti obrázku
IDN_XCOL0,					"E&xchange",																						// volba k zámìnì barev pro levé a pravé tlaèítko myši v obrázku
IDN_XCOL,					"Exchanges the left and right mouse button colors in the picture or in its part.\nExchange",		// [2] nápovìda k volbì pro zámìnu barev pro levé a pravé tlaèítko myši v obrázku
IDN_SCOL0,					"S&ubstitution",																					// volba k náhradì barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
IDN_SCOL,					"Substitutes the right mouse button color by the left mouse button color in the picture or in its part.\nSubstitution",	// [2] nápovìda k volbì pro náhradu barvy pro pravé tlaèítko barvou pro levé tlaèítko myši v obrázku
// [1] Menu "Nástroje" - editace obrázkù a ikon
IDN_NASTROJE0,				"&Tools",																							// volba k vyvolání menu "Nástroje"
IDN_PEN0,					"&Pen",																								// volba k zapnutí kreslení pomocí pera
IDN_PEN,					"Draws with the pen.\nPen",																			// [2] nápovìda k volbì pro zapnutí kreslení pomocí pera
IDN_LINE0,					"&Line",																							// volba k zapnutí kreslení èáry
IDN_LINE,					"Draws a line.\nLine",																				// [2] nápovìda k volbì pro zapnutí kreslení èáry
IDN_BOX0,					"&Box",																								// volba k zapnutí kreslení obdélníku bez vıplnì
IDN_BOX,					"Draws a box.\nBox",																				// [2] nápovìda k volbì pro zapnutí kreslení obdélníku bez vıplnì
IDN_FILLBOX0,				"Filled B&ox",																						// volba k zapnutí kreslení obdélníku s vıplní
IDN_FILLBOX,				"Draws a filled box.\nFilled Box",																	// [2] nápovìda k volbì pro zapnutí kreslení obdélníku s vıplní
IDN_CIRCLE0,				"&Circle",																							// volba k zapnutí kreslení krunice bez vıplnì
IDN_CIRCLE,					"Draws a circle.\nCircle",																			// [2] nápovìda k volbì pro zapnutí kreslení krunice bez vıplnì
IDN_FILLCIRCLE0,			"Filled Ci&rcle",																					// volba k zapnutí kreslení kruhu s vıplní
IDN_FILLCIRCLE,				"Draws a filled circle.\nFilled Circle",															// [2] nápovìda k volbì pro zapnutí kreslení kruhu s vıplní
IDN_ELLIPSE0,				"&Ellipse",																							// volba k zapnutí kreslení elipsy bez vıplnì
IDN_ELLIPSE,				"Draws an ellipse.\nEllipse",																		// [2] nápovìda k zapnutí kreslení elipsy bez vıplnì
IDN_FILLELLIPSE0,			"Fille&d Ellipse",																					// volba k zapnutí kreslení elipsy s vıplní
IDN_FILLELLIPSE,			"Draws a filled ellipse.\nFilled Ellipse",															// [2] nápovìda k volbì pro zapnutí kreslení elipsy s vıplní
IDN_SPHERE0,				"Sp&here",																							// volba k zapnutí kreslení koule
IDN_SPHERE,					"Draws a sphere.\nSphere",																			// [2] nápovìda k volbì pro zapnutí kreslení koule
IDN_SELECT0,				"&Selection",																						// volba k zapnutí reimu práce s blokem
IDN_SELECT,					"Selects the determined part.\nSelection",															// [2] nápovìda k volbì pro zapnutí reimu práce s blokem
IDN_SPRAY0,					"Spr&ay",																							// volba k zapnutí kreslení pomocí spreje
IDN_SPRAY,					"Draws with the spray.\nSpray",																		// [2] nápovìda k volbì pro zapnutí kreslení pomocí spreje
IDN_PIPE0,					"P&ipette",																							// volba k nabrání barvy z obrázku
IDN_PIPE,					"Sets the color beneath the cursor as selected.\nPipette",											// [2] nápovìda k volbì pro nabrání barvy z obrázku
IDN_FILL0,					"&Filler",																							// volba k zapnutí reimu vyplòování plochy
IDN_FILL,					"Fills the surface by a color.\nFiller",															// [2] nápovìda k volbì pro zapnutí reimu vyplòování plochy
IDN_TEXT0,					"&Text",																							// volba k vyvolání psaní textu do obrázku
IDN_TEXT,					"Writes the text.\nText",																			// [2] nápovìda k volbì pro vyvolání psaní textu do obrázku
// [1] Menu "Tlouška" - editace obrázkù a ikon
IDN_TLOUSTKA0,				"Thi&ckness",																						// volba k vyvolání menu "Tlouška"
IDN_WIDTH10,				"Thickness &1 Pixel",																				// volba k nastavení tloušky pera 1 bod
IDN_WIDTH1,					"Draws the lines with a thickness of 1 pixel.\nThickness 1 Pixel",									// [2] nápovìda k volbì pro nastavení tloušky pera 1 bod
IDN_WIDTH20,				"Thickness &2 Pixels",																				// volba k nastavení tloušky pera 2 body
IDN_WIDTH2,					"Draws the lines with a thickness of 2 pixels.\nThickness 2 Pixels",								// [2] nápovìda k volbì pro nastavení tloušky pera 2 body
IDN_WIDTH30,				"Thickness &5 Pixels",																				// volba k nastavení tloušky pera 5 bodù
IDN_WIDTH3,					"Draws the lines with a thickness of 5 pixels.\nThickness 5 Pixels",								// [2] nápovìda k volbì pro nastavení tloušky pera 5 bodù
IDN_WIDTH40,				"Thickness &9 Pixels",																				// volba k nastavení tloušky pera 9 bodù
IDN_WIDTH4,					"Draws the lines with a thickness of 9 pixels.\nThickness 9 Pixels",								// [2] nápovìda k volbì pro nastavení tloušky pera 9 bodù
IDN_WIDTH50,				"Thickness 21 &Pixels",																				// volba k nastavení tloušky pera 21 bodù
IDN_WIDTH5,					"Draws the lines with a thickness of 21 pixels.\nThickness 21 Pixels",								// [2] nápovìda k volbì pro nastavení tloušky pera 21 bodù
// [1] Menu "Plocha" - editace plochy
IDN_PLOCHA0,				"&Sheet",																							// volba k vyvolání menu "Plocha"
IDN_EDITMAP0,				"&Editing",																							// volba k zapnutí/vypnutí módu editace políèek plochy
IDN_EDITMAP,				"Turns on/off the editing mode of the sheet items.\nEditing",										// [2] nápovìda k volbì pro zapnutí/vypnutí módu editace políèek plochy
IDN_FILLMAP0,				"&Filling",																							// volba k zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_FILLMAP,				"Turns on/off the mode of filling the sheet with the item.\nFilling",								// [2] nápovìda k volbì pro zapnutí/vypnutí módu vyplòování plochy políèkem
IDN_MAP0,					"&Items",																							// volba k pøepnutí plochy na editaci pøedmìtù
IDN_MAP,					"Edits items on the sheet.\nItems",																	// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøedmìtù
IDN_SWC10,					"Flag &1",																							// volba k pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC1,					"Edits the flag 1.\nFlag 1",																		// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 1
IDN_SWC20,					"Flag &2",																							// volba k pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC2,					"Edits the flag 2.\nFlag 2",																		// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 2
IDN_SWC30,					"Flag &3",																							// volba k pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC3,					"Edits the flag 3.\nFlag 3",																		// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 3
IDN_SWC40,					"Flag &4",																							// volba k pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC4,					"Edits the flag 4.\nFlag 4",																		// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 4
IDN_SWC50,					"Flag &5",																							// volba k pøepnutí plochy na editaci pøepínaèe 5
IDN_SWC5,					"Edits the flag 5.\nFlag 5",																		// [2] nápovìda k volbì pro pøepnutí plochy na editaci pøepínaèe 5
IDN_SWCN10,					"&Numeric Value 1",																					// volba k pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN1,					"Edits the numeric value 1 (range 0 to 1023).\nNumeric Value 1",									// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 1
IDN_SWCN20,					"N&umeric Value 2",																					// volba k pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN2,					"Edits the numeric value 2 (range 0 to 1023).\nNumeric Value 2",									// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 2
IDN_SWCN30,					"Nu&meric Value 3",																					// volba k pøepnutí plochy na editaci èíselné hodnoty 3
IDN_SWCN3,					"Edits the numeric value 3 (range 0 to 127).\nNumeric Value 3",										// [2] nápovìda k volbì pro pøepnutí plochy na editaci èíselné hodnoty 3
// [1] Menu "Sprajt" - editace sprajtu
IDN_SPRAJT0,				"&Sprite",																							// volba k vyvolání menu "Sprajt"
IDN_SPRITEPAR0,				"&Properties",																						// volba k vyvolání okna pro nastavení vlastností sprajtu
IDN_SPRITEPAR,				"Sets properties of the sprite (number of phases, directions, ...).\nProperties",					// [2] nápovìda k volbì pro vyvolání okna k nastavení vlastností sprajtu
IDN_TEST0,					"&Test",																							// volba k vyvolání okna pro test sprajtu
IDN_TEST,					"Starts test mode of the sprite.\nTest",															// [2] nápovìda k volbì pro vyvolání okna k testu sprajtu
// [1] Menu "Zvuk" - editace zvuku, doplòuje menu "Hudba"
IDN_SOUND0,					"&Sound",																							// volba k vyvolání menu "Zvuk"
IDN_PLAY0,					"&Play",																							// volba ke spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PLAY,					"Starts playing.\nPlay",																			// [2] nápovìda k volbì pro spuštìní pøehrávání zvuku nebo hudby (PLAY)
IDN_PAUSE0,					"Pa&use",																							// volba k pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_PAUSE,					"Pauses playing.\nPause",																			// [2] nápovìda k volbì pro pozastavení pøehrávání zvuku nebo hudby (PAUSE)
IDN_STOP0,					"&Stop",																							// volba k zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_STOP,					"Stops playing.\nStop",																				// [2] nápovìda k volbì pro zastavení pøehrávání zvuku nebo hudby (STOP)
IDN_LOOP0,					"&Loop",																							// volba k zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_LOOP,					"Turns on/off the repetition of playing.\nLoop",													// [2] nápovìda k volbì pro zapnutí/vypnutí opakovaného pøehrávání zvuku nebo hudby (LOOP)
IDN_RECORD0,				"&Record",																							// volba ke spuštìní nahrávání zvuku (RECORD)
IDN_RECORD,					"Starts recording.\nRecord",																		// [2] nápovìda k volbì pro spuštìní nahrávání zvuku (RECORD)
// [1] Menu "Hudba" - editace hudby, doplòuje menu "Zvuk"
IDN_MUSIC0,					"&Music",																							// volba k vyvolání menu "Hudba"
IDN_REW0,					"&Rewind",																							// volba k posunu pøehrávání hudby o 10 sekund zpìt
IDN_REW,					"Moves playing by 10 seconds back.\nRewind",														// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund zpìt
IDN_FRW0,					"&Forward",																							// volba k posunu pøehrávání hudby o 10 sekund vpøed
IDN_FRW,					"Moves playing by 10 seconds forward.\nForward",													// [2] nápovìda k volbì pro posun pøehrávání hudby o 10 sekund vpøed
// [3] Dialog "O aplikaci Petr"
IDN_ABOUTBOX,				"About the Peter Application",																		// titulek okna "O aplikaci Petr" (ABOUT)
IDC_VERZE,					"Peter version",																					// text pøed oznaèením verze v oknì
IDC_COPYNAME,				"Copyright © 1999-2012 Miroslav Nemecek",															// copyright
IDC_FIRMA,					"Gemtree Software, s.r.o.",																			// název firmy
IDC_POBOX,					"Svazarm.1011, P.O.Box 136",																		// P.O. Box
IDC_PSC,					"756 61",																							// PSÈ
IDC_ADRMESTO,				"Roznov pod Radhostem",																				// Ronov pod Radhoštìm
IDC_REPUBLIKA,				"Czech Republic",																					// Èeská Republika
IDC_DEMOTEXT1,				"The demoversion cannot save nor execute the new",													// 1. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT2,				"or modified programs. Editing possibilities,",														// 2. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT3,				"help and saving into the library are fully functional.",											// 3. (ze 3) øádek informaèního textu v oknì DEMO verze
IDC_DEMOTEXT4,				"Actual product information can be obtained on the following internet address:",					// informaèní text v oknì DEMO verze "aktuální informace ... na adrese: www.gemtree.com"
IDC_DEMOTEXT5,				"The orders are possible to be sent to the following address:",										// informaèní text v oknì DEMO verze "objednávky ... na adresu:"
IDC_LICTITLE,				"LICENSE",																							// nadpis licenèních informací v oknì PLNÉ verze
IDC_LICTITLE0,				"unlimited",																						// poèet licencí neomezenı - v oknì PLNÉ verze
IDC_LICTITLE1,				"for 1 computer",																					// poèet licencí pro 1 poèítaè - v oknì PLNÉ verze
IDC_LICTITLE2,				"computers",																						// poèet licencí pro 2 a 4 poèítaèe - v oknì PLNÉ verze
IDC_LICTITLE3,				"computers",																						// poèet licencí pro 5 a více poèítaèù - v oknì PLNÉ verze
IDC_TELEFON,				"",																									// telefon
IDC_LITETEXT1,				"Lite version of the Peter provides limited programmatic equipment",								// 1. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT2,				"(unfunctional elements are marked by grayed icons). Lite version",									// 2. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT3,				"is FREEWARE and may be distributed and used freely for private",									// 3. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT4,				"purposes. For commercial uses and for schools the license payment",								// 4. (z 5) øádek informaèního textu v oknì LITE verze
IDC_LITETEXT5,				"is required by further specifications on the address www.gemtree.com.",							// 5. (z 5) øádek informaèního textu v oknì LITE verze
// [3] Dialog hledání textu
IDN_FIND_DIALOG,			"Find Text",																						// titulek okna hledání textu
IDN_FINDTEXT,				"Enter the text to be found:",																		// vızva k zadání textu k hledání
IDN_CANCEL0,				"Cancel",																							// text tlaèítka Storno (CANCEL) (vyuívá se i u jinıch dialogù a v interpreteru v dialogu zadání textu)
// [3] Dialog zadání rozmìru plochy
IDN_MAPDIMEN,				"Sheet Dimensions",																					// titulek okna zadání rozmìrù plochy
IDN_SIRKA,					"Width:",																							// nadpis pøed polem pro zadání šíøky (vyuívá se i u jinıch dialogù)
IDN_VYSKA,					"Height:",																							// nadpis pøed polem pro zadání vıšky (vyuívá se i u jinıch dialogù)
// [3] Dialog hlášení chyby pøi otevøení programu k editaci
IDN_OPENERR,				"Open Error",																						// titulek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR1,				"The program cannot be opened.",																	// 1. øádek okna hlášení chyby otevøení programu k editaci (následuje oddìlovací prázdnı øádek)
IDN_OPENERR2,				"It may be already opened by another",																// 2. øádek okna hlášení chyby otevøení programu k editaci
IDN_OPENERR3,				"application or the file access is denied.",														// 3. øádek okna hlášení chyby otevøení programu k editaci
// [3] Dialog hlášení chyby pøi ètení ze souboru
IDN_READERR,				"Read Error",																						// titulek okna hlášení chyby ètení souboru
IDN_READERR1,				"Program reading error.",																			// 1. øádek okna hlášení chyby ètení souboru (následuje oddìlovací prázdnı øádek)
IDN_READERR2,				"The program is damaged or it was created by the newer",											// 2. øádek okna hlášení chyby ètení souboru
IDN_READERR3,				"version of editor and therefore it might not work correctly.",										// 3. øádek okna hlášení chyby ètení souboru
// [3] Dialog hlášení chyby pro Lite verzi
IDN_LITEERR,				"Unsupported Commands",																				// titulek okna hlášení chyby Lite verze
IDN_LITEERR1,				"Warning: The program uses commands which are not",													// 1. øádek okna hlášení chyby Lite verze
IDN_LITEERR2,				"supported by the Lite version of the Peter application.",											// 2. øádek okna hlášení chyby Lite verze
IDN_LITEERR3,				"By saving the program it can become unfunctional.",												// 3. øádek okna hlášení chyby Lite verze
// [3] Dialog pro konverzi obrázku (otáèení, velikost, barvy)
IDN_PICBLOK,				"Modifications of the Picture or its Selected Part",												// titulek okna pro konverze obrázku
IDN_PREVRACENI,				"Flip",																								// nadpis rámeèku operací pøevrácení
IDN_YFLIP_TXT,				"Horizontal",																						// popis tlaèítka pro horizontální pøevrácení
IDN_XFLIP_TXT,				"Vertical",																							// popis tlaèítka pro vertikální pøevrácení
IDN_OTOCENI,				"Rotate",																							// nadpis rámeèku operací rotace
IDN_LROT_TXT,				"+1/2 pi (+90 degrees)",																			// popis tlaèítka pro otoèení o 90 stupòù vlevo
IDN_RROT_TXT,				"-1/2 pi (-90 degrees)",																			// popis tlaèítka pro otoèení o 90 stupòù vpravo
IDN_LROT67_TXT,				"+3/8 pi (+67.5 degrees)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vlevo
IDN_RROT67_TXT,				"-3/8 pi (-67.5 degrees)",																			// popis tlaèítka pro otoèení o 67.5 stupòù vpravo
IDN_LROT60_TXT,				"+1/3 pi (+60 degrees)",																			// popis tlaèítka pro otoèení o 60 stupòù vlevo
IDN_RROT60_TXT,				"-1/3 pi (-60 degrees)",																			// popis tlaèítka pro otoèení o 60 stupòù vpravo
IDN_LROT45_TXT,				"+1/4 pi (+45 degrees)",																			// popis tlaèítka pro otoèení o 45 stupòù vlevo
IDN_RROT45_TXT,				"-1/4 pi (-45 degrees)",																			// popis tlaèítka pro otoèení o 45 stupòù vpravo
IDN_LROT30_TXT,				"+1/6 pi (+30 degrees)",																			// popis tlaèítka pro otoèení o 30 stupòù vlevo
IDN_RROT30_TXT,				"-1/6 pi (-30 degrees)",																			// popis tlaèítka pro otoèení o 30 stupòù vpravo
IDN_LROT22_TXT,				"+1/8 pi (+22.5 degrees)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vlevo
IDN_RROT22_TXT,				"-1/8 pi (-22.5 degrees)",																			// popis tlaèítka pro otoèení o 22.5 stupòù vpravo
IDN_ZVETSENI,				"Resize",																							// nadpis rámeèku operací zmìny velikosti
IDN_MUL2_TXT,				"Double",																							// popis tlaèítka pro zdvojnásobení obrázku
IDN_DIV2_TXT,				"Half",																								// popis tlaèítka pro zmenšení obrázku na polovinu
IDN_MULDIV_TXT,				"Optional",																							// popis tlaèítka pro volitelnou velikost obrázku
IDN_BARVY,					"Colors",																							// nadpis rámeèku operací s barvami
IDN_XCOL_TXT,				"Left <-> Right Button",																			// popis tlaèítka pro zámìnu barev pro levé a pravé tlaèítko myši
IDN_SCOL_TXT,				"Left -> Right Button",																				// popis tlaèítka pro náhradu barvy pravého tlaèítka barvou levého tlaèítka
// [3] Dialog nastavení rozmìrù obrázku
IDN_PICDIMEN,				"Picture Dimensions",																				// titulek okna pro nastavení rozmìrù obrázku
IDN_ROZMERY,				"Dimensions Specified",																				// nadpis rámeèku volby jednotky
IDC_KROK,					"In &Steps",																						// [1] volba jednotky v krocích
IDC_BOD,					"In &Pixels",																						// [1] volba jednotky v bodech
// [3] Dialog volitelné zmìny velikosti obrázku
IDN_PICRESIZE,				"Resize Picture or its Part",																		// titulek okna pro volitelnou zmìnu velikosti obrázku
IDN_SOUCASNE_ROZMERY,		"Actual dimensions:",																				// nadpis pøed zobrazením souèasnıch rozmìrù
IDN_KROKU,					"steps",																							// text za údajem velikosti obrázku v krocích (pouívá i okno pro nastavení vlastností sprajtù)
IDN_BODU,					"pixels",																							// text za údajem velikosti obrázku v bodech
IDN_NOVE_ROZMERY,			"New Dimensions",																					// nadpis rámeèku pro nastavení novıch rozmìrù obrázku
IDN_SIRKA2,					"Width:",																							// nadpis nad sloupeèkem zobrazení šíøky obrázku
IDN_VYSKA2,					"Height:",																							// nadpis nad sloupeèkem zobrazení vıšky obrázku
IDN_PICRESIZE_STEP,			"In Steps",																							// [1] volba rozmìrù zadanıch v krocích
IDN_PICRESIZE_POINT,		"In Pixels",																						// [1] volba rozmìrù zadanıch v bodech
IDN_PICRESIZE_PROC,			"Percentage",																						// [1] volba rozmìrù zadanıch v procentech
IDN_PICRESIZE_PROP,			"Keep original ratio of the sides (ratio width/height)",											// [1] pøepínaè zachování pomìrù stran obrázku
IDN_PICRESIZE_INT,			"Refine edges (accurate, but slow convert)",														// [1] pøepínaè zjemnìní hran - interpolace
IDN_PICRESIZE_DITH,			"Dithering (ON for photographs, OFF for drawings)",													// [1] pøepínaè pouití ditheringu
// [3] Dialog vıbìru barvy
IDN_SELECT_COLOR,			"Color Selection",																					// titulek okna vıbìru barvy
// [3] Dialog hlášení chyby vytvoøení nového programu
IDN_SELECT_CREATE,			"Program Creation Error",																			// titulek okna hlášení chyby vytvoøení programu
IDN_SELECT_CREATE1,			"Cannot create the program.",																		// 1. øádek hlášení
IDN_JINE_JMENO,				"Try another name.",																				// 2. øádek hlášení (pozor - pouívá se i u jinıch chybovıch hlášení)
// [3] Dialog potvrzení rušení programu
IDN_SELECT_DEL,				"Program Deletion",																					// titulek okna potvrzení rušení programu
IDN_SELECT_DEL1,			"Do you really want to delete the selected program?",												// 1. øádek hlášení
IDN_SELECT_DEL2,			"WARNING: It will not be possible to restore the program!",											// 2. øádek hlášení
// [3] Dialog potvrzení rušení sloky
IDN_SELECT_DELDIR,			"Folder Deletion",																					// titulek okna potvrzení rušení sloky
IDN_SELECT_DELDIR1,			"Do you really want to delete the selected folder?",												// hlášení okna
// [3] Dialog hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR,		"Folder Deletion Error",																			// titulek okna hlášení chyby rušení sloky
IDN_SELECT_DELDIRERROR1,	"The folder cannot be deleted, if it is not empty.",												// hlášení okna
// [3] Dialog hlášení chyby rušení programu
IDN_SELECT_DELERROR,		"Program Deletion Error",																			// titulek okna hlášení chyby rušení programu
IDN_SELECT_DELERROR1,		"The program cannot be deleted, it is the read only program.",										// hlášení okna
// [3] Dialog vytvoøení nové sloky
IDN_SELECT_DIR,				"New Folder",																						// titulek okna vytvoøení nové sloky
IDN_SELECT_DIR1,			"What will be the new folder name?",																// vızva v oknì
// [3] Dialog hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE,		"Folder Creation Error",																			// titulek okna hlášení chyby vytvoøení sloky
IDN_SELECT_DIRCREATE1,		"The folder cannot be created.",																	// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existující sloky pøi vytváøení nové sloky
IDN_SELECT_DIREXIST,		"Folder Already Exists",																			// titulek okna hlášení chyby existující sloky
IDN_SELECT_DIREXIST1,		"Atention - such a folder already exists.",															// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog hlášení chyby existujícího programu pøi vytváøení nového programu
IDN_SELECT_EXIST,			"Program Already Exists",																			// titulek okna hlášení chyby existujícího programu
IDN_SELECT_EXIST1,			"Atention - such a program already exists.",														// 1. øádek hlášení (následuje 2. øádek "Zkuste jiné jméno")
// [3] Dialog vytvoøení nového programu
IDN_SELECT_NEW,				"New Program",																						// titulek okna vytvoøení nového programu
IDN_SELECT_NEW1,			"What will be the new program name?",																// vızva v oknì
// [3] Dialog vytvoøení kopie programu
IDN_SELECT_NEWCOPY,			"Program Copy",																						// titulek okna vytvoøení kopie programu
IDN_SELECT_NEWCOPY1,		"What will be the copied program name?",															// vızva v oknì
// [3] Dialog nastavení vlastností sprajtu
IDN_SPRITEDIMEN,			"Sprite Properties",																				// titulek okna nastavení vlastností sprajtu
IDN_ANIMACE,				"Animation",																						// nadpis rámeèku pro nastavení animací sprajtu
IDN_PRODLEVA_MEZI_FAZEMI,	"Delay Between Phases:",																			// nadpis pøed zadáním prodlevy mezi fázemi
IDN_MILISEKUND,				"milliseconds",																						// text "milisekund" za nastavením prodlevy mezi fázemi
IDN_FAZI_NA_KROK,			"Phases per Step (0 = Immediately):",																// nadpis pøed zadáním poètu fází na krok
IDN_HLADINA_K_ZOBRAZENI,	"Level to Be Displayed (0 = Items):",																// nadpis pøed zadáním hladiny k zobrazení sprajtu
IDN_POCET_OBRAZKU,			"Number of Pictures",																				// nadpis rámeèku pro nastavení poètu obrázkù sprajtu
IDN_FAZI_PRO_KLID,			"Standstill Phases:",																				// nadpis pøed zadáním fází pro klidovı stav sprajtu
IDN_FAZI_PRO_POHYB,			"Moving Phases:",																					// nadpis pøed zadáním fází pro pohyb sprajtu
IDN_SMERU,					"Directions:",																						// nadpis pøed zadáním poètu smìrù sprajtu
IDN_ROZMER_OBRAZKU,			"Picture Dimension",																				// nadpis rámeèku pro nastavení rozmìrù obrázku sprajtu
IDN_SIRKA_OBRAZKU,			"Picture Width:",																					// nadpis pøed zadáním šíøky obrázku sprajtu
IDN_VYSKA_OBRAZKU,			"Picture Height:",																					// nadpis pøed zadáním vıšky obrázku sprajtu
// [3] Dialog testu sprajtu
IDN_SPRITETEST,				"Sprite Test",																						// titulek okna testu sprajtu
// [3] Dialog chybového hlášení chyby uloení programu
IDN_WRITEERR,				"Saving Error",																						// titulek chybového hlášení chyby uloení programu
IDN_WRITEERR1,				"The program cannot be saved.",																		// 1. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR2,				"Check, whether it is not running or",																// 2. øádek hlášení
IDN_WRITEERR3,				"whether it is not protected against saving.",														// 3. øádek hlášení (následuje prázdnı oddìlovací øádek)
IDN_WRITEERR4,				"If needed, save the program with",																	// 4. øádek hlášení
IDN_WRITEERR5,				"the different name or to the different disk.",														// 5. øádek hlášení
// [3] Dialog dotazu, zda má bıt zmìnìnı program uloen
IDN_FILEMODICAP,			"Program Changed",																					// titulek okna dotazu, zda má bıt program uloen
IDN_FILEMODI,				"Program changed.\nDo you want to save the changes?",												// text okna
// [3] Dialog dotazu, zda má bıt pouívanı prvek zrušen
IDN_TESTREFER2,				"Element Is Being Used",																			// titulek okna varování, e rušená poloka je v programu pouívána
IDN_TESTREFER,				"Warning - deleted element is used in the program.\nBy its deleting you also delete the apropriate subtrees of this element.",	// text okna
// [3] Dialog dotazu, zda má bıt zrušen prvek z knihovny
IDN_CLASSDEL2,				"Irreversible Deletion",																			// titulek okna varování, e rušenı prvek z knihovny nebude moné obnovit
IDN_CLASSDEL,				"Warning - you delete the element of library.\nThis deletion is irreversible, it will not be possible to restore the element.",	// text okna
// [3] Dialog chybového hlášení o nedostatku pamìti
IDN_MEMERR_NADPIS,			"Insufficient Memory",																				// titulek okna chybového hlášení pøi nedostatku pamìti (pouívá se i pro interpreter)
IDN_MEMERR_TEXT,			"Insufficient memory for performing of the requested operation!\n\nFree some space on the Windows system disk\nor check setting of the Windows virtual memory.\nThis program can be now in an instable state,\ntherefore quit it as soon as possible.",	// text okna
IDN_LOADER_MEMERR_TEXT,		"Sorry, this program will be terminated due to the insufficient memory!",							// text okna hlášení pro interpreter
// [3] Dialog hlášení poškození licenèních dat
IDN_LICERR2,				"Damaged License Data",																				// titulek okna hlášení o poškozenıch licenèních datech
IDN_LICERR,					"The license data were damaged. Run instalator of the Peter application again to correct the license data.",	// text okna
// [3] Dialog hlášení o konci èasovì omezené licence
IDN_LICTIMEERR2,			"Termination of Time Limited Activity",																// titulek okna hlášení o ukonèení èasovì omezené doby provozu aplikace Petr
IDN_LICTIMEERR,				"The time limited activity period of the Peter application has expired.",							// text okna
// [3] Dialog hlášení o blíícím se konci èasovì omezené licence
IDN_LICTIME1,				"Termination of Time Limited Activity",																// titulek okna hlášení o blíícím se konci èasovì omezeného provozu Petra
IDN_LICTIME2,				"Activity of the Peter application is time limited.\nNumber of remaining days to the activity termination:",	// text okna
// [3] Dialog hlášení o chybì systémovıch prostøedkù
IDN_RESOURCE_ERR1,			"System Error",																						// titulek okna hlášení o nedostatku prostøedkù
IDN_RESOURCE_ERR2,			"Insufficient system resources to run program PETER.EXE.",											// text okna
// [3] Dialog hlášení o chybì poškození programu
IDN_DAMAGE_ERR1,			"Program Damaged",																					// titulek okna hlášení o poškozeném programu
IDN_DAMAGE_ERR2,			"Program PETER.EXE damaged, could not start.",														// text okna
// [3] Dialog uloení do jiného souboru
IDN_SAVE_AS1,				"Save to Another File",																				// titulek okna uloení do jiného souboru
IDN_PROGRAMY,				"Programs",																							// název souborù typu "program" v oknì uloení
IDN_VSECHNY_SOUBORY,		"All files",																						// název souborù typu "všechny soubory" v oknì uloení (pouívá se i pro interpreter v dialozích vıbìru souborù)
IDN_SAVE_DISTR1,			"Save Distribution Version of the Program",															// nadpis okna uloení distribuèní verze programu
IDN_SAVE_DISTR2,			"Program Already Exists",																			// titulek dialogu potvrzení pøepisu distribuèní verze
IDN_SAVE_DISTR3,			"Warning - the file being saved already exists.\n\nYou are saving the distribution noneditable version\nof this program and if the overwritten program is\na source program, all source information will be lost.\n\nDo you want to continue and to overwrite the file?",	// text dialogu potvrzení pøepisu distribuèní verze
// [3] Dialog interpreteru hlášení nespustitelného programu
IDN_NESPUSTITELNY,			"Nonexecutable program",																			// titulek okna hlášení nespustitelného programu
IDN_NESPUSTITELNY2,			"This program was created by a programmable tool Peter\nand is now stored in a nonexecutable form.",	// text okna hlášení
// [3] Dialog nastavení písma oken stromù
IDN_SETUP,					"Font Setup",																						// titulek okna nastavení písma oken stromù
IDN_SETUP_VZOR,				"Sample:",																							// nadpis nad textem vzorku písma
IDN_SETUP_VZOR2,			"This is a text sample.",																			// vzorek textu písma (text by mìl obsahovat nejrùznìjší znaky s diakritikou)
IDN_SETUP_STD,				"Standard Font",																					// volba pro zapnutí standardního typu písma
IDN_SETUP_BOLD,				"Bold",																								// volba pro zapnutí tuèného písma
IDN_SETUP_ITALIC,			"Italic",																							// volba pro zapnutí šikmého písma
IDN_SETUP_UNDERLINE,		"Underline",																						// volba pro zapnutí podtreného písma
IDN_SETUP_STRIKEOUT,		"Strike Out",																						// volba pro zapnutí pøeškrtnutého písma
IDN_SETUP_NORMAL,			"Without Serifs",																					// volba pro zapnutí bìného písma bez patièek (ARIAL)
IDN_SETUP_SERIF,			"With Serifs",																						// volba pro zapnutí písma s patièkami (SERIF)
IDN_SETUP_COURIER,			"Fixed Pitch",																						// volba pro zapnutí písma s pevnou rozteèí (COURIER)
IDN_SETUP_USER,				"Selected from List",																				// volba pro zapnutí písma s volbou ze seznamu typù písem
IDN_SETUP_TYP,				"List of Font Typeface Names:",																		// nadpis okna pro volbu typu písma
IDN_SETUP_HEIGHT,			"Height:",																							// nadpis okna pro volbu vıšky písma
IDN_SETUP_WIDTH,			"Width[%]:",																						// nadpis okna pro volbu šíøky písma
IDN_SETUP_RAM1,				"Effects",																							// nadpis rámeèku volby efektù písma (tuèné, kurzíva, podtrené a pøeškrtnuté)
IDN_SETUP_RAM2,				"Shape",																							// nadpis rámeèku volby vzhledu písma (patièky, pevná rozteè, fonty)
// [3] Dialog pro export a import programu
IDN_EXPORT2,				"Folder and name for program export",																// nadpis okna k volbì cíle pro export programu
IDN_IMPORT2,				"Name of imported program",																			// nadpis okna k volbì importovaného programu
IDN_EXPIMP,					"Peter programs",																					// název souborù s programy Petra
// [4] Stavební prvky programu
IDF_NONE,					"empty square",																						// prázdnı implicitní pøedmìt
IDF_GROUP,					"group",																							// skupina prvkù
IDF_IF,						"conditional executing of commands",																// záhlaví podmínky
IDF_IF_COND,				"if valid",																							// test podmínky (IF)
IDF_IF_YES,					"then do",																							// vìtev pøi splnìní podmínky (THEN)
IDF_IF_NO,					"else do",																							// vìtev pøi nesplnìní podmínky (ELSE)
IDF_WHILE,					"conditional repeating of commands",																// záhlaví smyèky s podmínkou
IDF_WHILE_COND,				"while is valid",																					// test smyèky s podmínkou (WHILE)
IDF_WHILE_BODY,				"repeat commands",																					// tìlo smyèky s podmínkou (DO)
IDF_WHILE_BREAK,			"break executing",																					// pøerušení smyèky (BREAK)
IDF_MINUS,					"negative sign",																					// záporné znaménko "-" v èísle
IDF_CASE,					"multibranch control structure",																	// záhlaví konstrukce vìtvení
IDF_CASE_SUM,				"for value of expression",																			// vìtvící hodnota konstrukce vìtvení (SWITCH)
IDF_CASE_ON,				"execute commands in case of",																		// jedna vìtev konstrukce vìtvení (CASE)
IDF_CASE_EQU,				"expression is equal to",																			// testovaná hodnota konstrukce vìtvení (ON)
IDF_CASE_DEF,				"else execute commands",																			// implicitní vìtev konstrukce vìtvení (DEFAULT)
IDF_NUM,					"numeric constant",																					// èíselná konstanta
IDF_0,						"0",																								// èíslice 0
IDF_1,						"1",																								// èíslice 1
IDF_2,						"2",																								// èíslice 2
IDF_3,						"3",																								// èíslice 3
IDF_4,						"4",																								// èíslice 4
IDF_5,						"5",																								// èíslice 5
IDF_6,						"6",																								// èíslice 6
IDF_7,						"7",																								// èíslice 7
IDF_8,						"8",																								// èíslice 8
IDF_9,						"9",																								// èíslice 9
IDF_DOT,					".",																								// desetinná teèka v èísle
IDF_EXP,					"exponent",																							// exponent v èísle
IDF_EQU,					"is equal to",																						// podmínka =
IDF_NEQU,					"is not equal to",																					// podmínka <>
IDF_EQGR,					"is greater or equal to",																			// podmínka >=
IDF_EQLT,					"is less or equal to",																				// podmínka <=
IDF_GR,						"is greater than",																					// podmínka >
IDF_LT,						"is less than",																						// podmínka <
IDF_AND,					"and",																								// logickı souèin
IDF_OR,						"or",																								// logickı souèet
IDF_XOR,					"either or (exclusive or)",																			// logickı vıhradní souèet
IDF_NOT,					"is not valid that",																				// logická negace
IDF_ADD,					"add",																								// souèet èísel
IDF_SUB,					"subtract",																							// rozdíl èísel
IDF_MUL,					"multiply",																							// násobek èísel
IDF_DIV,					"divide",																							// podíl èísel
IDF_REAL,					"number",																							// èíselná promìnná
IDF_ICON,					"item",																								// pøedmìtová promìnná
IDF_SND,					"sound",																							// zvuková promìnná
IDF_MUS,					"music",																							// hudební promìnná
IDF_FNC,					"function",																							// funkce
IDF_MAP,					"sheet",																							// promìnná plochy
IDF_SPRITE,					"sprite",																							// promìnná sprajtu
IDF_OPER_EXTRA,				"program control - extension",																		// skupina prvkù pro rozšíøené øízení programù
IDF_TEXT,					"text",																								// textová promìnná
IDF_WINDOWS,				"windows",																							// skupina prvkù pro øízení oken
IDF_PAR,					"input variables",																					// vstupní promìnné v oknì místních promìnnıch a funkcí
IDF_OUT,					"output variable",																					// vıstupní promìnná v oknì místních promìnnıch a funkcí
IDF_MAP_EXTRA,				"sheet - extension",																				// skupina prvkù pro práci s plochou - rozšíøení
IDF_LIST,					"list",																								// záhlaví seznamu (LIST)
IDF_OPER,					"program control",																					// skupina prvkù pro øízení programu
IDF_KROK,					"step",																								// Petøík popojít o krok vpøed
IDF_VLEVO,					"left",																								// Petøík otoèit doleva
IDF_VPRAVO,					"right",																							// Petøík otoèit doprava
IDF_VZAD,					"turn about",																						// Petøík otoèit vzad
IDF_PETRIK,					"Peter",																							// skupina prvkù Petøíka
IDF_BOOL,					"flag",																								// logická promìnná
IDF_TEXT_CONST,				"text constant",																					// textová konstanta
IDF_TRUE,					"yes",																								// logickı pøíznak TRUE
IDF_FALSE,					"no",																								// logickı pøíznak FALSE
IDF_PETRA,					"Lucy",																								// skupina prvkù Lucky
IDF_PETRA_KROK,				"step",																								// Lucka popojít o krok vpøed
IDF_PETRA_VLEVO,			"left",																								// Lucka otoèit doleva
IDF_PETRA_VPRAVO,			"right",																							// Lucka otoèit doprava
IDF_PETRA_VZAD,				"turn about",																						// Lucka otoèit vzad
IDF_RYCHLE,					"visible",																							// viditelnost Petøíka
IDF_EXIT,					"function termination",																				// pøerušení funkce
IDF_PETRA_RYCHLE,			"visible",																							// viditelnost Lucky
IDF_SOUNDMUSIC_GROUP,		"sound and music",																					// skupina prvkù pro zvuk, hudbu a CD
IDF_PREDMET,				"item in front of Peter",																			// pøedmìt pøed Petøíkem
IDF_SMER,					"direction",																						// smìr otoèení Petøíka
IDF_POZICEX,				"horizontal position",																				// horizontální souøadnice Petøíka
IDF_POZICEY,				"vertical position",																				// vertikální souøadnice Petøíka
IDF_PETRA_PREDMET,			"item in front of Lucy",																			// pøedmìt pøed Luckou
IDF_PETRA_SMER,				"direction",																						// smìt otoèení Lucky
IDF_PETRA_POZICEX,			"horizontal position",																				// horizontální souøadnice Lucky
IDF_PETRA_POZICEY,			"vertical position",																				// vertikální souøadnice Lucky
IDF_CONST,					"calculations",																						// skupina prvkù èíselnıch a logickıch operací
IDF_VYPOC,					"arithmetic operations",																			// skupina èíselnıch operátorù
IDF_FUNC,					"functions",																						// skupina èíselnıch funkcí
IDF_POROVNANI,				"comparisons",																						// skupina porovnávacích operátorù
IDF_LOG_OPER,				"logic operations",																					// skupina logickıch prvkù
IDF_MOD,					"modulo",																							// èíselnı operátor modulo
IDF_SIN,					"sine",																								// funkce sinus
IDF_COS,					"cosine",																							// funkce kosinus
IDF_TG,						"tangent",																							// funkce tangens
IDF_COTG,					"cotangent",																						// funkce kotangens
IDF_ARCSIN,					"arcsine",																							// funkce arcus sinus
IDF_ARCCOS,					"arccosine",																						// funkce arcus kosinus
IDF_ARCTG,					"arctangent",																						// funkce arcus tangens
IDF_ARCCOTG,				"arccotangent",																						// funkce arcus kotangens
IDF_PI,						"pi",																								// Ludolfovo èíslo (pí)
IDF_INTEGER,				"integer part",																						// funkce odstranìní desetinné èásti èísla
IDF_FRAC,					"fractional part",																					// funkce odstranìní celoèíselné èásti èísla
IDF_ABS,					"absolute value",																					// funkce absolutní hodnoty
IDF_SQRT,					"square root",																						// funkce druhá mocnina
IDF_FACT,					"factorial",																						// funkce faktoriál
IDF_RAND,					"random number (0 <= x < 1)",																		// náhodné èíslo
IDF_EUL,					"Euler constant",																					// Eulerova konstanta (e)
IDF_DEGRAD,					"convert degrees to radians",																		// funkce konverze stupòù na radiány
IDF_RADDEG,					"convert radians to degrees",																		// funkce konverze radiánù na stupnì
IDF_LOG,					"decadic logarithm",																				// funkce dekadickı logaritmus (základ 10)
IDF_LN,						"natural logarithm",																				// funkce pøirozenı logaritmus (základ e)
IDF_PEXP,					"natural exponential function",																		// funkce pøirozenı exponent (základ e)
IDF_MOCN,					"power",																							// operátor mocniny
IDF_UHEL,					"angle, direction",																					// skupina úhlù (smìrù)
IDF_UHEL0,					"right (0 pi, that is 0 degrees)",																	// smìr vpravo
IDF_UHEL45,					"right up (1/4 pi, that is 45 degrees)",															// smìr vpravo nahoru
IDF_UHEL90,					"up (1/2 pi, that is 90 degrees)",																	// smìr nahoru
IDF_UHEL135,				"left up (3/4 pi, that is 135 degrees)",															// smìr vlevo nahoru
IDF_UHEL180,				"left (1 pi, that is 180 degrees)",																	// smìr vlevo
IDF_UHEL225,				"left down (1 1/4 pi, that is 225 degrees)",														// smìr vlevo dolù
IDF_UHEL270,				"down (1 1/2 pi, that is 270 degrees)",																// smìr dolù
IDF_UHEL315,				"right down (1 3/4 pi, that is 315 degrees)",														// smìr vpravo dolù
IDF_COMMAND,				"controls",																							// skupina prvkù ovládání (klávesnice, myš, joystick, dialogy)
IDF_WAIT,					"wait (default = 0.05 s)",																			// pøíkaz pro èekání
IDF_KLAV,					"keyboard",																							// skupina ovládání klávesnice
IDF_KLAV_TEST,				"there is pressed key",																				// test stisknuté klávesy
IDF_KLAV_VKEY,				"key input (does not wait for press)",																// vstup klávesy bez èekání
IDF_KLAV_CHAR,				"character input (does not wait for press)",														// vstup znaku bez èekání
IDF_KLAV_VK,				"keys",																								// skupina kódù kláves
IDF_KLAV_FX,				"function keys",																					// skupina kódù funkèních kláves
IDF_KLAV_PISM,				"letters",																							// skupina kódù kláves písmen
IDF_KLAV_NUM,				"numeric keyboard",																					// skupina kódù kláves numerické klávesnice
IDF_KLAV_RUZNE,				"character keys",																					// skupina kódù znakovıch kláves
IDF_KLAV_RID,				"control keys",																						// skupina kódù øídicích kláves
IDF_TRANSPARENT,			"transparency",																						// zprùhlednìní okna
IDF_F1,						"F1",																								// kód klávesy F1
IDF_F2,						"F2",																								// kód klávesy F2
IDF_F3,						"F3",																								// kód klávesy F3
IDF_F4,						"F4",																								// kód klávesy F4
IDF_F5,						"F5",																								// kód klávesy F5
IDF_F6,						"F6",																								// kód klávesy F6
IDF_F7,						"F7",																								// kód klávesy F7
IDF_F8,						"F8",																								// kód klávesy F8
IDF_F9,						"F9",																								// kód klávesy F9
IDF_F10,					"F10",																								// kód klávesy F10
IDF_F11,					"F11",																								// kód klávesy F11
IDF_F12,					"F12",																								// kód klávesy F12
IDF_A,						"A",																								// kód klávesy A
IDF_B,						"B",																								// kód klávesy B
IDF_C,						"C",																								// kód klávesy C
IDF_D,						"D",																								// kód klávesy D
IDF_E,						"E",																								// kód klávesy E
IDF_F,						"F",																								// kód klávesy F
IDF_G,						"G",																								// kód klávesy G
IDF_H,						"H",																								// kód klávesy H
IDF_I,						"I",																								// kód klávesy I
IDF_J,						"J",																								// kód klávesy J
IDF_K,						"K",																								// kód klávesy K
IDF_L,						"L",																								// kód klávesy L
IDF_M,						"M",																								// kód klávesy M
IDF_N,						"N",																								// kód klávesy N
IDF_O,						"O",																								// kód klávesy O
IDF_P,						"P",																								// kód klávesy P
IDF_Q,						"Q",																								// kód klávesy Q
IDF_R,						"R",																								// kód klávesy R
IDF_S,						"S",																								// kód klávesy S
IDF_T,						"T",																								// kód klávesy T
IDF_U,						"U",																								// kód klávesy U
IDF_V,						"V",																								// kód klávesy V
IDF_W,						"W",																								// kód klávesy W
IDF_X,						"X",																								// kód klávesy X
IDF_Y,						"Y",																								// kód klávesy Y
IDF_Z,						"Z",																								// kód klávesy Z
IDF_VK_NUM0,				"0 Ins",																							// kód numerické klávesy 0 Ins
IDF_VK_NUM1,				"1 End",																							// kód numerické klávesy 1 End
IDF_VK_NUM2,				"2 Down",																							// kód numerické klávesy 2 dolù
IDF_VK_NUM3,				"3 PgDn",																							// kód numerické klávesy 3 PgDn
IDF_VK_NUM4,				"4 Left",																							// kód numerické klávesy 4 vlevo
IDF_VK_NUM5,				"5",																								// kód numerické klávesy 5
IDF_VK_NUM6,				"6 Right",																							// kód numerické klávesy 6 vpravo
IDF_VK_NUM7,				"7 Home",																							// kód numerické klávesy 7 Home
IDF_VK_NUM8,				"8 Up",																								// kód numerické klávesy 8 nahoru
IDF_VK_NUM9,				"9 PgUp",																							// kód numerické klávesy 9 PgUp
IDF_VK_NUMTECKA,			". Del",																							// kód numerické klávesy . Del
IDF_VK_NUMPLUS,				"+",																								// kód numerické klávesy +
IDF_VK_NUMMINUS,			"-",																								// kód numerické klávesy -
IDF_VK_NUMKRAT,				"*",																								// kód numerické klávesy *
IDF_VK_NUMDELENO,			"/",																								// kód numerické klávesy /
IDF_VK_NUMENTER,			"Enter",																							// kód numerické klávesy Enter
IDF_VK_NUMLOCK,				"Num Lock",																							// kód numerické klávesy Num Lock
IDF_VK_1,					"1 !",																								// kód klávesy 1 !
IDF_VK_2,					"2 @",																								// kód klávesy 2 @
IDF_VK_3,					"3 #",																								// kód klávesy 3 #
IDF_VK_4,					"4 $",																								// kód klávesy 4 $
IDF_VK_5,					"5 %",																								// kód klávesy 5 %
IDF_VK_6,					"6 ^",																								// kód klávesy 6 ^
IDF_VK_7,					"7 &",																								// kód klávesy 7 &
IDF_VK_8,					"8 *",																								// kód klávesy 8 *
IDF_VK_9,					"9 (",																								// kód klávesy 9 (
IDF_VK_0,					"0 )",																								// kód klávesy 0 )
IDF_VK_LCARKA,				"` ~",																								// kód klávesy ` ~
IDF_VK_POMLCKA,				"- _",																								// kód klávesy - _
IDF_VK_ROVNITKO,			"= +",																								// kód klávesy = +
IDF_VK_ZLOMITKO,			"\\ |",																								// kód klávesy \ |
IDF_VK_LLOMENA,				"[ {",																								// kód klávesy [ {
IDF_VK_RLOMENA,				"] }",																								// kód klávesy ] }
IDF_VK_STREDNIK,			"; :",																								// kód klávesy ; :
IDF_VK_RCARKA,				"\' \"",																							// kód klávesy ' "
IDF_VK_CARKA,				", <",																								// kód klávesy , <
IDF_VK_TECKA,				". >",																								// kód klávesy . >
IDF_VK_LOMITKO,				"/ ?",																								// kód klávesy / ?
IDF_VK_ESC,					"Esc",																								// kód klávesy Esc
IDF_VK_TAB,					"Tab",																								// kód klávesy Tab
IDF_VK_CAPSLOCK,			"Caps Lock",																						// kód klávesy Caps Lock
IDF_VK_WIN,					"left Windows menu key",																			// kód klávesy Menu Windows vlevo
IDF_VK_BS,					"Back Space",																						// kód klávesy Back Space
IDF_VK_ENTER,				"Enter",																							// kód klávesy Enter
IDF_VK_MENU,				"local menu",																						// kód klávesy Lokální menu
IDF_VK_LEFT,				"Left",																								// kód klávesy Vlevo
IDF_VK_RIGHT,				"Right",																							// kód klávesy Vpravo
IDF_VK_UP,					"Up",																								// kód klávesy Nahoru
IDF_VK_DOWN,				"Down",																								// kód klávesy Dolù
IDF_VK_INSERT,				"Insert",																							// kód klávesy Insert
IDF_VK_DELETE,				"Delete",																							// kód klávesy Delete
IDF_VK_HOME,				"Home",																								// kód klávesy Home
IDF_VK_END,					"End",																								// kód klávesy End
IDF_VK_PAGEUP,				"Page Up",																							// kód klávesy Page Up
IDF_VK_PAGEDOWN,			"Page Down",																						// kód klávesy Page Down
IDF_VK_PRINT,				"Print Screen",																						// kód klávesy Print Screen
IDF_VK_SCROLL,				"Scroll Lock",																						// kód klávesy Scroll Lock
IDF_VK_PAUSE,				"Pause",																							// kód klávesy Pause
IDF_VK_SHIFT,				"left Shift",																						// kód klávesy Levı Shift
IDF_VK_CTRL,				"left Ctrl",																						// kód klávesy Levı Ctrl
IDF_VK_ALT,					"left Alt",																							// kód klávesy Levı Alt
IDF_VK_SPACE,				"spacebar",																							// kód klávesy Mezera (mezerník)
IDF_MOUSE,					"mouse",																							// skupina prvkù myši
IDF_MOUSE_L,				"left mouse button is held",																		// pøíznak dreného levého tlaèítka myši
IDF_MOUSE_R,				"right mouse button is held",																		// pøíznak dreného pravého tlaèítka myši
IDF_MOUSE_X,				"mouse position in horizontal direction",															// horizontální souøadnice myši
IDF_MOUSE_Y,				"mouse position in vertical direction",																// vertikální souøadnice myši
IDF_EQU_TEXT,				"text identity",																					// operátor porovnání textù
IDF_EQU_ICO,				"item identity",																					// operátor porovnání pøedmìtù
IDF_SPRITE_EXTRA,			"sprites - extension",																				// skupina prvkù pro práci se sprajty - rozšíøení
IDF_WINDOW_FRAME,			"window has border",																				// pøíznak zobrazení okraje okna
IDF_WINDOW_CAPTION,			"window has caption",																				// pøíznak zobrazení titulku okna
IDF_COMMAND_LINE,			"program parameters",																				// parametry programu z pøíkazového øádku (prvek v místních promìnnıch hlavní funkce programu)
IDF_RETURN_CODE,			"return code",																						// návratovı kód programu (prvek v místních promìnnıch hlavní funkce programu)
IDF_PIC,					"picture",																							// promìnná obrázku
IDF_REPEAT,					"command repeating with specified run number",														// záhlaví smyèky se zadanım poètem opakování
IDF_REPEAT_N,				"for number of repetitions",																		// zadání poètu opakování smyèky (FOR)
IDF_OKRAJ,					"sheet border",																						// pøedmìt okraje plochy (neplatnı pøedmìt)
IDF_SPRITE_X,				"horizontal",																						// horizontální souøadnice sprajtu
IDF_SPRITE_Y,				"vertical",																							// vertikální souøadnice sprajtu
IDF_SPRITE_SMER,			"direction",																						// smìr sprajtu
IDF_SPRITE_MOVE,			"moving",																							// pøíznak pohybu sprajtu
IDF_SPRITE_VISIBLE,			"visible",																							// pøíznak viditelnosti sprajtu
IDF_LIST_SIZE,				"number",																							// velikost seznamu (poèet prvkù)
IDF_LIST_INDEX,				"index",																							// index seznamu
IDF_LIST_AUTO,				"index increment",																					// pøírustek indexu seznamu
IDF_PETER_EXTRA,			"Peter - extension",																				// skupina rozšiøujících prvkù Petøíka
IDF_PETRA_EXTRA,			"Lucy - extension",																					// skupina rozšiøujících prvkù Lucky
IDF_PETER_SWCN1,			"numeric value 1 (range 0 to 1023)",																// èíselná hodnota 1 na pozici s Petøíkem
IDF_PETRA_SWCN1,			"numeric value 1 (range 0 to 1023)",																// èíselná hodnota 1 na pozici s Luckou
IDF_PETER_SWCN2,			"numeric value 2 (range 0 to 1023)",																// èíselná hodnota 2 na pozici s Petøíkem
IDF_PETRA_SWCN2,			"numeric value 2 (range 0 to 1023)",																// èíselná hodnota 2 na pozici s Luckou
IDF_PETER_SWCN3,			"numeric value 3 (range 0 to 127)",																	// èíselná hodnota 3 na pozici s Petøíkem
IDF_PETRA_SWCN3,			"numeric value 3 (range 0 to 127)",																	// èíselná hodnota 3 na pozici s Luckou
IDF_PETER_SWC1,				"flag 1",																							// pøepínaè 1 na pozici s Petøíkem
IDF_PETRA_SWC1,				"flag 1",																							// pøepínaè 1 na pozici s Luckou
IDF_PETER_SWC2,				"flag 2",																							// pøepínaè 2 na pozici s Petøíkem
IDF_PETRA_SWC2,				"flag 2",																							// pøepínaè 2 na pozici s Luckou
IDF_PETER_SWC3,				"flag 3",																							// pøepínaè 3 na pozici s Petøíkem
IDF_PETRA_SWC3,				"flag 3",																							// pøepínaè 3 na pozici s Luckou
IDF_PETER_SWC4,				"flag 4",																							// pøepínaè 4 na pozici s Petøíkem
IDF_PETRA_SWC4,				"flag 4",																							// pøepínaè 4 na pozici s Luckou
IDF_PETER_SWC5,				"flag 5",																							// pøepínaè 5 na pozici s Petøíkem
IDF_PETRA_SWC5,				"flag 5",																							// pøepínaè 5 na pozici s Luckou
IDF_TEXT_GROUP,				"texts",																							// skupina prvkù pro práci s textem
IDF_TEXT_LEFT,				"left part of text",																				// funkce levé èásti textu
IDF_TEXT_LEFT_LEN,			"length of left part of text",																		// délka pro funkci levé èásti textu
IDF_TEXT_RIGHT,				"right part of text",																				// funkce pravé èásti textu
IDF_TEXT_RIGHT_POS,			"beginning of right part of text",																	// poèátek pro funkci pravé èásti textu
IDF_TEXT_MID,				"middle part of text",																				// funkce støední èásti textu
IDF_TEXT_MID_POS,			"beginning of middle part of text",																	// poèátek pro funkci støední èásti textu
IDF_TEXT_MID_LEN,			"length of middle part of text",																	// délka pro funkci støední èásti textu
IDF_TEXT_LEN,				"length of text",																					// funkce zjištìní délky textu
IDF_TEXT_ADD,				"merge of texts",																					// operátor pro slouèení textù
IDF_TEXT_SCAN,				"conversion of number from text form",																// funkce pro pøevod èísla z textového zápisu na èíslo
IDF_TEXT_FORMAT,			"conversion of number to text form",																// funkce pro pøevod èísla do textového zápisu
IDF_TEXT_GT,				"alphabetic comparison of texts",																	// operátor pro abecední porovnání textù
IDF_TEXT_LOWER,				"convert to lower case",																			// funkce pro pøevod textu na malá písmena
IDF_TEXT_UPPER,				"convert to upper case",																			// funkce pro pøevod textu na velká písmena
IDF_TEXT_FIND,				"find text position (-1 = none)",																	// funkce pro vyhledání textového øetìzce v jiném textu
IDF_TEXT_INPUT,				"input text",																						// zadanı vstupní text pro textové funkce
IDF_TEXT_FIND_SUB,			"text to be found",																					// zadanı text k hledání pro funkci vyhledání textu
IDF_STATUS_LINE,			"information text",																					// stavovı øádek hlavního okna (textová promìnná)
IDF_CAPTION,				"window caption",																					// titulek hlavního okna (textová promìnná)
IDF_ORD,					"convert character to numeric code",																// funkce pro konverzi jednoho znaku na èíselnı kód (poøadí znaku v ASCII tabulce)
IDF_CHAR,					"convert numeric code to character",																// funkce pro konverzi èíselného kódu (poøadí v ASCII tabulce) na znak
IDF_SOUND_GROUP,			"sound",																							// skupina prvkù pro práci se zvukem
IDF_SOUND_PLAY,				"play sound",																						// pøehrátí zvuku
IDF_SOUND_STOP,				"stop sound (default = all)",																		// vypnutí zvuku
IDF_COLOR,					"color",																							// barevná konstanta pro zadání barvy
IDF_GRAPH_GROUP,			"graphic",																							// skupina prvkù pro práci s grafikou a obrázky
IDF_GRAPH_COLOR,			"pen color",																						// zadání barvy pera pro grafické pøíkazy
IDF_GRAPH_WIDTH,			"pen width",																						// zadání tloušky pera pro grafické pøíkazy
IDF_POINT,					"point",																							// nakreslení grafického bodu
IDF_POINT_X,				"horizontal X coordinate of point",																	// horizontální souøadnice X kresleného bodu
IDF_POINT_Y,				"vertical Y coordinate of point",																	// vertikální souøadnice Y kresleného bodu
IDF_LINE,					"line",																								// nakreslení èáry
IDF_LINE_X1,				"horizontal X1 coordinate of line",																	// 1. horizontální souøadnice X kreslené èáry
IDF_LINE_Y1,				"vertical Y1 coordinate of line",																	// 1, vertikální souøadnice Y kreslené èáry
IDF_LINE_X2,				"horizontal X2 coordinate of line",																	// 2. horizontální souøadnice X kreslené èáry
IDF_LINE_Y2,				"vertical Y2 coordinate of line",																	// 2. vertikální souøadnice Y kreslené èáry
IDF_BOX,					"box",																								// nakreslení obdélníku bez vıplnì
IDF_BOX_X1,					"horizontal X1 coordinate of box",																	// 1. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y1,					"vertical Y1 coordinate of box",																	// 1. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_X2,					"horizontal X2 coordinate of box",																	// 2. horizontální souøadnice X kresleného obdélníku bez vıplnì
IDF_BOX_Y2,					"vertical Y2 coordinate of box",																	// 2. vertikální souøadnice Y kresleného obdélníku bez vıplnì
IDF_BOX_FILL,				"filled box",																						// nakreslení obdélníku s vıplní
IDF_BOX_FILL_X1,			"horizontal X1 coordinate of filled box",															// 1. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y1,			"vertical Y1 coordinate of filled box",																// 1. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_BOX_FILL_X2,			"horizontal X2 coordinate of filled box",															// 2. horizontální souøadnice X kresleného obdélníku s vıplní
IDF_BOX_FILL_Y2,			"vertical Y2 coordinate of filled box",																// 2. vertikální souøadnice Y kresleného obdélníku s vıplní
IDF_FILL,					"filler",																							// vıplò plochy (vylití barvou)
IDF_FILL_X,					"horizontal X coordinate of filler",																// horizontální souøadnice X k vyplnìní plochy
IDF_FILL_Y,					"vertical Y coordinate of filler",																	// vertikální souøadnice Y k vyplnìní plochy
IDF_CIRCLE,					"circle",																							// nakreslení krunice bez vıplnì
IDF_CIRCLE_X,				"horizontal X coordinate of centre",																// horizontální souøadnice X støedu kreslené krunice bez vıplnì
IDF_CIRCLE_Y,				"vertical Y coordinate of centre",																	// vertikální souøadnice Y støedu kreslené krunice bez vıplnì
IDF_CIRCLE_R,				"radius",																							// polomìr kreslené krunice bez vıplnì
IDF_CIRCLE_FILL,			"filled circle",																					// nakreslení kruhu s vıplní
IDF_CIRCLE_FILL_X,			"horizontal X coordinate of centre",																// horizontální souøadnice X støedu kresleného kruhu s vıplní
IDF_CIRCLE_FILL_Y,			"vertical Y coordinate of centre",																	// vertikální souøadnice Y kresleného kruhu s vıplní
IDF_CIRCLE_FILL_R,			"radius",																							// polomìr kresleného kruhu s vıplní
IDF_TRIANGLE,				"triangle",																							// nakreslení trojúhelníku (s vıplní)
IDF_TRIANGLE_X1,			"horizontal X1 coordinate of triangle",																// 1. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y1,			"vertical Y1 coordinate of triangle",																// 1. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X2,			"horizontal X2 coordinate of triangle",																// 2. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y2,			"vertical Y2 coordinate of triangle",																// 2. vertikální souøadnice Y kresleného trojúhelníku
IDF_TRIANGLE_X3,			"horizontal X3 coordinate of triangle",																// 3. horizontální souøadnice X kresleného trojúhelníku
IDF_TRIANGLE_Y3,			"vertical Y3 coordinate of triangle",																// 3. vertikální souøadnice Y kresleného trojúhelníku
IDF_SPHERE,					"sphere",																							// nakreslení koule
IDF_SPHERE_X,				"horizontal X coordinate of centre",																// horizontální souøadnice X støedu kreslené koule
IDF_SPHERE_Y,				"vertical Y coordinate of centre",																	// vertikální souøadnice Y støedu kreslené koule
IDF_SPHERE_R,				"radius",																							// polomìr støedu kreslené koule
IDF_COLOR_LEVEL,			"change color brightness",																			// funkce pro zmìnu jasu barvy
IDF_COLOR_LEVEL_N,			"color brightness (0 to 1)",																		// poadovanı jas barvy pro funkci zmìny jasu barvy
IDF_KLAV_VKEY_WAIT,			"key input (waits to be pressed)",																	// funkce pro vstup klávesy s èekáním na stisk
IDF_KLAV_CHAR_WAIT,			"character input (waits to be pressed)",															// funkce pro vstup znaku s èekáním na stisk
IDF_VK_NOKEY,				"no key pressed",																					// kód klávesy, není-li ádná klávesa stisknuta
IDF_VK_WINR,				"right Windows menu key",																			// kód klávesy Menu Windows vpravo
IDF_VK_SHIFTR,				"right Shift",																						// kód klávesy Pravı Shift
IDF_VK_CTRLR,				"right Ctrl",																						// kód klávesy Pravı Ctrl
IDF_VK_ALTR,				"right Alt",																						// kód klávesy Pravı Alt
IDF_STATUS_NUMLOCK,			"status of Num Lock",																				// prvek stavu indikátoru Num Lock
IDF_STATUS_CAPSLOCK,		"status of Caps Lock",																				// prvek stavu indikátoru Caps Lock
IDF_STATUS_SCROLLLOCK,		"status of Scroll Lock",																			// prvek stavu indikátoru Scroll Lock
IDF_STATUS_INSERT,			"status of Insert",																					// prvek stavu indikátoru Insert
IDF_MOUSE_LCLICK,			"click by left mouse button",																		// pøíznak kliknutí levım tlaèítkem myši
IDF_MOUSE_RCLICK,			"click by right mouse button",																		// pøíznak kliknutí pravım tlaèítkem myši
IDF_MOUSE_LDCLICK,			"double click by left mouse button",																// pøíznak dvojkliknutí levım tlaèítkem myši
IDF_MOUSE_RDCLICK,			"double click by right mouse button",																// pøíznak dvojkliknutí pravım tlaèítkem myši
IDF_MOUSE_REGION,			"mouse test in the region",																			// funkce pro test souøadnic myši v zadané oblasti
IDF_MOUSE_REGION_X,			"horizontal X coordinate of the region beginning",													// horizontální souøadnice X poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_Y,			"vertical Y coordinate of the region beginning",													// vertikální souøadnice Y poèátku testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_W,			"width of region",																					// šíøka testované oblasti funkce pro test myši v oblasti
IDF_MOUSE_REGION_H,			"height of region",																					// vıška testované oblasti funkce pro test myši v oblasti
IDF_GRAPH_TEXT,				"text display",																						// vıpis textu v grafickém reimu
IDF_GRAPH_TEXT_X,			"horizontal X coordinate of text",																	// horizontální souøadnice X k vıpisu grafického textu
IDF_GRAPH_TEXT_Y,			"vertical Y coordinate of text",																	// vertikální souøadnice Y k vıpisu grafického textu
IDF_GRAPH_TEXT_ANGLE,		"angle orientation of text",																		// úhel orientace vypisovaného grafického textu (smìr textu)
IDF_GRAPH_TEXT_H,			"height of characters",																				// vıška znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_W,			"relative width of characters (1 = usual)",															// relativní šíøka znakù vypisovaného grafického textu
IDF_GRAPH_TEXT_BOLD,		"bold",																								// pøíznak tuèného textu pro vypisovanı grafickı text (BOLD)
IDF_GRAPH_TEXT_ITALIC,		"italic",																							// pøíznak šikmého textu pro vypisovanı grafickı text (ITALIC)
IDF_GRAPH_TEXT_UNDERLINE,	"underline",																						// pøíznak podtrení pro vypisovanı grafickı text (UNDERLINE)
IDF_GRAPH_TEXT_STRIKEOUT,	"strike out",																						// pøíznak pøeškrtnutí pro vypisovanı grafickı text (STRIKEOUT)
IDF_GRAPH_TEXT_SERIF,		"serifs",																							// pøíznak patièek vypisovaného grafického textu (SERIF)
IDF_GRAPH_TEXT_COURIER,		"typewriter",																						// pøíznak pevnıch rozteèí znakù vypisovaného grafického textu (COURIER)
IDF_GRAPH_TEXT_TEXT,		"text to be displayed",																				// zadanı text k vıpisu vypisovaného grafického textu
IDF_TEXTLINE_NUM,			"number of text lines",																				// funkce pro zjištìní poètu øádkù textu
IDF_TEXTLINE_GET,			"text line",																						// funkce pro získání jednoho øádku víceøádkového textu
IDF_TEXTLINE_INDEX,			"text line number",																					// èíslo øádku pro funkci získání jednoho øádku textu z víceøádkového textu
IDF_SOUND_TEST,				"sound test (default = all sounds)",																// funkce pro test pøehrávání zvuku
IDF_SOUND_PLAY_LOOP,		"repetition number (0 = permanently)",																// zadanı poèet opakování pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_PREDMET_POZ,			"item on Peter\'s position",																		// pøedmìt na pozici s Petøíkem
IDF_PETRA_PREDMET_POZ,		"item on Lucy\'s position",																			// pøedmìt na pozici s Luckou
IDF_PIC_DISP,				"draw picture",																						// pøíkaz pro vykreslení obrázku
IDF_PIC_BACK,				"picture to be drawn",																				// obrázek k vykreslení pro pøíkaz vykreslení obrázku
IDF_PIC_X,					"horizontal X coordinate of picture",																// horizontální souøadnice X k vykreslení obrázku
IDF_PIC_Y,					"vertical Y coordinate of picture",																	// vertikální souøadnice Y k vykreslení obrázku
IDF_PIC_BLOCK_X,			"horizontal X coordinate of cutout",																// horizontální souøadnice X vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_Y,			"vertical Y coordinate of cutout",																	// vertikální souøadnice Y vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_W,			"width of cutout",																					// šíøka vıøezu v obrázku k vykreslení
IDF_PIC_BLOCK_H,			"height of cutout",																					// vıška vıøezu v obrázku k vykreslení
IDF_PIC_GET,				"retain cutout from sheet as picture",																// funkce pro získání vıøezu z okna jako obrázek
IDF_ICON_GET,				"retain cutout from sheet as item",																	// funkce pro získání vıøezu z okna jako pøedmìt
IDF_LANGUAGE,				"language (0=auto, 5=CZ, 7=D, 9=USA, 27=SK)",														// aktivní jazyk
IDF_SOUND_PLAY_SOUND,		"sound to be played",																				// zvuk k pøehrátí (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_VOL,			"sound volume (0 to 1)",																			// hlasitost pøehrávaného zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_BAL,			"stereophonic balance (-1 = left to +1 = right)",													// stereofonní pøehrávání zvuku (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_PLAY_STOP,		"break playing sound",																				// pøíznak pøerušení starého zvuku, je-li ji pøehráván (je to parametr pøíkazu pro pøehrávání zvuku)
IDF_COMMENT,				"comment",																							// komentáø
IDF_SOUND_FUNCTIONS,		"sound functions",																					// skupina zvukovıch funkcí
IDF_MOUSE_CURSOR,			"setting shape of mouse cursor",																	// pøíkaz pro nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_PIC,		"picture of mouse cursor (default = original)",														// obrázek myši pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_X,			"horizontal X coordinate of the region beginning",													// horizontální souøadnice X oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_Y,			"vertical Y coordinate of the region beginning",													// vertikální souøadnice Y oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_W,			"width of region",																					// šíøka oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MOUSE_CURSOR_H,			"height of region",																					// vıška oblasti pro pøíkaz nastavení vzhledu kurzoru myši
IDF_MUSIC_PLAY,				"play music",																						// pøíkaz pro pøehrátí hudby (PLAY)
IDF_MUSIC_LOOP,				"play music repeated",																				// pøíkaz pro opakované pøehrávání hudby (LOOP)
IDF_MUSIC_STOP,				"stop playing music",																				// pøíkaz pro zastavení pøehrávání hudby (STOP)
IDF_MUSIC_PAUSE,			"pause/continue playing music",																		// pøíkaz pro pozastavení/pokraèování v pøehrávání hudby (PAUSE)
IDF_MUSIC_TEST,				"test playing music",																				// test pøehrávání hudby
IDF_MUSIC_POS,				"position in music being played",																	// pozice v pøehrávání hudby
IDF_MUSIC_LEN,				"length of music being played",																		// délka pøehrávané hudby
IDF_COLOR_SYNTH,			"compound color components to color",																// funkce pro slouèení barevnıch sloek do barev
IDF_COLOR_SYNTH_RED,		"red component (0 to 1)",																			// èervená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_GREEN,		"green component (0 to 1)",																			// zelená sloka funkce pro slouèení barevnıch sloek do barvy
IDF_COLOR_SYNTH_BLUE,		"blue component (0 to 1)",																			// modrá sloka funkce pro slouèení barevnıch sloek do barvy
IDF_GET_POINT,				"get color of pixel",																				// funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_X,			"horizontal X coordinate for getting color of pixel",												// horizontální souøadnice X funkce pro zjištìní barvy bodu z okna
IDF_GET_POINT_Y,			"vertical Y coordinate for getting color of pixel",													// vertikální souøadnice Y funkce pro zjištìní barvy bodu z okna
IDF_SQR,					"square power",																						// funkce druhá mocnina
IDF_MUSIC_GROUP,			"music",																							// skupina prvkù pro práci s hudbou
IDF_CD_GROUP,				"audio CD",																							// skupina prvkù pro práci se zvukovım CD
IDF_CD_PLAY,				"play CD from requested track (default = 1)",														// pøehrátí CD od zadané stopy (PLAY)
IDF_CD_STOP,				"stop playing CD",																					// zastavení pøehrávání CD (STOP)
IDF_CD_PAUSE,				"pause/continue playing CD",																		// pozastavení/pokraèování v pøehrávání CD (PAUSE)
IDF_CD_TEST,				"test playing CD",																					// test pøehrávání CD
IDF_CD_LENGTH,				"total length",																						// celková délka CD
IDF_CD_TRACKS,				"number of tracks",																					// poèet stop CD
IDF_CD_POS,					"position from the beginning",																		// pozice pøehrávání od zaèátku CD
IDF_CD_TRACK,				"track being played",																				// èíslo pøehrávané stopy CD
IDF_CD_TRACK_LENGTH,		"length of track being played",																		// délka pøehrávané stopy CD
IDF_CD_TRACK_POS,			"position from the track beginning",																// pozice pøehrávání od zaèátku stopy CD
IDF_FILE_GROUP,				"files",																							// skupina prvkù pro práci se soubory
IDF_FILE_FILEGROUP,			"basic operations",																					// skupina prvkù pro základní operace se soubory
IDF_FILE_FILENEW,			"new file",																							// vytvoøení nového souboru
IDF_FILE_DIRNEW,			"new folder",																						// vytvoøení nového adresáøe
IDF_FILE_DELETE,			"delete file or folder",																			// zrušení souboru nebo adresáøe
IDF_FILE_TEST,				"test of existence",																				// test existence souboru nebo adresáøe
IDF_FILE_ACT,				"active disk and folder",																			// nastavení aktivního disku a adresáøe
IDF_FILE_DISKSIZE,			"disk capacity",																					// zjištìní celkové kapacity disku
IDF_FILE_DISKFREE,			"free disk space",																					// zjištìní volného místa na disku
IDF_FILE_DISKLABEL,			"disk volume label",																				// zjištìní/nastavení jmenovky disku (VOLUME, LABEL)
IDF_FILE_DISKSERIAL,		"disk serial number",																				// zjištìní sériového èísla disku
IDF_FILE_READ,				"active file/folder for reading",																	// aktivní soubor pro ètení dat ze souboru
IDF_FILE_WRITE,				"active file/folder for writing",																	// aktivní soubor pro zápis dat do souboru
IDF_FILE_COPY,				"file copy",																						// provedení kopie souboru
IDF_FILE_MOVE,				"file (folder) move/rename",																		// provedení pøesunu/pøejmenování souboru nebo adresáøe
IDF_FILE_DISKGROUP,			"disk",																								// skupina prvkù pro práci s diskem
IDF_FILE_ATTRIB,			"attributes",																						// skupina prvkù pro práci s parametry souborù a adresáøù
IDF_FILE_RO,				"attribute R/O (read-only)",																		// atribut R/O souboru nebo adresáøe
IDF_FILE_HID,				"attribute HID (hidden)",																			// atribut HID souboru nebo adresáøe
IDF_FILE_SYS,				"attribute SYS (system)",																			// atribut SYS souboru nebo adresáøe
IDF_FILE_DIR,				"attribute DIR (folder)",																			// atribut DIR souboru nebo adresáøe
IDF_FILE_ARC,				"attribute ARC (archive)",																			// atribut ARC souboru nebo adresáøe
IDF_FILE_TMP,				"attribute TEMP (temporary)",																		// atribut TEMP souboru nebo adresáøe
IDF_FILE_CMP,				"attribute COMP (compressed)",																		// atribut COMP souboru nebo adresáøe
IDF_FILE_OFF,				"attribute OFF (offline)",																			// atribut OFF souboru nebo adresáøe
IDF_FILE_CREATE,			"date and time of creation",																		// datum a èas vytvoøení souboru nebo adresáøe
IDF_FILE_OPEN,				"last access date and time",																		// datum a èas posledního pøístupu k souboru nebo adresáøi (ètení)
IDF_FILE_MODI,				"last write date and time",																			// datum a èas poslední modifikace souboru nebo adresáøe (zápis)
IDF_FILE_DATA,				"data",																								// skupina dat souborù
IDF_FILE_BYTES,				"integer number with sign, 1 byte",																	// celé èíslo se znaménkem 1 bajt (data souboru)
IDF_FILE_BYTEU,				"integer number without sign, 1 byte",																// celé èíslo bez znaménka 1 bajt (data souboru)
IDF_FILE_WORDS,				"integer number with sign, 2 bytes",																// celé èíslo se znaménkem 2 bajty (data souboru)
IDF_FILE_WORDU,				"integer number without sign, 2 bytes",																// celé èíslo bez znaménka 2 bajty (data souboru)
IDF_FILE_DWORDS,			"integer number with sign, 4 bytes",																// celé èíslo se znaménkem 4 bajty (data souboru)
IDF_FILE_DWORDU,			"integer number without sign, 4 bytes",																// celé èíslo bez znaménka 4 bajty (data souboru)
IDF_FILE_FLOAT,				"decimal number, 4 bytes",																			// desetinné èíslo 4 bajty (data souboru)
IDF_FILE_DOUBLE,			"decimal number, 8 bytes",																			// desetinné èíslo 8 bajtù (data souboru)
IDF_FILE_TEXT0,				"text terminated by binar null (ASCIIZ)",															// text zakonèenı binární nulou ASCIIZ (data souboru)
IDF_FILE_TEXTCR,			"text terminated by end of line",																	// text zakonèenı koncem øádku (data souboru)
IDF_FILE_TEXTN,				"text with fixed length",																			// text s pevnou délkou (data souboru)
IDF_FILE_ICON,				"item (ICO)",																						// pøedmìt ICO (data souboru)
IDF_FILE_PICTURE,			"picture (BMP, JPG)",																				// obrázek BMP, JPG (data souboru)
IDF_FILE_SOUND,				"sound (WAV, MP3)",																					// zvuk WAV, MP3 (data souboru)
IDF_FILE_MUSIC,				"music (MID, RMI)",																					// hudba MID, RMI (data souboru)
IDF_FILE_READOFF,			"read pointer",																						// ukazatel ètení ze vstupního souboru
IDF_FILE_WRITEOFF,			"write pointer",																					// ukazatel zápisu do vıstupního souboru
IDF_DATETIME_GROUP,			"date and time",																					// skupina prvkù pro práci s datem a èasem
IDF_DATETIME_CURRENT,		"actual date and time (number of seconds since January 1, 1601)",									// aktuální datum a èas
IDF_DATETIME_UTC,			"convert local time to world time",																	// funkce pro konverzi místního èasu na svìtovı UTC
IDF_DATETIME_LOCAL,			"convert world time to local time",																	// funkce pro konverzi svìtového èasu UTC na místní
IDF_DATETIME_COMP,			"merge components of date and time",																// funkce pro slouèení poloek data a èasu
IDF_DATETIME_COMP_YEAR,		"year",																								// rok pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MONTH,	"month",																							// mìsíc pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_DAY,		"day",																								// den pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_HOUR,		"hour",																								// hodina pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MINUTE,	"minute",																							// minuta pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_SECONDE,	"second",																							// sekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_COMP_MSECONDE,	"millisecond",																						// milisekunda pro funkci slouèení poloek data a èasu
IDF_DATETIME_GET_YEAR,		"year from date and time",																			// získání poloky roku z data a èasu
IDF_DATETIME_GET_MONTH,		"month from date and time",																			// získání poloky mìsíce z data a èasu
IDF_DATETIME_GET_DAY,		"day from date and time",																			// získání poloky dne z data a èasu
IDF_DATETIME_GET_WEEK,		"day of week from date and time (0 = sunday, 1 = monday, ...)",										// získání poloky dne v tıdnu z data a èasu
IDF_DATETIME_GET_HOUR,		"hour from date and time",																			// získání poloky hodiny z data a èasu
IDF_DATETIME_GET_MINUTE,	"minute from date and time",																		// získání poloky minuty z data a èasu
IDF_DATETIME_GET_SECONDE,	"second from date and time",																		// získání poloky sekundy z data a èasu
IDF_DATETIME_GET_MSECONDE,	"millisecond from date and time",																	// získání poloky milisekundy z data a èasu
IDF_DATETIME_DATEEUR,		"convert date to text \"day.month.year\"",															// funkce pro konverzi data na text v evropském formátu
IDF_DATETIME_DATEUSA,		"convert date to text \"month/day/year\"",															// funkce pro konverzi data na text v americkém formátu
IDF_DATETIME_DATEJAP,		"convert date to text \"year-month-day\"",															// funkce pro konverzi data na text v japonském formátu
IDF_DATETIME_TIME24,		"convert time to text \"hour:minute:second\" (24 hours)",											// funkce pro konverzi èasu na text s formátem 24 hodin
IDF_DATETIME_TIME12,		"convert time to text \"hour:minute:second x\" (12 hours)",											// funkce pro konverzi èasu na text s formátem 12 hodin
IDF_FILE_SIZE,				"size of file",																						// velikost souboru
IDF_FILE_ERROR,				"operation error flag",																				// pøíznak chyby souborové operace
IDF_FILE_TEXTN_LEN,			"length of text with fixed length",																	// nastavení délky textu s pevnou délkou (data souboru)
IDF_FILE_DISK_TYPE,			"disk type (2=FD, 3=HD, 4=NET, 5=CD, 6=RAM)",														// zjištìní typu disku
IDF_TEXT_FORMAT2,			"convert number to text - 2 digits",																// funkce pro pøevod èísla na textovı tvar vyjádøenı 2 èíslicemi (0 a 99)
IDF_TEXT_FORMATH,			"convert number to text - 8 HEX digits",															// funkce pro pøevod èísla na textovı tvar vyjádøenı 8 hexadecimálními èíslicemi
IDF_FILE_3BYTES,			"integer number with sign, 3 bytes",																// celé èíslo se znaménkem 3 bajty (data souboru)
IDF_FILE_3BYTEU,			"integer number without sign, 3 bytes",																// celé èíslo bez znaménka 3 bajty (data souboru)
IDF_DIALOG_GROUP,			"dialogs",																							// skupina prvkù pro dialogová okna
IDF_DIALOG_BOX,				"confirmation dialog (return 1=OK, 2=Cancel, 3=Abort, 4=Retry, 5=Ignore, 6=Yes, 7=No)",				// potvrzovací dialog
IDF_DIALOG_BOX_TEXT,		"text",																								// text pro zobrazení v potvrzovacím dialogu
IDF_DIALOG_BOX_CAPTION,		"caption",																							// nadpis okna potvrzovacího dialogu
IDF_DIALOG_BOX_ICON,		"icon (0=none, 1=error, 2=question, 3=warning, 4=information)",										// ikona potvrzovacího dialogu
IDF_DIALOG_BOX_BUTTON,		"buttons (0=OK, 1=OK/Cancel, 2=Abort/Retry/Ignore, 3=Yes/No/Cancel, 4=Yes/No, 5=Retry/Cancel)",		// tlaèítka potvrzovacího dialogu
IDF_DIALOG_BOX_DEFAULT,		"default button (1 to 3)",																			// implicitní tlaèítko potvrzovacího dialogu
IDF_TEXT_CRLF,				"next line",																						// textová konstanta - další øádek (CR/LF)
IDF_DIALOG_TEXT,			"enter text",																						// dialog pro zadání textu
IDF_DIALOG_TEXT1,			"1st line of message",																				// 1. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT2,			"2nd line of message",																				// 2. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT3,			"3rd line of message",																				// 3. øádek vızvy k zobrazení v dialogu zadání textu
IDF_DIALOG_TEXT_PAR,		"prepared text to enter",																			// pøednastavenı text k zadání v dialogu zadání textu
IDF_CD_EJECT,				"eject CD",																							// vysunutí CD (EJECT)
IDF_SOUND_BIT,				"number of bits per sample (8 or 16)",																// funkce zjištìní poètu bitù na vzorek zvuku
IDF_SOUND_FREQ,				"sample frequency (Hz)",																			// funkce zjištìní vzorkovacího kmitoètu zvuku
IDF_SOUND_STEREO,			"is sound stereophonic?",																			// funkce testu, zda je zvuk stereofonní
IDF_SOUND_LENGTH,			"length of sound (seconds)",																		// funkce zjištìní délky zvuku
IDF_SOUND_CONV_8BIT,		"convert to 8 bits",																				// funkce pro konverzi zvuku na vzorek 8 bitù
IDF_SOUND_CONV_16BIT,		"convert to 16 bits",																				// funkce pro konverzi zvuku na vzorek 16 bitù
IDF_SOUND_CONV_STEREO,		"convert to stereo",																				// funkce pro konverzi zvuku na stereofonní
IDF_SOUND_CONV_MONO,		"convert to mono",																					// funkce pro konverzi zvuku na monofonní
IDF_SOUND_CONV_11025,		"convert to 11 kHz",																				// funkce pro konverzi zvuku na frekvenci 11 kHz
IDF_SOUND_CONV_22050,		"convert to 22 kHz",																				// funkce pro konverzi zvuku na frekvenci 22 kHz
IDF_SOUND_CONV_44100,		"convert to 44 kHz",																				// funkce pro konverzi zvuku na frekvenci 44 kHz
IDF_SOUND_ADD,				"merge of sounds",																					// operátor pro slouèení zvukù
IDF_SOUND_SPEED,			"change speed of sound",																			// funkce pro konverzi rychlosti zvuku
IDF_SOUND_INPUT,			"sound to conversion",																				// zvuk ke konverzi pro funkci konverze rychlosti zvuku
IDF_SOUND_SPEED_K,			"relative change of speed (1 = unchanging)",														// poadovaná zmìna rychlosti pro funkci konverze rychlosti zvuku
IDF_TONGEN,					"tone generator",																					// tónovı sinusovı generátor k vygenerování zvuku stálého tónu
IDF_TONGEN_F,				"frequency of tone (Hz)",																			// frekvence tónu pro tónovı generátor
IDF_TONGEN_T,				"length of tone (seconds)",																			// délka tónu pro tónovı generátor
IDF_MAP_GROUP,				"sheet",																							// skupina prvkù pro práci s plochou
IDF_MAP_WIDTH,				"width of sheet",																					// zjištìní šíøky plochy
IDF_MAP_HEIGHT,				"height of sheet",																					// zjištìní vıšky plochy
IDF_MAP_X,					"X coordinate",																						// souøadnice X pro funkce naètení prvku z plochy
IDF_MAP_Y,					"Y coordinate",																						// souøadnice Y pro funkce naètení prvku z plochy
IDF_MAP_INPUT,				"sheet",																							// vstupní plocha pro funkce naètení prvku z plochy
IDF_MAP_ICON,				"item",																								// funkce pro zjištìní pøedmìtu z plochy
IDF_MAP_NUM1,				"numeric value 1 (range 0 to 1023)",																// funkce pro zjištìní èíselné hodnoty 1 z plochy
IDF_MAP_NUM2,				"numeric value 2 (range 0 to 1023)",																// funkce pro zjištìní èíselné hodnoty 2 z plochy
IDF_MAP_NUM3,				"numeric value 3 (range 0 to 127)",																	// funkce pro zjištìní èíselné hodnoty 3 z plochy
IDF_MAP_SWC1,				"flag 1",																							// funkce pro zjištìní pøepínaèe 1 z plochy
IDF_MAP_SWC2,				"flag 2",																							// funkce pro zjištìní pøepínaèe 2 z plochy
IDF_MAP_SWC3,				"flag 3",																							// funkce pro zjištìní pøepínaèe 3 z plochy
IDF_MAP_SWC4,				"flag 4",																							// funkce pro zjištìní pøepínaèe 4 z plochy
IDF_MAP_SWC5,				"flag 5",																							// funkce pro zjištìní pøepínaèe 5 z plochy
IDF_MAP_COPY,				"copy cutout from the sheet",																		// kopie èásti plochy do jiné plochy
IDF_MAP_COPY_INPUT,			"sheet with cutout",																				// plocha s vıøezem pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_X,				"X coordinate of cutout",																			// souøadnice X vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_Y,				"Y coordinate of cutout",																			// souøadnice Y vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_W,				"cutout width",																						// šíøka vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_MAP_COPY_H,				"cutout height",																					// vıška vıøezu pro funkci kopírování vıøezu plochy do jiné plochy
IDF_CONSOLE_GROUP,			"console",																							// skupina prvkù pro práci s konzolou
IDF_SPRITE_SHIFT_X,			"move of all sprites in X direction",																// hromadnı posun sprajtù ve smìru X
IDF_SPRITE_SHIFT_Y,			"move of all sprites in Y direction",																// hromadnı posun sprajtù ve smìru Y
IDF_SPRITE_WIN_X1,			"left edge of sprites window",																		// levı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y1,			"lower edge of sprites window",																		// dolní okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_X2,			"right edge of sprites window",																		// pravı okraj okna pro zobrazení sprajtù
IDF_SPRITE_WIN_Y2,			"upper edge of sprites window",																		// horní okraj okna pro zobrazení sprajtù
IDF_CONSOLE_ON,				"console mode (must be used at the main function beginning)",										// zapnutí reimu konzoly
IDF_CONSOLE_OUT,			"text output to console",																			// vıstup textu na konzolu (STDOUT)
IDF_CONSOLE_IN,				"text input from console",																			// vstup textu z konzoly (STDIN)
IDF_CONSOLE_ERR,			"error text output to console",																		// chybovı vıstup textu na konzolu (STDERROUT)
IDF_COMMAND_PAR,			"program parameter (0 = program name)",																// funkce pro zjištìní jednoho parametru programu (zadaného z pøíkazového øádku)
IDF_EXEC_NAME,				"program name with full path",																		// jméno tohoto programu s plnou cestou
IDF_EXEC,					"program execution",																				// spuštìní zadaného programu bez èekání na dokonèení
IDF_EXEC_WAIT,				"program execution with waiting",																	// spuštìní zadaného programu s èekáním na dokonèení a s návratem kódu
IDF_JOYSTICK_GROUP,			"joystick",																							// skupina prvkù pro práci s joystickem
IDF_JOYSTICK_X,				"X coordinate of joystick",																			// souøadnice X joysticku
IDF_JOYSTICK_Y,				"Y coordinate of joystick",																			// souøadnice Y joysticku
IDF_JOYSTICK_Z,				"Z coordinate of joystick",																			// souøadnice Z joysticku
IDF_JOYSTICK_1,				"button 1 of joystick",																				// tlaèítko 1 joysticku
IDF_JOYSTICK_2,				"button 2 of joystick",																				// tlaèítko 2 joysticku
IDF_JOYSTICK_3,				"button 3 of joystick",																				// tlaèítko 3 joysticku
IDF_JOYSTICK_4,				"button 4 of joystick",																				// tlaèítko 4 joysticku
IDF_WINDOWNEW_GROUP,		"texts and pictures",																				// skupina dialogovıch prvkù texty a obrázky
IDF_WINDOW_ID,				"element number (0 = main window)",																	// èíslo aktivního prvku dialogového okna
IDF_WINDOW_DEL,				"delete element/window",																			// zrušení prvku dialogového okna
IDF_WINDOW_NEW,				"create window",																					// vytvoøení dialogového okna
IDF_WINDOW_X,				"horizontal coordinate",																			// horizontální souøadnice prvku v dialogovém oknì
IDF_WINDOW_Y,				"vertical coordinate",																				// vertikální souøadnice prvku v dialogovém oknì
IDF_WINDOW_W,				"width",																							// šíøka prvku dialogového okna
IDF_WINDOW_H,				"height",																							// vıška prvku dialogového okna
IDF_WINDOW_TEXT,			"text",																								// text prvku dialogového okna
IDF_WINDOW_VISIBLE,			"visible",																							// viditelnost prvku dialogového okna
IDF_WINDOW_DISABLE,			"disable",																							// zákaz prvku dialogového okna
IDF_BUTTON_NEW,				"create button",																					// vytvoøení tlaèítka v dialogovém oknì (BUTTON)
IDF_BUTTON_CLICK,			"button press or element change",																	// stisk tlaèítka nebo zmìna prvku dialogového okna
IDF_BUTTONCHECK_NEW,		"create check box",																					// vytvoøení zaškrtávacího boxu dialogového okna (CHECKBOX)
IDF_EDIT_NEW,				"create edit line",																					// vytvoøení editaèního øádku dialogového okna (EDIT)
IDF_BUTTONRADIO_NEW,		"create switch",																					// vytvoøení pøepínaèe dialogového okna (RADIOBUTTON)
IDF_WINDOWPAR_GROUP,		"functions common for all elements",																// skupina prvkù pro øízení prvkù dialogového okna
IDF_MEMO_NEW,				"create edit field",																				// vytvoøení editaèního pole dialogového okna (MEMO)
IDF_WINCONTROL_GROUP,		"buttons",																							// skupina prvkù pro vytváøení tlaèítek dialogového okna
IDF_CHECKBOX_ON,			"switch on/off",																					// pøíznak zapnutí pøepínaèe dialogového okna (CHECK)
IDF_FOCUS,					"input focus",																						// prvek dialogového okna se vstupním zamìøením (FOCUS)
IDF_DEFBUTTON_NEW,			"create default button",																			// vytvoøení implicitního tlaèítka dialogového okna (DEFAULT BUTTON)
IDF_BUTTONICON_NEW,			"create icon button",																				// vytvoøení ikonového tlaèítka dialogového okna
IDF_GROUPBOX_NEW,			"create frame",																						// vytvoøení rámeèku v dialogovém oknì
IDF_LISTBOX_NEW,			"create listbox",																					// vytvoøení bìného seznamu v dialogovém oknì (SIMPLE LISTBOX)
IDF_WINTEXT_NEW,			"create text",																						// vytvoøení textu v dialogovém oknì (STATIC TEXT)
IDF_COMBOBOX_NEW,			"create drop-down listbox",																			// vytvoøení rozbalovacího seznamu v dialogovém oknì (DROPDOWN LISTBOX)
IDF_COMBOEDIT_NEW,			"create drop-down listbox with edit",																// vytvoøení rozbalovacího seznamu s editací v dialogovém oknì (DROPDOWN COMBOBOX)
IDF_FONTBOLD,				"bold",																								// zvıraznìné písmo prvku dialogového okna (BOLD)
IDF_FONTFIXED,				"fixed pitch",																						// písmo s pevnou rozteèí prvku dialogového okna (COURIER)
IDF_BUTTONRADIO_NEW2,		"create switch - group beginning",																	// vytvoøení prvního pøepínaèe skupiny pøepínaèù v dialogovém oknì (RADIOBUTTON)
IDF_WINDOWLIST_GROUP,		"listboxes",																						// skupina prvkù pro práci se seznamy v dialogovém oknì
IDF_LISTBOX_ADD,			"add entry to listbox",																				// pøidání poloky do seznamu dialogového okna (LISTBOX atd.)
IDF_LISTBOX_CLEAR,			"empty of listbox",																					// vyprázdnìní seznamu dialogového okna (LISTBOX)
IDF_LISTEDIT_NEW,			"create listbox with edit",																			// vytvoøení seznamu s editací v dialogovém oknì (COMBOBOX)
IDF_BUTTON3_NEW,			"create 3-state checkbox",																			// vytvoøení 3-stavového boxu v dialogovém oknì (3-STATE CHECKBOX)
IDF_BUTTON3_ON,				"switch in undefined state",																		// pøíznak neurèitého stavu tlaèítka dialogového okna
IDF_WINDOWRO_NEW,			"create window without closing possibility",														// vytvoøení dialogového okna bez monosti uzavøení
IDF_WINDOW_ICON,			"icon",																								// ikona prvku dialogového okna
IDF_WINICON_NEW,			"create icon",																						// vytvoøení prvku zobrazení ikony v dialogovém oknì
IDF_FILE_SPRITE,			"sprite (SPR)",																						// sprajt (data ze souboru)
IDF_2PI,					"2*pi (= 360 degrees)",																				// 2*pi (2*Ludolfovo èíslo)
IDF_BOD32,					"distance of 1 pixel (= 1/32)",																		// èíselná konstanta vzdálenosti 1 grafického bodu
IDF_M1,						"-1",																								// èíselná konstanta èísla -1
IDF_SPRITE_FAZE,			"phase",																							// fáze sprajtu
IDF_SPRITE_STATUS,			"state",																							// stav sprajtu (stavovı indikátor)
IDF_FULLSCREEN,				"full screen mode",																					// ovládání celoobrazovkového reimu (FULLSCREEN)
IDF_KLAV_FLUSH,				"flush out of key buffer",																			// vyprázdnìní zásobníku kláves (FLUSH)
IDF_SOUND_POS,				"position in playing sound",																		// pozice v pøehrávání zvuku
IDF_SOUND_PAUSE,			"pause/continue playing sound",																		// pozastavit/pokraèovat v pøehrávání zvuku (PAUSE)
IDF_FILE_LIST,				"file list",																						// zjištìní seznamu souborù zadanıch pomocí masky
IDF_EQU_MAP,				"sheet identity",																					// operátor porovnání ploch
IDF_EQU_PIC,				"picture identity",																					// operátor porovnání obrázkù
IDF_EQU_SPR,				"sprite identity",																					// operátor porovnání sprajtù
IDF_EQU_SND,				"sound identity",																					// operátor porovnání zvukù
IDF_EQU_MUS,				"music identity",																					// operátor porovnání hudeb
IDF_NET_GROUP,				"communication",																					// skupina pro obsluhu komunikací
IDF_DIRECTPLAY_GROUP,		"net support DirectPlay",																			// skupina pro obsluhu herní sítì DirectPlay
IDF_CONNECT_LIST,			"list of connections",																				// seznam monıch spojení DirectPlay
IDF_CONNECT_ACT,			"active connection",																				// aktivní spojení DirectPlay
IDF_GAME_LIST,				"list of games",																					// seznam bìících her DirectPlay
IDF_GAME_ACT,				"active game",																						// aktivní hra DirectPlay
IDF_PLAYER_LIST,			"list of players",																					// seznam zapojenıch hráèù DirectPlay
IDF_PLAYER_ACT,				"active player",																					// aktivní hráè DirectPlay
IDF_GAME_N1,				"numeric game parameter 1 (-16384 to +16383)",														// èíselnı parametr 1 hry DirectPlay
IDF_GAME_N2,				"numeric game parameter 2 (-16384 to +16383)",														// èíselnı parametr 2 hry DirectPlay
IDF_GAME_N3,				"numeric game parameter 3 (-16384 to +16383)",														// èíselnı parametr 3 hry DirectPlay
IDF_GAME_N4,				"numeric game parameter 4 (-16384 to +16383)",														// èíselnı parametr 4 hry DirectPlay
IDF_GAME_N5,				"numeric game parameter 5 (-16384 to +16383)",														// èíselnı parametr 5 hry DirectPlay
IDF_GAME_N6,				"numeric game parameter 6 (-16384 to +16383)",														// èíselnı parametr 6 hry DirectPlay
IDF_GAME_N7,				"numeric game parameter 7 (-16384 to +16383)",														// èíselnı parametr 7 hry DirectPlay
IDF_GAME_N8,				"numeric game parameter 8 (-16384 to +16383)",														// èíselnı parametr 8 hry DirectPlay
IDF_GAME_L1,				"game flag 1",																						// pøepínaè 1 hry DirectPlay
IDF_GAME_L2,				"game flag 2",																						// pøepínaè 2 hry DirectPlay
IDF_GAME_L3,				"game flag 3",																						// pøepínaè 3 hry DirectPlay
IDF_GAME_L4,				"game flag 4",																						// pøepínaè 4 hry DirectPlay
IDF_GAME_L5,				"game flag 5",																						// pøepínaè 5 hry DirectPlay
IDF_GAME_L6,				"game flag 6",																						// pøepínaè 6 hry DirectPlay
IDF_GAME_L7,				"game flag 7",																						// pøepínaè 7 hry DirectPlay
IDF_GAME_L8,				"game flag 8",																						// pøepínaè 8 hry DirectPlay
IDF_GAME_GROUP,				"game setup",																						// skupina pro nastavení parametrù hry
IDF_GAME_HOST,				"host (control computer)",																			// pøíznak, e poèítaè je hostitel DirectPlay
IDF_PLAYER_MAX,				"maximum of players (0 = unlimited)",																// maximální poèet hráèù DirectPlay
IDF_PLAYER_INX,				"active player number (-1 = none)",																	// èíslo aktivního hráèe DirectPlay
IDF_GAME_DATA_GROUP,		"data",																								// skupina pro pøenos dat DirectPlay
IDF_GAME_PACKET,			"data block send/receive (-1 = to all/none)",														// obsluha pøenosu dat DirectPlay
IDF_GAME_DATAN,				"number",																							// èíslo dat DirectPlay
IDF_GAME_DATAT,				"text",																								// text dat DirectPlay
IDF_GAME_DATAL,				"flag",																								// pøepínaè dat DirectPlay
IDF_GAME_IP,				"IP address of this computer",																		// zjištìní IP adresy poèítaèe
IDF_GAME_DATAB,				"integer number 0 to 255 (byte)",																	// èíslo bajt dat DirectPlay
IDF_INC,					"increment (adds 1)",																				// funkce inkrementace èísla
IDF_DEC,					"decrement (subtracts 1)",																			// funkce dekrementace èísla
IDF_WINTEXT_NEW_CENTER,		"create centered text",																				// vytvoøení centrovaného textu v dialogovém oknì
IDF_BUTTON_ESC,				"button for Esc key (-1 = none)",																	// prvek dialogového okna obsluhující klávesu Esc
IDF_PICTURE_WIDTH,			"picture width",																					// funkce zjištìní šíøky obrázku
IDF_PICTURE_HEIGHT,			"picture height",																					// funkce zjištìní vıšky obrázku
IDF_PICTURE_XFLIP,			"horizontal flip of picture",																		// funkce pro horizontální pøevrácení obrázku (podle osy ve smìru Y)
IDF_PICTURE_YFLIP,			"vertical flip of picture",																			// funkce pro vertikální pøevrácení obrázku (podle osy ve smìru X)
IDF_PICTURE_GROUP,			"pictures",																							// skupina prvkù pro práci s obrázky
IDF_PICTURE_ZOOM,			"change picture size",																				// funkce pro zmìnu velikosti obrázku
IDF_PICTURE_ZOOM_PIC,		"picture",																							// obrázek pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_WIDTH,		"width (default = proportional to height)",															// šíøka pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_HEIGHT,	"height (default = proportional to width)",															// vıška pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_INT,		"refine edges",																						// pøíznak zjemnìní hran pro funkci zmìny velikosti obrázku
IDF_PICTURE_ZOOM_DITH,		"dithering (photograph)",																			// pøíznak ditheringu pro funkci zmìny velikosti obrázku
IDF_GRAPHIC_GROUP,			"drawing",																							// skupina prvkù pro grafiku (kreslení)
IDF_WINPIC_NEW,				"create picture",																					// vytvoøení prvku obrázku v dialogovém oknì
IDF_WINDOW_PIC,				"picture",																							// obrázek prvku dialogového okna
IDF_RICHEDIT_NEW,			"create RichEdit editor",																			// vytvoøení editaèního pole RichEdit v dialogovém oknì
IDF_FONTHEIGHT,				"height of characters (0 = usual)",																	// vıška znakù textu prvku dialogového okna
IDF_FONTITALIC,				"italic",																							// šikmé písmo textu prvku dialogového okna (ITALIC)
IDF_FONTUNDER,				"underline",																						// podtrené písmo textu prvku dialogového okna (UNDERLINE)
IDF_FONTSTRIKE,				"strike out",																						// pøeškrtnuté písmo textu prvku dialogového okna (OVERSTRIKE)
IDF_FONTSERIF,				"serifs",																							// patièkové písmo textu prvku dialogového okna (SERIF)
IDF_FONTWIDTH,				"relative width of characters (0 = usual, 1 = basic)",												// relativní šíøka znakù textu prvku dialogového okna
IDF_FONTANGLE,				"text slope angle",																					// úhel sklonu textu prvku dialogového okna
IDF_WINTEXT_NEW_RIGHT,		"create right aligned text",																		// vytvoøení textu zarovnaného vpravo v dialogovém oknì
IDF_FONTCOL,				"character color",																					// barva písma textu prvku dialogového okna
IDF_FONTBACK,				"background color",																					// barva pozadí textu prvku dialogového okna (BACKGROUND)
IDF_FONTGROUP,				"font of element",																					// skupina pro ovládání písma prvku dialogového okna
IDF_SOUND_PLAY_SPEED,		"speed of playing (1 = usual)",																		// rychlost pøehrávání zvuku (parametr pøíkazu pro pøehrávání zvuku)
IDF_SOUND_DISTINGUISH,		"distinguish code (0 to 65535)",																	// rozlišovací kód zvuku
IDF_DIALOG_OPEN,			"enter file to open",																				// dialog zadání souboru k otevøení
IDF_DIALOG_SAVE,			"enter file to save",																				// dialog zadání souboru k uloení
IDF_DIALOG_FIND,			"enter text to find",																				// dialog zadání textu k hledání (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_COLOR,			"enter color",																						// dialog zadání barvy (rezervováno, v souèasné verzi nepouito)
IDF_DIALOG_EXT,				"file mask",																						// seznam masek souborù pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_NAME,			"prepared file name",																				// pøednastavené jméno souboru pro dialogy zadání souboru k otevøení a uloení
IDF_DIALOG_FILES,			"files type name",																					// seznam názvù souborù pro dialogy zadání souboru k otevøení a uloení
IDF_PICTURE_LEVEL,			"change brightness of picture",																		// funkce zmìny jasu obrázku
IDF_PICTURE_LEVEL_PIC,		"picture to change brightness",																		// obrázek pro funkci zmìny jasu obrázku
IDF_PICTURE_LEVEL_N,		"picture brightness (1 = usual)",																	// poadovanı jas obrázku funkce zmìny jasu obrázku
IDF_PICTURE_ROTATE,			"rotate picture",																					// funkce pro rotaci obrázku
IDF_PICTURE_ROTATE_PIC,		"picture to be rotated",																			// obrázek pro funkci rotace obrázku
IDF_PICTURE_ROTATE_ANGLE,	"angle of rotation",																				// úhel otoèení pro funkci rotace obrázku
IDF_SOUND_CONV_PCM,			"sound decompression",																				// dekomprese zvuku na formát PCM
IDF_FILE_TEXT_UNICODE,		"text is in UNICODE format (2 bytes)",																// pøíznak textu ve formátu UNICODE (data souboru)
IDF_MAP_PICTURE,			"convert sheet to picture",																			// funkce pro konverzi plochy na obrázek
IDF_ICON_PICTURE,			"convert item to picture",																			// funkce pro konverzi pøedmìtu na obrázek
IDF_BIT_GROUP,				"bit operations",																					// skupina bitovıch (binárních) operací
IDF_BIT_AND,				"AND bit product",																					// bitovı (binární) souèin AND
IDF_BIT_OR,					"OR bit sum",																						// bitovı (binární) souèet OR
IDF_BIT_XOR,				"XOR bit inversion",																				// bitová (binární) inverze XOR
IDF_BIT_NOT,				"NOT bit complement",																				// bitovı (binární) doplnìk NOT
IDF_BIT_MAX,				"maximum bit number (doubleword)",																	// konstanta - maximální bitové (binární) èíslo, dvojslovo
IDF_BIT_LEFT,				"bit rotate left",																					// bitová (binární) rotace vlevo
IDF_BIT_RIGHT,				"bit rotate right",																					// bitová (binární) rotace vpravo
IDF_MOUSE_ITEM,				"test mouse in element",																			// test myši, zda se nachází nad zadanım prvkem dialogového okna
IDF_WINDOW_W_INT,			"internal width",																					// vnitøní šíøka prvku dialogového okna (klientská šíøka)
IDF_WINDOW_H_INT,			"internal height",																					// vnitøní vıška prvku dialogového okna (klientská vıška)
IDF_CODEPAGE,				"character set (1250=easteurope, 1251=russian, 1252=west)",											// èíslo pouité znakové sady fontù
IDF_USERFONT,				"user font",																						// jméno uivatelského fontu
IDF_ENUMFONTS,				"font list",																						// zjištìní seznamu systémovıch fontù
IDF_MAP_NEW,				"new sheet",																						// vytvoøení nové plochy
IDF_MAP_NEW_W,				"width of sheet",																					// šíøka nové plochy
IDF_MAP_NEW_H,				"height of sheet",																					// vıška nové plochy
IDF_WINDOW_TOP,				"always on top",																					// pøíznak okna, které je vdy nahoøe
IDF_VZOR2,					"[CD-ROM]",																							// název vzorového adresáøe v knihovnì CD-ROM
IDF_ALIAS,					"nickname (alias)",																					// !!! pøezdívka (alias) souboru nebo sloky
IDF_COM_GROUP,				"communication port",																				// skupina pro obsluhu komunikaèních portù
IDF_COM_OPEN,				"open port (-1=error)",																				// pøíkaz k otevøení komunikaèního portu
IDF_COM_CLOSE,				"close port",																						// pøíkaz k zavøení komunikaèního portu
IDF_COM_ID,					"active port",																						// aktivní port
IDF_COM_NUM,				"number (0 to 255)",																				// vstup/vıstup èísla
IDF_COM_TEXT,				"character (text)",																					// vstup/vıstup znaku
IDF_COM_BAUD,				"baud rate",																						// pøenosová rychlost
IDF_COM_STOP,				"2 stop bits",																						// reim s 2 stopbity
IDF_COM_BITS,				"number of bits (5 to 8)",																			// poèet bitù na znak
IDF_COM_PARIT,				"parity (0=none, 1=odd, 2=even)",																	// zvolená parita
IDF_COM_IN,					"character was received",																			// byl pøijatı znak
IDF_COM_SEND,				"sending is allowed (CTS, RTS)",																	// povoleno vysílání
IDF_COM_RECEIVE,			"receiving is allowed (DSR, DTR)",																	// povolen pøíjem
IDF_PICTURE_MASK,			"picture masking",																					// funkce k maskování obrázku
IDF_PICTURE_MASK_PIC,		"picture",																							// obrázek k maskování obrázku
IDF_PICTURE_MASK_MASK,		"mask",																								// maska k maskování obrázku
IDF_GRAPH_AREA_WIDTH,		"field width to display text (0 = none)",															// šíøka pole k centrování vypisovaného textu
IDF_RICHMEMO_NEW,			"create edit field without wrap",																	// vytvoøení editaèního pole dialogového okna bez zalamování øádku (RICHMEMO)
IDF_WINDOW_RESIZABLE,		"resizable window",																					// dialogové okno má mìnitelnou velikost
IDF_WINDOW_MAY_CLOSE,		"window may be closed",																				// povolení/zákaz uzavøení dialogového okna
IDF_WINDOW_MAXIM,			"window is maximized",																				// maximalizace okna
IDF_WINDOW_MINIM,			"window is minimized",																				// minimalizace okna
IDF_PROGRESS_NEW,			"create progressbar",																				// vytvoøení dialogového prvku indikátoru prùbìhu (progressbar)
IDF_HTRACKBAR_NEW,			"create horizontal trackbar",																		// vytvoøení dialogového prvku horizontálního jezdce (trackbar)
IDF_VTRACKBAR_NEW,			"create vertical trackbar",																			// vytvoøení dialogového prvku vertikálního jezdce (trackbar)
IDF_WINDOW_POS,				"actual position",																					// aktuální pozice v dialogovém prvku
IDF_MIX_GROUP,				"mixer device",																						// skupina mixáního zaøízení
IDF_MIX_DEVICE,				"mixer device",																						// volba smìšovacího zaøízení
IDF_MIX_LINE_DST,			"destination line",																					// volba cílového signálu
IDF_MIX_LINE_SRC,			"source line (none=only destination line)",															// volba zdrojového signálu
IDF_MIX_LINE_TYPE,			"type of line",																						// zjištìní typu signálu
IDF_MIX_CONTROL,			"control item",																						// volba ovládacího prvku
IDF_MIX_CONTROL_TYPE,		"type of control item",																				// zjištìní typu prvku
IDF_MIX_CONTROL_VAL,		"value of control item (0 to 1)",																	// nastavení hodnoty prvku
IDF_MIX_CONTROL_LIST,		"selection of item value",																			// vıbìr hodnoty prvku
IDF_MIX_CHANNEL,			"controlled channel (-1=all)",																		// volba ovládaného kanálu
IDF_DIRECT3D_GROUP,			"3D graphics",																						// skupina grafiky Direct3D
IDF_DIRECT3D_VIEW,			"3D graphics window",																				// definice okna Direct3D
IDF_DIRECT3D_VIEW_X,		"X coordinate of 3D graphics window",																// definice souøadnice X okna Direct3D
IDF_DIRECT3D_VIEW_Y,		"Y coordinate of 3D graphics window",																// definice souøadnice Y okna Direct3D
IDF_DIRECT3D_VIEW_W,		"width of 3D graphics window",																		// definice šíøky okna Direct3D
IDF_DIRECT3D_VIEW_H,		"height of 3D graphics window",																		// definice vıšky okna Direct3D
IDF_DIRECT3D_MODE_LIST,		"videomode (width*height/bits)",																	// seznam/vıbìr videomódù
IDF_DIALOG_GRAPHIC,			"graphic background",																				// zapnuto grafické pozadí dialogovıch oken
IDF_DIRECT3D_SETTING_GROUP,	"settings",																							// skupina nastavení Direct3D
IDF_DIRECT3D_WIREFRAME,		"filling surfaces",																					// mód vyplòování
IDF_DIRECT3D_LIGHTON,		"lighting",																							// mód osvìtlení
IDF_DIRECT3D_SHADES,		"smooth shading",																					// mód stínování
IDF_DIRECT3D_INVERT,		"object inversion",																					// invertovat objekt (pøevrátit "naruby")
IDF_DIRECT3D_OBJECTS_GROUP,	"objects",																							// skupina objektù Direct3D
IDF_DIRECT3D_WALL,			"wall",																								// vytvoøení stìny
IDF_DIRECT3D_CUBE,			"cube",																								// vytvoøení krychle
IDF_DIRECT3D_SPHERE,		"sphere",																							// vytvoøení koule
IDF_DIRECT3D_CYLINDER,		"cylinder",																							// vytvoøení válce
IDF_DIRECT3D_CONE,			"cone",																								// vytvoøení kuele
IDF_DIRECT3D_CLONE,			"clone",																							// vytvoøení klonu
IDF_DIRECT3D_TEXT,			"object from text",																					// vytvoøení objektu z textu
IDF_DIRECT3D_FILE,			"object from file",																					// vytvoøení objektu ze souboru
IDF_DIRECT3D_OBJECT_ID,		"active object (0=scene, 1=camera, 2=light)",														// aktivní objekt k manipulaci
IDF_DIRECT3D_OBJECT_DELETE,	"delete object",																					// zrušení objektu
IDF_DIRECT3D_VISIBLE,		"visible",																							// zviditelnìní objektu
IDF_DIRECT3D_LINK,			"link",																								// pøipojení jiného objektu
IDF_DIRECT3D_SAVE,			"object to file",																					// uloení objektu do souboru
IDF_DIRECT3D_TRANS_GROUP,	"transformations",																					// transformace objektù
IDF_DIRECT3D_SCALEX,		"scale in X direction",																				// nastavení mìøítka ve smìru X
IDF_DIRECT3D_SCALEY,		"scale in Y direction",																				// nastavení mìøítka ve smìru Y
IDF_DIRECT3D_SCALEZ,		"scale in Z direction",																				// nastavení mìøítka ve smìru Z
IDF_DIRECT3D_ROTATEX,		"rotation around X-axis",																			// nastavení rotace podle osy X
IDF_DIRECT3D_ROTATEY,		"rotation around Y-axis",																			// nastavení rotace podle osy Y
IDF_DIRECT3D_ROTATEZ,		"rotation around Z-axis",																			// nastavení rotace podle osy Z
IDF_DIRECT3D_TRANSX,		"translation in X direction",																		// nastavení posunu ve smìru X
IDF_DIRECT3D_TRANSY,		"translation in Y direction",																		// nastavení posunu ve smìru Y
IDF_DIRECT3D_TRANSZ,		"translation in Z direction",																		// nastavení posunu ve smìru Z
IDF_DIRECT3D_MAT_GROUP,		"surface",																							// skupina pro nastavení povrchu
IDF_DIRECT3D_COLOR,			"color (-1=internal, -2=default)",																	// nastavení barvy objektu
IDF_DIRECT3D_EMISSIVE,		"emissive color",																					// nastavení barvy svítivosti
IDF_DIRECT3D_POWER,			"dimness (0=off, 5=metal, 50=plastic)",																// nastavení matnosti
IDF_DIRECT3D_SPECULAR,		"reflectance color",																				// nastavení barvy odrazivosti
IDF_DIRECT3D_TEXTURE,		"texture",																							// obrázek textury
IDF_DIRECT3D_TEXTMAP,		"texture mapping",																					// pøíkaz pro mapování textury
IDF_DIRECT3D_TEXTMAP_TYPE,	"projection type (0=flat, 1=cylinder, 2=sphere, 3=chrome, 4=lens)",									// typ projekce mapování
IDF_DIRECT3D_TEXTMAP_OX,	"X coordinate of projection center",																// souøadnice X støedu porjekce mapování
IDF_DIRECT3D_TEXTMAP_OY,	"Y coordinate of projection center",																// souøadnice Y støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_OZ,	"Z coordinate of projection center",																// souøadnice Z støedu projekce mapování
IDF_DIRECT3D_TEXTMAP_RX,	"rotation of projection around X-axis",																// otoèení projekce mapování podle osy Z
IDF_DIRECT3D_TEXTMAP_RY,	"rotation of projection around Y-axis",																// otoèení projekce mapování podle osy X
IDF_DIRECT3D_TEXTMAP_RZ,	"rotation of projection around Z-axis",																// otoèení projekce mapování podle osy Y
IDF_DIRECT3D_TRANSPARENT,	"transparency (1=normal, 11=fire, 20=glass, 54=overlap)",											// nastavení prùhlednosti objektu
IDF_DIRECT3D_ALPHAREF,		"contours (0=normal, 0.5=contours)",																// nastavení referenèní úrovnì alfa kanálu
IDF_DIRECT3D_TEXTMAP_METHOD,"method (0=addresses, 1=vertices, 2=faces)",														// metoda mapování textury
IDF_DIRECT3D_TEXTMAP_OU,	"horizontal origin of texture",																		// poèátek textury vodorovnì
IDF_DIRECT3D_TEXTMAP_OV,	"vertical origin of texture",																		// poèátek textury svisle
IDF_DIRECT3D_TEXTMAP_SU,	"horizontal decrease grade of texture",																// mìøítko textury vodorovnì
IDF_DIRECT3D_TEXTMAP_SV,	"vertical decrease grade of texture",																// mìøítko textury svisle
IDF_DIRECT3D_LIGHT_GROUP,	"lighting",																							// skupina pro ovládání svìtel
IDF_DIRECT3D_LIGHT,			"create new light",																					// vytvoøení svìtla
IDF_DIRECT3D_LIGHT_COLOR,	"light color",																						// nastavení barvy svìtla
IDF_DIRECT3D_LIGHT_TYPE,	"light type (1=point, 2=spot, 3=directional)",														// volba typu svìtla
IDF_DIRECT3D_LIGHT_UMBRA,	"angle of light cone",																				// nastavení úhle kuele svìtla
IDF_DIRECT3D_LIGHT_PENUMBRA,"penumbra angle",																					// nastavení úhle polostínu
IDF_DIRECT3D_LIGHT_RANGE,	"light range",																						// vzdálenost dopadu svìtla
IDF_DIRECT3D_LIGHT_CATTEN,	"light intensity (1=normal)",																		// nastavení intenzity svìtla
IDF_DIRECT3D_LIGHT_LATTEN,	"linear attenuation",																				// lineární zeslabení svìtla
IDF_DIRECT3D_LIGHT_QATTEN,	"quadratic attenuation",																			// kvadratické zeslabení svìtla
IDF_DIRECT3D_PROJECTION,	"projection type (0=persp, 1=ortho, 2=r-persp, 3=r-ortho)",											// nastavení typu projekce
IDF_DIRECT3D_SCENE_GROUP,	"scene",																							// skupina pro øízení scény
IDF_DIRECT3D_SCENE_COLOR,	"scene background color (-1=off, -2=no initialization)",											// nastavení barvy pozadí scény
IDF_DIRECT3D_SCENE_TEXTURE,	"scene background texture",																			// nastavení textury pozadí scény
IDF_DIRECT3D_FOG_COLOR,		"fog color (-1=off)",																				// nastavení barvy mlhy
IDF_DIRECT3D_FOG_MODE,		"fog type (0=lin, 1=exp, 2=quadr, +4=correction)",													// volba typu mlhy
IDF_DIRECT3D_FOG_START,		"start of linear fog",																				// nastavení zaèátku mlhy
IDF_DIRECT3D_FOG_END,		"end of linear fog",																				// nastavení konce mlhy
IDF_DIRECT3D_FOG_DENSITY,	"density of exp. and quadr. fog (0 to 1)",															// nastavení hustoty mlhy
IDF_DIRECT3D_VIEW_FRONT,	"distance of projection plane",																		// nastavení vzdálenosti promítací roviny
IDF_DIRECT3D_VIEW_BACK,		"visual range distance",																			// nastavení vzdálenosti dohledu
IDF_DIRECT3D_UPPER,			"create upper base",																				// vytváøet horní podstavu objektu
IDF_DIRECT3D_LOWER,			"create lower base",																				// vytváøet dolní podstavu objektu
IDF_DIRECT3D_PICK,			"search object",																					// vyhledání objektu
IDF_DIRECT3D_PICK_X,		"X coordinate of point",																			// souøadnice X k vyhledání objektu
IDF_DIRECT3D_PICK_Y,		"Y coordinate of point",																			// souøadnice Y k vyhledání objektu
IDF_DIRECT3D_MINFILTER,		"texture minification filter",																		// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_2DOBJECT,		"2D object",																						// vytvoøení 2D objektu
IDF_DIRECT3D_TERRAIN,		"terrain from picture",																				// vytvoøení terénu z obrázku
IDF_DIRECT3D_LEVEL,			"terrain level",																					// zjištìní úrovnì terénu
IDF_DIRECT3D_LEVEL_X,		"horizontal coordinate",																			// horizontální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_LEVEL_Y,		"vertical coordinate",																				// vertikální souøadnice pro zjištìní úrovnì
IDF_DIRECT3D_EMPTY,			"group",																							// vytvoøení skupiny objektù
IDF_DIRECT3D_SPLITS,		"complexity of object (2 to 100)",																	// nastavení úrovnì sloitosti objektu
IDF_DIRECT3D_ORDER,			"order of rotations (0=XYZ, 1=XZY, 2=YXZ, 3=YZX, 4=ZXY, 5=ZYX)",									// nastavení poøadí provádìnıch rotací
IDF_DIRECT3D_DRIVER,		"driver (0=auto, 1=HAL, 2=TnLHal, 3=REF, 4=RGB, 5=MMX, 6=Ramp)",									// volba ovladaèe
IDF_DIRECT3D_ROTARY,		"rotary object",																					// vytvoøení rotaèního objektu
IDF_DIRECT3D_TERRAIN_MAP,	"terrain from sheet",																				// vytvoøení terénu z plochy
IDF_DIRECT3D_AMBIREF,		"reflection of ambient light (-1=default)",															// nastavení barvy rozptıleného svìtla
IDF_ACTIVE,					"program is active application",																	// program je aktivní aplikací systému Windows
IDF_POLAR_RADIUS,			"distance of point",																				// vıpoèet vzdálenosti bodu
IDF_POLAR_ANGLE,			"angle of point",																					// vıpoèet úhlu bodu
IDF_POLAR_X,				"X coordinate of point",																			// souøadnice X bodu
IDF_POLAR_Y,				"Y coordinate of point",																			// souøadnice Y bodu
IDF_FILE_LOGIC,				"logical value",																					// uloení logické hodnoty do souboru
IDF_DIRECT3D_SMOOTH,		"smoothing of textures (1=no)",																		// stupeò vyhlazení ditheringu textur
IDF_PRECISE_TIMER,			"precise time counter",																				// pøesnı èítaè pro mìøení èasu
IDF_DIRECT3D_AMBIENT,		"ambient light",																					// nastavení rozptıleného svìtla
IDF_DIRECT3D_MAGFILTER,		"texture magnification filter",																		// nastavení filtrace textur
IDF_DIRECT3D_MIPFILTER,		"faraway texture filter",																			// nastavení filtrace textur
IDF_DIRECT3D_OWIREFRAME,	"filling object surfaces",																			// mód vyplòování
IDF_DIRECT3D_OLIGHTON,		"object lighting",																					// mód osvìtlení
IDF_DIRECT3D_OSHADES,		"object smooth shading",																			// mód stínování
IDF_DIRECT3D_OMINFILTER,	"object texture minification filter",																// nastavení filtrace zmenšenıch textur
IDF_DIRECT3D_OMAGFILTER,	"object texture magnification filter",																// nastavení filtrace textur
IDF_DIRECT3D_OMIPFILTER,	"faraway object texture filter",																	// nastavení filtrace textur
IDF_DIRECT3D_OCULLING,		"visible object side (0=both, 1=front, 2=back)",													// zobrazené strany ploch Direct3D
IDF_DIRECT3D_NEW_GROUP,		"create",																							// skupina vytvoøení objektù
IDF_DIRECT3D_NORM,			"object normalization",																				// normalizace 3D objektu
IDF_DIRECT3D_CIRCLE,		"circle",																							// vytvoøení kruhu
IDF_DIRECT3D_TRIANGLE,		"triangle",																							// vytvoøení trojúhelníku
IDF_DIRECT3D_TORUS,			"torus (parameter = diameter 0 to 1)",																// vytvoøení torusu (anuloid)
IDF_DIRECT3D_2DSTATIC,		"static 2D object",																					// vytvoøení statického 2D objektu
IDF_DIRECT3D_HEMISPHERE,	"hemisphere",																						// vytvoøení polokoule
IDF_DIRECT3D_INTERFACE,		"interface (0=auto, 1=GL0, 2=GL1, 4=DX3, 5=DX5, 6=DX6, 7=DX7, 8=DX8)",								// volba rozhraní 3D
IDF_DIRECT3D_ELAPSED,		"elapsed time",																						// èas ubìhlı od posledního renderování
IDF_DIRECT3D_SPEED,			"rendering speed",																					// rychlost renderování
IDF_DIRECT3D_FREE,			"free videomemory",																					// zjištìní volné videopamìti
IDF_DIRECT3D_PICTURE,		"2D picture",																						// vytvoøení 2D obrázku
IDF_DIRECT3D_TEXT_GROUP,	"textures",																							// skupina textur
IDF_DIRECT3D_STAGE,			"stage (0 to 7)",																					// volba stupnì textur
IDF_DIRECT3D_COLOROP,		"color operation (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s barvou
IDF_DIRECT3D_COLORARG1,		"first color argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 1 operace s barvou
IDF_DIRECT3D_COLORARG2,		"second color argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 2 operace s barvou
IDF_DIRECT3D_ALPHAOP,		"alpha operation (1=off, 2=arg1, 3=arg2, 4-6=MOD, 7-11=ADD)",										// volba operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG1,		"first alpha argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 1 operace s alfa kanálem
IDF_DIRECT3D_ALPHAARG2,		"second alpha argument (0=color, 1=result, 2=texture, 3=factor, 16=inversion)",						// volba argumentu 2 operace s alfa kanálem
IDF_DIRECT3D_ADDRESSU,		"horizontal addressing mode (1=repeat, 2=mirror, 3=clamp)",											// volba horizontálního adresování textur
IDF_DIRECT3D_ADDRESSV,		"vertical addressing mode (1=repeat, 2=mirror, 3=clamp)",											// volba vertikálního adresování textur
IDF_DIRECT3D_BIAS,			"blurring of faraway textures (0=default)",															// nastavení stupnì zjemnìní vzdálenıch textur
IDF_DIRECT3D_CONE2,			"truncated cone (parameter = diameter 0 to 1)",														// vytvoøení komolého kuele
IDF_DIRECT3D_TFACTOR,		"color of texture factor",																			// nastavení barvy faktoru textur
IDF_COLOR_SYNTH_ALPHA,		"alpha component (0=transparency to 1=color)",														// alfa sloka funkce pro slouèení barevnıch sloek do barvy
IDF_DIRECT3D_MIPMAPS,		"number of faraway textures (0=all)",																// nastavení poètu úrovní vzdálenıch textur
IDF_DIRECT3D_ZGROUP,		"render group (0-7=objects, 8-11=transparent, 12-15=pictures)",										// nastavení renderovací skupiny
IDF_DIRECT3D_ZSORT,			"depth sort render group",																			// hloubkové tøídìní renderovací skupiny
IDF_DIRECT3D_ZWRITE,		"write depth information",																			// ukládat hloubkovou informaci
IDF_DIRECT3D_ZTEST,			"depth test (1 never, 2 <, 3 =, 4 <=, 5 >, 6 <>, 7 >=, 8 always)",									// provádìnı hloubkovı test
IDF_DIRECT3D_NORMALS,		"calculate normals (parameter = angle for smoothing)",												// pøepoèet normál
IDF_DIRECT3D_RENDER,		"render without displaying",																		// renderování scény bez zobrazení
IDF_TEXT_BLOCK,				"text block",																						// vyjmutí bloku textu
IDF_TEXT_BLOCK_BEGLINE,		"line of the block beginning",																		// øádek poèátku bloku
IDF_TEXT_BLOCK_BEGPOS,		"position of the block beginning",																	// pozice poèátku bloku
IDF_TEXT_BLOCK_ENDLINE,		"line of the block end (-1=end)",																	// øádek konce bloku
IDF_TEXT_BLOCK_ENDPOS,		"position of the block end (-1=end)",																// pozice konce bloku
IDF_WINDOW_POS2,			"actual position 2",																				// aktuální pozice 2 v dialogovém prvku
IDF_BUTTONCHECK_NEW2,		"create switch button",																				// vytvoøení tlaèítkového pøepínaèe dialogového okna
IDF_TABLE_NEW,				"create table (parameter = list of titles)",														// vytvoøení tabulky dialogového okna
IDF_TABLE_WIDTH,			"width of table column",																			// nastavení šíøky sloupce tabulky dialogového okna
IDF_SHADOW_RANGE,			"shadow range (0=off)",																				// nastavení vzdálenosti dopadu stínu 3D objektu
IDF_TABLE_ALIGN,			"align of table column (0=left, 1=right, 2=center)",												// nastavení zarovnávání sloupce tabulky dialogového okna
IDF_HSCROLLBAR_NEW,			"create horizontal scrollbar",																		// vytvoøení horizontálního posuvníku
IDF_VSCROLLBAR_NEW,			"create vertical scrollbar",																		// vytvoøení vertikálního posuvníku
IDF_PICTURE_XCOL,			"exchange colors",																					// zámìna barev v obrázku
IDF_PICTURE_XCOL1,			"first color",																						// první barva k zámìnì barev v obrázku
IDF_PICTURE_XCOL2,			"second color",																						// druhá barva k zámìnì barev v obrázku
IDF_PICTURE_SCOL,			"replace color",																					// náhrada barvy v obrázku
IDF_PICTURE_SCOL1,			"old color",																						// pùvodní barva k náhradì barvy v obrázku
IDF_PICTURE_SCOL2,			"new color",																						// nová barva k náhradì barvy v obrázku
IDF_PRINT_PICTURE,			"print picture",																					// tisk obrázku na tiskárnu
IDF_DIRECT3D_LOD_OBJECT,	"object with reduced detail level (-1=none)",														// definice objektu se sníenou úrovní detailù
IDF_DIRECT3D_LOD_DISTANCE,	"distance for detail level reduction",																// vzdálenost pro sníení úrovnì detailù
IDF_DIRECT3D_MORPH_MODEL,	"add pattern for morphing (-1=reset)",																// pøidání vzoru pro morfování objektu
IDF_DIRECT3D_MORPH_LEVEL,	"morphing stage (0...1...2...)",																	// nastavení stupnì morfování objektu
IDF_DIRECT3D_LENSFLARE,		"lens flare",																						// vytvoøení èoèkového odlesku
IDF_DDE_GROUP,				"dynamic data exchange DDE",																		// skupina obsluhy DDE (dynamická vımìna dat)
IDF_DDE_APP,				"server name/list of servers",																		// jméno aplikace pro DDE, seznam aplikací DDE
IDF_DDE_TOPIC,				"topic name/list of topics",																		// jméno tématu pro DDE, seznam témat DDE
IDF_DDE_ITEM,				"entry name/list of entries",																		// jméno poloky pro DDE, seznam poloek DDE
IDF_DDE_SERVER,				"program provides entry (it is server)",															// program poskytuje poloku ostatním programùm
IDF_DDE_TYPE,				"type of entry (0 to 7, -1=invalid entry)",															// typ poloky pro DDE
IDF_DDE_NUMBER,				"(0) number",																						// èíslo DDE
IDF_DDE_BOOL,				"(1) flag",																							// pøíznak DDE
IDF_DDE_TEXT,				"(2) text",																							// text DDE
IDF_DDE_ICON,				"(3) item",																							// pøedmìt DDE
IDF_DDE_PICTURE,			"(4) picture",																						// obrázek DDE
IDF_DDE_SOUND,				"(5) sound",																						// zvuk DDE
IDF_DDE_MUSIC,				"(6) music",																						// hudba DDE
IDF_DDE_SPRITE,				"(7) sprite",																						// sprajt DDE
IDF_DDE_EXECUTE,			"command to execute",																				// pøíkaz k provedení DDE
IDF_DLL_GROUP,				"DLL libraries",																					// skupina funkcí pro knihovny DLL
IDF_DLL_LOAD,				"load library",																						// naètení knihovny DLL do pamìti
IDF_DLL_FREE,				"free library",																						// uvolnìní knihovny z pamìti
IDF_DLL_IMPORT,				"import function",																					// importování funkce z knihovny
IDF_DLL_IMPORT_LIB,			"library identifier",																				// identifikátor knihovny pro importování funkce
IDF_DLL_IMPORT_NAME,		"function name",																					// jméno importované funkce
IDF_DLL_IMPORT_PAR,			"number of parameters",																				// poèet parametrù importované funkce
IDF_DLL_EXEC,				"execute function",																					// provedení funkce z knihovny DLL
IDF_MEMORY_NEW,				"create memory block",																				// vytvoøení bloku pamìti
IDF_MEMORY_FREE,			"free memory block",																				// uvolnìní bloku pamìti
IDF_MEMORY_RESIZE,			"change size of memory block",																		// zmìna velikosti bloku pamìti
IDF_MEMORY_RESIZE_ADR,		"address of memory block",																			// adresa bloku pamìti
IDF_MEMORY_RESIZE_NEW,		"new size",																							// nová velikost bloku pamìti
IDF_MEMORY_READ,			"read pointer",																						// adresa pro ètení z pamìti
IDF_MEMORY_WRITE,			"write pointer",																					// adresa zápisu do pamìti
IDF_MEMORY_COPY,			"data copy",																						// kopie bloku dat
IDF_MEMORY_COMPARE,			"data comparison",																					// porovnání bloku dat
IDF_MEMORY_BYTES,			"byte with sign",																					// ètení/zápis bajtu se znaménkem
IDF_MEMORY_BYTEU,			"byte without sign",																				// ètení/zápis bajtu bez znaménka
IDF_MEMORY_WORDS,			"word with sign",																					// ètení/zápis slova se znaménkem
IDF_MEMORY_WORDU,			"word without sign",																				// ètení/zápis slova bez znaménka
IDF_MEMORY_3BYTES,			"3-byte with sign",																					// ètení/zápis 3-bajtu se znaménkem
IDF_MEMORY_3BYTEU,			"3-byte without sign",																				// ètení/zápis 3-bajtu bez znaménka
IDF_MEMORY_DWORDS,			"doubleword with sign",																				// ètení/zápis dvouslova se znaménkem
IDF_MEMORY_DWORDU,			"doubleword without sign",																			// ètení/zápis dvouslova bez znaménka
IDF_MEMORY_FLOAT,			"decimal number 4 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_DOUBLE,			"decimal number 8 bytes",																			// ètení/zápis reálného èísla 4 bajty
IDF_MEMORY_BOOL,			"logical value",																					// ètení/zápis logické hodnoty
IDF_MEMORY_TEXT0,			"text terminated by null",																			// ètení/zápis textu zakonèeného nulou
IDF_MEMORY_TEXT0P,			"pointer to text terminated by null",																// ètení/zápis ukazatele na text zakonèenı nulou
IDF_MEMORY_TEXTN,			"text with fixed length",																			// ètení/zápis textu s pevnou délkou
IDF_MEMORY_TEXTN_LEN,		"length of text with fixed length",																	// definice délky textu s pevnou délkou
IDF_MEMORY_LOAD,			"read data from file",																				// ètení dat ze souboru
IDF_MEMORY_SAVE,			"write data to file",																				// zápis dat do souboru
IDF_WINDOW_HANDLE,			"identifier of window element",																		// zjištìní identifikátoru okenního prvku
IDF_DLL_IMPORT_C,			"calling convention C",																				// volací konvence C pro importovanou funkci
IDF_TABS_NEW,				"create tabs",																						// vytvoøení záloek v dialogovém oknì
IDF_INI_GROUP,				"configuration",																					// skupina funkcí pro ukládání konfigurace programu
IDF_INI_FILE,				"configuration fike",																				// jméno konfiguraèního souboru
IDF_INI_SECTION,			"parameter section",																				// název sekce konfiguraèních parametrù
IDF_INI_VALUE,				"parameter name",																					// jméno konfiguraèního parametru
IDF_INI_STRING,				"read/write text prameter",																			// ètení/zápis hodnoty textového konfiguraèního parametru
IDF_INI_NUM,				"read/write integer prameter",																		// ètení/zápis hodnoty celoèíselného konfiguraèního parametru
IDF_REG_KEY,				"key group (1=CURRENT_USER, 2=LOCAL_MACHINE)",														// urèení skupiny klíèù registrù
IDF_REG_SUBKEY,				"key name",																							// plnı mázev klíèe registrù
IDF_REG_VALUE,				"entry name",																						// název datové poloky
IDF_REG_STRING,				"read/write text entry",																			// ètení/zápis textové poloky registrù
IDF_REG_NUM,				"read/write integer entry",																			// ètení/zápis celoèíselné poloky registrù
IDF_MEMORY_3D,				"create 3D object from memory blocks",																// vytvoøení 3D objektu z pamìovıch blokù
IDF_MEMORY_3D_VN,			"number of vertices",																				// poèet vrcholù 3D objektu
IDF_MEMORY_3D_VERT,			"vertices",																							// buffer vrcholù 3D objektu
IDF_MEMORY_3D_NORM,			"normals (0=auto)",																					// buffer normál 3D objektu
IDF_MEMORY_3D_TEXT,			"texture mapping (0=none)",																			// buffer mapování textur 3D objektu
IDF_MEMORY_3D_COL,			"colors (0=none)",																					// buffer barev 3D objektu
IDF_MEMORY_3D_FN,			"number of faces",																					// poèet plošek 3D objektu
IDF_MEMORY_3D_FACE,			"faces",																							// buffer plošek 3D objektu
IDF_DIRECT3D_TEXTURE_FILE,	"texture from file",																				// naètení textury ze souboru
IDF_DIRECT3D_MEMORY,		"memory block from 3D object",																		// export 3D objektu do pamìového bloku
IDF_DIRECT3D_CHILD,			"find child (-1=first, -2=parent)",																	// nalezení prvního/dalšího potomka 3D objektu
IDF_UDP_GROUP,				"UDP packets",																						// skupina pro komunikaci pomocí UDP paketù
IDF_UDP_SEND_IP,			"sending IP address",																				// nastavení cílové IP adresy pro odesílané UDP pakety
IDF_UDP_SEND_PORT,			"sending port (-1=close sending)",																	// nastavení cílového portu pro odesílané UDP pakety
IDF_UDP_REC_SIZE,			"size of receiving buffer",																			// nastavení velikosti pøijímacího UDP bufferu
IDF_UDP_REC_IP,				"received/receiving IP address",																	// zjištìní IP adresy naposledy pøijatého UDP paketu, pøijímací IP adresa
IDF_UDP_REC_PORT,			"received/receiving port (-1=close receiving)",														// port pro pøíjem UDP paketù
IDF_UDP_MEM,				"binary packet",																					// pøíjem/odeslání binárního UDP paketu
IDF_UDP_TEXT,				"text packet",																						// pøíjem/odeslání textového UDP paketu
