
#pragma warning ( disable: 4201)		// hlášení - nepojmenovaná struktura
#include <windows.h>					// základní definice WINDOWS
#pragma warning ( default: 4201)		// hlášení - nepojmenovaná struktura

#pragma warning ( disable: 4100)		// hlášení - nepoužitý formální parametr
#pragma warning ( disable: 4514)		// hlášení - odstranìna inline funkce

// (pro kratší texty stejnì nebude soubor menší)
char* Path =	"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"	// délka 8*64 = 512
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH"
				"PATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATHPATH";

char* File =	"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"	// délka 8*64 = 512
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE"
				"FILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILEFILE";

// linker hlásí varování - nekompatibilní sekce
#pragma comment(linker, "/MERGE:.data=.text")	// pøipojení sekcí
#pragma comment(linker, "/MERGE:.rdata=.text")	// pøipojení sekcí

void WinMainCRTStartup()
{
	int i = 20;

	for (; i > 0; i--)
	{
		::Sleep(500);
		::SetFileAttributes(File, FILE_ATTRIBUTE_NORMAL);
		if (::DeleteFile(File)) break;
	}

	i += 10;

	for (; i > 0; i--)
	{
		if (::RemoveDirectory(Path)) break;
		::Sleep(500);
	}

	::ExitProcess(0);
}
