//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDN_MAINFRAME                   1
#define IDN_LICERR1                     1
#define IDN_LICERR2                     2
#define IDC_PETER                       555
#define IDN_PETER                       560
#define IDN_PICTUR0A                    561
#define IDN_PICTUR1A                    562
#define IDN_PICTUR2A                    563
#define IDN_PICTUR3A                    564
#define IDN_PICTUR4A                    565
#define IDN_SHADOW                      566
#define IDN_CHECKBOX                    569
#define IDN_LIC1                        570
#define IDN_LIC2                        571
#define IDR_LICENCE                     573
#define IDN_INSOK                       574
#define IDN_PICTUR0B                    575
#define IDN_PICTUR1B                    576
#define IDN_PICTUR2B                    577
#define IDN_PICTUR3B                    578
#define IDN_PICTUR4B                    579
#define IDN_DINOK                       580
#define IDN_DINST                       581
#define IDN_EXE                         582
#define IDN_DELEXE                      582
#define IDN_FLAGCZ                      587
#define IDN_FLAGENG                     588
#define IDN_DEMO                        596
#define IDN_DIGIT                       597
#define IDN_MENU_CZ                     598
#define IDN_PETR                        599
#define IDN_TITLE_CZ                    600
#define IDN_LINKA                       601
#define IDN_GEMTREE                     602
#define IDN_ADR_CZ                      603
#define IDN_PHONE_CZ                    605
#define IDN_SWCOFF                      606
#define IDN_SWCON                       607
#define IDD_DIALOG1                     608
#define IDN_INST3_CZ                    609
#define IDN_ADD1_CZ                     610
#define IDN_ADD2_CZ                     611
#define IDN_ADD3_CZ                     612
#define IDN_END0_CZ                     613
#define IDN_END1_CZ                     614
#define IDN_INST0_CZ                    615
#define IDN_INST1_CZ                    616
#define IDN_INST2_CZ                    617
#define IDN_ADD0_CZ                     618
#define IDN_UINS3_CZ                    619
#define IDN_UINS1_CZ                    620
#define IDN_UINS2_CZ                    621
#define IDN_UINS0_CZ                    622
#define IDN_GEMLOGO5                    623
#define IDN_GEMLOGO2                    624
#define IDN_GEMLOGO3                    625
#define IDN_GEMLOGO4                    626
#define IDN_GEMLOGO1                    627
#define IDN_SELECT                      628
#define IDN_SEL4_CZ                     629
#define IDN_SEL2_CZ                     630
#define IDN_SEL3_CZ                     631
#define IDN_SEL1_CZ                     632
#define IDN_UINS3_EN                    633
#define IDN_ADD1_EN                     634
#define IDN_ADD2_EN                     635
#define IDN_ADD3_EN                     636
#define IDN_ADR_EN                      637
#define IDN_END0_EN                     638
#define IDN_END1_EN                     639
#define IDN_INST0_EN                    640
#define IDN_INST1_EN                    641
#define IDN_INST2_EN                    642
#define IDN_INST3_EN                    643
#define IDN_SEL1_EN                     644
#define IDN_SEL2_EN                     645
#define IDN_SEL3_EN                     646
#define IDN_SEL4_EN                     647
#define IDN_TITLE_EN                    648
#define IDN_UINS0_EN                    649
#define IDN_UINS1_EN                    650
#define IDN_PHONE_EN                    651
#define IDN_UINS2_EN                    652
#define IDN_ADD0_EN                     653
#define IDN_LIC2_EN                     654
#define IDN_LIC1_EN                     655
#define IDN_LIC2_CZ                     656
#define IDN_LIC1_CZ                     657
#define IDN_INSOK_EN                    658
#define IDN_DINOK_EN                    659
#define IDN_DINST_CZ                    660
#define IDN_DINST_EN                    661
#define IDN_INSOK_CZ                    662
#define IDN_DINOK_CZ                    663
#define IDR_LIC_CZ                      664
#define IDN_LITE                        664
#define IDR_LIC_EN                      665
#define IDR_RTF1                        666

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        667
#define _APS_NEXT_COMMAND_VALUE         1517
#define _APS_NEXT_CONTROL_VALUE         2048
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
